### ISSUE TITLE
species distribution fixes

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#10]
>
> 5. This count also looks a bit odd, Val? I would assume that number conserved in fungi will be ≤eukaryotes
> but cdc2:
> conserved in fungi 	
> 	
> 	4564
> conserved in eukaryotes 	
> 	
> 	4482

Yeah, there are quite a lot of proteins, which when I did this, were only present in pombe (but no other fungi) and metazoa, like this one:

http://www.pombase.org/spombe/result/SPBC26H8.13c
http://www.ebi.ac.uk/interpro/entry/IPR022773/taxonomy

and this one
http://www.pombase.org/spombe/result/SPCC18.17c

So there really was no broad fungal conservation. Now there are japonicus and octospous for many.

Others I need to fix.....

Original comment by: ValWood

**Comment by ValWood** [comment]
transferred to 
https://github.com/pombase/curation/issues/810
