### ISSUE TITLE
dephosphorylation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1013]
As this is an assay, could it be used for an MF annotation to phophatase, instead of BP to dephosphorylation for 
pho1,pho4?

curs/dad0d98fa4da533e

**Comment by ValWood** [comment]
Ah, I think this might be one of those where it isn't clear if pho1/4 are directly phosphorylating so this would be correct...

**Comment by ValWood** [comment]
although should it be "protein dephosphorylation?"

**Comment by mah11** [comment]
No, the paper is about acid phosphatase, which is not restricted to phosphoprotein substrates.

**Comment by ValWood** [comment]
Actually, I thought this was one of the ones with  a downstream protein target, it isn't.

I this case as they have  assayed phosphatase activity in a mutant I would make
a MF to "phosphatase activity" with IMP rather than  BP to 	"dephosphorylation"
