### ISSUE TITLE
Nuf2, Csi1 chromsomes segregation work

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1017]
Csi1 --- is a kinetochore-SPB connector in mitotic interphase (Hou et al., 2012),

Nuf2-- which connects the cen- tromeres to the SPB, disappears at the early meiotic prophase and releases the centromeres from the SPB (Asakawa et al., 2005; Hayashi et al., 2006.

**Comment by ValWood** [comment]
transferred to
https://github.com/pombase/curation/issues/1017

**Comment by mah11** [comment]
links to self - what ticket was this transferred to?

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/1104
