### ISSUE TITLE
FYPO soft check required 'increased protein level'

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1018]
I think we are splitting lots of 
 'increased protein level'
 'increased protein level during vegetative growth'

![move down](https://cloud.githubusercontent.com/assets/7359272/17867209/7cd1c81a-68a1-11e6-8838-5f7bed5636b1.jpg)

**Comment by mah11** [comment]
I know you know how to do this yourself. It works the same way as the GO soft checks, and the file is in the same directory.

Furthermore, in this case there is nothing to do here. FYPO:0000836 increased protein level is already in the file, and is reported in the soft checks log.

**Comment by ValWood** [comment]
You are right. I didn't want to stick things in there without you approval.
