### ISSUE TITLE
alp4 duplicate annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1019]
![alp4 looks same](https://cloud.githubusercontent.com/assets/7359272/17869184/0c92f9d0-68aa-11e6-8a88-aa2b13baed48.jpg)

I think this is fixed

**Comment by ValWood** [comment]
There are still 2 annotations on the gene page. This isn't critical, but I can't see why. I can only see a single annotation from this paper.
@kimrutherford  what do you see in the chado database for the release?

**Comment by mah11** [comment]
A single annotation line gets written to the GAF now, but there are two in the v61 GAF.

latest build has:
    PomBase	SPBC365.15	alp4		GO:0031122	PMID:11080156	IMP		P	gamma tubulin complex Spc97/GCP2 subunit Alp4		protein	taxon:4896	20070725	PomBase

The v61 release also has a line that differs only by the date.

presumably all will be well on that distant horizon when v62 (or whatever we call it by then) goes live

**Comment by ValWood** [comment]
This is fixed then....
