### ISSUE TITLE
srw1 check annotation "pheromone signalling"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1023]
Looks odd.... (its an APC co-activator?)

**Comment by Antonialock** [comment]
I celaned the GO terms from the session upso this will go away.

It does seem like signalling is exerted via srw1 though...
"Ste9 acts in collaboration with Rum1 in response to nitrogen deprivation to downregulate the Cdc2/Cdc13 activity supporting G1 arrest."
http://www.tandfonline.com/doi/pdf/10.4161/cc.5.8.2647?needAccess=true

**Comment by ValWood** [comment]
I guess it might turn the pathway off by protein degradation....I don't know if this is signalling though...? its like the APC degrades cdc13 but we don't think of that as signalling. This will probably only make sense if we LEGO it.... I  can't even remember the stuff I did know about this any longer.....

**Comment by Antonialock** [comment]
Ok, I thought srw1 might have some "special" role in mediating this signalling, like the example with the RNA pol II subunit that mediates certain processes - not sure if it then should be annotated to it? There's no evidence for that though here...it will go away...
