### ISSUE TITLE
iron sulphur assembly project

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1032]
- [x] annotate pombe gene products (all published papers)
-  [ ]  Make table of proteins pombe/human/cerevisiae
  - [ ]  table needs extending to add recent new human 
  - [ ] Can we find pombe/cereivsiae orthologs for these?
-  [x] Create LEGO model for pombe  (VW, march 2018 : it should be possible to autogenerate the model)
- [ ] Present LEGO model on Noctua call
- [ ] Any iterations improvements required 
- [ ] Use LEGO model as a template for other species (human/ Mouse / cerevisiae)
- [ ] Identify and correct ontology errors
- [ ] Summarize ontology fixes
  1 corrected parent term x etc
- [ ] Ontology improvements
  - Can you make other ontology improvements?  (function process links)
  - if F=P links can't be added in the ontology, add the extensions part_of
- [ ] The definitions of the core terms might need to be refined....
- [ ] Correct erroneously annotated pombe pathway proteins
  - [ ] summarize fixes
- [ ] Correct erroneously annotated  proteins other species
  - [ ] Open Protein2GO tickets 
  - [ ] summarize fixes (e.g. SDHF1 human removed x)
- [ ] Correct any erroneous mappings (InterPro, SPKW)
- [ ] Use matrix to identify   reamaining outliers, remove
- [ ]  Use PAINT  to annotate pathway across all species 
- [ ] Can we do anything with phenotype data (pathway or targets)? Angeli etc
- [ ] Plot inviability phenotypes onto pathway (can distinguish  linear parts of pathway and any redundancy...might be able to figure  out   something about targets with this ... where the pathway branches, we would expect chaperones for essential targets to be essential
  11/16 pathway members are essential  19/43 targets are essential
- [ ]  Suggest  new improved mappings for InterPro
- [ ] Do string  for main species and look at close interactors
- [ ] Possible function predictions?

Paper:  A comprehensive protocol for improving species-wide curation using iron sulfur cluster assembly pathway as a model

Introduction
- [ ] Describe pathway (summarize with figure) and disease associations

Methods
- [ ] Describe curation protocol in a way that it can be implemented for other pathways /species

Results
- [ ]  Summarize final annotations (cytoscape figure?)
- [ ]  Number of papers curated
- [ ]  Summarize corrections
  Resources provided :
- [ ]  Number of manual GO annotations (pombe and human). 
- [ ] LEGO model
- [ ]  SBML  format model

New knowledge?
- [ ]  Possible function predictions (one possible but may have more from interactions and enrichments)
- [ ] Anything that can be gleaned from targets?  or species distribution?

Conclusions
- [ ]  advantages of annotating by pathway

**Comment by Antonialock** [comment]
I'm very good at "tidying away" (chucking) old notes so thought I'd upload this here for ref

![img-2501](https://user-images.githubusercontent.com/12727506/37856420-4c8ab51e-2eec-11e8-91af-32dcc7d2c5c8.JPG)

**Comment by ValWood** [comment]
Great to do this- It really should be part of the archive!

**Comment by Antonialock** [comment]
it makes it so much easier. This will be my approach when I dare to tackle conjugation ;-)

**Comment by Antonialock** [comment]
just such a huge process

**Comment by Antonialock** [comment]
FYI the gene products annotated to cytosolic transfer / assembly could be a bit fluid - the process isn't really well mapped out yet

**Comment by Antonialock** [comment]
also I guess there are likely to be more players in mitochondrial 2fe2s transfer

**Comment by ValWood** [comment]
I still think this is likely to do with  iron transfer...we shall see....

https://www.pombase.org/gene/SPBC18E5.10

**Comment by Antonialock** [comment]
I looked for it, couldn't find anything not involving the cyt complex pombe doesn't have

**Comment by Antonialock** [comment]
even more annoyingly I think the protein that transfers clusters to NDUFV1 (IND1) is not conserved to pombe

**Comment by Antonialock** [comment]
(I think I just did diopt so didn't look hard)

**Comment by ValWood** [comment]
We are calling this one done
