### ISSUE TITLE
PECO logs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1034]
@Antonialock  do you need to do something here?

warning in 466ed4e946c15c3f: condition 'ID:0000000' isn't a PECO term ID
warning in 466ed4e946c15c3f: condition 'ID:0000000' isn't a PECO term ID
warning in 466ed4e946c15c3f: condition 'ID:0000000' isn't a PECO term ID

**Comment by mah11** [comment]
I fixed this a week or so ago

**Comment by ValWood** [comment]
OK I'm still confused. If this was fixed a week ago but it was still in the new logs from lat night.
Does something else need to happen somewhere?

**Comment by mah11** [comment]
If it hasn't happened automagically, I guess someone has to go in and update in the session. I"ll do it now, since this has got me on the subject.

**Comment by mah11** [comment]
Actually, the rogue ID was for queuosine (now PECO:0000299), but the expt used queuine. I'll add to PECO and deploy tomorrow.
