### ISSUE TITLE
mus81 checkpoint

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1037]
I think we already checked this but I noticed again that mus81 has 2 checkpoint
![deletion of mus81](https://cloud.githubusercontent.com/assets/7359272/18226167/e197dfc4-71fb-11e6-82e1-6992b2842061.jpg)
 annotations even though if deleted the checkpoint is still active which seemed odd...will take another look

**Comment by Antonialock** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/21084840

**Comment by ValWood** [comment]
Looks like a response, rather than  being part of the checkpoint?

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/921
duplicated in
