### ISSUE TITLE
Log file errors, possibly something needs updating?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1040]
more the one relation cvterm returned for part_of:
terms: BFO:0000050 and _global:part_of

warning in 466ed4e946c15c3f: condition 'ID:0000000' isn't a PECO term ID
warning in 466ed4e946c15c3f: condition 'ID:0000000' isn't a PECO term ID
warning in 466ed4e946c15c3f: condition 'ID:0000000' isn't a PECO term ID

warning in a75082ad0a8ac32d: can't find term with ID: PATO:0000323
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0000323
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0000323
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0000323
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0000323
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0000323
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0000323
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0000323
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0000323
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0001261
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0001261
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0001261
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0001262
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0001262
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0001262
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0001262
warning in a75082ad0a8ac32d: can't find term with ID: PATO:0001262

warning in 3aac4505bb3ec2e8: in annotation extension for SPAC22A12.15c.1, can't parse identifier: 10 
(I already reported this one to Kim as I couldn't see a problem https://github.com/pombase/pombase-chado/issues/573)

genotype SPAC4D7.11-DUMMY has no alleles
genotype SPAC1486.02c-DUMMY has no alleles
genotype SPAC20H4.02-DUMMY has no alleles

**Comment by kimrutherford** [comment]
The PATO warnings will go away when I fix this: pombase/pombase-chado#571

**Comment by mah11** [comment]
the part not covered by Kim's Chado ticket is in #1034
