### ISSUE TITLE
G2_M transition How to define the core control network

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1047]
Overview, tasks and issues related to modelling G2/M transition

@JackyVH

**Comment by ValWood** [comment]
At the cell cycle meeting, we  discuused the G2/M transition and which genes/pathways were part of "regulation of the transition"

From the persective of GO this would include any gene products which positively or negatively regulated the G2/M transtion by some menchanism

In GO regulation is defined:
Any process that modulates the frequency, rate or extent of a biological process. Biological processes are regulated by many means; examples include the control of gene expression, protein modification or interaction with a protein or substrate molecule.

Note that this does not include gene product which *AFFECT* the G2/M transition. For example a gene which when mutated or deleted causes a defect which results in problems with the cell cycle would not be regulating the transition. This includes gene products which when mutated cause a problem which results in 'checkpoint activation". These gene products are NOT activating the checkpoint per se. The gene product which activates the checkpoint is the 'sensor'  which detects the problem caused by the defective gene product.

**Comment by ValWood** [comment]
At the LEGO meeting Jacky was concerned that this was too broad for "G2/M transition"

I still think its correct, but there might be a case for a term to represent the 'core mitotic control network, if we can define it:

[Mitotic control network.pdf](https://github.com/pombase/curation/files/467194/Mitotic.control.network.pdf)


JAcky, I think that here, by labelling the  DNA damage checkpoints as inputs you are implicating them in regulation

**Comment by ValWood** [comment]
So I think this is what Jacky thinks should be "regulation of G2M"

![g2_m_regulation](https://cloud.githubusercontent.com/assets/7359272/18444601/df7da27e-7911-11e6-9747-9c3c7a526fa5.jpg)


This is what I have currently 



![g2_m](https://cloud.githubusercontent.com/assets/7359272/18444623/fa5df2ce-7911-11e6-98a7-d75c2e841641.jpg)


These  might need to be included:
Check whether upstream or downstream of the checkpoint signalling
rfc2	DNA replication factor C complex subunit Rfc2 
rad17	RFC related checkpoint protein Rad17  (Clamp loader)
? hsp9	heat shock protein Hsp9
ctp1	CtIP-related endonuclease  (SENSOR???)

Check
? ppa2	serine/threonine protein phosphatase Ppa2 
? cdc14	SIN component Cdc14 
?cmk1	calcium/calmodulin-dependent protein kinase Cmk1 

skb1?

**Comment by ValWood** [comment]
New review
Signaling Pathways that Regulate Cell Division
Nicholas Rhind1 and Paul Russell2
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3475169/


This review puts the replication checkpoint as a
![g2_m signalling](https://cloud.githubusercontent.com/assets/7359272/18445353/15ef0138-7915-11e6-920c-1560399bf3e8.jpg)

**Comment by ValWood** [comment]
This is the list of genes presented as major cell cycle regulators (I have annotated this list with the 'transition(s).

![genes](https://cloud.githubusercontent.com/assets/7359272/18445506/d1085c94-7915-11e6-8639-b07b962091b6.jpg)

**Comment by ValWood** [comment]
Jacky's Concern:
Also we thought that biologically there is no difference but for the GO  it is useful to differentiate between these otherwise everything would be regulating the G2-M transition e.g. To take an extreme view a transporter affecting nutrient levels would regulate the G2-M transition

When I was doing the haploinsufficient  screen I picked up prp19 which is a major regulator of splicing as delaying the G2-M transition.   When prp19 is deleted the cells are elongated and cannot undergo the G2-M transition and when gene copy number is reduced in a diploid it delays the transition suggesting that the level of prp19 is important for G2-M ( most genes manage OK with just one copy and  seem to have no effect on the cell).  This is similar to saying Chk1 regulates the G2-M transition but for Chk1 there is no evidence that changing the level of activity affects the timing of G2-M, though as far as I know this has not be tested in the presence of DNA damage.   A rate limiting step  is just one way of looking at it  and prp19 looks as if it is rate limiting for the G2-M transition, however I’m not sure I would say it regulates the G2-M transition. So should the mitotic control network extend to include a rate limiting step that affect the timing of G2-M or should it end at the point in which it impinges on the mitotic control e.g. With prp19 should this be included or only the gene activity which it feeds into in the mitotic control network.

**Comment by ValWood** [comment]
Response to Jacky's concern:

This isn't such a problem.
We would not annotate prp19 to G/2 M transition based only on the fact that the deletion  is elongated, and  the transition is delayed when copy number is reduced in a diploid.

We have 320 genes annotated
FYPO:0001492 - viable elongated vegetative cell)
FYPO:0001490 - inviable elongated vegetative cell
these include ribosomal proteins
lots of splicing factors cwf2,20,15,23,  prp 11,12,16,18,19,24
mRNA decapping complex
replication  proteins
etc, etc

So clearly the phenotype 'elongated vegetative' is not 'selective' enough on its own to indicate  G2/M transition regulation.   
We would say that these are NOT involved in the regulation of G2/M, because we have no evidence that there are regulating this process in a *normal* cell.  The "cell cycle delay" phenotype is only apparent because  some upstream process which the cell cycle regulation depends on has been compromised. This may either cause a problem which  one of the checkpoints can detect and the checkpoint pathway is activated. However we would not annotate anything upstream of the "checkpoint sensor", and the possibly the structural change which activates the sensor to the checkpoint, so  all genes with these phenotypes would not become annotated to "regulation of the G2/M transition.
Alternatively  the phenotype could be an problem directly affecting the gene products required to complete the cell cycle (for example failing to remove an intron in a required gene product). Again we do not annotate this to regulation, because in a normal cell when the  WT gene product for the splicing factor is present, this gene product  does not have a role in the regulation of the transition. If it IS later demonstrated that the splicing IS regulated to control the cell cycle we would need to review this.

So, initially we would *only* annotate a phenotype.
We need further information (more detailed experiments) to  make a GO term annotation. 
All we would annotate to the "regulation of transition" are the gene products  considered to regulate (positively or negatively)  when the cell cycle occurs in a normal cell (this can include situations where the cell is dealing with a problem like DNA damage).

Currently  the gene s we have annotated  to "regulation of the G2/M transition) are the ones in the esyN figure above PLUS the list underneath the figure which I want to check as they are not currently linked in to the network....


So, my plan is

- [ ] Check that the network includes ALL gene products which would be considered to be regulating the transition, and build them into the model above
- [ ]  Figure out what is common about the subset which  are considered to be the "Mitotic control network"

A question for jacky
- [ ]  I am wondering if the difference is to do with timing.
Most of the checkpoints can occur during Interphase, and seem to result in the sequestering of cdc25 in the cytoplasm.

and then, presumably to achieve full Cdk activity cdc25 must be nuclear, so I was wondering 
if the  part that you consider to be the "mitotic control network" are all occurring after cdc25 is nuclear localized?

**Comment by JackyVH** [comment]
Hi Val I'm going to digest all of this and will get back to you.  And yes according to the diagram I sent I do think Chk1 and Cds1 regulate the mitotic control network. I guess that many gene functions have a regulatory aspect of their function and in some situations this is has more importance than other times which is what I would say for chk1 and cds1. For other gene functions they nearly always have a major regulatory effect. I think what I m trying to distinguish  what has the major effect (i.e. determines the timing/rate of a process) and how we differentiate this from all the other regulation of the process but lets talk about it when I've had a look at it all. Jacky

**Comment by ValWood** [comment]
Related tickets
Questions for experts
https://github.com/pombase/curation/issues/1049

**Comment by ValWood** [comment]
this is my current G2/M

![g2 m](https://cloud.githubusercontent.com/assets/7359272/23817233/692f943c-05e9-11e7-9212-456da112a789.jpg)

**Comment by ValWood** [comment]
now part of https://github.com/pombase/curation/issues/2900
