### ISSUE TITLE
GO annotation of GPI anchored proteins

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#105]
should be annoted to GPI-anchored proteins should be annotated to GO:0031225 \(possibly other terms\)
I don't know if this is the case...

Original comment by: ValWood

**Comment by ValWood** [comment]
these 12 have
MOD:00818 - glycosylphosphatidylinositolated residue
but not GO:0031225 - anchored component of membrane

SPAC821.09	eng1	I	endo-1,3-beta-glucanase Eng1
SPAC19G12.16c	adg2	I	conserved fungal protein Adg2 
SPBP4G3.02	pho1	II	acid phosphatase Pho1 
SPCC1223.12c	meu10	III	GPI anchored cell surface protein involved in ascospore wall assembly Meu10 
SPAC2E1P3.05c	SPAC2E1P3.05c	I	fungal cellulose binding domain protein 
SPAC1039.11c	gto1	I	alpha-glucosidase (predicted) 
SPAC750.05c	SPAC750.05c	I	S. pombe specific 5Tm protein family 
SPAC1F5.08c	yam8	I	stretch-activated calcium ion channel Yam8 [Source:PomBase;Acc:SPAC1F5.08c]	protein_coding	1	275089	276661
SPBC1E8.05	SPBC1E8.05	II	conserved fungal protein [Source:PomBase;Acc:SPBC1E8.05]	protein_coding	1	1970612	1972799
SPAPJ760.03c	adg1	I	Schizosaccharomyces specific protein Adg1 
SPAC17A5.04c	mde10	I	spore wall assembly ADAM family peptidase Mde10 
SPAC1A6.03c	SPAC1A6.03c	I	phospholipase (predicted)

**Comment by ValWood** [comment]
This wouldn't make sense as  they are more likely to be attached to cell wall. I tidied some annotations replaced IEAs removed NAS etc
