### ISSUE TITLE
ssp1 annotation check PMID: 22375066 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1050]
This paper is done but has this MF  mentioned in abstract is not annotated

As in animal cells, the fission yeast CaMKK ortholog (Ssp1) phosphorylates and activates the catalytic subunit of AMPK (Ssp2) in its activation loop (Thr189) when cells are starved for nitrogen or glucose.

**Comment by Antonialock** [comment]
in this paper there is evidence that ssp1 functions upstream of phosphorylation of ssp2, but there is no evidence for a physical interaction between them. There is nothing on the gene pages either or else I would IMP this annotation.

"suggesting that Ssp2 is phosphorylated in vivo on Thr189 and that Ssp1 could be the kinase responsible for this phosphorylation"

**Comment by ValWood** [comment]
Oh yeah its all genetics!
