### ISSUE TITLE
cmk1 annotation priority

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1053]
we dont have cdc25 as a substrate of cmk1?

![cmk1](https://cloud.githubusercontent.com/assets/7359272/18473277/f3221c2c-79b3-11e6-8744-64f507833bee.jpg)

**Comment by ValWood** [comment]
and
Cmk1 is first phosphorylated and activated by the newly identified kinase CaMKK2 homologue, Ckk2

**Comment by ValWood** [comment]
Actually its possible that the annotation are there, on the processes. I don't know if the server error for the taxon restricted processes affects all annotations for an aspect of just the taxon restricted one. Will wait for this one.

**Comment by Antonialock** [comment]
They don't show this...there's just an IGI

**Comment by ValWood** [comment]
OK so they know that ckk2 is downstream of cmk1 only?

they actually call it
calmodulin-dependent kinase kinase, I guess that comes from similarity.

this is an example where we can only capture the relationship with 
"protein phosphorylation" term.

**Comment by Antonialock** [comment]
cmk1 is somewhere downstream of ckk2

**Comment by ValWood** [comment]
yep ;)
