### ISSUE TITLE
check term and annotations "metaphase arrest with short spindle"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1055]
I suspect this is because this phenotype is oftn reported as

metaphase arrest with short spindle

FYPO:0004532 - abnormal cell cycle arrest in mitotic M phase with abnormal spindle

However, short spindle is 'normal for metaphase'

Check annotations (after update).
consider filter

**Comment by ValWood** [comment]
Also check, I think parent is?
FYPO:0000620	abnormal cell cycle arrest in mitotic metaphase

**Comment by mah11** [comment]
I'll fix the dodgy link (erroneous has_part, probably copied by mistake).

**Comment by ValWood** [comment]
ok, sorry its 'wrong tracker'

**Comment by ValWood** [comment]
transferred to 
https://github.com/pombase/curation/issues/1100
