### ISSUE TITLE
Oh dear, some reconfiguring

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1058]
I just remembered that historically we have used  "inhibited_by" dfor chamicals.
I have a feeling that this is one of those incorrect usage of an extension.

I think its useful information, but we might need to store it elsewhere?

https://github.com/pombase/canto/issues/1248

**Comment by mah11** [comment]
> we have used "inhibited_by" for chemicals.

This is correct.

http://wiki.geneontology.org/index.php/Annotation_Extension_Relation:inhibited_by

**Comment by ValWood** [comment]
Ah OK, I thought it was one of the ones that we put in but David-O-S said isn't correct. If it is can worry about it later...

**Comment by mah11** [comment]
The documentation DO-S linked to has material on using activated_by and inhibited_by to connect MFs with CHEBI terms. There's no hint that they're deprecated (whereas a few other relations do have notes saying they may be deprecated), so we won't have to change anything for quite some time.
