### ISSUE TITLE
priority paper Ppk11 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1064]
- [ ]  Fission yeast germinal center (GC) kinase Ppk11 interacts with Pmo25 and plays an auxiliary role in concert with the morphogenesis Orb6 network (MOR) in cell morphogenesis.
PMID: 20826805

(NO published papers annotated for ppk11)

**Comment by Antonialock** [comment]
Done. It will get the annotation
regulation of establishment or maintenance of bipolar cell polarity regulating cell shape 

ppk11 seems to play a minor role in this pathway:
ppk11 physically interacts with pmo25 
ppk11 deletion mutants have less pmo25 at the cell division site. 
This is not so important under optimal conditions but becomes important when cells are stressed. 
The phenotype of MOR mutants is excaberated by ppk11-delta.

**Comment by ValWood** [comment]
Great!
