### ISSUE TITLE
create general pombase GitHub account

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1069]
With helpdesk as collector...

**Comment by mah11** [comment]
testing @pombase-admin

**Comment by mah11** [comment]
I found an old bit of email saying that the pombase-admin account is connected with the helpdesk email, but Kim has disabled notifications from that account. It's "watching" some of our trackers and was spawning more helpdesk tickets than we wanted. That must be why my little test earlier today didn't create a helpdesk ticket.

So it might work to remove pombase-admin from the list of watchers on pombase/curation and pombase/website, and then re-enable notifications so we can use the account for GO and the like. (I think Kim would have to do the re-enabling.)

I did try, and GitHub won't let me add a second account with the same email address.

**Comment by mah11** [comment]
@kimrutherford

**Comment by ValWood** [comment]
I forgot why we were doing this :)

**Comment by mah11** [comment]
so GO could have a single account to point to instead of having to tag all three of us in tickets relevant to pombase

**Comment by ValWood** [comment]
This seems to be waiting for something, and I'm not sure what?

@mah11 @kimrutherford

**Comment by kimrutherford** [comment]
I've made the changes suggested by Midori.

@pombase-admin

**Comment by kimrutherford** [comment]
> I've made the changes suggested by Midori.

Turns out I didn't.  pombase-admin can't use the address "helpdesk@pombase.org" because the fypoadmin account is already using it.

**Comment by mah11** [comment]
Hmm. I don't know anything about the fypoadmin account other than what I can see on its [people page](https://github.com/orgs/pombase/people/fypoadmin) (hey, I just work on FYPO ;) ).

I think if someone can log into the fypoadmin account, they could change its email address? @kimrutherford, do you have a password for fypoadmin? I don't; I didn't create it ...

If that doesn't work, I'm stumped.

**Comment by ValWood** [comment]
@kimrutherford

**Comment by kimrutherford** [comment]
> I think if someone can log into the fypoadmin account, they could change its email address? @kimrutherford, do you have a password for fypoadmin? I don't; I didn't create it ...

I can't remember why I created the fypoadmin account.  It must have seemed like a good idea at the time.  It's not used for anything.

> pombase-admin can't use the address "helpdesk@pombase.org" because the fypoadmin account is already using it.

Right, after a bit of thrashing around I think that's fixed now and hopefully pombase-admin works as expected.
As a test: @pombase-admin 

> With helpdesk as collector...

We could use staff@pombase.org instead if we get too many help desk tickets.

**Comment by kimrutherford** [comment]
> We could use staff@pombase.org instead if we get too many help desk tickets.

We were getting too many helpdesk tickets so I've changed to use staff@pombase.org.  :-)

But at least we now know that @pombase-admin works.

**Comment by kimrutherford** [comment]
I had the settings wrongs for notifications but I think it's OK now.

**Comment by mah11** [comment]
I did a pull request to add @pombase-admin to GO's contact list.
