### ISSUE TITLE
map our allele types to SO

### ISSUE THREAD

**Issue by mah11** [pombase/curation#1070]
useful for PhenoPackets, Monarch, etc.

I guess "unknown" will map to the most general "variant" term ...

**Comment by ValWood** [comment]
Hmm, I am trying to create a project "monarch" to group these tickets, but it didn't work. 
I'll use label "phenopackets" for now...

**Comment by mah11** [comment]
Draft mapping added to svn (pombe-embl/chado_load_mappings/allele_type_to_SO_mapping.txt)

Current version also uploaded here so people without access (e.g. @cmungall, @dosumis) to our svn repo can look at it: [allele_type_to_SO_mapping.txt](https://github.com/pombase/curation/files/489814/allele_type_to_SO_mapping.txt)

Note that not everything maps precisely, and some mappings may have scope for improvement.

Chris - flag anyone else who may want to see this ...

@kimrutherford

**Comment by ValWood** [comment]
And this is what we have for single allele:

56326 
   1 Allele type
7898 amino_acid_mutation
37345 deletion
 283 disruption
 374 nonsense_mutation
 936 nucleotide_mutation
1211 other
1511 partial_amino_acid_deletion
 104 partial_nucleotide_deletion
3966 unknown
 357 unrecorded
2341 wild_type

We now have some tickets to fix some inconsistent  allele descriptions  and see if we can describe some of the 'others'

**Comment by ValWood** [comment]
This is straightforward to do if we need to (i.e. for Alliance) , but until necessary closing
