### ISSUE TITLE
rho gap specificities

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1082]
- [ ] Rga1 functions as a GAP for Rho1 and is involved in actin-patch localization, cell mor- phogenesis, septation, and cell wall synthesis (Nakano et al., 2001).

Characterization of GTPase-activating proteins for the function of the Rho-family small GTPases in the fission yeast Schizosaccharomyces pombe.
PMID: 11737264

**Comment by ValWood** [comment]
Rga2 is a GAP for Rho2 and regulates cell morphology and cell wall integrity (Villar-Tajadura et al., 2008). Rga2 localization depends on polarity markers and actin polymerization (Villar-Tajadura et al., 2008). 
(needs regulation of process annotations)

**Comment by ValWood** [comment]
Rga2 is a GAP for Rho2 and regulates cell morphology and cell wall integrity (Villar-Tajadura et al., 2008). Rga2 localization depends on polarity markers and actin polymerization (Villar-Tajadura et al., 2008). 
(needs rho2 substrate)

**Comment by ValWood** [comment]
Rga5 is a GAP for Rho1 and regulates cell integrity (Calonge et al., 2003). Rga6 is a less-studied GAP for Rho2 (Villar-Tajadura et al., 2008; Soto et al., 2010). Rga8 is a GAP for Rho1 and a downstream target of p21-activated kinase Shk1 (Yang et al., 2003). Rga3 and Rga9 have not been studied. Rga7 is a Rho2 GAP (Martin-Garcia et al., 2014; Arasada and Pollard, 2015). It cooperates with Fes/CIP4 homology-Bin/amphiphysin/Rvs (F-BAR) proteins Cdc15 and Imp2 in actomyosin ring stability, proper ring disassembly, and successful septum formation and separation to en- sure cell integrity (Martin-Garcia et al., 2014).

**Comment by mah11** [comment]
Is the task here to curate papers? If so, do you have PMIDs for them?

**Comment by ValWood** [comment]
Most of these gaps are now filled. I added PMIDs for the missing data.
No hurry for this obviously but nice ones to prioritize for linking MF targets.

**Comment by mah11** [comment]
done
