### ISSUE TITLE
re-entry into mitotic cell cycle

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1084]
Follow on from
https://github.com/pombase/curation/issues/1011

I think these should either be  a) more specific (if they are not just checkpoint arrest)
or b) removed (if they are checkpoint arrest)

SPAC23C11.16.1		GO:0000320	re-entry into mitotic cell cycle	70f8ac4a3ff0e8c5	PomBase
SPBC30D10.10c.1		GO:0000320	re-entry into mitotic cell cycle	ab2c8f1287892790	PomBase
SPCC320.13c.1		GO:0000320	re-entry into mitotic cell cycle	70f8ac4a3ff0e8c5	PomBase
SPAC23C11.16.1		GO:0000320	re-entry into mitotic cell cycle	21507585ab1a2dfc	PomBase

**Comment by ValWood** [comment]
If they are some sort of "checkpoint arrest" in response to nutritional status they should be annotated to the  +ve regulation of the transition they are regulating (G2/M?).

**Comment by Antonialock** [comment]
I had some coments on these annotations saying I wasn't sure it was the right term, so they have been fixed now. It seems like I wasn't sure if it was mitotic exit + re entry following stress, but actually I think it is just an arrest in the cycle, and then a restart (+ve reg G2/M).
