### ISSUE TITLE
check should these be meiotic cell cycle rather than "nuclear division"?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1085]
The abstract talks about regulating pre-meiotic replication?

SPCC18B5.03.1       GO:0045835  negative regulation of meiotic nuclear division 915dd27f11d0b65d    PomBase
SPBC660.14.1        GO:0045835  negative regulation of meiotic nuclear division 915dd27f11d0b65d    PomBase
SPBC32H8.11.1       GO:0045836  positive regulation of meiotic nuclear division 915dd27f11d0b65d    PomBase
SPAC24H6.05.1       GO:0045836  positive regulation of meiotic nuclear division 915dd27f11d0b65d    PomBase

SPBC32H8.11.1       GO:0045836  positive regulation of meiotic nuclear division 915dd27f11d0b65d    PomBase

SPAC24H6.05.1       GO:0045836  positive regulation of meiotic nuclear division 915dd27f11d0b65d    PomBase

**Comment by ValWood** [comment]
and this one
SPBC29A10.02.1		GO:0007126	meiotic nuclear division	2a809a0d2e35ee91	PomBase

**Comment by Antonialock** [comment]
I think these are all ok, they should not be to "meiotic cell cycle" but I don't really want to make them more specific either.

**Comment by ValWood** [comment]
If you are sure its "meiotic nuclear division"
shouldn't you be able to say minimally whether it is meiosis I or meiosis II?

if you can't be more specific  I'm wondering if you can really say its meiosis (which should be some aspect of nuclear division)

(For example a defect in premeiotic replication could probably cause problems with meiotic nuclear division indirectly , analogous to mitotic S-phase defects causing a block in G2/M and entry into mitosis)

I guess my question is, what is the evidence that these are nuclear division?

**Comment by Antonialock** [comment]
> If you are sure its "meiotic nuclear division"
shouldn't you be able to say minimally whether it is meiosis I or meiosis II?

yes I think it looks like they are intrinsically involved. I did move it down to meiosis I but I need a new term for the neg reg.

do you want to have a look at the paper and see if you agree?

**Comment by ValWood** [comment]
If this is regulation entry into meiosis I, then it seems to be regulating the transition between
the GO:0051331 meiotic G2 phase and meiotic nuclear division.
We do not yet have this transition represented in GO.

"regulation of meiotic G2/M transition" might work.

However, a slight complication which also needs resolving

https://en.wikipedia.org/wiki/Meiosis
says that the extended G2 This S-phase can be referred to as "premeiotic S-phase" or "meiotic S-phase." Immediately following DNA replication, meiotic cells enter a prolonged G2-like stage known as meiotic prophase. 

so are  GO:0051331 meiotic G2 phase
and meiotic prophase I GO:0007128 the same?

In GO GO:0007128
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0007128
is described as the first stage of meiosis I rather than preceding it.

Perhaps meiosis and mitosis differ in this respect?

**Comment by ValWood** [comment]
yeah I think this is analogous to the ?G2/M transition (same pathway),
so here it would be  regulation of  meiosis I G2/M transition

i.e transition from
GO:0051331
Name	meiotic G2 phase
Definition	The cell cycle 'gap' phase which is the interval between the completion of DNA synthesis and the beginning of DNA segregation by meiosis.

However when I google I find"
This S-phase can be referred to as "premeiotic S-phase" or "meiotic S-phase." Immediately following DNA replication, meiotic cells enter a prolonged G2-like stage known as meiotic prophase."

which would indicate that
 GO:0051331 meiotic G2 phase
and
GO:0007128 meiotic prophase I
are the same?

this would indicate that phases are delimited slightly differently in meiosis and explain our confusion here.
https://github.com/pombase/fypo/issues/2035

I think we need to ask an expert. 

but we definitely need a transition term to annotate to:

+'ve regulation of  meiotic G2/meiosis I transition

**Comment by ValWood** [comment]
Sorry there are 2 comments. They should say more or less the same thing. I though the first on disappeared!

**Comment by ValWood** [comment]
also I'm not so sure that mei4 should be annotatated to this....(causally upstream?)

**Comment by ValWood** [comment]
Note that the mei4 shouldn't be "regulation of meiosis"
more detail in https://github.com/pombase/curation/issues/907 if you need it

**Comment by ValWood** [comment]
What still needs to be done here. Have been discussing with Pascale this week. It is likely that some of these terms might be obsoleted and reinstated. Would be good to check what we have in terms of

"meiotic nuclear division" and the  regulation terms, and that they are correct

**Comment by ValWood** [comment]
mei4 GO:0060903	positive regulation of meiosis I

looks wrong to me
I think it should be
GO:0010673	
positive regulation of transcription from RNA polymerase II promoter involved in meiotic cell cycle
or if we can't be this specific, regulation of meiotic cell cycle...

**Comment by ValWood** [comment]
I think this is done except mei4 check?
