### ISSUE TITLE
Terms used in annotation that are now missing from the database

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#1089]
These are the IDs that are used in an annotation but are no longer in the Canto DB probably because we now load a pombe-only version of GO:

c57f22a897472fa7 - GO:0009008
16267d2a11f0cdbf - GO:0070885   (see #1087)
16267d2a11f0cdbf - GO:0033173
35bfa0019d25c550 - GO:0035756
35bfa0019d25c550 - GO:0035377
80b382d361649949 - GO:0000918
9e6658619f3b13c3 - GO:0035082

**Comment by ValWood** [comment]
35bfa0019d25c550 - GO:0035756
35bfa0019d25c550 - GO:0035377
are in @kimrutherford's test session

**Comment by Antonialock** [comment]
this one is fine because it is a NOT
c57f22a897472fa7 - GO:0009008

**Comment by ValWood** [comment]
ooh we hadn't thought of that!

**Comment by ValWood** [comment]
Actually I think we can delete it. Ideally this paper could be used to support the taxon restirction, but its fairly common knowledge that pombe does not have this  activity, and  prevent a positive annotation. A taxon restriction will do an even better job...

**Comment by Antonialock** [comment]
Im definitely in favor of keeping it - the human ortholog is annotated to
DNA (cytosine-5-)-methyltransferase activity

one of the main selling poinst of NOT annotations is to say that "although this protein has this function in another species, it does not have it in pombe"

**Comment by ValWood** [comment]
ok

**Comment by Antonialock** [comment]
and the paper obviously gives evidence that this is the case....so even if it is well established knowledge that pombe does not have this activity, it might be of interest to someone to find a reference providing evidence that this is the case.

If it makes it easier then I wouldn't mind canto not knowing what term the ID refers to (Im happy to copy and paste an ID from quickGO, adding the NOT qualifier, and leaving it at that)

**Comment by ValWood** [comment]
The human ortholog 	TRDMT1 isn't a DNA methytransferase in vivo, its a tRNA methytransferase. I still think this is probably an 'unnecessary' annotation in light of 'modern' knowledge for this particular protein....

**Comment by ValWood** [comment]
> Im happy to copy and paste an ID from quickGO, adding the NOT qualifier, and leaving it at that

you can't do this...the term is taxon restricted so Canto won't recognise it.

**Comment by ValWood** [comment]
we can do this instead:
https://github.com/geneontology/go-ontology/issues/12702

**Comment by ValWood** [comment]
I raised a query about hte human TAS annotation, it does not appear to be the case.
DNA (cytosine-5-)-methyltransferase activity
I think we can lose this NOT annotation easily enough, but yes I think we do need to keep them in any cases where  orthologs have different molecular function. I don't think we have any cases of this at the moment? although we may make a NOT annotation for processes, I don't think we would do this if a BP term was taxon restricted?

**Comment by ValWood** [comment]
can close this when decision about  c57f22a897472fa7 - GO:0009008 finalised

**Comment by Antonialock** [comment]
ok fine, I won't lose any sleep if you remove it.... I just thought if anyone who is not an expert in pombe, or on this activity was looking for the information then this mightmake it quicker to find...

**Comment by ValWood** [comment]
I wonder at this point if the orthologs don't have this activity the NOT in this case might be even misleading....I don't think there is any real reason now to think it  might be a DNA methytransferase, especially when the human ortholog is corrected.

We might need the ability at some point to make a NOT annotation to a taxon restricted term, but we can worry about this when we have a use case.
I requested this ref is added to the taxon restriction. 

I'll add removing this NOT to the list and close this

**Comment by Antonialock** [comment]
well presumably it is ok in chado so we could always add special cases using artemis.

**Comment by ValWood** [comment]
The filter will apply to chado. I still think its not that useful. Pombe does not have this activity, and the ortholog does not have this activity....why show it? OK it was tested but  its an old paper
and there are other links to it.  I don't think there is really any reason why anyone might think this was a DNA methytransferase nowadays....
