### ISSUE TITLE
c57f22a897472fa7 - GO:0009008

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1090]
from https://github.com/pombase/curation/issues/1089

curs/c57f22a897472fa7/ro/
has a DNA methytransferase annotated.
I'm sure pombe does not have this activity. Can you check? if it needs deleting you won't be able to remove it. You will need to open a ticket for Kim to delete manually

**Comment by Antonialock** [comment]
good thing it is annotated to 
NOT DNA-methyltransferase activity 
then :-)
