### ISSUE TITLE
glt1  	glutamate synthase 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1092]
should have 	

GO:0019676 ammonia assimilation cycle
defined
The pathway by which ammonia is processed and incorporated into a cell. In an energy-rich (glucose-containing), nitrogen-poor environment, glutamine synthetase and glutamate synthase form an ammonia assimilatory cycle, in which ammonia is incorporated into L-glutamate to form L-glutamine, which then combines with alpha-ketoglutarate to regenerate L-glutamate. This ATP-dependent cycle is essential for nitrogen-limited growth and for steady-state growth with some sources of nitrogen.

**Comment by ValWood** [comment]
also chech, is it NADP or NADPH

**Comment by Antonialock** [comment]
I take it you mean NADH or NADPH? I have had a good look and haven't found anything definite (the ref for the cerevisiae annotation does specify NAD, but there seems to be some conflicting statements in other papers).

**Comment by Antonialock** [comment]
this might be a good ref to do
https://curation.pombase.org/pombe/view/object/pub/PMID:20435771?model=track

**Comment by ValWood** [comment]
> I take it you mean NADH or NADPH?

OK ignore that part

**Comment by ValWood** [comment]
done
