### ISSUE TITLE
substrates for modifiers?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1102]
follow on from
https://rt.sanger.ac.uk/Ticket/Display.html?id=549316

I was wondering, as this session has modifications with added by and removed by
curs/d91d901cb0a83596/ro/

should it also not have MF terms with has_substrate for these?
i.e.  rhp18/rad8 ubp16

**Comment by mah11** [comment]
one done; rest need https://github.com/pombase/canto/issues/1273

**Comment by mah11** [comment]
finally done
