### ISSUE TITLE
chromosome segregation 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1104]
klp5, klp6 
do not yet have phenotypes
- [x] increased chromosome loss ? (has a chromosome segregation phenotype)
- [x] elongated mitotic spindle ?

Csi1 
- [x] is a kinetochore-SPB connector in mitotic interphase (Hou et al., 2012),
paper is curated, 
mitotic centromere-SPB clustering protein, binds to sad1. More data required

Nuf2
- [x] which connects the centromeres to the SPB, disappears at the early meiotic prophase and releases the centromeres from the SPB (Asakawa et al., 2005; Hayashi et al., 2006.

need MF to capture this...
attachment of mitotic spindle microtubules to kinetochore

Cut2 
- [x] has no mitotic spindle annotation on dev, only meiotic (might have been made since).
  -  [ ] Current annotation says cut2 is present _during_ S-phase, check

Cut7
- [x]  In the temperature-sensitive cut7 mutant, spindle formation is blocked shortly after duplication of the SPB. 
see https://github.com/pombase/fypo/issues/3415

- [x] The mitotic spindle radiating from the opposite poles cannot interdigitate and thus remains as a V shape (Hagan and Yanagida, 1992). 
see https://github.com/pombase/fypo/issues/3415

moved to https://github.com/pombase/curation/issues/2320

NMS complex
- [x] needs annotation to ndc80 complex

**Comment by ValWood** [comment]
sfi1
- [ ] S. pombe Sfi1 (SpSfi1) perfectly colocalizes with Cdc31 at the SPB half-bridge/bridge in high-resolution fluorescence microscopy, and both proteins are essential for SPB duplication (48–50).

**Comment by ValWood** [comment]
-[ ] mis6, mis12
Fission yeast mis6-302 and mis12-537 mutants exhibit unequal segregation of regular chromosomes when shifted to a restrictive temperature. In these mutants, sister chromatids were segregated to the daughter cells at anaphase without a long delay, but the segregation patterns of sister chromatids were random. Consequently, these mutations produced aneuploid cells with a high frequency. Localization studies using green  ̄uorescent protein (GFP) and chromatin immunoprecipitation (ChIP) assays estab- lished that Mis6 and Mis12 are bound to the central centromere regions throughout the cell cycle. MNase digestion experiments indicated that these proteins are essential for forming the specialized chromatin of the central centromere regions (Saitoh et al., 1997; Goshima et al., 1999). However, no genetic or physical interactions have been found between Mis6 and Mis12.

**Comment by ValWood** [comment]
One of the outstandig questions is whther kinetochore assembly should be part of chromosome segregation (particularly the inner kinetochore/centromere complex)
has a mis-match with Mis6-Sim4 complex annotations.
mal2 currently has no chromosome segregation process annotation

**Comment by ValWood** [comment]
- [ ] read review PMID: 23512483

- [ ] is CENP-A containing nucleosome assembly part of kinetochore assembly? Although the outer repeats play an important role in sister centromere cohesion and possibly help to properly orient the multiple kinetochore microtubule attachment sites (Pidoux and Allshire, 2004

- [ ] Centromeres: getting a grip of chromosomes. Curr. Opin. Cell Biol. 12, 308–319., the central region is needed for the assembly of the kinetochore per se and the interaction with the mitotic spindle fibers

- [ ] what is the relationship between kinetochoe assembly, spindle elongation and chromosome segregation (currently disjoint)

- [ ] reannotate ndc80 and MIND subcomplexes annotate PAS complex

- [ ] ask expert to look at CENP_A assembly vs CENP-A assembly phenotype

- [ ] no substrates currently annotated for APC, look for motifs ABBA, KENm D-Box, C-BOX, F-box, 2BR, LRRL   possible substrates to annotate mitotic securin and cyclin; late mitosis cdh1 , cytokinesis aurora, cyclins, cdc29; G1 geminin, cdc6, skp2,ubcH10(ubc11)....check all know APC targets annotated

**Comment by ValWood** [comment]
- [ ] dnt1 should this be in  spindle checkpoint?

**Comment by ValWood** [comment]
-[ ] 

Cells lacking either Klp5 or Klp6 are resistant to thiabendazole, a microtubule depolymerising agent, display a prolonged delay in pro-metaphase and metaphase with highly elongated spindles and are essential for viability in the absence of either Bub3 or the Dam1 complex (Figure 3A, Garcia et al., 2002; Sanchez-Perez et al., 2005; West et al., 2002). It is presently unclear why mitotic spindles are elongated in the absence of Klp5 and Klp6, since neither protein displays microtubule depolymerase activity in vitro (Grissom et al., 2009). 

This isn't really what we have now ;)

**Comment by Antonialock** [comment]
klp 5-delta has:
resistance to thiabendazole
mitotic metaphase/anaphase transition delay

klp6
resistance to thiabendazole
mitotic metaphase/anaphase transition delay

and they have double mutant phenotypes with dam1

**Comment by ValWood** [comment]
Ah this might be OK, the transition M/A was delayed .
I just wanted to check what things in metaphase have an "elongated spindle" phenotype, follow on from
https://github.com/pombase/fypo/issues/2845

**Comment by ValWood** [comment]
I think its what is usually called 
"spindle elongation without chromosome separation"

**Comment by ValWood** [comment]
- [ ] find physical interaction to connect proteasome lid particle to core complex (currently the lid is floating around on its own in my interaction network)

**Comment by ValWood** [comment]
(noticed because ubc11 is annotated to both +ve and -ve  regulation of the transition)
https://github.com/geneontology/go-ontology/issues/12366

**Comment by ValWood** [comment]
- [ ]  check all the cohesin/condensin ring have the  GO:0061776 - DNA ring activity/topological  entrapment term (also not dsDNA binding parent)

**Comment by ValWood** [comment]
- [ ] cut vs mitotic spindle assembly checkpoint override

**Comment by ValWood** [comment]
- [ ] How is spindle elongation regulated? (SIN?)  
 - [ ] Are all anaphase events membrane expansion, spindle elongation part of the transition? or just securin degradation?

**Comment by ValWood** [comment]
- [ ] Q …..should all  CENP-A partially replaces canonical histone H3 at the centromere to serve as the structural and functional foundation for kinetochore assembly (Black and Cleveland, 2011; Bodor et al., 2014; Sullivan and Karpen, 2004). 


 - [ ] One key factor known to promote CENP-A loading is the conserved histone chaperone, Scm3/ HJURP, which is in turn recruited by the Mis16-Mis18 complex (Dunleavy et al., 2009; Foltz et al., 2009; Pidoux et al., 2009; Wil- liams et al., 2009; Yu et al., 2015). However, how CENP-A and histone H3 levels are precisely maintained at the centromere re- mains unknown.

**Comment by ValWood** [comment]
- [ ] monopolar spindle check

In the first mutant phenotype category, the spindle formed from only one SPB, which is normally referred to as monopolar spindle (Figures 2A and S2A). This phenotype is common in a number of mutants for SPB components including Cdc31 [34], Sad1 [35], Cut12 [36], Cut11 [37], Pcp1 [38], Plo1 [39], and Cut7/Kinesin-5 [40].

I only have cut11, plo1 and cut7 from this list at present...

**Comment by ValWood** [comment]
- [ ]  skp1, bent spindle
A similar phenotype has been reported for the skp1 mutant of the SCF (skp, cullin, F-box) ubiquitin ligase complex [30,43]. This is probably due to entangled chromosomes that fail to resolve during mitosis and meiosis, which is caused abnormal tension in the elongating spindle [30,43].

**Comment by ValWood** [comment]
In fission yeast, the recruitment of cohesin at the mating type locus, at outer repeat regions of centromeres, and at telomeric sites is dependent on the fission yeast heterochro- matin protein 1 (HP1) homologue Swi6 through an interaction with Psc3 (Bernard et al., 2001; Nonaka et al., 2002) and the loading factor Mis4 (Fischer et al., 2009).

**Comment by ValWood** [comment]
Inhibition of Aurora B using a Shokat mutant leads to chromosome segregation defects (Koch et al., 2011), such as merotelic or syntelic attachment (Gay et al., 2012),

**Comment by ValWood** [comment]
gaaah this ticket is sooooo long ;(
