### ISSUE TITLE
cdc14 G2/M transition

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1111]
I don't think cdc14 is involved in G2/M transition. What is the phenotype?

**Comment by Antonialock** [comment]
to sumarise the excerpt:

- cdc14-OP is arrested in G2
- The wee1-6 cdc14-OP double mutant continues to divide.
-> it seems like cdc14 acts via wee1 to inhibit mitosis

In the discussion they speculate that cdc14 is involved in ensuring that septation doesn't begin until mitosis is underway.

**Comment by ValWood** [comment]
Hmm, here's my thoughts:

- Cdc14 is a scaffold  (armadillo repeat) protein for the SIN.
- The SIN is activated *after G2/M) 
- Cdk1 inhibits the sin via byr4( after the G2/M transition in mitosis I think).

There is a connection between the SIN and G2-M in that, if   cytokinesis is compromised the subsequent division  is  halted, but I think this is too indirect to capture as a G2/M regulator because it isn't what normally happens, and its after proceeding through G1/S phase, it could just be that the cytokinesis defect  is causing the problem rather than direct regulation by the SIN (this is purely my speculation).

However, taking that into account, and the age of the paper I would say that we shouldn't make this annotation....otherwise we would have to assume that the SIN is regulating G2/M which it isn't.....

Overexpressions can be dodgy because things can interfere in unknown ways if expressed when they would not normally be present.

maybe a 2nd opinion @jvhayles ?

**Comment by Antonialock** [comment]
the green bar is a confirmed intron....is this weird?

![screen shot 2016-10-11 at 15 34 37](https://cloud.githubusercontent.com/assets/12727506/19274508/3f54d254-8fc8-11e6-9280-cd82309e7883.png)

**Comment by Antonialock** [comment]
according to that paper, an allele of cdc14 has a different phenotype from their deletion allele

human folliculin exists as 3 different isoforms, the longest is 579 AAs, pombe folliculin is 367, cdc14 240

**Comment by ValWood** [comment]
> human folliculin exists as 3 different isoforms, the longest is 579 AAs, pombe folliculin is 367, cdc14 240

? whats this about, I don't get it?

**Comment by Antonialock** [comment]
bhd1, should it be longer? is cdc14 part of it?

**Comment by ValWood** [comment]
bhd1 is on the opposite strand ;)

**Comment by Antonialock** [comment]
Fair point :p just thought they looked odd.

**Comment by ValWood** [comment]
Yeah they look fine if you look at the domain arrangement.

**Comment by Antonialock** [comment]
Ok, I really don't know enough about how these pathways connect to see that it is way upstream of regulating wee1. In its annotations it just says it localizes sid1...I trust your expert opinion though ;-) we can always tweak it if new stuff comes to light..

**Comment by ValWood** [comment]
Yeah the actual function of cdc14 is just a "scaffold" for the SIN signalling pathway.
The picture in this ticket is pretty  useful:
https://github.com/pombase/curation/issues/1031
