### ISSUE TITLE
phosphatases 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1120]
- [x] product labels updated

![summary_iains paper](https://cloud.githubusercontent.com/assets/7359272/19270941/6556e392-8fba-11e6-930a-72d03a23d8a0.jpg)

**Comment by ValWood** [comment]
check these too
ppa1 targets ppe1? 
ppe1 targets pim1?
pck1 targets ppe1?

**Comment by Antonialock** [comment]
I looked for these but couldnt find them

**Comment by ValWood** [comment]
yep this was in an older ticket, but I think  some of them might be a bit hidden because they use the Phospatase type A B regulator etc nomenclature. I will ask if I can't find them...

**Comment by ValWood** [comment]
- [ ] dis1  check these phenotypes 
PMID:16920624 plus…XMAP215/ TOG/Stu2-family homolog, binds microtubules and localizes to kinetochores (Nakaseko et al., 2001). Mutants in dis1 lack the chromosome alignment phase in metaphase and arrest with elongated spindles and segregated but unseparated chromosome pairs (Nabe- shima et al., 1998; Ohkura et al., 1988).dis1 mutants arrest with an activated spindle checkpoint and appear to experience an increase in sister chromatid cosegregation (70%) at full restrictive temperature. Such cosegregation results when mono-ori

**Comment by ValWood** [comment]
- [ ] dis mutants form a mitotic spindle that elongates but does not completely disappear at the end of anaphase B.
