### ISSUE TITLE
query about ctp1

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1134]
I was doing a periodic sanity check to ensure that all sequence-specific  DNA binding  transcription factors have both a  transcription factor, and a DNA binding MF term.

I found this oddity. It doesn't ring any bells with me, and it looks very odd?

![ctp1_query](https://cloud.githubusercontent.com/assets/7359272/19568818/0dddbac2-96eb-11e6-82ac-45d8e256abe5.jpg

(ctp1 is an endonuclease? should this be on another gene product? ctp1 is also the target)

**Comment by Antonialock** [comment]
I didn't make this annotation afaik....maybe you pasted in the wrong term ID, or made the annotation to the wrong gene..?

**Comment by mah11** [comment]
oops, was meant for nrm1

**Comment by ValWood** [comment]
Ha ha, I was going to take the blame. I thought it couldn't possibly be you ;) and obviously neither did Antonia.

**Comment by Antonialock** [comment]
sorry :-P
