### ISSUE TITLE
cutin 1 as a condition? PMID:26869222 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1138]
If cells show "abnormal chromosome segregation" but only in the proesence of cutin-1, I guess I need +cutin1 as a condition?

**Comment by mah11** [comment]
Yep - we've only built substances into FYPO terms for sensitivity and resistance (in the population growth department).

**Comment by ValWood** [comment]
OK

**Comment by Antonialock** [comment]
added:
+ cutin-1
