### ISSUE TITLE
plasmids in genotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1139]
jacky put a comment
"I seem to have written a lot of comments as I needed to explain the genotype especially whether a plasmid was integrated or multi copy. I couldn't find a way of do this."
curs/2bfae567526bc0ec

we should discuss tomorrow how to indicate  do this , and if we need to refine

**Comment by Antonialock** [comment]
edge case?

**Comment by ValWood** [comment]
historically if  genome copy is deleted and mutant introduces, we don't differentialt, we just 
annotatae as mutantx., and capture if it overespressed.

Going forwards, we should be able to capture if the WT copy is still present  but we cant do this until https://github.com/pombase/canto/issues/1244 is done

@jvhayles
