### ISSUE TITLE
label sup3

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1140]
Need sup3 as a gene name on the appropriate  tRNA  if possible

Sup3 is tRNA serine gene and sup3-5 mutant is an opal nonsense suppressor.   Here are a couple of  references 
PMID: 3921825 
PMID: 68184 and Paul references  
PMID:  762155 for sup3-5 

problem is need to  apply the label to a specific tRNA serine (hopefully this can be distinguished).
If this is done, we can  pull the gene out of the background in 

curs/91da8e4c4e7b6d48

**Comment by Antonialock** [comment]
PMID: 68184 is not a pombe paper (I suffixed numbers 1-9 but one of them are a pombe paper)
PMID: 3921825 is not about sup3-5 (it mentions -e and -i - these two alleles map to SPATRNASER.03 but I don't know if -5 also does

**Comment by mah11** [comment]
> PMID: 68184 is not a pombe paper

It might be PMID:6818425

**Comment by Antonialock** [comment]
PMID:762155 is not about sup3-5 either PMID:762155

**Comment by Antonialock** [comment]
PMID:6818425 is sup3-e

**Comment by Antonialock** [comment]
sup3-5 is synonymous to sup3-e

fixed in session.
