### ISSUE TITLE
disruptions described as "other" to fix

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1141]
asp1-delta1,SPCC1672.06c:allele-3,disruption,deleting amino acids 82-331,1fecc0470053ec75
nic1-1,SPCC1884.02:allele-3,disruption,947219ec962a1b36
swi1-1,SPBC216.06c:allele-4,disruption,05f7d09930433392
mcp60-,SPAC12G12.04:allele-2,disruption,b522bc9d484ad0db
pck2D,SPBC12D12.04c:allele-12,partial disruption,e0e85df0e0e16a77
,SPCC188.06c:allele-35,disruption,
psk1-,SPCC4G3.08:allele-3,disruption,fafb883b15d2587b
spo15::ura4+,SPAC1F3.06c:allele-6,spo15::ura4+disruption,f51c10788015bf25
srp7.1,SPNCRNA.98:allele-127,disruption (srp7::m-Tn3(Leu2)),065a5d3851a4f583
pck1D,SPAC17G8.14c:allele-4,partial disruption,e0e85df0e0e16a77
,SPAC29B12.10c:allele-3,disruption,0148c364556794c5
,SPBC30D10.11:allele-2,disruption,b90e1da4e1a8027a
msn5::ura4+,SPAC328.01c:allele-5,disruption,c1d9cf8c5062801d
gar2::ura4+,SPAC140.02:allele-4,disruption; produces fusion of Gar2 amino acids 1-163 to Ura4 amino acids 1-39,cbaaa61496b71364

**Comment by mah11** [comment]
1fecc0470053ec75 requires https://github.com/pombase/canto/issues/1274
description will be asp1::ura4+(aa82-331)

leaving one from cbaaa61496b71364 as 'other' because of resulting fusion

the rest are done

**Comment by mah11** [comment]
will close when the asp1 allele is done

**Comment by ValWood** [comment]
closing this if the one left is a fusion.
We'll have another purge once all the existing tickets are dealt with and we can see what is left in "other"
