### ISSUE TITLE
other allele to fix, pending allowing a WT allele background

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1142]
once https://github.com/pombase/canto/issues/1244 is done
- [x] the multi mutant containing an "other" allele in session ad3cea5e630841a3

can be updated from:
![screen shot 2016-10-26 at 11 56 30](https://cloud.githubusercontent.com/assets/12727506/19723455/467b5c72-9b73-11e6-9e78-180bcb4b4026.png)

to:
![screen shot 2016-10-26 at 11 53 16](https://cloud.githubusercontent.com/assets/12727506/19723410/19d5c93c-9b73-11e6-9544-bd9ff33c7c7d.png)
- [ ] also look at cut1C in this session, many alleles, should be with a wt allele background? 3926aad5386b9286: 
  http://onlinelibrary.wiley.com/doi/10.1046/j.1365-2443.2002.00586.x/epdf

this should be "over expression of 1245–1828 (Cut1C-terminal domain) in WT background. 
Some of them also have point mutations, but we can update the domain overexpression in WT background before then.

**Comment by ValWood** [comment]
You can do this one now

**Comment by ValWood** [comment]
Oh I thought that was done but the Canto ticket is still open so maybe not....

**Comment by ValWood** [comment]
You can do this one now.....

**Comment by ValWood** [comment]
@Antonialock  can you see if this one can close?

**Comment by Antonialock** [comment]
fixed.

maybe this should be in the background information though?...

**Comment by ValWood** [comment]
I'm not sure what the ticket is about? (maybe I forgot). Could you explain?

**Comment by Antonialock** [comment]
It is about adding a WT allele + WT expression when you have another allele of the same gene expressed in an organism (from a plasmid/ other locus) 

Perhaps this should be added to the background info (I remember  people asking for the ability to delete a gene that they have then added back in (mutated) on a plasmid....nowadays we would tell them to ignore but maybe this should go in background? Also at the moment background info is all free text which is pretty ugly

**Comment by ValWood** [comment]
Hmm, if you have 2 copies shouldn't it really be in the foreground?
Is that what you mean?

If you say you  are expressing a mutated gene on a plasmid the default assumption is that you deleted the wt copy isn't it?
In this case you need to specify if you leave it in?

We do need to clarify clearly!

**Comment by Antonialock** [comment]
Well, I would say that most of the time, researchers either delete a gene in the genome + reintroduce a mutated copy from a plasmid OR directly mutate the gene in the genome.

I would not say that we make any sort of formal assumption to this effect. There are cases where a WT copy remains in the genome simultaneously with a mutated copy.

**Comment by mah11** [comment]
I think we have to explicitly state when a wild-type copy of a gene is present along with a mutated copy (no matter where the copies are). The vast, vast majority of users will make the same assumption that Val and I do - that the reported allele(s) of a gene of interest is/are the only one(s) present for that gene, and we need to ensure that that assumption is safe. It is most assuredly NOT background information.
