### ISSUE TITLE
caf2 "other" allele to fix

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1144]
caf2-3 / WT,SPAC1805.17:allele-22,heterozygous cross,9076c0731474baf4

**Comment by Antonialock** [comment]
fix after https://github.com/pombase/canto/issues/976 when we can handle diploids, this looks like a mutant allele + wt allele diploid

**Comment by ValWood** [comment]
Closing as this will still be in "other" log, don't need a ticket
