### ISSUE TITLE
allele type other, partial deletions?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1146]
cdc27partial_delta,SPBC1734.02c:allele-59,75% deletion,c5bcc1ff40b42c22

,SPCC736.04c:allele-3,partial deletion,8c6fa414440558a1

**Comment by ValWood** [comment]
sme2deltaE,SPNCRNA.103:allele-4,1058-1586,e3c8313e9bd1dabc

**Comment by ValWood** [comment]
dli1deltav,SPAC458.04c:allele-4,other,c7fac5251ee4f493 (if not, clarify)

**Comment by mah11** [comment]
done; same paper as I was talking about - the remaining deletions marked 'other' aren't partial (some or all of ncRNA, but also some upstream sequence
