### ISSUE TITLE
allele type other -> amino acid mutation?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1149]
LiL,SPBC1604.21c:allele-6,Insertion of thr-gly between aa198-199,285ddfe564bdf7e2

**Comment by mah11** [comment]
yes, but not worth changing yet because it's an insertion

**Comment by ValWood** [comment]
SSAA,SPAPB1E7.12:allele-3,both RxxS phosphorylation sites disrupted,f07cd572b2d0adcf

**Comment by ValWood** [comment]
or can just close I guess...other will be dealt with at some point
