### ISSUE TITLE
GO  protein binding children

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#115]
We don't want all protein binding children available for curation.
This problem may partially go away as GO are obsoleting lots of binding children.

If they don't disappear, or can't be filtered before CC release, a "PomBase specific comment" might be the way to go....

I'll continue to think about this

Original comment by: ValWood

**Comment by ValWood** [comment]
There are rumblings of GO working on this. I will continue to hassle.....

**Comment by ValWood** [comment]
for starters I requested some taxon constraints, and domain and family groupings and a few gene product specific obsoletions....

**Comment by ValWood** [comment]
open a GO ticket

use
GO:0097371    MDM2/MDM4 family protein binding
GO:0043221    SMC family protein binding
as examples
