### ISSUE TITLE
spd1 checks

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1153]
annotated to both sensitive and normal HU phenotype
cellular localization BP -> can this be made more specific?

**Comment by mah11** [comment]
> annotated to both sensitive and normal HU phenotype

I looked at the papers (I did approval for one of them), and it's a very small difference in results.

- PMID:25795664 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4426379/ fig 2 - looks the same as wild type

- PMID:26890608 http://www.tandfonline.com/doi/full/10.1080/15384101.2016.1148839 fig 4D - looks very slightly sensitive, almost as much growth as wild type

> cellular localization BP -> can this be made more specific?

from an old-ish paper, not yet curated in Canto, so it'll probably get upgraded in due course; may well turn into just a phenotype annotation

**Comment by ValWood** [comment]
close?

**Comment by mah11** [comment]
yeah, checked and older stuff will be mopped up eventually
