### ISSUE TITLE
ppk31 iso to autophagy?

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1155]
http://www.yeastgenome.org/locus/S000001861/go

PMID: 25660547

**Comment by Antonialock** [comment]
probably regulation? cerevisiae annotated to autophagy
this is the absract
 ppk31= cerevisiae rim15
rph1 = jmj3 (we dont have any exp BPs for jmj3 at the moment)

We identified Rph1 as a negative regulator of the transcription of several ATG genes and a repressor of autophagy induction. Rph1 is a histone demethylase protein, but it regulates autophagy independently of its demethylase activity. Rim15 mediates the phosphorylation of Rph1 upon nitrogen starvation, which causes an inhibition of its function. Preventing Rph1 phosphorylation or overexpressing the protein causes a severe block in autophagy induction. A similar function of Rph1/KDM4 is seen in mammalian cells, indicating that this process is highly conserved.

**Comment by ValWood** [comment]
I left rph1 for now. Its role in autophagy os proposed to be as a transcription factor, so I not really sure if thais is going to be a) direct or b) conserved.
I don't usually so any inter- species transfer of regulation  via transcription of specific genes without more information
