### ISSUE TITLE
request GO to  get rid of these MF terms which result in different ways to describe the same thing..

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1161]
I'm not fond of these  gene product specific activities like

(cyclin dependent kinase) activating kinase
 but as we have them we  should  use consistently or not at all

![csk1_collapse](https://cloud.githubusercontent.com/assets/7359272/19886620/fc7a7704-a01b-11e6-9375-dde3fc90dd2f.jpg)

**Comment by Antonialock** [comment]
Might be ok to remove the specificity seeing that the specificity is on the substrate anyway?

**Comment by ValWood** [comment]
I think so...
here we say the same thing in 3 different ways...

although maybe we should be compliant and move them all to  
cyclin-dependent protein kinase activating kinase activity

If I eventually persuade GO to merge them (my first attempt  was refused) they will still be correct

**Comment by ValWood** [comment]
I have no idea when in the cell cycle these operate....

**Comment by ValWood** [comment]
- [ ] when does csk1 phosphorylate and activate cdc2?????

**Comment by ValWood** [comment]
@jvhayles may know

**Comment by ValWood** [comment]
- [x] cyclin-dependent protein kinase activating kinase activity 
- [x] cyclin-dependent protein serine/threonine kinase regulator activity
- [x] protein kinase activator activity	
will be fixed by  GO checks
(will become  serine/trheonine protein kinase directly_activates cdc2,mcs6 etc)

-  [x]  update product to 
cyclin-dependent kinase activating kinase  (remove cyclin dependent kinase)

**Comment by ValWood** [comment]
Still interested if Jacky knows "when" but we could probably dig this out easily enough...

**Comment by ValWood** [comment]
Just the question

when does csk1 and msc6 phosphorylate and activate cdc2?????

**Comment by Antonialock** [comment]
Jacky says this is not known.

We decided that it is redundant to specify what type of protein the substrate is. 


Change to more general term, specificity is on the annotation extension.
