### ISSUE TITLE
cdc2 -> cdc18 and orc2

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1162]
I am trying to link this cdc2-substrate  to a process. I think this is involved in 
negative regulation of re-replication?
(which seems to be a bona fida regulatory process confining replication normally to one per cell cycle)

there does not seem to be a GO term for this process @mah11  should there be?

(it seems to be misleading to say it is involved in "regulation of initiation" as this could be misinterpreted...

**Comment by mah11** [comment]
It is negative regulation of initiation (GO:0032297).

**Comment by ValWood** [comment]
Ah can add "during G2" doh
