### ISSUE TITLE
allow extension part_of/involved_in process for MF terms

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1164]
Going to bite the bullet this one. I have been linking manually, not sure why I didn't do this before......

**Comment by ValWood** [comment]
added to the config file
GO:0003674	is_a	part_of	GO:0009987	involved in biological process		0,1	user

just so you know, in case anything stuff up.....

**Comment by kimrutherford** [comment]
There seems to be an update problem at the moment.  I'm still trying to fix it: pombase/canto#1273

**Comment by ValWood** [comment]
Well I have been using these so this can close
