### ISSUE TITLE
mad2 mitotic index phenotype

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1168]
in
https://curation.pombase.org/pombe/view/object/curs/2973?model=track

you annotated mad2 to "decreased mitotic index"

This was based on the observation that if you treat mad2-delta cells with the microtubule depolymerizing drug CBZ, fewer cells arrested.

I would not have annotated this to "decreased mitotic index", I would have annotated this to "decreased mitotic spindle assembly checkpoint " (probably?)

I would reserved the term "decreased mitotic index" for cases where you have unperturbed cells cycling, and a smaller proportion are in M phase

**Comment by ValWood** [comment]
I also did this

mis6
mis6-302(aaG135E)[Not assayed]
FYPO:0004318	abolished mitotic spindle assembly checkpoint

and I should have made this annotation on mad2 also. I have done that now.
I think the "decreased mitotic index" phenotypes are also valid.

But that is a good point. Maybe we should  have a term to represent this phenotype in cycling cells. I could delete these annotations though if you think they are misleading.

**Comment by ValWood** [comment]
Actually I deleted. They are misleading because I didn't capture all the conditions etc either.
