### ISSUE TITLE
pom1 MF-BP link

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1169]
Pom1 is a negative regulator of G2/M.

Pom1 goes to the cell ends and diffuses outwards. In short cells there is enough pom1 to inactivate cdr2 at the equator. In long cells inhibition of the mitotic inhibitor cdr2 is released. 

pom1 has neg reg of M BP annotation + kinase for cdr2 MF annotation from the Martin SG, Berthelot-Grosjean M publication so might be able to make a MF-BP link here. 

also see
PMID:19474792
PMID:19474789

**Comment by ValWood** [comment]
good place to get connected up....important papers

**Comment by ValWood** [comment]
This page is looking good in terms of substrates
http://pombase2.aska.gen.nz/gene/SPBC530.04

It should be possible to make MF-BP links for most of these?

**Comment by ValWood** [comment]
I did these papers for pombe 2017 talk examples
