### ISSUE TITLE
"PECO:000170" in PMID_16371652_phaf.tsv 

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#1178]
There's an unknown ID when loading data for pombase2.  It's at line 8 of: pombe-embl/external_data/phaf_files/chado_load/PMID_16371652_phaf.tsv 

Is "PECO:000170" missing a zero?

**Comment by kimrutherford** [comment]
Also "PECO:000004" in
  phenotype_mapping/tab_phenotype.csv
  phenotype_mapping/mapping.csh
  phenotype_mapping/one_line_per_annotation
  phenotype_mapping/phaf_format_phenotypes.tsv

**Comment by kimrutherford** [comment]
The new code can't cope with alt_ids yet so it's failing to read some of the files in:
  external_data/Quantitative_gene_expression_data/

Could we change PECO:0000014 to PECO:0000126 and PECO:0000012 to PECO:0000136 as a quick fix?

I'm happy to make the changes if that would help and the changes are OK.

**Comment by ValWood** [comment]
whoops will fix in next couple of days. i have a couple of fixes to this file pending so i'll do them all together.

v

**Comment by mah11** [comment]
I have done the fixes for PMID_16371652_phaf.tsv and the files in Quantitative_gene_expression_data/. Leaving phenotype_mapping/ for Val!

(PECO:0000012 -> PECO:0000137)

**Comment by ValWood** [comment]
done  phenotype_mapping/phaf_format_phenotypes.tsv etc

**Comment by kimrutherford** [comment]
Thanks, the data generation for PomBase2 is working now and updating nightly.  I'll sort out some better monitoring of the process so we know when it goes wrong.  pombase/pombase-chado-json#3
