### ISSUE TITLE
feedback on Jacky's sessions

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1179]
I'll document changes I made here, in case anyone can correct me, or we can make improvement on what I have done:

1. curs/8fb498d6aad39666
condition "methanol fixation"
condition "formaldehyde fixation"
condition"live cell imaging"

I'm moving all of these to comments.
To me, these sound like method details. If anywhere they would be subtypes of ECO terms perhaps?
I'll keep the note in comment in case they are useful later if we have more specific evidence codes.

**Comment by mah11** [comment]
Yes, these are experimental techniques rather than conditions.

Strictly speaking, they fit the scope of OBI (Ontology for Biomedical Investigations; http://obofoundry.org/ontology/obi.html) but that ontology is one scary f*%^er. I'd rather leave the info in comments - and I've done similar occasionally - than have to deal directly with OBI in Canto.

**Comment by ValWood** [comment]
- they really do look like shmooing cells! but I agree I kept as tapered, but they look different from other tapered in a subtle way

- added one phenotype
FYPO:0001018
abolished activation of bipolar cell growth

- deleted penetrance=high from normal  phenotypes (these might be copy edit errors, I keep doing this, leaving extensions).

- positive regulation of protein localization to cell tip
I agree with your comment. This should not be “regulation of” s it is directly involved (required). GO is a bit weird, in that  the regulation terms  are not necessarily more specific. 
so these are now
protein localization to cell tip
- [ ] I  will try to find some documentation at GO to explain this.


- changed the allele name and description of tip1Δ299 from
name(description)
tip1(Δ299-461)
tip1Δ299(299-461)
to follow standard for partial amino acid deletion description

Does that make sense?

- [ ] Q tip1 should have pest  motif can these be predicted?

- [ ] Q should human ortholog be? DCTN1

- [ ]  Add a "misc" annotation in Artemis
   tip1 localisation to cell end dependent on microtubule cytoskeleto

- changed my legacy GO annotation from
	GO:0071963	establishment or maintenance of cell polarity regulating cell shape
to
GO:0071964	establishment of cell polarity regulating cell shape
does that sound correct?

**Comment by ValWood** [comment]
/curs/b19dfb2b27f82b53
now through when new terms added. No comments on this session

**Comment by ValWood** [comment]
pombe/curs/f2b0ffda72370b22

I am replacing my old GO annotations 
tea1	GO:0034613	cellular protein localization	IMP	has_input PomBase:tip1
by more specific
tea1 GO:1990896	protein localization to cell cortex of cell tip	IMP	has_input pom1

This will often apply with the legacy GO annotation.
Usually I make a new annotation, to see if I can "go deeper"
Then remove the old annotation. So if you need to you can ask me to delete the old annotation,
or I can do it when we approve.
(these sessions are spot on so I will stop checking them properly soon :) 
I'll just do a cursory check for obvious stuff like copy parse extensions etc.

**Comment by ValWood** [comment]
https://curation.pombase.org/pombe/curs/f2b0ffda72370b22#

Also spot on.
I only changed my GO annotations.

I also removed the GFP and YFP from the  geneotypes.
When we capture these, if the GFP is presumed not to affect the protein we only capture the allele of the  mutated gene. We don't bother with the GFP of the WT localized gene.  
If we did, these would all be multi-gene phenotypes, rather than single gene phenotypes.

**Comment by ValWood** [comment]
curs/ce1fc9c90e999884  PMID:15177031
also spot on.

For future sessions do you want to put the  phenotype term request straight into the FYPO tracker.
https://github.com/pombase/fypo/issues

This way I will start  approve the sessions once the FYPO terms have been created, then I can add the new terms while I am checking, which will save time.

**Comment by ValWood** [comment]
I can't find any documentation on the GO site about "regulation" relationship and terms.

Basically, in the ontology we always try to annotate as specifically as possible. Most terms are related by is_a and Part_of
but all regulation terms are related by the relation "regulates"
As illustrated here:
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0010695#term=ancchart

So we always annotate as specific as possible, but if we don't know if a gene product is "regulating", or "directly involved" we stick  with the parent. 

A gene product  might be  both directly involved and regulating (for example a rate limiting step in a metabolic pathway)
Or neither  (just a phenotype because an upstream process is compromised).

It took us a long, long time to figure out when to use the term itself and when to use regulates. We still don't have good guidelines but  we usually know. We sometimes check with each other if we aren't sure.....

It would be good to have your thoughts on this at a future curation meeting. There are still  some of the cell cycle signalling  where I am not sure.....

So  I'm going to close this ticket, as any tasks are done and the rest was just for reference.
