### ISSUE TITLE
PMID:8087848  cdc2 query

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1183]
JAcky wote:
I was unable to curate the data showing that cdc2 and cdc13 are presence in two different cellular fractions. After high speed spin (310,000g in TL100 15 min) the proteins are present in the supernatant (soluble form) and the pellet (insoluble form). Hear shock treatment destroys the soluble form of both cdc2 and cdc13 in cdc13-117 and cdc2-L7 and cdc13 in wild type (around 30% of cdc2 remains in wild type after heat shock. Therefore when cells undergo re-replication insoluble cdc2 and cdc13 are present but not the soluble form of cdc2 or cdc13.

**Comment by ValWood** [comment]
Q: Does  you think we can use this to annotate cdc2  as "extrinsic to membrane " EXP
(we can assume that with no TM domians it isn't integral, so there is a bit of curator inference in here)

- I have seen papers say that some cdc2 is membrane associated ( some must be at the division site...), but never  seen any data.

**Comment by ValWood** [comment]
Hi @JackyVH do you think this annotation would make sense?

**Comment by JackyVH** [comment]
I'm not sure as it could also be because it is associated with chromatin.  Let me think about it.  Sorry again for being so slow getting back to you !

**Comment by ValWood** [comment]
Its OK we ended up with nearly 300 tickets open on the curation tracker so I am having a blitz!

**Comment by ValWood** [comment]
Actually let's ignore this one. I thought cdc2 was sometimes at the division site, but I don't think it  is is it. That wouldn't make sense because cdc2  is physically separated from cdc25 which is sequestered int eh cytoplasm. I may have imagined it!
