### ISSUE TITLE
compound modifications, what do these mean

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1186]
Mhs6

I notice that on msh6 we have quite a few compound modifications.

I guess this is just saying these are present at the same time (they seem to be modifications on the same fragments).

Do we want to do this though?
It will generate a  lot of redundancy and the combinatorial combinations are endless. Its also not very meaningful  if the resolution of the co-occurance can only apply to fragments  so will only capture when residues are proximal.

Possibly better only to try to capture  the phase  when available and let users  infer whether they co-occur?
Thoughts?
![mhs6 why are these linked like this](https://cloud.githubusercontent.com/assets/7359272/20628064/ef766b90-b31b-11e6-9fec-45742438e917.jpg)

**Comment by ValWood** [comment]
For example
S299 occurs with S303 and S 307
then  with S303 alone
then with S303 and S309
and then with S301........

**Comment by ValWood** [comment]
also on tea2 page http://www.pombase.org/spombe/result/SPBC1604.20c#modifications

**Comment by ValWood** [comment]
midori will munge the file

**Comment by mah11** [comment]
after brief discussion we decided we're willing to lose the tiny bit of information that the multiple-residue extensions add (about which modifications do and don't occur together/simultaneously)

**Comment by mah11** [comment]
done!
