### ISSUE TITLE
Fleig cdc2 paper

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1190]
Hi Jacky, @jvhayles

I updated the alleles here
https://curation.pombase.org/pombe/curs/43f8a34aa26e2202/ro/

 (we can  now construct genotypes where a wt copy expressed with a mutant copy).

I'm assuming  there was always a wt copy of cdc2 (either pombe or human) when  DL2 is used

so these are the genotypes I ended up with,

https://curation.pombase.org/pombe/curs/43f8a34aa26e2202/genotype_manage/ro

is that correct?

**Comment by ValWood** [comment]
Hi @jvhayles did this look OK?

Val

**Comment by ValWood** [comment]
Hi @JackyVH   does this look OK?

Val

**Comment by JackyVH** [comment]
Ill check this tomorrow. Sorry I have left it so long!

**Comment by ValWood** [comment]
pinging you on this one in case you have chance to look. If not we can do on Thurs.
@JackyVH

**Comment by ValWood** [comment]
there was always a WT. If you say a mutant is dominant you always  need to have a WT

**Comment by ValWood** [comment]
This one is in PomBase
