### ISSUE TITLE
dsc1 specificity/ dsc2

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1197]
move the protein processing down to make consistent?
![srebp cleavage](https://cloud.githubusercontent.com/assets/7359272/20833499/f53fe968-b887-11e6-9aa6-885438c01539.jpg)

 - [x] also dsc1 does not have its 
Dsc E3 ubiquitin ligase complex
annotation.

done this one as I happened to be in the session where it should have been

- [ ] And, the GO localization annotation is probably phenotype only? (I can't tell because there is no corresponding phenotype annotation, but likely if  one complex  subunit is mutated localization of other subunits is compromised?

**Comment by ValWood** [comment]
dsc2 protein processing - same as above

**Comment by ValWood** [comment]
- [ ] dsc2 has
regulation of protein glycosylation regulates dsc1
but dsc1 has nothing about protein glycosylation?

**Comment by Antonialock** [comment]
Hmmm
"Multiple lines of evidence demonstrate that Dsc1 E3 ligase activity is required for ER exit of the Dsc complex, thus ensuring that only fully functional Dsc E3 ligase moves to the Golgi where it acts in SREBP activation."

would you change
protein localization to Golgi apparatus

to 
protein targeting to Golgi 

(and add the BP to MF with part_of)

**Comment by ValWood** [comment]
I'm not aware of any pathway for "protein targeting to golgi" proteins are only targeted to the ER, then it's vesicle mediated isn't it? (probably explains why only 17 EXP annotations)

**Comment by Antonialock** [comment]
Yeah I think it said all the dsc proteins have TM domains so I guess it must be vesicle mediated?

**Comment by ValWood** [comment]
I think so....
I'll raise the targeting issue  again at some point. But for now I'll block "protein targeting to Golgi"
for us unless there is a demonstrated mechanism

**Comment by ValWood** [comment]
this will be dealt with by SREBP signalling review. I removed some phenotypes earlier today via another ticket.
