### ISSUE TITLE
flocculins

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1201]
E-mail conversation with Huang made me realise it isn't possible to easily retrieve ALL "flocculins"

Add a protein family grouping

**Comment by ValWood** [comment]
I have a question about flocculation. the paper I approved last week referred to flocculation which occurred on plates. Why is it defined as only occurring in liquid culture?  I'm asking this here before I put it on the GO tracker in case anyone knows.

**Comment by ValWood** [comment]
flocculins (with flocculation annotation):

PTHR31492 fta5	SPAC1F8.06	cell surface glycoprotein
gsf2	SPCC1742.01	galactose-specific flocculin Gsf2
pfl2	SPAPB15E9.01c	flocculin Pfl2
PTHR31492  pfl3	SPBC947.04	cell surface glycoprotein (predicted), DIPSY family
PTHR31492  pfl4	SPCC188.09c	cell surface glycoprotein, adhesion molecule (predicted)
PTHR31492  pfl5	SPBC1289.15	cell surface glycoprotein (predicted)
PTHR31492  pfl6	SPAC977.07c	cell surface glycoprotein, adhesion molecule (predicted)
PTHR31492  pfl7	SPBC359.04c	cell surface glycoprotein (predicted), DIPSY family
PTHR31492  pfl9	SPAC186.01	cell surface glycoprotein (predicted), DIPSY family

PTHR31492 mam3	SPAP11E10.02c	cell agglutination protein Mam3
PTHR31492	map4	SPBC21D10.06c.	cell surface agglutination protein Map4

PTHR31492 SPBC1348.08c	SPBC1348.08c	SPBC1348.08c.1:pep	cell surface glycoprotein, adhesion molecule (predicted)
PTHR31492 SPAPB2C8.01	SPAPB2C8.01	SPAPB2C8.01.1:pep	cell surface glycoprotein, adhesion molecule (predicted)


SPBPJ4664.02	SPBPJ4664.02	cell surface glycoprotein, flocculin, related to Gsf2

**Comment by mah11** [comment]
> Why is it defined as only occurring in liquid culture?

It isn't (at least in GO BP).

**Comment by ValWood** [comment]
I  could swore I saw that in GO, but I don't know where....

**Comment by ValWood** [comment]
I still have a probelm with the ontology.

I think we have been here before. I can't see why flocculation isn't a descendent of adhesion. Flocculation is a  specialised type of adhesion?

**Comment by mah11** [comment]
This question has come up a zillion times. It's a hold-over from the cellular/multi-organism process thing, and GO still has those hacky "cell-cell adhesion involved in flocculation" terms. With the more recent discussions about "cellular process", maybe they can rationalize the flocculation department soon(ish).

**Comment by ValWood** [comment]
I'll go with

MF GO:0050839 cell adhesion molecule binding

and 
BP GO:0043689 cell-cell adhesion involved in flocculation (at least  they will have both parents  for now)

CC GO:0070263 external side of fungal-type cell wall

**Comment by ValWood** [comment]
- [ ] for ease using 
/GO="aspect=F; term=cell adhesion molecule binding; GOid=GO:0050839; evidence=ISM; db_xref=GO_REF:0000024; with=Panther:PTHR31492; date=20161220"

so I'll need to supply refs for the panther family

**Comment by ValWood** [comment]
also
 - [ ]  added flocculin to product where applicable
 - [ ] deleted TAS to adhesion, and made CAnto BP more specific

**Comment by mah11** [comment]
> /GO="aspect=C; term=external side of fungal-type cell wall; GOid=GO:0070263; evidence=ISM; db_xref=GO_REF:0000024; with=Panther:PTHR31492; date=20161220"

For ISM, the correct reference is GO_REF:0000050. I'll fix these if you want, since I'm working on GO_REF upgrades anyway.

**Comment by ValWood** [comment]
ok
