### ISSUE TITLE
pdc1  	protein complex scaffold?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1203]
Is annotated as 
	protein complex scaffold

which complex is it a scaffold subunit for?
it doesn't have a complex annotation.

The binding annotation is to itself, is that correct?

**Comment by Antonialock** [comment]
It doesn't seem crazy based on the abstract for the paper referenced? https://www.ncbi.nlm.nih.gov/pubmed?term=23319050

**Comment by ValWood** [comment]
Ah OK its for P-body.... we can add that as an extension.
I'll do that...I might tweak the product.

**Comment by ValWood** [comment]
I don't think this is necessariy a "protein complex scaffold" in that it provides structural assembly for a protein complex.

https://github.com/geneontology/go-ontology/issues/12123

For now I made it
P-body assembly protein

We can delete the "scaffold" term later is the GO meaning  turns out to be the narrow way I have used it...
