### ISSUE TITLE
cdc2 allele?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1209]
One of these must be wrong:

![fix](https://cloud.githubusercontent.com/assets/7359272/20978344/7a54373c-bca0-11e6-94d1-c4a8686de760.jpg)

**Comment by ValWood** [comment]
Also check that this shows in the logs. I can't remember if we report 
same allele diff name
or 
same name diff allele

**Comment by Antonialock** [comment]
This is fine. The paper reports on two alleles: cdc2-M26 and cdc2-M56. They have the same amino acid change. I could remove one but seeing they are (probably) alleles from a mutagenesis screen and not "cleanly" genereated alleles by PCR the two strains could have different background mutations, and therefore I think we should keep both.
