### ISSUE TITLE
cdc42 GO:0046909 intermembrane transport

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1215]
This is an odd term floating around on its own in GO.

It only has  5 EXP annotations (only 1 pombe)
GO:0046909 intermembrane transport

Its likely the annotation could be better somewhere else?

**Comment by ValWood** [comment]
we also don't capture that cdc42 activates shk1 kinase?
That might be this paper?
https://www.ncbi.nlm.nih.gov/pubmed?term=7597098

**Comment by ValWood** [comment]
see also
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=176845

**Comment by mah11** [comment]
cdc42 fixed for that helpdesk ticket
