### ISSUE TITLE
bgs4 target of

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1218]
Rho-GAP Rga7 plays a role in β-1,3-glucan synthase Bgs4 delivery from Golgi to the cleavage site during cytokinesis [29,30]

Arasada R, Pollard TD. A role for F-BAR protein Rga7p during cytokinesis in S. pombe. J Cell Sci. 2015; 128:2259–68. doi: 10.1242/jcs.162974 PMID: 25977474

Liu Y, Lee I-J, Sun M, Lower CA, Runge KW, Ma J, et al. Roles of the novel coiled-coil protein Rng10 in septum formation during fission yeast cytokinesis. Mol Biol Cell. 2016; 27:2528–41. doi: 10.1091/mbc. E16-03-0156 PMID: 27385337

**Comment by Antonialock** [comment]
both primary and secondary apparently. I made an IMP.

**Comment by Antonialock** [comment]
localization added pending FYPO term / paper approval
