### ISSUE TITLE
isp6  psp3 krp1 yps1 - protein processing?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1242]
has
dibasic protein processing

dibasic protein processing is  part of "protein maturation"
but isp6 appears to be  a vacuolar protease involved in protein catabolism?

(which protein is it processing?)

**Comment by ValWood** [comment]
Also for isp6 the "RNA metabolic process" for isp6 and pnu1 from this paper look dodgy.
https://www.ncbi.nlm.nih.gov/pubmed?term=11872168  From the abstract this really seems to be just about expression level (phenotype only?). It isn't even clear that pnu1 is involved in RNA metabolism, it seems to be a mitochondrial DNA nuclease....

**Comment by Antonialock** [comment]
I updated the annotations to proteolysis, it is a common parent of both terms.

**Comment by ValWood** [comment]
Yep I think proteolysis is as specific as we can be  here...
