### ISSUE TITLE
nfs1 -iron sulfur cluster assembly?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1243]
]nfs1 is involved in tRNA wobble position udidine thiolation,

but it has an iSO to  iron sulfur cluster assembly  (from SGD). Do you think that should be removed?

**Comment by Antonialock** [comment]
I think it should have both based on the def of tRNA wobble position uridine thiolation:
"The process in which a uridine residue at position 34 in the anticodon of a tRNA is post-transcriptionally thiolated at the C2 position. **This process involves transfer of a sulfur from cysteine to position C2 by several steps**." 

In this text it says that small amounts of nfs1 is present in the cytosol (pombe nfs1 is only annotated to mitochondrion)
https://books.google.com/books?id=bp3oBQAAQBAJ&pg=PA527&lpg=PA527&dq=nfs1+ctu1+ctu2&source=bl&ots=aEiVw85Bnd&sig=c2orA-4jg-Bn5O2S0JefhiUf4rE&hl=en&sa=X&ved=0ahUKEwi894qK3czRAhXGPCYKHe14CwwQ6AEIMTAD#v=onepage&q=nfs1%20ctu1%20ctu2&f=false

![screen shot 2017-01-18 at 17 32 12](https://cloud.githubusercontent.com/assets/12727506/22085977/92742f8c-dda4-11e6-8884-a834307c529f.png)

**Comment by Antonialock** [comment]
nfs1 /ctu1 flow from the middle of the diagram to the bottom left

**Comment by ValWood** [comment]
Which  part is the iron sulfer cluster assembly? This seems to show that it isn't involved so I clearly don't understand the figure...

**Comment by ValWood** [comment]
yep I see.....

**Comment by ValWood** [comment]
I made "GO:0002143" an exception in the intersect between  "tRN metabolism" and "cofactor metabolism"

Could you add ISS to any other thiolation pathway that should have "iron sulfur cluster assembly"

**Comment by Antonialock** [comment]
I think it is ok as it is, only one missing is isd11 but it doesn't look like it's been established whether it is involved or not
![screen shot 2017-01-20 at 08 34 38](https://cloud.githubusercontent.com/assets/12727506/22151254/62e4f1be-deeb-11e6-9c27-0231fff53557.png)
