### ISSUE TITLE
isu1/isa1 iron sulfur cluster assemlby or transfer

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1244]
both have

![remove isca and isa1](https://cloud.githubusercontent.com/assets/7359272/21582992/6147085a-d064-11e6-8dc4-13c5534e07db.jpg)

 do the older annotations need removing?

**Comment by Antonialock** [comment]
I think that isu1 should be annotated to both but isa1 should only be annotated to protein maturation. It is an IEA though so I cannot remove it....filter?

![screen shot 2017-01-18 at 16 54 47](https://cloud.githubusercontent.com/assets/12727506/22086369/76685c8a-dda6-11e6-9173-d49003938ff4.png)

**Comment by Antonialock** [comment]
isu1=ISCU
isa1=ISCA1

**Comment by ValWood** [comment]
could you report it on the GO  annotation tracker.
I will add to the filter.
v
