### ISSUE TITLE
gpt1 unfolded protein response?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1245]
this gives a violation, and looks odd as "unfolded protein response" is a signalling pathway

![check 2nd one](https://cloud.githubusercontent.com/assets/7359272/21583034/9c082c3e-d065-11e6-868c-00d2af3dc1ec.jpg)

assign to original curator when canto back

**Comment by Antonialock** [comment]
This was from a genetic interactions paper. I removed the annotations to UPR, I don't think it is very good evidence for BPs.

According to PMID:23066505 the UPR in pombe is different from cerevisiae. In cereivisae, Ire1 activates the UPR by direct splicing of an mRNA. This trigger the increased expression of ER genes and boosts ER protein folding capacity. This role is conserved in metazoa. 

In PMID:23066505 it is shown that in pombe, activation of ire1 leads to the decay of mRNAs that all encode proteins entering the ER. 
"in Drosophila cells that Ire1 induction not only results in splicing of XBP1 mRNA but also mediates enhanced mRNA breakdown. This output of Ire1 activation, termed ‘regulated Ire1-dependent decay’ (RIDD), is conserved in mammalian cells, but not in S. cerevisiae,"

RIDD seems fairly well established
https://www.ncbi.nlm.nih.gov/pubmed/26108623
But there is not GO term for it? Should I request? there is already a term for the "other" downstream happenings from ire1

IRE1-mediated unfolded protein response
 	A series of molecular signals mediated by the endoplasmic reticulum stress sensor IRE1 (Inositol-requiring transmembrane kinase/endonuclease). Begins with activation of IRE1 in response to endoplasmic reticulum (ER) stress, and ends with regulation of a downstream cellular process, e.g. transcription. One target of activated IRE1 is the transcription factor HAC1 in yeast, or XBP1 in mammals; IRE1 cleaves an intron of a mRNA coding for HAC1/XBP1 to generate an activated HAC1/XBP1 transcription factor, which controls the up regulation of UPR-related genes.

**Comment by ValWood** [comment]
I don't really know anything about this, I have only ever annotated to these from inference. Let's leave for now. Can come back to this....

**Comment by Antonialock** [comment]
It's ok, it is not very complicated, 

In cerevisiae/metazoa during ER stress, ire1 cleaves a transcript called HAC1/XBP1, this leads to expression of more folding proteins, and increased folding capacity.

In pombe/meatazoa during ER stress, ire1 selectively degrades "difficult to fold" proteins, thereby giving the protein folding machinery an easier time.

Physiologically it looks like a really important pathway (development, drug target..).

Look at this diagram:
![screen shot 2017-01-18 at 11 19 23](https://cloud.githubusercontent.com/assets/12727506/22072320/07eaae9c-dd70-11e6-85ce-dfbb2bdc5052.png)

"The two Ire1 functions, RIDD and splicing of Xbp1 mRNA, can be uncoupled in vitro, allowing a better understanding of the physiological output of each pathway."

**Comment by Antonialock** [comment]
![screen shot 2017-01-18 at 11 26 03](https://cloud.githubusercontent.com/assets/12727506/22072669/108bacda-dd71-11e6-99e8-16623b1a7792.png)

**Comment by Antonialock** [comment]
i also removed the annotation from cnx1 and ire1 from the interactions paper.

ire1 is now replaced with experimental evidence from 24768994
calnexin has ISO

**Comment by ValWood** [comment]
Hi 

Can you list which annotations were deleted here?
I need to collate them,

Thanks

Val

**Comment by ValWood** [comment]
Interesting. I remember spending ages trying to find hac1...

**Comment by Antonialock** [comment]
hah, typical eh...If this is true then what's pretty cool is that human retained both pathways whereas yeast ditched different ones...seems unusual

**Comment by Antonialock** [comment]
The only annotation that will disappear is
gpt1 	GO:0030968 	endoplasmic reticulum unfolded protein response 	IMP 	

From the same paper ( PMID:22682253) I also removed the same annotation from cnx1 and ire1 (because the evidence wasn't very good in that paper) but I found a different paper supporting an exp annotation for ire1 and cnx1 will have an ISO.

**Comment by ValWood** [comment]
was this "indirect" or just plain "annotation error"

**Comment by Antonialock** [comment]
weak evidence, genetic interactions and nothing else. I think the annotation is correct for ire1 but not gpt1

**Comment by ValWood** [comment]
OK thanks!
genetic interactions are not good unless there is a really strong phenotype uniquely associated with the process.
