### ISSUE TITLE
grx5- iron sulphur cluster assembly?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1246]
assembly or transfer?

![grx5](https://cloud.githubusercontent.com/assets/7359272/21583066/0bf8d90c-d067-11e6-9e63-fe1ad375ce62.jpg)

should the ISS be deleted?

**Comment by Antonialock** [comment]
based on the def for iron sulphur cluster assembly: "The incorporation of iron and exogenous sulfur into a metallo-sulfur cluster", I think yes

the red and yellow blobs is the iron sulfur cluster, by the time grx5 touches it (in the middle) the cluster is assembled and is being ferried to target proteins..

**Comment by Antonialock** [comment]
Looks like it had been removed alread...it's not here
http://pombase2.bioinformatics.nz/gene/SPAPB2B4.02
:-)

**Comment by ValWood** [comment]
GO:0016226	iron-sulfur cluster assembly	ISS	UniProtKB:Q02784 (delted)

Ask SGD to update?

**Comment by ValWood** [comment]
done
