### ISSUE TITLE
din1- small tweaks

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1248]
1. Can "mRNA catabolic process" move down to "nuclear transcribed..."

2.  positive regulation of ribonuclease activity by IPI? Is that correct. If so should it be an MF (enzyme regulator)? and can the "substrate" be added?

![din1](https://cloud.githubusercontent.com/assets/7359272/21594537/8fb457bc-d11b-11e6-9ad4-77c7e5912079.jpg)

**Comment by Antonialock** [comment]
din1 is a pyrophosphohydrolase, so it removes diphosphates from triphosphates (yielding monophosphates)
din1 binds dhp1
dhp1 is a XRN exoribonuclease, these have exclusive activity against RNA with 5’ monophosphates

so basically it looks like these two act together to degrade uncapped (5' triphosphorylated) RNA - din1 removes 2 phosphates to 'prime' the RNA for dhp1 - I guess that's what I meant by +ve reg.

I have:
- removed "positive regulation of exoribonuclease activity"
- added "nuclear-transcribed mRNA catabolic process, exonucleolytic, 5'-3' " 

It looks like the authors think it is mRNA catabolism "Mutagenesis and biochemical studies demonstrate that Rai1 possesses pyrophosphohydrolase activity towards 5’ triphosphorylated RNA. Such an activity is important for mRNA degradation in bacteria"

However, FYI, there is also a GO termfor "las1 complex" (4 proteins including these two) that process rRNA. 
https://www.ncbi.nlm.nih.gov/pubmed/26638174

...but I think my annotations should be ok now based on the info in the pombe paper...
reopen if you have anything to add...

**Comment by ValWood** [comment]
No need
https://github.com/pombase/curation/issues/1249

**Comment by ValWood** [comment]
BTW did you remove old redundant ISOs?

**Comment by Antonialock** [comment]
done
