### ISSUE TITLE
tdh1 Are these 2 annotations saying almost the same? 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1252]
![2 ways same](https://cloud.githubusercontent.com/assets/7359272/21595497/649384c6-d126-11e6-88b4-3c23a933b1ec.jpg)

**Comment by mah11** [comment]
These look like they're saying tdh1 regulates two different signal transduction pathways, one phosphorelay and one MAP kinase cascade. So no, they don't say the same thing as each other.

Whether they're both correct is a different question; I haven't read the paper so can't answer it off the top of my head.

**Comment by ValWood** [comment]
But the stress-activated MAP kinase cascade is a phosphorelay isn't it? (MAP kinases)

maybe will be clearer with "regulates" targets...

**Comment by mah11** [comment]
No. Phosphorelays are those pathways with the phospho-histidine thing - see GO:0000160 def. Completely separate from MAPK and most other kinase cascades.

**Comment by ValWood** [comment]
Oh yes sorry, they are MAK, but  aren't they considered part of 
GO:0031098
stress-activated protein kinase signaling cascade?

I'm not keen on those "signalling module type terms" in GO. It would be better/more consistent is we just said the type of signal transducer  (MF) and signalling involved in  pathway/process.

WE have 4 axis of classification in GO, module, pathway, response type/process regulated.

Anyway that's for another day...

**Comment by mah11** [comment]
I don't know, but that's a separate question, isn't it? The annotations you asked about here are MAPK cascade and phosphorelay, which are different.
