### ISSUE TITLE
wdr70 - check genotype

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1254]
I think this is just a gene replacement, in which case it isn't necessary to  specify the deletion, that's a given?

![deletion required](https://cloud.githubusercontent.com/assets/7359272/21597173/0712669c-d13e-11e6-9aa2-31d21d2b4743.jpg)

**Comment by mah11** [comment]
These are two separate single mutations, each of which causes the phenotype. (Scroll up to see the "FYPO Single-Allele Phenotypes" box header ...)

**Comment by ValWood** [comment]
Oh yeah, dopey...
