### ISSUE TITLE
Rlc1 prority paper, MF for LEGO

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1256]
For @vanaukenk 
https://www.ncbi.nlm.nih.gov/pubmed/19570908
 Regulation of fission yeast myosin-II function and ...
www.ncbi.nlm.nih.gov
1. Mol Biol Cell. 2009 Sep;20(17):3941-52. doi: 10.1091/mbc.E09-04-0346. Epub 2009 Jul 1. Regulation of fission yeast myosin-II function and contractile ring dynamics ...

From kimberley

**Comment by mah11** [comment]
paper curated, and will get a moment in the spotlight on the 28 Feb GO call
