### ISSUE TITLE
gsk31 missing BP

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1265]
gsk31 has status "	biological role inferred" but no BP - role of GSK-3 must be known?

**Comment by ValWood** [comment]
I don't think its clear what gsk31 is doing. gsk3 is annotated...

**Comment by Antonialock** [comment]
ok, I had a look at PMID:27604537 but I couldn't get any processes out of it.

**Comment by ValWood** [comment]
its one of those proteins you imagine we know loads about, but we know nothing really other that its a protein kinase....
