### ISSUE TITLE
Matrix annotation check PMID:25401760

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1268]
Might be ok, some ribosomal proteins are assembly, but they aren't usually also translation

rpl701
	endonucleolytic cleavage involved in tRNA processing
	endonucleolytic cleavage in ITS1 to separate SSU-rRNA from 5.8S rRNA and LSU-rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)

looks kind of odd....

**Comment by Antonialock** [comment]
Let me know if you think this is crazy.

From this publication it really looks like rpl701 is involved in trna and rrna processing. 

> Our preparation, however, contained one additional protein subunit, Rpl701, which had not been identified in RNase MRP of any organisms studied. Rpl701, generally known as subunit L7 of the large ribosome, was reproducibly detected in the RNase MRP complex prepared multiple times. Furthermore, the reverse pull-down analysis using a tagged Rpl701 as bait allowed isolation of RNase MRP from S. pombe cells, whereas tagged Rpl702 or Rpl703, the paralogs of Rpl701, failed to recover the enzyme complex (Figure S4). Thus, we concluded that Rpl701 is a novel component of RNase MRP in S. pombe.

> Our purified RNase MRP preparation cleaved a synthetic substrate, trailer+tRNAMet, and produced a “trailer” nucleotide with 3′-OH and tRNAMet with a 5′-phosphate (Figure 3D). This is consistent with the cleavage specificity reported for RNase MRP. 

The Matsayama paper did not detect any rpl701 in the cytosol, only in the nucleus. The paralog rpl702 in contrast was detected in the cytoplasm. tRNA biogenesis happens in the nucleus. 

Is it crazy to think that rpl702 could have a role in translation and rpl701 has a role in r/t-RNA processing? (there is also an rpl703) 

For now I will remove the rpl701 ISO to cytoplasmic translation, cytosolic large ribosomal subunit, & 	structural constituent of ribosome. I'm changing the product to "RNase MRP subunit".

Reopen if you want it reversed (and you want overlaps in the matrix ;-) )
If we want to change it back then this is what I took out:

/GO="aspect=F; term=structural constituent of ribosome; GOid=GO:0003735; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000003044; date=20060530"
/GO="aspect=P; term=cytoplasmic translation; GOid=GO:0002181; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000003044; date=20060530"
/GO="aspect=C; term=cytosolic large ribosomal subunit (sensu Eukaryota); GOid=GO:0022625; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000003044; date=20060530"
/product="60S ribosomal protein L7"

**Comment by ValWood** [comment]
Not crazy, but I thought that the Rpl7-like protein  was SPAC664.06
.....will dig deeper...

=

Similarly, RPL7/RPL7
IPR000517 PF00327

SPAC664.06 YNL002C  (are orthologs and are involved in ribosome biogenesis)

SPBC18H10.12 and SPAC3H5.07 YGL076C|YPL198W (are orthologs and are involved in translation)

**Comment by ValWood** [comment]
Its OK, Rpl7 is a completely different thing.

But yes, there is a precedent for the ribosomal paralogs to have slightly different roles.


This makes it impossible to make sensible inferences because the paralogs are more closely related to each other...

and the same situation occurs at SGD for RPL7a and RPL7b

https://www.ncbi.nlm.nih.gov/pubmed/19466602

I'm not keen on changing the product to "RNase MRP subunit".

I think it should be
60S ribosomal protein L7a involved in ribosome biogenesis
60S ribosomal protein L7b involved in cytoplasmic translation
so that it is clear at a glance why they are differently annotated.
(I'm not sure that it is really a MRP complex subunit,  probably a substrate?)

This is  a  big problem with all of the ribosomal paralogs, which tend to get annotated to both cytoplasmic translation  AND ribosome biogenesis. At least this one is sorted though!

**Comment by Antonialock** [comment]
1. ok but why don't they see rpl701 in the cytoplasm?

2. If it is a substrate then how is it involved in biogenesis? 

3. also should it be annotated to ribonuclease MRP complex ? 


(this is why I hate tracker tickets, they always get reopened :p)

**Comment by ValWood** [comment]
I'm agreeing with you. Only needs product name change :)

**Comment by ValWood** [comment]
You can annotate to MRP complex, but I think we should keep the ribosomal designation, and just say "involved in ribosome assembly"

OK, not substrate, but just associated. These are difficult to assess, because the ribosomal proteins are always contaminants in proteomics experiments, and are present in such excess. If we annotate to MRP its there for follow up, without making a big thing about it.....

**Comment by Antonialock** [comment]
Yep, that's why I thought this was reassuring:

> Furthermore, the reverse pull-down analysis using a tagged Rpl701 as bait allowed isolation of RNase MRP from S. pombe cells,

**Comment by Antonialock** [comment]
Yep, that's why I thought this was reassuring:

> Furthermore, the reverse pull-down analysis using a tagged Rpl701 as bait allowed isolation of RNase MRP from S. pombe cells,

**Comment by Antonialock** [comment]
products updated to 
60S ribosomal protein L7a involved in ribosome biogenesis
60S ribosomal protein L7b involved in cytoplasmic translation
