### ISSUE TITLE
ire1 RIDD pathway

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1270]
from #1245 

there is no GO term for RIDD pathway
 
![screen shot 2017-01-18 at 11 26 03](https://cloud.githubusercontent.com/assets/12727506/22080649/55bef2e0-dd8e-11e6-875f-549172aeadce.png)

(A) S. cerevisiae Ire1 is activated by ER stress. Upon activation, Ire1 undergoes trans-autophosphorylation and oligomerization. HAC1 mRNA is spliced by activated Ire1 through its RNase domain. Upon translation, transcription factor Hac1 up-regulates UPR target genes to restore homoeostasis.

(B) In S. pombe upon ER stress, Ire1 triggers downstream RIDD; the protein BiP1′s poly-A tail is recognized and cleaved by RIDD, but BiP1 protein is stabilized despite the cleavage of its mRNA. BiP1 protein is important for cell survival during stress condition; there are possible unknown candidates also involved in stress response, either in ER lumen or on ER membrane.

**Comment by ValWood** [comment]
RIDD= regulated Ire1-dependent decay

I used
IRE1-mediated unfolded protein response (GO:0036498)

I guess 
RIDD= regulated Ire1-dependent decay
should be a synonym, and the definition broadened?

**Comment by ValWood** [comment]
I think this is OK for now
