### ISSUE TITLE
reserve block of  ncRNA IDs for JB

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1272]
Would like  to reserve a block of IDs for 5775 lnRNAs.

I suggest we  let him begin at 2000 and avoid anything in the range 2000-8000 

Does that sound OK?

**Comment by ValWood** [comment]
where should we record this? wiki?

**Comment by Antonialock** [comment]
I don't know what's best..

**Comment by ValWood** [comment]
Also discussion about
CUTs, DUTs and XUTs
will ask Jurg/ Sam to define and request SO terms.

**Comment by ValWood** [comment]
Will close this ticket. For now we only need to be mindful if any other ncRNAs turn up in the interim....
