### ISSUE TITLE
is this correct parentage for genetic imprinting at mating type locus?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1277]
@Antonialock 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0071171#term=ancchart

this has  "imprinting" as "regulation of mating type switching"

I would have said part of (I think)
Is this regulation?

**Comment by ValWood** [comment]
I think this is because genetic imprinting is described as

Any process that modulates the frequency, rate or extent of the chemical reactions and pathways involving macromolecules by a mechanism that is mediated by DNA, is mitotically or meiotically heritable, or is stably self-propagated in the cytoplasm of a resting cell, and does not entail a change in DNA sequence.

Does that definition make sense?

**Comment by ValWood** [comment]
I think there is a reason why  genetic imprinting t the mating type locus is not always a type of "regulation of gene expression" but I can't remember what.  Anyone?

**Comment by Antonialock** [comment]
I don't know...I have never thought about this before.
From 22209903
The switching process is initiated by a DNA strand-specific epigenetic entity, called an imprint, found at the junction of the homology-box H1 and the mat1 allele-specific sequence (Figure 1). The imprint is either a strand- and sequence-specific nick and/or two ribonucleotides incorporated in DNA . Three genes (swi1, swi3, and swi7) are required for synthesis of the imprint.


DNA replication of the imprinted strand at mat1 is thought to create a transient double-strand break (DSB) in the resulting chromatid. The DSB is repaired by recombination by copying P or M information from one of the two donor loci through the synthesis-dependent strand-annealing (SDSA) mechanism. This strand-specific imprinting/segregation mechanism explains the generation of one-in four-granddaughters switching pattern observed in cell pedigrees


In this study, we found evidence that the mat1-Mc gene dictates directionality in M cells such that mat2 is preferred over mat3 as the donor for switching. Moreover, we discovered the mechanism of this preference. Specifically, Mc induces the transcription of a shorter form of swi2 mRNA by activating a previously uncharacterized promoter, which lies within the 5′-end side of the ORF of the longer form of the swi2 gene. We also found that Abp1 similarly dictates directionality by inducing swi2S mRNA synthesis. Furthermore, a new cis-acting element, SRE2, located next to mat2 was identified, and that also facilitates mat2 utilization. 

![screen shot 2017-02-01 at 14 29 53](https://cloud.githubusercontent.com/assets/12727506/22510798/2bf0a384-e88b-11e6-824e-3fdab876e13e.png)

**Comment by mah11** [comment]
Re ancestry of imprinting at mat locus:

I think it makes sense as regulation because having the imprint constrains switching to one chromatid. The actual switching process is the replacement of one DNA sequence with another, and its parts are donor selection and the actual recombination resulting in gene conversion.

(iirc cerevisiae switches in G1, so doesn't need a comparable constraint because there's only one copy of the chromosome present)

But I also think the standard regulation def wording isn't fully adequate because "modulates the frequency, rate or extent" doesn't cover regulating where a process happens.

**Comment by mah11** [comment]
> Does [the genetic imprinting] definition make sense?

I bet it could be worded more gracefully, but it doesn't look fundamentally wrong (tho I'm not at all an expert on imprinting).

> I think there is a reason why genetic imprinting t the mating type locus is not always a type of "regulation of gene expression" but I can't remember what.

Because what it's regulating - mating type switching - isn't a gene expression process.

**Comment by ValWood** [comment]
thanks!
