### ISSUE TITLE
evaluating regulation annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1278]
What can be classed as regulation?

So we have 1161 gene products annotated to biological regulation.

So far, regulation is always 

1. Within process, in which case it is one MF directly regulating another molecular function
2. Upstream, in which case it is  signalling or otherwise regulating  a) gene expression, or b) catabolism/stability
3. regulation of a biological quality

Violators below (after fixing some obvious ones and  removing those with no regulation annotation on PomBase 2) 

Midori @mah11 
cdt1	replication licensing factor Cdt1 
mcb1	MCM binding protein homolog Mcb1 
fml1	ATP-dependent 3' to 5' DNA helicase, FANCM ortholog Fml1 
rad55	RecA family ATPase Rad55/Rhp55 
dmc1	RecA family ATPase Dmc1 
rlp1	RecA family ATPase Rlp1 
brc1	BRCT domain protein Brc1 
rdl1	RAD51D-like protein 1  (possible mf regulator?)
 - [ ] ssa2	heat shock protein Ssa2 
 - [ ] mas5	DNAJ domain protein Mas5 (predicted) 
We identify the Ssa2-Mas5/Hsp70-Hsp40 chaperone complex as repressor of the heat shock transcription factor Hsf1 (looks like potential for mf regulator, or regulation of transcription annotation?)

Val

lsd2	histone demethylase SWIRM2 (predicted) 
 - [x] SPBC36.10	mitochondrial intermembrane space protein....(predicted)  (Indirectly upstream, appears to be phopsholipid translocation, metabolism is indirect"
- [x] SPBC646.08c	oxysterol binding protein (predicted)  Appears to bedownstream. Primary role most likely ergosterol metabolism (is ER)
- [x] scw1	RNA-binding protein Scw1  deleted annotation in artemis, paper not curated but it would not reach our current regulation annotation guidelines, phenotype only
- [x] naa20	NatB N-acetyltransferase complex catalytic subunit Naa20 (predicted) 
- [x] wdr21	WD repeat protein, human DDB1 and CUL4-associated factor 4 ortholog Wdr21 
punted by GO:0070647
- [x] nab2	poly(A) binding protein Nab2 (predicted)  issues/12991
- [x] nup132	nucleoporin Nup132 
- [x] SPBC1773.17c	glyoxylate reductase (predicted)  old IC annotation deleted. Glyoxylate cycle definitely feeds gluconeogenesis  (upstream) but I don't find any evidence that this particular step is regulatory
 - [x] swf1	palmitoyltransferase Swf1 (predicted)  indirect upstream, already removed
 - [x] lsd1	histone demethylase SWIRM1  (regulation of gene expression)
- [x] per1	plasma membrane amino acid permease Per1  regulation of nitrogen utilization -> nitrogen utilization
- [x] mcp1	microtubule binding protein Mcp1  regulation of microtubule depolymerization -microtubule depolymerization
- [x] gti1	gluconate transmembrane transporter inducer Gti1  (signal transduction)
- [x] any1	arrestin-related endocytic adaptor Any1  (ubiquitin-dependent endocytosis can exclude this process as is regulatory ...catabolism of proteins via vacuole)
- [x] hpz1	zf-PARP type zinc finger protein, G1-S transition regulator Hpz1  (Not sure why this was in the list as it is regulation of phase transition)
- [x] blt1	ubiquitin domain-like protein Blt1  (Not sure why this was in the list as it is regulation of phase transition)
- [x] SPBC36B7.08c	nucleosome assembly protein (predicted)  fixed by
/GO="aspect=F; term=acetyltransferase activator activity; GOid=GO:0010698; evidence=ISS; db_xref=GO_REF:0000024; with="SGD:S000005190 date=20170203"

Antonia
- [x] mfm1	M-factor precursor Mfm1  (@Antonialock changed to  changed to pheromone-dependent signal transduction involved in conjugation with cellular fusion)
- [x] mei2	RNA-binding protein involved in meiosis Mei2 - seems fine, see discussion
- [x] csi1	mitotic centromere-SPB clustering protein Csi1  @Antonialock should spindle elongation be phenotype only (upstream?)
- [x] bob1	prefoldin subunit 5 (predicted)  @Antonialock  is this regulating conjugation?
- [x] myo51	myosin type V 
- [x] rhn1	RNA polymerase II transcription termination factor homolog (@Antonialock  changed regulation of conjugation to phenotype only)
- [x] pac1	double-strand-specific ribonuclease Pac1  (@Antonialock  changed to phenotype only)
- [x] dni1	tetraspan protein Dni1  (@lock changed to involved in)
- [x] hsp9	heat shock protein Hsp9 - this one seems fine, see below

Approved violators, via imprinting...
 - [x] sap1	switch-activating protein Sap1  (upstream regulation of where the process occurs)
- [x] rtf2	replication termination factor Rtf2  ) via imprinting...
- [x] rtf1	replication termination factor Rtf1  via imprinting...

clearly regulating gene expression in some way, but not by ontology term
- [ ] iss10	Mmi1-driven selective elimination factor Iss10 
- [ ] mmi1	YTH family RNA binding protein Mmi1 
- [ ] msa1	RNA-binding protein Msa1 

from the same paper, hetrogeneous mix, (DNA repair) this paper crops up a lot as matrix outliers too:
- [x] kms1	meiotic spindle pole body protein Kms1 
- [x] mto1	MT organizer Mto1 

extent of heterochromatin assemlby
- [x] bdf2	BET family double bromodomain protein Bdf2 
- [ ] leo1	RNA polymerase II associated Paf1 complex (predicted) 

end point of a signal transduction pathway?
- [ ] hta2	histone H2A beta 
- [ ] hta1	histone H2A alpha 

replication fork protection (is a child of GO:2000104 negative regulation of DNA-dependent DNA replication) is that correct.
I don't even know if this should really be a term...it's one of my old ones...
- [ ] nse6	Smc5-6 complex non-SMC subunit Nse6 
- [ ] nse5	Smc5-6 complex non-SMC subunit Nse5 
- [ ] swi3	replication fork protection complex subunit Swi3 

For some they could be classified as above.
For some I'm not sure we can say "regulation"
I'll flag some for checking, but only 62 violators currently.....

Leaving these for now: 
 - [x] rpb7	DNA-directed RNA polymerase complex II subunit Rpb7  and rpb7 might be phenotype only...its a tricky one. it interacts with mediator (which is gene specific regulation). perhaps mutations prevent mediator association with pol II but does  this make it a regulator?

- [x] peg1	CLASP family microtubule-associated protein 
- [x] mto2	MT organizer Mto2 
I think they are likely MF regulators...

**Comment by ValWood** [comment]
I divied up a few for us to check at opportune moments.

There may be types I have missed (substrate inhibition, we might want to annotate that an upstream enzyme regulates  a downstream enzyme in this way, and that would not fit the above.

So, either fix, or  add the reason/type of regulation after the list item in parentheses)

v

**Comment by ValWood** [comment]
Also feel free to take others further down the list if you recognise them. I'm pretty impressed that the list is so short.

**Comment by ValWood** [comment]
So essentially here, we need to know why the above are classed as regulating a process, rather than directly involved in....( I think they are mainly within process, so the assumption is that they are  should usually be MF regulators)

**Comment by ValWood** [comment]
This might be obvious but being not required for a process doesn't automatically mean that a gene product is a regulator. It might operate redundantly, or be required for fidelity etc.

**Comment by mah11** [comment]
I think what would help me more would be to understand how the violators have been identified as, well, violating. IOW, what are the criteria for "being a violator"?

I feel as though I'll need to know that to be able to tell when I've fixed one, or defined why it's an allowable exception.

**Comment by ValWood** [comment]
it isn't one of these:

Within process, in which case it is one MF directly regulating another molecular function
Upstream, in which case it is signalling or otherwise regulating a) gene expression, or b) catabolism/stability
regulation of a biological quality

So there is not indication from the annotation that it is either 
i) involved in signal  transduction or the regulation of gene expression
ii) A molecular function regulator (or regulation of molecular function) descendant annotation
iii) Regulation of biological quality annotation
iv) catabolism (I  haven't been so fussy here about  'regulation' because it isn't always annotated as 'regulation of" but this is clearly a common way to regulate processes....

Does that make sense?

There may be more 'types' that I have overlooked....

**Comment by mah11** [comment]
I guess my question could be more specifically phrased as "how did you determine that the genes listed here don't meet your 'within process or signaling or reg-of-quality' criteria?".

**Comment by ValWood** [comment]
query builder...

**Comment by mah11** [comment]
what query parameters?

**Comment by ValWood** [comment]
I began with "biological regulation" and then subtracted 
"molecular function regulator" (and regulation of molecular function)
"signal transduction"
"regulation of gene expression"
"protein catabolic process" (although this may include non regulators)
"regulation of biological quality"
"regulation of cell cycle transition" (because although not All annotated as signal transducers these are clearly signalling pathways)

I did this last month and weeded out a  few of my old PomBase/Artemis annotation which have not come through yet, and I fixed some more yesterday. So currently this query will generate more than are in this ticket. These are just the remaining ones....

So you won't yet get these results from the query.

**Comment by ValWood** [comment]
More thoughts.
I don't think a mutant phenotype which affects the rate of a process, for a gene product which is  clearly involved in a process, is enough for a "regulation" annotation.
The rate is likely to be affected in the mutant of a gene involved in a process, but this does not  necessarily imply that the gene product is a regulator in a normal situation. The process could be happening more slowly because it is  a bit stuffed.
They would need to do more to show it was a regulator (which activity it directly regulated, OR showing that wt over expression increased the rate of the process).
This might be obvious.

**Comment by ValWood** [comment]
For some, they are clearly involved directly in a process, and regulating it (by regulating some molecular function) . But as yet we don't know the exact mechanism  of the regulation

For example
 - [ ] eso1	mitotic cohesin N-acetyltransferase/DNA polymerase eta Eso1 fusion protein 
(the acetyltransferase is part of cohesion and somehow regulates it. I think that  somehow the cohesin only becomes 'locked on' if the  psm3 is acetylated ...I'm not totally sure that this is regulation, but can allow this for now...

- [ ]  chr4	1,3-beta-glucan synthase regulatory factor Chf3/Chr4  Cfh3p is a regulatory protein for Bgs1p, but we don't know the mechanism

**Comment by ValWood** [comment]
wpl1 should be in this list, but isn't???

**Comment by mah11** [comment]
I'm gonna open a new ticket for cdt1 because it's a bit complicated. But it's been fun looking back into it.

**Comment by ValWood** [comment]
autophagy related

- [ ] vps38	phophatidylinositol 3-kinase complex subunit Vps38

**Comment by mah11** [comment]
**brc1**
GO:0000018      PMID:15972456   IMP

Old annotation in Artemis, now deleted. Might be only phenotypes when the paper gets done in Canto.

**Comment by mah11** [comment]
**mcb1**
GO:1903463      PMID:21813639   IMP
Mcb1's actions aren't yet well characterized at the molecular level. There are plenty of phenotype annotations from this paper, so I could easily delete the GO BP. But it doesn't have any others - @ValWood, are you happy with it not having any BP (or MF) annotations?

**Comment by ValWood** [comment]
So why not just "DNA replication"? instead of "regulation"?

**Comment by mah11** [comment]
It's been a while, but probably because the authors interpreted the phenotypes to mean that Mcb1 acts via some effect on the MCM complex, rather than more directly in replication. But it wouldn't be a big deal to change it if that's what you prefer.

**Comment by ValWood** [comment]
so again this will depend if pre-initiation is part of initiation?

**Comment by mah11** [comment]
For mcb1 it's even broader than that, because its role hasn't been pinned down as precisely as initiation, elongation, or both.

**Comment by mah11** [comment]
aaaanyhow, plodding along ...

**swi3**
GO:0071515      PMID:15059961   IMP
GO:0043111      PMID:15367656   IC
GO:0048478      PMID:15367656   IDA

From a quick overview, it looks correct for swi3 to be annotated to GO:0043111 and GO:0048478. It inherits biological regulation annotation due to paths in GO for those two terms, i.e. it's not annotated directly to anything with "regulation" in its name. There are some other problems with the current swi3 annotation (e.g. a TAS cites the wrong paper), which I think 'n hope will be sorted by whoever tackles it properly (probably won't be me any time soon), but they don't make a big difference to the regulation annotation. As noted, that comes from the ancestry of terms for processes swi3 is directly involved in.

GO:0043111 ! replication fork arrest
GO:0048478 ! replication fork protection

**Comment by ValWood** [comment]
Yep Its the replication fork protection parentage. I dislike that term as a process ( know I created it...see my comment for nse5 and 6 complex above).... I will add swi3 to this list.

**Comment by mah11** [comment]
Replication fork arrest also has is_a GO:2000104 ! negative regulation of DNA-dependent DNA replication ... but I can see the rationale for that, since arrest does make replication stop for a while. Wonder if it should move down to regulation of elongation?

**Comment by Antonialock** [comment]
mfm genes changed to pheromone-dependent signal transduction involved in conjugation with cellular fusion

**Comment by Antonialock** [comment]
I think mei2 is a regulatory protein, though it is not 100% clear what it does, it seems to play a role at multiple steps

"Hence, the key molecular function of the Mei2 dot in fission yeast is most likely to be the shutdown of the DSR-Mmi1 system during meiotic prophase"
" the evidence indicates that Mei2 plays a key role in sequestering and inactivating Mmi1,  an  RNA-binding  protein  crucial  for  the removal of hazardous meiosis-specific mRNAs during the mitotic cell cycle."
(so it negatively regulates the negative regulators?)
(https://www.jstage.jst.go.jp/article/pjab/86/8/86_8_788/_pdf)

I think it also played a role for premeiotic synthesis, and for G1 arrest

"It remains puzzling, however, how Mei2 participates in the earlier steps of sexual differentiation, i.e. G1 arrest and mating, even though it is not absolutely necessary for these steps. One possible explanation has emerged from our recent study; activated Mei2 was found to enhance the expression of ste11 through a positive-feedback loop involving the stress-responsive MAP kinase pathway (Sukegawa et al., 2011). Ste11 is a major transcription factor controlling the switch from cellular proliferation to sexual differentiation (Sugimoto et al., 1991; Otsubo and Yamamoto, 2012). Thus, lack of the full expression of ste11 in the absence of Mei2 function might result in lower mating efficiency.

**Comment by ValWood** [comment]
OK for mei2...seems likely some way regulating gene expression. Just make a note and tick this one...

**Comment by mah11** [comment]
**rad55, dmc1, rlp1, rdl1**

    rad55   GO:0010520      PMID:25414342   IMP
    rad55   GO:0010520      PMID:25414342   IGI     PomBase:SPCC4G3.05c (mus81)
    
    dmc1    GO:0010520      PMID:25414342   IMP
    dmc1    GO:0010520      PMID:25414342   IGI     PomBase:SPAC3C7.03c (rad55)
    dmc1    GO:0010520      PMID:25414342   IGI     PomBase:SPBC28F2.07 (sfr1)
    
    rlp1    GO:0010520      PMID:25414342   IMP
    rlp1    GO:0010520      PMID:25414342   IGI     PomBase:SPCC4G3.05c (mus81)
    
    rdl1    GO:0010520      PMID:25414342   IMP
    rdl1    GO:0010520      PMID:25414342   IGI     PomBase:SPCC4G3.05c (mus81)

We discussed the GO:0010520 annotations from PMID:25414342 around when the curation was done, and decided to keep them. Unless you've changed your mind since then I'll leave them in. This is the email exchange (first bit is from me, then it alternates between Val & me):

> > > I wonder whether some of the genes in this session could be annotated to regulation of meiotic recombination* based on the phenotypes, to reflect the effect on whether you get crossovers and/or gene conversion. I'm not sure, because even if the mechanism is understood I haven't got my head round it, and actually it sounds as though the authors aren't sure about mechanism either.
> > >
> > > I also don't know which part(s) of meiotic recombination are affected - strand invasion? joint molecule formation? DSB processing? some or all of the above? just looking at part_of GO:0007131 in GO, and it's not making my head spin any slower.
> > >
> > > Would you add the high-ish level reg of meiotic recomb if you were doing this approval?
> > >
> > > * i.e. GO:0010520 regulation of reciprocal meiotic recombination
> >
> > I think I would have added "reciprocal meiotic recombination" as I'm not sure how to judge regulation vs directly involved in vs both from just genetic interactions without knowing more about the pathway.
> >
> > But, I think you are suggesting "regulation" because these interactions somehow  dictate the *choice* of pathway?
>
> Exactly. If I'm interpreting correctly, the effects of the mutations on which pathway gets used suggests the gene products may be involved in regulating that pathway choice (and that wouldn't rule out some or all of them also having a direct role in recombination). But I'm not sure they're sure how it works, so I'm not sure whether to make any annotation, let alone recomb vs. regulation.
>
> > I think I could go with either.
>
> I could put in the regulation term, and explicitly ask Alexander if it looks sensible.

(Alexander Lorenz subsequently reviewed the session and had no problem with the GO:0010520 annotations. It's https://curation.pombase.org/pombe/curs/903cb37e16a1d237/ro/)

**Comment by mah11** [comment]
**fml1**

    GO:0045128      PMID:22723423   IMP

https://curation.pombase.org/pombe/curs/37ebf9ba3b26613d/ro/

I don't know this stuff well at all. It looks like there are fml1 phenotypes consistent with it doing "regulation" in the same sense as for the rad55 etc. annotations - in meiotic recombination, whether breaks are repaired in a crossover or non-crossover way. I'm really guessing now: maybe the curator (Matthew Whitby) chose negative regulation of recombination because there's more crossing over in fml1delta and less with overexpression. Fml1 unwinds D loops and to the extent that I can follow the model in the last figure, that appears to be how it influences how many breaks are repaired with crossovers. But it all does my head in.

**Comment by mah11** [comment]
**ssa2, mas5**

I happened to notice that these two had been added to my list in the original summary since I last looked at it on Friday. I strongly recommend that you NOT make any further additions in the main summary or existing comments, because we don't get email notification for edits. Use new comments instead.

Anyway, on to annotations ...

    ssa2            GO:1900035      PMID:24146635   IMP
    mas5            GO:1900035      PMID:24146635   IMP

These were made by community curator Aleksandar Vjestica in https://curation.pombase.org/pombe/curs/c29f51c4cc86096d/ro/.

I haven't gone back through the paper in as much depth as when I reviewed the session, but from briefly revisiting it, the Ssa2/Mas5 experiments show phenotypes only, so I don't think there's enough detail to identify an MF regulator (even for the "high Hsf1 activity" claim, it's inferred from phenotypes). We could perhaps say regulation of transcription if you're comfortable inferring that much from these phenotypes:

mas5

    mas5Δ	FYPO:0002934	altered mRNA level during vegetative growth	Transcript expression level evidence		Global gene expression profile (RNAseq) of deletion similar to that of heat-stressed wild type.	
    mas5Δ	FYPO:0003152	increased protein level during cellular response to heat	Microscopy			assayed_using hsp90 | 
    mas5Δ	FYPO:0003151	decreased protein level during cellular response to heat	Microscopy			assayed_using PomBase:gef1 | assayed_using scd1 | assayed_using rga4

ssa2

    ssa2Δ	FYPO:0002934	altered mRNA level during vegetative growth	Transcript expression level evidence		Global gene expression profile (RNAseq) of deletion similar to that of heat-stressed wild type.
    ssa2Δ	FYPO:0003152	increased protein level during cellular response to heat	Microscopy			assayed_using hsp90 | assayed_using psi1

**Comment by Antonialock** [comment]
changed the csi1 annotation, it was whacky. Also moved csi2 up to mitotic spindle organization

**Comment by Antonialock** [comment]
bob1, I changed 'regulation of conjugation with cellular fusion' to 'conjugation with cellular fusion'. 

Bob1 is shown to physically interact with byr1, and both the deletion mutant and overexpression mutant are defective for mating. It interacts genetically with byr1 as byr1-OP rescues the mating defect of both bob1-delta and bob1-OP.

Maybe bob1 links cytoskeletal events to the changes needed for shmooing? who knows..

**Comment by Antonialock** [comment]
myo51 changed from regulation to being involved in the process + tweaked other terms in session.

**Comment by Antonialock** [comment]
rhn1 removed, it is a bit of stretch based on the phenotypes.

**Comment by Antonialock** [comment]
pac1 removed, phenotype

**Comment by Antonialock** [comment]
dni1 involved in

**Comment by Antonialock** [comment]
Hsp9 - I think this one is ok and is part of "regulation of G2/M". This guy physically interacts with 14-3-3 and cdc25 and negatively regulates the activity of cdc25. Although it is there during normal growth it only seems to be important when the cells are stressed (to slow down entry into Mphase)

- hsp9 deletion grows quicker (120min generation time vs 140) and there is less phosphorylated cdc2. i
-hsp9-OP grows slower than WT and more cells are septated
- The interaction between 14-3-3 and Cdc25 is significantly decreased in Delta-hsp9
- Hsp9 physically interacts with 14-3-3 and Cdc25 and seems to enhance their interaction

All in all it looks like hsp negatively regulates cdc25, which is important during stress to slow down the cell cycle.

**Comment by ValWood** [comment]
hsp9- makes sense....and the others too

re hsp9,  "physically interacts with 14-3-3 and cdc25 and negatively regulates the activity of cdc25" isn't currently annotated... this would join it up into the network...

**Comment by ValWood** [comment]
bob1, most likely   "delivering unfolded proteins to cytosolic chaperonin, which it acts as a cofactor for". (It is not only for tubulin). This might be regulatory for conjugation, but better as a direct annotation until we know...

**Comment by Antonialock** [comment]
I annotated hsp9 to 
negative regulation of protein tyrosine phosphatase activity has_regulation_target cdc25

I think that's the best I can do for now (can't say it is a direct regulator, and can't say the interaction is direct)

**Comment by Antonialock** [comment]
bob1 yeah I guess it is one for future refinement :-)

**Comment by ValWood** [comment]
don't use these terms.. they tell you nothing about the process

use 
"+ve regulation  G2/M transition" has regulation target cdc25

its easy for a biologist to figure  if it is +vely or -vely regulating cdc25... cdc25 positively regulates the transition, so  if this is positively regulating the transition it must be negatively regulating cdc25
I'm not even sure I would say it was regulating the phosphatase activity, most likely its part of the sequestering, so this is probably not true anyways...

**Comment by Antonialock** [comment]
I really don't like 
"+ve regulation G2/M transition" has regulation target cdc25

the extension should be an extension of the GO term? Cdc25 is not a "G2/M transition" so it doesn't make sense to add it here? @mah11 what do you think?

I reported a similar thing for srw1, it's annotated to
mitotic G1 cell cycle arrest in response to nitrogen starvation
regulates cdc2

same thing here, the extension does not make sense as an extension to the GO term.

**Comment by Antonialock** [comment]
but yes I agree on not using neg reg of phosphatase activity...I do get it it was just a good fudging term :p

**Comment by ValWood** [comment]
Yes you are correct, it doesn't make sense.

Maybe  the new qualifiers would work  for these (acts upstream of or something)

**Comment by Antonialock** [comment]
Hmm, I think you mentioned before that you weren't so keen on those because where do you stop, but maybe they would be useful for (the few cases) where we want to make a connection and cannot be more precise, with the view to remove them as soon as the science is resolved to a more precise level?

**Comment by ValWood** [comment]
Leave the hsp9 as it is until we resolve
https://github.com/pombase/canto/issues/1308
It isn't wrong, and it will just sit in the logs with the others which currently only make sense this way.

**Comment by Antonialock** [comment]
well actually, as you rightfully pointed out, it might not be regulating its atcivity, it could be regulating its localization ;)

**Comment by Antonialock** [comment]
(but I put it back for now with the comment it is a stop gap :-) )

**Comment by ValWood** [comment]
I'm happy with the rest staying as they are. I'll evaluate again in a few month

So do we agree (so far) with the following:

1. Regulation is either upstream of a process or within or downstream
2. OR it is regulation of a biological quality
3. Upstream regulation can be signal transduction/ regulation of gene expression/catabolism
or substrate availability ( some cases of substrate availablility  will be independent of signal transduction) 
4. Within process regulation can be
i). Direct regulation of a molecular function (activity or binding)
ii) Regulation of pathway "decision" for a branched pathway within a process (e.g. within DNA repair process specific pathway choices can be regulated, or "mating type switching/imprinting)
iii) Regulation of localization  
iv) Rate limiting  (slowest) step usually within a metabolic pathway
v) Operating within a process to negatively regulate the process whilst some step is completed or correction is made (I guess this is always going to be a class of  i) eventually, but sometimes we don't know the specific MF that is regulated, but  know that it is "within pathway" regulation)

(The above within process regulation examples only cover non-signal transduction, which may have additional sub-types like amplification )

Hopefully this is a reasonable broad level view of types of biological regulation
So, fir future annotations to regulation check that  the annotation is compliant with this list or  extend the list as necessary.
I'll re-evaluate violators after V63 (no point checking for V 62 as most of the changes were post update).

Note: if a process has a "within process regulation" i.e  DNA recombination, we should aim to ensure that it also gets a direct annotation to the term if we know that it is also part_of the process (this will be the case for most). Examples I can think of where this is not true are where a signalling pathway controls a later stage of a process independently (like SIN for cell separation, during cytokinesis). This is because many tools seem to be showing only direct annotations by default and you need to toggle on the "regulates" relationship. We need to make sure that they continue to slim to the correct process if "regulates" is excluded.

**Comment by ValWood** [comment]
closing, outstanding issue in 
https://github.com/pombase/curation/issues/2982
