### ISSUE TITLE
need signal transduction/signalling  annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1279]
https://github.com/pombase/curation/issues/1278 plus these:

- [x] ssu72 
- [x] tsc1	hamartin 
- [x] mug27	meiosis specific protein kinase Mug27/Slk1 
- [x] azr1
~stm1~
- [x] mik1 -> checkpoint signalling
- [x] pph3
- [x] dis2 DPS complex
~ppn1 DPS complex~
~swd22 DPS complex~
- [x] nem1
- [x] hhp1
- [x] gsk3
- [x] hba1  not signaling
- [x] mug27

**Comment by Antonialock** [comment]
which ones form 1278?

**Comment by ValWood** [comment]
ignore 1278 is largely done, a few will remain and I can fix over coming months....so only these...

There is a term for "signal transducing protein kinase" which might fix some
There is a ticket about this term on GO tracker but I con't find it...will track down...

**Comment by ValWood** [comment]
Hi Antonia, have a look at this ticket.
https://github.com/geneontology/go-ontology/issues/12677

One open question, for me is  are the terminal kinases in any signalling pathway also signal transducers? I'm not sure...

**Comment by ValWood** [comment]
correction, this ticket
https://github.com/geneontology/go-ontology/issues/12999

**Comment by ValWood** [comment]
done
