### ISSUE TITLE
cdt1 and regulation

### ISSUE THREAD

**Issue by mah11** [pombase/curation#1281]
In #1278 cdt1 comes up as annotated to biological regulation, but not annotated to any of the more specific things @ValWood has identified as "real" regulation. It has two regulation annotations: 

    PomBase SPBC428.18      cdt1            GO:0001934      PMID:12604790   IDA
    PomBase SPBC428.18      cdt1            GO:1903466      PMID:10766248   IMP

I'll tackle each one separately in follow-up comments.

**Comment by mah11** [comment]
cdt1            GO:1903466      PMID:10766248   IMP

In vitro, adding Cdc23/Mcm10, Cdt1 or Cdc18 increases Mcm2 phosphorylation by Hsk1. They only looked into mechanism at all for Cdc23/Mcm10, which seems to stabilize interaction between Hsk1 and the MCM complex. I put a comment on all three GO:0001934 annotations from this paper saying I didn't know how to do extensions (still don't); maybe LEGO would do better. In the meantime, I'm not wedded to keeping the annotations, especially for cdt1 and cdc18, but they aren't egregious violators of the "it'd regulate everything" ilk.

**Comment by mah11** [comment]
fixed previous comment ... sigh ...

**Comment by mah11** [comment]
cdt1            GO:1903466      PMID:10766248   IMP

a slight oversimplification of what happens at origins:
1. ORC + Cdc6/18 + (MCM + Cdt1) = pre-RC
2. pre-RC - Cdt1 + other stuff including GINS, Cdc45, etc. = pre-IC
3. more stuff happens; initiation has definitely started by the time origin DNA is melted

Therefore, whether cdt1 acts in replication initiation or (just) upstream of it depends heavily on how GO defines the start of the initiation process. They have two open tickets on the subject: https://github.com/geneontology/go-ontology/issues/10596 and https://github.com/geneontology/go-ontology/issues/9913.

As for what Cdt1 is doing, it seems that molecular details haven't been worked out yet. http://www.mdpi.com/2073-4425/8/1/2/htm (PMID:28025526) is a recent review and looks comprehensive. Among other things, it says "Notably, Cdt1 is essential for MCM loading in all eukaryotes in which it has been tested, but its precise molecular function in origin licensing is not fully clear [48,49,50].". It  has to bind to the MCM hexamer for MCM to be loaded at origins+ORC, and if MCM isn't loaded the subsequent steps don't happen. Because Cdt1 doesn't remain associated with the complex at the origin, it seems unlikely to be doing anything else in later steps (and it's not known to have any catalytic activity). In the sense that Cdt1 does something that appears to control whether MCM loads, it wouldn't outrage replication experts to see Cdt1 annotated to regulation of initiation, and it's reasonably specific (not regulating all the processes ever).

The annotation to GO:1903466 is a reasonable interpretation of the phenotypes in the paper, but that paper is old enough that maybe it's more of a historical record than an essential annotation. I'd be willing to delete that annotation, especially if we wait until GO sorts out when initiation starts. It's got an ISO to pre-RC assembly to maintain its link to events that happen just before or during initiation.

pre-RC = prereplicative complex
pre-IC = preinitiation complex
S.c. Cdc6 = S.p. Cdc18

**Comment by ValWood** [comment]
I think we keep them and wait. Clearly they are both
i) involved in replication
and 
ii) regulating replication as a MF regulator (albeit mechanism unknown).

So we could probably make a tempory annotation"molecular function regulator" but we might not want to do that (I think that is what would happen in LEGO).

For now all we need to know is that  this is a MF regulator (so it isn't a violator as such)

**Comment by mah11** [comment]
I don't know what MF it might be regulating. What's the evidence that it is regulating some yet-to-be-identified MF?

**Comment by ValWood** [comment]
OK I see it might not re regulating a MF it could just be required for localization?

So why not just "mitotic DNA replication initiation"?

**Comment by mah11** [comment]
because it seems to be a major control point

**Comment by mah11** [comment]
i.e. the effect of its (presumed) localization activities determines whether subsequent events can proceed

also, the GO definition issue means we still don't know if it's initiation or upstream because we don't know where GO will put the start of initiation

**Comment by ValWood** [comment]
yep got it.  So it depends on the GO outcome. I would just stick this as waiting for feedback...

**Comment by ValWood** [comment]
Re:

> I don't know what MF it might be regulating. What's the evidence that it is regulating some yet-to-be-identified MF?

as it has an annotation to 
GO:0001934	positive regulation of protein phosphorylation
presumably it must regulate some MF?

If it does not regulate a kinase direct;y, a kinase regulator?

**Comment by mah11** [comment]
That might be separate from its role in pre-RC assembly - it's in a separate paper, and I haven't dug deeply enough into literature from other species to see if an effect on Hsk1 (aka Cdc7) activity has been connected to pre-RC assembly since then. I didn't see anything in pombe papers when I went through them.

The paper that suggests it might be regulating Hsk1 activity said nothing about a mechanism. That's why I don't think it would be a big problem to delete the GO:0001934 annotation.
