### ISSUE TITLE
with field fixes

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1283]
Pfam:00498 (incomplete)
   PANTHER:PTHR1092/Panther:PTHR31492 (CHECK CORRECT CASE)

check case
 2 AGI_LocusCode:AT4G20910
   1 AGI_LocusCode:At2g27100
   2 AGI_LocusCode:At3g44600

confused by this one...seems to be with & from?
  1 GO:0019005|PomBase:SPBC409.05

are all of these needed simultaneously to make the annotation?
  1 GO:1990483|GO:0033698|GO:0070210|GO:0032221

  1 Pfam:Pf02181 ->PF

1 UniProt:P30536 -> add KB to prefix

These are only used once each. We could use the InterPro ID of these entries for consistency of landing page (it still recognised contributing resource)
SMART:SM00317
Prosite:PS01164

**Comment by mah11** [comment]
I have fixed all except this one, because it's not one I worked on, nor a no-brainer text fix:

> are all of these needed simultaneously to make the annotation?
> GO:1990483|GO:0033698|GO:0070210|GO:0032221

**Comment by mah11** [comment]
fix details, for posterity ...

> Pfam:00498 (incomplete)

fixed

> PANTHER:PTHR1092/Panther:PTHR31492 

all upper-case is correct; fixed

> AGI_LocusCode

all upper-case is correct, although TAIR's search is case-insensitive so nothing broke; fixed

> confused by this one...seems to be with & from?
> GO:0019005|PomBase:SPBC409.05

deleted - it was redundant with another annotation anyway

> Pfam:Pf02181 ->PF
> UniProt:P30536 -> add KB to prefix

done

> SMART:SM00317
> Prosite:PS01164

found a couple others; changed all to InterPro

**Comment by ValWood** [comment]
are all of these needed simultaneously to make the annotation?
GO:1990483|GO:0033698|GO:0070210|GO:0032221

only needs one chromatin remodelling complex to infer chromatin remodelling so I just used the first one.

**Comment by mah11** [comment]
all of these done
