### ISSUE TITLE
Linking "within process" molecular functions that are not known to be direct substrates 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1285]
This ticket is spawned from:
https://github.com/pombase/canto/issues/1308#issuecomment-278334643

we need a way to annotate things which are regulating a molecular function indirectly.

In the example  from here
https://github.com/pombase/curation/issues/1278#issuecomment-277270238
- hsp9 where we don't know exactly how it is regulating cdc25 phosphatase activity
- hsp9 has not been shown to be a direct regulator of cdc25 so I can't put it on the MF term
-  We want to link hsp9 to cdc25 as it is part of the pathway
- Currently we use BP annotations "regulation of MF" for these.
- PomBase  have been evaluating if we can get rid of them for 
https://github.com/geneontology/go-ontology/issues/12859
(and for general consistency and LEGO compliance)

- possibly the best way to do this would be to have a relation which can be used with a MF term
  and specifies that a target is not a direct substrate (causally upstream of *and* within). This does not exist. 

 - [ ]  Q what are the existing extensions for MF allowed by GO (Ihave a feeling we self imposed a narrower set)
- [ ]  once decision made, retrofit existing (mainly should be the ones sitting  in the GO logs?)

**Comment by mah11** [comment]
> Q what are the existing extensions for MF allowed by GO 

Anything that has local_domain = GO:0003674 or any of its is_a descendants, or BFO:0000015 ("process" in the formal-ontology sense that encompasses both MF and BP in GO).

That's kind of a pain to get an from the documentation in GitHub (https://github.com/geneontology/annotation_extensions/tree/master/doc), which has a page for each relation to slog through ...

**Comment by ValWood** [comment]
I wonder if for these we can use "negatively regulates" and "positively regulates"

This would not work for all molecular functions, but  for most of the phosphorylation examples,  it is regulatory.

The example above would be

hsp9 some_molecular_function  negatively_regulates cdc25 part_of "negative regulation of G2/M transition"

that seems to work?
