### ISSUE TITLE
phosphorylation sites, add residues

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#13]
PMID: 18257517  allow to map a bunch of phosphorylation sites onto specific residues

Original comment by: ValWood

**Comment by ValWood** [comment]
@kimrutherford  can you find any ancient correspondence about this?

**Comment by ValWood** [comment]
I don't know if it helps but there is a second spreadsheet (EVIN) and most of the missing entries are in there.

Except these, 
https://www.pombase.org/results/from/id/531ff02d-cc63-490e-98ff-c14494b68cf4
and these seem to be special because they are mainly exact duplicates of entries that are in the other set...

**Comment by ValWood** [comment]
i.e 
rpn502 = rpn501
rps1501= rps502
rps1602 = rps1601
rps1802 = rps1801
rpl2401 = rpl2402
rpl401 = rpl402
rpl502= rpl501
ubi4 = ubi1 = ubi2 = ubi3 (at least, the ubiquitin part will be identical so a mass spec would not be able to differntiate)
tif512= tif511

In Uniprot these might have all been mapped to  a single protein entry at this point, and we would split them to both of our identifiers.

this leaves
ssa1
spk1
SPAC750.01
as  'magic-ed from nowhere'
I will dig further into these...

**Comment by ValWood** [comment]
This is how SPAC750.01 aligns to SPAC977.14C
so I am guessing these fragments would not map unambiguously

<img width="711" alt="Screenshot 2024-10-14 at 13 18 52" src="https://github.com/user-attachments/assets/b330b006-8490-4108-8fca-b296d307e8e3">

**Comment by kimrutherford** [comment]
> can you find any ancient correspondence about this?

Sorry, I couldn't find anything useful.
