### ISSUE TITLE
hem2, delete lead ion binding ISS

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1306]
not normal process

**Comment by Antonialock** [comment]
has this been removed already? I can't see it in artemis

I reported the annotation for the human protein using the uniprot helpdesk..

**Comment by ValWood** [comment]
hmm, I can see it on pomabse 2....need to check that the source is not uniprot..

**Comment by Antonialock** [comment]
ah that's probably it...I never know how those annotations come in and how to remove them

**Comment by mah11** [comment]
It is assigned_by UniProt in the GAF.

**Comment by ValWood** [comment]
Mailed uniprot
added "lead ion bindng" to filtered GO IDs for external data (hard check)
so this will disappear....
