### ISSUE TITLE
specifiying residues for gps that modify other gps

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#131]
For point 4, "We can't make this link from the modifying gene" -

Why not? There isn't an applicable relation yet, but we can request/create one. We might also have to confer with Chris et al. about the desired syntax, but again, if it would be useful to capture this, we might as well try to work out how rather than assume it's impossible.

E.g.  gene A: MF GO:nnn kinase activity \[has\_substrate: gene B, residue 27\] \(in some sensible syntax\)

We could also create an accurate relation, such as modified\_by, to use to extend modification annotations, and include residues in extensions. 

Original comment by: ValWood

**Comment by ValWood** [comment]
Can we close this. We have the capability to do it when necessary. Correct?
@mah11

**Comment by mah11** [comment]
From my Dec. 2011 comment it looks like the SF predecessor of this ticket was closed at one point. We can indeed get PRO PR:nnn IDs to put in extensions whenever we can be bothered, so I don't really care whether we have an open ticket as well.
