### ISSUE TITLE
decide what to do about Pfam IDs in substrate

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1312]
Pfam IDs in has substrate, need to look into source etc

![track this down](https://cloud.githubusercontent.com/assets/7359272/23311727/02ca1900-faaf-11e6-8235-b20250a5199e.jpg)

**Comment by ValWood** [comment]
I can't figure out where this comes from, will move

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/189

If we need to do this
gene/SPBC32H8.10
we need a way to indicate which gene the Pfam domain refers to.
Ideally I'd rather not  use Pfam domains in this way (although it could have been me at some point).

We can discuss.
Would be useful to know numbers to begin with...

**Comment by ValWood** [comment]
Only these 2 occurences. Antonia will fix...

**Comment by Antonialock** [comment]
removed

**Comment by ValWood** [comment]
did you change to genes?  there seems to be duplicate annotations for these now?

**Comment by ValWood** [comment]
I don't know what my final comment means, Pfam accs removed so closing...
