### ISSUE TITLE
need signalling annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1319]
stm1
igo1

(from speces distribution analysis, more about this later)

**Comment by ValWood** [comment]
pzh1

**Comment by Antonialock** [comment]
stm1 has signal transduction annotation from PMID:11461899

added annotation to igo1...igo1 is downstream of TOR, there is another signalling term for "downstream of" but there must be a better way of doing it)

looking for a good ref for pzh1..

**Comment by ValWood** [comment]
Which term is for "downstream of" that sounds a bit odd for a process..? 
I thought that was what the new qualifiers were to be for (partly).

Really, we want something like 
signalling involved in "regulation of G2/M transition", but it ends up a bit redundant because this *is* a signalling pathway.
I might be able to get this changed eventually but not yet....

**Comment by Antonialock** [comment]
all done (including lots of papers)

**Comment by ValWood** [comment]
;)

**Comment by Antonialock** [comment]
I was looking at the terms e.g. signal transduction downstream of smoothened http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0007227

**Comment by Antonialock** [comment]
also FYI hal3 will get regulation of signal transduction annotation...multifunctional

**Comment by ValWood** [comment]
woooh, I'm pretty sure that should not be a  term!

**Comment by Antonialock** [comment]
yeah but I was thinking that "signal transduction downstream of TOR" would be handy in this case ;-)

**Comment by ValWood** [comment]
but they will be connected by F-P links?
![tor](https://cloud.githubusercontent.com/assets/7359272/24415672/1ecacbba-13da-11e7-9776-c791e79892d8.jpg)

**Comment by ValWood** [comment]
so this process
http://pombase2.aska.gen.nz/term/GO%3A1905287
(or its parent 
regulation of G2/M transition of mitotic cell cycle
which oddly doesn't exist at present)

will eventually provide a reconstruction of this pathway just from the F-P  and substrate/target links

**Comment by ValWood** [comment]
ah its OK it was added recently:
https://curation.pombase.org/pombe/curs/5beca4251520f38b/ro
but chado hasn't been updated for a while...

We still don't have the connection of tor2/sck2 in this particular pathway curated, although we do have sck1 as a substrate of tor2 and we know this is in starvation conditions...I think we should be able to make this connection somehow...

**Comment by Antonialock** [comment]
yes I added it...

**Comment by ValWood** [comment]
which one?

**Comment by ValWood** [comment]
I added the connections between  ppk18/igo1  to the moreno session last week, but we still dont have tor2/sck2 AFAIK

**Comment by Antonialock** [comment]
I meant the signal transduction annotations
