### ISSUE TITLE
I thought fkh2 regulated earlier than mitotic M-phase

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1322]
(Is there even any transcription during M-phase?)

![is mitotic m-phase correct here i though fkh2 regulated earlier](https://cloud.githubusercontent.com/assets/7359272/23579542/b6a29b4e-00e7-11e7-8794-e56252295d1b.jpg)

**Comment by Antonialock** [comment]
There are two papers for this, Rustici and Shimada

Rustici - not through Canto yet
SHimada: Been through canto PMID:18059475

**Comment by ValWood** [comment]
shimada, deas not mnention transcription in M-phase

I don't think Rustici does either. these annotations appear to be old in artemis and probably just need correcting the phase or deleting

**Comment by ValWood** [comment]
need to be careful not to annotate transcription of genes *required* in M-phase as transcription *in* M-phase

**Comment by ValWood** [comment]
Asked jurg

**Comment by ValWood** [comment]
not clear, closing anyway for now
