### ISSUE TITLE
membrane and lipid biology

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1324]
Follow on from

lipid transport
https://github.com/geneontology/go-ontology/issues/12329
http://www.nature.com/nrm/journal/v11/n10/pdf/nrm2971.pdf

and as lots of new papers seem to impinge on lipid biology, I think we should check through these soon:

LTP mediated transfer
flippase/translocation (shphingolipid/phospholipid etc)
Processes at MCS's (membrane contact sites, Ermes etc)

also the membrane bending pathways...

**Comment by ValWood** [comment]
from
https://github.com/pombase/curation/issues/911
Mast FD, Jamakhandi A, Saleem RA, Dilworth DJ, Rogers RS, Rachubinski RA, Aitchison JD.       
Peroxins Pex30 and Pex29 Dynamically Associate with Reticulons to Regulate Peroxisome Biogenesis from the Endoplasmic Reticulum.
J Biol Chem. 2016 Apr 29;. [Epub ahead of print]
PMID: 27129769

**Comment by ValWood** [comment]
from:
https://github.com/pombase/curation/issues/1181
capture reticulon's role in membrane curvature
https://www.ncbi.nlm.nih.gov/pubmed/27872254?dopt=Abstract

also BAR domain and others...

**Comment by ValWood** [comment]
lipid binding domains

PH PF00169
FYVE clan
PF01363
PF16696
PF02318
PF00628
PX, PF00787
C2  clan
PF00168 C2
PF08174 anillin
PF00792 PI3K_C2
PF10358 NT-C2

**Comment by ValWood** [comment]
need lipid binding

SPAC26A3.10 | cnt6 | centaurin ADP ribosylation factor GTPase activating protein family (predicted)
-- | -- | --
SPBC1289.04c | pob1 | Boi family protein
SPAC26A3.09c | rga2 | RhoGAP, GTPase activating protein Rga2
SPAC26F1.01 | sec74 | Arf GEF Sec74 (predicted)
SPAC1F5.09c | shk2 | PAK-related kinase Shk2
SPAC19A8.02 | sip3 | ER-plasma membrane tethering protein Sip3 (predicted)

**Comment by ValWood** [comment]
SPCC24B10.07 | gad8 | AGC family protein kinase Gad8
-- | -- | --
SPAC17G8.14c | pck1 | protein kinase C (PKC)-like Pck1
SPAC22F8.11 | plc1 | phosphoinositide phospholipase C Plc1
SPAC1B9.02c | sck1 | serine/threonine protein kinase Sck1

**Comment by ValWood** [comment]
/GO="aspect=F; term=lipid binding; GOid=GO:0008289; evidence=ISM; db_xref=GO_REF:0000001; with=Pfam:PF10358; date=20200320"

**Comment by mah11** [comment]
For ISM, use  db_xref=GO_REF:0000050;

cheers!

**Comment by ValWood** [comment]
oh yes!

**Comment by mah11** [comment]
saves me going back and mopping up later ;)

**Comment by ValWood** [comment]
SPBC428.07 | meu6 | pleckstrin homology domain protein, implicted in meiotic chromosome segregation protein Meu6
-- | -- | --
SPCC4B3.15 | mid1 | medial ring protein, anillin Mid1
SPAC26H5.11 | mug56 | spore wall assembly protein Mug56 (predicted)
SPBC1289.04c | pob1 | Boi family protein
SPAC26A3.09c | rga2 | RhoGAP, GTPase activating protein Rga2
SPCC645.07 | rgf1 | RhoGEF for Rho1, Rgf1
SPCC645.06c | rgf3 | RhoGEF Rgf3
SPAC16E8.09 | scd1 | RhoGEF Scd1
SPAC19A8.01c | sec73 | Arf GEF Sec73 (predicted)
SPAC26F1.01 | sec74 | Arf GEF Sec74 (predicted)
SPAC1F5.09c | shk2 | PAK-related kinase Shk2
SPAC19A8.02 | sip3 | ER-plasma membrane tethering protein Sip3 (predicted)

**Comment by ValWood** [comment]
and me because  I ofter realise during....

**Comment by ValWood** [comment]
PF00018

SPAPJ760.02c | abp1 | cofilin/tropomyosin family, drebrin ortholog Abp1
-- | -- | --
SPAC23A1.17 | bbc1 | WIP family cytoskeletal protein Bbc1
SPAC9G1.06c | cyk3 | Nebulin-family actin filament anchoring protein Cyk3
SPBC21D10.12 | hob1 | BAR adaptor protein Hob1
SPBC1734.08 | hse1 | STAM like protein Hse1
SPBC119.05c | lsb1 | Wiskott-Aldrich syndrome homolog binding protein Lsb1 (predicted)
SPAPJ696.02 | lsb4 | actin cortical patch component Lsb4 (predicted)
SPCC1919.11 | mug137 | BAR adaptor protein, involved in endocytosis (predicted)
SPAC3C7.10 | pex13 | peroxin 13 (predicted)
SPBC1289.04c | pob1 | Boi family protein
SPAC7D4.02c | sfp47 | Ubp4 interactor Sfp47
SPAC16E8.01 | shd1 | cytoskeletal protein binding protein Sla1 family, Shd1 (predicted)
SPCC1442.01 | ste6 | Ras GEF Ste6
SPBC1706.01 | tea4 | tip elongation aberrant protein Tea4
SPBC19C2.10 |   | BAR adaptor protein, human endophilin-A2 ortholog, implicated in endocytosis

**Comment by ValWood** [comment]
PF00130

SPBC12C2.05c	bzz1	F-BAR domain protein Bzz1
SPAC17G8.14c	pck1	protein kinase C (PKC)-like Pck1
SPBC12D12.04c	pck2	protein kinase C (PKC)-like Pck2

**Comment by ValWood** [comment]
At revision 6174.
