### ISSUE TITLE
Datasets suitable for tracks 

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1327]
Chromatin binding
 * sir2, clr3: PMID:16079916
 * pho7     PMID:23231582 GSE39499

RNA expression
 * copper, iron: PMID:17477863 
 * copper iron phosphate     PMID:23231582 GSE39499
 * hydrogen peroxide, menadione, tbh: PMID:18003976, E-MEXP-1083
 * cell cycle:  E-MEXP-54  PMID:15195092
 * nitric oxide GSE67272  PMID:26645666

Histone modifications
 * https://www.ebi.ac.uk/arrayexpress/experiments/E-GEOD-11511/samples/?keywords=histone+methylation&organism=Schizosaccharomyces+pombe&exptype%5B%5D=&exptype%5B%5D=&array=&s_page=2&s_pagesize=25

**Comment by Antonialock** [comment]
all WT features for tracks or external references for some? @ValWood

**Comment by ValWood** [comment]
I think the vague plan is for all WT features to be tracks if appropriate... I guess some may not be high priority to host though. We should prioritise datasets that we know will be popular first...

**Comment by Antonialock** [comment]
histone modifications https://www.ebi.ac.uk/arrayexpress/experiments/E-GEOD-11511/samples/?keywords=histone+methylation&organism=Schizosaccharomyces+pombe&exptype%5B%5D=&exptype%5B%5D=&array=&s_page=2&s_pagesize=25

**Comment by ValWood** [comment]
Should this be on the website tracker, or is it covered?

**Comment by ValWood** [comment]
Not sure we need this ticket. If we have datasets we need to host  with high priority will open a tracker ticket. Otherwise, there are plenty in the "datasets to host" portion of the curation tool
