### ISSUE TITLE
manual annotations needed to replace suppressed mapping

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1342]
response to pheromone or descendant should be on mam1 and map3?
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000749#term=children

PomBase	SPAC18G6.07c	mra1		GO:0019236	GO_REF:0000037	IEA	UniProtKB-KW:KW-0589	P	rRNA (pseudouridine) methyltransferase Mra1		protein	taxon:4896	20170114	UniProt		
PomBase	SPBC25B2.02c	mam1		GO:0019236	GO_REF:0000037	IEA	UniProtKB-KW:KW-0589	P	M-factor transmembrane transporter Mam1	SPBC2G5.09c	protein	taxon:4896	20170114	UniProt		
PomBase	SPAC2F3.12c	plp1		GO:0019236	GO_REF:0000037	IEA	UniProtKB-KW:KW-0589	P	thioredoxin fold protein Plp1 (predicted)		protein	taxon:4896	20170114	UniProt		
PomBase	SPAC3F10.10c	map3		GO:0019236	GO_REF:0000037	IEA	UniProtKB-KW:KW-0589	P	pheromone M-factor receptor Map3		proteitaxon:4896	20170114	UniProt

**Comment by Antonialock** [comment]
I sorted out map3, 
mam1 is a pheromone export receptor so I don't think it should have the annotation (it's map3 and mam2 that sense exogenous pheromone)

**Comment by ValWood** [comment]
OK mam1 needs a SPKW error reporting too then...
We now filter but it should still be reported (I'll do this on the tracker)

**Comment by ValWood** [comment]
Oh
