### ISSUE TITLE
MAPK involved in process

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1350]
I think there are only 2 annotations of this sort.

![kill and block terms](https://cloud.githubusercontent.com/assets/7359272/24007809/9e967ca8-0a67-11e7-95f8-233dde1a8ec0.jpg)

we should do as F-P links so we are internally consistent

**Comment by ValWood** [comment]
also pmk1
MAPK involved in cell wall org & bio

**Comment by ValWood** [comment]
and pyp2
(MAP kinase phosphatase, osmolarity sensing)

**Comment by Antonialock** [comment]
These terms already have FP links? I take it you mean you want them converted to part_of?

Fixed....reopen if I misinterpreted..

**Comment by ValWood** [comment]
done
spk1	GO:0004707	MAP kinase activity	IDA		has_substrate PomBase:ste11 , part_of conjugation with cellular fusion
byr2	GO:0004709	MAP kinase kinase kinase activity	IMP	has_substrate byr1 , part_of conjugation with cellular fusion
etc

(I think this is the only place we use F-P links precomposed, I think these will disappear, only used by us).  Using part_of extensions will be clearer/mpre consistent on the genes pages...

**Comment by ValWood** [comment]
I'll take this ticket as I can ask GO too kill these terms when the annotations disappear

**Comment by ValWood** [comment]
To standardize the remainder 👍 

![map kinase](https://user-images.githubusercontent.com/7359272/27836516-a2338434-60d7-11e7-9976-25458258cc92.jpg)

I'll do

Map kinase activity involved_in  "regulation of cell wall organization and biogenesis"
etc 
instead of
Map kinase activity involved_in  "MAPK cascade regulation of cell wall organization and biogenesis"


I'm  going to propose we lose "MAPK cascade" because it isn't really necessary/ useful

**Comment by ValWood** [comment]
I did a couple but I'm going to punt this until the signalling workshop.
The problem is that is we  don't use the "MAPK cascade  involved in" term these will end up with no annotation to signal transduction.

If we use these parts which describe fragments of a pathway we end up with different parts of the pathway annotated inconsistently, depending which part of the pathway you are annotating.

The only sustainable solution I can see is to do:

MF (kinase GTPase receptor etc) has substrate (acts on activity of)  MF  involved_in "signal transduction" part of "positive regulation of process"

 This way the pathways  will  automatically resolve based on the MF connections, and the multitude of different ways of describing the same pathway (by module- e.g  MAPK cascade), by name (osmolarity signalling pathway) by  response to (salt stress) by process regulated   would standardize. It's largely what we have been doing, but would need to include the signal transduction part too.

**Comment by ValWood** [comment]
covered by subsequent
