### ISSUE TITLE
ste11 has regulates for "promoter"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1353]
![tr box ste11](https://cloud.githubusercontent.com/assets/7359272/24072296/36e66c0e-0bdd-11e7-8c63-81cdd9026a08.jpg)

ste11 has TR box  with regulates on a transcription factor term.

Promoter motifs should only extend the DNA binding transcription factor terms

**Comment by Antonialock** [comment]
Doesn't it make sense though?
"+ve reg of transcription from PROMOTER"

-> what promoter? extension: TR box

**Comment by mah11** [comment]
I think it would make more sense if the relation for "what promoter" was "occurs_at" instead of regulates. It looks like GO allows that (https://github.com/geneontology/annotation_extensions/blob/master/doc/occurs_at.md), and if our Canto configuration doesn't allow it, that's easy to fix.

**Comment by Antonialock** [comment]
ok, I updated the extension to occurs_at (it is not allowed)

**Comment by mah11** [comment]
to get it allowed in Canto, edit pombe-embl/supporting_files/annotation_ex_config/GO_BP_A_E_config

**Comment by Antonialock** [comment]
done

Val reopen if you have objections..

**Comment by ValWood** [comment]
Is that  "is now allowed" or do we still need to fix the config?
