### ISSUE TITLE
spac10f6.14 odd allele "+"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1354]
check this out
![allele](https://cloud.githubusercontent.com/assets/7359272/24240178/9d60a1c4-0fa8-11e7-89b1-9c295cd30725.jpg)

**Comment by mah11** [comment]
in Artemis (paper not Canto'd yet)

    FT                   /controlled_curation="term=phenotype, microtubule
    FT                   organization defects; allele=noname(overexpression);
    FT                   db_xref=PMID:15797925; date=20100706"

**Comment by mah11** [comment]
hmm, I think I'll do that paper ... it'll make a nice break from the #!&%@& MRN complex

**Comment by kimrutherford** [comment]
This is a bug in the Chado loader.  It has has stored "+" as the name for the allele.  There are 6 other genes that have an allele with "+" as the name.  Should the loader spit out a warning for alleles that have no name or description like that?  Or is there a better name and/or description that can be assigned?

The other genes:

 SPBC2F12.05c
 SPBP4H10.07
 SPBC3B8.04c
 SPBC887.17
 SPBC543.02c
 SPCC1827.03c

**Comment by mah11** [comment]
If there really are so few, we/I can just go do the curation to assign them names, descriptions, or both.

**Comment by mah11** [comment]
... especially since they are all from the same paper!

**Comment by kimrutherford** [comment]
The odd thing is that there are lots of alleles like this in the contig files:

    allele=noname(overexpression)

but only 7 get stored with "+" as the name.

It think the common factor is that they aren't named genes.

**Comment by mah11** [comment]
well spotted :D 
but they'll get proper descriptions when I do the paper in Canto, so the problem will go away soon

**Comment by mah11** [comment]
done a while ago & forgot to close
