### ISSUE TITLE
update  affecting-> affecting activity of

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1370]
![1](https://cloud.githubusercontent.com/assets/7359272/24496342/e0b1f32e-152f-11e7-863c-e12164bbfb77.jpg)

**Comment by mah11** [comment]
relevant to descendants of FYPO:0000654, including FYPO:0001382

**Comment by ValWood** [comment]
affecting -> affecting activity of (mostly)
http://pombase2.bioinformatics.nz/term/FYPO%3A0001382
from
https://github.com/pombase/curation/issues/1359

**Comment by ValWood** [comment]
I'm  a bit confused by how to do these

I changes all
http://preview.pombase.org/reference/PMID%3A2665944
to assayed _enzyme cdc2 because the activity of cdc2 was decreased


but it could just as easily be  affecting_activity of
https://curation.pombase.org/pombe/curs/8759012da61b3559/ro
not that in some cases the mutated gene is cdc2 and sometimes it isn't.

What is the correct way to do these?

**Comment by mah11** [comment]
The relation is assayed_enzyme. "affecting activity of" is just what gets displayed when the extension uses assayed_enzyme behind the scenes.

For the extension it doesn't matter which gene was mutated. Assayed_enzyme is the gp whose activity is affected, and assayed_substrate is, well, the substrate (if it's a gp ... and known).

**Comment by ValWood** [comment]
So, have I got this?
I just need to change all the cdc2 ones where cdc2 is mutated and cdc2 is the activity affected to 
assayed _enzyme cdc2?

**Comment by mah11** [comment]
yes

**Comment by Antonialock** [comment]
I think I did them all
