### ISSUE TITLE
fnx1 G1 to G0 transition

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1371]
This is the only annotated gene. but it looks suspiciously phenotype-y since fnx1 is a membrane transporter and not a signalling pathway?

**Comment by Antonialock** [comment]
I would remove it...it looks like a legacy annotation but it is not in the embl files?

**Comment by ValWood** [comment]
Twas there...now removed.
Does this have the appropriate phenotypes to cover this (I guess its the absence of G1 arrest?)
if so this is done.

**Comment by Antonialock** [comment]
yeah I had a check through the paper and curation
