### ISSUE TITLE
help needed is a cell wall polysaccharide an extracellular polysaccharide

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1379]
I struggle with the difference between extracellular and external
![parentage](https://cloud.githubusercontent.com/assets/7359272/24633523/e74a6b50-18c0-11e7-85c1-5e5d8c51b246.jpg)

but is a  cell wall polysaccharide an extracellular polysaccharide?

currently extracellular polysaccharide isn't a parent of 
"fungal type cell wall polysaccharide"
should it be?

If not, should we have any annotations to "extracellular polysaccharide" at all?
Taxon restrictions?

**Comment by ValWood** [comment]
@mah11 
@Antonialock

**Comment by mah11** [comment]
In GO, the cell wall is defined as part of the cell, so not extracellular.

**Comment by ValWood** [comment]
we have used

	
agn2
GO:0072316
alpha-glucan catabolic process involved in ascospore release from ascus
and
GO:0072317
glucan endo-1,3-beta-D-glucosidase activity involved in ascospore release from ascus

they are children of
GO:0072000	extracellular polysaccharide catabolic process involved in ascospore release from ascus

but these would not be "extracellular" either would they?

**Comment by ValWood** [comment]
- [ ] anyway 19 of these are IC, so I'll begin by killing those....

**Comment by ValWood** [comment]
SPCC11E10.09c
pvg2
gto2
SPAC27E2.01
agn1
eng1
SPBC1198.07c
SPBC1198.06c
SPCC970.02
mok11
asl1
mel1
mug191
mde5
SPCC757.12
aah2
gas5
gas4
meu7

**Comment by ValWood** [comment]
gto1 also has NAS

**Comment by mah11** [comment]
> children of GO:0072000 extracellular polysaccharide catabolic process involved in ascospore release from ascus
> but these would not be "extracellular" either would they?

Those are extracellular, because it's the ascus that's being digested. The ascus is the container. Each spore has a wall (aka ascospore wall) both before and after it's released from the ascus.

**Comment by ValWood** [comment]
OK I removed the offending ones...

**Comment by ValWood** [comment]
I was thinking extracellular amylase -> extracellular polysachharide blah, but the saccharide itself isn't extracellular. I have always sgruggled with "extracellular..."
