### ISSUE TITLE
evidence code normalization

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1385]
see the list use here:
https://github.com/pombase/website/issues/249

(I might try to get rid of the 3 GO ones used < 10 times)

**Comment by ValWood** [comment]
https://curation.pombase.org/dumps/latest_build/logs/log.2017-04-19-21-54-41.annotation_counts_by_cv

**Comment by ValWood** [comment]
can we standardize these 2:


northern assay evidence used in manual assertion                       | gene_ex                  |     3
Northern assay evidence                                                | gene_ex                  |   781

Western blot evidence                                                  | gene_ex                  |   408
western blot evidence used in manual assertion                         | gene_ex                  |    15


Western blot evidence                                                  | fission_yeast_phenotype  |     1
Western blot assay                                                     | fission_yeast_phenotype  |  2807

which are probably in  spreadsheets?

then this can close

**Comment by mah11** [comment]
most were in contig files; updated to manual assertion IDs
