### ISSUE TITLE
rec8 is hhp1,2 substrate

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1387]
![hhp-rec8](https://cloud.githubusercontent.com/assets/7359272/24918636/fa3e3f70-1ed8-11e7-8349-005de6ce2bc8.jpg)

**Comment by ValWood** [comment]
![rec8 p](https://cloud.githubusercontent.com/assets/7359272/24918671/14137b68-1ed9-11e7-9946-9b30971e44c9.jpg)

![hhp1 phosphorylates rec8](https://cloud.githubusercontent.com/assets/7359272/24918693/26d27b64-1ed9-11e7-8606-a6215b9e7365.jpg)

**Comment by mah11** [comment]
What is the task here?

**Comment by ValWood** [comment]
We have been prioritising papers which identify substrates for quite a while.
This one is  hhp1&2 substrate is rec8

actually I can take this one as its chromosome segregation....I've only been doing mitotic so far  but  I can put these on the pile

**Comment by mah11** [comment]
I infer that the task is to curate a paper. Is that correct? If so, which paper?

**Comment by ValWood** [comment]
No worries its more in my area....

If you do feel inclined  the refs are above  were citations 12 and 23 in the paper I was approving (PMID:20581463 and 2038139), but I will get to them eventually!

**Comment by ValWood** [comment]
These substrates are done. I think I have done the Ishiguro paper but not the Rumpf one.... It will be on my list somewhere......
