### ISSUE TITLE
residue syntax to fix

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#139]
These are the last of the residue syntax to fix (I think)
Need to figure out which residue (CTD refers to C terminal domain)

chromosome2.contig:FT                   residue=CTD,S2; cv=pt_mod; evidence=IDA;
chromosome2.contig:FT                   residue=CTD,S5; cv=pt_mod; evidence=IDA;
chromosome2.contig:FT                   residue=CTD,S2|CTD,S5; cv=pt_mod; evidence=IDA;
chromosome2.contig:FT                   db_xref=PMID:19328067; residue=CTD,S2; date=20100923"
chromosome2.contig:FT                   residue=CTD,S5; date=20100923"
chromosome2.contig:FT                   residue=CTD,S2|CTD,S5; date=20100923"

Original comment by: ValWood

**Comment by ValWood** [comment]
Oh, so comma, not _ ?

**Comment by mah11** [comment]
No, it looks like we changed _from_ commas _to_ underscores, after considering colons for a while (but didn't put a comment here to document it). We don't want to use commas because that would clash with commas meaning "and" in extensions.

Definitely CTD, not CDT, though ;)

**Comment by ValWood** [comment]
OK I used CTD_x
anything else to do here?

**Comment by mah11** [comment]
> anything else to do here?

I doubt it ...

**Comment by mah11** [comment]
pushed the wrong button .... grumble ...
