### ISSUE TITLE
add names to these ncRNAs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1390]
![name rnas](https://cloud.githubusercontent.com/assets/7359272/24997075/313ab738-202d-11e7-9872-dcc1ac5ff021.jpg)

then add as extensions in PMID:28031482

**Comment by ValWood** [comment]
Hmm crap, of all the names to choose, we already have prl1-68 for poly-A nc RNA's

I'm going to make these
101-108 with synonyms prl1-8

**Comment by ValWood** [comment]
with
SPNCRNA.1700 - prl101
SPNCRNA.1702 - prl102

**Comment by ValWood** [comment]
just need to:
- [ ]  check the strand is correct (mailed author)
- [ ]  add extensions to session
- [ ] add to new genes list @mah11

**Comment by mah11** [comment]
website task moved to https://github.com/pombase/website/issues/371
