### ISSUE TITLE
ortholog pb xref

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1391]
write a PB_REF for the ones ortholog predictions  don't have a  specific publication to cite

....we should use  use my old book chapter which describes in detail how the orthology calls are made

**Comment by ValWood** [comment]
I was going to write the ref based on this
http://www.pombase.org/documentation/manually-curated-orthologs
do you know where it is? @mah11

**Comment by mah11** [comment]
If "it" refers to the PB reference document, it's in SVN at pombe-embl/supporting_files/PB_references.txt

**Comment by ValWood** [comment]
No I mean the text that used to be here:
http://www.pombase.org/documentation/manually-curated-orthologs

(if there was any)

**Comment by mah11** [comment]
I think that got changed to http://www.pombase.org/documentation/orthologs

**Comment by ValWood** [comment]
Draft:

Sources of manually curated orthologs in PomBase may vary.  In some cases the consensus ortholog from the major ortholog predictors (Compara, Inparanoid, OrthoMCL) is used. Many distant orthologs have also been identified by PSI-BLAST matches that are uniformly one-to one across species; these alignments have been submitted to the Pfam protein family database. This process is described in detail in Wood V; Schizosaccharomyces pombe comparative genomics; from sequence to systems. In: Comparative Genomics using fungi as models (P. Sunnerhagen, J. Piskur, eds.) Topics in Current Genetics vol 15, pp 233- 285 (2006).  Other ortholog predictions come from experimental data demonstrating functional correspondence or involving membership of corresponding complexes. These predictions are also aligned and submitted to Pfam before inclusion. PomBase's approach ensures that the breadth of coverage is greater than any individual prediction method, and includes many ortholog calls which are not detected by any automated method. Gradually, we will add and display supporting references for all orthology calls. 

Willl this do? @mah11  can you improve?

**Comment by mah11** [comment]
I'll probably tidy up some punctuation after you commit it

**Comment by ValWood** [comment]
plugged it into file.
