### ISSUE TITLE
continue to think about how to capture dependencies

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1395]
like 
componet A formation  dependent on  componet B
localization of A dependent on process B (is cytokinetic ring location dependent on membrane trafficking)

etc

We often have cases where these are deomstrated by drug treatment (TBZ, latrunculin etc) , rather than mutant and cannot be attached to a specific gene product

**Comment by mah11** [comment]
I've been sticking comments in ever since GO deprecated localization_dependent_on(cytoskeleton BP or CC term). At least that way Kim can find them with a query ...

**Comment by ValWood** [comment]
OK we can all do that...its tricky with this paper because they don't actually assay the localization of any specific components to attach a qualifier to.

I can add the PMID to this ticket instead.

PMID:12791993 has various dependencies
cytokinetic ring location dependent on membrane trafficking
PAA formation dependent on cytokinetic ring

**Comment by ValWood** [comment]
not required.
