### ISSUE TITLE
a bit weird to have altered activity when it's the substrate altered

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1403]
this seems a bit odd, dig deeper
![a bit weird](https://cloud.githubusercontent.com/assets/7359272/25360974/7fe8dd28-2943-11e7-8a53-b8c767cf9907.jpg)

**Comment by mah11** [comment]
What looks odd to me is that the extensions are on a phosphorylation term. They must have been done before the clever extension interface, because now the assayed_enzyme and assayed_substrate extension relations are configured to be available only for catalytic activity and regulation of catalytic activity phenotypes.

**Comment by ValWood** [comment]
I think these 3 annotations relate to figure 2 ?
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4755545/pdf/pgen.1005834.pdf
Antonia should both extensions be  "assayed protein" but I wasn't sure which substrte you were putting the expressivity with?

Could you fix?

**Comment by Antonialock** [comment]
Val there are no phosphorylations shown in fig2 (the annotations ref'd fig 1d).
There are also no expressivity annotations?

I did change phosphorylation to kinase activity. 

reopen if you want more things done that i didn't understand.

**Comment by ValWood** [comment]
I don't understand still. How can a mutant in mad3 affect the kinase activity of mph1?

**Comment by Antonialock** [comment]
It's a bit weird either way.

In an in vitro assay of mph1 phosphorylating mad3, you observe less kinase activity using the mad3 mutant then when you use mad3WT

I agree it looks unintuitive (which is probably why I chose the phosphorylation term) but it is in fact the correct term to use?

**Comment by ValWood** [comment]
Ah I  see, yes phosphorylation is the right term to use.  It's confusing to see "affecting activity of" mad3. Mad3 activity isn't affected, its just that mad3 in not  phosphorylatable. Tricky. OK....

**Comment by Antonialock** [comment]
I don't agree...I think the kinase term is the correct one. 

They didn't test the phosphorylation status of mad3 in whole cells...only in the kinase assay. Potentially mad3 is phosphorylated normally in a cell extract (they didn't show this experiment)

**Comment by ValWood** [comment]
OK, it just looks weird. I'm sure people can figure it out if they look! In fact it makes sense to me now....
