### ISSUE TITLE
Possible conflicting viable vs inviable

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#1406]
I'm implementing this: https://github.com/pombase/website/issues/233

As a by-product here is a list of genes that are inviable and viable in the same conditions (assuming I've understood that website ticket).  Could you have a look and see if they make sense?

SPBC1921.02 is viable and inviable with conditions: "PECO:0000005", "PECO:0000137"
SPAC31G5.13 is viable and inviable with conditions: "PECO:0000137", "PECO:0000126", "PECO:0000102", "PECO:0000005"
SPAC26A3.12c is viable and inviable with conditions: "PECO:0000005", "PECO:0000137"
SPBC16A3.09c is viable and inviable with conditions: "PECO:0000137", "PECO:0000004", "PECO:0000005"
SPAC24B11.11c is viable and inviable with conditions: "PECO:0000005", "PECO:0000137", "PECO:0000004"
SPBC691.02c is viable and inviable with conditions: "PECO:0000005", "PECO:0000137", "PECO:0000102"
SPCC5E4.06 is viable and inviable with conditions: "PECO:0000005", "PECO:0000137"
SPBC119.02 is viable and inviable with conditions: "PECO:0000005", "PECO:0000137"
SPAPB1A10.02 is viable and inviable with conditions: "PECO:0000005", "PECO:0000137"

**Comment by kimrutherford** [comment]
Sorry, ignore that previous list.  I had the logic wrong and it was looking at all alleles, not just deletions.  There are actually only four that are suspicious: 

SPAC3G9.08
SPAC3H8.10
SPBC428.19c
SPAC1006.08

In all four cases there is a viable and an inviable deletion and there are no conditions on the annotations.

I did a spot check on two of those and found "inviable vegetative cell population" and "viable vegetative cell population".

**Comment by kimrutherford** [comment]
> There are actually only four that are suspicious:

Please hold off checking those as I have suspicions about my suspicions.  I'd like have a chat about this.  I found yet another problem with the way I was doing this and now the code reports 60 genes that are viable and inviable.

For example for:
  http://pombase2.bioinformatics.nz/gene/SPCC576.01c

The code reports that the gene is viable and inviable with condition PECO:0000266 ("glucose MM, xanthine nitrogen source") -
   there is an annotation to FYPO:0003648 (which is_a FYPO:0002058)
   and to FYPO:0002061 (which is_a FYPO:0002059)

Is that right?  Perhaps we could chat on Skype today?

(PomBase v1 says "Viability depends on conditions" for SPCC576.01c)

**Comment by kimrutherford** [comment]
Since I have it handy, here is the full list of genes that are reported as viable and inviable, along with the conditions and terms used in the conflicting annotations:

[viable-inviable-conflicts.txt](https://github.com/pombase/curation/files/954361/viable-inviable-conflicts.txt)

**Comment by mah11** [comment]
One thing I've spotted so far is that some genes on the list have different viability for spore populations vs. vegetative populations (e.g. SPBC3B9.16c, SPAC13C5.07). That covers anything where one of the tems is FYPO:0002150 or FYPO:0003612. I'll think about whether we want to restrict to just vegetative ..

I'll also see if any other patterns emerge from the rest of the list. Watch this space ...

**Comment by mah11** [comment]
The spore viability issue accounts for 27 of the conflicts in the file. For those I think we have two options:

1. Only consider the vegetative population viability terms (change to FYPO:0002060 and FYPO:0002061)
pro: simple to do, and reduces the number of viability-depends genes
con: users might care about cases where spore and vegetative viability differs

or 

2. Leave it as is, and trust users to spot that the difference is between spores and vegetative cells
pro: even easier (no change); people generally will understand that spores and vegetative populations might behave differently
con: spore vs. vegetative isn't technically a condition; some users will need it explained rather than getting it intuitively (tho they'll then get it, I think)

@valwood, @antonialock - any preference?

**Comment by mah11** [comment]
Of the rest, some are due to terms that are descendants of FYPO:0002058 or FYPO:0002059, but fold something about conditions into the term name and definition, e.g. FYPO:0000082 "decreased cell population growth at high temperature" or FYPO:0003648 "abolished cell population growth on xanthine nitrogen source". To make it even more fun, the same phenotype can be annotated with one of these terms, or with a non-condition-specific term + conditions, or both. (The SPCC576.01c example even has an annotation with xanthine in both the selected term and a condition on that very annotation.)

Curators have been going back and forth dithering about this literally for years - it would be nice and clean and tidy not to have any terms with condition info built in, but we can't shake the feeling that there are some that people expect to see, so we've retained some. (https://curation.pombase.org/pombase-trac/wiki/PrePostComposePhenotype for a bit more background)

The take-home message is that, although it reflects a bit of sub-optimal curation inconsistency, it's not wrong to say that viability does depend on conditions. So we could leave them as is.

That leaves 18 conflicts that are probably worth investigating. I've added PMIDs in the "edited" file:

[viable-inviable-conflicts_edited.txt](https://github.com/pombase/curation/files/955182/viable-inviable-conflicts_edited.txt)

**Comment by ValWood** [comment]
So 
http://pombase2.bioinformatics.nz/gene/SPCC576.01c
is fine, viability depends on conditions

Usually for talking about whether a gene is viable, users probably onlyexpect that  it can grow vegetatively.  We  used “inviable vegetative population”  in PB1 (although this does pull in some inviable spores  because the method to generate the deletions had a sporulation step).

An aside: 
Later Henry Levine’s transposon insertion collection shows which genes are viable vegetatively but cannot sporulate. I still need to make corrections to the correct terms for these….basically if a cell dies at the sporulation stage I should not annotate to “inviable vegetative population”, but it will get this annotation from Henry’s data if it can grow vegetatively.
I need to do these
https://github.com/pombase/curation/issues/988
and
https://github.com/pombase/curation/issues/1038

So, I think we should keep things as they are in current pombase (use inviable vegetative population),  which will  get rid of the "viable spore" /"inviable vegetative cell population"
differences

Our FAQ says
http://www.pombase.org/faqs/can-i-get-list-essential-pombe-genes
inviable vegetative cell population" best fits the most common usage of "essential gene". If you do want to include other stages (such as "inviable spore"), you can use the very generic term "inviable cell population" (FYPO:0002059) or "viable cell population" (FYPO:0002058) in your query. All of the caveats about alleles and conditions still apply.

and I think that is true, but we should double check with users for  the future @Antonialock 
could you put this on your list to ask next time you are in Jurg's lab.

@jvhayles do you agree?

**Comment by ValWood** [comment]
>
That leaves 18 conflicts that are probably worth investigating. I've added PMIDs in the "edited" file:
viable-inviable-conflicts_edited.txt

 @jvhayles had a list of deletions which were differentially reported in the deletion project paper. I looked though this  this morning and I could not find this part so maybe we took it out.

Essentially, (ha ha) there were a number of mutants (about 18 iirc), which had a different viability reported previously. This was often because:

a) The entire gene was not deleted.
b) The conditions were slightly different at some level below the resolution of our reported conditions (slightly different media supplements (amino acids, carbon source), or pH level or such like. 
c)  Very sick (wether you call as alive or dead may depend how many generations you grow for . So viability isn't always all or nothing, you can be almost dead ;)

So probably this is fine.
@jvhayles can you point me to your list if it was in one of the publications?
We can sanity check....

**Comment by ValWood** [comment]
So in summary, Kim, just change for now to be "viable vegetative population" and  any changes required later will be decided by curators. Hopefully there will be none...

**Comment by ValWood** [comment]
Maybe we should discuss this again:

FYPO:0000082 "decreased cell population growth at high temperature" or FYPO:0003648 "abolished cell population growth on xanthine nitrogen source". To make it even more fun, the same phenotype can be annotated with one of these terms, or with a non-condition-specific term + conditions, or both.

Perhaps it is time to get rid of these?
And we can use this as the first options for the "conditions filter"

I have no idea how we would do this but  some way to filter on
non permissive temperature/non standard
non standard media
I'll open a curation tracker ticket for this and  once we have thought about it we can open a condition filter ticket, it isn't required urgently.

**Comment by kimrutherford** [comment]
> Maybe we should discuss this again

Should I hold off on changes?

The viable/inviable terms are configured in SVN in pombase-embl/website/pombase_v2_config.json in this section:

    "viability_terms": {
      "viable": "FYPO:0002058",
      "inviable": "FYPO:0002059"
    },

If you change them, let me know so I can re-release the site.

**Comment by mah11** [comment]
Based on Val's comments, I went ahead and changed that bit of pombe-embl/website/pombase_v2_config.json to:

    "viability_terms": {
      "viable": "FYPO:0002060",
      "inviable": "FYPO:0002061"
    },

to use the "vegetative cell population" viability terms. If I'm reading Val's comments correctly, she's confident about that, and it's the other cases, especially the terms that build in conditions, that remain to be discussed. (Also, it's dead easy to change back if I've got that wrong ;) )

**Comment by ValWood** [comment]
Yep correct, that keeps it as it is now.

We'll randomly survey users, especially those who use
ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Phenotype_annotations/FYPOviability.tsv
(I need to e-mail Li Lin shortly and I know he uses this file, will ask.

Alternatively if anyone has time to ask the list at some point please do.
I suspect its OK as nobody has complained...

**Comment by ValWood** [comment]
So we can close this as nothing left for Kim, we can open new tickets after decisions...

**Comment by mah11** [comment]
> I suspect it's OK as nobody has complained...

that's always a good answer ;)

**Comment by kimrutherford** [comment]
> I went ahead and changed that bit of pombe-embl/website/pombase_v2_config.json to:

Thanks.  I've re-released the site with that change.

**Comment by kimrutherford** [comment]
> Thanks. I've re-released the site with that change.

I should have checked the results better.  Every gene had a viability of "unknown".

The configuration of viability terms wasn't obvious and those two terms IDs that needed changing appeared in two places in the file.  Unfortunately Midori edited the first occurrences but didn't see the second occurrence.  The mismatch in the config then caused everything to be "unknown".

I've improved the config so that the viability terms only appear once and I've made sure that FYPO:0002060 and FYPO:0002061 are in the right places.

So the viability status is now fixed.

There are still some genes that are flagged as viable and inviable in the same conditions (actually no conditions in all cases):

SPAC806.06c is viable and inviable with                                                                                                                                                                                                                                                                                      
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPBC2A9.06c is viable and inviable with                                                                                                                                                                                                                                                                                      
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPAC343.05 is viable and inviable with                                                                                                                                                                                                                                                                                       
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPAC23G3.10c is viable and inviable with                                                                                                                                                                                                                                                                                     
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPAC3H8.10 is viable and inviable with                                                                                                                                                                                                                                                                                       
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPBC17G9.05 is viable and inviable with                                                                                                                                                                                                                                                                                      
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPAC10F6.09c is viable and inviable with                                                                                                                                                                                                                                                                                     
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPBP23A10.05 is viable and inviable with                                                                                                                                                                                                                                                                                     
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPAC821.10c is viable and inviable with                                                                                                                                                                                                                                                                                      
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPBC428.19c is viable and inviable with                                                                                                                                                                                                                                                                                      
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPAC15A10.01 is viable and inviable with                                                                                                                                                                                                                                                                                     
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002620                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPBC32F12.01c is viable and inviable with                                                                                                                                                                                                                                                                                    
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPAC4F8.07c is viable and inviable with                                                                                                                                                                                                                                                                                      
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0001234                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPAC1B3.14 is viable and inviable with                                                                                                                                                                                                                                                                                       
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPAPB1E7.09 is viable and inviable with                                                                                                                                                                                                                                                                                      
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPAC23A1.19c is viable and inviable with                                                                                                                                                                                                                                                                                     
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0001357                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061                                                                                                                                                                                                                                                                                               
SPAC3G9.08 is viable and inviable with                                                                                                                                                                                                                                                                                       
  no conditions                                                                                                                                                                                                                                                                                                              
   viable term: FYPO:0002060                                                                                                                                                                                                                                                                                                 
   inviable term: FYPO:0002061

**Comment by ValWood** [comment]
I think these are real conflicts.  But I suspect most of these will be slightly different conditions, I think its fine.  I can block the deletion project annotations if we know that they  really are wrong.
I  already filter 2.

**Comment by ValWood** [comment]
The deletion project table has conditions already.....Some (most of the differences between the deletion project) were real differences due to how to call viability  (dead vs nearly dead), and incomplete deletion, so will still be the same.  Probably worth  having a look at the conflicts and seeing if the non-deletion project annotation needs conditions or allele description revising (sometimes may be disruption,  or partial deletion, not deletion)

**Comment by mah11** [comment]
Turns out the phenotype annotations form Jacky's paper had conditions, but the ones from the earlier deletion project paper didn't. Because it's been Friday afternoon, I've moved the older ones from Artemis to a PHAF, and added conditions. Woohoo.

**Comment by kimrutherford** [comment]
> Because it's been Friday afternoon, I've moved the older ones from Artemis to a PHAF, and added conditions.

Thanks!  Unfortunately the load failed last night because a feature (SPAC16E8.05c) had two /systematic_id lines.  The lines were identical so I removed one.  I'll check the load in the morning.

**Comment by mah11** [comment]
oops, if I did that, sorry ... it loaded & saved as normal in Artemis so I didn't spot it. thanks for fixing

**Comment by kimrutherford** [comment]
Sorry, I missed another duplicate /systematic_id and the load failed again.  This time I've checked all the config files for other duplicates and I think it should be OK now.  I'm going to restart last night's load manual and I'll check viable vs inviable when it's done.

**Comment by kimrutherford** [comment]
> I'll check viable vs inviable when it's done

The nightly load has managed to succeed just in time for the conference.

Midori, your fix helped a lot.  There are now just two reported conflicts:

op is viable and inviable with
  no conditions
   viable term: FYPO:0002060
   inviable term: FYPO:0002061
SPBC32F12.01c is viable and inviable with
  no conditions
   viable term: FYPO:0002060
   inviable term: FYPO:0002061


https://curation.pombase.org/dumps/builds/pombase-build-2017-05-13-v1/logs/log.2017-05-14-07-28-57.web-json-write

**Comment by ValWood** [comment]
It's odd that there are only 2 conflicts. I expected more.....just because I know some don't agree...or did you find conditional differences for all of the conflicting viability reports?

**Comment by mah11** [comment]
adding conditions to the PMID:20473289 (older deletion collection paper) changed some from "conflict" to "different conditions" (including having vs. not having conditions annotated at all)

**Comment by ValWood** [comment]
> having vs. not having conditions annotated at all

Ok that would be it...I was thinking viability differences, but  we will still have a larger number of these
