### ISSUE TITLE
Decide about FYPO terms that combine conditions, and condition filters

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1407]
follow on from
https://github.com/pombase/curation/issues/1406#issuecomment-297029371

-  [ ] Find out which FYPO terms affected.
-  [ ] If we merge/obsolete need to make sure new annotations have conditions annotated
-  [ ]  Decide what conditions people are  a)  likely to want to filter on, and  b) will give sensible results
It might  need to be a kind of negative filter
so that you can filter out obviously non-standard conditions (because most standard  conditions will not be recorded). Anyway as you can see I haven't thought about this fully.

If anyone has any ideas, or can  remember any previous discussions and add them to this ticket that would be useful. Not urgent though as we won't do this before Banff...

**Comment by ValWood** [comment]
we can start to add possible things people may want to know
- [ ] non permissive temperature/non standard
- [ ] non standard media
- [ ]  @Antonialock  any sensible high level condition groupings in PECO?
- [ ] @Antonialock  ask Jurg's group at next meeting

**Comment by Antonialock** [comment]
"standard" conditions are grouped under the same high level terms as "less common" conditions.

It's not a very big ontology...we can add more subgroupings / clean up the ones we have

**Comment by ValWood** [comment]
essentially a duplicate of
https://github.com/pombase/curation/issues/2653
