### ISSUE TITLE
pom1 delete localization of mid1

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1409]
http://pombase2.aska.gen.nz/reference/PMID%3A9852154

abolished protein localization to nucleus during vegetative growth
plo1+  affecting mid1

and
abnormal protein localization to nucleus during vegetative growth
pom1Δ  affecting mid1

mid1 isn't nuclear?

**Comment by ValWood** [comment]
confirm replacement terms because pom1 is one of my example pages

**Comment by mah11** [comment]
I didn't curate this paper originally, but I had a look out of curiosity, and the annotations look OK. Mid1 is nuclear during interphase, and then moves first to the medial cortex and then to a ring (fig 5 and other papers cited). That goes awry upon plo1+ overexpression (fig 8). The pom1Δ phenotype is subtler to me (fig 7), but the annotation is consistent with what the authors say.

**Comment by ValWood** [comment]
OK, that makes sense the cortical location is /G2 so maybe its nuclear in S phase....

the pom1 delete doesn't fully make sense to me....because pom1 operates to localize to medial cortex, and deletion has this phenotype in pom1 delete:

![mid1](https://cloud.githubusercontent.com/assets/7359272/25441185/6a6b4dd0-2a99-11e7-9ea7-e9bce23ad09b.jpg)

**Comment by mah11** [comment]
> the cortical location is /G2 so maybe it's nuclear in S phase

there's some in the nucleus in all phases except M, according to the diagram in PMID:10930468 fig 4D

> [mid1 in phenotype in pom1Δ]

That's a much higher resolution micrograph than in PMID:9852154, but if the cell is in interphase, it doesn't seem wildly inconsistent with abnormal mid1 nuclear localization.
