### ISSUE TITLE
wee1 inconsistencies

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1410]
from this paper
http://pombase2.aska.gen.nz/reference/PMID%3A25492408

will look at this later

**Comment by ValWood** [comment]
actually it sounds like these should be
	meiotic DNA replication checkpoint
instead of
negative regulation of meiotic nuclear division

(cds1 is presumably directly upstream of mik1/wee1 and  the DNA replication checkpoint
-ve regulates G2/M). T/he phenotype would be absence of nuclear division.

although maybe meiosis is different....will need to check...

**Comment by Antonialock** [comment]
I think I have done the required changes
