### ISSUE TITLE
atg1-m14 allele description shorten

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1411]
atg1-m14(U inserted after nt1182, causing frameshift, amino acid change V395C, and stop codon after amino acid 411)	

Can this be shortened to  " V395C, X412->opal" or whatever? Or is there something additional

tip:
you can make the nucleotide change in artemis to get the exact AA changes, just don't save..

**Comment by mah11** [comment]
The allele _name_ is atg1-m14. Correcting ticket summary accordingly ...

The shortened description misses out the insertion, so it's not complete.

**Comment by ValWood** [comment]
Oh yes. I don't think we need to describe the consequences of the change except that its truncated. People should refer to the paper to see that.


nt1182U, truncates at AA411

**Comment by Antonialock** [comment]
changed
