### ISSUE TITLE
positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1413]
positive regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation
Any positive regulation of G2/M transition of mitotic cell cycle that is involved in cellular response to nitrogen starvation.

would a better name be
TORC1 signaling involved in positive regulation of G2/M transition of mitotic cell cycle 

then we could also have

TORC1 signaling involved negative regulation of G2/M transition of mitotic cell cycle involved in cellular response to nitrogen starvation

In which case GO may prefer us to post compose this, would need to see...

Is TORC signalling always in response to nutrient status? This is unclear from the GO defs

It would be clear to pombe people which signalling pathway this referred to...

@Antonialock

**Comment by ValWood** [comment]
reminder:

![endosulphine](https://cloud.githubusercontent.com/assets/7359272/25482194/7df94186-2b48-11e7-8bca-639b61b930be.jpg)

**Comment by ValWood** [comment]
http://pombase2.aska.gen.nz/gene/SPBC216.07c
similarly


has substrate psk1  during cellular response to ammonium ion

has substrate psk1  Involved in TORC1 signalling

It's uneccessary to say "response to ammonium" as this is just a condition to study the pathway?

even more informative would be

has substrate psk1  Involved in TORC1 signalling  (as part of) 	positive regulation of G1/S transition of mitotic cell cycle

or whatever process is regulated by the signalling

**Comment by Antonialock** [comment]
TORC2 is regulated by glucose, but stress pathways also seem to feed into it.

**Comment by ValWood** [comment]
TORC1?

We need to think a bit more about the signalling pathway representation.....probably should dedicate a curation meeting to this....

**Comment by ValWood** [comment]
I thought it was the other way around  that TOR fed into the stress pathway?. Isn't it upstream of  sty1?
Isn't it a type of stress in this respect ? (starvation).
@Antonialock How do the stress pathways feed into TOR pathway?

**Comment by Antonialock** [comment]
TORC1 or TORC2?

**Comment by ValWood** [comment]
TORC1 here but  aren't they both upstream of the stress pathway.

I don't think all of the curated connections are displayed here
http://www.esyn.org//builder.php?type=Graph&term=GO:1901990&interactionType=physical&source=pombase&includeInteractors=false

I am looking into this,  ignore for now we'll have a look in banff....

https://github.com/pombase/pombase-chado/issues/626

**Comment by ValWood** [comment]
closing this one for now, this term might need changing later.....
