### ISSUE TITLE
update these annotations so that  residues group

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1426]
These should  specify residue

![specify](https://cloud.githubusercontent.com/assets/7359272/25805384/5531a8d0-33f7-11e7-9ce8-4492dfbdfcee.jpg)

so that they group with these:

![so these group](https://cloud.githubusercontent.com/assets/7359272/25805404/6a04bcca-33f7-11e7-83b7-407300a65aa3.jpg)

**Comment by mah11** [comment]
What page(s) is/are the screenshots from?

**Comment by ValWood** [comment]
cdc25 is an example
http://preview.pombase.org/gene/SPAC24H6.05
but maybe it isn't a HTP?

**Comment by mah11** [comment]
It looks like you did indeed add these manually in Canto. I've edited them to more specific MOD terms.

PMID:10523629 a820cd9476653a92

**Comment by ValWood** [comment]
Oh you should have chucked it back to me. I though it was a spreadsheet, and you are the queen of the spreadsheets.
