### ISSUE TITLE
walker A mutant(G419A)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1429]
We probably shouldn't do this.
Its nice to know that the allele is in walker A /B motif, but the user can work this out.

Especially when 
https://github.com/pombase/website/issues/143
is implemented and we can align allele changes with protein family tracks.

Even if the lab names it "walker A" put this in the "lab strain name" and use our standard naming procedure.

**Comment by Antonialock** [comment]
what gene Val?

**Comment by ValWood** [comment]
Euuuuhhhh, damn. I don't know how to find that again....
Let's close. It will come out in the future when we look at nn standard allele names or allele type "other"

**Comment by mah11** [comment]
from the latest-build PHAF:

    % grep -i 'walker' pombase-build-2017-07-04-v1.phaf
    PomBase	SPBC947.01	FYPO:0001587	D478A,E479A	Not assayed	972 h-			knk1	Walker B mutant		amino_acid_mutation	Microscopy				assayed_using(PomBase:SPBC947.01)	PMID:25422470	489620170207
    PomBase	SPBC947.01	FYPO:0004700	D478A,E479A	Not assayed	972 h-			knk1	Walker B mutant		amino_acid_mutation	Microscopy					PMID:25422470	4896	20170207
    PomBase	SPBC947.01	FYPO:0001586	G419A	Not assayed	972 h-			knk1	Walker A mutant		amino_acid_mutation	Microscopy				assayed_using(PomBase:SPBC947.01)	PMID:25422470	4896	20170207
    PomBase	SPBC947.01	FYPO:0004700	G419A	Not assayed	972 h-			knk1	Walker A mutant		amino_acid_mutation	Microscopy

**Comment by ValWood** [comment]
:) thanks!

**Comment by Antonialock** [comment]
done
