### ISSUE TITLE
cut7 / pkl1

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1433]
I dont really get the directionality terms but from the pombe talks (Iva Tolic and Masashi Yukawa) should the directionality of these be swapped around? 
eg cut7 minus end directed and pkl1 plusend directed

**Comment by Antonialock** [comment]
but then meredith just said cut7 walks mainy towards +end. Maybe I just dont get the jargon

**Comment by mah11** [comment]
abstract of PMID:27834216 says cut7 can go both ways - how cool is that?

**Comment by Antonialock** [comment]
nvm

**Comment by Antonialock** [comment]
Yeah I just realized this
