### ISSUE TITLE
opy1 gene name

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1438]
just a reminder

**Comment by ValWood** [comment]
I forgot which gene....

**Comment by ValWood** [comment]
added opy1 to
SPCPB16A4.02c

Did somebody submit this? I have kept it as "unknown" as it is not annotated at SGD.
I can't find any e-mail and I can't remember were it came from.

I wonder why it isn't annotated at SGD?

https://www.ncbi.nlm.nih.gov/pubmed/22562153
"Furthermore, we identify a tandem PH domain-containing protein, Opy1, as a novel Mss4-interacting protein that partially colocalizes with PIK patches. Based upon genetic, cell biological, and biochemical data, we propose that Opy1 functions as a coincidence detector of the Mss4 PtdIns(4)P 5-kinase and PtdIns(4,5)P(2) and serves as a negative regulator of PtdIns(4,5)P(2) synthesis at the PM."

**Comment by ValWood** [comment]
Add  ISS  to SGD based on Rob's e-mail



I had a chance to look at the OPY1 paper, and was able to make four annotations for OPY1 in P2G:

GO:0005737 cytoplasm
IDA
GO:0005886 plasma membrane IDA
GO:1902647 negative regulation of 1-phosphatidyl-1D-myo-inositol 4,5-bisphosphate biosynthetic process
IMP, IGI with MSS4 or IGI with INP51 and INP52 and INP53
GO:0005546 phosphatidylinositol-4,5-bisphosphate binding
IDA

**Comment by Antonialock** [comment]
emailed requestor

**Comment by ValWood** [comment]
did you do the ISS's

**Comment by ValWood** [comment]
>emailed requestor

for?

we can add ISS to this because the identification is trivial. It isn't compromising a future publication (which could be *ages*, and does not always appear). I  add 'general' ISS to orthologs  as a matter of course.

Its just that now  we do it via the tracker...

**Comment by Antonialock** [comment]
I emailed the requestor to say that we had added the name to the DB.

I have added the ISSs.

**Comment by ValWood** [comment]
changed to colour=7
