### ISSUE TITLE
EJC

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1440]
- [ see comment below ] Annotate genes to  GO:0035145 Exon junction complex pfal1 y14 mnh1 rnps1
- [x] Magoh synonym mnh1
- [x] rnps1 ortholog?
 ~~Y14 is SPAC23A1.09	add synonym~~  don't add this one, it wont be published as this

**Comment by ValWood** [comment]
- [ ] SRm160
- [ ] DEK, 
- [ ] RNPS1 
- [ ] Y14
- [ ] REF

**Comment by ValWood** [comment]
Splicing-dependent NMD does not require the EJC in Schizosaccharomyces pombe.
PMID: 20360683 

The fission yeast MTREC and EJC orthologs ensure the maturation of meiotic transcripts during meiosis.
PMID: 27365210 this is the one we need.

for this and
https://github.com/pombase/curation/issues/1441

**Comment by ValWood** [comment]
If you like you can ask the author if they are stuck...

**Comment by Antonialock** [comment]
this was from a talk at pombe2017...

**Comment by ValWood** [comment]
Thats OK, this isn't really pre-publication data. We should have the complex subunits identified and annotated by ISS....

**Comment by Antonialock** [comment]
Current evidence argues against the formation of a mamma- lian-like EJC in fission yeast. First, open reading frames (ORFs) in fission yeast contain very few introns, so NMD probably occurs independent of splicing (Wen and Brogna 2010). Indeed, EJC orthologs are not required for NMD, and the presence of an intron in the mature transcript stim- ulates NMD regardless of its position relative to the PTC (Wen and Brogna 2010). Second, our study shows that EJC orthologs play distinct roles during meiosis; only pFal1 and Mnh1 exhibit meiotic defects correlated with defective splic- ing of meiotic transcripts (Figs. 4, 5). Third, pFal1 associates with Mnh1 without Y14 or Rnps1 (Fig. 4A,C), suggesting that pFal1 and Mnh1 form a separate complex, which interacts with MTREC. Additional biochemical analysis, such as cosed- imentation, is necessary to fully address whether an EJC-like complex is formed in fission yeast.
