### ISSUE TITLE
MTREC

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1441]
Annotate all the MTREC complex subunits

**Comment by ValWood** [comment]
described as a heterodimer so this probably needs updating too

MTREC complex
Ontology	Cellular Component
Definition	A protein complex that consists of a heterodimer formed by Red1 and Mtl1 or homologs thereof, and that promotes degradation of mRNAs and noncoding RNAs and associates with different proteins to assemble heterochromatin via distinct mechanisms. 
PMID:24210919
Comment	An example of this is the complex formed by Red1 and Mtl1 in S. pombe (UniProt symbols Q9UTR8 and O13799 respectively) in PMID:24210919 (inferred from direct assay).

**Comment by ValWood** [comment]
PMID: 25989903 out for cc
PMID: 26942678 curated
PMID: 27365210 out for CC...appears to have gene names added

**Comment by ValWood** [comment]
also called
 human CBCN complex
NURS (nuclear RNA silencing) complex

**Comment by ValWood** [comment]
I think this is OK as defined in GO.

MTREC is a 2 subunit complex  and  NURS (nuclear RNA silencing) complex is related.
I think we can sort this one from  new papers as they come through...it's not so bad but I don't think that the full cohort of subunits is clear. Newer papers can refine and extend.
