### ISSUE TITLE
 rga1 and psy1 localization

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1444]
I think rga1 and psy1 are both published as
	lateral cortical node

**Comment by Antonialock** [comment]
I can't find any evidence for the localization of proteins other than Skb1 and Slf1 to lateral cortical nodes....and we are the only ones annotating to this term at the moment
http://amigo.geneontology.org/amigo/term/GO:1990463#display-associations-tab

**Comment by Antonialock** [comment]
from here: PMID:25009287

**Comment by ValWood** [comment]
no worries I can't remember what iniitiated this one. I should have provided more info.
