### ISSUE TITLE
iron sulfur cluster protein

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1450]
has

/GO="aspect=F; term=oxidoreductase activity; GOid=GO:0016491; evidence=ISM; db_xref=GO_REF:0000050; with=Pfam:PF01512; date=20160904"

@Antonialock  did you add?

(am deleting)

**Comment by Antonialock** [comment]
which one?

**Comment by ValWood** [comment]
SPBC18E5.10

**Comment by ValWood** [comment]
No evidence to suggest this is oxidoreductase
many, many tickets about this:

https://sourceforge.net/p/geneontology/annotation-issues/1180/
https://github.com/geneontology/go-annotation/issues/31

there are some with more explanation somewhere.....
