### ISSUE TITLE
fix UTRs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1453]
- [x] SPAC977.16c
FT   3'UTR           complement(64559..64903)
FT   CDS             complement(64904..66679)
FT   5'UTR           complement(66681..66980)

**Comment by ValWood** [comment]
- [ ] 

5'UTR and exon don't meet up: SPAC6F12.13c.1 at pos 1339942
3'UTR and exon don't meet up: SPAC3A11.09.1 at pos 3450113
3'UTR and exon don't meet up: SPAC16E8.02.1 at pos 3506896
3'UTR and exon don't meet up: SPAC2F3.13c.1 at pos 3947929
5'UTR and exon don't meet up: SPBC25B2.07c.1 at pos 2610710

**Comment by ValWood** [comment]
way to go Ensembl!

**Comment by ValWood** [comment]
these are OK
its the clearest way for users to represent known frameshifts in the reference sequence:

![export](https://cloud.githubusercontent.com/assets/7359272/26309736/137eab0e-3ef6-11e7-9f35-74cc31f4d22f.jpg)


complement(join(1624885..1625092,1625092..1629753,1629825..1629841))
FT                   /gene="SPAP27G11.10c"

- [ ]   more
no gap between exons at 2343704..2343702 in SPAC17G8.01c
no gap between exons at 2588026..2588024 in SPAC823.04
no gap between exons at 3125119..3125117 in SPAC688.08
no gap between exons at 3197530..3197528 in SPAC1486.05
no gap between exons at 3460319..3460317 in SPAC3A11.06
no gap between exons at 4407495..4407493 in SPAC29E6.03c
no gap between exons at 5142627..5142625 in SPAC29A4.03c
no gap between exons at 1950049..1950047 in SPBC16E9.16c
no gap between exons at 1960393..1960391 in SPBC1E8.03c
no gap between exons at 2053518..2053516 in SPBC29A3.08
no gap between exons at 2108181..2108179 in SPBC23G7.06c
no gap between exons at 2219929..2219927 in SPBC14C8.09c

**Comment by kimrutherford** [comment]
OK, thanks.  I'll change the code to warn only if the the overlap isn't exactly 1 base.

**Comment by ValWood** [comment]
or 2..... sometimes I need 2 to make the correct translation.

This is the correct way to do it I believe...at least the paper I was reading says  cites Tim Hubbard and this way to represent frameshifts. Ensembl didn't like it though...... I only recently put them back like this...

**Comment by kimrutherford** [comment]
> Ensembl didn't like it though

PomBase v2 handling overlaps as you'd expect.
