### ISSUE TITLE
spo12 neglected

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1460]
should it be called wis3?
Five novel elements involved in the regulation of mitosis in fission yeast.
Warbrick E, Fantes PA.
Mol Gen Genet. 1992 Apr;232(3):440-6.
PMID: 1588914

spo12 is a multicopy suppressor of mcs3 that is periodically expressed in fission yeast mitosis.
Samuel JM, Fournier N, Simanis V, Millar JB.
Mol Gen Genet. 2000 Oct;264(3):306-16.
PMID: 11085271

**Comment by Antonialock** [comment]
I wouldn't change it now....there's only the one publication (1992) for wis3+pombe on a pubmed search. Spo12+pombe has 5 publications (2000-2008).
changing the name would probably just confuse people?

**Comment by ValWood** [comment]
Yes agreed it's too late now;)
