### ISSUE TITLE
homozygous multi allele

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1469]
It seems odd to me to have homozygous diploid as multi allele...
![homozygous diploid multi-allele](https://cloud.githubusercontent.com/assets/7359272/26421587/77fed53a-40be-11e7-8ace-8a37bb8b72e5.jpg)

**Comment by mah11** [comment]
It's an allowable stopgap until https://github.com/pombase/canto/issues/976 is done, and arguably more consistent with standard genetic notation than some of our other temporary fixes.

**Comment by ValWood** [comment]
ah ok
