### ISSUE TITLE
unknown, unrecorded alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1471]
red1,spn4 mid2 spn1

**Comment by ValWood** [comment]
red1

curs/f17c3d43d258f9f6/ro/ 
needs chacking. Has gone through canto but old phenotypes with no alleles etc were not replaced

- [ ] PMID:15385632 needs curating

**Comment by ValWood** [comment]
@Antonialock 
rememver we were discussing "multiple rings" in Banff

Spn1p and Spn3p are known to organize at the site of cell division late in mitosis where they form a ring that splits as the septum forms, but this ring does not constrict with actomyosin ring invagination; rather, the ring dissipates after cell cleavage (Berlin et al., 2003; Tasto et al., 2003).

This is probably what you were thinking of....

**Comment by ValWood** [comment]
done the septin paper to remove spn4 and 2.  only red1 left

**Comment by mah11** [comment]
What is the task?

**Comment by ValWood** [comment]
The session which isn't checked (still has "unknown" alleles left in Artemis?)

**Comment by mah11** [comment]
done
