### ISSUE TITLE
DiGeorge syndrome

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1475]
We have 3 genes annotated but I am not sure that these are correct.
Anyone know where they came from? 
Di George appears to be associated with a chromosomal region at present rather than a specific gene?

**Comment by Antonialock** [comment]
No idea but yes it is not a monogenetic disorder, and a lot of genes are deleted in humans. Deleted...

**Comment by ValWood** [comment]
OK but if we do not know that this one is disease causing we can't have the link. There is a difference between multigenetic , and lots of genes are deleted in this region, one of them is disease causing...  if these are orthologs of all genes in the deleted region, we can't make the connection. We need to know that it is causative, not just implicated...

**Comment by Antonialock** [comment]
according to the wikipedia page it looks like different genes contribute to different symptoms.

I am not sure what you mean by "if we do not know that this one is disease causing we can't have the link"

**Comment by ValWood** [comment]
If the Wiki page is up to date, only these 2 have been definitively associated with the disease:

Haploinsufficiency of the TBX1 gene (T-box transcription factor TBX1) is thought to be the cause of some of the symptoms observed.

DGCR8
In mice, haploinsufficiency of the DGCR8 gene has been linked to improper regulation of the microRNA miR-338 and 22q11.2 deletion phenotypes

Neither of these appears to have pombe orthologs that I can see. We can't just annotate a gene because it is in the deleted region and has an ortholog. It needs to be associated with the disease symptoms, not just associated with the region implicated in the disease.

**Comment by Antonialock** [comment]
Yeah I wouldn't make annotations to genes in a deleted region..

**Comment by Antonialock** [comment]
I blame some random author pushing their paper :p

**Comment by Antonialock** [comment]
By "No idea but yes it is not a monogenetic disorder, and a lot of genes are deleted in humans. Deleted..."

I meant that I had deleted the annotations and I'm still not sure what else you want done (if anything). Closing.
