### ISSUE TITLE
is except_during allowed?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1477]
see:

![can we do this](https://cloud.githubusercontent.com/assets/7359272/26504537/de007f26-423c-11e7-8b9f-31349a68fb55.jpg)

**Comment by mah11** [comment]
> is except_during allowed?

No. It's effectively the same as not_during, and GO has deprecated all the not_* extension relations (prematurely in my opinion; they should have waited until they'd figured out what to do instead).

**Comment by ValWood** [comment]
OK this appears to be in Artemis, paper not through yet. Will delete.
