### ISSUE TITLE
linear element abnormal or abolished

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1479]
for
- [ ] rec25
- [ ] rec27
- [ ] mug20

according to

![linear element abnormal or abolished](https://cloud.githubusercontent.com/assets/7359272/26504857/3fda582e-423e-11e7-9a27-71a3f63478c0.jpg)

**Comment by ValWood** [comment]
from 16532353

**Comment by mah11** [comment]
What's the specific task here - to curate some papers? If so, they can join the queue ...

Also, "linear element abolished" makes no sense. Linear elements are physical structures, and only processes can be abolished.

**Comment by mah11** [comment]
I'm looking at the full text of PMID:16532353 and I do not see the text shown in the screenshot.

**Comment by ValWood** [comment]
The term is "linear element absent from cell"
Have rec10 and rep1
I usually make a tracker ticket when I'm reading one paper and see a bunch of genes which an author reports as phenocopying, but we have some missing. It's a nice cross check.
I think, here i tracked down  that the ones we don't have would all be in this paper.

**Comment by mah11** [comment]
Which paper? Before I left, I spotted that the screenshot is not from PMID:16532353.

**Comment by ValWood** [comment]
don't worry about it. Is not a priority. In fact I'll remove you. It's just a reminder I'll check it in a  year :)

PMID:16532353  is the paper containing the missing annotation(s) referred to in this paper.

I can't remember what I was reading...

**Comment by ValWood** [comment]
oh, the paper with the original text was this one:
http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005225

**Comment by mah11** [comment]
Of the papers in question, Antonia had already done two, I've now done two others, and the rest are out for community curation. One of the ones I did covers rec25 and rec27, and one of the community ones will bag mug20, so I'll close this.
