### ISSUE TITLE
transcription specificity

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1485]
shouldn't all of these be 
"regulation of transcription from pol-II promoter"?????

![regulation](https://cloud.githubusercontent.com/assets/7359272/26506745/7d7b9e52-4245-11e7-9f59-bac5c9588e53.jpg)

also:
so you can add the spkw mappings and interPro IDs to
https://curation.pombase.org/dumps/latest_build/pombe-embl/goa-load-fixes/filtered_mappings

but you need to check first the gaf to make sure we don't lose a useful mapping at the same time, and make a manual annotation to cover it.

**Comment by Antonialock** [comment]
brf1 - IEA annotation. Brf1 is involved in polIII transcription. Will get positive regulation of transcription from RNA polymerase III promoter from PMID:12682361

**Comment by Antonialock** [comment]
ps @ValWood 5x ? doesn't make it more clear a question is being asked ;)

**Comment by Antonialock** [comment]
elp1 IEA that should be removed https://github.com/geneontology/go-annotation/issues/1624

**Comment by Antonialock** [comment]
ies2,ies6 see https://github.com/geneontology/go-ontology/issues/14141

**Comment by ValWood** [comment]
so  you can add the spkw mappings and interPro IDs to
https://curation.pombase.org/dumps/latest_build/pombe-embl/goa-load-fixes/filtered_mappings

but you need to check first  the gaf to make sure we don't lose a useful mapping at the same time, and make a manual annotation to cover it.

**Comment by ValWood** [comment]
> ps @ValWood 5x ? doesn't make it more clear a question is being asked ;)

Oh I get it now  ;)
I thought I would try all the labels....

**Comment by Antonialock** [comment]
lcp1 is gone

**Comment by Antonialock** [comment]
mat2-pi is ol II so found a ref to support a manual annotation..

**Comment by Antonialock** [comment]
mst1 interpro mapping questioned issue 1629

**Comment by Antonialock** [comment]
asked for pof4 IEA to be refined to polII since it is elongator issue 14162

**Comment by Antonialock** [comment]
sak1 fixed with PMID:25908789.
