### ISSUE TITLE
unknown updates

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1491]
- [x]  clu1 is translation initiation factor

- [x]  toc1 has no process annotation? @Antonialock 

- [x]  pex32

**Comment by ValWood** [comment]
- [ ]  sle1, eisosome assembly, endocytosis , plasma membrane organization

**Comment by ValWood** [comment]
- [ ]  htb1	histone H2B Htb1

- [ ] hnt1   adenosine 5'-monophosphoramidase (predicted)

- [ ] dys1 has eptidyl-lysine modification to peptidyl-hypusine should this be a child of regulation of translation?

**Comment by ValWood** [comment]
- [ ] spn6/7 meiotic septins

**Comment by ValWood** [comment]
-  [ ] whi2
mRNA splicing, via spliceosome  ISO  Q9BRR8

**Comment by ValWood** [comment]
- [ ]  glyoxylate reductase 
	glyoxylate catabolic process  SGD:S000005218

also add name gor1

**Comment by ValWood** [comment]
Great.
Do you think that 
GO:0070583 spore membrane bending pathway should be
"GO:0032120 ascospore-type prospore membrane assembly"?

it sounds as though it should be  "prospore membrane organization" ( which does not exist)...

**Comment by Antonialock** [comment]
well it looks like if you dont have it, then the prospore membrane can't assemble properly...I dont know..

**Comment by ValWood** [comment]
We'll ignore this for now but keep it in mind. I'm not sure why there is no 'organization' term, its usually a parent of assembly.  anyway it isn't critical, and probably better addressed when really working in the area.
