### ISSUE TITLE
mxr2 manual annotation to protein repair

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1493]
Should be able to get this?

There might be an older ticket about this? I'm sure we have discussed it?

**Comment by Antonialock** [comment]
Yes, I found this paper....PMID:11677230
ISSd to e. coli

**Comment by ValWood** [comment]
Ah I thought these was pombe experimental data from Elena? MAybe it was only mxr1?

**Comment by Antonialock** [comment]
do you have a pmid?

**Comment by ValWood** [comment]
PMID: 24118096  I think the paper probably only has data for mxr1 although it mentions mxr2 in abstract...

**Comment by ValWood** [comment]
These aren't annotated to protein repair?

**Comment by ValWood** [comment]
ignore
