### ISSUE TITLE
make formal list of  cloned but unmapped genes 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1501]
https://curation.pombase.org/pombase-trac/wiki/PhysicallyUnmappedGenesProteins

**Comment by ValWood** [comment]
I'm doing htis now.

@Antonialock  please confirm these individual names, unclear
•	ird genes PMID:24301766, PMID:16377914, PMID:26301056

**Comment by ValWood** [comment]
which paper?
•	scr1 (no evidence that it's the same scr1 as SPBC1D7.02c)
•	scr2

**Comment by mah11** [comment]
> scr1, scr2 which paper?

I don't remember, but it looks like it must have been PMID:672902.

**Comment by ValWood** [comment]
also can't find thses via PMID
	•	sts2 (sts genes are Toda/Yanagida? papers)
	•	sts3
	•	sts4
	•	sts7
	•	sts8
	•	sts9
	•	sts10
	•	sts11

**Comment by ValWood** [comment]
> I don't remember, but it looks like it must have been PMID:672902.

How did you find that? I'm searching  PMID with gene names...

**Comment by ValWood** [comment]
maybe I was typing src1, its possible!

**Comment by mah11** [comment]
> How did you find [PMID:672902]?

oldest one on the list of hits for "scr1 AND (pombe OR fission yeast) "

**Comment by ValWood** [comment]
- [ ]  Val, to find paper(s) for mis genes

**Comment by ValWood** [comment]
- [ ]  anyone cps genes?

- [ ]  pet1
- [ ]  all2
- [ ]  ani1

**Comment by ValWood** [comment]
Will close this. When we announce the page we can ask if anyone knows sources.

**Comment by ValWood** [comment]
old page still on wiki, moved to deprecated
