### ISSUE TITLE
Genes with no InterPro results / "This entry is obsolete" in UniProt

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#1503]
I don't know if this is a problem but the following genes/uniprot IDs don't have any InterPro information.  I looked up the first 5 in UniProt and it says "This entry is obsolete" for them.

    SPAC212.01c   |       | Q9HGQ1
    SPAC977.01    |       | Q9P3V8
    SPAC977.02    |       | Q9P332
    SPAC977.07c   | pfl6  | Q9P329
    SPAC977.08    |       | Q9P324
    SPAC977.09c   |       | Q9P327
    SPAC977.11    | fex1  | Q9UTS8
    SPAPB17E12.02 | yip12 | Q9P347
    SPAC19B12.12c | yip11 | Q9P347
    SPAC750.02c   |       | Q9P3E8
    SPBC1348.02   |       | Q9P3V8
    SPBC1348.06c  |       | Q9P3V4
    SPBC1348.09   |       | Q9P324
    SPBPB10D8.04c |       | Q9C0Q1
    SPBPB10D8.05c |       | Q9C0Q1
    SPBPB10D8.06c |       | Q9C0Q1
    SPBPB10D8.07c |       | Q9C0Q1
    SPBPB2B2.15   |       | Q9P3V4
    SPBPB2B2.16c  |       | Q9P3E8
    SPBPB2B2.19c  |       | Q9P3V8
    SPBCPT2R1.04c |       | Q9HGQ1

**Comment by ValWood** [comment]
action
 We need to
i) locate all of the new IDs
ii) update the mapping file. 

I moaned to uniprot, but this should not happen again now.  These entries did need de-merging, but I really can't think of a valid reason for anything to change  further in future....

**Comment by ValWood** [comment]
SPAC212.01c   
  SPAC977.01  
    SPAC977.02    
    SPAC977.07c   
    SPAC977.08   
    SPAC977.09c 
    SPAC977.11    
    SPAPB17E12.02 
    SPAC19B12.12c 
    SPAC750.02c  
    SPBC1348.02   
    SPBC1348.06c 
    SPBC1348.09  
    SPBPB10D8.04c 
    SPBPB10D8.05c 
    SPBPB10D8.06c
    SPBPB10D8.07c 
    SPBPB2B2.15   
    SPBPB2B2.16c  
    SPBPB2B2.19c  
    SPBCPT2R1.04c

**Comment by ValWood** [comment]
outstanding tast to update the file now on chado tracker
https://github.com/pombase/pombase-chado/issues/634
I'm nt sure where or how this should happen.
Van discuss with Kim
