### ISSUE TITLE
describing alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1505]
![shorten](https://cloud.githubusercontent.com/assets/7359272/26798743/aa956508-4a29-11e7-98c0-fb4d54dea6c5.jpg)

I would do alleles like this as

DWDDIEGYYKV138VSVVFDNNTE

....although maybe a notation display like DWDDIEGYYKV-138-VSVVFDNNTE would be better?

**Comment by mah11** [comment]
which gene is this? (please, _please_ include which gene if you have to use screenshots ... or even if you don't.)

Anyway, for the first one, DWDDIEGYYKV138VSVVFDNNTE with or without hyphens misses out amino acid 139.

**Comment by ValWood** [comment]
prp4?

and 
DWDDIEGYYKV-138-VSVVFDNNTE
should be 
DNWDDIEGYYKV-138-VNSVVFDNNTE

I think this format is more readable, not just shorter because you can easily see the string that was replaced at a glance....
