### ISSUE TITLE
open canto tickets for anything on this page outstanding

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1506]
and move to depracated
https://curation.pombase.org/pombase-trac/wiki/CurationToolMultiGenePhenotypes

**Comment by ValWood** [comment]
the page says clearly at the top

THIS PAGE IS OUT OF DATE! - EVERYTHING IS DONE OR MOVED TO TICKETS.



so I'm moving to depracted!

**Comment by ValWood** [comment]
I can no longer find this page from
https://curation.pombase.org/pombase-trac
so I guess it doesn't need movign

**Comment by mah11** [comment]
found and moved link
