### ISSUE TITLE
expressivity-> severity

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1507]
I think we have briefly  discussed relabelling expessivity as severity to make it  more obvious the meaning to users?

If we decide to do this I think  we need to open tickets for Canto and chado to do this (and anywhere else changes are required)

**Comment by ValWood** [comment]
@mah11 @Antonialock  thoughts. Did we discuss doing this at some point and decide it was a good idea? or did I imagine?

**Comment by Antonialock** [comment]
I remember talking about this, either on a call or at pombe. The general consensus was that "severity" would be less confusing & that not even the geneticists always understood the meaning of expressivity.

**Comment by ValWood** [comment]
@mah11  @Antonialock  Should we do this?

**Comment by ValWood** [comment]
@mah11 @Antonialock Should we do this?

**Comment by Antonialock** [comment]
I don't know. I don't know how widely understood "expressivity" is as a term. If it is generally used and understood I think we should keep it, if it is not we could change it to severity which to me is more intuitive.

**Comment by ValWood** [comment]
I have known people be confused by it. Its the correct term,  but a lot of people seem not to know what it is until you say "severity" to clarify...
I have even known people confuse expressivity and penetrance. This would make it easier to distinguish.

**Comment by Antonialock** [comment]
I asked

**Comment by mah11** [comment]
no objection; just need to coordinate code changes with documentation changes

**Comment by Antonialock** [comment]
seems like we could change expressivity to severity both in canto and on website if we are not using it correctly anyway (are we?)?

**Comment by Antonialock** [comment]
I think so..

**Comment by ValWood** [comment]
see
https://github.com/pombase/canto/issues/1398
