### ISSUE TITLE
RNA binding extension

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1509]
currently showing "occurs at" when you want to use with SO, but should be has input

**Comment by mah11** [comment]
Whether occurs_at or has_input is better depends on the SO term, and on the type of RNA. has_input works when the SO term identifies a type of RNA that would be bound in its entirety, like tRNA or snRNA (or at least no one bothers to say anything more fine-grained about which part of the RNA).

But for binding to a particular sequence within a (large) RNA, occurs_at is correct, analogous to DNA binding + SO term. In those cases the input is some RNA, and the SO term indicates where binding occurs along the input RNA.

I'm not sure whether SO is organized in a way that makes it easy to have our configuration make the distinction. If you haven't figured it out by the time I'm back from holiday I'll have a look. It should get better if and when the "SO molecule" ontology takes over covering things like "an actual piece of tRNA".

**Comment by Antonialock** [comment]
ok so close?

**Comment by mah11** [comment]
up to you - could close because we can't do anything elegant yet, or leave open to remind us that this is one way we want to use that molecule ontology if it's ever ready for prime time

**Comment by Antonialock** [comment]
I guess it will be done as part of implementation anyway so we don't need this ticket..
