### ISSUE TITLE
rlc1 negative regulation of SIN

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1510]
this seems incorrect?

does it provide a docking site for shk1?

If so I don't think this makes it a negative regulator of SIN signalling?

**Comment by Antonialock** [comment]
removed from rlc1, added FP link to shk1

**Comment by ValWood** [comment]
was it localization ?

**Comment by Antonialock** [comment]
I changed shk1 to 
protein kianse activity
 has_substrate rlc1 , part_of negative regulation of mitotic actomyosin contractile ring contraction

can't do an annotation to rlc1 based on this paper, do't know direct involvement or reg

**Comment by ValWood** [comment]
but  
rlc1 must be able to have 
"mitotic actomyosin contractile ring contraction" surely?

we know it's involved in contraction in some way (it must be based on the shk1 annotation)

**Comment by Antonialock** [comment]
ah yes...of course, regulation is a child of the process...

I added it...there is also a ticket t scout out the other players...
https://github.com/pombase/curation/issues/1559
