### ISSUE TITLE
EMC complex

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1519]
ER- mitochondrial membrane terthering/ facilitates phospholipid transfer

**Comment by ValWood** [comment]
might be duplicate

**Comment by mah11** [comment]
#461 is closed

**Comment by ValWood** [comment]
GO:0072546
Name	ER membrane protein complex
Ontology	Cellular Component
Definition	A transmembrane protein complex located in the ER that is involved in ER-mitochondrial membrane tethering, which is required to facilitate lipid transfer from the ER to the mitochondrial membrane. In S. cerevisiae, it has six members: 
EMC1, 
EMC2, 
AIM27, 
EMC4, 
KRE27, and 
EMC6.
