### ISSUE TITLE
 ncRNA annotation

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#152]
In GeneDB only protein-coding genes had "characterisation status" annotated. In PomBase we should be able to assign status to a lot of the ncRNA genes as well.

Note that not all of the status designations would be applicable to ncRNAs, but we can use "published" and "role inferred from homology". Any others?

Also update http://www.pombase.org/status/gene-characterisation table and descriptions when RNAs have status.

Also see items on ncRNA GO annotation
https://sourceforge.net/tracker/?func=detail&aid=3232326&group\_id=65526&atid=2096329
https://sourceforge.net/tracker/?func=detail&atid=2096329&aid=3316936&group\_id=65526

Original comment by: mah11

**Comment by ValWood** [comment]
Probably don't need to do "characterization status" in the same way for non coding rnas, but if we do would need to establish what we mean by "characteriasation" for an non coding RNA...particularly a cryptic transcript, which might be non-functional. 

This is ahead of knowledge so I'll close...no point speculating about unknown biology...
