### ISSUE TITLE
add to physically unmapped genes list

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1521]
http://pombase2.aska.gen.nz/status/unmapped_genes
(can't remember how)
all1
ala1
all1 lack allantoinase, ala1 lack allantoicase  PMID24177583

**Comment by ValWood** [comment]
remove from list
From Cahrlie H.
scr1 should not be on the unmapped genes list.

@kimrutherford  where is the Yaml for this?

**Comment by kimrutherford** [comment]
> where is the Yaml for this?

It's here:
  https://github.com/pombase/website/blob/master/frontend/src/docs/status/unmapped_genes.md

It's one of the tables that hasn't yet been converted to Markdown.  I've removed scr1.  The change will be visible in 10 minutes or so.

**Comment by ValWood** [comment]
added all1 and ala1
