### ISSUE TITLE
SPAC11D3.10 SPCC777.03c  need MF

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1538]
transferred from
https://github.com/pombase/curation/issues/1532

 - [ ] 	SPAC11D3.10 SPCC777.03c transaminase?

http://www.uniprot.org/uniprot/Q46925
A bit of detective work reqiuired...
Note : horizontal transfer
Note : combubulate E. coli annotations
Note : connection to  iron sulphur cluster biosynthesis. Relevant?
Note: paralog 

For now added 
/GO="aspect=F; term=catalytic activity; GOid=GO:0003824; evidence=NAS; db_xref=GO_REF:0000051; date=20170624"
2 things I would not normally do (term and evidence) so it goes into the correct bin for analysis (I'm treating catalytic and non-catalitic separately)

So all I want here is the first level EC number ( it might not be possible to predict...)

**Comment by Antonialock** [comment]
So, in general, the SUF system for iron-sulfur cluster assembly is different from the ISC system.

The ISC system is mitonchondrial in eukaryotes but this system is also found in bacteria (this is the one I have been working on).
The SUF system is found in plant chloroplasts and in bacteria. 
(E. coli csdA is part of the SUF system. )

Sulfur is required for pathways other than FeS biogenesis. This is why the pombe desulfurase nfs1 is annotated to both
- iron-sulfur cluster assembly &
- tRNA wobble position uridine thiolation
(as discussed in #1243 )

Like nfs1, CsdA is involved in sulfur transfer. Like nfs1 it's been implicated in thiolation as well as FeS cluster biogenesis PMID:20054882 )

I added 
/GO="aspect=F; term=cysteine desulfurase activity; GOid=GO:0031071; evidence=ISS; with=UniProtKB:Q46925; db_xref=GO_REF:0000024; date=20170705"

to these two, seems ok to do?  reopen if you want a more general term

**Comment by ValWood** [comment]
seems reasonable.
But we don't have a process, especially as likely horizontal transfer. Thats fine...

**Comment by Antonialock** [comment]
no...I guess the most specific you could go is cellular metabolic process which doesn't seem very useful

**Comment by ValWood** [comment]
Yes we don't annotate to that....
