### ISSUE TITLE
guide for U2 snRNA 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1548]
Despite the hundreds of noncoding RNAs annotated in the fully sequenced S. pombe genome (http://www.pombase.org), the list of snoRNAs is far from complete; in fact, no guide RNAs for U2 snRNA modification have been identified so far. Using a nucleotide blast database search, we found a pu- tative U2 snRNA-specific guide RNA downstream from the RPC10 gene (Fig. 4A). Standard 5′ and 3′ RACE and Northern blot analysis confirmed the expression of this RNA in S. pombe (Fig. 4C). The nucleotide sequence was deposited to the Third Party Annotation Section of the DDBJ/EMBL/GenBank databases under accession number BK009173. We predict that the newly identified box H/ACA RNA can direct modification of U2 snRNA at positions 43 and 44 (Fig. 4B).

**Comment by ValWood** [comment]
As an alternative for further functional assays, we cloned a 695- bp fragment of S. pombe genomic DNA containing the newly identified guide RNA into YEplac181 vector without a pro- moter (Fig. 4A) and transformed S. cerevisiae cells with this plasmid. The S. cerevisiae transformants showed (i) expres- sion of the fully processed S. pombe guide RNA (Fig. 4C)

and (ii) pseudouridylation of U2 snRNA at position 45, equiv- alent to position 44 in S. pombe U2 snRNA (Fig. 4D). This demonstrated that the newly identified S. pombe RNA is a gen- uine guide RNA for U2 snRNA pseudouridylation. More im- portantly, expression of this guide RNA in the pus1Δ S. cerevisiae strain induced modification of both position 45 and 44, although position 44 was modified less efficiently than in the wild-type strain (Fig. 4D). The pseudouridylation pocket of S. pombe pugU2-43/44 RNA has a one-nucleotide bulge in the upper stem when base paired with S. pombe U2 snRNA for positioning Ψ43 (Fig. 4B, star). I

**Comment by ValWood** [comment]
searched for BK009173 at EBI...guess what I found?....

Its a treasure hunt clue....

**Comment by ValWood** [comment]
As soon as our paper was published we sent to GenBank an update for BK009173, but it seems that the record has not yet been processed.

The deposited sequence of S. pombe pseudouridylation guide RNA for U2 snRNA at positions 43 and 44 is the following:

>II dna:chromosome chromosome:ASM294v2:II:1676220:1676334:1
TTGGCGACGGTTTGAAAGTGCCATGTGTACTTTAACCATGCCTATAAAAAATCGTCCACT
TGAAAATCTTAAAGTCAAGAAAACCGATTTTATGGACAGATACGGTGGATACATAC

**Comment by ValWood** [comment]
So far I have done


ncRNA
1676220..1676335
/SO="SO:0000602"
/db_xref="EMBL:BK009173"
/product="U2 snRNA-specific guide RNA"
/systematic_id="*****"


- [ ]  Somewhere I recorded which nc RNA ID we were upto but I forgot where I put it-
add systemtic ID
- [ ]  add to new genes list

**Comment by mah11** [comment]
#1272 reserves 2000-8000

highest ID outside that range is SPNCRNA.1708

**Comment by ValWood** [comment]
OK for this newby I'll use  SPNCRNA.1709

**Comment by ValWood** [comment]
- next annotate GO stuff when  ID is available in Canto

**Comment by ValWood** [comment]
I just annotated my first guide RNA.
