### ISSUE TITLE
need to change GO:0031074 annotations

### ISSUE THREAD

**Issue by mah11** [pombase/curation#1556]
term chosen by community curator is flagged by GO as not for direct annotation

    pdc2	GO:0031074	nucleocytoplasmic transport complex	EXP				Shao-Win Wang <shaowinwang@nhri.org.tw>	
    lsm1	GO:0031074	nucleocytoplasmic transport complex	EXP				Shao-Win Wang <shaowinwang@nhri.org.tw>

PMID:28031482
https://curation.pombase.org/pombe/curs/4f36d75cf334acbc

Val - assigning to you because you reviewed the session when it came in, but give it to me if you don't remember enough to know what to use instead.

**Comment by ValWood** [comment]
Hmm I do remember a discussion about the term with the author, will dig htat out.

I remember  (I think) a separate discussion  with GO about nucleocytoplasmic transport complexes in general. Maybe i do need to request a new term...

**Comment by mah11** [comment]
looks like this is the GO ticket: https://github.com/geneontology/go-ontology/issues/13354

**Comment by ValWood** [comment]
I can't find the correspondence with Shao-Win, but I'm sure that I queried this one with him, and based on his response decided to keep it. I can't remember, but based on the other annotations it could  might not be involved in "transport" ...

**Comment by ValWood** [comment]
OK I deleted both...

**Comment by ValWood** [comment]
will probably add back...
