### ISSUE TITLE
update or delete annotations to obsolete FYPO:0001520

### ISSUE THREAD

**Issue by mah11** [pombase/curation#1557]
I've had to make FYPO:0001519 and FYPO:0001520 obsolete because they referred to GO:0003840, which has itself gone obsolete (https://github.com/pombase/fypo/issues/3042).

ggt1 and ggt2 have alleles annotated to FYPO:0001520 from PMID:15052323 and PMID:15920625 respectively (I just included the parent FYPO:0001519 for obsessive completeness). They'll show up in the canto log next load.

Open a FYPO ticket if you need a new term to replace the annotations.

**Comment by ValWood** [comment]
abnormal GO:0036374 instead

**Comment by Antonialock** [comment]
I annotated to increased catalytic activity & EXPd the MF

GO ticket for ref
https://github.com/geneontology/go-ontology/issues/13571

**Comment by mah11** [comment]
I've now added terms for https://github.com/pombase/fypo/issues/3043, so you could update the annotations.

I'm also thinking of flagging the "catalytic activity" FYPO terms as not for direct annotation - any objection?

**Comment by Antonialock** [comment]
The reason why I didn't request it is because the assay seemed so "indirect" for the real activity. I'm happier 

Because they assayed a "transferase activity" I'm happier annotating to "increased catalytic activity" than "increased glutathione hydrolase activity". What do you think?

**Comment by mah11** [comment]
I really think "increased catalytic activity" doesn't say anything specific enough to be useful.

I don't know these activities well, but the GO ticket seems to be saying that the assay is a reliable proxy for the GO:0036374 activity - it sounds like there's not much risk of a gene product with some other activity in vivo catalyzing the reaction used in the assay.

**Comment by Antonialock** [comment]
ok i'll update the terms then

**Comment by Antonialock** [comment]
fixed
