### ISSUE TITLE
Look for beta-ketoadipate pathway members

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1563]
from
https://github.com/pombase/curation/issues/1542

These are likely to be in the unknowns...

**Comment by ValWood** [comment]
A bit of detective work required...

**Comment by mah11** [comment]
MetaCyc
https://metacyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-5431

reviews with decent diagrams
PMID:8905091
PMID:23122644

**Comment by ValWood** [comment]
Since we have 5.1.1.1
we should also have 
1.13.11.1  catechol 1,2-dioxygenase
5.3.3.4 muconolactone isomerase

and then possibly 

3.1.1.24 
2.8.3.6   β-ketoadipate:succinyl CoA transferase
2.3.1.174  β-ketoadipyl CoA thiolase

Will check fungal annotations for any candidates first...

**Comment by ValWood** [comment]
So based on the fact that I can't detect  anything looking like the neighbouring enzymes, and this pathway appears to be mainly involved in lignin degradation and the like, its possible/likely that we don't have it so closing for now.
