### ISSUE TITLE
pck2  GO process annotation refinement (using 'MF' term)

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1567]
GO:0050732 	negative regulation of peptidyl-tyrosine phosphorylation 	1
regulates pmk1
	IMP 	Zaitsevskaya-Carter T et al. (1997) 

maybe this can be changed to neg reg of signaling or something

**Comment by ValWood** [comment]
Yes, this is the only annotation to the "function" term..

**Comment by Antonialock** [comment]
it was a 2012 session and very indirect evidence...removed.
