### ISSUE TITLE
Wild-type expression datasets in specific conditions

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1572]
h90 Mata E-TABM-139 PMID:17032641 Nitrogen starvation
iron replete and depleted PMID:18223116
zinc starvation 18203864

**Comment by ValWood** [comment]
this is microarray though?

and already hosted in linked viewer.
http://bahlerweb.cs.ucl.ac.uk/cgi-bin/SPGE/geexview

What else would we do  with it?

**Comment by Antonialock** [comment]
Just thought we might want to host on a track?

**Comment by ValWood** [comment]
Hmm I guess we might if no RNAi dataset becomes available sooner...
