### ISSUE TITLE
long list of term requests

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1574]
I wonder if some of these have forgotten to hit submit?For instance Sigurd and I nearly completed his paper at the meeting.

 http://curation.pombase.org/pombe/curs/6c1cc5fd9503d415
    Masamitsu Sato  PMID:23770679
    "Microtubules and Alp7-Alp14 (TACC-TOG) reposition chromosomes before meiotic segregation."

- [x]   http://curation.pombase.org/pombe/curs/bf037075feb20f28
    Amanda Bird  PMID:24831008
    "The double zinc finger domain and adjacent accessory domain from the transcription factor loss of zinc sensing 1 (loz1) are necessary for DNA binding and zinc sensing."

Sent another reminder to Amanda

- [ ]   http://curation.pombase.org/pombe/curs/80b382d361649949
    Juan Carlos Garc�a Cort�s  PMID:26132084
    "Cooperation between Paxillin-like Protein Pxl1 and Glucan Synthase Bgs1 Is Essential for Actomyosin Ring Stability and Septum Formation in Fission Yeast."

  http://curation.pombase.org/pombe/curs/fdc3419730dab35f
    Sylvie Tournier  PMID:25778919
    "Aurora B prevents chromosome arm separation defects by promoting telomere dispersion and disjunction."

 
  http://curation.pombase.org/pombe/curs/48962b9e331018c2
    Henry Levin  PMID:26358720
    "Single-Nucleotide-Specific Targeting of the Tf1 Retrotransposon Promoted by the DNA-Binding Protein Sap1 of Schizosaccharomyces pombe."
  
http://curation.pombase.org/pombe/curs/5ade41ae7e0543d6
    Yannick Gachet  PMID:26359299
    "Fission yeast kinesin-8 controls chromosome congression independently of oscillations."

  http://curation.pombase.org/pombe/curs/8ad14ac446a38d4f
    Sophie Martin  PMID:26443240
    "PKA antagonizes CLASP-dependent microtubule stabilization to re-localize Pom1 and buffer cell size upon glucose limitation."

- [x]   http://curation.pombase.org/pombe/curs/db997f5a4f033da9
    Sigurd Braun  PMID:26744419
    "Control of heterochromatin localization and silencing by the nuclear membrane protein Lem2."  
mailed 11/11

 

 - [x]  http://curation.pombase.org/pombe/curs/5c744b7dd350f431
    Pernilla Bjerling  PMID:27613427
    "Stress sensitivity of a fission yeast strain lacking histidine kinases is rescued by the ectopic expression of Chk1 from Candida albicans."
Session only sent out in MAy will leave for now
 
  http://curation.pombase.org/pombe/curs/2ff9544218a3c825
    Sandra Lopez-Aviles  PMID:28041796
    "A PP2A-B55-Mediated Crosstalk between TORC1 and TORC2 Regulates the Differentiation Response in Fission Yeast."

  http://curation.pombase.org/pombe/curs/5724d1814ea9f342
    Sophie Martin  PMID:28410370
    "A systematic screen for morphological abnormalities during fission yeast sexual reproduction identifies a mechanism of actin aster formation for cell fusion."

  http://curation.pombase.org/pombe/curs/bfd3f85ba1c4e658
    Susanna Boronat  PMID:28640807
    "Lack of a peroxiredoxin suppresses the lethality of cells devoid of electron donors by channelling electrons to oxidized ribonucleotide reductase."

**Comment by ValWood** [comment]
Deleted Karen May, she told me already shoe would finalise when back from holiday.

It would be good if we could check which of these have been hanging around for over a couple of months which indicates they are "forgotten"

Will  can gradually send reminders. I will contact Amanda and Sigurd today as I have spoken with them recently.

**Comment by mah11** [comment]
I sent emails about these back in February ... _2016!_ ... saying I'd added the terms:

http://curation.pombase.org/pombe/curs/6c1cc5fd9503d415
Masamitsu Sato PMID:23770679

http://curation.pombase.org/pombe/curs/bf037075feb20f28
Amanda Bird PMID:24831008

http://curation.pombase.org/pombe/curs/80b382d361649949
Juan Carlos Garc�a Cort�s PMID:26132084

Maybe you'll have better luck if you remind them again.

**Comment by ValWood** [comment]
thanks,  I'll give it  a go, after

https://github.com/pombase/canto/issues/1328

**Comment by mah11** [comment]
I've got this one in approval; waiting for a GO term to work its way through the pipeline

http://curation.pombase.org/pombe/curs/92141eb3ba63c234
Sarah Lambert PMID:28475874

**Comment by mah11** [comment]
These also have FYPO requests that haven't reached the tracker before now:

http://curation.pombase.org/pombe/curs/8ad14ac446a38d4f
Sophie Martin PMID:26443240

http://curation.pombase.org/pombe/curs/db997f5a4f033da9
Sigurd Braun PMID:26744419

http://curation.pombase.org/pombe/curs/5c744b7dd350f431
Pernilla Bjerling PMID:27613427

http://curation.pombase.org/pombe/curs/5724d1814ea9f342
Sophie Martin PMID:28410370
(also has a GO request; opening ticket)

http://curation.pombase.org/pombe/curs/f02a15cea2c40c03
Mario Halic PMID:28404620
(there's also a GO request, but I suspect that one could be done with extensions - Val, you should check this one)

http://curation.pombase.org/pombe/curs/bfd3f85ba1c4e658
Susanna Boronat PMID:28640807
(also didn't find sensitive to hydroxyurea FYPO:0000088)

**Comment by mah11** [comment]
This one has a FYPO request, but I'm not sure it really needs new terms.

http://curation.pombase.org/pombe/curs/2ff9544218a3c825
Sandra Lopez-Aviles PMID:28041796

@antonialock, could you look at it and think about whether "normal mating efficiency upon nitrogen starvation" is any different from "normal mating efficiency" for pombe? (It would be for budding yeast, but they do mate under nutrient-replete conditions normally anyway, so what goes for them is irrelevant to us.) Same for "decreased", also requested.

**Comment by mah11** [comment]
edited FYPO request list in earlier comment - missed one in the copy/paste maneuver

**Comment by mah11** [comment]
Karen has added the GO term for this one

http://curation.pombase.org/pombe/curs/48962b9e331018c2
Henry Levin PMID:26358720

https://github.com/geneontology/go-ontology/commit/aed99d2c0196464be0b9cc907965595259ba4419

**Comment by ValWood** [comment]
OK most of these are fairly recent sessions so can close this when @Antonialock  has answered your question.
We get them when we get them....

**Comment by mah11** [comment]
http://curation.pombase.org/pombe/curs/5724d1814ea9f342
Sophie Martin PMID:28410370

id: GO:0061915
name: actin fusion focus localization
