### ISSUE TITLE
check nup155 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1576]
should this population viability be vegetative?
https://github.com/pombase/website/issues/436#issuecomment-313539663

**Comment by ValWood** [comment]
from https://github.com/pombase/website/issues/436

If they only say that spores are inviable I annotate to this term so please
don't move it down if it is my annotation

(I annotate to inviable spore pop if they show that spores do not
germinate. I annotate to inviable veg pop if they show that spores
germinate but don't divide / only do a few divisions)

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/436
I use inviable spore population if they show that the spores don't
germinate.

Unless they say or show this you won't know if the spores didn't germinate
(inviable spore pop) or germinated but didn't divide/only did a few
divisions (inviable vegitative)

**Comment by ValWood** [comment]
So we have a problem that this is a differnce (maybe deletion project is incorrect?)
but doesn't show as one.

Need to decide if we should use "inviable cell population" for viability.
I know we decided previously not to. Maybe we should revisit this?

Need to think about the consequences of doing/not doing....

**Comment by mah11** [comment]
The previous discussion is in #1406.

Briefly, if we use only vegetative we miss nup155 and maybe a few others. If we move up to viable/inviable population we get a few more "depends on conditions" because of cases where spore and vegetative viability genuinely differ. More details in the older ticket ...

**Comment by ValWood** [comment]
OK thanks. Will think...

**Comment by ValWood** [comment]
actually, I don't know if this discussion applies to this one. The abstract says

"15 of these nucleoporins are essential for vegetative cell growth"
