### ISSUE TITLE
signalling, stress-activated MAPK cascade

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1579]
Before the signalling meeting I need to documents some of the issues with the signalling term choice. This will spawn questions.

1 - [ ]  stress activated protein kinase
has cmk2, mak2, mak3, mcs4, sin1, srk1, sty1, win1, wis4

I wondered why
GO:0051403 stress-activated MAPK cascade
isn't used here instead?

**Comment by Antonialock** [comment]
I don't understand what you mean. Mcs4 and sin1 are not kinases. None of these genes are annotated to "stress activated protein kinase" (that isn't even a GO term)

**Comment by ValWood** [comment]
That should say
"stress-activated protein kinase signaling cascade"
I might have fixed these yesterday though...

**Comment by ValWood** [comment]
> I might have fixed these yesterday though...

Maybe not. It seemed familiar but I don't see the ticket...

**Comment by ValWood** [comment]
I did fix at least some of these yesterday
but the changes aren't showing?
https://github.com/pombase/curation/issues/1589
@kimrutherford

**Comment by ValWood** [comment]
will check this tomorrow, see if my updates fixed

**Comment by Antonialock** [comment]
I went through them. 

cmk2 isn't part of the MAPK cascade? it is a target of it? so that's fine? or what would the alternative be?
mak2/mak3 - I guess it could change to +ve reg of stress activated mapk cascade. It seems kind of arbitrary whether to regulate to +ve regulation of MAPK cascade, or part of a broader stress pathway. 
 - changed mak2 to positive regulation of stress-activated MAPK cascade
 - changed mak3 to positive regulation of stress-activated MAPK cascade, legacy paper, prioritised for future curation
- mcs4 was fixed yesterday
- sin1 - legacy paper, I can't see the annotation in artemis. Does that mean it has been removed? I put the paper on my list.
- sty1 looks fixed
 - srk1 - this one is a target of the MAPK cascade, so that's fine? or what would the alternative be?
- win1 looks fixd
- wis4 fixed

**Comment by ValWood** [comment]
positve regulation seems to be the way  that was being proposed, because the MAPK cascade is defined to begin with MAPKKK (although this was never clear to me until now).
It is fairly arbitrary, because most people would view this as a single pathway, not one pathway regulating another. But you can see that it would be impossible to have a term for every incarnation of 
feedin pathway + MAP cascade+ stress 
so this modular approach does work. I don't remember it ever being communicated, but it makes sense...

Lets see how it looks tomorrow. We should be able to follow  the pathway in your figure and all the processes be consistent (with different "in response to"  downstream of different feed in points, obviously these won't be saturating but we should get the picture)

**Comment by Antonialock** [comment]
Just to clarify, so it is fine that cmk2 is not annotated to the mapk cascade? (I wouldn't except it to be annotated to it if it is downstream of the MAPK, I think the current guidelines make sense)

Which GO ticket? this one? 
https://github.com/geneontology/go-annotation/issues/1597

**Comment by Antonialock** [comment]
Just to clarify, so it is fine that cmk2 is not annotated to the mapk cascade? (I wouldn't except it to be annotated to it if it is downstream of the MAPK, I think the current guidelines make sense)

Which GO ticket? this one? 
https://github.com/geneontology/go-annotation/issues/1597

**Comment by ValWood** [comment]
I didn't expect them to be, but according to the definition  and this discussion they should be:
https://github.com/geneontology/go-annotation/issues/1598

**Comment by Antonialock** [comment]
I see. Ok. It makes sense to not have the MAPKAK MF (also MAPKs etc have sequence similarity? whereas I guess there is no sequence "theme" among the MAPKAKs?)

I will close this ticket and proceed to #1605

**Comment by ValWood** [comment]
Its not that. The  fact that it is phosphorylated BY a MAPK is nothing to do with its activity...

The MAPK designations  specify the *substrate* not the think that modified them. Its quite different....
