### ISSUE TITLE
Qusetion, negative regulation of signal transduction in absence of ligand

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1580]
I noticed this term. What doe is mean? Wouldn't the pathway normally be inactive in the absence of ligand?

**Comment by Antonialock** [comment]
phenotype only....part of this pathway is constitutively expressed at low levels (the part that positively regulates its own transcription), if you delete the receptor you get increased activation of the pathway...I guess because the galpha isn't sequestered...

**Comment by Antonialock** [comment]
removed

**Comment by ValWood** [comment]
OK, I guess it has the phenotype?

**Comment by Antonialock** [comment]
yes..
