### ISSUE TITLE
git related

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1582]
![git](https://user-images.githubusercontent.com/7359272/28054277-3405741a-660c-11e7-855a-5b78d7402498.jpg)

can get7 have the same more specific annotation as the other gits?

**Comment by ValWood** [comment]
Also, in GO should this be is_a cAMP mediated signalling?

**Comment by ValWood** [comment]
GO:0007188 | adenylate cyclase-modulating G-protein coupled receptor signaling pathway
is a NAS

I think the 2 Schadick paper  processes = 

GO:0010619 adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway?

**Comment by ValWood** [comment]
git1 and pka1 have only camp-mediated signalling, but aren't they same pathway?

-> 
GO:0007188 | adenylate cyclase-modulating G-protein coupled receptor signaling pathway

**Comment by ValWood** [comment]
and pka1
glucose mediated signalling pathway should be able to be
GO:0010619 adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway?

If you know it is in the same pathway you should be able to annotate to the same term as other  pathway members?

**Comment by ValWood** [comment]
- [ ] also git11 is not annotated to this signalling pathway?

**Comment by ValWood** [comment]
this is how the signalling map looks for git?, quite a few not visible?

![pka1_map](https://user-images.githubusercontent.com/7359272/28056232-118023ec-6614-11e7-8d20-f4bbdc3debf0.jpg)

**Comment by Antonialock** [comment]
A bit of an unstructured ticket Val, where are the tick boxes :-) 

![screen shot 2017-07-14 at 10 15 51](https://user-images.githubusercontent.com/12727506/28206375-85b451fa-687d-11e7-8ef5-a3af7bf14372.png)

1.  "can get7 have the same more specific annotation as the other gits?"
Maybe... I'm not sure if it is part of the GPCR cascade. It is downstream of the galpha but git7, git10 (hsp90) and git1 are needed for the activation of cyr1. It is not known how. Git1 physically interacts with cyr1, so it is probably ok for git1 at least
- put 12456004 on my list
- removed git7 NAS to adenylate cyclase-modulating G-protein coupled receptor signaling pathway 
- git1 git7 git10 now all have the terms i) activation of adenylate cyclase activity ii) positive regulation of cAMP-mediated signaling iii) negative regulation of transcription by glucose
- added  adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway  to git1

2. Also, in GO should this be is_a cAMP mediated signalling?
I've requested this

3. I think the 2 Schadick paper processes = GO:0010619 adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway?
- There is only 1 schadick paper?
https://www.ncbi.nlm.nih.gov/pubmed/?term=Schadick%20K%5BAuthor%5D&cauthor=true&cauthor_uid=12456004
-this paper has not been done yet, I put it on my list. It looks like they show that it activates cyr1, but not that it is part of the GPCR cascade

4. git1 and pka1 have only camp-mediated signalling, but aren't they same pathway? ->
GO:0007188 | adenylate cyclase-modulating G-protein coupled receptor signaling pathway
- see above for git1
- pka1 doesn't modulate adenylate cyclase, it's an effector of activated adenylate cyclase. The comment on that term however states "This term is intended to cover steps in a GPCR signaling pathway both upstream and downstream of adenylate-cyclase activity." so I guess it is ok....
-> added GO:0007188 | adenylate cyclase-modulating G-protein coupled receptor signaling pathway to pka1

5.  also git11 is not annotated to this signalling pathway?
-done

Additional: 
- all git genes with the exceptions of git7, git10 and git9 should now be annotated to this pathway
- sck1 NTR for negative regulation of adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway 
- annotated cgs1 to directly negatively regulates pka1 a6a51043db00c124
- tup11, tup12 and lkh1 annotated to neg reg of transc by glucose (I was naughty and curated a paper...)  04b16267fe7a710d I'm not sure how lkh1 connects with pka1....
- made connection between this pathway and phosphoryation of rst2 (I was double naughty and annotated a second paper...it is friday ;) ) d1d283a2ef48f053
- I hate the term "negative regulation of transcription by glucose" it sounds like a phenotype. I know you want to keep it...should clc1 also have this BP? it is git9...

I think this pathway should be pretty much done now...there might be some papers lurking where more genes are tied in but the main players should be correct.

**Comment by ValWood** [comment]
Yes that one was a steam of conciousness.
I spotted a provblem with the autogenerated pathway.
We are using a  "complex grouping term" heterotrimeric G-protein complex
instead of terms for individual complexes. This means that the  Glucose sending pathway  and the conjugation one are glued together.

We will need to represent these as "protein binding" or substrate -> target.
I will add a filter for GO:0005834 - heterotrimeric G-protein complex
to the complex file (but this will not disappear until
https://github.com/pombase/website/issues/273
is done

**Comment by ValWood** [comment]
GO:0005834 added to
pombe-embl/supporting_files/Complex_annotation_filters 
(we could also request specific complexes to annotate, but this will also depend on new complex file generation)

**Comment by ValWood** [comment]
- [x] I hate the term "negative regulation of transcription by glucose" it sounds like a phenotype. I know you want to keep it...should clc1 also have this BP? it is git9...

I am not attached to this term...it is historical
http://europepmc.org/abstract/MED/11018147
I would propose to obsolete ;)

**Comment by ValWood** [comment]
How does git7 fit in?

Ah clc1, yes I see, that  looks indirectly upstream for sure...phenotype only!

**Comment by ValWood** [comment]
I think I meant 2 process from  schadick paper, not 2 papers.
It sounds as though you have this pretty much covered!

Will take a look after tomorrows updates. Today was meeting-full.....

**Comment by ValWood** [comment]
Not sure what is still to do for git but

- [ ] gpa2/gpb1/git11 -> cyr1?
- [ ] cyr1->cap1
- [ ] git3->gpa2
from
https://github.com/pombase/curation/issues/940

**Comment by Antonialock** [comment]
to go back to what this ticket is about, git7 should not have this annotation (it is rescued by TORC1 signalling!)
