### ISSUE TITLE
gnr1 signal transducer

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1584]
This is described as a signal transducer.
http://pombase2.bioinformatics.nz/reference/PMID%3A16884933

But, it seems to be an inhibitor of a signal transducer? and not required FOR signal trasnduction?

**Comment by ValWood** [comment]
In case it's not obvious this should be something like

GTPase inhibitor? target G-protein alpha involved in "negative regulation of x signal transduction" ?

**Comment by Antonialock** [comment]
TAS so didn't show in the curation session..removed
also added reciprocal protein binding gnr1-gpa1 + FP link

**Comment by ValWood** [comment]
So what is the MF?
GTPase inhibitor? target G-protein alpha

**Comment by Antonialock** [comment]
betagamma dimers are not GTPase inhibitors, they typically stabilizes the GDP bound form of Galphas (and typically, activation of the GPCR promotes GDP for GTP exchange on the Galpha).

I don't think you can say from this paper....I did protein binding + FP link
