### ISSUE TITLE
signalling cascade

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1585]
A lot of components of the signalling pathway are annotated to "positive regulation of the pathway" rather than directly to the pathway? (these are part of the pathway.
They are positively regulating the downstream processes.

**Comment by ValWood** [comment]
e.g
http://preview.pombase.org/gene/SPBC215.04
http://preview.pombase.org/gene/SPBC32H8.07

cAMP-mediated signaling NOT "regulation of cAMP mediated signalling" etc

within a pathway is not regulating the pathway. It might be regulating the next *molecular function* in the pathway, but this is part of the  signalling process, not  regulation.

**Comment by ValWood** [comment]
So if it is within the pathway it isn't regulation.
If its upstream it might be.

**Comment by Antonialock** [comment]
I think I have fixed all these now looking at this page
http://preview.pombase.org/term/GO%3A1902533

**Comment by ValWood** [comment]
brill!

**Comment by ValWood** [comment]
Mainly gone, small tickets for  some
