### ISSUE TITLE
signalling review , downstream processes should be "regulation of"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1586]
For example
http://preview.pombase.org/gene/SPAC1D4.13

should be regulation of conjugation

For the processes, if the terms do not exist I would do

MAPK cascade  part_of regulation of   ascospore formation
MAPK cascade  part_of regulation of   regulation of conjugation with cellular fusion

because the word is that we wont't have precomposed terms for signal transuduction regulating process (unsustainable)

--

**Comment by Antonialock** [comment]
fixed byr1, spk1, byr2

**Comment by ValWood** [comment]
byr2 http://pombase2.aska.gen.nz/gene/SPBC1D7.05
spk1 http://pombase2.aska.gen.nz/gene/SPAC31G5.09c
byr1 http://pombase2.aska.gen.nz/gene/SPAC1D4.13
look the same?

**Comment by ValWood** [comment]
@kimrutherford  and no changes here. did the update use  yesterdays data?

**Comment by Antonialock** [comment]
oh, I slightly misunderstood...I thought you meant that if the MAPK yadiyada term existsed then just add the FP link, but I now see the regulation problem in these terms.


I changed to this
![screen shot 2017-07-13 at 09 50 55](https://user-images.githubusercontent.com/12727506/28158224-f0f82e3c-67b0-11e7-98ff-e3f685eef447.png)

problem: the extension interface doesn't technically allow you to use "part_of" on these processes, should it? (I added it as text)

**Comment by ValWood** [comment]
OK, can you say the direction of regulation (positive?)

I have been doing it as text too. Technically we could request the terms, but I don't think we would get them, and it  would compound the existing problems...

**Comment by Antonialock** [comment]
done
