### ISSUE TITLE
 inactivation of MAPK activity

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1587]
I don't think we need to use this term (or descendants)

GO:0000173 | inactivation of MAPK activity involved in osmosensory signaling pathway

should be

MAP kinase threonine phosphatase activity directly_inhibits gene_x(MAPK activity)

**Comment by ValWood** [comment]
- [ ] ptc1 http://preview.pombase.org/gene/SPAC2G11.07c

deleted artemis
/GO="aspect=F; term=protein serine/threonine phosphatase activity; GOid=GO:0004722; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000000152; date=20141208"
unnecessary

**Comment by ValWood** [comment]
- [x]  deleted
/GO="aspect=P; term=inactivation of MAPK activity during osmolarity sensing; GOid=GO:0000173; evidence=IMP; db_xref=PMID:7859738; date=20050708"
added paper to priorities

**Comment by ValWood** [comment]
- [ ] SPCC4F11.02.1		GO:0000173		PomBase
- [ ] SPCC1223.11.1		GO:0000173		PomBase
- [ ] SPAC26F1.10c.1	GO:0000173		PomBase

**Comment by ValWood** [comment]
@Antonialock  just check my final  change in your session and close

**Comment by ValWood** [comment]
note PMID:7859738 is in high priority paper list, covers all 3 MAPK phosphatases

**Comment by Antonialock** [comment]
yes looks right
