### ISSUE TITLE
phosphatase which regulates MAP kinase pathway (pmp1)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1588]
needs to be negative regulation of 
http://pombase2.bioinformatics.nz/gene/SPBC1685.01

MAP kinase tyrosine phosphatase has_substrate pmk1 (MAP kinase)
involved_in negative regulation of MAPK cascade

- [x] update to
pmp1 | GO:0033550 | MAP kinase tyrosine phosphatase activity | EXP |   | directly_inhibits PomBase:SPBC119.08 , part_of negative regulation of MAPK cascade

**Comment by ValWood** [comment]
- [ ]  @Antonialock  I'm confused why this is 
positively regulating signal transduction involved in conjugation?

If its a MAPK phosphatase, its directly inhibiting a MAP kinase, and the MAP kinase  (presumably Spk1 or Sty1 here)  is positively  regulating conjugation. It doesn't seem to add up?

- [ ]

**Comment by ValWood** [comment]
- [ ] I don't think this should be
GO:0022604 | regulation of cell morphogenesis ?
The cell shape defects are really cytokinesis defects

(the abstact says  Pmp1 and calcineurin share an essential function in Cl- homeostasis, cytokinesis and cell viability." In fact I would remove 'pear shaped'  I see branched, stubby and elongated in figure 6?
Pear shaped is a much stronger round bulbous part with a narrow part.

In general be wary of using  morphology phenotypes to make  a morphology Go annotation without more information. This is strong enough for cytokinesis  term though.  Multiple septa etc

**Comment by Antonialock** [comment]
wow, PMID:9427748 is old. updated phenotypes, GO terms, extensions. 

PMID:12172965
left to review

**Comment by ValWood** [comment]
I have been re doing some of my older papers this week, and OH MY GOD...
But we get better!

**Comment by Antonialock** [comment]
PMID:12172965 
another blast from the past....updated phenotypes to what we do now and removed the BPs (phenotypes only)

**Comment by Antonialock** [comment]
yeah I know, it's a bit embarrassing really :-)

**Comment by ValWood** [comment]
Note that "phenotypes only" can be used to make GO process annotations. But..the phenotype must be  specific/clear cut enough to indicate the process. For example a cell cycle block is not specific enough to implicate in "cell cycle  transition regulation" but another phenotype could well be.

Main questions to ask. 
1. Is this phenotype specific for this process (or is it seen associated with Gene products that we know are not involved in this process).
2. Based on this phenotype and the combination of data knowledge, author intent do we feel comfortable making the annotation from the phenotype. For example, but we can make an MF annotation to something which looks like a transporter, based on a transport defect using IMP. We probably wouldn't make the same inference from a phenotype for something which does not look like a transporter (this one is a fudge, I know but the phenotype 'supports' the assertion, rather than confirms it, which is more like how Cam Models work).

**Comment by ValWood** [comment]
> yeah I know, it's a bit embarrassing really :-)

Not really. The annotation used to be like the rest. Now it's much better;)
