### ISSUE TITLE
GO:0031098 - stress-activated protein kinase signaling cascade

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1589]
we should not need to use this term directly?

can always be more specific?
stress-activated MAPK cascade
or  positive/negative regulation of?

**Comment by ValWood** [comment]
stress-activated protein kinase signaling cascade

  | cmk2, mak2, mak3, mcs4, sin1, srk1, sty1, win1, wis4

**Comment by ValWood** [comment]
Could you do the 2 which need checking as a sanity check to see if you agree?

**Comment by Antonialock** [comment]
mak2 - done
mak3 - put the paper on my list, updated annotation in artemis
