### ISSUE TITLE
protein localization to prospore membrane

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1592]
Annotations in this paper cropped up in  a chat with Pascale
http://pombase2.bioinformatics.nz/reference/PMID%3A12557273

Can we check this paper. If we make a 
protein localization to prospore membrane
we should be able to say the target, if we think it really it is "localization" or just a phenotype. ...and if it is, what is the localization target (note there is no localization phenotype)

**Comment by ValWood** [comment]
I had   a quick skim through this paper and I could not see a localization experiment?
@Antonialock  could you check ?
(If you want to reannotate keep it  for later!)

**Comment by ValWood** [comment]
@pgaudet I don't think this is more than a phenotype. Certainly no mechanism for localization.

**Comment by Antonialock** [comment]
no they were just looking at spo3 as a marker for prospore membrane formation, I removed it.
