### ISSUE TITLE
MAPK cascade question

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1593]
How  do people usually refer to the 3 different MAPK cascades?

**Comment by ValWood** [comment]
Are all 3 MAPK cascades activated in response to stress of some sort? or just some of them. It's unclear to me how they are named, vs what they respond to vs. what they regulate.
Can you generalise for me?

**Comment by Antonialock** [comment]
Directly or indirectly? 

The pathway starting with the wis4/win1 MAPKKKs is activated in response to stress (osmo, oxidative, heat).
mkh1 pathway also stress ("cell integrity pathway") 
The byr2 pathway is activated in response to pheromone (indirectly stress I suppose?)

I did most of the signalling papers <4 years ago. With the P2 term pages it is so clear to see that annotation is inconsistent. I'd love to spend time on fixing these pathways.

**Comment by ValWood** [comment]
So there are 3 separate pathways.
What are there "usual" names, if any in fission yeast?
(i.e how do people usually differentiate between them in papers).

This question is independent of the GO annotations/terms.

Byr2-Byr1-spk1
Mkh1- Pek1-Pmk1
Win1/Wis4- Wis1-Sty1 

So all MAPK pathways are  really  "stress-activated MAPK cascade"
there is really  no difference between "osmolarity sensing pathway" and "stress-activated MAPK cascade". The same pathway responds to multiple stresses.

> I'd love to spend time on fixing these pathways.
Don't worry, you are  right now.

**Comment by Antonialock** [comment]
well there are different mechanisms of feeding in....I have a feeling there is also a difference of how it is activated depending on the type of peroxide stress (eg H2O2 vs tBOOH) but I can't remember how

![screen shot 2017-07-13 at 09 57 52](https://user-images.githubusercontent.com/12727506/28158479-cbf2a4a4-67b1-11e7-97a6-517338646fbf.png)

**Comment by ValWood** [comment]
Ah thats a nice summary!
@ukemi more problems!

**Comment by ukemi** [comment]
In mammals, the MAPK cascade lies downstream of lots of other signaling, including growth factors. The question is whether we want to make all of the different flavors based on the upstream events. I don't think this is feasible and I suspect it is why in the original signaling work, they make this comment. 

MAPK cascades lie downstream of many cell surface receptors and cooperate in transmitting various extracellular signals to the nucleus. One way by which the specificity of each cascade is regulated is through the existence of several distinct components in each tier of the different cascades. The cascades are typically named according to the component in the MAPK tier.

When we begin to look at the totality of annotations, I think that the different types of MAPK cascades should be differentiated by the molecules that have the MFs specified in the current cascade definition. Currently we also have MAPK cascade involved in blah terms, but I'm not sure those are really different MAPK cascades. 

The diagram that Antonia shows above is the great basis for a GO-CAM model. 

The other axis of classification would be what happens after the MAPK activated kinase. I wonder how many different mechanisms for that we will find.

**Comment by ValWood** [comment]
so here
"When we begin to look at the totality of annotations, I think that the different types of MAPK cascades should be differentiated by the molecules that have the MFs specified in the current cascade definition. Currently we also have MAPK cascade involved in blah terms, but I'm not sure those are really different MAPK cascades."

what do you mean?

Do you envisage 
Win1/Wis1/Sty1 MAPK pathway etc?
This would be a nightmare...different names in every species.
Also cross talk between pathways...

**Comment by ValWood** [comment]
will review pathway  when annotating
