### ISSUE TITLE
Win1/Wis4- Wis1-Sty1 MAPK cascade Day 2 review

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1605]
So from this image:
![image](https://user-images.githubusercontent.com/12727506/28203102-1aab0e10-6870-11e7-9fa2-c15b8ce3faaf.png)

- [x] mak3 needs the annotation "positive regulation of stress-activated MAPK cascade"  "involved in cellular response to oxidative stress" 
- [x] mpr1/tdh1 needs annotation updating from "response to" to cellular response to" on the +ve reg of stress activated term
- [x] should mcs4 have the "involved in heat" extension?
- [x] how do ptc1/3 fit in? 
- [x] how does ptc4 fit in? 
- [x] pyp2 Millar 95?

- [x] can pyp1 be annotated from the same paper or another one to the same term?
- [x] cmk2 MAPKAK extensions
- [x] lsk1 MAPKAK
- [x] srk1 MAPKAK     18272791
- [x] sty1 needs during cellular response to osmotic stress
- [x] does win1 need extension "hydrogen peroxide/heat? (I think wis4/win1 have slightly different specificities)
- [x] wis1 needs all extensions
- [x]  mak2 , mcs4 , sty1 are annotated to hydrogen peroxide mediated signaling pathway
- [x]  tdh1 is annotated to "positive regulation of phosphorelay signal transduction system involved in hydrogen peroxide mediated signaling pathway"
- [x]   still have annotations to MAPK cascade involved in osmosensory signaling pathway
- [x]    Mcs4 RR-MAPKKK complex needs more components
- [x]     ppk18 is annotated to GO:0000160 - phosphorelay signal transduction system ?
- [x]    cellular resposne to osmotic stress -> osmosensory?
- [x]    clean up sty1 BPs
- [x]    srk1 targets cdc25, PMID:26575035

Whoopdedoo @ValWood , we don't need to wait 6 months to check fixes :-)

**Comment by ValWood** [comment]
Sounds good.
For the stress extensions, can you use involved_in rather than "during". The implication is that this is  "involved in" the response process, rather than just "happening at the same time"

**Comment by Antonialock** [comment]
even for heat?

**Comment by ValWood** [comment]
>Whoopdedoo @ValWood , we don't need to wait 6 months to check fixes :-)

It's bloody brilliant isn't it.... we can work!

looking good
http://pombase2.aska.gen.nz/term/GO%3A0000165

**Comment by ValWood** [comment]
lets leave heat "during" do you think, less clear?

**Comment by Antonialock** [comment]
yeah..

**Comment by Antonialock** [comment]
it looks like ssp1 is a hub taking input from different kinases to neg reg cdc25

**Comment by ValWood** [comment]
are you sure?
It's upstream of cdr2 inhibiting wee1? 
https://github.com/pombase/curation/issues/1049
(but I think sid2 mob1  fin1 are somewhere upstream)

**Comment by Antonialock** [comment]
red herring..
