### ISSUE TITLE
git pathway (and other signalling receptors)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1609]
I just spotted that  git3 and gpa2 are annotated to

http://preview.pombase.org/term/GO%3A0051594
detection of glucose

These should really be
G-protein coupled glucose receptor activity
(detection of glucose I suspect should not exist, but should be an F-P link if it does)

(git3 has this already)
If gpa2 is part of the receptor maybe it should have this annotation with "contributes to"

- [x] I will request F-P link (or obsoletion of) glucose sensing)

**Comment by ValWood** [comment]
agree?

**Comment by Antonialock** [comment]
I removed it from gpa2 already

**Comment by Antonialock** [comment]
but kept it for git3 (G-protein coupled glucose receptor activity sounds good though...I didn't think of this one, so many terms hanging about...)

**Comment by ValWood** [comment]
Always think of the molecular function first, what is this actually doing.... then you can eliminate any of the wanky-processes that are saying the same thing. Top tip...

**Comment by ValWood** [comment]
gpa1 etc, should all  g-protein receptor?

**Comment by Antonialock** [comment]
removed from git3
