### ISSUE TITLE
regulation of cAMP-mediated signaling

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1615]
- [x] atf1 , 
- [x] cgs2 , 
- [x] pcr1 , 
- [x] sty1

-ve of -ve 
(term might not be required anyway )?

**Comment by ValWood** [comment]
on cgs2 I'm not sure what these terms mean in context:

GO:2000480 | negative regulation of cAMP-dependent protein kinase activity | IGI with cyr1 | Demirbas D et al. (2011) 
- | GO:1902660 | negative regulation of glucose mediated signaling pathway | IGI with cyr1 | Demirbas D et al. (2011)

Is this a way of regulating the pathway  by removing cAMP?
should the kinase term have pka1 as a substrate?
Or should we curate removal of a substrate as negative regulation of enzyme activity? (i'm not sure)



--

**Comment by Antonialock** [comment]
From a different paper I annotated cgs2 as neg reg of glucose activated camp mediated GPCR pathway yadiyada....I don't think it negatively regulates the enzyme activity (just the output of the enzyme activity)....

these annotations need a bit of cleaning.

**Comment by Antonialock** [comment]
reviewed all
