### ISSUE TITLE
proteins classed as "inferred process" but no slim process annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1622]
- [x] SPBC1861.02  abp2 call this uncharacterised -> colour 10, no follow up in 20 years
- [x] SPAC3A11.02    cps3, revert to unknown, no characterisation
- [x] SPBC14C8.09c  dbl3, changed to 10, no indfo other than ds-break binding
- [x] SPBC17D11.08  regulation of DNA replication P61962
- [x] SPBC646.17c   microtubule cytoskeleton process IC GO:0005868
- [x] SPBC146.04    protein refolding? P55789
- [x] SPBC354.01 colour7
- [x] SPBC2G2.04c   ADD   isoleucine biosynthetic process  S000001313
- [x] SPAC343.07    UNKNOWN
- [x] SPAC630.09c   UNKNOWN
- [x] SPBC713.11c
- [x] SPAC19D5.04 GO:0006364 SGD
- [x] SPCC1442.16c  detoxification Q08257
- [x] SPAC3A12.08  acyl-CoA metabolic process Q5T1C6
- [x] SPAC4H3.01
- [x] SPAC823.09c
- [x] SPAPB2B4.06 fatty acid metabolic process Q5T1C6
- [x] SPBC17A3.05c chaperone cofactor-dependent protein refolding
- [x] SPBC4.06	ADD phospholipid metabolic process   Q9NPH0
- [x] SPBC2D10.20
- [x] SPBC211.07c
- [x] SPAC1071.09c UNKNOWN
- [x] SPBC56F2.03	ADD   microtubule based transport IC from dynactin
- [x] SPCC61.03     -> ISS NAD biosynthesis via nicotinamide riboside salvage pathway
- [x] SPAC24C9.14   otu1 IS This published?
- [x] SPAC1952.03   otu2 IS This published?
- [x] SPAC3F10.15c spo12, quite a few papers but no process (called unknown as there doesn't seem to be anything clear)
- [x] SPBC649.04  uvi15
- [x] SPCC16C4.07 RNA-binding protein Scw1, published (curated paper)
- [x] SPBC20F10.10 cyclin psl1 had to go with NAS to "regulation of cell cycle transition" which seems safe as cerevisiae orthologs are cdk1 binding partners. Reverted from published to inferred as I can't find any functional info
- [x] SPBC18H10.15  cdk11 https://github.com/pombase/curation/issues/1565 added an NAS which will be  filtered when the curation comes through

published in some depth but no biological role, ignore for now
- [ ] SPBC839.07 ask Susan
- [ ] SPAC1071.12c stp1 quite a few papers but no process published, unkown role

published recently but not curated
- [ ] SPCC4G3.11	published but not curated nur1 PMID:27451393 
- [ ] SPBC29A10.12  PUBLISHED 2017
- [ ] ptf1  PMID:22184112

- [ ] SPAC12B10.14c tea5 where is name from as I can't find any papers, ask @haylesjv
- [ ] SPBP35G2.02    26S proteasome co-factor Txc1

- [ ] SPAC4F10.04  protein phosphatase type 2A regulator, PTPA family Ypa1
- [ ] SPAC1782.05  protein phosphatase type 2A regulator, PTPA family Ypa2

mtr
- [ ] SPBC1711.02  m-t-r
- [ ] SPMTR.04 m-t-r
- [ ] SPMTR.03 m-t-r

signalling
- [x] SPAC2F7.02c sounds like signalling, but no term
- [x] SPBC1271.03c sounds like signalling, but no term.
- [x] SPBC216.01c -> signalling

other
- [ ] SPBC1289.16c copper amine oxidase, what process? possibly non-functional
- [x] SPBC8D2.01	protein degradation???
- [x] SPAC1039.11c alpha-glucosidase
- [x] SPAC25H1.09   ADD	fungal-type cell wall biogenesis
- [ ] SPCC16C4.12   ADD protein maturation
- [ ] SPBC21B10.05c @Antonialock torc process?
- [x] SPAC823.14 L-serine biosynthetic process P78330???? not sure transferred to
https://github.com/pombase/curation/issues/1633
- [x] SPBC1734.05c mRNA splicing, via spliceosome  but TAS reactome, trace paper mail UniProt - https://github.com/pombase/curation/issues/1632
- [x] SPAC1039.06 alanine racemase - > D-serine ammonia-lyase activity
- [x] SPAC186.06   FIXED…actually where does the process come from, we did not curate this paper
- [x] SPAC27E2.01  alpha-amylase 
- [ ] SPAC9.02c  sgd has chromatin organization  , seems odd
- [x] SPAPB24D3.03 agmatinase
- [x] SPBC16E9.15 http://www.uniprot.org/uniprot/O75506 check for EXP for TAS
- [x] SPBC21H7.03c acid phosphatase
- [x] SPCC297.05  -> reg endosome-vac
- [x] ulp2 SPAC17A5.07c

rearranged
- [ ] SPAC212.06c DNA helicase in rearranged telomeric region, truncated
- [ ] SPAC977.04  truncated C terminal region of membrane transporter
- [ ] SPAC186.04c  N-terminal of transmembrane channel, truncated

my big rock for tomorrow....

**Comment by ValWood** [comment]
Jacky has never heard of tea5 either. I can't find anything in my e-mail archive about this name.
For now I will change this to an obsolete name and revert to "conserved unknown"

**Comment by Antonialock** [comment]
Looks like tea5 was named by the Chang lab?
https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=11&cad=rja&uact=8&ved=0ahUKEwjR6aOq5JPVAhWPb1AKHQ7_DIU4ChAWCCMwAA&url=https%3A%2F%2Facademiccommons.columbia.edu%2Fdownload%2Ffedora_content%2Fdownload%2Fac%3A206020%2FCONTENT%2FLutz_columbia_0054D_12454.pdf&usg=AFQjCNHCvEU6HOCaBUyATDs-Qu_XeNLl6A

"Based upon its properties described below we named this gene tea5 (tip elongation aberrant 5). The amino acid sequence of tea5p is predicted to have a kinase domain with sequence variations in its active site, suggesting it is a pseudokinase."

also in this pub
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5011436/

**Comment by ValWood** [comment]
Good detective work. I'll give it some sort of high level  polarity annotation for now with a TAS to Fulvia's paper...I'll call it a kinase until anything is published to the contrary...

**Comment by ValWood** [comment]
curated PMID:24818994 for ulp2

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/1622
moving back to my list of published/novel, as yet unannotated
