### ISSUE TITLE
oxidative stress vs response to hydrogen peroxide

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1625]
There doesn't appear to be a different feed in point for H2O2 than any other oxidative stress?

Could we change all
cellular response to hydrogen peroxide
to
 involved in cellular response to oxidative stress
do you think?

For example here: (ptc4)
http://pombase2.aska.gen.nz/gene/SPAC4A8.03c
we have

MAP kinase phosphatase activity   | has substrate sty1 involved in negative regulation of stress-activated MAPK cascade involved in cellular response to oxidative stress

then for the corresponding process we have:

negative regulation of stress-activated MAPK cascade
  | during cellular response to hydrogen peroxide

(the H2O2 information will still be available in the phenotype conditions for those who want 
 experimental details of  which stress condition was used, and because people will use different concentrations etc I don't think precisely which  stress is useful at the GO level).

**Comment by Antonialock** [comment]
yep.

I *think* I have changed them all....hard to know when they are buried in extensions

**Comment by ValWood** [comment]
We should be able to find these in Amigo, so  can do a check after next GO file update

**Comment by ValWood** [comment]
...or can just grep on the GAF file  for the extension tomorrow
