### ISSUE TITLE
		viable elongated aseptate vegetative cell

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1627]
check this phenotype.
This sounds odd, because if the cells are  really aseptate
they would be inviable.

I think these annotation  should probably be
viable elongated vegetative cell, elongated upon mitotic entry

check and if so, move and request obsoletion of this term

**Comment by ValWood** [comment]
adress with
https://github.com/pombase/curation/issues/1628

**Comment by ValWood** [comment]
I don't think we have this term any longer? I don't see it (@mah11  can you confirm?)

**Comment by mah11** [comment]
yes, FYPO:0004514 is obsolete
