### ISSUE TITLE
git pathway GPCR

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1630]
GO:0007190 activation of adenylate cyclase activity is a regulation of MF process term that we should not need to use.
It would only used for the previous step, the GPCR, and this should be
"MF adenylate cyclase activator activity"

GO:0010856 | adenylate cyclase activator activity

**Comment by ValWood** [comment]
PMID:1340462 phenotypes and genetic interactions conclusive enough to make "signal transducer" GO:0010856 | adenylate cyclase activator activity by IMP?

**Comment by Antonialock** [comment]
i think this term is ok to use for the g-alpha - it binds and directly activates cyr1. If you don't annotate it to this it will only have "protein binding" annotation to connect it to cyr1

**Comment by Antonialock** [comment]
oh sorry, I meant the MF! ... yeah if that's a BP then it is redundant.
