### ISSUE TITLE
G2/M transition via MAPK and TOR signalling

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1638]
![g2_m_tor_mapk](https://user-images.githubusercontent.com/7359272/28414472-b3c8ab48-6d43-11e7-9ed6-c62aabb6d445.jpg)

(https://github.com/pombase/curation/files/1162043/G2_M_TOR_MAPK.pdf)

genes not connected up:
- [x] ckk2 not annotated to regulation of G2/M  transition
- [x] mak3  not annotated to regulation of G2/M  transition but connected up to MAPK pathway. Need to decide where to begin
- [x] spp1  is G1/S
- [x] spp2 not sure why this is in the list
- [ ]  ppa2 to cdc25

**Comment by ValWood** [comment]
questions
- [ ] Is the MAPK part similar to this?
(sty1 is  annotated to -ve and -ve regulation of the transition, need to figure out which things are activating and inhibiting during nutrient excess and nutrient starvation:

![7df94186-2b48-11e7-8bca-639b61b930be](https://user-images.githubusercontent.com/7359272/28414532-f9a20056-6d43-11e7-9b4c-c16d5de508f9.jpg)

**Comment by ValWood** [comment]
This simplified figure has plo1 downstream of MAPK and upstream of  cdc25 abd wee1. I don't have this?


![df7da27e-7911-11e6-9747-9c3c7a526fa5](https://user-images.githubusercontent.com/7359272/28415774-108573ca-6d49-11e7-9361-ec6ed3697af0.jpg)

**Comment by Antonialock** [comment]
>  sty1 is annotated to -ve and +ve regulation of the transition:

>  sty1 activates srk1

>  active srk1 inhibits cdc25 keeps cdc2 inactive -> negative regulation of G2/M
so presumably this is the situation in nutrient rich conditions and the opposite applies in nutrient poor conditions?

This is doing my head in. sty1 activates srk1 during osmotic stress, and srk1 inhibits cdc25.
however, activation of srk1 by sty1 during stress also promotes the degradation of srk1, so the response is transient. I guess this is one of the comlicated mechanisms that could be influenced by adaptation etc.

**Comment by ValWood** [comment]
> activation of srk1 by sty1 during stress also promotes the degradation of srk1

which experiment is that? (I can't access the papers)
Presumably something downstream of sty1 signalling provides a feedback loop to degrade srk1?
Is it really sty1 turning srk1 off? (it guess it might be but it seems odd?)

**Comment by Antonialock** [comment]
apparently - sty1 binding to srk1 inherently stabilizes srk1 (neg reg of protein catabolism?). 

Once srk1 is phosphorylated it is activated and can go and phosphorylate cdc25 (which leads to nuclear exclusion of cdc25 -> neg reg G2/M)

However, unbound srk1 is unstable and is degraded meaning that the delay (neg reg G2/M) is on a 'timer'
https://curation.pombase.org/pombe/curs/8ee3edf9b1bcb1d5

[zmk1670-2.pdf](https://github.com/pombase/curation/files/1382727/zmk1670-2.pdf)

**Comment by ValWood** [comment]
OK I need to think about that for a bit!

**Comment by ValWood** [comment]
OK I don't think this means that sty1 is positively regulating the G2/M transition though...

It just means that to keep negatively regulating  G2/M sty1 needs to stay active (otherwise the phosphorylated srk1 disappears rapidly (short half life).

**Comment by Antonialock** [comment]
That was not the evidence used for the +ve reg of G2/M? 
It's the evidence used for neg reg of G2/M e.g. see https://curation.pombase.org/pombe/curs/8ee3edf9b1bcb1d5

**Comment by Antonialock** [comment]
so via srk1 it negatively regulates G2/M when cells are exposed to osmotic stress.

**Comment by ValWood** [comment]
So sty1 is doing 2 things

1) stabilizing srk1 (inactive, unphosphorylated form)

2) activating srk1 (by phosphorylation which induces disassociation, presumably the activated srk1 needs to dissociate to go on to find its targets)

Sty1 therefore -ve regulates G2/M by transiently activating srk1 (in response to stress)

Should be
sty1 binds srk1 (unphosphorylated form) part_of GO:0050821 protein stabilization
sty1 phosphorylates srk1 part of "-ve reg G2/M)

What happens to srk1 after it is released from sty1 is what occurs naturally (it isn't regulated by sty1).

I think?

**Comment by ValWood** [comment]
Yeah its the +ve regulation of G2/M which needs checking, but I suspect the above is true?

**Comment by Antonialock** [comment]
I think the above is true.

I think I checked the +ve reg of G2/M a few weeks ago and they also seemed sensible. Could you look? I geuss it is a different mechanism.

**Comment by ValWood** [comment]
Can you send me the papers, and which experiment, I can't access them.

**Comment by Antonialock** [comment]
free full text: https://www.ncbi.nlm.nih.gov/pubmed?term=7657164
[378739a0.pdf](https://github.com/pombase/curation/files/1383618/378739a0.pdf)

http://preview.pombase.org/reference/PMID:7501024
http://preview.pombase.org/reference/PMID:7657164

**Comment by ValWood** [comment]
PMID:7657164
sty1 mutants divide at reduced size (i.e divide early) when cells are stressed?
This means that normally sty1 is preventing G2/M (negatively regulating)?

**Comment by ValWood** [comment]
Ignore, mutant cells are unable to divide at a smaller size.

Yeah I'm confused now too.... Will need to ask Jacky....

**Comment by ValWood** [comment]
Arrrgh, this is so complicated. I thought I understood it......

**Comment by ValWood** [comment]
wis 1 has
positive regulation of G2/M transition of mitotic cell cycle
but I thought it was negative?

allso consider
#1638 (comment)
has sty1 activating plo1 to activate cdc25

**Comment by ValWood** [comment]
Outstanding tasks in 
https://github.com/pombase/curation/issues/2900
