### ISSUE TITLE
pka1 function process links

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1657]
| protein serine/threonine kinase activity | 105
-- | -- | --
has substrate                                         mei3

can probably make a fp link here

**Comment by Antonialock** [comment]
check next update

**Comment by ValWood** [comment]
has the substrate but no F-P link

**Comment by Antonialock** [comment]
can;t make one from paper.

**Comment by ValWood** [comment]
but taken together with phenotypes we could say "regulation of meiotic cell cycle"? because mei3 is specific for this?

**Comment by Antonialock** [comment]
logically yes, I just didn't think there was enough evidence in this paper
