### ISSUE TITLE
pheromone signaling ticket

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1662]
- [ ]    need to connect gpa1 / ras / byr2

**Comment by Antonialock** [comment]
dont think this can be done...

**Comment by ValWood** [comment]
hmm, we know it is true, how do  we know?

**Comment by ValWood** [comment]
so it isn't possible to order/link these?
http://preview.pombase.org/term/GO:0032005

**Comment by Antonialock** [comment]
yeah but there could be a 'middle step' protein that connects the receptor module with the MAPK (the interaction isnt necessarily physically direct)

**Comment by Antonialock** [comment]
eg.
![screen shot 2017-09-07 at 18 52 12](https://user-images.githubusercontent.com/12727506/30177417-b99cfb38-93fd-11e7-946a-de74ec9dbab3.png)

**Comment by Antonialock** [comment]
I was thinking about making MF - substrate ennotation extensions here)

**Comment by ValWood** [comment]
yep that would be helpful...
