### ISSUE TITLE
GO data

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1668]
OK Let's start updating our GO data  at GO. 
It's pretty cleaned up since last submitted.
(especially for signalling).

**Comment by mah11** [comment]
Do we have a stable location for them to pull GAF, GPAD, and GPI yet? (I think it can be just GAF for a while if need be, and we can add GPAD and GPI when we're ready to produce them.)

If not, I can manually update the GAF periodically until we do have a place to point GOC. How often do you want it done?

**Comment by mah11** [comment]
I guess the question about a location is mainly for @kimrutherford

**Comment by mah11** [comment]
I have updated the GAF in the GO repository, and will do so in the middle of the month until we get the tell-GO-where-to-look system up and running.

**Comment by ValWood** [comment]
Thanks....dying to check out what the cdc2 page looks like ;)
Extension city.....

**Comment by ValWood** [comment]
OK?
