### ISSUE TITLE
PMID:7593289 FYPO evidence query

### ISSUE THREAD

**Issue by mah11** [pombase/curation#1676]
Quick question about two annotations from PMID:7593289 (https://curation.pombase.org/pombe/curs/5c6714c7f2a5126a/):

    cdc2-N152(aaD152N)[Overexpression]	FYPO:0001490	inviable elongated vegetative cell	Flow cytometry data		has_expressivity high	

    cdc2I172(aaT172I)[Overexpression]	FYPO:0001490	inviable elongated vegetative cell	Flow cytometry data	+ sorbitol	has_expressivity high	

Can you really tell that cells are elongated by flow cytometry? Or should the evidence be microscopy?

assigning to @Antonialock, who curated the paper

**Comment by Antonialock** [comment]
cheers, fixed to microscopy
