### ISSUE TITLE
negated GO annotation with extensions

### ISSUE THREAD

**Issue by mah11** [pombase/curation#1678]
This annotation gets flagged in the GOA syntax checks because NOT and extensions don't play nice together:

    Line 39113:	ERROR	Annotation_extension can not be supplied with NOT-qualified annotations [has_direct_input(PomBase:SPBC365.06),part_of(GO:0051604)]
    39113> PomBase	SPAC17A5.07c	ulp2	NOT	GO:0008233	PMID:24818994	IDA		F       SUMO deconjugating cysteine peptidase Ulp2 (predicted)		protein taxon:4896	20170719	PomBase has_direct_input(PomBase:SPBC365.06),part_of(GO:0051604)	

It comes from https://curation.pombase.org/pombe/curs/1116101d850ce3e6/

**Comment by ValWood** [comment]
deleted it.
