### ISSUE TITLE
ino80 complex transcription?

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1679]
depending on outcome of https://github.com/geneontology/go-ontology/issues/14141
may need to remove some annotations from ino80 complex subunits

**Comment by ValWood** [comment]
although....
https://github.com/geneontology/go-ontology/issues/14144

**Comment by ValWood** [comment]
but I guess that could just be clearing nucleosomes from promoters generally....I didn't look at the paper other than the abstract...
