### ISSUE TITLE
migrate to residue syntax (requires_feature(Pfam etc)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#168]
chromosome1.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF07647\);
chromosome1.contig:FT                   annotation\_extension=requires\_feature\(SO:0000204\);
chromosome1.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00659\);
chromosome1.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00659\);
chromosome1.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00651\);
chromosome1.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00787\);
chromosome1.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00018\);
chromosome1.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00564\);
chromosome1.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00169\);
chromosome1.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF04571\);
chromosome2.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00069\);
chromosome2.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00620\);
chromosome2.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF03114\);
chromosome2.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF03114\);
chromosome2.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00651\);
chromosome2.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF14260\);
chromosome3.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00651\);
chromosome3.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00653\);
chromosome3.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00653\);
chromosome3.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00653\);
chromosome3.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00400\)|requires\_feature\(Pfam:PF04494\);
chromosome3.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF00069\);
chromosome3.contig:FT                   annotation\_extension=requires\_feature\(Pfam:PF07535\);

Original comment by: ValWood

**Comment by ValWood** [comment]
We don't have this extension relation anymore so closing.....
