### ISSUE TITLE
check  high-affinity MF exists

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1688]
| high-affinity zinc II ion transmembrane import (GO:0044749) | 1
  | high-affinity iron ion transmembrane transport (GO:0006827) | 1
  | high affinity glucose import (GO:1990821) | 1
  | high-affinity hexose transport (GO:0008646)

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/14210#issuecomment-329805698

**Comment by Antonialock** [comment]
zinc - fine
iron - term exists but we haven't annotated to it. In PMID:8995275  they use an assay where FeCl3 is added to the uptake assay. FeCl3 is ferric iron and the term high-affinity ferric iron uptake transmembrane transporter activity exists. Just need to annotate the paper.

**Comment by Antonialock** [comment]
glucose - need to request

**Comment by Antonialock** [comment]
hexose - no need, that's from high affinity glucose transport

**Comment by Antonialock** [comment]
Ive requested the glucose term and will update it when it is available. I'll annotate the iron paper next.
