### ISSUE TITLE
increased GTP binding

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1689]
to what?
Is this to rho1 GTPAse?

![to what](https://user-images.githubusercontent.com/7359272/30559674-5a113e6e-9cad-11e7-913f-5015387f0eb2.jpg)

not to pxl1 anyway ...

**Comment by mah11** [comment]
which gene, or which paper? (type in screenshot isn't really big enough to read)

also not 100% sure what your question is ...

**Comment by ValWood** [comment]
pxl1 delta so pxl1?  
Pinar 2008? I thought that was enough info but
the paper is PMID:18256290

I don't know what  the  "GTP binding to" is decreased, there is no context. GTP binding to something is decreased?
I would assume it was the annotated gene, but since that gene is deleted it can't be?

**Comment by ValWood** [comment]
Ah I see, you said to small.
OK...

**Comment by mah11** [comment]
Thanks, and do you mean there should be an assayed_using extension?

**Comment by ValWood** [comment]
I guess that's how we would do it. I'm presuming it's Rho1 (I think that's the GTPase pxl1 regulates?)

**Comment by mah11** [comment]
extension added
(as text, so also edited config ...)
