### ISSUE TITLE
wee1 tidy check

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1692]
Check that annotations on wee1 page are sensible because we are using it as an example gene. E.g. it is annotated as both a ser/thr kinase + a tyrosine kinase, with itself as a substrate. Is this correct?

**Comment by ValWood** [comment]
yep.

**Comment by ValWood** [comment]
wee1 P's itself on serine
added by wee1 | IDA |   | Featherstone C et al. (1991)
-- | -- | -- | --
added by wee1 | IDA |   | Coleman TR et al. (1993)
added by wee1 | IDA |   | Hannig G et al. (1993)

and tyrosine
added by wee1 | IDA |   | Featherstone C et al. (1991)
-- | -- | -- | --
added by wee1 | IDA |   | Coleman TR et al. (1993)
added by wee1 | IDA |   | Hannig G et al. (1993)
