### ISSUE TITLE
add lncrna gene names

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1693]
http://onlinelibrary.wiley.com/doi/10.15252/embj.201796571/pdf

**Comment by Antonialock** [comment]
these names are reversed in the manuscript


In the supp table 1
nam2= SPNCRNA.1366
nam3=SPNCRNA.1696

however in fig 1b
nam3=SPNCRNA.1366

I have emailed the author to clarify

**Comment by ValWood** [comment]
@Antonialock  any feedback?

**Comment by Antonialock** [comment]
fig1b wrong
