### ISSUE TITLE
move  annotations back down to establishment or maintenece

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1694]
after demerge, need to check a pre 2017-07-13 GAf for

https://github.com/geneontology/go-ontology/issues/14219#issuecomment-331140986

SPAC2F7.10	akr1	palmitoyltransferase Akr1 (predicted)
SPBP16F5.07	apm1	AP-1 adaptor complex mu subunit Apm1
SPBC31F10.16	bch1	exomer complex ChAPs family (Chs5p-Arf1p-binding) protein Bch1
SPCC1620.05	bet4	Rab geranylgeranyltransferase alpha subunit Bet4 (predicted)
SPBC24C6.08c	bhd1	folliculin/Birt-Hogg-Dube syndrome ortholog Bhd1
SPAC17G6.04c	cpp1	protein farnesyltransferase beta subunit Cpp1
SPAC2E1P5.04c	cwg2	geranylgeranyltransferase I beta subunit Cwg2
SPAPB1A10.04c	cwp1	geranylgeranyltransferase I and farnesyltransferase alpha subunit Cwp1
SPCC794.08	efr3	phosphatidylinositol-4 kinase plasma membrane scaffold Efr3
SPBC3H7.09	erf2	palmitoyltransferase Erf2
SPAC3F10.07c	erf4	palmitoyltransferase complex subunit Erf4
SPBC1685.13	fhn1	eisosome assembly protein Fhn1
SPBC211.03c	gea1	guanyl-nucleotide exchange factor (predicted)
SPBC2F12.15c	pfa3	palmitoyltransferase Pfa3 (predicted)
SPBC691.01	pfa5	vacuolar membrane palmitoyltransferase Pfa5 (predicted)
SPAC2F7.03c	pom1	DYRK family cell polarity protein kinase Pom1
SPAC167.02	ptb1	geranylgeranyltransferase II beta subunit Ptb1
SPAC17H9.09c	ras1	GTPase Ras1
SPBC13G1.07	swf1	palmitoyltransferase Swf1 (predicted)
SPBC1706.01	tea4	tip elongation aberrant protein Tea4

**Comment by mah11** [comment]
done
