### ISSUE TITLE
Move Trac wiki to the curation GitHub wiki

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#1696]
This isn't urgent but it's probably a good move to migrate the wiki pages from Trac on oliver0.  It will be one less thing to maintain.

**Comment by ValWood** [comment]
Antonia and me should tackle this.  Midori has done too much tedious documentation stuff.

**Comment by ValWood** [comment]
transfer any useful inventories to static content
https://github.com/pombase/website/issues/386

**Comment by ValWood** [comment]
Most pages now deprecated as covered by documentation, or obsolete. Remaining are just lists I am working through. They don't need to be rehoused on the PomBase wiki.
