### ISSUE TITLE
Auto-generating models (cAMP signalling)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1699]
For each process, or  sub process we can auto-generate a bare-bones model of the connections within the  process, by importing the list of IDs into EsyN.

This generates a model like this...
(this is cAMP-mediated signalling)

Later we will add Molecular Function  and CC notation,  

![today_camp](https://user-images.githubusercontent.com/7359272/30870951-281f4294-a2dd-11e7-867a-8250b3a94143.jpg)

**Comment by ValWood** [comment]
Models are generated from 3 files
1) file of GO complexes (purple connections)
2 ) protein binding (orange connection, no arrowheadss)
3)  directional interactions use has_input extensions (orange with arrowhead)

Its a really quick way to see if you have all of the connections in a pathway WITHOUT building a GO-CAM model. Takes a few seconds....

Here we are still missing:
 - [ ] git3 glucose receptor activity has_input gpa2
 - [ ] currently we can't connect cyr12  (adenylate cyclase) to pka1 (would need to enable another relation, possibly provides input for?)
- [ ]  how pka1 connects to the TFs pcr1 and atf1

We also can't represent inhibition, but hope to d that later.

We can't colour the annotation according to specific pathway, the idea is that you only look at a specific pathway. Does that make sense? So you can look at a big pathway, but if you want to look at a subpathway you would generate the network  for that subset instead.

**Comment by ValWood** [comment]
This is ALL fission yeast signalling pathways:

http://www.esyn.org//builder.php?type=Graph&term=GO:0023052&interactionType=physical&source=pombase&includeInteractors=false

**Comment by ValWood** [comment]
- [ ] what does gpa2s gtpase activity act on? @Antonialock 
- [ ]  not in graph git1 , cgs2, ~ncs1~

@Antonialock  do I need to delete NAS from  git1?


adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway (GO:0010619) | 12
adenylate cyclase-activating G-protein coupled receptor signaling pathway (GO:0007189) | 12
cAMP-mediated signaling (GO:0019933) | 13

are almost consistently annotated

ncs1 is the extra annotation on cAMP-mediated signaling, need to check

@pgaudet thinks that GO:0019933  GO:0007189 are synonymous and I agree

**Comment by ValWood** [comment]
https://user-images.githubusercontent.com/7359272/30877308-2fce606a-a2f1-11e7-9716-b2cd7a577b78.jpg

Also ask @Antonialock  about  beta gamma side

**Comment by Antonialock** [comment]
I don't understand your quetsion Val, the GTPase activity acts on the GTP molecule

**Comment by ValWood** [comment]
OK but how does the GTPase activate adenylate cyclase?

**Comment by Antonialock** [comment]
I think it just binds? Typically (but not always) the heterotrimeric G protein is pre-bound to the GPCR. Ligand binding to the GPCR stimulates GDP for GTP exchange on the G protein -> it dissociates and binds to its downstream effector (eg adenylate cyclase in this case). GTP hydrolysis leads to dissociation of the G protein from the effector molecule and the G protein can go and rebind the GPCR
(it doesn't always happen exactly happen like this)

**Comment by ValWood** [comment]
So is it something like this:

The other  heterotrimeric G-protein subunits are some sort of "GDP dissociation inhibitor activity" (or is the unbound receptor the gpa2 inhibitor)
The receptor binding activates the GTPase and this inhibits its own inhibitors?


can we get this connection?
 git3 glucose receptor activity has_input gpa2
This clearly isn't the right activity but git3 does "something" to gpa2?

**Comment by Antonialock** [comment]
I'm not quite following what you mean Val (and this "inhibits its own inhibitors?" = ?). 
The GPCR does NOT activate the GTPase activity of G proteins (the GTPase activity turns signalling off. Receptor binding ligand stimulates GDP for GTP exchange on the G protein, the GTP bound form is the active form (often/typically/in-many-examples-but-not-all))

I think you can use has_substrate with "G-protein coupled glucose receptor activity" because the def specifies that ligand binding activates the G protein:
"Combining with an extracellular glucose molecule and transmitting the signal across the membrane by activating an associated G-protein; promotes the exchange of GDP for GTP on the alpha subunit of a heterotrimeric G-protein complex"

I can IC it...

**Comment by Antonialock** [comment]
or I think we can EXP it from a binding GO annotation

**Comment by Antonialock** [comment]
Val if you add in new annotations/change annotations in my sesions, could you please make sure they get your name stamp on them. It is very confusing to see annottions that I didn't make with my name on them.

**Comment by ValWood** [comment]
> I think you can use has_substrate with "G-protein coupled glucose receptor activity" 
Then that is what is missing.....

so when the GTPase is activated by git3 it dissociates and  activates adenylate cyclase?

**Comment by ValWood** [comment]
> Val if you add in new annotations/change annotations in my sesions, could you please make sure they get your name stamp on them. It is very confusing to see annottions that I didn't make with my name on them.

It would only be to add a missing substrate. So above, I added missing  cyr1 as substrate of "adenylate cyclase inhibitor". You want me to delete and make a new annotation?

**Comment by ValWood** [comment]
I think you can EXP it.

So what does a GTPase for in this scenario. Is it only  a switch? Active GTPAse dissociates from complex? I guess thats what GTPases are?

**Comment by Antonialock** [comment]
when the GTPase does its thing, GTP is hydrolyzed to GDP and the G protein dissociates from cyr1.

I have added the GPCR-G protein association.

**Comment by Antonialock** [comment]
git1 will get exp annotation fro PMID:16489217

**Comment by ValWood** [comment]
- [ ]  how is phospholipase C activated

- [ ]  is this downregulating CAMP signalling http://preview.pombase.org/gene/SPACUNK4.15

**Comment by ValWood** [comment]
> git1 will get exp annotation fro PMID:16489217

I see git1 now has 
positive regulation of adenylate cyclase activity
from IPI

isn't git1 a membrane anchor?  is it definitely a positive regulator of  adenylate cyclase?
It seems to be a necessary part of the pathway. I need to check from the signalling meeting how a protein anchor should be annotated.



--

**Comment by ValWood** [comment]
do this

**Comment by ValWood** [comment]
1. should  cgs1 have
adenylate cyclase-activating glucose-activated G protein-coupled receptor signaling pathway (GO:0010619)
