### ISSUE TITLE
Linear element components

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1705]
According to PMID:28893786 there are 4 major structural components of linear elements:
rec10 rec25 rec27 and mug20

currently we have 7 genes annotated to this term, including a kinase, ubiquitin ligase and SUMO.

Presumably we only want structural components annotated to this component? (I haven't read the papers but assuming the kinase just goes in to phosphorylate something then it should be removed? similar with the ligase? what about SUMO?) 

@ValWood  @mah11

**Comment by Antonialock** [comment]
(they do say that "Two other proteins, Hop1 and Mek1, also localize to LinEs and their localization depends on Rec10" so maybe they are part of the linear elements but might be worth it to check in case you think they might/should not be annotated to this term)

**Comment by ValWood** [comment]
I think it might be OK. I think linear elements are major structural components. A bit like a spindle pole body. we have ubiquitin ligases and kinases which are sometimes part_of the spindle pole body....

**Comment by mah11** [comment]
Yeah, I'd say it's OK if the kinase and the ligase go to the linear element to do something.

(I think that back when "colocalizes_with" had a hint of legitimacy, it was for situations like this. But the gain from ditching that qualifier outweighs the loss ...)

**Comment by ValWood** [comment]
Yep, ideally if we know when it localizes there we would add "during mitotic M phase" or similar

**Comment by Antonialock** [comment]
ok super.

**Comment by mah11** [comment]
ain't it great when the answer is "we don't have to do any work"?

**Comment by Antonialock** [comment]
;-)
