### ISSUE TITLE
MAPK scaffolds

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1709]
we only have one MAPK scaffold annotated

which probably has below threshold C2 and PH domain protein.
http://pfam.xfam.org/family/PF08578#tabview=tab1

PH domains are involved in signalling component recruitment
 and both C2 and PH domains appear to bind phospholipids and recruit things to membranes

PH
This domain can bind phosphatidylinositol lipids within biological membranes (such as phosphatidylinositol (3,4,5)-trisphosphate and phosphatidylinositol (4,5)-bisphosphate),[8] and proteins such as the βγ-subunits of heterotrimeric G proteins,[9] and protein kinase C.[10] Through these interactions, PH domains play a role in recruiting proteins to different membranes, thus targeting them to appropriate cellular compartments or enabling them to interact with other components of the signal transduction pathways.

C2
A C2 domain is a protein structural domain involved in targeting proteins to cell membranes. The typical version (PKC-C2) has a beta-sandwich composed of 8 β-strands that co-ordinates two or three calcium ions, which bind in a cavity formed by the first and final loops of the domain, on the membrane binding face. Many other C2 domain families don't have calcium binding activity.[2][3]

C2 domains are frequently found coupled to enzymatic domains; for example, the C2 domain in PTEN, brings the phosphatase domain into contact with the plasma membrane, where it can dephosphorylate its substrate, phosphatidylinositol (3,4,5)-trisphosphate (PIP3), without removing it from the membrane - which would be energetically very costly. PTEN consists of two domains, a protein tyrosine phosphatase domain and a C2 domain. This domain pair constitutes a superdomain, a heritable unit that is found in various proteins in fungi, plants and animals.[4] In addition, phosphatidylinositol 3-kinase (PI3-kinase), an enzyme that phosphorylates phosphoinositides on the 3-hydroxyl group of the inositol ring, also uses a C2 domain to bind to the membrane (e.g. 1e8w PDB entry).

we have cerevisiae ortholog
https://www.yeastgenome.org/locus/YDL073W#go
can we detect higher eukaryotic orthologs, this MUST be conserved @Antonialock  student

also we only have the scaffold for one pathway, can we find the others?

**Comment by ValWood** [comment]
Antonia, would you consider the scaffold to be a positive regulator?
https://github.com/geneontology/go-ontology/issues/14286

**Comment by ValWood** [comment]
perhaps the one above isn't really a scaffold?

see comment in
https://github.com/geneontology/go-ontology/issues/14286

we should find all of the SGD scaffolds and see if we have orthologs. There really *must * exist
and they must be conserved to vertebrates.

The MAPK  scaffold family http://pfam.xfam.org/family/PF11610
only has 3 species members!

**Comment by ValWood** [comment]
ore these?

**Comment by Antonialock** [comment]
nope sorry, I passed them on. I have asked her
