### ISSUE TITLE
cytokinetic ring components without human orthologs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1711]
I think these will likely be present in metazoa?

https://github.com/geneontology/go-ontology/issues/14337
SPBC1A4.05	blt1	ubiquitin domain-like protein Blt1
SPBC83.18c	fic1	C2 domain protein Fic1
SPAC4H3.14c	rng8	contractile ring myosin V regulator Rng8
SPBP8B7.02	rng9	contractile ring myosin V regulator Rng9

(for student)

**Comment by ValWood** [comment]
I gues she detected none of these?

**Comment by Antonialock** [comment]
I passed on all her predictions (except a couple that I didn't believe)

**Comment by Antonialock** [comment]
and I passed on all the suggestions of candidates to look for

**Comment by Antonialock** [comment]
it can go in the fodder for next one :-)

**Comment by ValWood** [comment]
yep will collect in one ticket. I don't actively look for them any more, but they do still turn up. I think there is still some mileage in this project...

**Comment by Antonialock** [comment]
yeah double bonus reusing the project, we end up with useful stuff and reusing means less prep work
