### ISSUE TITLE
mmi1 binds pre-mRNA not mRNA

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1717]
I think mmi1 binds pre-mRNA and not mRNA (it happens co-transcriptionally?) so the mRNA binding term should be changed to either RNA binding or pre-mRNA binding?
http://preview.pombase.org/reference/PMID:26670050

**Comment by ValWood** [comment]
I presume the assay here was only for mRNA binding though?
I think Cornelai would have done pre-mRNA otherwise (she use pre mRNA intronic  binding for some)

**Comment by ValWood** [comment]
lets leave for now, can move down later.
