### ISSUE TITLE
Review papers

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#172]
Very low priority

Assign topics to review papers
\(or use Mesh terms? .... these appear to be a bit weird for example the genome paper has "chemistry" and "protein structure" Eh?\)

Maybe use a\) mini ontology of review topics \(if this is overkill a  b\) list of slim terms +\)
if a\) this could be a student project.

I don't envisage we \(curators\) will get around to this in the next 2 years ......
maybe something for renewal...

\(hopefully we can make the reviews available through PomBase sooner\)

Original comment by: ValWood

**Comment by ValWood** [comment]
replaced by
https://github.com/pombase/curation/issues/811
