### ISSUE TITLE
GO IPI MF errors

### ISSUE THREAD

**Issue by mah11** [pombase/curation#1720]
The OWL GAF checks (the ones run by GO Jenkins) flagged up these two annotations because GOC doesn't allow IPI evidence for MF terms in the catalytic activity branch:

SPBC725.02/mpr1 GO:0009927 PMID:10749922 IPI with SPBC887.10/mcs4 [snip rest of line]
SPAC22E12.10c/etp1 GO:0009055 PMID:21536008 IPI with SPBC3B8.01c/arh1 [snip]

(These particular annotations don't look outrageous to me with IPI, but them's the rules that are enforced on the GAFs at GO, so I guess we should play nice.)

To get the GAF through, I changed the evidence to EXP and deleted the 'with' entries. I haven't changed anything in the sessions, but if you do - or tell me what you want and I'll do it -- corrected annotations will get into the next GAF via the usual route.

https://curation.pombase.org/pombe/curs/ed04f04bf6b4ebbc/
https://curation.pombase.org/pombe/curs/bbaa96d60dc05b65/

**Comment by Antonialock** [comment]
Cheers. I have updated the annotations to IMP/IDA, seemed to be the best fit
