### ISSUE TITLE
new disease association  FDXR

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1722]
| FDXR Mutations Cause Sensorial Neuropathies and Expand the Spectrum of Mitochondrial Fe-S-Synthesis Diseases.
-- | --
  | Am J Hum Genet. 2017 Sep 27;. [Epub ahead of print]
  | PMID: 28965846

**Comment by ValWood** [comment]
added

/controlled_curation="term=disease associated, mitochondrial disorders; db_xref=PMID:28965846; date=20171017"
/controlled_curation="term=disease associated, optic atrophy; db_xref=PMID:28965846; date=20171017"
/controlled_curation="term=disease associated, deafness; db_xref=PMID:28965846; date=20171017"


@Antonialock 
abtract says the sole human ferredoxin reductase implicated in the biosynthesis of iron-sulfur clusters (ISCs) and in heme formation......

**Comment by Antonialock** [comment]
note to self
http://www.sciencedirect.com/science/article/pii/S0167488915000361#f0025
Moreover, ferredoxin reductase and ferredoxins 1 and 2 utilize electrons from NADPH to reduce sulfane (S0), which occurs in cysteine, to sulfide (S2-), which occurs in ISCs
