### ISSUE TITLE
ire1 mRNA targets

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1723]
. Annotation of 39 previously-identified RIDD mRNA targets
497 (red dots in B and C) and WT/ire1Δ mRNA-Seq ratios (C) are from (Kimmig et al., 2012)

**Comment by ValWood** [comment]
Do we want to capture these 39 targets?

Also in this session is a reference to RIDD.
I recently requested this as it came up again
https://github.com/geneontology/go-ontology/issues/14380

**Comment by Antonialock** [comment]
I chose not to since it was a deletion phenotype. bip1 is the only one they characterized directly.

**Comment by ValWood** [comment]
OK.
