### ISSUE TITLE
s. cerevisiae ortholog of pex16

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1726]
http://preview.pombase.org/gene/SPBC646.15c

  | Farré JC, Carolino K, Stasyk OV, Stasyk OG, Hodzic Z, Agrawal G, Till A, Proietto M, Cregg J, Sibirny AA, Subramani S. | Related Articles
-- | -- | --
  | A new yeast peroxin, Pex36, a functional  homologue of mammalian PEX16, functions in the ER-to-peroxisome traffic  of peroxisomal membrane proteins.
  | J Mol Biol. 2017 Oct 13;. [Epub ahead of print]
  | PMID: 29037759 [PubMed - as supplied by publisher]

**Comment by ValWood** [comment]
YCL056C s.c  pex34?

**Comment by ValWood** [comment]
not sure about this.

. In this study, we isolated PEX36, a new gene in K. phaffii, which encodes a PMP. Pex36 is required for cell growth in conditions that require peroxisomes for the metabolism of certain carbon sources. This growth defect in cells lacking Pex36 can be rescued by the expression of human PEX16, S. cerevisiae Pex34, 

We do not have S. c pex34, but we have human pex16 ortholog. However  pex34 and pex16 are very different in length. I wonder if S. c pex34 is missing some ?

**Comment by ValWood** [comment]
@Antonialock  your student could look at this.
I didn't try to align or anything.

**Comment by ValWood** [comment]
Didi you pass this one to you student?
Did she find anything?

**Comment by Antonialock** [comment]
yes I passed on all the ones you sent through
