### ISSUE TITLE
lys9 oddity

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1730]
In Amigo I see the following annotation:

![annotation sisappeared](https://user-images.githubusercontent.com/7359272/31865273-4554f1ec-b764-11e7-9b79-f08d6c9846bc.jpg)

but  we didn't make this annotation from this paper

https://preview.pombase.org/reference/PMID:20537132

AND
The annotation is dated 20050622  (the paper was not published until 2010)

@mah11 @Antonialock  any ideas before I submit an AmiGO ticket?

**Comment by ValWood** [comment]
Ignore- we did make the annotation, I was thinking it was an MF.

The date is off though isn't it?

**Comment by mah11** [comment]
idea: typo by whoever made that annotation

evidence:

    FT                   /GO="aspect=P; term=lysine biosynthetic process;
    FT                   GOid=GO:0009085; evidence=IMP; db_xref=PMID:20537132;
    FT                   date=20050622"

in chromosome2.contig

**Comment by ValWood** [comment]
Ah I didn't think it would be that as I thought it would be in the session, not in art. weird...but I guess 2010 was on the cusp....

**Comment by mah11** [comment]
also c1, lys12

    FT                   /GO="aspect=P; term=lysine biosynthetic process;
    FT                   GOid=GO:0009085; evidence=IMP; db_xref=PMID:20537132;
    FT                   date=20040823"

**Comment by ValWood** [comment]
yes this is a *ver* bad practice I used to have of copying an existing annotation and editing but not changing the date.

I  don't do  this anymore. I find it a challenge because I never know the date, but I usually know the month, so I often default to  first of the current month :)

**Comment by mah11** [comment]
LOL.

If you click on the time in the toolbar at the top of your screen, it'll tell you the date:

![screen shot 2017-10-23 at 12 10 06 pm](https://user-images.githubusercontent.com/5196259/31886199-46cb3d1a-b7eb-11e7-87e4-27cd7f600ae8.png)

**Comment by ValWood** [comment]
Yeah my calendar works too. I have some sort of  aversion to knowing it.
