### ISSUE TITLE
retriage "Other"

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#174]
http://oliver0.sysbiol.cam.ac.uk/pombe/view/list/triage\_other\_publications?model=track

A lot of these will go into
Not physically mapped
Cell composition or WT features
mutagenicity or toxicity study
phylogeny

mindless friday afternoon job to work through

Original comment by: ValWood

**Comment by ValWood** [comment]
replaced by https://github.com/pombase/curation/issues/811
