### ISSUE TITLE
psm1-psm3 (cohesin related)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1742]
- [x] should have an IPI for this

used PMID:26687354

**Comment by ValWood** [comment]
and rad21 binding to both.

Not sure why I have overlooked these...

**Comment by ValWood** [comment]
Pds5, Wpl1 and Psc3 are conserved additional subunits that bind to Rad21 (Nasmyth & Haering, 2009; Peters & Nishiyama, 2012; Remeseiro & Losada, 2013).

**Comment by ValWood** [comment]
make a better job of this...
Recent evidence indicates that SMC3 acetylation would prevent DNA release from cohesin by preventing ATP hydrolysis by the SMCs (Murayama & Uhlmann, 2015; Beckouet et al, 2016; Elbatsh et al, 2016).

**Comment by ValWood** [comment]
odd, not got this either...

In fission yeast, the eso1 gene is essential for sister chromatid cohesion and cell viability but dispensable when the wpl1 gene is deleted (Tanaka et al, 2000; Feytout et al, 2011). Likewise, the acetyl-mimicking allele psm3K105NK106N allows cell survival in the absence of Eso1. odd...

However, the thermosensitive eso1-H17 mutant is deficient for Psm3K106 acetylation even at the permissive tempera- ture and the psm3K105RK106R non-acetylatable mutant is viable, indi- cating that Eso1 might counteract Wpl1 through another mechanism besides Psm3 acetylation (Feytout et al, 2011; Kagami et al, 2011).

**Comment by ValWood** [comment]
psm1 has protein binding to rad21 but this does not show on rad21 page
will be fixed by
https://github.com/pombase/pombase-chado/issues/433

**Comment by ValWood** [comment]
Given that Psm3 acetylation declines during anaphase towards G1 phase (Feytout et al, 2011;)

**Comment by ValWood** [comment]
- [ ] Feytout et al, 2011)

passing this one back to you for the double mutants in this one....

**Comment by Antonialock** [comment]
PMID:21300781

**Comment by ValWood** [comment]
This looks quick...

**Comment by Antonialock** [comment]
all done
