### ISSUE TITLE
How should non coding RNAs be named

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1743]
I need to confer with other GNC members.
Still 3 letters number?

we have a name assigned "prt"  @Antonialock  has added as a synonym

**Comment by Antonialock** [comment]
Many are named "conventionally" e.g. sme2, prlX (where X is a number)

then there's the geneX-antisense ones

**Comment by ValWood** [comment]
We also need a record  of way to know which ranges of sys IDs we have used or given out.

**Comment by Antonialock** [comment]
currently 2000-8000 to Jurg right?

**Comment by ValWood** [comment]
17,576 3 letter codes avaiable

**Comment by ValWood** [comment]
decision, continue with 3 -letter until anyone complains that they cannot find anything suitable
