### ISSUE TITLE
duplicated gene names

### ISSUE THREAD

**Issue by mah11** [pombase/curation#1747]
The last few rounds of logs have contained this in chado_checks:

    no_duplicate_pombe_gene_names - CHECK FAILURE:  expected 0 but got 2
      2 fkh2
      2 dal2

because these were added in svn revision 4398 (chr1):

    FT                   /product="histone peptidyl-prolyl cis-trans isomerase Fkh2
    FT                   (predicted)"
    FT                   /systematic_id="SPAC27F1.06c"
    FT                   /primary_name="fkh2"

    FT                   /fasta_file="fasta/chromosome1.contig.seq.01740.out"
    FT                   /product="transcription factor, zf-fungal binuclear
    FT                   cluster type Dal2 (predicted)"
    FT                   /systematic_id="SPAC1F7.11c"
    FT                   /primary_name="dal2"

I am inclined to simply remove the newer of the duplicate pairs, especially for fkh2, since that's a forkhead gene. I also don't see where the new usage of either name comes from.

**Comment by ValWood** [comment]
I agree...I'm not sure where they came from...

**Comment by ValWood** [comment]
fixed
