### ISSUE TITLE
annotate all flocculins to GO:0098631 'cell-cell adhesion mediator activity

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1748]
https://github.com/geneontology/go-ontology/issues/14533

not GO:0050839
(do any real binding with IPI protein binding)

**Comment by mah11** [comment]
Ugh, what a horrible term. I wish they hadn't added it. What could it possibly mean other than "protein binding involved in cell-cell adhesion"? And I thought GO wanted to move that sort of thing to GO-CAMs ... aren't they in the middle of scrapping a lot of other MF-involved-in-BP terms? ... and for us GO:0005515 + ext part_of(GO:0007155) does the job ...

**Comment by ValWood** [comment]
I think there pragmatic reasons for making some of the  " protein binding function grouping terms"
for things like "adaptors", "chaperones" and "adhesion molecules" and the like
 otherwise they get completely buried in the "protein binding" cohort.

So, I think they will be helpful, even though its probably not ontologically pure ;)

**Comment by ValWood** [comment]
done via another ticket
