### ISSUE TITLE
Review annotation for GPCR 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1750]
https://github.com/geneontology/go-annotation/issues/1691

We need to migrate annotations to these terms:

GO:0030819 positive regulation of cAMP biosynthetic process
GO:0043950 positive regulation of cAMP-mediated signaling
GO:0007194 negative regulation of adenylate cyclase activity
GO:0030818 negative regulation of cAMP biosynthetic process
(I thought they were gone)

The first one
git1

GO:0010619	adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway
IMP	Kao RS et al. (2006)	

GO:0045762	positive regulation of adenylate cyclase activity	
part of adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway IPI  with cyr1	Kao RS et al. (2006)

That looks like it should be
MF protein binding git1/cyr1
part of GO:0045762
?

Or is it  upstream of the pathway, I remember discussing this one?

**Comment by ValWood** [comment]
remove you name for GO assignees when done...

**Comment by ValWood** [comment]
Is git1 some sort of membrane anchor for adenylate cyclase?

**Comment by mah11** [comment]
> gpa2 GO:0045762	regulates activity of cyr1 IDA	PMID:15925945

I did this one - Gpa2 activates Cyr1 directly in vitro. Changed to MF GO:0010856.

**Comment by Antonialock** [comment]
positive regulation of adenylate cyclase activity 
is a descendant of 
positive regulation of cAMP biosynthetic process @mah11 should I remove it?

**Comment by mah11** [comment]
I would wait and see what GO does with that link in the ontology. Sometimes a gene product will look like it regulates adenylate cyclase activity, but you won't be sure it meets the criteria for an MF regulator term, so I think they'll probably have to keep the "regulation of adenylate cyclase activity" BP terms somewhere.

**Comment by Antonialock** [comment]
ok cheers

**Comment by Antonialock** [comment]
for git1 they do not demonstrate direct binding, just co-IP. Also, its deletion doesn't alter git2 abundance or localization. I removed it, it will still have adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway, which can be revised once we know what it does..

**Comment by Antonialock** [comment]
fixed the others

**Comment by ValWood** [comment]
sounds good
