### ISSUE TITLE
remove  FP orfeome data to nucleus

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1758]
If a nucleus  localization  is not shown in small scale localization I generally remove from

to
GO_ORFeome_localizations2.txt

add to
GO_ORFeome_localizations2_deleted.txt

check
- [x] dip1
- [x] tea4
- [x] cdc3

**Comment by ValWood** [comment]
@Antonialock @mah11 
Keep a look out for these and remove if they do not agree with new data

**Comment by ValWood** [comment]
- [x] oca8 | SPCC16A11.10c | cytochrome b5 (predicted)
-- | -- | --

**Comment by Antonialock** [comment]
Why?

**Comment by ValWood** [comment]
Because they are incorrect ?

**Comment by ValWood** [comment]
I have been removing them for years because there are  loads (probably about 10%) false positives 
becase of the slight overexpression.

if small scale detailed experiment dos not support, no point to keep displaying them (won't help  users, but they can ignore, will hinder machine learning etc)
I usually check the image and some are dodgy anyway.

**Comment by ValWood** [comment]
We have a record of the removed ones
https://curation.pombase.org/dumps/latest_build/pombe-embl/external_data/external-go-data/GO_ORFeome_localizations2_deleted.txt
