### ISSUE TITLE
no nucleus annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1759]
![no nucleus](https://user-images.githubusercontent.com/7359272/33089525-c93f4c28-cee8-11e7-86b0-beaa18740ddc.jpg)

**Comment by ValWood** [comment]
![nuclear](https://user-images.githubusercontent.com/7359272/33089562-dfc58b06-cee8-11e7-8eb9-b54166234121.jpg)

**Comment by ValWood** [comment]
- [ ] SPBC30B4.08	eri1	double-strand siRNA ribonuclease Eri1
- [ ] SPBC336.05c	hen1	small RNA 2'-O-methyltransferase Hen1 (predicted)
- [ ] SPBC21D10.12	hob1	BAR adaptor protein Hob1
- [ ] SPBC12C2.09c	izh2	Haemolysin-III family plasma membrane receptor implicated in zinc ion homeostasis Izh2 (predicted)
- [ ] SPBC23G7.09	mat1-Mc	mating-type m-specific polypeptide Mc
- [ ] SPMTR.02	mat2-Pi	silenced P-specific polypeptide Pi
- [ ] SPAC26H5.05	mga2	IPT/TIG ankyrin repeat containing transcription regulator of fatty acid biosynthesis (predicted)
- [ ] SPAC2F7.11	nrd1	RNA-binding protein Nrd1
- [ ] SPCC1020.10	oca2	serine/threonine protein kinase Oca2
- [ ] SPBC2A9.09	plp2	phosducin family protein Plp2 (predicted)
- [ ] SPBC1198.11c	reb1	RNA polymerase I transcription termination factor/ RNA polymerase II transcription factor Reb1
- [ ] SPAC227.15	reg1	protein phosphatase regulatory subunit Reg1 (predicted)
- [ ] SPCC645.08c	snd1	RNA-binding protein, involved in chromatin silencing by small RNA, Snd1
- [ ] SPBC365.07c	tmf1	TATA element modulatory factor homolog Tmf1 (predicted)
- [ ] SPCC18.03		shuttle craft like transcriptional repressor/ubiquitin-protein ligase E3 (predicted)

**Comment by ValWood** [comment]
- [ ] SPCC338.08	ctp1	CtIP-related endonuclease
- [ ] SPBC17D11.08	dca7	WD repeat protein, DDB1 and CUL4-associated factor Dca7 (predicted)
- [ ] SPCC417.07c	mto1	MT organizer Mto1
- [ ] SPCC338.16	pof3	F-box protein Pof3
- [ ] SPBC1198.11c	reb1	RNA polymerase I transcription termination factor/ RNA polymerase II transcription factor Reb1
- [ ] SPAC12G12.16c		Fen1 family nuclease, XP-G family (predicted)

**Comment by ValWood** [comment]
- [ ] nrd1
rDNA heterochromatin  should be able to add IDA
then IC  nucleolus from this?

**Comment by ValWood** [comment]
- [ ]  nrd1 @Antonialock  is this definitely regulating txn?

**Comment by ValWood** [comment]
@Antonialock can you look at this one nxt, should be quick...

**Comment by Antonialock** [comment]
eri1 I don't think we should annotate t nucleus, see comment in #1806

**Comment by Antonialock** [comment]
hen1 ISS to thaliana

**Comment by Antonialock** [comment]
nrd1 is not annotated to regulating trx1 if that is what you mean?

**Comment by ValWood** [comment]
Nrd1 is annotated to regulation of transcription (abbrev. txn), how does it do this?
I couldn't figure it out...

**Comment by ValWood** [comment]
I see, it isn't nuclear anyway, so you can ignore this one....

**Comment by ValWood** [comment]
Maybe hen1 isn't nuclear in pombe...until yesterday I thought all of our RNAi was in the nucleus.... maybe leave this one too?

**Comment by Antonialock** [comment]
Yeah might not be.

It had a physical interaction annotation to fft3, but it doesn't look convincing (the biogrid annotation)

![screen shot 2017-12-09 at 13 17 50](https://user-images.githubusercontent.com/12727506/33795973-752a59a8-dce3-11e7-8c1f-d9bb0024328a.png)

e.g.
![screen shot 2017-12-09 at 13 17 18](https://user-images.githubusercontent.com/12727506/33795974-7714e738-dce3-11e7-9545-96b83f68ae69.png)

**Comment by Antonialock** [comment]
ok removed hen1 
/GO="aspect=C; term=nucleus; GOid=GO:0005634; evidence=ISS; db_xref=GO_REF:0000024; with=AGI_LocusCode:AT4G20910; date=20171209"

**Comment by Antonialock** [comment]
mat1-mc added ic from GO:0005634

**Comment by ValWood** [comment]
ok only snd1 left, not sure about that so  closing
