### ISSUE TITLE
cdt1 FP for mitochondria?  also swi3

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1769]
Is there any evidence that cdt1 is also mitochondrial?
If not will remove as FP
https://www.pombase.org/gene/SPBC428.18

**Comment by mah11** [comment]
I don't know of any; false positive seems likely.

**Comment by ValWood** [comment]
I'll ask PR

**Comment by ValWood** [comment]
actually based on this I'm going to move to "deleted" file
http://www.riken.jp/SPD/Img_page/20_iP/20F09_Loc.html
