### ISSUE TITLE
Epistasis annotation

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#177]
Would be nice to be able to capture these.I have captured in the past with "same pathway" qualifier with IGI,  but these need removing (replacing with IMP)
as they are not IGI

...maybe it isn't need but we just need a GO term specific enough if there are 2 branches of a pathway. Think about this some more....

Original comment by: ValWood

**Comment by ValWood** [comment]
probably even 'future grant'

**Comment by ValWood** [comment]
might come  back on the radar in this grant, but unlikely...

**Comment by ValWood** [comment]
future doc...
