### ISSUE TITLE
tapered

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1771]
SPBC17F3.02 | PAK-related GC kinase Nak1

tip1 | SPAC3C7.12 | CLIP170 family protein Tip1
-- | -- | --

are annotated to tapered, but I think these are different from the bottle/skittle that tapered morphed into.

the tapered phenotype is exclusively mitochondrial.
I'll try to find some pics, we might need to refine....

**Comment by ValWood** [comment]
I know I had a folder somewhere with images of these general morphology phenotypes. I thought it was in dropbox, but I have been through and I can't locate it (I also thought I put images in the tickets when the terms were added?). I know we have them somewhere.....

**Comment by mah11** [comment]
Dropbox/pombase/Documentation_and_help/Example\ phenotype\ images/

**Comment by ValWood** [comment]
Of course, documentation.

I can see what the difference is between pear and skittle, but I don't know how  to describe it!

**Comment by mah11** [comment]
The FYPO defs use 

tapered (synonym: skittle): [T]he cell tapers at one end to a diameter smaller than the other. The cell diameter at the narrow end is smaller than that of a wild-type cell.

pear: One end is rounded, while the other resembles an end of a normal rod-shaped cell. The normally shaped end has the same diameter as a wild-type cell.

Anything wrong with either of those?

**Comment by ValWood** [comment]
I think they are fine.

 The problem is that in use, the phenotypes are quite a continuum, so they do not always fit the shape precisely.

FOr the orb one, I think this is better classified as a pear, the authors  Leonhard K and Nurse P
call it a pear

![orb3-167 pear](https://user-images.githubusercontent.com/7359272/33267337-028ccc8a-d371-11e7-84ee-0c15e0659564.jpg)

tip1 is trickier....

![tip1](https://user-images.githubusercontent.com/7359272/33267424-58232df6-d371-11e7-8b20-abc4842c9fd9.jpg)

it does look tapered but it isn't the same as a skittle/bottle. I think we might be able to exclude it from tapered because the narrower end would not be narrower than wild type....this is a phenotype derived from a normal shaped cell that is swollen. @JackyVH  do you agree? 

It's tapered but it does not fit the "skittle-type" tapered def (I would like to exclude it because it is clearly  a different phenotype, this may need  a different type of tapered phenotype (tapered and swollen?)

**Comment by ValWood** [comment]
orb3-167 is an "avocado" pear,  the pear we have in the def, we also see more like this:

![pear](https://user-images.githubusercontent.com/7359272/33267706-6e759f8e-d372-11e7-971b-a6c2d1541ed6.jpg)

T  thing the difference might be due to wether a septum is formed or not?

**Comment by Antonialock** [comment]
- make sure orb3 annotated to pear

**Comment by Antonialock** [comment]
fixed nak1

**Comment by ValWood** [comment]
Didn't we decide to create  
"tapered elongated" as a child of tapered for "tip1" or did we overturn that and decide we were happy as it is.

What is still to do here?

**Comment by ValWood** [comment]
nak1 is orb3?

**Comment by ValWood** [comment]
ignore, you closed...
