### ISSUE TITLE
homeostasis

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#178]
Antonia pointed out:

when I was curating cadmium ion genes I noticed that you have annotated to cellular cadmium ion homeostasis
do you think this term is appropriate?
To me, homeostasis implies keeping a certain amount +/- a bit i.e. the substance/condition is needed within range A to B \(say calcium or temperature or whatever\).
As far as I know cadmium isn't needed at all by the cells but is 'just' toxic, and therefore I'd expect the cells to try and get rid of any cadmium, i.e. not maintaining a steady level of cadmium in the cells.

So at some point in the future, need to check homeostasis annotation

Original comment by: ValWood

**Comment by Antonialock** [comment]
all gone
