### ISSUE TITLE
iron sulfur cluster carrier vs transferase

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1788]
From GO ticket. I have annotated to transferase when I should have annotated to carrier. E.g. http://dmm.biologists.org/content/5/2/155
ssu1 transferase but isu is carrier.
https://github.com/geneontology/go-ontology/issues/14336

**Comment by Antonialock** [comment]
obvs other carriers too

**Comment by Antonialock** [comment]
not sure what needs doing here that hasn't been fixed?

**Comment by ValWood** [comment]
I think this was just to ensure that the carriers  were correctly annotated as carriers?
