### ISSUE TITLE
protein binding, bridging

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1793]
https://www.pombase.org/gene/SPAC1002.06c
should be 3 individuals?

**Comment by ValWood** [comment]
I can't fix this
https://github.com/pombase/website/issues/639

**Comment by ValWood** [comment]
annotated as
/GO="aspect=F; term=protein binding, bridging; qualifier=contributes_to; GOid=GO:0030674; evidence=IPI; db_xref=PMID:16615890; with=SPBC1778.02,SPBC12D12.01; date=20171209"

and deleted from canto.
added to bqt1 and2.

because of the comment, I also added "contributes_to"

![bqt1 2](https://user-images.githubusercontent.com/7359272/33795481-01932776-dcda-11e7-80a7-1d58ccf35f06.jpg)

**Comment by ValWood** [comment]
check tomorrow and close

**Comment by ValWood** [comment]
hmmph, i managed to lose the annotation completely...

**Comment by ValWood** [comment]
I'm not even sure why...

/GO="aspect=F; term=protein binding, bridging; qualifier=contributes_to; GOid=GO:0030674; evidence=IPI; db_xref=PMID:16615890; with=SPBC1778.02,SPBC12D12.01; date=20171209"

comma separated with field allowed?

@mah11 ?

**Comment by mah11** [comment]
it'll come back when one of us add the prefixes (in logs; I was planning to do 'em tomorrow anyway, so leave if for me if you want)

**Comment by ValWood** [comment]
Oh Yep got it, I was just  looking at the logs. I can do this one, I have art open...

**Comment by ValWood** [comment]
will check tomorrow

**Comment by ValWood** [comment]
The annotation is there but I need to add 
has_substrate to make the binding partners appear in the summary

**Comment by ValWood** [comment]
well actually,  bqt2 is showing but bqt1 isn't.....

**Comment by ValWood** [comment]
added 
annotation_extension=has_direct_input(PomBase:SPBC1778.02,PomBase:SPBC12D12.01);
to both

I can't see a problem with bqt1, so I am guessing @mah11  fixed it today.
