### ISSUE TITLE
snu no longer have process annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1794]
probably enough info from phenotypes to make these

snu2 | SPSNRNA.02 | small nuclear RNA U2
snu3 | SPSNRNA.03 | small nucleolar RNA U3
snu32 | SPSNRNA.07 | small nucleolar RNA U3B
snu5 | SPSNRNA.05 | small nuclear RNA U5
snu6 | SPSNRNA.06 | small nuclear RNA U6

(also need nucleolus)

**Comment by mah11** [comment]
I looked at a few old-ish GAFs (last two years or so) and I can't find any MF or BP annotations for these, so the "no longer" in the summary is probably an error. Only snu2 and snu3 have phenotypes other than population growth, and those are all about transcription and processing of the snRNA itself.

I'll see what I can do by ISS ...

(these all already have nucleolus IDA annotations)

**Comment by ValWood** [comment]
Oh right  of course they are snRNA, I don't think I ever GO annotated these.....
I was only supposed to be looking at proteins...

**Comment by mah11** [comment]
s'ok, SGD have some experimental data for some of theirs, so I might as well plunk in some ISOs now that I've looked

**Comment by mah11** [comment]
done
