### ISSUE TITLE
pho1 plasma membrane

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1800]
has IDA  mebrane, but  is "cell surface" and no TM domain. What was assayed?

**Comment by Antonialock** [comment]
purified membranes

**Comment by Antonialock** [comment]
it is not annotated to plasma membrane, it is annotated to "membrane", I guess it is exocytosis

**Comment by Antonialock** [comment]
I guess it is golgi:
"high-& immunoreactive proteins (> 94 kDal) corresponding to the fully glycosylated form of APh (lane d) and the core-glycosylated 72 Dal form. Immunoblotting of proteins EMMl extracted from purified membranes (Fig. 4B, lanes a-d) shows that in cells transformed with pSp4C/2 the 72-kDa.l form of the enzyme is membrane-bound (lane b) as it is in wild-type cells (lane d),

**Comment by Antonialock** [comment]
I guess it could also be exocytosis vesicles

**Comment by Antonialock** [comment]
I'm happy leaving it at "membrane"

**Comment by ValWood** [comment]
ok
