### ISSUE TITLE
nuclear?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1806]
- [x] ase1 | SPAPB1A10.09 | antiparallel microtubule cross-linking factor Ase1
IC from GO:1990023

- [x] csi2 | SPAC4D7.07c | mitotic chromosome segregation protein Csi2
IC from GO:0044732

- [x] sid2 | SPAC24B11.11c | NDR kinase Sid2
IC from GO:0044732

**Comment by ValWood** [comment]
prp4	SPCC777.14	serine/threonine protein kinase Prp4

**Comment by ValWood** [comment]
ase1 | SPAPB1A10.09 | antiparallel microtubule cross-linking factor Ase1
cek1 | SPCC1450.11c | serine/threonine protein kinase Cek1
dhc1 | SPAC1093.06c | minus-end directed microtubule motor, dynein heavy chain Dhc1
dma1 | SPAC17G8.10c | mitotic spindle checkpoint ubiquitin ligase Dma1
rpt5 | SPAC3A11.12c | 19S proteasome regulatory subunit Rpt5
sid2 | SPAC24B11.11c | NDR kinase Sid2

**Comment by ValWood** [comment]
eri1 | SPBC30B4.08 | double-strand siRNA ribonuclease Eri1
hen1 | SPBC336.05c | small RNA 2'-O-methyltransferase Hen1 (predicted)
snd1 | SPCC645.08c | RNA-binding protein, involved in chromatin silencing by small RNA, Snd1
tri1 | SPBC29A10.09c | triman, ribonuclease involved in priRNA formation Tri1

**Comment by ValWood** [comment]
eri1  if definitely

GO:0000467 | exonucleolytic trimming to generate mature 3'-end of 5.8S rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)

can be IC as this occurs in nucleus?

**Comment by ValWood** [comment]
then this one can be closed, I'll ignore  snd1 for now

**Comment by Antonialock** [comment]
I don't think we should make a nucleus annotation, it looks like it could be different from higher (human, mouse) eukaryotes, but it is inline with worm

2 assays in PMID:16797182 show strict cytoplasmic localization
![screen shot 2017-12-08 at 12 45 21](https://user-images.githubusercontent.com/12727506/33768726-1f73998a-dc1f-11e7-83b7-4ee9a50c70c3.png)

also:
"However, functional Eri1-GFP fusion proteins seem to be strictly cytoplasmic in C. elegans, and Flag-tagged Eri1 localized only to the cytoplasm in S. pombe1,4,10. Therefore, Eri1-mediated 5.8S rRNA  maturation may occur after ribosome assembly and export to the cytoplasm, at least in these species." -nature paper PMID:18438418

**Comment by Antonialock** [comment]
I don't think we should make a nucleus annotation, it looks like it could be different from higher (human, mouse) eukaryotes, but it is inline with worm

2 assays in PMID:16797182 show strict cytoplasmic localization
![screen shot 2017-12-08 at 12 45 21](https://user-images.githubusercontent.com/12727506/33768726-1f73998a-dc1f-11e7-83b7-4ee9a50c70c3.png)

also:
"However, functional Eri1-GFP fusion proteins seem to be strictly cytoplasmic in C. elegans, and Flag-tagged Eri1 localized only to the cytoplasm in S. pombe1,4,10. Therefore, Eri1-mediated 5.8S rRNA  maturation may occur after ribosome assembly and export to the cytoplasm, at least in these species." -nature paper PMID:18438418

**Comment by ValWood** [comment]
OK makes sense, 
in that case is

GO:0000467 | exonucleolytic trimming to generate mature 3'-end of 5.8S rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)

correct. This is part of the processing that occurs in the nucleus (or so I thought)?

**Comment by ValWood** [comment]
I'm basing htis on the fact that the tricistronic transcript does not exist by the time that the ribosome is exported from the nucleus, so it must be processed in there?

**Comment by ValWood** [comment]
these terms are horrible......

**Comment by ValWood** [comment]
can close this if

 exonucleolytic trimming to generate mature 3'-end of 5.8S rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)

is definitely the correct term

**Comment by ValWood** [comment]
this is largely a duplicate and covered by
https://github.com/pombase/curation/issues/1759
