### ISSUE TITLE
check vacuole? isp6

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1812]
4 | (protein catabolic process in the vacuole (GO:0007039) AND vacuole (GO:0005773)) | ...

  | 7 | protein catabolic process in the vacuole (GO:0007039)

**Comment by ValWood** [comment]
gid1 | SPCC1259.12c | GID complex subunit, Ran GTPase binding protein Gid1 (predicted)
-- | -- | --
gid4 | SPAC3H1.14 | GID complex subunit Gid4 (predicted)
gid5 | SPAC26H5.04 | GID complex armadillo repeat subunit Gid5 (predicted)

**Comment by ValWood** [comment]
it isn't a vacuolar complex, but only 
3/7 GID complex subunits are annotated to  "protein catabolic process in the vacuole"
maybe the others should be?

**Comment by ValWood** [comment]
should isp6

https://www.pombase.org/gene/SPAC4A8.04

be -ve reg of  "protein catabolic process in the vacuole"
not just "proteolysis"?
@Antonialock

**Comment by ValWood** [comment]
remove 
"protein catabolic process in the vacuole" from gid1 subunits, it's proteasomal?

**Comment by ValWood** [comment]
delete ISS's from
SPCC1259.12c

(vid24) gid4   & vid28 (SPAC26H5.04) still has annotation at SGD, not sure if that is correct?
probably indirect, anyway I'm going to remove...

**Comment by ValWood** [comment]
Gid complex is done @Antonialock  could you respond re isp6

**Comment by Antonialock** [comment]
isp6 isn't annotated to 'proteolysis'
