### ISSUE TITLE
 GO:0070187 - shelterin complex  missing members

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1823]
according to def of shelterin complex in fission yeast it consists of 
Pot1, Tpz1, Rap1, Rif1, Rif2 and Taz1 

currently annotated: ccq1 , pot1 , poz1 , tpz1 
missing: rap1, rif1, rif2, taz1
It will get rap1 next DB update from PMID:29149597.

Find refs for: rif1, rif2, taz1

**Comment by Antonialock** [comment]
<img width="422" alt="screen shot 2017-12-29 at 17 58 55" src="https://user-images.githubusercontent.com/12727506/34449044-0a46d960-ecc2-11e7-894a-6b139be2f27c.png">


<img width="816" alt="screen shot 2017-12-29 at 17 58 40" src="https://user-images.githubusercontent.com/12727506/34449045-0f4f3538-ecc2-11e7-8092-8a9820960c65.png">

**Comment by Antonialock** [comment]
<img width="316" alt="screen shot 2017-12-29 at 18 01 10" src="https://user-images.githubusercontent.com/12727506/34449096-88f1fc22-ecc2-11e7-8bd9-1d6a17604419.png">

**Comment by Antonialock** [comment]
fission yeast doesn't seem to have rif2 (YLR453C)?

**Comment by Antonialock** [comment]
"Not all proteins at chromosome ends are part of shelterin. Several criteria distinguish the shelterin components from the non-shelterin proteins observed at telomeres (Table 1). Shelterin is abundant at chromosome ends but does not accumulate elsewhere; it is present at telomeres throughout the cell cycle, and its known function is limited to telomeres. Non-shelterin proteins at chromosome ends fail to meet two or three of these criteria, yet can play important roles at telomeres"

**Comment by ValWood** [comment]
@mah11  might know

**Comment by ValWood** [comment]
What is the action? is anything missing?

**Comment by mah11** [comment]
> @mah11 might know

or she might not.

But I did remember a place to look: PMID:26063574 is exquisitely well written, and its introduction says pombe shelterin has pot1, poz1, rap1, taz1 and tpz1. It shouldn't be too hard to track down refs to add taz1.

The paper cited for ccq1 hasn't been curated in Canto yet; I suppose we could just delete the GO:0070187 annotation in Artemis in the meantime.

**Comment by mah11** [comment]
Or, if other researchers do count ccq1 as part of shelterin, leave it as is. That's not something I know.

**Comment by ValWood** [comment]
OK that's a good starting point!

**Comment by Antonialock** [comment]
so taz1 needs it

**Comment by Antonialock** [comment]
IDA added
