### ISSUE TITLE
linking to trembl entry rather than UniProt

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1825]
For SPAC1F7.01c
we are linking to 
http://www.uniprot.org/uniprot/S6BMF4

which is a Trembl entry. We should be linking to the uniprot entries....
I have not checked if this is in UniProt, but I know we were "all uniprot" at one point.

Before we query  with UniProt, I wanted to check wether it was related to us switching the file source from the one Paul Kersey created to the protein to GO one...(may have reverted us to Trembl entries, although to be honest I though that file was already all Uniprot).

**Comment by mah11** [comment]
> I wanted to check w[h]ether it was related to us switching the file source

No, the files were identical except for some entries missing from the PomBase2UniProt.tsv file that Paul and Mark generated, and the missing ones were all related to "demerged" UniProtKB entries. Background in https://github.com/pombase/pombase-chado/issues/634

I don't know why SPAC1F7.01c has two entries, nor why our links are using the TrEMBL one. (I've also never understood why they don't merge or obsolete these TrEMBL entries for species as thoroughly studied as S.c. & S.p., but that's a whole other tangent ...) 

I do now see that there are 27 pombe systematic IDs that have two UniProtKB accessions each, and one that has four (SPAC22E12.16c). These have all been inherited from past versions of the file, and were not among the differences between the gp2protein file and the EBI-spawned PomBase2UniProt.tsv file (i.e. the duplications have been in both files for a long time and we've only just noticed).

Anyway, if no one remembers why there are any TrEMBL IDs in there, we can simply delete them. Want me to go ahead?

**Comment by ValWood** [comment]
Yep there should only be one
SP-> UniProt in the file
cheers,

**Comment by mah11** [comment]
OK, done
