### ISSUE TITLE
Fig 1A

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1830]
![fig1a](https://user-images.githubusercontent.com/7359272/34906666-c0f8b05e-f869-11e7-9082-e40950a5bdc4.jpg)

Figure 1 shows the proportions of the predicted proteomes of the two yeasts and human that have biological roles known from experimentation or inferred by homology, over [x] years. 

Antonia is revising this figure to  show the historical aspect more, and the flatlining at 80%, and to include human.

**Comment by ValWood** [comment]
@Antonialock  if you have more than one source for a year   do you think it will be best to  include both data points and 
use an "error bar" ?

**Comment by ValWood** [comment]
Show as a % rather than number?

**Comment by Antonialock** [comment]
yeah % could be good. @ValWood can I have your numbers?

**Comment by ValWood** [comment]
yep:
https://www.pombase.org/status/gene-characterisation-statistics-history
https://www.pombase.org/status/gene-characterisation

**Comment by Antonialock** [comment]
for ref this is all the data I dug out and that I based the graph on (didn't use all of it, tried to avoid the "guesstimates"


94-98: YPD table 

<img width="428" alt="screen shot 2017-12-29 at 15 26 45 1" src="https://user-images.githubusercontent.com/12727506/37868365-d899442a-2f9c-11e8-89ee-b5ba5d019997.png">


1996a: 3000 (very much a guesstimate)
1996b: 2200 genes of unknown function
2000: 1644 genes of unknown Cellular Role
2002: 1519 unknown
2009: 1134 uncharacterized excl computational predictions, 718 genes uncharacterized by BP including computational predictions
2013: 1214 genes annotated to "biological process unknown"
2013 (November): 1153 genes annotated to BP root



Refs:
94-98:  Hodges PMID:9847145
1996a: PMID:8628394 Oliver
1996b: 2013 presentation, Nazish Nehal, slide 16 https://www.slideshare.net/Nazish_Nehal/yeast-genome-project
2000: YPD proteome cellular role, downloaded on Dec 7 2000, cited in Wu et al PMID:12089522
2002: MIPS inventory date stamped feb15 2002. sum of genes labelled as similarity to unknown protein and no similarity.
http://mips.helmholtz-muenchen.de/proj/yeast/tables/inventy.html
2009: PMID:19577472 Christie et al. "Despite the vast body of literature for this organism, 554 out of 5796 protein-coding genes (almost 10%) remain uncharacterized for all three GO vocabularies. Approximately 500 additional genes only have annotations to very general locations, such as ‘cytoplasm’, defined by HTP localization experiments"

<img width="452" alt="screen shot 2017-12-23 at 21 33 52" src="https://user-images.githubusercontent.com/12727506/37868369-ecd4e4ee-2f9c-11e8-9711-71103932061e.png">


2013: PMID:23749449 Gibney et al. Supplementary downloadable data, file: GO-slim_analysis_full
2013 (November): 2013 presentation, Nazish Nehal, slide 24 https://www.slideshare.net/Nazish_Nehal/yeast-genome-project

**Comment by Antonialock** [comment]
also for ref spreadsheets and graphs live in dropbox unknowns_paper_2017

**Comment by Antonialock** [comment]
@ValWood don't forget to add latest numbers

**Comment by Antonialock** [comment]
![historical characterization](https://user-images.githubusercontent.com/12727506/37868462-92fca2b6-2f9e-11e8-9205-bdb8a08733c6.png)

putting this in the right ticket..

**Comment by ValWood** [comment]
Yes.  

I think we should say right there in the legend where each datapoint comes from. People will thank us for this later, because nobody will need to do this again......

So, 
1994 (PMID:xxxxx)
obviously if it's the same source we can do
1994-1998 (PMID:xxxxx), 1999 (PMID:yyyyy)

Can you add a "string"  to this ticket  as above describing each  data-point source. 

I will draft figure legends for  @mah to trash/refine next week.

**Comment by Antonialock** [comment]
1994-1998 (PMID:9847145), 2000 (PMID:12089522), 2002 (http://mips.helmholtz-muenchen.de/proj/yeast/tables/inventy.html), 2009 (PMID:19577472), 2013 (PMID:23749449)

**Comment by ValWood** [comment]
so here you just want pombe up to date totals? 4373/5070
https://www.pombase.org/status/gene-characterisation

**Comment by ValWood** [comment]
I'll do those from the slim.

**Comment by ValWood** [comment]
1011/5915 cerevisiea are unknown (83% known).  vs pombe 86% known

I will do a final slim next week when to GO database is updated to our current totals. T his will change the numbers a fraction, (so that they match my figure 3 exactly)

but the percentages won't change.

**Comment by Antonialock** [comment]
![unknowns historical graph](https://user-images.githubusercontent.com/12727506/38322249-cfede5ae-3831-11e8-8aaf-d58ec68501ab.jpg)

**Comment by Antonialock** [comment]
![unknowns historical graph](https://user-images.githubusercontent.com/12727506/38322284-e07dc164-3831-11e8-81ce-2e22076578d1.jpg)

**Comment by Antonialock** [comment]
done?

**Comment by Antonialock** [comment]
super duper! slight tweak to make the text clearer

![unknowns historical graph](https://user-images.githubusercontent.com/12727506/38333473-a2f2bc86-3850-11e8-8a41-6de9238c9255.jpg)

**Comment by ValWood** [comment]
what did you do?

**Comment by Antonialock** [comment]
just decreased the width a bit

**Comment by ValWood** [comment]
hmm, that makes the distance between  cerevisiae and  pombe smaller though ;) ...although I guess that isn't the primary aim ;)

**Comment by ValWood** [comment]
How much better is it than my old figure ! whenever I showed that nobody had a clue what it was!

**Comment by ValWood** [comment]
4 boring lines!

**Comment by ValWood** [comment]
But flipping heck, I hope the speed of characterisation increases because on the current trajectory I'll be around ~66  before we get to 100% !

**Comment by ValWood** [comment]
Great idea of yours to go further back in time anyway!

**Comment by ValWood** [comment]
Could you send me this figure as an  e-mail atttachment? or put it here Goolge folder
