### ISSUE TITLE
figure Figure [2A] ?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1832]
This is updated data for pombe

![intersection](https://user-images.githubusercontent.com/7359272/34907638-a8b145f0-f879-11e7-84ec-8cebf564e21b.jpg)

@mah could you find time to do S. c equivalent next week?
I used Intermine, and I thought I had saved the queries, but I didn't I saved the results, and I can't rerun them, or remember how I did it!

The only thing to remember is that you need to use the  protein only ex-dubious set to perform the intersections on (I think there is a template for this, although I remember I could not find it myself I had to mail SGD). This set should have  5915 members (I don't think this has changed?).

**Comment by mah11** [comment]
> [@mah11] could you find time to do S. c equivalent next week?

I can look at this from Mon. 22nd onwars. not earlier

**Comment by ValWood** [comment]
Oh yes of course. I might get to it sooner if I finish fig 3 and the  other stuff... will see...keep the ticket anyway and I'll claim it if I do it.

**Comment by mah11** [comment]
I haven't tried to add any colors yet. If I use the yeastmine template defaults, which exclude "computational" annotations, the numbers haven't changed much:

![sc_go_counts_small](https://user-images.githubusercontent.com/5196259/35289791-44fb3176-0060-11e8-861e-8b71016ac785.png)


With the computational annotations included, it looks like this:

![sc_go_counts_incl_comp_small](https://user-images.githubusercontent.com/5196259/35289809-4e9dbc8a-0060-11e8-8dc3-e25492111907.png)

**Comment by ValWood** [comment]
Hmm, OK, we do need to include IEA, as I included IEA for pombe.
I thought I had (I probably did not realise that it wasn't the default)

It may seem odd to eaders that the numbers of things with process  annotations is different from the histogram. This is because for the histogram I filter any annotation which have high level uninformative terms (mostly IEA) ...I think it should be OK though since this is explained in the text.

**Comment by ValWood** [comment]
data from pombase 28/april 2018
~3535~ 3580
~763~  749
~198~ 179
~37~ 39
~0~ 2
~420~  412
~23~ 20
 
none ~90~ 89

@mah11  could you make the figure with pombe and cerevisiae data?
I don't think it needs colours, I like your plain one.....

**Comment by mah11** [comment]
I uploaded a new file to the google drive directory
it's GO_aspect_figure_2A_20180430.png

**Comment by ValWood** [comment]
Great thanks!

**Comment by ValWood** [comment]
ooh can close one...
