### ISSUE TITLE
short term goal for IEA reduction, removal

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1833]
It seems that for most processes that are well studied in pombe, we don't have many IEA's. Let's try to eradicate  over the next few months!
(A nice task for when Canto down if I can resist the urge to do them sooner)

A lot are zero  or nearly 0 already!

- [x] cytokinesis 0
- [x] ascospore formation  0
- [x] telomere organization 0
- [x] cell adhesion 0
- [x] GO:0016074 - snoRNA metabolic process 0
- [x] autophagy 0 
- [ ] (need to open  annotation tracker ticket for KW-0072
- [x]  GO:0000226 - microtubule cytoskeleton organization 1 (gtb1)
- [ ] nucleocytoplasmic transport 1 rpn15, ~nup45~ (leaving this for now, rpn15 probably correct)
- [x] GO:0006399 - tRNA metabolic process 0
- [x]  detoxification 1  ~trr1~
- [ ] DNA repair ~21~ 17
- [ ] DNA replication 
- [ ] DNA recombination 
- [x]  mitochondrial gene expression 0
- [x]  GO:0030036 - actin cytoskeleton organization ~rid1~ ,~bud6~, ~adf1~, ~cap1~ ,shk1
- [ ] GO:1901990 - regulation of mitotic cell cycle phase transition 2 (mad1, byr4)

- [ ] mitotic chromosome segregation	2 (mad1, hcn1)
- [ ] GO:0140056 - organelle localization by membrane tethering 6 pof6, sec8,10,15, vps33,45
- [ ] GO:0042254 - ribosome biogenesis 9
~nob1~, ~utp6~, ~tif6~ , ~wdr74~,  nup146, nup82, ~nip7~, rpl8, rpp0, ~bud23~, ~erb1~

- [ ] mRNA processing 17
- [ ] vitamin metabolic process 14 ~abz1, abz2~, fol1, SPAC6F6.11c, SPCC18.10, sno1, snz1, pdx3, rib2, urg1, thi4, SPBP8B7.17c, SPBP8B7.18c, plr1

- [x] GO:0000747 - conjugation with cellular fusion 0

**Comment by Antonialock** [comment]
can't access the paper right now (wiley is down) will look asap.

**Comment by Antonialock** [comment]
nice idea by the way!

**Comment by ValWood** [comment]
I thought we were pretty close to eradicating IEA for processes, but not that close.....

**Comment by ValWood** [comment]
558       P    (actually it is still quite a lot but I hope to get rid of most this year)

**Comment by ValWood** [comment]
Actually  processes  that are not so well studied  IEA isn't so bad (metabolism, transmembrane transport, will probably only eradicate for well-studied processes in the short term.

**Comment by Antonialock** [comment]
dni1 IEA should be removed...I'll stick it on the tracker.

**Comment by Antonialock** [comment]
requested missing paretnage

**Comment by ValWood** [comment]
exactly 500 IEA for	P, removed a few more today

**Comment by ValWood** [comment]
Moved to "future" doc
