### ISSUE TITLE
cleavage furrow

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1846]
I'm not so sure these 3 gene products should be annotated to 
"cleavage furrow"
based ont eh description of cleavage furrow as a  cell surface plasma membrane invagination

https://www.pombase.org/term/GO:0032154
(these are all cell cortex ?)

**Comment by ValWood** [comment]
I can't figure out if the problem is describing the cleavage furrow as "cell surface", maybe it is?

**Comment by ValWood** [comment]
I suspect these should really be much broader annotation "cell division site" maybe?

**Comment by Antonialock** [comment]
maybe, you approved these community sessions.

**Comment by Antonialock** [comment]
maybe, you reviewed these community sessions already

**Comment by ValWood** [comment]
Yep I think its fine after some recent GO changes....they are no longer under "cell surace" which was my issue.
