### ISSUE TITLE
pombe wikepedia page

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1850]
The whole page really irritates me,  it has so many errors, but this in particularly:

During the Genome Project in S. pombe researchers found that 50 genes coded for proteins and/or mutations that linked to human diseases, with nearly half of them (23) being cancer-related.[31]

@Antonialock  could you replace by
PomBase reports over 69% of  protein coding genes have human orthologs and over 500 of these are human disease associated [ PomBase paper?] [ query url ? I think it is possible to do this now] [your book chapter when published?]

your book chapter when published -> you can wait until then to do this...

We could also replace every legacy protein  gene number with a Pombase link to teh query result...
(how do we do this?)

**Comment by Antonialock** [comment]
I don't think we can link to a query result @kimrutherford ? 

I have done a minor update linking to the ortholog table and the PBO term for disease associated, and citing papers.

I agree the page is horrendous

**Comment by ValWood** [comment]
It's the worst page I have seen for a while!

**Comment by ValWood** [comment]
Actually we should not put links to PomBase queries. People might think we wrote it....

**Comment by Antonialock** [comment]
ok, otherwise it looks like it might be possible from https://github.com/pombase/website/issues/540

**Comment by ValWood** [comment]
I'm sure someone will edit it at some point. When it looks less silly we can add  PomBase links to support statements.

**Comment by kimrutherford** [comment]
Since it's bad form to edit our own page, perhaps it's something we could ask the community to help with?  Probably no one in the community knows it's bad because they're unlikely to look at it?  A little bit of editing by a bunch of people would have it fixed in no time.

**Comment by ValWood** [comment]
That's this issue, it isn't out page (we created a pombase one)

The pombe (organism) age is a mish-mash edited by everyone, but possibly mainly by an enthusiastic student! It did not used to be so bad. Anyway I'm sure it will annoy somebody in the community enough to tidy it at some point....(Charlie probably...I'll hint next time I chat with him)

**Comment by kimrutherford** [comment]
Ah, I misread.  I thought it was about the PomBase page.

You're probably right that it was edited by someone with enthusiasm but not so much knowledge.  I bet most of the knowledgeable people have never looked at the page because they wouldn't need to.
