### ISSUE TITLE
lam genes, regulation of TORC signaling

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1852]
-Should these be annotated to regulation of TORC signaling (structural?)
-IEA to +ve, manual to -ve

**Comment by ValWood** [comment]
As part of this, I spotted
lam1 ego1
lam2 ego3
lam3 ego2


what is the relationaship between 
GO:0034448    EGO complexego complex
GO:0035859    Seh1-associated complex (synonym GATOR)
 and the gators (is one synonymous?)

**Comment by ValWood** [comment]
new orthologs need to be recorded here:
https://curation.pombase.org/pombase-trac/wiki/OrthologTableUpdates
(especially cerevisiae ones, because currently I need to manually update the downloadable table periodically)


until
https://github.com/pombase/pombase-chado/issues/202

**Comment by ValWood** [comment]
@Antonialock can close?
