### ISSUE TITLE
Extension configuration fix

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#1861]
Hi.

I think this:  GO:0031399-GO:0043666-GO:0045859  in GO_BP_A_E_config
needs to be GO:0031399-GO:0043666&GO:0045859

The parser can't cope with "term-term-term".

I haven't made the change because I wanted to check that I had the sense right.

**Comment by kimrutherford** [comment]
> I haven't made the change because I wanted to check that I had the sense right.

I have changed it now because of pombase/canto#1373 - the ontology update now throws an error if the "-term" bit doesn't include the relation.

It's now: "GO:0031399-is_a(GO:0043666)&is_a(GO:0045859)"
which is unfortunately quite unclear.

That example is currently assumed by Canto to mean:

    This config line applies to terms where TERM is_a GO:0031399 and:
          TERM is not a GO:0043666
      AND TERM is not a GO:0045859

I'll add that to the documentation.

**Comment by ValWood** [comment]
@kimrutherford can we close?

**Comment by ValWood** [comment]
closing @kimrutherford  reopen if required
