### ISSUE TITLE
question protoporphyrinogen IX

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1866]
@Antonialock 
@mah11 

do fungi have
protoporphyrinogen IX?

or is this only for organisms which have hemoglobin?

**Comment by ValWood** [comment]
(we are picking up quite a few mappings)

**Comment by mah11** [comment]
haven't the foggiest ...

**Comment by ValWood** [comment]
seems ok it's before heme
https://en.wikipedia.org/wiki/Protoporphyrinogen_IX
