### ISSUE TITLE
some annotations that were there 4 years ago that might be valid

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1870]
Various reasons they could have disappeared,   I nearly finished checking and most things that have disappeared were bad.

These might be OK:

nucleobase-containing small molecule metabolic process
consider 
 - [x] gda1 https://github.com/pombase/curation/issues/1876
 - [ ] ynd1

**Comment by ValWood** [comment]
carbohydrate
- [ ] exg1	fungal-type cell wall beta-glucan metabolic process
- [ ] eng2	oligosaccharide catabolic process
- [ ] alpha amylases

**Comment by ValWood** [comment]
transmembrane transport
- [ ] SPAC4G8.08
- [ ] SPCC1682.11c
- [ ] SPAC9G1.04

**Comment by ValWood** [comment]
cytoskeleton
- [ ]  slm1	SPAC637.13c	cytoskeletal signaling protein Slm1 (predicted)
- [ ] vps1	SPAC767.01c	dynamin family protein Vps1
- [ ] kinases regulation of actin cyto? pom1 plo1
- [ ] syp1	SPBC4C3.06	F-BAR domain protein Syp1 (predicted)
- [ ] SPAC926.03	myosin II regulatory light chain Rlc1

**Comment by ValWood** [comment]
DNA repair?
- [ ] ASTRA complex telomere maintenance and DNA repair?
- [ ] Smc5-Smc6 complex
- [ ] Ino80 complex
- [ ] hus5 (sumo related)

**Comment by ValWood** [comment]
conjugation  @Antonialock 
- [ ] git1
- [ ] cgs2
- [ ] (gpa1 and pka1 are annotated)

**Comment by Antonialock** [comment]
ohh, yes, all of these should be negative regulation of conjugation with cellular fusion I guess

(pka1 phosphorylates rst2 resulting in rst2 exclusion from the nucleus. rst2 when in the nucleus acts as a TF fror ste11 which drives mating

**Comment by Antonialock** [comment]
all genes annotated to "adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway" now also have the annotation negative regulation of induction of conjugation with cellular fusion.

**Comment by ValWood** [comment]
protein glycosylation
gpi14 | SPBC13E7.05 | glycosylphosphatidylinositol-mannosyltransferase I complex subunit pig-M

**Comment by ValWood** [comment]
- [ ] eng2 some carbohydrate term

**Comment by ValWood** [comment]
- [ ]  pep3 vesicle docking

**Comment by ValWood** [comment]
meiotic nuclear division

- [ ]  hcn1
- [ ] ask1  (any DASH?)
- [ ] nuf2, spc24, spc25 (any NMS?)

**Comment by ValWood** [comment]
meiotic nuclear division
spo15 | SPAC1F3.06c | mitotic and mieotic spindle pole body protein Spo15
sad1 | SPBC12D12.01 | spindle pole body SUN domain protein Sad1
dms1 | SPCC1739.04c | meiotic spindle pole body protein Dms1
cdc2


check
cam1
cdc13
csi1
cut2
cut7
meu14
mug27
spo7

**Comment by ValWood** [comment]
cell cycle transition

- [ ]  nuc2
- [ ]  cut4
- [ ] rad26??? 
- [ ] par1 ?
- [ ] par2 ?
- [ ] ppa3? 
- [ ] cut1/2
- [ ] slp1
- [ ] bir1

**Comment by ValWood** [comment]
cytokinesis
- [ ]  myo1
- [ ] mcp1?
- [ ] fim1

**Comment by ValWood** [comment]
carbohydrate derivative 
- [ ]  SPCC191.05c | nucleoside 2-deoxyribosyltransferase (predicted) ?
- [ ]  SPBP18G5.02 | CDP-diacylglycerol-glycerol-3-phosphate3-phosphatidyltransferase Pgs1
- [ ]  mde1 | SPAC20H4.05c | 5'-methylthioribulose-1-phosphate dehydratase, adducin Mde

**Comment by ValWood** [comment]
@Antonialock

**Comment by mah11** [comment]
> @mah11 could you check the DNA repair complexes ...

Which genes?

**Comment by ValWood** [comment]
It's this set from above:

DNA repair?
- [ ] ASTRA complex telomere maintenance and DNA repair?
- [ ] Smc5-Smc6 complex
- [ ] Ino80 complex
- [ ] hus5 (sumo related)

**Comment by mah11** [comment]
Do you mean genes currently annotated to the GO terms for the named complexes?

**Comment by ValWood** [comment]
Yes,  these genes *used* to have  DNA repair annotations. Maybe got removed, maybe aren't relevant. However, I think (at least some)  these particular complexes are  defined as being  involved in repair, and if this is the case they could be done via IC from complex

**Comment by mah11** [comment]
progress so far:

- Smc5-Smc6 complex: did IC for nse5, nse6, smc5; the others already had DNA repair annotations
- ASTRA complex: The GO:0070209 definition calls it "part of the chromatin remodeling machinery" and doesn't say anything about DNA repair, so it doesn't look safe to infer a repair annotation from the GO CC annotation.
- Ino80 complex: Similar to ASTRA -  the GO definition (GO:0031011) has "chromatin remodeling activity and 3' to 5' DNA helicase activity", which doesn't narrow it down to necessarily DNA repair. That said, ino80 and nht1 have ISO annotations from the cerevisiae orthologs (the latter only from phenotypes at SGD).
- hus5: It looks like there's data in PMID:21444718. For now I've just done an IGI with rad60 in artemis as a stopgap.

Should I look into individual Ino80 complex subunits in more detail (post-hols)?

**Comment by ValWood** [comment]
No leave it at that ...just wanted to make sure we were missing nothing obvious....

**Comment by mah11** [comment]
OK. I like that answer ;)

**Comment by ValWood** [comment]
The only outstanding part of this ticket is to try to annotate these to 
meiotic nuclear division (or regulation of) in some way

- [ ] sad1 | SPBC12D12.01 | spindle pole body SUN domain protein Sad1
- [ ] cdc2
- [ ] cdc13
- [ ] cam1
- [ ] spo15
- [ ] cut2  -ve reg meiotic chromosome separation
- [ ] cut7   IC from GO:0008574 +GO:0072687

**Comment by Antonialock** [comment]
cdc2 done, doing 25688135 for sad1

**Comment by Antonialock** [comment]
I don't think spo15 should have meiotic nuclear division....it's a sporulation protein, meiosis I and II are normal. It's involved in spindle pole body remodelling. This maps to sexual reproduction / meiotic cell cycle process

**Comment by Antonialock** [comment]
same with cam1

**Comment by ValWood** [comment]
OK makes sense. The SPB  remodelling occurs quite far upstream of  events of division (prophase?)

**Comment by Antonialock** [comment]
no it's when it remodels to form a crescent during sporulation

**Comment by ValWood** [comment]
Ah OK yes even further upstream...
