### ISSUE TITLE
annotations don’t make sense based on product description

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1871]
https://www.pombase.org/gene/SPBC18H10.12c

Some ribosomal-like proteins are not actually ribosomal, they are only involved in assembly. I don't know  if tis is one of those but I annotated the known ones as "ribosomal protein SX-like" which is how they are usually referred....

**Comment by ValWood** [comment]
these are the other 2, 
ribosomal L24-like protein involved in ribosome biogenesis Rlp24 
ribosomal protein L7-like Rlp7

1. standardize
2. find out if the above is one of these (I presume s,  as it has no translation annotation)

**Comment by ValWood** [comment]
This is only minor, but if it isn't a ribosomal protein add -like to the product

**Comment by Antonialock** [comment]
changed product description to

"Rpl701, generally known as subunit L7 of the large ribosome, was reproducibly detected in the RNase MRP complex prepared multiple times. Furthermore, the reverse pull-down analysis using a tagged Rpl701 as bait allowed isolation of RNase MRP from S. pombe cells, whereas tagged Rpl702 or Rpl703, the paralogs of Rpl701, failed to recover the enzyme complex (Figure S4). Thus, we concluded that Rpl701 is a novel component of RNase MRP in S. pombe. "


also changed these product descriptions to:
RNase P and RNase MRP subunit Rpp40 (included MRP subunit)
RNase P and RNase MRP subunit Pop4 (included product name)

**Comment by ValWood** [comment]
OK, I changed to
RNase MRP subunit, ribosomal protein L7-like 
(Its useful because its good to point out it looks just like a ribosomal protein (these are generally more similar to the ribosomal proteins than to the  orthologs in other species, so they can be very confusing).

 Annotating as "ribosome-like alerts us to check that they don't  pick up mappings to translation, ribosome etc.
They will.....

**Comment by ValWood** [comment]
@Antonialock did you change any GO annotation here?
Ribosome biogenesis has dropped by 2 and I can't think why

**Comment by ValWood** [comment]
and tRNA metabolic process dropped by one, possibly related?

perhaps not, but it seems odd as these 2 processes are pretty static...

**Comment by Antonialock** [comment]
no I think I just touched the product descriptions?

**Comment by ValWood** [comment]
ok it must be something else. tks
