### ISSUE TITLE
annotations don't agree with abstract pet127

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1872]
abstract says not involved in RNA catabolism, but involved in processing?

**Comment by Antonialock** [comment]
no, the abstract says "The Pet127p-stimulated RNA degradation activity is **independent** of Par1p/Pah1p in fission yeast mitochondria"

from initial characterization paper:
Our findings support the hypothesis that Pet127p
stimulates RNA decay or destabilizes mitochondrial
transcripts in mitochondria.
