### ISSUE TITLE
egt1/2 amino acid, or derivative?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1874]
should these annotations be amino acid derivative?

**Comment by mah11** [comment]
The amino acid metabolism annotations come from paths in GO. Both genes are annotated to ergothioneine biosynthetic process (GO:0052699), and egt1 is also annotated to GO:0052707. Both have is_a paths to GO:0006520 amino acid metabolic process (GO:0052699 is is_a GO:0000097 sulfur amino acid biosynthetic process, based on ChEBI's classification of ergothioneine, and GO:0052707 is is_a GO:0006548 histidine catabolic process).

All of the BP terms do also have paths to GO:0006575 (the derivative term, 'cellular modified amino acid metabolic process'), so the genes appear in a search for either term.

So not really a curation issue ...
