### ISSUE TITLE
dsc complex related

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1875]
curs/8f019ff3f6b166f6/ro

@Antonialock  you added 

dsc1 | GO:0034067 | protein localization to Golgi apparatus
here with no target gene

@mah11  "regulation  of protein glycosylation" looks odd as a process. Did you think these  should be phenotype only (I notice you added  the phenotypes)

**Comment by mah11** [comment]
> "regulation of protein glycosylation" looks odd as a process.

You queried this before, in #677. I'm not wedded to keeping the GO:0060049 annotations, but they do seem to be how Peter interprets the stuff in figure 3. Let me know if you want me to forward the emails.

**Comment by ValWood** [comment]
I think we need to look at some of this SREBP signalling stuff , its confusing, but not urgently...

**Comment by ValWood** [comment]
removed 
| GO:0034067 | protein localization to Golgi apparatus
but 
SREBP pathway needs a review one day. ...in time...
