### ISSUE TITLE
standardize symporter product names

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1880]
plasma membrane malate/succinate: proton symporter

@Antonialock question, are ght family symporters?

only this one is annotated as one:
http://pombase-dev.bioinformatics.nz/gene/SPCC548.07c

**Comment by ValWood** [comment]
@Antonialock question, are ght family symporters?

**Comment by Antonialock** [comment]
What do you mean by "are ght family symporters"? I believe they are all hexose transporters, expression dependent on conditions (high glucose, low glucose, while in the spore stage) and different affinities for fructose, glucose etc

**Comment by ValWood** [comment]
I think they must all be symporters...
http://pombase-dev.bioinformatics.nz/term/GO:0005358

**Comment by ValWood** [comment]
- [ ] SPCC548.07c	ght1	hexose transmembrane transporter Ght1
- [ ] SPBC4B4.08	ght2	plasma membrane hexose transmembrane transporter Ght2
- [ ] SPAC1F8.01	ght3	plasma membrane hexose transmembrane transporter Ght3
- [ ] SPBC1683.08	ght4	plasma membrane hexose transmembrane transporter Ght4
- [ ] SPCC1235.14	ght5	plasma membrane hexose transmembrane transporter Ght5
- [ ] SPCC1235.13	ght6	plasma membrane hexose transmembrane transporter Ght6
- [ ] SPBC1348.14c	ght7	plasma membrane hexose transmembrane transporter Ght7
- [ ] SPCC548.06c	ght8	hexose transmembrane transporter Ght8 (predicted)

**Comment by ValWood** [comment]
I went with this could you glance over and see if it seems ok, then close. Gradually annotations can move down to the symporter MF terms.

**Comment by Antonialock** [comment]
included high affinity in ght5 descr.
