### ISSUE TITLE
CST complex

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1882]
https://www.pombase.org/term/GO:1990879
+pot1?

or is it not in pombe?

**Comment by mah11** [comment]
Looks like not. The GO definition doesn't list Pot1, and Figure 1 of PMID:20697207 (review) shows Pot1 in a different complex in pombe. The review and the introduction to PMID:28180297 both also say that CST has Cdc13p/CTC1, Stn1p/STN1, and Ten1p/TEN1, or orthologs thereof, but they also say that pombe doesn't have a Cdc13p/CTC1 ortholog. I have no idea whether the authors would question your CDC13/pot1 orthology call.

From the review figure I gather that those authors are saying that pombe has both shelterin and CST, and they put Pot1 with shelterin (which is also how we have it annotated).

Usual "I'm no expert" caveats apply.

**Comment by ValWood** [comment]
OK soundes good.

I'm fairly confident about the orthology call. We used to think that pot1 wasn't conserved
http://pfam.xfam.org/family/PF02765#tabview=tab6
https://www.ebi.ac.uk/interpro/entry/IPR011564/taxonomy

but it's a 1:1 and  it's doing the same thing ...
