### ISSUE TITLE
telomere maintenance check 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1884]
taz1
- | GO:0030466 | chromatin silencing at silent mating-type cassette | TAS |   | Park MJ et al. (2002) | 36
?

~- | GO:0006348 | chromatin silencing at telomere | IMP |   | Nimmo ER et al. (1998) | 23
  | IMP |   | Fujita I et al. (2012)
(is this really 'silencing?'~   yup at subtelomere

**Comment by ValWood** [comment]
While Taz1, Rap1, Poz1, Rap1, and Rif1 are required to limit telomere extension by telomerase, Tpz1 and Ccq1 are required for recruitment and activation of telomerase

?

**Comment by ValWood** [comment]
phosphorylation targets

Interaction between the telomerase regulatory subunit Est1 and Ccq1 is required to recruit telomerase to telomeres, and this interaction is promoted by Rad3ATR/Tel1ATM-dependent phos- phorylation of Ccq1 Thr9317.

Moser, B. A., Chang, Y. T., Kosti, J. & Nakamura, T. M. Tel1ATM and Rad3ATR kinases promote Ccq1-Est1 interaction to maintain telomeres in fission yeast. Nat. Struct. Mol. Biol. 18, 1408–1413 (2011).

**Comment by ValWood** [comment]
The Nakamura papers are in progress.

ccq1 annotation here looks contradictory (positive and negative)
![contradictory](https://user-images.githubusercontent.com/7359272/36580215-3bffb634-185f-11e8-8572-19310a19d057.jpg)

**Comment by ValWood** [comment]
Actions
- [ ]  taz1 and rif1 are not annotated to telomere maintenance via telomerase
- [ ] check ccq1
- [ ]  is the "mating type silencing" correct for taz1 (tas)?
- [ ] PMID: 26354422  check covered by CC

**Comment by mah11** [comment]
> ccq1 annotation here looks contradictory (positive and negative)

It's OK. PMID:29216371 says (even right in the abstract) that Ccq1 can do positive or negative regulation, depending on what else it's complexed with.

**Comment by ValWood** [comment]
Hmm, OK, it seems as though it would be directly involved in these two processes rather than regulating (as a scaffold).
But since that is what they say....we'll  ignore for now...
