### ISSUE TITLE
Slim term "protein complex assembly" is now obsolete

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#1885]
The load failed last night because one of the GO slim terms we have in the configuration file is now obsolete.

    "protein complex assembly" - GO:0006461

is now an alt_id of:

    [Term]
    id: GO:0065003
    name: protein-containing complex assembly
    namespace: biological_process
    alt_id: GO:0006461
    def: "The aggregation, arrangement and bonding together of a set of  ..." [GOC:jl]
    subset: goslim_chembl
    subset: goslim_generic
    subset: goslim_metagenomics
    subset: goslim_pir
    subset: goslim_pombe
    ...

I'm going to change GO:0006461 to GO:0065003 in the slim configuration.  Let me know if that's wrong.

**Comment by ValWood** [comment]
bummer, thanks, I forgot about the knock on effect of this change!

**Comment by ValWood** [comment]
@Antonialock  need to fix this in any anlysis slims. I'll update the wiki

**Comment by ValWood** [comment]
I fixed anything I can think of, and looks OK here:
http://pombase-dev.bioinformatics.nz/browse-curation/fission-yeast-go-slim-terms
