### ISSUE TITLE
MICOS complex

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1887]
only have 4 subnuits annotated but 9 in
https://www.sciencedirect.com/science/article/pii/S0167488915003626

**Comment by Antonialock** [comment]
not all of these should be micos core see
https://www.ncbi.nlm.nih.gov/pubmed/26477565

**Comment by Antonialock** [comment]
DNAJC11 MIB complex? conserved unknown....seems to have something to do with crisate, I only had a quick look https://www.ncbi.nlm.nih.gov/pubmed/22252321

**Comment by ValWood** [comment]
Nice one.
I'll do this now then it can be in my final slim and update for fig 3. 
I plan to *finish* it this weekend....

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/15245

![micos and mib](https://user-images.githubusercontent.com/7359272/36589905-bf48c196-1884-11e8-948d-29760146d39c.jpg)

**Comment by Antonialock** [comment]
>  I plan to finish it this weekend....

yes..

**Comment by ValWood** [comment]
We have Mic 10,19,26 and 60 annotated
- [ ] 12 appears to be absent (which seems odd) look for this
- [ ] Our 19  is  ortholog of 19 AND 25 (a duplication) add 25 to orthologs
- [ ]  Figure out what our 26 is
- [ ] Figure out where our 23/27 is (possibly called 26, see above)

**Comment by ValWood** [comment]
- [ ] Got it. Our 26 is  HUMAN 23/27 (APOO and APOO-LIKE)  S. cerevisiae 26/27  (duplications in both branches)
Add all of these names as synonyms for searching

**Comment by Antonialock** [comment]
also SPCC417.16 electron transport chain?

**Comment by ValWood** [comment]
nope we don't know what this is. It's not an NASH dehydrogenase (this is a massive 43/44 subunit complex in human). It's always been a problem annotation.

**Comment by ValWood** [comment]
see, https://sourceforge.net/p/geneontology/annotation-issues/1180/
and many others...

**Comment by ValWood** [comment]
I think it might be iron sulfur cluster assembly, or lipid metabolism,  or some complex assembly thing

**Comment by ValWood** [comment]
should have
mic10
mic60
mic19
mic26
mic23/27
sam50
mtx1/3
mtx2
dnaJc11
