### ISSUE TITLE
Add IDs to LTRs PMID:     12952871

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#190]
In this paper, the LTRs  were assigned IDs , but I have never got around to adding them because they are in a word doc.

I guess we need to covert this to gff (or EMBL),  check how the coordinates compare with the current LTR number/coordinates and maybe drop the current ones and import the new file into artemis (as there is no other information associated with the LTRs except coordinates)

they could have the ID added, and the Db_xref for this paper 
I guess I will do this one day if I get an overwhelming urge to write a perl script, but if anyone else wants a go, go ahead....)
(not urgent)

Original comment by: ValWood

**Comment by ValWood** [comment]
Out LTRs have IDs, if anyone aver provides a mapping of the IDs in this paper we will add them, but for us this will never be a priority task
