### ISSUE TITLE
Q conjugation with cellular fusion, annotation drop

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1901]
has recently dropped from 108 -> 96 (last update)

didi you remove lots, or is it a GO ontology change?

**Comment by Antonialock** [comment]
I did not remove lots in the last week or so

**Comment by ValWood** [comment]
these are the ones that dissapeared....

cfr1 | SPAC6G9.12 | exomer complex BRCT domain subunit Cfr1
-- | -- | --
fab1 | SPBC3E7.01 | 1-phosphatidylinositol-3-phosphate 5-kinase Fab1
fkh2 | SPBC16G5.15c | forkhead transcription factor Fkh2
gnr1 | SPCC1020.09 | heterotrimeric G protein beta (WD repeat) subunit Gnr1
lsc1 | SPBC530.13 | Lsk1 associated cyclin
lsg1 | SPCC4B3.08 | Lsk1 complex gamma subunit Lsg1
lsk1 | SPAC2F3.15 | P-TEFb-associated cyclin-dependent protein kinase Lsk1
mfm1 | SPAPB8E5.05 | M-factor precursor Mfm1
mfm2 | SPAC513.03 | M-factor precursor Mfm2
mfm3 | SPBPJ4664.03 | M-factor precursor Mfm3
spk1 | SPAC31G5.09c | MAP kinase Spk1
spt8 | SPBC14C8.17c | SAGA complex subunit Spt8
ste11 | SPBC32C12.02 | transcription factor Ste11

**Comment by ValWood** [comment]
that's weird
these are (at least some) 
GO:0000750    JSON
pheromone-dependent signal transduction involved in conjugation with cellular fusion

and that parentage appears to be intact...

**Comment by ValWood** [comment]
Other slim terms don't appear to be affected?

**Comment by ValWood** [comment]
Actually, I am pretty sure this is an ontology issue...it's just not yet visible in QuickGO...
(I am seeing other ontology problems  reported in the logs that haven't yet filtered through)
I can check on it tomorrow

**Comment by ValWood** [comment]
I'm not sure about this...
mfm1 is in the "conjugation with cellular fusion list" for PomBAse
http://pombase-dev.bioinformatics.nz/term/GO:0031137

but not slimming  to GO:0031137 according to the slim groups on the gene page

@kimrutherford  any idea what might cause this?

**Comment by ValWood** [comment]
@kimrutherford  could you see if you can see why this is?
I think it's us but I can't work out why

see mfm1 is annotated to 
http://pombase-dev.bioinformatics.nz/term/GO:0000747
but not slimmed to this process?
http://pombase-dev.bioinformatics.nz/gene/SPAPB8E5.05

**Comment by ValWood** [comment]
transferred to https://github.com/pombase/website/issues/699

**Comment by ValWood** [comment]
can reopen based on  pombase/website#699

**Comment by ValWood** [comment]
Check tomorrow, will hopefully fix itself....

**Comment by ValWood** [comment]
now back to 108
http://pombase-dev.bioinformatics.nz/query

mfm1 slims to "conjugation with cellular fusion"
http://pombase-dev.bioinformatics.nz/gene/SPAPB8E5.05

**Comment by Antonialock** [comment]
yay

**Comment by ValWood** [comment]
it dropped back to 101!
http://pombase-dev.bioinformatics.nz/query

**Comment by ValWood** [comment]
105
GO:0000750 - pheromone-dependent signal transduction involved in conjugation with cellular fusion
still missing conjugation paremt

**Comment by ValWood** [comment]
It has the parent.
Most are annotated to conjugation, except gnr1, I don't know why. Maybe because its a regulation of a regulation?

**Comment by ValWood** [comment]
back to 102....so we definitely lost some. I'll look into this if they don't reappear in a day  or 2...

**Comment by ValWood** [comment]
it's still 102, this term and cytoskeleton organization go up and down on a daily basis... no idea why but cosing anyway...

**Comment by ValWood** [comment]
was >100 what went?
96 | conjugation with cellular fusion (GO:0000747)

I haven't done any annotation in this branch, so I think this 'flip-floppong' is GO related.

Did  either  of you do any annotations here? @Antonialock @mah11 ?
if not I'll  ask GO. Its almost as if the same change keeps getting over-ridden and fixed. It shouldn't change this much (nothing else is, other then up, and for known reasons).

**Comment by mah11** [comment]
PMID:29453312 had a couple of new regulation annotations, but both for genes that already annotations in the conjugation branch (ras1 & gap1). That's all I've done in this area lately.

**Comment by ValWood** [comment]
yeah it shouldn't have dropped thats for sure. I'll see if I can track what is missing in a minute...

**Comment by ValWood** [comment]
these are the ones which disappeared, I see a pattern!

SPBC3E7.01	fab1	1-phosphatidylinositol-3-phosphate 5-kinase Fab1
SPBC16G5.15c	fkh2	forkhead transcription factor Fkh2
SPCC1020.09	gnr1	heterotrimeric G protein beta (WD repeat) subunit Gnr1
SPBC530.13	lsc1	Lsk1 associated cyclin
SPCC4B3.08	lsg1	Lsk1 complex gamma subunit Lsg1
SPAC2F3.15	lsk1	P-TEFb-associated cyclin-dependent protein kinase Lsk1
SPAPB8E5.05	mfm1	M-factor precursor Mfm1
SPAC513.03	mfm2	M-factor precursor Mfm2
SPBPJ4664.03	mfm3	M-factor precursor Mfm3
SPBC32F12.09	rum1	CDK inhibitor Rum1
SPAC31G5.09c	spk1	MAP kinase Spk1
SPBC14C8.17c	spt8	SAGA complex subunit Spt8
SPBC32C12.02	ste11	transcription factor Ste11

**Comment by ValWood** [comment]
duplicate see https://github.com/pombase/pombase-chado/issues/678
for more....
