### ISSUE TITLE
GO-0070647_gap_filling.gaf.txt evidence corrections

### ISSUE THREAD

**Issue by mah11** [pombase/curation#1903]
This file has GO_REF:0000036 for all its entries, but that reference can only be used when there's more than one "inferred from" GO ID to put in the with/from column.

If the "from" terms (GO:0019783, GO:0019787, etc.) all have sequence similarity evidence (ISS, ISO, ISM, etc), the IC'd annotations can use GO_REF:0000111.

**Comment by ValWood** [comment]
OK, I copied that form another IC annotation and I thought it looked unfamiliar...

**Comment by ValWood** [comment]
fixed
