### ISSUE TITLE
pom1 mid1 double mutant phenotype check

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1911]
and cells lacking both Mid1p and Pom1p were reported as inviable [11].

11. Ba ̈ hler, J., Steever, A.B., Wheatley, S., Wang, Y., Pringle, J.R., Gould, K.L., and McCollum, D. (1998). Role of polo kinase and Mid1p in determining the site of cell division in fission yeast. J. Cell Biol. 143, 1603–1616.

**Comment by ValWood** [comment]
@Antonialock  Assigning to you, don't moan at me!
(this probably preceded multi gene interface, it was an early one, I remember!)

**Comment by Antonialock** [comment]
curated for dluble mutants
