### ISSUE TITLE
yae1 tpt1 ortholog?

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1916]
tpt1 is bigger than yae1, but maybe it moonlights or is processed post transcription?

in cerevisiae you have 2 proteins with Yae1 domain https://www.yeastgenome.org/domain/PF09811
in pombe you also have two https://www.pombase.org/gene_subset/interpro:IPR019191

these proteins have been shown to physically interact in pombe, like they do in cerevisiae

![screen shot 2018-03-10 at 12 48 17](https://user-images.githubusercontent.com/12727506/37242444-82956068-2461-11e8-9171-e4c4cb3524ec.png)

**Comment by ValWood** [comment]
Hmm, possible


![tpt1](https://user-images.githubusercontent.com/7359272/37245568-0fbe579e-2492-11e8-8f0b-b0866f4f9ec1.jpg)


![tpt1-2](https://user-images.githubusercontent.com/7359272/37245579-2337e146-2492-11e8-9192-65e1bb9b6f0b.jpg)

**Comment by ValWood** [comment]
YN00_YEAST= LTO1/YNL260C = pombe YQ68_SCHPO lto1/SPCC191.08

**Comment by ValWood** [comment]
diopt supports
http://www.flyrnai.org/cgi-bin/DRSC_orthologs.pl?input_species=4896&output_species=0&additional_filter=None&search_fields=***&search_datasets=***&gene_list=SPAC2C4.12c

**Comment by ValWood** [comment]
pombe is the only thing with this architecture...implies a recent merge.....
![merge](https://user-images.githubusercontent.com/7359272/37245644-60d8d90a-2493-11e8-95ff-137e402075e3.jpg)

**Comment by ValWood** [comment]
Yep, and reciprocal best hits...will update  orthology

**Comment by ValWood** [comment]
yae1 is essential in cerevisiae, and conserved 1:1  which makes it unlikely to be missing from pombe

**Comment by ValWood** [comment]
well spotted...

**Comment by Antonialock** [comment]
was looking for it! iron sulfur cluster assembly and maturation processes will look nice tomorrow hopefully

**Comment by ValWood** [comment]
called it
tRNA 2'-phosphotransferase Tpt1/ ribosome biogenesis protein Yae1 fusion protein (predicted)

that OK?

added:
/controlled_curation="term=orthologous to S. cerevisiae YOL102C; qualifier=SPAC2C4.12c,N-term; date=20180310"
/controlled_curation="term=orthologous to S. cerevisiae YJR067C; qualifier=SPAC2C4.12c,C-term; date=20180310"

you can add the appropriate GO terms

**Comment by Antonialock** [comment]
done

**Comment by Antonialock** [comment]
i tweaked product descr to reflect the other CIA machinery proteins
