### ISSUE TITLE
fra3 uvi31 process

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1917]
~microtubule cyto. org. dropped to 67 from ???~  is now 70, not sure if we have lost any...

**Comment by ValWood** [comment]
- [ ]  pcp1 no longer has BP annotation?

**Comment by ValWood** [comment]
rest is this
https://github.com/geneontology/go-ontology/issues/15349

**Comment by ValWood** [comment]
- [ ]  aim31 barbed end F-actin assembly inhibitor
 - [ ]  klp8?

presumably these will return tomorrow?
 - [ ]  iba57 | SPAC21E11.07 | mitochondrial [4Fe-4S] cluster asssembly and transfer protein Iba57 (predicted)
 - [ ]  fra3 | SPCC4B3.11c | mitochondrial [4Fe-4S] cluster transfer protein Fra3 (predicted)
 - [ ]  uvi31 | SPBC16E9.06c | mitochondrial [4Fe-4S] cluster transfer protein Uvi31 (predicted)




 (I annotated this last week)?

**Comment by ValWood** [comment]
cytoskeleton organization (GO:0030036)
dropped from 125? to 112

**Comment by ValWood** [comment]
still not in
I wonder if it's square brackets in terms in artemis? @kimrutherford 
/GO="aspect=P; term=protein maturation by [4Fe-4S] cluster transfer; GOid=GO:0106035; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000000044; db_xref=PMID:27532772; date=20180309"

**Comment by ValWood** [comment]
fra3 and uvi31 are still no displaying, but iba57 is. I can't see anything wrong. Could you double check, check the logs and if you still think there is a problem open a ticket for kim?

v

**Comment by Antonialock** [comment]
ah, I see the problem, double dbxrefs

**Comment by Antonialock** [comment]
fixed

**Comment by ValWood** [comment]
blimey, I had looked at that loads......

**Comment by Antonialock** [comment]
for ref this is all the data I dug out and that I based the graph on (didn't use all of it, tried to avoid the "guesstimates"


94-98: YPD table 

<img width="428" alt="screen shot 2017-12-29 at 15 26 45 1" src="https://user-images.githubusercontent.com/12727506/37868365-d899442a-2f9c-11e8-89ee-b5ba5d019997.png">


1996a: 3000 (very much a guesstimate)
1996b: 2200 genes of unknown function
2000: 1644 genes of unknown Cellular Role
2002: 1519 unknown
2009: 1134 uncharacterized excl computational predictions, 718 genes uncharacterized by BP including computational predictions
2013: 1214 genes annotated to "biological process unknown"
2013 (November): 1153 genes annotated to BP root



Refs:
94-98:  Hodges PMID:9847145
1996a: PMID:8628394 Oliver
1996b: 2013 presentation, Nazish Nehal, slide 16 https://www.slideshare.net/Nazish_Nehal/yeast-genome-project
2000: YPD proteome cellular role, downloaded on Dec 7 2000, cited in Wu et al PMID:12089522
2002: MIPS inventory date stamped feb15 2002. sum of genes labelled as similarity to unknown protein and no similarity.
http://mips.helmholtz-muenchen.de/proj/yeast/tables/inventy.html
2009: PMID:19577472 Christie et al. "Despite the vast body of literature for this organism, 554 out of 5796 protein-coding genes (almost 10%) remain uncharacterized for all three GO vocabularies. Approximately 500 additional genes only have annotations to very general locations, such as ‘cytoplasm’, defined by HTP localization experiments"

<img width="452" alt="screen shot 2017-12-23 at 21 33 52" src="https://user-images.githubusercontent.com/12727506/37868369-ecd4e4ee-2f9c-11e8-9711-71103932061e.png">


2013: PMID:23749449 Gibney et al. Supplementary downloadable data, file: GO-slim_analysis_full
2013 (November): 2013 presentation, Nazish Nehal, slide 24 https://www.slideshare.net/Nazish_Nehal/yeast-genome-project

**Comment by ValWood** [comment]
Great we will need this for  the refs. But it is in the wrong ticket ;)

**Comment by Antonialock** [comment]
also for ref spreadsheets and graphs live in dropbox unknowns_paper_2017

**Comment by Antonialock** [comment]
oh, I had several open..

**Comment by ValWood** [comment]
I know the feeling. .....
