### ISSUE TITLE
missing process annotation?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1923]
Any idea why @Antonialock 

- [x] grx3 | SPCC1450.06c | CIA machinery monothiol glutaredoxin Grx3

- [x]  tah18 | SPAC1296.06 | CIA machinery NADPH-dependent diflavin oxidoreductase Tah18 (predicted)

**Comment by ValWood** [comment]
- [ ]  pcp1 | SPAC6G9.06c | gamma tubulin complex linker, pericentrin/kendrin Pcp1 (I think this is me...)

**Comment by ValWood** [comment]
- [ ] iba57 | SPAC21E11.07 | mitochondrial [4Fe-4S] cluster asssembly protein Iba57 (predicted)

- [ ] fra3 | SPCC4B3.11c | mitochondrial [4Fe-4S] cluster transfer protein Fra3 (predicted)

- [ ] uvi31 | SPBC16E9.06c | mitochondrial [4Fe-4S] cluster transfer protein Uvi31 (predicted)

**Comment by Antonialock** [comment]
sorry typod something, logs fixed

**Comment by ValWood** [comment]
grx3 not back, is it fixed?

**Comment by Antonialock** [comment]
yeah I fixed them yesterday

**Comment by Antonialock** [comment]
I can do log fixes at the same time as looking for them

**Comment by Antonialock** [comment]
can't find a problem for grx3. It has this annotation (I believe I fixed a problem in the annotation yesterday - I expect it to show tomorrow - this is what I menat when I said I suspect there is a 1 day delay in displaying artemis annotations on www - it takes 1 day for them to show in the logs and 2 days for www? I'm not sure about this, I just have a feeling. Lets see if it shows tomorrow? @kimrutherford )

/GO="aspect=P; term=[4Fe-4S] cluster assembly; GOid=GO:0044572; evidence=ISS; with=SGD:S000002168; db_xref=PMID:28515324; date=20180310"

**Comment by Antonialock** [comment]
I changed ISS to ISO, do you think that's what causing the issue?

**Comment by Antonialock** [comment]
that might be it? e.g. tah18 also has
/GO="aspect=C; term=cytosol; GOid=GO:0005829; evidence=ISS; db_xref=PMID:19194512; with=SGD:S000006252; date=20180310"

and that is not showing

**Comment by Antonialock** [comment]
Although I think another ISS was showing as an ISS, but that had evidence 
GO_REF:0000024

@kimrutherford

**Comment by Antonialock** [comment]
although grx5

/GO="aspect=P; term=[4Fe-4S] cluster assembly; GOid=GO:0044572; evidence=ISS; db_xref=PMID:25347204; with=UniProtKB:Q86SX6; date=20180309"
/GO="aspect=P; term=protein maturation by [2Fe-2S] cluster transfer; GOid=GO:0106034; evidence=ISS; db_xref=PMID:25347204; with=UniProtKB:Q86SX6; date=20180309"

not showing....is it a problem using a PMID xref with ISS in general?

**Comment by Antonialock** [comment]
shouldn't be..
"If the searches and evaluation of the sequence-based data are described in a published paper, the ID (either one assigned by PubMed or one assigned by another database such as a Model Organism Database) of the paper should be placed in the reference column. However, if the group that is doing the GO annotation performed the searches and evaluation of the sequence-based data, and there is no published reference, a reference can be used from the GO Consortium's collection of GO references"

**Comment by ValWood** [comment]
maybe we aren't displaying ISS

**Comment by ValWood** [comment]
nope thats not it. I'll take a look....

**Comment by ValWood** [comment]
its there...

**Comment by Antonialock** [comment]
That's dev not www? @kimrutherford

**Comment by ValWood** [comment]
thats ok, it might not have gone live, but it's there.
