### ISSUE TITLE
biosharing update

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1930]
mentions EBI

https://fairsharing.org/biodbcore-000139

**Comment by ValWood** [comment]
I found some more notes I made about this page (I'm having a mega laptop  tidy and planning day...I don't know how this happened my plan was to go swimming and spend the day cooking)...

Suggest new link types to cover
Project  Metrics, so that we can link to this page 
https://curation.pombase.org/pombe/stats/annotation
(@kimrutherford  should we change this so it it just "metrics"?)

Also add
Canto to tools
Data curation can link to Canto

other links should also be populated
Web interface
File download

Data release needs updating

versioning?

mailing list

terms of use

**Comment by Antonialock** [comment]
done to the best of my abilities (they say they review submissions so might not be immidiately updated online)
