### ISSUE TITLE
histone residue numbering

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1938]
for e.g. hta1 and hta2 allele descriptions state e.g. S121A mutations, but the serine is actually at position 122 in the sequence (could be either becuase it is 121 in human, or a residue is trimmed?)
121 is actually a Q in the sequence

in the modification section we specify S122  as a phosphorylated residue, not 121

should we report this as 121 (consistent with publications) or 122 (consistent with what we report as the translated sequence)? 

we might have discussed this before..

**Comment by ValWood** [comment]
I think histone residues are referenced differently (excluding the methione)...confusing...

**Comment by mah11** [comment]
This is a known annoyance: histones are special. The initiator methionine is removed, but for the purpose of allele descriptions residues are numbered as if that Met residue was still present.

In the literature, the residues are often numbered not counting the removed Met, but I can't guarantee there are no exceptions.

**Comment by Antonialock** [comment]
> for the purpose of allele descriptions residues are numbered as if that Met residue was still present

nope, for these examples the alleles reflext whatever the authors called it (S121A, when protein sequence = S122) 

for protein modification we have used the "real" sequence S122 is phosphorylated

**Comment by mah11** [comment]
But the difference does still reflect different ways of handling the removed initiator Met (even if I got it the wrong way round for alleles, or if not all our alleles are done consistently).

**Comment by Antonialock** [comment]
yeah fine, just wondered if we should try and be consistent across the phenotype section and the modification section? If so which section should change?

**Comment by ValWood** [comment]
What are the actions here? It says "discuss"

**Comment by mah11** [comment]
Make histone residue numbering consistent between allele descriptions and modification extensions.

I'm inclined to change modifications, because the alleles follow the convention in the literature ... but I think that's the bit that we could discuss if anyone prefers otherwise.

**Comment by ValWood** [comment]
I think we should follow the same convetion as allele. I think it will be a smaller number to fix too...

**Comment by ValWood** [comment]
Thoughts:
Will it be easy to  get the things which need fixing out of the  phospho spreadsheet? or will some query need to be run?

Will also need docs updating  for annotation, it would be really cool if we could somehow have this as a comment  for the terms (maybe PSSI-MOD would add them?)...perhaps we should check with them if they agree with the convention?

**Comment by ValWood** [comment]
I'm passing this to Midori as you have 100 tickets right now...

**Comment by mah11** [comment]
Annotations fixed. Documentation updated. (In both cases, some but not all needed work.)

> it would be really cool if we could somehow have this as a comment for the terms (maybe PSSI-MOD would add them?)

I think not - it would be out of scope for them. PSI-MOD defines the modified residues (what they are chemically, which are subtypes of which, etc.); it doesn't deal with locations at all.
