### ISSUE TITLE
find ER annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1939]
http://pombase-dev.bioinformatics.nz/gene/SPAC19A8.06

**Comment by ValWood** [comment]
has
but not displaying....

/GO="aspect=C; term=endomembrane system; GOid=GO:0012505; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000005125; date=20050609"

doesn't appear to be a reason that would be filtered...
@kimrutherford

**Comment by mah11** [comment]
filtered because there's a more specific annotation?

    /GO="aspect=C; term=endomembrane system; GOid=GO:0012505; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000005125; date=20050609"
    /GO="aspect=C; term=nuclear membrane; GOid=GO:0031965; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000005125; date=20050609"

GO:0031965 part_of GO:0005635, and GO:0005635 part_of GO:0012505

**Comment by ValWood** [comment]
I looked at the parentage and missed that!

**Comment by mah11** [comment]
glad all those years I spent doing GO weren't totally wasted ;)
