### ISSUE TITLE
Annotation priority: background 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1953]
curs/30da765280e4ffe0
cdc13

are these required?

If so let me know what the reason so I can add to my list:

![ask m](https://user-images.githubusercontent.com/7359272/37867555-5c066000-2f92-11e8-9980-78288eef4a8b.jpg)

specifically.
i)  is cdc2+ required (wouldn't that be a given?)
ii) what does cdc2-33 do (should this be foreground or is it an experimental thing?)

**Comment by mah11** [comment]
deleted cdc2+; it was only there to make the distinction from the cdc13+ knockdown in the cdc2-33 background more obvious

others are synchronization tools; retain or delete as you see fit.
