### ISSUE TITLE
review of background

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1957]
I went through the backgrounds and standardized.
removed comma,  removed within allele spaces, standardized allele names etc.

I removed 
TAGS eg:
5b7414d8bc7f80eb | GFP-atb2
 5b7414d8bc7f80eb | GFP-Atb2
 5b7414d8bc7f80eb | GFP Atb2 Cut11 GFP
 5b7414d8bc7f80eb | rlc1-GFP 
 d91d901cb0a83596 | pcn1:3FLAG
 f2b0ffda72370b22 | tubulin CFP kanR  leu1-32 ade6-M210 ura4-D18 h-
 f2b0ffda72370b22 | tubulin CFP kanR ura4-D18 ade6-M210h-
 8fb498d6aad39666 | GFP-Tubulin
88d2e1acdc9993bc | cor-C-GFP ade6-M216 leu1-32
 88d2e1acdc9993bc | cor-C-GFP leu1-32
 88d2e1acdc9993bc | cor-C-GFP leu1-32 ura4 D18

I removed WT from the backgrounds: e.g
d800c02f9eed68d9 | WT background
  d800c02f9eed68d9 | WT background
 30da765280e4ffe0 | cdc2+
52e0036cabf3303e | cdc18+ leu1-32
 8505764defef1039 | nuc2.663 cut7+ 
4847e0de3cb01075 | fhl1::ura4+ ura4-D18 h90

I removed the  deletion referring to the mutated gene
e.g
dc2Δ::ura4+
3e2f643b12155f98 | cdc2Δ::ura4+ leu1-32, ura4-D18 ade6-704
 50a71e0348432087 | cdc25::ura4+ ura4-D18 leu1-32
bc6337774fa106c2 | spc7::natMX6

**Comment by mah11** [comment]
different from https://github.com/pombase/canto/issues/1392?

**Comment by ValWood** [comment]
What is  left are all

1. strain e.g
619a912c82d69329 | h- 972
 ce4cb6da2a1e760  | h-
 cfa1ac27dc7acf6c | h90
 9ddea08e60ffe505 | h+
 or in combination

2. ploidy eg 
 1ebe4a1548de4aff | homozygous diploid
 b447b564f630559e | homozygous diploid
6378670e7a31c356 | pat1-114/pat1-114; homozygous diploid
will be dealt with later

experimental set up

synchronization
f78a781e3e01fdf4 | cdc25-22
- [ ] fed93fe54aa51313 | cdc25  ?????   FIX
 30da765280e4ffe0 | cdc2-33

to analyse transport
d17a6f8397b4b058 | hem1-delta 

cytoskeletal disruption
330f117d21a8480a | nda3-KM311
- [ ]  35e854953c18ed20 | nda3  ????? FIX
 4d4822dbe566aaac | nda3-KM311 ????FIX
- [ ]   25a5d9e72c9fc7ec | nda3-KM
 a8928db520ace5a9 | nda3-KM311
 f6a5a7da08695182 | nda3-KM311

force meiosis?
9f25f26d17f2ec78 | pat1-as2
 9f25f26d17f2ec78 | pat1-as2 cdc2delta, cdc13delta
 9f25f26d17f2ec78 | pat1-as2, cdc2delta, cdc13delta
393d0a5aae35d3ac | pat1-114

preventmeiosis?
 9197675c3ba9f5d1 | mei4delta
 f17c3d43d258f9f6 | mei4-P527 

g1 arrest?
292fcc3259a4f5aa | cdc10-129
 4ced25f5e52826a2 | cdc10-M17
30da765280e4ffe0 | cdc10-V50

**Comment by ValWood** [comment]
4. selectable markers, lots of flavours...

1ff973d4c300af54 | ade6-704 leu1-32 ura4-D6
 1ff973d4c300af54 | leu1-32
 2bfae567526bc0ec | ade6-704 ura4-D18 leu1-32
 b19dfb2b27f82b53 | his3-D1/his3-D1 ura4-D18/ura4-D18 ade6-M210/ade6-M216 leu1-32/leu1-32 h+/h-
 b19dfb2b27f82b53 | his3-D1 leu1-32 ura4-D18 ade6-
 b19dfb2b27f82b53 | his3-D1 leu1-32 ura4-D18 ade6-M210 h-
2bfae567526bc0ec | leu1-32
43f8a34aa26e2202 | leu1-32
 43f8a34aa26e2202 | leu1-32 his3-27
 43f8a34aa26e2202 | ura4-D18 leu1-32
  67026591584779dd | leu1-32, ura4-D18, ade6-M216
eab9a81ad211e62f | KanMX
 eab9a81ad211e62f | KanMX leu1-32 ade6-M210
 eab9a81ad211e62f | KanMX leu1-32 ura4-D18 ade6-M210
 eab9a81ad211e62f | KanMX ura4-D18
 eab9a81ad211e62f | KanMX  ura4+ ura4-D18
 eab9a81ad211e62f | KanR ura4+ ura4-D18 ade6-M210
f2b0ffda72370b22 | kanR ade6-M216 ura4-D18 h-
 f2b0ffda72370b22 | kanR leu1-32 ade6-M210 ura4-D18 h-
 f2b0ffda72370b22 | kanR  leu1-32 ade6-M216 ura4-D18 h-
 f2b0ffda72370b22 | kanR leu1-32 ade6-M216 ura4-D18 h-
 f2b0ffda72370b22 | kanR, ura4-D18, ade6-M210h-
 f302ee9f01375c61 | ura4-D18
 f8fd03e7d6da971d | leu1-32 h-
 f8fd03e7d6da971d | leu1-32h-
 f2b0ffda72370b22 | ura4+ ura4-D18 ade6-M210
 5c744b7dd350f431 | leu1-32 ade6-M216
 5c744b7dd350f431 | ura4-18 leu1-32 ade6-M216
 5c744b7dd350f431 | ura4-D18 ade6-M216
 5c744b7dd350f431 | ura4-D18 leu1-32
 5c744b7dd350f431 | ura4-D18 leu1-32 ade6-M216
 df21e2714ebca0b4 | leu1-32
 50a71e0348432087 | leu1-32 ura4-D18
etc

**Comment by ValWood** [comment]
There are ones that I wasn't sure what they were, but they look like   experimental set up 
so I left as is:
 063efc493e59cfc2 | pom1-as
 205df3a82b504d79 | pmd1delta
 20a764f2e6d7485e | tpz1delta
 22e0aeba5f85fb0e | diploid  homozygous for rad50delta, also with ura4+/ura4-D18 ade6-M210/ade6-M216
25a5d9e72c9fc7ec | mad2-OP
36fa256918417316 | RTS1-mat1-SspI::inv-RTS1 (RTS1 moved to cenII-distal side of mat1 and inverted)
 4adda085ff88928f | dis32-D461N
  593e1f8fb43caaa9 | rnh201delta
  5da5597d14f0cc49 | mat1Pdelta17::LEU2
 7145919e461c7ff3 | swi10delta uve1delta mlh1delta
 a309fa2c0e0a8d62 | swi10delta uve1delta mlh1delta
  7622b54e59b561d0 | mre11-H134S
 92800aaf61c226d9 | vps901delta
 a4e15abcd73293ed | orb6-as1
 b2ae716b0ad7c3cb | cdc25-22 wee1-as8 cut9ts
  b6b9d534da028509 | RTS1-mat1-SspI::inv-RTS1 (RTS1 moved to cenII-distal side of mat1 and inverted)
 b9792083a95e2fee | msc1delta
  c487bc6d6b5cb410 | sre1-delta
 e13e49a2df6b7722 | Cnp3C-TEV (kinetochore localized protease)
 f0afc6fe7b0b439a | slp1-shutoff
 f96ee693f519ef9d | cdc25-22 cdc13Δ

**Comment by ValWood** [comment]
5. One oddball, human gene in a construct. We weren't sure how to do this so it's fudgen in background. Should probably move to allele type "other"?

 2bfae567526bc0ec | cdc2::CDC2Hs ade607 leu1-32 his3-27
 2bfae567526bc0ec | cdc2::CDC2Hs ade6-704 leu1-32 his-27
  43f8a34aa26e2202 | cdc2Hs leu1-32 his3-27
1ff973d4c300af54 | CDC2HS his3-27 leu1-32
 1ff973d4c300af54 | CDC2HS his3-27 leu1-32

**Comment by ValWood** [comment]
So, should "ploidy" be in the background or in allele type "other"

- [ ] if the latter, need to migrate

@Antonialock  said
I think that is how I do it already e.g.
ygf1-/yfg- homozygous diploid
though I might not be consistent for this with meiotic phenotypes.
Heterozygous ones are really the ones that are interesting to differentiate
because the other one is a "deletion" anyway?

**Comment by Antonialock** [comment]
> because the other one is a "deletion" anyway?

no, one is mutated (anything) and one is WT

**Comment by mah11** [comment]
> So, should "ploidy" be in the background or in allele type "other"

Ploidy is definitely not an allele type. If https://github.com/pombase/canto/issues/976 gets implemented as suggested, ploidy won't have to be shoehorned into background either.


>> Heterozygous ... because the other one is a "deletion" anyway?
> 
> no, one is mutated (anything) and one is WT

Still not quite - heterozygous = the two alleles are different from each other. It could be any combination (deletion/wt (aka hemizygous), deletion/point mutant, point mutant/wt, two different point mutants, etc.).

**Comment by ValWood** [comment]
> Ploidy is definitely not an allele type. 

I know this, but it would be better to have them all in the same place pending the changes to handle ploidy.....

**Comment by ValWood** [comment]
@Antonialock said
> because the other one is a "deletion" anyway?

then 
@Antonialock  said
no, one is mutated (anything) and one is WT

so can you correct  your  first comment because  I don't know what you mean ;)

**Comment by Antonialock** [comment]
I think it's only interesting to note ploidy where it is a diploid doing vegetative growth, or where it is a haploid trying to do meiosis (otherwise it is a given)

the way we record alleles currently is sufficient for homozygous diploids. For heterozygous diploids the current system that allows addition of a WT allele might suffice? (so we could migrate)? I think it is a bit non-obvious, it might be nice to have a flag for those (e.g. heterozygous diploid...)

**Comment by ValWood** [comment]
OK, so we need to
- [ ]  document clearly when we need to record (I'm a bit confused)
- [ ]  figure out how we are doing this in the current system. If there are multiple different ways, we should standardize (so that migration is simpler for Kim when we have the new system. At present I think we capture in 2 different places? which is most common?

**Comment by ValWood** [comment]
Maybe tubulin tags should  be in fore ground, they affect microtubule dynamics?


Although expression of a GFP-tubulin construct is necessary for live-cell imaging of the MT cytoskeleton, it has been noted that expression of such constructs can affect MT behavior and dynam- ics (26). For example, it has been reported that strains expressing nmt81::GFP-Atb2 at the atb2􏰋 locus have altered MT properties (24, 27–29). The reason for this is unclear.

**Comment by ValWood** [comment]
Closing.
We can review background again in the future.
