### ISSUE TITLE
disease associations

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1959]
I know, this is not an efficient way to do this!
I did try to automate once, but I could not  access a list of human disease genes (even after mailing for help). I could not separate from candidates.

Armanios, M. & Blackburn, E. H. The telomere syndromes. Nat. Rev. Genet. 13, 693–704 (2012).

**Comment by ValWood** [comment]
| Mutations in PMPCB Encoding the Catalytic  Subunit of the Mitochondrial Presequence Protease Cause  Neurodegeneration in Early Childhood.
-- | --
  | Am J Hum Genet. 2018 Mar 21;. [Epub ahead of print]
  | PMID: 29576218

**Comment by Antonialock** [comment]
done
