### ISSUE TITLE
GO file update

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1961]
@mah11  I know that you usually update the GO  data on the 15th, but could you do one  at you earliest convenience?

currently the GO term mapper is quit a "bit out"
These 734 identifiers had no non-root annotations:

compared to
Protein coding genes not covered by the slim (717 in total):
Gene products with biological process annotation, but not in any of the categories above: 16
Gene products with no biological process annotation: 701

After the next GO update gets to  GO term mapper (takes a few days), I will finalise

https://github.com/pombase/curation/issues/1947
https://github.com/pombase/curation/issues/1830
etc so that it matches (as much as possible...it will never be exact...)

v

**Comment by ValWood** [comment]
this is the number I am after....
http://pombase-dev.bioinformatics.nz/browse-curation/fission-yeast-go-slim-terms
which is not the live number right now.

**Comment by mah11** [comment]
done

**Comment by ValWood** [comment]
OK I'll take this as a reminder to run when term mapper/slimmer updated, and this fixed
https://github.com/geneontology/helpdesk/issues/112

(or I can probably filter IBA etc)

**Comment by ValWood** [comment]
When I'm happy with the  term mapper output, also update the GO_slim.tab for esyN.
from https://github.com/pombase/curation/issues/1905
Check act1 has cytoskeleton connections

**Comment by ValWood** [comment]
yes! all working and act1 is in the network....
