### ISSUE TITLE
new external file

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1963]
there was another file for Juans data
Duncan_29432178_2.tx

I checked it in, removed the control characters, but I know realise that I missed out the evidence code which should be

ECO:0000058

@kimrutherford  can you insert that with a  perl one liner? I can't remember how to do tabs and I'll probably get it wrong.... (or tell me how)

Also which version of ECO are we using?  A new Evidence code I wanted for "ribosome profiling" has been added. 28/03/2018
I will stitch the code in Duncan_29432178 to ECO:0007087

**Comment by ValWood** [comment]
Or maybe I can just stick this evidence code  in now anyway?

**Comment by ValWood** [comment]
Thank you, I couldn't remember......

Can you fix the  missing evidence code in the RNA data file too ;)

**Comment by mah11** [comment]
The file that was missing evidence is the one where I added ECO:0007087.

In the slightly-older file (Duncan_29432178.txt), most of the lines have ECO:0000006, but one has ECO:0000112. Do you want them all changed to ECO:00007087?

**Comment by ValWood** [comment]
The one that was missing the evidence should be ECO:0000058 (the new file)

The older file had  ECO:0000006 as a place holder. ECO:0000006 should be converted to 
ECO:00007087 (ribosome profiling).

As a check, ECO:00007087 should only be with lines which have "translation" not "RNA".

**Comment by mah11** [comment]
OK, done

**Comment by kimrutherford** [comment]
> The one that was missing the evidence should be ECO:0000058 (the new file)

Loading Duncan_29432178_2.txt failed with:

    "during(GO:1903832)" is not a valid qualifier for gene expression annotation in line:
    SPAC21E11.04  RNA ECO:0000058 during(GO:1903832) increased PMID:29432178      4896 20180309

It looked like the qualifier and extension columns were swapped.  I've edited the file so it should work tomorrow.

**Comment by kimrutherford** [comment]
> I've edited the file so it should work tomorrow.

Usually I try to avoid running the load during the day when you might be using Canto or pombase-trac.  But it's the weekend and the new server is fast enough that I decided to restart it immediately.

**Comment by kimrutherford** [comment]
Got a different error this time:

    loading: /var/pomcur/sources/pombe-embl/external_data/qualitative_gene_expression_data/Duncan_29432178.txt
    unknown evidence code "ECO:0007087"

> Allowable ECO IDs and names go in https://github.com/pombase/pombase-chado/blob/master/load-pombase-chado.yaml - I've added ECO:0007087 there and in your new data file

Maybe you forgot to check in the file?  I've just added it and I'm about to restart the load.

**Comment by ValWood** [comment]
Oh yes, I forgot to swap the second file!
Thanks!

**Comment by kimrutherford** [comment]
The load has successfully finished with the new data and the main site is updated.

**Comment by ValWood** [comment]
Great, all looks good, have asked Juan and Caia to check it over.

v
