### ISSUE TITLE
cohesin loading

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1965]
once
https://github.com/geneontology/go-ontology/issues/15513
and 
https://github.com/pombase/fypo/issues/3273
adressed, need to work out which existing should move down to the new terms

(only Ullman paper probably?)

**Comment by ValWood** [comment]
Also need a NOT annotation for second strand capture for pds5 and wapl, need to do that in Artemis

**Comment by mah11** [comment]
admin users (i.e. us) can do qualifiers including NOT in canto

**Comment by ValWood** [comment]
I thought I could but I could not see it yesterday...maybe I wasn't logged in ??

**Comment by ValWood** [comment]
I didn't do this for now. I looked at it recently and decided I  the old annotations should stay as is.
