### ISSUE TITLE
need to change GO:0140110 annotations PMID:17452352

### ISSUE THREAD

**Issue by mah11** [pombase/curation#1966]
There's an annotation to GO:0140110 'transcription regulator activity' from PMID:17452352 (split into two lines in Canto "existing annotations" and GAF due to extensions), but GO:0140110 is marked as not for direct annotation, so it makes the checks throw an error.

To get the GAF in (for Val in #1961) I've just removed the GO:0140110 annotations from it, but left them in the Canto session until they get fixed. I think it would work to use a DNA binding term (most likely GO:00000981) by IC from the GO:0045944 BP and GO:0000790 CC annotations, maybe also with the DNA binding MFs for ams2 and GO_REF:0000036 for IC from multiple references.

The happens_during mitotic S phase and has_regulation_target (histones) extensions could either move to the BP term for maximal consistency with the IMP evidence, or go with the IC'd MF term; I don't have a preference there.

session 3e4ec1257970269c

**Comment by Antonialock** [comment]
Cheers, I think it can be changed to GO:0001077 (done)
