### ISSUE TITLE
oxidation-reduction  process

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1967]
I deleted these (in our do not annotate, because not telling us anything more than the MF term)

This will leave these without a process, so, don't we know what they *actually* do?

SPAC22E12.10c.1		GO:0055114	oxidation-reduction process	aeadfc528237dc96	PomBase
SPBC3B8.01c.1		GO:0055114	oxidation-reduction process	bbaa96d60dc05b65	PomBase
SPAC22E12.10c.1		GO:0055114	oxidation-reduction process	bbaa96d60dc05b65	PomBase

**Comment by ValWood** [comment]
...may need to come back into unknowns?

**Comment by Antonialock** [comment]
no they are good I think

**Comment by Antonialock** [comment]
GO:0044571

**Comment by Antonialock** [comment]
they provide electrons

**Comment by Antonialock** [comment]
the have MFs from these papers so deleting the BPs is fine I think

**Comment by ValWood** [comment]
so it should be a more specific term than
"oxidation-reduction process" which covers any oxidase or reductase?

**Comment by ValWood** [comment]
These won't have a process ?
I don't know if we have a process that describes adequately, but I'm not sure what it does.... these were in my unknowns bin until recently, I know we know quite a lot about them, I'm just not sure what it is ??

**Comment by Antonialock** [comment]
Well I guess it is involved in "electron flow"? But this isn't a GO term...

They enable flow of electrons...I don't think it is known exactly what for, probably to convert the cysteine sulphur (S0) to sulfide (S2−), or maybe to assemble or transfer the 2Fe2S cluster.

If we can't annotate to oxidation reduction or electron flow then I don't think we can annotate to anything.

**Comment by Antonialock** [comment]
they will have other annotations.

**Comment by Antonialock** [comment]
e.g. GO:0044571

**Comment by ValWood** [comment]
OK, oxidation/reduction is describing a MF not a process

but all good, i didn't realise they now had iron-sulphur cluster processses!

**Comment by ValWood** [comment]
one more question...

Is this the correct term
https://www.pombase.org/term/GO:0009055
has parentage to "electron transport chain"?

**Comment by ValWood** [comment]
and there are IDAs to
GO:0022904 | respiratory electron transport chain
(which don't appear to be from F-P links?)

**Comment by Antonialock** [comment]
I can't see IDA to respiratory electron transport chain?

but yes electon transfer activity has parentage to electron transport chain, that should change

**Comment by ValWood** [comment]
here
https://www.pombase.org/gene/SPAC22E12.10c

**Comment by ValWood** [comment]
> but yes electon transfer activity has parentage to electron transport chain, that should change

OK needs submitting to the GO tracker...no hurry one of us can do it later...

**Comment by Antonialock** [comment]
well, maybe just change the annotation, I'm not sure

**Comment by ValWood** [comment]
me neither!

**Comment by Antonialock** [comment]
at least it was a systematic error! easy to change from one term to another term even if there were 7 papers

changed to oxidoreductase activity, acting on NAD(P)H

**Comment by Antonialock** [comment]
also removed old annotation 

respiratory electron transport chain

**Comment by ValWood** [comment]
but that's a function, what's the process?

**Comment by Antonialock** [comment]
iron sulfur cluster assembly

**Comment by ValWood** [comment]
Oh yes right -  you said before. Got it!

**Comment by Antonialock** [comment]
so it is known "for sure" it provides electrons to this process (2Fe2S assembly) but not exactly sure why it is needed, e.g. sulfur reduction, cluster assembly or cluster transfer
