### ISSUE TITLE
wrong ortholog SPAC3G6.05

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1972]
pombe SPAC3G6.05

human mpv17 (correct)
cerevisae ortholog wrong?

e.g.
![screen shot 2018-04-07 at 14 29 33](https://user-images.githubusercontent.com/12727506/38455461-57a4ad9e-3a70-11e8-8ab5-de8e36a36131.png)

![screen shot 2018-04-07 at 14 30 58](https://user-images.githubusercontent.com/12727506/38455462-57d2334a-3a70-11e8-8c7a-1a1a8f08fc99.png)

**Comment by ValWood** [comment]
? pombe SPAC3G6.05??


I see?

![mpv](https://user-images.githubusercontent.com/7359272/38457072-bb3ffeb8-3a83-11e8-9dc0-607cb4a57e70.jpg)

**Comment by Antonialock** [comment]
oh this got confusing

**Comment by Antonialock** [comment]
SPAC4G9.14 - 
human  PXMP2 (high)
human  MPV17 (high)
cerevisiae SYM1 (high)
cerevisiae YOR292C (low)

pombe SPAC3G6.05
human  MPV17 (high)
human  MPV17L2 (moderate)
human  MPV17L (moderate)
human  PXMP2 (low)
cerevisiae YOR292C (high)
cerevisiae SYM1 (moderate)

**Comment by ValWood** [comment]
so it looks OK as is?

**Comment by Antonialock** [comment]
I guess...maybe? but that ref and cerevisiae gene page state that mpv17 and sym1 are orthologous

**Comment by ValWood** [comment]
it says "human homolog MPV1", not ortholog...

**Comment by Antonialock** [comment]
sorry!

**Comment by ValWood** [comment]
no worrires, good to check!
