### ISSUE TITLE
follow up on annotation conundrum

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1974]
I wanted to follow up on this because I thought  it was interesting

pathway: mitotic DNA replication checkpoint signalling
![20180410_170235](https://user-images.githubusercontent.com/7359272/38568776-6b4e933c-3ce1-11e8-839a-ec62b9fb47ac.jpeg)

1. I agree that the correct term would be "protein binding bridging"
this fits with the description in the abstract of the earlier publication
https://www.pombase.org/reference/PMID:14585996
as an "adaptor checkpoint protein"

2. I agree that MF "protein kinase activator" should be reserved for instances where the activity is altered

3. Here I ~don't~ think  we could just say

"protein binding bridging" part_of "regulation of mitotic DNA replication checkpoint signalling"

the rest of the information would be captured  if it is all pulled together (provided everything that should be annotated to  "DNA replication checkpoint signalling" is present.

i.e.
i) Mrc1 protein binding bridging Cds1,Rad3 part_of "regulation of mitotic DNA replication checkpoint signalling"
ii) rad3 phosphorylates Mrc1 on T604 part_of "regulation of mitotic DNA replication checkpoint signalling"
iii) mrc1 P604 binds to Cds1 part_of "regulation of mitotic DNA replication checkpoint signalling"
iv) rad3 phosphorylates Cds1 T11 part_of "DNA replication checkpoint signalling"

Maybe that will do to cover the figure? I think of this as regulating the process rather than regulating the activity of a gene product....

**Comment by ValWood** [comment]
typo fixed!
3. Here I ~don't~ think  we could just say

**Comment by mah11** [comment]
> "protein binding bridging" part_of "regulation of mitotic DNA replication checkpoint signalling"

That isn't the annotation I want to make from PMID:15173168. I want to use part of Cds1 phosphorylation in the extension on the bridging MF annotation, i.e.

"protein binding, bridging" part_of "positive regulation of protein phosphorylation"

but I'm a bit stuck because I don't know how to make it clear that (a) Mrc1 bridges between Cad3 and Cds1, and that increases phosphorylation of Cds1. At worst I can make separate annotations to the MF and BP terms.

(It also isn't this paper that shows that Rad3 phosphorylates Mrc1 on T604 ... the whole picture comes from putting a bunch of papers together, as always.)

**Comment by mah11** [comment]
> I think we have a ticket about this but here:
> [screenshot]
> I expected the modified form to refer to cds1 but it's mrc1....

Yeah, "active form" is what we display for column 17 entries. I'm not sure we've settled on what to display when a PR ID goes in a (col 16) extension. It got mired in the madness of what we might be able to reliably extract from PR entries and melted all our heads ...

Anyway, the ticket is https://github.com/pombase/website/issues/67

**Comment by ValWood** [comment]
What I'm saying is that if you just did
"protein binding bridging" part_of "regulation of mitotic DNA replication checkpoint signalling"

AND because the other annotations would (or should exist) and be connected correctly,
then you don't even need to say that 
"protein binding, bridging" is part_of "positive regulation of protein phosphorylation"
because "regulation of mitotic DNA replication checkpoint signalling" is a phosphorylation cascade, so this is a given...

if rad3 phosphorylates cds1 as part of "checkpoint signalling"
and mrc1 is a molecular adaptor between rad3 and cds1 as part of "regulation of checkpoint signalling"  
Then it is kind of implicit what is happening  you don't need to say because it kinda obvious, because the only thing rad3 does to cds1 is to phosphorylate it  (will be much clearer when we can draw pathways for all processes, ad we can label activities)

This is what we see right now:

**Comment by ValWood** [comment]
It's kind of related to this question:
https://github.com/geneontology/go-ontology/issues/15509
https://github.com/geneontology/go-annotation/issues/1899

**Comment by mah11** [comment]
> because "regulation of mitotic DNA replication checkpoint signalling" is a phosphorylation cascade, so this is a given...

I just went to check whether the definition makes this explicit ... and *the term doesn't even exist*. There are no regulation terms for GO:0072443 ! signal transduction involved in mitotic DNA replication checkpoint.

On the assumption that you'll get the reg terms added and defined as phosphorylation cascades ...

> then you don't even need to say that "protein binding, bridging" is part_of "positive regulation of protein phosphorylation"

but that's what I could attribute to PMID:15173168. If there's enough from other papers to fill in the story, I can just make the bridging MF annotation from this paper without an extension.

**Comment by ValWood** [comment]
Well the first sentence of the abstract is
"The protein kinase Cds1 is an effector of the replication checkpoint "
and in the intro
Mrc1, so named because it is a mediator of the replication checkpoint, is required for activation of Cds1 but not Chk1. 
 so I was making a gross assumption that the intent is to show how Mec1 regulates this checkpoint.

so when they say
In this study we provide evidence that the association of Mrc1 to the Cds1 FHA domain mediates the initial Thr-11 phosphorylation of Cds1. Furthermore, we show that expression of a Cds1-Rad26 fusion protein substantially bypasses the requirement for Mrc1 in the replication checkpoint.

I think it is safe to assume that this event  is "regulating the checkpoint signalling". But you are correct this depends on the knowledge that   "checkpoint signalling begins with the rad3 ATR kinase" and that cds1 is specific for the replication checkpoint......so I should update the GO term to reflect as much of  this as possible.
https://www.nature.com/scitable/topicpage/the-dna-replication-checkpoint-and-preserving-genomic-14157692

This seems to align with the guidelines which were developing from the signalling meeting, but I am not sure that they materialised yet...
This seems that it would be treated as a "scaffold" which brings components together and regulates  the "signalling pathway".

So if you want to make only the bridging annotation here that's fine, but I think that it could be extended to include part_of "regulation of mitotic DNA replication checkpoint signalling"
when the term exists.

I can take this ticket as a reminder to request the GO updates. I won't do it right now,   for obvious reasons.....( and also checkpoint signalling is still a bit of a mess....I need to find out what are classes as sensors and how to annotate those).....

**Comment by ValWood** [comment]
out of date
https://github.com/pombase/curation/issues/2970
