### ISSUE TITLE
oligopeotide and urea transport

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1981]
- [x] ptr2  dipeptide transmembrane transport ( improve specificity) PM?

- [x] dal51  dipeptide transmembrane transport

- [x]  gcs1  glutathione transport

- [x] gsa1  glutathione transport

- [x]  opt3 oligopeptide transmembrane transport ?

- [x] isp4  tetrapeptide transmembrane transport

**Comment by Antonialock** [comment]
whups, yes just a silly mistake. Fixed.
