### ISSUE TITLE
sequence status

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1985]
we should add the telomeric contig to this page with a note about position and overlap
https://www.pombase.org/status/sequencing-status

**Comment by mah11** [comment]
- this looks like a website item
- what should the note say?

**Comment by ValWood** [comment]
Argh I thought I  switched to website tracker....

for the note I will need to look out the overlap....I think there is one...

**Comment by mah11** [comment]
I've opened https://github.com/pombase/website/issues/747 and will follow up there.
