### ISSUE TITLE
unknowns figure 2C

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1986]
from  https://github.com/pombase/curation/issues/1960

Protein sets, slim and poutput files are now in google drive folder.

- [x]  human protein set needs replacing
- [x] pombe totals are incorrect becasue of PAINT data.

So essentially I want to use the pombe data Midori submitted to GO, which was fine without the PAINT.
Also I'd like all 3 to be done on the same day. Ideally I wanted the number of unknowns to match  with the other figures. This might not be possible but it won't be far off (It doest fully align anyway becasue it uses a slightly different method).

conserved unknown 410
pombe spceific  288
total 698

pombe should match the slim here though:
https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms
Protein coding genes not covered by the slim (718 in total):
Gene products with biological process annotation, but not in any of the categories above: 18
Gene products with no biological process annotation: 700

(we have an off-by 2 error but I'm not worried about that.....)

GO term mapper can be re-run  using the GAF submitted as the annotation file (rather than the  GO database). This should give the correct results, ex PAINT

- [ ] replace the 3  files: 

S_5_pombe_slim.tab
S_6_cerevisiae_slim.tab
S_5_human_slim.tab

The GOslim is also in the SUPPLEMENTAL DATA directory

**Comment by Antonialock** [comment]
I updated S7 and S3 - I keep getting a message that other versions are accessible to collaborators so I have no idea what the folder looks like on your end (it looks good to me - I only have one file per supplementary file)

**Comment by Antonialock** [comment]
Shouldn't there be two files for the slim?

**Comment by ValWood** [comment]
I don't understand what you mean (previous 2 messages).

this folder is shared with you
https://drive.google.com/drive/folders/1pGfAkCdGha6A1-g1UFZZPu42mQBow0nt
can you see it?

**Comment by Antonialock** [comment]
1. Yes I have access. I have updated docs S7 and S3. Every time I make a change in that folder a copy of the old document is spawned. If I delete the copy I’m told that the duplicate file is not deleted at collaborators end so I was wondering what your folder looked like now! I’ve never seen this message before in drive, it is very strange. 


2. Should there be one supp table for the yeast slim and one for the human?

**Comment by ValWood** [comment]
Should there be one supp table for the yeast slim and one for the human?

NO  there is ONLY ONE SLIM,  that's what I keep saying. I wanted to run the same slim for everything, so I just add the additional terms to my slim. We can't do this analyses consistently  if we use separate slims, and do the slimming on different dates.

**Comment by ValWood** [comment]
Please don't change any slims. We shouldn't need to because you already checked that everything slimmed with the previous dataset. I don't understand why we are changing anything now? We had all of the  protien datasets, the slims outputs and the numbers were ready to plug into the graph....

**Comment by Antonialock** [comment]
It wasn’t clear to me which sets to use.

**Comment by ValWood** [comment]
known (GO slim process)
unannotated (unannotated)
unknown (* unslimmed, this is BOTH ND unslimmed and BP not in the slim)

* this is why we needed to check that the  BP not in the slim were really unknown.

**Comment by ValWood** [comment]
duplicate

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/2051
