### ISSUE TITLE
user request to curate 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1988]
Batta G, Szilagyi Z, Laczik M, Sipiczki M.:  " The involvement of the Schizosaccharomyces pombe sep9/spt8 gene in the regulation of septum cleavage. FEMS Yeast Res. 2009 Aug;9(5):757-67. doi: 10.1111/j.1567-1364.2009.00522.x.  in the literature.

**Comment by ValWood** [comment]
PMID: 19473263

**Comment by ValWood** [comment]
and
The pleiotropic cell separation mutation spl1-1 is a nucleotide substitution in the internal promoter of the proline tRNACGG gene of Schizosaccharomyces pombe

**Comment by ValWood** [comment]
@Antonialock did you do this recently PMID: 19473263?  it's curated?

**Comment by ValWood** [comment]
I'll give this one to you since I am been asked for £££ for the paper, even with a VPN connection

https://link.springer.com/article/10.1007/s00294-009-0262-x

**Comment by Antonialock** [comment]
looks like I did PMID: 19473263 early May

**Comment by Antonialock** [comment]
probably just saw it on the tracker but forgot to close the ticket

**Comment by ValWood** [comment]
There is another paper too. She asked for 2

**Comment by Antonialock** [comment]
ah I made a separate ticket so it wouldn't get lost at the bottom of the comments
