### ISSUE TITLE
update doc and FAQ for mating type region

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1996]
It would be useful to have a clearer explanation about what is provided and why. Refs to the organization would also be useful for non-pombe people.

Also, we used to have a more prominent menu ling to "genome regions".
Do we need to add back something similar. The   pages for cen, tel, MT are quite hidden...

**Comment by Antonialock** [comment]
I opened a ticket on the website tracker to link to the online tutorial, I think it's very good.

**Comment by ValWood** [comment]
Great. It would be good also to have the description of what is included in  in the MT regions on the Website somewhere, and in the FAQ.

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/771
