### ISSUE TITLE
HP1 paper PMID: 19111658 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1999]
from
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=130280

The Chp2 paper still has not been curated with the relevant link to SHREC2 complex. I haven't had the chance to curate the Motamedi et al 2008 Mol Cell paper yet, and I know you have a lot to do, but perhaps someone can curate and update this paper before closing this request.

**Comment by ValWood** [comment]
no hurry....

**Comment by mah11** [comment]
https://github.com/geneontology/go-ontology/issues/16400

I'll close this because the rest is done, and I have a note-to-self to reopen the session when the GO:ntr is in.

**Comment by mah11** [comment]
finished off a little while ago but forgot to close this
