### ISSUE TITLE
stalled sessions where we have emailed community curator but not replied

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2001]
these were closed due to rt migration:

PMID:24831008 https://curation.pombase.org/pombe/curs/bf037075feb20f28
PMID:23770679 http://curation.pombase.org/pombe/curs/6c1cc5fd9503d415

**Comment by ValWood** [comment]
Did you re- email then. If so this can close. I will do another round of reminders soon (ish), when we have the strength to deal with them (I already have a big CC backlog...)

**Comment by Antonialock** [comment]
I responded to the tickets encouraging them to submit the sessions to us.
