### ISSUE TITLE
update promoter element genome browser file

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2006]
Apparently the current promoter element file for loading into the genome browser consists of elements matched to:
https://www.pombase.org/browse-curation/dna-binding-sites

This page may be out of date (might be more in SO that we submitted)

update at some point.

**Comment by ValWood** [comment]
The only ones in SO will be the ones that we submitted. I don't think we know any more or I would of added them. Ask Jurg's group to double check.

**Comment by ValWood** [comment]
Maybe we should add another column for the transcription factors?

**Comment by Antonialock** [comment]
I don't think we have maintained that page very well. On a quick look I found these terms that we submitted to SO but are not showing on that page:

AACCCT_box SO:0001901
GATA_box SO:0001840
CArG-box SO:0002156
SHP box SO:0002159

It is possible there are more..

Sorry I don't understand this:
> Maybe we should add another column for the transcription factors?

We could ask Jurgs group for more consensus promoters (Maria might know) but maybe we should add in the known unknowns first to avoid confusion :-)

Is it easy to regenerate this file with additional motifs? @kimrutherford

**Comment by Antonialock** [comment]
(if it is easy to do it would be great to add another track for matched restriction enzyme sites too...I'm sure that would be popular)

**Comment by ValWood** [comment]
> if it is easy to do it would be great to add another track for matched restriction enzyme sites too...I'm sure that would be popular

we need Mark's code to do this, it should be somewhere.

Ideally, we would have  config files to add binding  sites  and restriction sites.
The code would need to be rerun to generate new features when we added new sites.

**Comment by ValWood** [comment]
Sorry I don't understand this:

>Maybe we should add another column for the transcription factors?

a column for the TF(s) which bind to the motif?

**Comment by mah11** [comment]
> Is it easy to regenerate [the DNA binding sites] file with additional motifs?

It's a static page, so yes. Edit at https://github.com/pombase/website/blob/master/frontend/src/docs/browse-curation/dna-binding-sites.md, or open a website ticket with the content you want and Kim or I can do it.

> it would be great to add another track for matched restriction enzyme sites too

There's a ticket open for that: https://github.com/pombase/website/issues/35

**Comment by ValWood** [comment]
Antonia means to add the new motifs to the search  for the browser track I think?

**Comment by ValWood** [comment]
Kim can you see anything? Other wise I can contact Mark.....

**Comment by ValWood** [comment]
I asked Mark anyway. Saves hunting...

**Comment by ValWood** [comment]
So  if you have added all known motifs to the website page this can close.

**Comment by ValWood** [comment]
add another coloum
known binding proteins (or simiilar)

e.g

cyclic AMP response element (CRE) | TGACGTCA | SO:0001843 | pcr1
FLEX_element | GTAAACAAACAAAM | SO:0001846 | fkh2
pombe cell cycle box (PCB) | GNAACR | SO:0001871 |fkh2

Then could hyperlink to gene pages.

M26_binding_site (SO:0001900) is missing is also bound by pcr1


-- | -- | --



(might need to be comma separated as could be more than one?)


-- | -- | --

**Comment by ValWood** [comment]
double check everything is covered by  grepping out SO extensions from gaf

**Comment by ValWood** [comment]
Announce when the track is updated with the new motifs.
Remind people about the TF motif static page.
Ask if there are any known motifs we have missed (or if people would suggest a relaxed or otherwise improved consensus  for any of these)

**Comment by ValWood** [comment]
Afterthought:

We could ask people if there are any motifs missing , or need improving *BEFORE* Kim runs the script.

 - [ ]  1. A short announcement reminding people of the track, and the list, ask for additions/improvements

- [ ]  Announce when updated

Save running it twice

**Comment by mah11** [comment]
Reminder: if the static web page needs any changes, please open a website ticket for them.

Re this:

> Ask if there are any known motifs we have missed (or if people would suggest a relaxed or otherwise improved consensus for any of these)

The consensus sequences on the page all come from the linked SO entries, and we should submit any suggested changes to SO to keep consistent. I'd even go so far as to say we shouldn't change our page until SO gets updated, rather than display a sequence that doesn't match what SO has.

**Comment by ValWood** [comment]
@Antonialock  could you migrate the summary of this ticket to the website tracker.
thanks
Val

**Comment by Antonialock** [comment]
val I checked this page
https://www.pombase.org/term/GO:0003676

I think the list is complete insofar the annotation is complete
