### ISSUE TITLE
New sysIDs ncRNAs eser et al

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2008]
Making a ticket so that this doesn't get lost in my email.

Check if we want to make new sys IDs.

From Val (in exchange with Jurg):
If they want  to supply the new (unique)  ncRNAs they would need to supply  the number of features so  we can supply gene IDs. They would then need to supply the features standard  in a genome  exchange format.

We should remind people  (and reviewers) to ensure that  IDs should be obtained  for new features.

PMID:26883383

**Comment by Antonialock** [comment]
if we do something with this, then it is dependant on #2007

**Comment by ValWood** [comment]
What is the action here, I forgot?

**Comment by Antonialock** [comment]
first resolve #2007
then I guess approach them to see if they want the info loaded

**Comment by ValWood** [comment]
closing this as   it should be in the "browser datasets to host" I will open a new ticket listing all of the datasets that will affect gene structure boundaries
