### ISSUE TITLE
note, relation is directly_positively_regulates, not directly activates

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2012]
@Antonialock 
warning in c3f91b7bec8a34a1: directly_activates() not allowed for molecular_function
warning in 7537db502e936856: directly_activates() not allowed for molecular_function
warning in 7537db502e936856: directly_activates() not allowed for molecular_function
warning in 7537db502e936856: directly_activates() not allowed for molecular_function
warning in a8928db520ace5a9: directly_activates() not allowed for molecular_function

**Comment by ValWood** [comment]
fixed

**Comment by ValWood** [comment]
(directly activates is display label)

**Comment by ValWood** [comment]
warning in e58982138a6526c3: directly_activates() not allowed for molecular_function
warning in 98f0242de16564e8: directly_activates() not allowed for molecular_function
warning in 98f0242de16564e8: directly_inhibits() not allowed for molecular_function
warning in abf32a065b08bcd5: directly_activates() not allowed for molecular_function

**Comment by ValWood** [comment]
done

**Comment by Antonialock** [comment]
ok cheers
