### ISSUE TITLE
malformed terms in artemis

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2015]
- [x] disease association, ribosomopathy | PBO:0086309 | SPAC1687.01,SPBC1289.07c
- [x] disease association, Treacher Collins syndrome | PBO:0086308 | SPAC1687.01,SPBC1289.07c

- [x] endoplasmic reticulum organization | PBO:0086456 | SPAC23C11.01

- [x]  homologous to S. cerevisiae YIL124W | PBO:0086220 | SPAC977.08

- [x]  gene name description?
Lipid Transfer at Contact site | PBO:0087200 | SPBC20F10.07

- [x] no apparent S. cerevisiae ortholog | PBO:0011426 | SPAC23H4.16c

- [x]  orthologous to S. cerevisiae YDL168W | PBO:0086880 | SPBC1198.01

**Comment by ValWood** [comment]
@Antonialock 

can you see what is wrong here?
I can't...

/controlled_curation="term=disease association, Treacher Collins syndrome; date=20171010"
/controlled_curation="term=disease association, ribosomopathy; date=20171010"

**Comment by ValWood** [comment]
rpc19 &rpc40

**Comment by Antonialock** [comment]
yeah it needed fixing from disease association to disease associated

**Comment by Antonialock** [comment]
looks like everything done..

**Comment by ValWood** [comment]
weird, I thought I checked what we used....

**Comment by ValWood** [comment]
Ah we use "disease associated " here:
https://www.pombase.org/query
All disease associated genes

doh
