### ISSUE TITLE
cdc10, cdc18, cdc22 expression

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2017]
so I don't forget:

- [x] cdc10, txn present during  mitosis metaphase
- [x] cdc18  txn present during  mitosis metaphase
cdc22  txn present during  mitosis metaphase
- [x] cdc18   protein absent during metaphase, 
- [x] cdc18  protein increased during G1
- [x] cdc18  protein absent in G2

**Comment by ValWood** [comment]
I'll save these to test 
https://github.com/pombase/canto/issues/1491

**Comment by ValWood** [comment]
but which flippin paper???

**Comment by JackyVH** [comment]
It’s PMID 9755169

**Comment by ValWood** [comment]
/controlled_curation="term=gene expression, RNA level; qualifier=present; annotation_extension=during(GO:0000089) db_xref=PMID:9755169; date=20190514"

**Comment by ValWood** [comment]
DOne, Thanks @JackyVH !

**Comment by ValWood** [comment]
Committed revision 5570.
