### ISSUE TITLE
characterisation status question

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2019]
@Antonialock @mah11 

did anyone remove any thing from

characterisation_status_Schizosaccharomyces_pombe_specific_protein_uncharacterized OR subset: characterisation_status_Schizosaccharomyces_specific_protein_uncharacterized

last week?

**Comment by mah11** [comment]
no, I never touch those

**Comment by ValWood** [comment]
Also conserved in  vertebrates went up by one. What was added?
@Antonialock ?

Please let me know status changes or record them in the tracker. They are relatively rare  now...

**Comment by Antonialock** [comment]
Not me..

**Comment by ValWood** [comment]
OK weird.... I don't *remember* changing any. Maybe I did....

**Comment by Antonialock** [comment]
A "short" amount of time can be surprisingly difficult to remember xD. Please don't ask me what happened last week. Or yesterday.

**Comment by ValWood** [comment]
My memory is shot.... I only remember it is it is written down...
