### ISSUE TITLE
pmo25 isn't a protein kinase?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2023]
https://www.pombase.org/gene/SPAC1834.06c

**Comment by ValWood** [comment]
@mah11  was this assayed for protein kinase activity on it's own? It seems odd because its an Armadillo repeat  protein (I  have never seen any evidence for catalytic activity for this domain)
https://www.pombase.org/gene_subset/interpro:IPR016024

Some of the proteins do have catalytic activity but it is always in another domain.

So I wonder if this was not  a clean purfication...or something....

**Comment by ValWood** [comment]
Correction out  of 130 Armadillo, only this one is catalytic
https://www.pombase.org/gene/SPAC30C2.02
It has  an insertion  where the catalytic activity resides.

This looks like a canonical Armadillo though. No room for a protein kinase domain.

**Comment by mah11** [comment]
Wow, I forgot that I'd done this paper.

They IP'd GFP-tagged Pmo25 and did in vitro kinase assays. I deleted the GO annotation anyway, since they don't rule out another protein staying bound.

**Comment by ValWood** [comment]
old papers..........
