### ISSUE TITLE
mei4  and others 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2024]
has

regulation of transcription from RNA polymerase II promoter involved in meiotic cell cycle

I was trying to establish if -ve or -ve (the annotation  are a bit of a mixed bag)

but there is no annotated phenotype that this GO term is derived from?
https://www.pombase.org/reference/PMID:25492408

Also here
PMID:26804917
can the "regulation of meitotic cell cycle" annotations  be +ve or -ve?

What is really being regulated here ? is it entry into the meiotic cell cycle?

**Comment by Antonialock** [comment]
changed term.
