### ISSUE TITLE
pom1 Noctua model sub ticket

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2027]
pom1 has the MF
 protein serine/threonine kinase activity
has substrate cdr2, involved in negative regulation of protein localization to cell tip 

this doesn't really make sense 'as a sentence'. It would sound more correct to say
negative regulation of protein localization to cell tip 
has regulation target cdr2

On the MF it should be enough to say
protein serine/threonine kinase activity
has substrate cdr2, involved in negative regulation of G2/M

**Comment by Antonialock** [comment]
also
 has substrate cdr2 involved in positive regulation of G2/M transition of mitotic cell cycle
has snuck in

**Comment by ValWood** [comment]
I think it's important to capture the fact that the regulation is via "regulation of localization"

I'm sure there will be a better way to do this. It's sort of on my radar,  way out....

I agree that in these cases  
negative regulation of protein localization to cell tip
has regulation target cdr2
sounds better so maybe you can open a ticket to change the default display order in these cases.
You will need to look if this applies to other   "regulation target" terms...

I agree that  it's probably good to just have the  
has substrate cdr2, involved in negative regulation of G2/M
on the MF, although previously I always tried to  put connections on the MF where possible.

Lots to discuss here! 

Maybe we need to CAM model some of this and see which terms/extensions come out....

(BTW (and @mah11) there is a new Noctua quick add interface which circumvents the need to do  all the clicking...... I suggested to get rid of the clicking interface altogether and just    go from annotation-> drawing the model but that  wasn't well received ;)

...yet :)

**Comment by Antonialock** [comment]
> I think it's important to capture the fact that the regulation is via "regulation of localization"

yes I agree, I just think that this annotation makes sense.

The annotations says:
"when pom1 phosphorylates cdr2, some protein will not go to the cell tip"
which protein?
how is this a useful annotation?

**Comment by Antonialock** [comment]
on the other hand if you annotate pom1 to "

negative regulation of protein localization to cell tip, regulates cdr2

then this would be read as:
pom1 negatively regulates the localization of cdr2 to the cell tip

**Comment by Antonialock** [comment]
I guess it could be useful if we could nest the extensions?
e.g.
protein kinase activity, phosphorylates cdr2, involved in protein localization to cell tip, localizes cdr2

?

**Comment by ValWood** [comment]
> negative regulation of protein localization to cell tip, regulates cdr2

yes, this is clearer, can you fix

**Comment by ValWood** [comment]
We'll kick of the curator meeting with this as an example, for the network building.
How we should model it 

This is a nice summary of the output of pom1-crd2 signalling

Pom1 directly phosphorylates Cdr2 to inhibit mitotic entry through Wee1. This modification inhibits node assembly and prevents the activating kinase Ssp1 from phosphorylating the Cdr2 activation loop (Moseley et al., 2009; Bhatia et al., 2014; Deng et al., 2014; Rincon et al., 2014; Guzmán-Vendrell et al., 2015; Kettenbach et al., 2015).

**Comment by ValWood** [comment]
currentky

protein serine/threonine kinase activity
--
  | directly inhibits cdr2 involved in negative regulation of G2/M transition of mitotic cell cycle
  | has substrate cdr2 involved in negative regulation of protein localization to cell tip
  | has substrate pom1 involved in negative regulation of protein localization to plasma membrane

What its really doing to inhibit G2/M is preventing 
cdr2 node accumulation at the medial region
(the other stuff is true but incidental?)

**Comment by ValWood** [comment]
This is OK now as the target is only on the process.

We  only need to capture localization until we can get the annotation onto the MF term with 
either "recruitment" by modified form.
