### ISSUE TITLE
remove endopeptidase from proteasome regulatory particle

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2031]
- [x] mts4 | SPBP19A11.03c | 19S proteasome regulatory subunit Rpn1/Mts4
- [ ] rpn11 | SPAC31G5.13 | 19S proteasome regulatory subunit Rpn11
- [x] rpn2 | SPBC17D11.07c | 19S proteasome regulatory subunit Rpn2
- [x] rpt3 | SPCC576.10c | 19S proteasome regulatory subunit Rpt3
- [x] rpt4 | SPCC1682.16 | 19S proteasome regulatory subunit Rpt4
- [x] rpt6 | SPBC23G7.12c | 19S proteasome regulatory subunit Rpt6

**Comment by ValWood** [comment]
/GO="aspect=F; term=proteasome-activating ATPase activity; GOid=GO:0036402; evidence=ISM; db_xref=GO_REF:0000024; with=InterPro:IPR003960; date=20180611"

- [ ] rpt1
- [ ] rpt2
- [ ] rpt3
- [ ] rpt4
- [ ] rpt5
- [ ] rpt6

**Comment by mah11** [comment]
The db_xref to use for ISM is GO_REF:0000050.

**Comment by ValWood** [comment]
fixed ref

**Comment by ValWood** [comment]
rpn is actually a  peptidase...

thiol-dependent ubiquitin-specific protease activity
