### ISSUE TITLE
add allele to unmapped genes

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2034]
add srs1 PMID:9651503

to https://www.pombase.org/status/unmapped_genes

I'm unsure if this is https://www.pombase.org/gene/SPAC29A4.15 (can't find any evidence for it) have asked Val, will close if she says they are the same.

**Comment by ValWood** [comment]
A different srs1...I'm not sure what srs is on the genetic map (something 'sensitive'?),
but it's not related to the tRNA synthase name....

**Comment by Antonialock** [comment]
suppressor of ras and ste9 :-)

**Comment by mah11** [comment]
moved to https://github.com/pombase/website/issues/798 because this is a website change
