### ISSUE TITLE
DNA binding motifs completeness

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2038]
- [x] Once the DNA binding motif page ahs updated with today's amendments, ask on pombelist if there are more known motifs or if the consensus sequences should be tweaked, or if relaxed/strict motifs can be added.

- [x] Add Zas1 binding site (Y)CCCCAY (needs a new SO term based on PMID:29735745

outstanding from #2006

**Comment by Antonialock** [comment]
@kimrutherford could you do another update? I fixed some typos

**Comment by kimrutherford** [comment]
> could you do another update? I fixed some typos

Should be there now.

**Comment by Antonialock** [comment]
Thanks!

**Comment by ValWood** [comment]
zas1 binding site now included

https://github.com/pombase/website/issues/802
can proceed

**Comment by ValWood** [comment]
note to self, add to session

i'll do this in a minute

**Comment by ValWood** [comment]
done
