### ISSUE TITLE
transcription overhaul continued

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2048]
from
https://github.com/pombase/curation/issues/2025

I'm trying to figure out  how teb1 should be decribed.

Do these experiemenst show that teb binds directly to  AACCCT_box? or is it chip data?
https://www.pombase.org/reference/PMID:23314747

It seems odd, because the TF that it recruits  (ams2) binds this motif?
Do they both bind directly to this motif at the same time?

**Comment by Antonialock** [comment]
see
https://github.com/pombase/curation/issues/1543
