### ISSUE TITLE
preparing final histogram

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2051]
Once 
https://github.com/pombase/curation/issues/2050
is resolved, and  you are using an ID set that  will slim properly

Here is how the numbers  output by the Term Mapper  should be used in the histogram

1. These 2763 identifiers were found to be unannotated:

(this number is UNANNOTATED in the graph)

2
i) These 607 identifiers were not annotated in the slim, but they had non-root annotations that were not in the slim:

ii)  These 218 identifiers had no non-root annotations: 

(add these two number together, this is UNKNOWN in the graph)

3. Add all three numbers together and subtract from your total protein number.
This figure is “known”  "i.e. slimmed".

Try not to add any terms to the slim, but if you need to document them here.
Also document which ID set you used (both as input and which one you selected from the GO term mapper options)

**Comment by ValWood** [comment]
replaces 
https://github.com/pombase/curation/issues/2016

**Comment by Antonialock** [comment]
Q2. 
I have for example

**Comment by Antonialock** [comment]
Q2.
I have for example:

C-terminal protein   lipidation
inositol phosphate metabolic process

included in my slim list (you told me to include them in ticket #1960) but they are not incldued in the slim shown in supp fig 4 ?
https://docs.google.com/document/d/1HtoyUcOlT99v2ot8UISVT76Fn_hCXcAnGf2Q1MNQ-jw/edit

**Comment by ValWood** [comment]
Q1.
why does it look like there are redundant terms in your slim?
e.g. transmembrane transport is redundant with transport
regulation of transcription, DNA templated is redundant with transcription, DNA templated
meiotic nuclear division is redundant with reproductive process


I'll remove the  redundant ones at the end (I forgot), but it's useful to keep them there until we ar sure these iterations are finished

**Comment by ValWood** [comment]
>included in my slim list (you told me to include them in ticket #1960) but they are not incldued in the slim shown in supp fig 4 ?
https://docs.google.com/document/d/1HtoyUcOlT99v2ot8UISVT76Fn_hCXcAnGf2Q1MNQ-jw/edit

they should be that is a msitake.
but this file has almost 200 IDs in it now! it isn't the one I made????????

**Comment by Antonialock** [comment]
the slim I've been using has around 100 so it isn't mine.

**Comment by ValWood** [comment]
When I added  your extra terms to my slim I only had 53 terms. 
I think we need to start again here.....

**Comment by ValWood** [comment]
closing, will open a new ticket in a minute
