### ISSUE TITLE
sxa1 is it involved in conjugation?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2059]
shouldn't this have a conjugation annotation?

**Comment by Antonialock** [comment]
not sure, there's contradicting evidence

**Comment by Antonialock** [comment]
http://www.biochemsoctrans.org/content/25/2/229S.long

suggests that it could be indirect effect, it doesn't seem to process pheromone directly

**Comment by ValWood** [comment]
But this is only saying  that it does not process the pheromone. There are many ways a protease could affect conjugation. There is quite a strong conjugation specific phenotype?

**Comment by ValWood** [comment]
Actually here, there is a "conjugation" annotation for sxa2
https://www.pombase.org/reference/PMID:1549128
but for sxa2. What is the difference? phenotypes are similar?

**Comment by ValWood** [comment]
But isn't rearranging the cell wall in the Shmoo tip part of conjugation?
The Davy paper could provide a NOT annotation for pheromone processing maybe?

We can't really annotate one gene with a process based on phenotype, and not annotate another gene with the same phenotype becasue of information in another paper.  Otherwise it isn't possible to know why?

**Comment by Antonialock** [comment]
sxa2 directly degrades P-factor - I dont know what sxa1 degrades

**Comment by ValWood** [comment]
ok!
