### ISSUE TITLE
adding "during" extensions to processes

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2060]
Do we need to add  config options to allow this.... ( I didn't look yet, this is just a placeholder from testing)

**Comment by ValWood** [comment]
GO:0006325      is_a    happens_during  GO:0022403|GO:0033554   happens during (e.g. cell cycle phase or stress response)               0,1     user
GO:0007165      is_a    happens_during  GO:0033554      happens during (e.g. stress response)           0,1     user
GO:0071554      is_a    happens_during  GO:0022403|GO:0033554   happens during (e.g. cell cycle phase or stress response)               0,1     user
GO:0007010      is_a    happens_during  GO:0022403|GO:0033554   happens during (e.g. cell cycle phase or stress response)               0,1     user
GO:0061024      is_a    happens_during  GO:0022403|GO:0033554   happens during (e.g. cell cycle phase or stress response)               0,1     user
GO:0006913      is_a    happens_during  GO:0022403|GO:0033554   happens during (e.g. cell cycle phase or stress response)               0,1     user
GO:0030163      is_a    happens_during  GO:0022403|GO:0033554   happens during (e.g. cell cycle phase or stress response)               0,1     user
GO:0070647      is_a    happens_during  GO:0022403|GO:0033554   happens during (e.g. cell cycle phase or stress response)               0,1     user
GO:0032200      is_a    happens_during  GO:0022403|GO:0033554   happens during (e.g. cell cycle phase or stress response)               0,1     user
GO:0006351      is_a    happens_during  GO:0022403|GO:0033554   happens during (e.g. cell cycle phase or stress response)               0,1     user

**Comment by ValWood** [comment]
I don't know why we only have this subset. I wonder if we should move to "biological process" maybe this isn't appropriate?
If not we should all look for other places it could be added...It's useful to get the temporal info, especially as the info accumulates.

**Comment by ValWood** [comment]
Can we have "phase terms" always allowable (for terms we use)
I'm not sure what the configuration file has at the moment, this ticket might be our of date...

**Comment by mah11** [comment]
I didn't work on these (Val, you did all of the GO extension config originally), so I don't know why the GO terms that have happens_during entries were selected.

I have changed it so any biological process can have "during x cell cycle phase" or "during response to y" extensions. I commented the previous entries out so they can be restored easily if the updated config doesn't work out well.
