### ISSUE TITLE
cdr2 pom1 axis

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2069]
have I questioned this before?

has substrate cdr2 involved in positive regulation of G2/M transition of mitotic cell cycle

pom1 negatively regulates G2/M?

**Comment by ValWood** [comment]
It seems that you spotted it here, but didn't fix it yet:
https://github.com/pombase/curation/issues/2027

**Comment by ValWood** [comment]
combining from

https://github.com/pombase/curation/issues/2068

probably the same paper

Cdr2 is activated by phosphorylation of threonine 166 (T166) by the kinase Ssp1, and levels of Cdr2-pT166 increase with cell size (Deng et al., 2014).

we have the substrate but not "directly activatates"

or the residue, activated by

note: you can also now add residue to phosphorylation changes

**Comment by Antonialock** [comment]
done
