### ISSUE TITLE
qualifier= field

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#208]
These are the remaining qualifiers:

c  |          value           |                name  
-----+--------------------------+------------------------------------

Need to decide what to do with these:

219 | required                 | biological_process
79 | same_pathway             | biological_process 
53 | region                   | sequence 
47 | different_pathway        | biological_process   
~33 | cancer_census            | disease_associated~
21 | predominantly            | cellular_component
18 | acts_downstream_of       | biological_process
18 | redundant_with           | biological_process
17 | acts_upstream_of         | biological_process
~13 | activates                | biological_process~
11 | constitutive             | cellular_component
7 | partially_redundant      | biological_process
~4 | antagonistic_interaction | biological_process~
4 | major                    | molecular_function
4 | minor                    | molecular_function
3 | partially_redundant      | molecular_function  
~2 | constitutive             | molecular_function~
~2 | weak                     | fission_yeast_phenotype~
~1 | inhibits                 | PSI-MOD~

We should keep these

49 | heterologous_system      | cellular_component
69 | heterologous_system      | molecular_function
100 | heterologous_system      | biological_process

We need these until there is a way to split these genes into their constiuent peptides:

8 | N_term                   | molecular_function
7 | N_term                   | cellular_component
18 | C_term                   | molecular_function
6 | C_term                   | biological_process
6 | N_term                   | biological_process
4 | C_term                   | cellular_component

Allowed for GO
263 | contributes_to           | molecular_function
40 | colocalizes_with         | cellular_component

Documented for gene expression:
2 | present                  | gene_ex
4 | decreased                | gene_ex
24 | increased                | gene_ex

Documented for complementation
9 | full                     | complementation
9 | partial                  | complementation

These are attached to the extension rather than the term?? There is a SF chado load tracker item about this, follow up with Kim
9 | decreased                | PomBase annotation extension terms
11 | contributes_to           | PomBase annotation extension terms
7 | required                 | PomBase annotation extension terms
6 | inhibits                 | PomBase annotation extension terms
68 | increased                | PomBase annotation extension terms
25 | present                  | PomBase annotation extension terms
10 | absent                   | PomBase annotation extension terms
10 | unchanged                | PomBase annotation extension terms
2 | constitutive             | PomBase annotation extension terms
2 | same_pathway             | PomBase annotation extension terms
3 | activates                | PomBase annotation extension terms  

Original comment by: ValWood

**Comment by ValWood** [comment]
@kimrutherford  do we have a list of qualifers used currently somewhere?

**Comment by kimrutherford** [comment]
Is this what you need?: https://curation.pombase.org/dumps/builds/pombase-build-2019-11-24/logs/log.2019-11-24-21-56-54.qualifier_counts_by_cv

**Comment by ValWood** [comment]
Yes thanks. We have dealt with some already.

For GO we will keep
 74 | heterologous_system   | biological_process
 60 | heterologous_system   | molecular_function
 42 | heterologous_system   | cellular_component
(don't do any harm, used with IGI and other organism)

9 | C_term                | molecular_function
7 | C_term                | biological_process
7 | N_term                | molecular_function
4 | N_term                | cellular_component
4 | N_term                | biological_process
3 | C_term                | cellular_component
(until we have IDs for parts)

These might be useful for epistasis
50 | same_pathway          | biological_process
 7 | different_pathway     | biological_process
10 | redundant_with        | biological_process
 3 | partially_redundant   | biological_process

Some of these can probably go
 65 | required              | biological_process
 11 | predominantly         | cellular_component
 6 | acts_downstream_of    | biological_process
 6 | acts_upstream_of      | biological_process
 4 | major                 | molecular_function
 3 | minor                 | molecular_function
 1 | activates             | biological_process

**Comment by ValWood** [comment]
These aren't doing any harm. I made notes in "future doc" where things might be useful later.
