### ISSUE TITLE
crazy protein, SPBPJ4664.02

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2083]
http://pombase-dev.bioinformatics.nz/reference/PMID:29844133

mentions "crazy protein", in the abstract, but no annotation to this...

**Comment by ValWood** [comment]
Crazy protein, if you never saw it:


NSSTPITSSSVLNSSTPITSSSILNTSTPITSSSVLNSSTPI
TSSSILNSSTPITSSTVLNSSTPITSSTALNTSTPITSSSVLNSSTPITSSSVLNSSTPI
TSSTVVNTSTPITSSTVVNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTALNTSTSI
TSSSVLNSSTPITSSTVVNTSTPITSSSVLNSSTPITSSTVVNTSTPITRYSVLNSSTPI
TSSTVLNSSTPITSSSVLNSSTPITSSTALNTSTPITSSSVLNSSTPITSSSVLNSSTPI
TSSTALNTSTPITSSSVLNSSTPITSSTALNTSTPITSSSVLNSSTAITSSTALNTSTPI
TSSSVLNSSTPITSSTALNTSTPITSSSVLNSSTPITSSSILNSSTPITSSSVLNSSTPI
TSSTVVNTSTPITSSSVLNSSTPITSSTVLNSSTPITSSSVLNSSTPITSSTVVNTSTPI
TSSTVVNSSTPITSSSVLNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTVVNTSTPI
TSSTVVNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTGLNTSTPITSSSVLNSSTPI
TSSTVLNSSTPITSSTALNTSTPITSSSVLNSSTPITSSSVLNTSTPITSSSVLNSSTAI
TSSTALNTSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPITSSTALNTSTPI
TSSSVLNSSTPITSSTVLNSSTPITSSSVLNSSTPITSSTVVNTSTPITSSTALNTSTPI
TSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPITSSTVVNTSTPITSSTVVNTSTPI
TSSTVVNSSTPITSSTVLNTSTPITSSSVLNSSTPITSSSILNSSTPITSSSVLNSSTPI
TSSTVVNSSTPITSSTALNTSIPITSSSVLNSSTPITSSTALNTSTSITSSSVLNSSTPI
TSSTVVNTSTPITSSSVLNSSTPITSSTVVNSSTPITSSTVVNTSTPITSSTVVNTSTPI
TSSTVVNSSTPITSSTVLNSSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPI
TSSTVVNTSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPITSSTVVNTSTPI
TSSTVVNTSTPITSSTVVNSSTPITSSTVLNTSTPITSSSVLNSSTPITSSSVLNSSTPI
TSSTVVNTSTPITSSSVVNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTALNTSTPI
TSSSVLNSSTPITSSTVLNSSTPITSSTALNTSPPITSSTVVNSSTPITSSTVVNTSTPI
TSSTVVNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPI
TSSTVVNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTALNTSTPITSSSVLNSSTPI
TSSTALNTSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPITSSTALNTSTPI
TSSSVLNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTVLNSSTPITSSTALNTSTPI
TSSSVLNSSTPITSSSVLNSSTPITSSTVVNSSTPITSSSVLNSSTPITSSTALNTSTPI
TSSSVLNSSTPITSSSVLNTSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPI
TSSTALNTSTPITSSSVLNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTVLNSSTPI
TSSTALNTSTPITSSSVLNSSTPITSSSVLNSSTPITSSTVVNSSTPITSSSVLNSSTPI
TSSTALNTSTPITSSSVLNSSTPITSSTVVNSSTPITSSTVVNTSTPITSSTVVNTSTPI
TSSTVVNSSTPITSSTVLNSSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPI
TSSTVVNTSTPITSSTVVNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTVVNTSTPI
TSSSVLNSSTPITSSTVVNTSTPITSSTALNTSTSITSSSVLNSSTPITSSTVVNTSTPI
TSSSVLNSSTPITSSTVVNTSTSITSSSVLNSSTPITSSSVLNSSTPITSSTVVNSSTPI
TSSSVLNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPI
TSSTVLNSSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPITSLTALNSSTPI
TSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPITSSTALNTSTPITSSSVLNSSTPI
TSSTALNTSTSITSSSVLNSSTPITSSTVVNTSTPITSSSVLNSSTPITSSTVVNTSTPI
TSSTVVNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTVVNTSTPITSSSVLNSSTPI
TSSTVVNTSTPITSSTALNTSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPI
TSSTVLNSSTPITSSSVLNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTALNTSTSI
TSSSVLNSSTPITSSTVVNTSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPI
TSSTALNTSTPITSSSVLNSSTPITSSTALNTSTSITSSSVLNSSTPITSSTVVNTSTPI
TSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPITSSTALNTSTPITSSTVLNSSTPI
TSSSVLNSSTPITSSTALNTSTPITSSSVLNSSTAITSSSIVNSSTPITSSSVLNSSTAI
TSSSILNSSTPITSSSILNSSTPITSSTVVNSSTPITSSTTLNTSTPITSSSVLNSSTAI
TSSSIVNSSTPITSSSVLNSSTPITSSTTLNTSTPITSSSVLNSSTAITSSSVLNSSTPI
TSSSVLNSSTPITSSTVVNTSTPITSSSVLNSSTPITSSTVVNTSTPITSSTVVNSSTPI
TSSTTLNTSTPITSSSVLNSSTAITSSTALNTSTPITSSSVLNSSTAITSSSILNSSTPV
TSSSVLNSSTPITSSTVVNSSTPITSSTALNTSTPITSSSVLNSSTPITSSTVVNSSTPI
TSSTALNTSTPITSSTVVNSSTPITSSSVLNSSTAIASSSILNSSTPITSSSVLNSSTPI

**Comment by kimrutherford** [comment]
The "Protein features" section of the gene page doesn't look great: https://www.pombase.org/gene/SPBPJ4664.02

**Comment by ValWood** [comment]
you should have seen it when we included prints. it was about 2 miles long!

Ideally these repeats would not b in the domain database. They represent a domain made from a set of repeats (threre are 33 repeats  PITSSTALNTST IIRC) . I keep trying to get Pfam to remove it, but without success. Anyway we can live with it like this, hopefully I will sort it eventually.

**Comment by Antonialock** [comment]
love it! We should name it before someone names it something boring..

**Comment by ValWood** [comment]
I want to put "crazy protein" in the product line ,even if only temporarily, to draw attention to it ;)

**Comment by ValWood** [comment]
I had had people mail me over the years asking if I have seen SPBPJ4664.02
and saying is this a mistake. Nope.

**Comment by ValWood** [comment]
actually it's ~250-270 copies of a 12 AA repeat, NSSTPITSSSIL not 33 copies...

**Comment by kimrutherford** [comment]
> I want to put "crazy protein" in the product line ,even if only temporarily, to draw attention to it ;)

I'll post a screenshot to Twitter if you do.  :-)

**Comment by ValWood** [comment]
will be called  "crazy cell surface glycoprotein" tomorrow

Could tweet a challenge

"can any organism beat out most repetitive protein over 250 copies of a NSSTPITSSSIL repeat"

Include something like
![screenshot](https://user-images.githubusercontent.com/7359272/43256733-a176ebc0-90c5-11e8-89ec-10cf1ccf46b5.jpg)
 as the background ;)

**Comment by kimrutherford** [comment]
I tweeted that with slightly different wording: https://twitter.com/PomBase/status/1022731248194600960

**Comment by ValWood** [comment]
cool!

**Comment by kimrutherford** [comment]
The tweet has been very popular.

Do you know the answer to this?: https://twitter.com/DPMelters/status/1023023636461101056

**Comment by kimrutherford** [comment]
Now up to 32 retweets and 93 likes!  And a bunch of comments.

**Comment by Antonialock** [comment]
You  are trending Kim  :-)
-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by kimrutherford** [comment]
> You are trending Kim :-) 

It's by far the most popular thing I've ever posted.  :-)

The post in October announcing the new website only got 7 retweets and 12 likes.

**Comment by kimrutherford** [comment]
> I want to ask Snezhana about this on Monday

Thanks.  In the meantime, should I reply and say "We don't think there are orthologs in the other Schizosaccharomyces"?

> we can do one of these a week!

Yep!  I think an occasional post about in interesting or weird gene would be great.  I think we should post more papers too.

**Comment by Antonialock** [comment]
did number of followers spike at all?

**Comment by kimrutherford** [comment]
> did number of followers spike at all?

I little bit - there are 12 new followers in the last 2 days.

**Comment by ValWood** [comment]
You can say
"Many paralogous cell surface protein  have similar but non identical S/T rich repeats
but ’crazy’ has not direct orthologs in other Schizos.

**Comment by ValWood** [comment]
could also post the ensembl synteny view 

and appears to be a  synteny breakpoint

(also note corrected above before posting)

**Comment by ValWood** [comment]
I have always thought that there is a mechanism to generate these ST repeat proteins in certain genomic regions...

**Comment by kimrutherford** [comment]
Thanks I replied to the question.

Here are the current stats.  We should definitely do more of this.  At least 15 new followers too.

![twitter-crazy-protein-stats-1](https://user-images.githubusercontent.com/90474/43371077-af099104-93de-11e8-8bc6-818e4a80031d.png)
