### ISSUE TITLE
response to caffeine (2), fix

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2088]
e.g.
GO:1901181 | negative regulation of cellular response to caffeine | IMP | Castillo EA et al. (2003)

phenotypes?

**Comment by ValWood** [comment]
only 1 annotation now

hba1 | SPBC365.13c | Ran GTPase binding protein Hba1
-- | -- | --

**Comment by Antonialock** [comment]
yeah response to caffeine isn't a thing in itself. Guess it is the oxidative stress response somehow.  removed.
