### ISSUE TITLE
Cdc42 Gefs localization

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2098]
Both Scd1 and Gef1 have been described to localize to the cell midzone during cytokinesis and to the cell tips during interphase (Coll et al., 2003; Das et al., 2009, 2015; Hirota et al., 2003; Kokkoris et al., 2014; Vjestica et al., 2013).

@Antonialock  you curated the  Das paper which has a lot of cell tip localizations.

Could you go in and add "during interphase" to these (where possible). The  temporal info from the phases is always required for  any  localization related to polarity etc)

**Comment by Antonialock** [comment]
added during g2

**Comment by Antonialock** [comment]
(mitotic)
