### ISSUE TITLE
After UPDATE; sort pseudogenes

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#21]
Original comment by: ValWood

Some pseudogenes have changed status and need "warning, previously annotated as pseudo"
and GO annotation.

If a gene has a single frameshift, it probably isn't good to represent them as pseudo genes, make "valid translations" for these, removing the psudo label and flagging as 
"
warning, possible frameshift
warning, previously annotated as pseudo
(they may be problems in the sequenced stain and some are problems with the sequence)

This way people will see them in the gene set if they are tring to do comparisons with other strains, or octosporus, japonicus etc. Adding the pseudo flag makes them less visible by excluding them from the protein set....

**Comment by mah11** [comment]
flagging for discussion because I don't understand what the task is, and the file said to be attached is apparently long gone

**Comment by ValWood** [comment]
revisit after the update when some will probably be resolved....

**Comment by ValWood** [comment]
We need a plan for this in the first instance. It isn't a big task, but it isn't clear what we should do...

**Comment by ValWood** [comment]
See "future"
