### ISSUE TITLE
klp9 missing phosphorylation data

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2113]
Phosphoproteomic studies have revealed that Klp9 contains four phosphorylation sites (S596, S598, S605, and S611) for Cdk1/Cdc2 kinase in its C-terminal 38 amino acids (Chen et al., 2013).

PMID: 23297348

**Comment by mah11** [comment]
What is the task?

**Comment by ValWood** [comment]
The paper I was reading  mentions that those phospho residues are reported in Chen et al.
They aren't curated (although PMID: 23297348 is through canto).

It is quite possible they provided the incorrect ref.....

**Comment by mah11** [comment]
Ah. Before I asked, I looked at the Canto session, and it has oodles of modifications curated, mostly by Jun-Song (with a handful of additions by Antonia, presumably during approval). It would be a little suprising if they both missed something well-supported.

**Comment by ValWood** [comment]
Ah right, I thought it was one you did.
I can just ask Jun-Song... I'll take it.

In fact it was one of her papers with the quote!

**Comment by ValWood** [comment]
Re- emailed Jun-Song.

Original message said:
>All other phosphorylation sites (several hundreds), which were shown in the supplementary table 5, were not curated.

but mentioned sending a spreeadsheet.

**Comment by ValWood** [comment]
Here is the spreadsheet...
[PMID23297348.xlsx](https://github.com/pombase/curation/files/2832823/PMID23297348.xlsx)

**Comment by ValWood** [comment]
@mah11  could you process this when you get chance?

**Comment by ValWood** [comment]
a tab separated text file
[PMID23297348.txt](https://github.com/pombase/curation/files/2832847/PMID23297348.txt)

**Comment by ValWood** [comment]
I notice the date is 2013...

**Comment by mah11** [comment]
done
