### ISSUE TITLE
4 annotations to fix / inhibition of binding

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2122]
https://docs.google.com/spreadsheets/d/1mpoIskoYNs4mOOtXelBuBmPLe4Hbuzu5ZKiO89zoi8k/edit#gid=0

- [x]  PomBase:SPAC8C9.11 | iron-sensor Fra2 | GO:1903026 | {"relationship": {"relation": [{"id": "RO:0002092", "label": "happens_during"}], "id": "GO:0010106", "label": "cellular response to iron ion starvation"}}\|{"relationship": {"relation": [{"id": "RO:0002233", "label": "has input"}], "id": "PomBase:SPAC23E2.01", "label": "PomBase:SPAC23E2.01"}} | PomBase | NCBITaxon:4896 | IMP |   |   |   | PMID:25806539 | 20160904 | negative regulation of RNA polymerase II regulatory region sequence-specific DNA binding |   |   |   |   |   |   |   |  

- [x]  PomBase:SPBC26H8.06 | CIA machinery monothiol glutaredoxin Grx4 | GO:1903026 | {"relationship": {"relation": [{"id": "RO:0002092", "label": "happens_during"}], "id": "GO:0010106", "label": "cellular response to iron ion starvation"}}\|{"relationship": {"relation": [{"id": "RO:0002233", "label": "has input"}], "id": "PomBase:SPAC23E2.01", "label": "PomBase:SPAC23E2.01"}} | PomBase | NCBITaxon:4896 | IMP |   |   |   | PMID:25806539 | 20160904 | negative regulation of RNA polymerase II regulatory region sequence-specific DNA binding |   |   |   |   |   |   |   |  

- [x]  PomBase:SPBC11B10.09 | cyclin-dependent protein kinase Cdk1/Cdc2 | GO:1903026 | {"relationship": {"relation": [{"id": "GOREL:0000015", "label": "has_regulation_target"}], "id": "PomBase:SPBC16G5.15c", "label": "PomBase:SPBC16G5.15c"}}\|{"relationship": {"relation": [{"id": "GOREL:0000501", "label": "occurs at"}], "id": "GO:0000307", "label": "cyclin-dependent protein kinase holoenzyme complex"}}\|{"relationship": {"relation": [{"id": "BFO:0000050", "label": "part_of"}], "id": "GO:0051445", "label": "regulation of meiotic cell cycle"}} | PomBase | NCBITaxon:4896 | IDA |   |   |   | PMID:26804917 | 20171215 | negative regulation of RNA polymerase II regulatory region sequence-specific DNA binding |   |   |   |   |   |   |   |  

  - [ ] PomBase:SPBC23G7.09 | mating-type m-specific polypeptide Mc | GO:1905636 | {"relationship": {"relation": [{"id": "GOREL:0000015", "label": "has_regulation_target"}], "id": "PomBase:SPBC32C12.02", "label": "PomBase:SPBC32C12.02"}} | PomBase | NCBITaxon:4896 | IDA |   |   |   | PMID:9233811 | 20171209 | positive regulation of RNA polymerase II regulatory region sequence-specific DNA binding |   |   |   |   |   |   |   |  

Discussion with @pgaudet these aren't really 'processes'

Inhibition of binding, if required should be an activity.

May need a  MF term for "inhibition of binding"
https://github.com/geneontology/go-annotation/issues/2039

**Comment by ValWood** [comment]
@Antonialock  we can chat about these when you are done

**Comment by ValWood** [comment]
http://pombase-dev.bioinformatics.nz/term/GO:2000677

**Comment by ValWood** [comment]
can you describe the "inhibition" in the ticket in each case.

I think 2 are cytoplasmic sequestration

**Comment by ValWood** [comment]
http://pombase-dev.bioinformatics.nz/gene/SPBC26H8.06

php4 and fep 1 are annotated differently, are these both sequestering?

**Comment by ValWood** [comment]
@Antonialock  when you do this can you update the spreadsheet in this ticket

https://github.com/geneontology/go-annotation/issues/2039#event-1760105355

**Comment by pgaudet** [comment]
> May need a MF term for "inhibition of binding"
Probably 'binding inhibitor activity' to be consistent with GO MF?

**Comment by ValWood** [comment]
done
