### ISSUE TITLE
no human ortholog  for some mitochondrial ATPase subunits

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2124]
has a disease association
https://www.pombase.org/gene/SPMIT.09

but no human ortholog detected yet.

Did you find it @Antonialock ?

**Comment by Antonialock** [comment]
I can't remember adding it, but it doesn't look unreasonable that I did it...

I found this paper that says that A6L and atp8 are equivalent subunits
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3278611/

human gene has disease associations
https://www.uniprot.org/uniprot/P03928

**Comment by ValWood** [comment]
So I add human MT-ATP8 to our ATP8

**Comment by ValWood** [comment]
these have no human ortholog:

atp17 | SPBC1604.11 | F1-FO ATP synthase subunit F (predicted)   ATP5MF?


one of these must be ATP5MPL? ATP5MD? ATP5MF?
atp18 | SPAC23C4.11 | F1-FO ATP synthase subunit J (predicted)
atp19 | SPAC25H1.10c | F1-FO ATP synthase subunit K (predicted)

**Comment by ValWood** [comment]
https://www.genenames.org/cgi-bin/genefamilies/set/644

**Comment by Antonialock** [comment]
Atp17 - ATP5MF
Atp18 - ATP5MPL
Atp19 -  ATP5MD

Eg see fig 1
https://www.pnas.org/content/115/12/2850

**Comment by Antonialock** [comment]
here is a ref stating that atp19=ATP5MD
https://www.ncbi.nlm.nih.gov/pubmed/29440398

**Comment by Antonialock** [comment]
atp19 leigh disease PMID:29917077 added

**Comment by Antonialock** [comment]
also added a ref for atp8 which is what this ticket was initially aboutr

**Comment by ValWood** [comment]
remove fungi only and add
/controlled_curation="term=species distribution, conserved in eukaryotes only;  date=20190128"
/controlled_curation="term=species distribution, conserved in vertebrates; date=20190128"
/controlled_curation="term=species distribution, conserved in metazoa; date=20190128"
/controlled_curation="term=human XXXX ortholog; db_xref=PMID:29514954; date=20190128"

for each
