### ISSUE TITLE
ESCRT

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2131]
should ESCRT proteins, bro1 etc be annotated to multivesicular body assembly rather than transport?

[annurev-biochem-072909-101058.pdf](https://github.com/pombase/curation/files/2253517/annurev-biochem-072909-101058.pdf)

**Comment by ValWood** [comment]
probably but it's still part of the transport process.... but the connection is n't made in GO ?

I think this part is a 'bit of a mess'

Will keep   on the radar, but don't want to tackle that area right now.

**Comment by ValWood** [comment]
will close
