### ISSUE TITLE
silenced gene loci

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2136]
Didn't we decide that these should not have GO annotation?

Maybe we should change the feature type so they are not CDS?

**Comment by mah11** [comment]
I don't remember, but it would make sense not to GO-annotate because they don't normally have a product.

**Comment by ValWood** [comment]
https://www.pombase.org/gene/SPBC1711.02
https://www.pombase.org/gene/SPBC1711.01c
need  to be   a misc feature with a SO feature type

**Comment by mah11** [comment]
SO:0000127 silenced_gene
or one of the subtypes

**Comment by Antonialock** [comment]
https://www.pombase.org/gene/SPBC1711.02
https://www.pombase.org/gene/SPBC1711.01c
 can have phenotypes (just remove the Matsayama annotations)

mat2-pc and pi can have annotations becuase we can't stash them anywhere else.

**Comment by ValWood** [comment]
The phenotypes will still apply, but we will lose them if we convert to a misc feature of type
SO:0000127 silenced_gene (I think)

So we need to be able to add phenotypes to this type of feature in Canto....

**Comment by ValWood** [comment]
HELP ! So I do want to annotate  Mi....which copy do we use to annotate? @Antonialock  ?

**Comment by ValWood** [comment]
Chromatin immunoprecipitation experiments further showed that Pi and Mi associate with the mei3 promoter, but only when both proteins are present (Fig. 2f, Extended Data Fig. 2c). Thus, the Pi–Mi complex—but not its individual subunits—binds chromatin and induces mei3 expression.

**Comment by ValWood** [comment]
so I want to annotate the  TF function of mat2. which sequence do I use? (and why aren't any described as 'homeobox transcription factor"?

**Comment by ValWood** [comment]
mat2-Pi used to have
transcriptional activator activity, RNA polymerase II proximal promoter sequence-specific DNA binding
https://www.uniprot.org/uniprot/P10842
so where did it move to instead?

**Comment by ValWood** [comment]
I think I misunderstood about the silencing here. I thought these were permanently silenced cssettes. Which is the "active loci"  for mat2-Pi?

**Comment by Antonialock** [comment]
mat1-Pi....the reference strain doesn't contain this gene because the reference strain is an M cell

active locus:
mat1

silenced loci:
mat2
mat3


so if you want to annotate the active mat-mi it is SPBC23G7.17c

active mat-pi is impossible to annotate using the reference genome, only silenced SPMTR.02 can be annotated. It is a fudge but the best we can do.

**Comment by ValWood** [comment]
OK got it. We sould add some sort of warning to this effect.

**Comment by Antonialock** [comment]
:-)

![fd4a6124-f2b4-407c-a9cb-628b52588446](https://user-images.githubusercontent.com/12727506/46505071-cb023780-c827-11e8-80b9-7c0b6418bdc7.png)

**Comment by ValWood** [comment]
OK, I think I still need to annotate something...

**Comment by ValWood** [comment]
re:
mat2-Pi used to have
transcriptional activator activity, RNA polymerase II proximal promoter sequence-specific DNA binding
https://www.uniprot.org/uniprot/P10842
so where did it move to instead?

do any of the removed annotations need to be added back? @Antonialock 

I will do  the TF annotation from the paper above

but should we also change the  description

from
silenced P-specific polypeptide Pi

to 
silenced P-specific trancription factor Pi ? @Antonialock

**Comment by ValWood** [comment]
Actually I think the annotations are all there?

https://www.pombase.org/gene/SPMTR.02

Just update the products then? Would that be OK ? polypepetide sounds a bit 'old hat'

**Comment by Antonialock** [comment]
updated all 6

**Comment by ValWood** [comment]
Thanks. It still confuses me ;)
