### ISSUE TITLE
figure out what these mean "regulation of transcription factor" -> pat1-stell model

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2137]
regulation of DNA-binding transcription factor activity (GO:0051090)

Gene name | Systematic ID | Product
-- | -- | --
cka1 | SPAC23C11.11 | serine/threonine protein kinase Cka1
ckb1 | SPAC1851.03 | CK2 family regulatory subunit Ckb1
pmk1 | SPBC119.08 | MAP kinase Pmk1
rad24 | SPAC8E11.02c | 14-3-3 protein Rad24
taf6 | SPCC16C4.18c | SAGA complex/transcription factor TFIID complex histone H4-like subunit Taf6
tpx1 | SPCC576.03c | thioredoxin peroxidase Tpx1
txl1 | SPBC577.08c | thioredoxin-like I protein Txl1

most of these are NOT regulating the transcription factor activity....
https://github.com/geneontology/go-ontology/issues/16152

and this is a really mixed bag of  random activities

**Comment by ValWood** [comment]
taf6 GO:0051090 | regulation of DNA-binding transcription factor activity | IEA with IPR011442

cka1
surplus to
GO:0004674 | protein serine/threonine kinase activity | IDA |
has substrate rrn7 involved in negative regulation of transcription by RNA polymerase II | IDA | Moreira-Ramos S et al. (2015)

etc

**Comment by ValWood** [comment]
rad24
surplus to
GO:0000122 | negative regulation of transcription by RNA polymerase II

**Comment by ValWood** [comment]
tpx1, I think this acts directly on pap1 (oxidation status) if so, this should be an MF annotation?

txl1
has
GO:0004791 | thioredoxin-disulfide reductase activity | has substrate pap1


need to add F-P link to 

negative regulation of transcription from RNA polymerase II promoter in response to oxidative stress

and delete

negative regulation of DNA-binding transcription factor activity
  | regulates pap1 during cellular response to oxidative stress

**Comment by ValWood** [comment]
pmk1

"positive regulation of DNA-binding transcription factor activity"

should be "positive regulation of transcription from RNA polymerase II promoter"

and F-P connection.

**Comment by ValWood** [comment]
@Antonialock do you agee?
I think these are old.

positive regulation of DNA-binding transcription factor activity is a function term in the process ontology.

**Comment by Antonialock** [comment]
should cka1/ckb1 change to negative regulation of DNA-templated transcription, initiation ?

atf1 yes looks odd

rad24 - yes looks like it should be a function, paper is still uncurated (I think rad24 sequesters several proteins)

tpx1 - looks like paper might need reading again to overhaul GO terms. Looks a bit complicated at a glance but doesn't look like they are right. Probably same with txl1

**Comment by ValWood** [comment]
- [ ] tpx1 /tx11 is  done:

![tpx](https://user-images.githubusercontent.com/7359272/43883474-24a1b42c-9bab-11e8-84f5-31988ef174d1.jpg)

**Comment by ValWood** [comment]
I'll had this over to you.

No hurry but it would be nice to capture  the  data in the model for  pat1-ste11, and you have that one

**Comment by Antonialock** [comment]
Closed?
-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by ValWood** [comment]
actually, we don't really need the ticket anyway. you have the paper with the model in you list. Close?

**Comment by ValWood** [comment]
your call ;)

**Comment by Antonialock** [comment]
ok close, thee are too many tickboxes spread out over multiple comments in this ticket ;)
