### ISSUE TITLE
new ncRNA

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2138]
- [ ]  new ncRNA for
add to new genes page
/primary_name="RnpB"
/systematic_id="SPMITNCRNA.01"
/product="mitochondrial RNase P RNA"
/GO="aspect=P; term=tRNA 5'-leader removal; GOid=GO:0090646; evidence=TAS; db_xref=PMID:29954949;  date=20180809"
/GO="aspect=C; term=mitochondrial ribonuclease P complex; GOid=GO:0030678; evidence=TAS; db_xref=PMID:29954949; date=20180809"
/GO="aspect=F; term= ribonuclease P activity; qualifier=contributes_to; GOid=GO:0004526; evidence=TAS; db_xref=PMID:29954949; date=20180809"
/controlled_curation="term=warning, new gene; db_xref=PMID:29954949; date=20180809"
/db_xref="PMID:29954949"

- [x]  find pombe member (protein component!)
http://www.ebi.ac.uk/interpro/entry/IPR013888/taxonomy
I could not find this.....

**Comment by ValWood** [comment]
just needs adding to new genes page...

**Comment by mah11** [comment]
> just needs adding to new genes page...

this belongs on the website tracker

**Comment by mah11** [comment]
There's a log warning for this one because the GO ID and term name don't match; I haven't fixed it because I don't know which is correct:

/GO="aspect=P; term=tRNA 5'-leader removal; GOid=GO:0090646; evidence=TAS; db_xref=PMID:29954949; date=20180809"

    ncRNA SPMITNCRNA.01.1: ID in EMBL file (GO:0090646) doesn't match ID in Chado (GO:0001682) for EMBL term name tRNA 5'-leader removal   (Chado term name: mitochondrial tRNA processing):

**Comment by ValWood** [comment]
fixed. Also lower cased the Gene name...
