### ISSUE TITLE
sort these before next EMBL submission

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#214]
Chr 1:

====

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: pyruvate decarboxylase

\(predicted\) \[\(emb|CU329670.1|:c103544-

101872, c101869-101836\)\] -&gt;

\[emb|CAB03601.3|\]

\[gi|159883886|emb|CU329670.1|: delta, dna

len= 5579133\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: conserved fungal protein

\[\(emb|CU329670.1|:2499035-2499159, 2499161-

2499353, 2499443-2499824, 2499875-2500236\)\] -

&gt; \[emb|CAB16233.3|\]

\[gi|159883886|emb|CU329670.1|: delta, dna

len= 5579133\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: rRNA processing protein Rrp36,

DUF947 family \(predicted\)

\[\(emb|CU329670.1|:2587729-2587897, 2587952-

2588028, 2588031-2588143, 2588182-2588620\)\] -

&gt; \[emb|CAB90149.3|\]

\[gi|159883886|emb|CU329670.1|: delta, dna

len= 5579133\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: kinetochore protein Nnf1

\[\(emb|CU329670.1|:4409773-4410192, 4410194-

4410391\)\] -&gt; \[emb|CAB66467.2|\]

\[gi|159883886|emb|CU329670.1|: delta, dna

len= 5579133\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: mitochondrial ribosomal

protein subunit Mrps9 \(predicted\)

\[\(emb|CU329670.1|:5142407-5142628, 5142631-

5143224\)\] -&gt; \[emb|CAB10130.2|\]

\[gi|159883886|emb|CU329670.1|: delta, dna

len= 5579133\]

WARN           SEQ\_FEAT       ShortIntron                                  

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329670.1|:c1485023-

1485015\] \[gi|159883886|emb|CU329670.1|:

delta, dna len= 5579133\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329670.1|:1704621-

1704628\] \[gi|159883886|emb|CU329670.1|:

delta, dna len= 5579133\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329670.1|:c2214776-

2214769\] \[gi|159883886|emb|CU329670.1|:

delta, dna len= 5579133\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329670.1|:c2684726-

2684719\] \[gi|159883886|emb|CU329670.1|:

delta, dna len= 5579133\]

Chr 2:

====

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: ornithine decarboxylase

antizyme with +1 programmed ribosomal

frameshift Spa1 \[\(emb|CU329671.1|:c779869-

779669, c779667-779188\)\] -&gt;

\[emb|CAB54822.2|\]

\[gi|157310380|emb|CU329671.1|: delta, dna

len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: translation initiation factor

eIF3 alpha subunit \(p135\) \(predicted\)

\[\(emb|CU329671.1|:c802851-802839, c802651-

800840, c800838-799142\)\] -&gt;

\[emb|CAA19172.3|\]

\[gi|157310380|emb|CU329671.1|: delta, dna

len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: cell surface glycoprotein

\(predicted\), DUF1773 family protein 6

\[\(emb|CU329671.1|:c1033776-1033610, c1033607-

1032857\)\] -&gt; \[emb|CAO77661.2|\]

\[gi|157310380|emb|CU329671.1|: delta, dna

len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: Lsd90 protein

\[\(emb|CU329671.1|:c1950255-1950053, c1950050-

1948955, c1948953-1947985\)\] -&gt;

\[emb|CAB16908.4|\]

\[gi|157310380|emb|CU329671.1|: delta, dna

len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: mitochondrial matrix protein

import protein Tam41 \(predicted\)

\[\(emb|CU329671.1|:c1988353-1988081, c1988015-

1987737, c1987675-1987102, c1987099-

1987044\)\] -&gt; \[emb|CAA20110.3|\]

\[gi|157310380|emb|CU329671.1|: delta, dna

len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: CGI-48 family \(predicted\)

\[\(emb|CU329671.1|:2048336-2049892, 2049894-

2049896\)\] -&gt; \[emb|CAA18383.2|\]

\[gi|157310380|emb|CU329671.1|: delta, dna

len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: elongin-A, F-box protein Pof4

\(predicted\) \[\(emb|CU329671.1|:2053033-

2053517, 2053519-2053600\)\] -&gt;

\[emb|CAA18385.2|\]

\[gi|157310380|emb|CU329671.1|: delta, dna

len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: conserved eukaryotic protein

\[\(emb|CU329671.1|:c2108786-2108181, c2108178-

2106448\)\] -&gt; \[emb|CAA22622.3|\]

\[gi|157310380|emb|CU329671.1|: delta, dna

len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: IMPACT domain protein,

involved in translation \(predicted\)

\[\(emb|CU329671.1|:c2220322-2219937, c2219934-

2219430\)\] -&gt; \[emb|CAA18427.3|\]

\[gi|157310380|emb|CU329671.1|: delta, dna

len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: guanyl-nucleotide exchange

factor Vps901 \(predicted\)

\[\(emb|CU329671.1|:2708076-2709415, 2709418-

2709793\)\] -&gt; \[emb|CAA20730.2|\]

\[gi|157310380|emb|CU329671.1|: delta, dna

len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: splicing factor Cwf22

\[\(emb|CU329671.1|:3037988-3040331, 3040334-

3040650\)\] -&gt; \[emb|CAA20491.4|\]

\[gi|157310380|emb|CU329671.1|: delta, dna

len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329671.1|:c1598117-

1598111\] \[gi|157310380|emb|CU329671.1|:

delta, dna len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329671.1|:1598549-

1598558\] \[gi|157310380|emb|CU329671.1|:

delta, dna len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329671.1|:1599745-

1599752\] \[gi|157310380|emb|CU329671.1|:

delta, dna len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                  

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329671.1|:c1601011-

1601003\] \[gi|157310380|emb|CU329671.1|:

delta, dna len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329671.1|:1629197-

1629205\] \[gi|157310380|emb|CU329671.1|:

delta, dna len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329671.1|:1643887-

1643896\] \[gi|157310380|emb|CU329671.1|:

delta, dna len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329671.1|:1645083-

1645090\] \[gi|157310380|emb|CU329671.1|:

delta, dna len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329671.1|:c1646349-

1646341\] \[gi|157310380|emb|CU329671.1|:

delta, dna len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                  

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329671.1|:3814173-

3814180\] \[gi|157310380|emb|CU329671.1|:

delta, dna len= 4539804\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329671.1|:3814596-

3814605\] \[gi|157310380|emb|CU329671.1|:

delta, dna len= 4539804\]

Chr 3:

====

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: wtf element Wtf12

\[\(emb|CU329672.1|:1401530-1401668, 1401900-

1402172, 1402490-1402551, 1402553-1402672\)\] -

&gt; \[emb|CAB63875.2|\]

\[gi|157310483|emb|CU329672.1|: delta, dna

len= 2452883\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: CDS: meiotic recombination protein

\(predicted\) \[\(emb|CU329672.1|:c1775429-

1774236, c1774233-1773925\)\] -&gt;

\[emb|CAA21438.3|\]

\[gi|157310483|emb|CU329672.1|: delta, dna

len= 2452883\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329672.1|:1092972-

1092980\] \[gi|157310483|emb|CU329672.1|:

delta, dna len= 2452883\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329672.1|:c1106022-

1106014\] \[gi|157310483|emb|CU329672.1|:

delta, dna len= 2452883\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329672.1|:c1139579-

1139572\] \[gi|157310483|emb|CU329672.1|:

delta, dna len= 2452883\]

WARN           SEQ\_FEAT       ShortIntron                                 

Introns should be at least 10 nt long

FEATURE: intron:  \[emb|CU329672.1|:1475073-

1475080\] \[gi|157310483|emb|CU329672.1|:

delta, dna len= 2452883\]

Original comment by: ValWood

**Comment by ValWood** [comment]
closing as these will be sorted as part of the sequence update. Presumably when I next try to submit to EMBL I'll get these warnings if any are left, so no need to worry about it here.
