### ISSUE TITLE
M26_binding question

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2140]
I thought the M26 was a recombination hotspot (I.e a specific site) rather than a TF binding site (it just happens to also be a TF binding site)., but isn't the motif CRE?

M26 is defined

Definition | Parents
-- | --
A promoter element that contains a core sequence TGACGT, bound by a protein complex that regulates transcription of genes encoding PKA pathway components.

I have never heard anyone call the  TF regulatory motif M26

**Comment by ValWood** [comment]
M26 binding site TGACGT
more correctly CRE (this is a substring or CRE)
cyclic AMP response element (CRE) | TGACGTCA


We need to ask for these to merge, if it is describing the CRE element.

If we want a feature to describe the M26 recombination hotspot near to the ade locus we  should request a new term (I think this might be longer).

Can we also extend this table to include the primary reference ? (Should be the one in the SO entry)

**Comment by Antonialock** [comment]
I've requested the merge.

might impact FYPO xrefs? @mah11

**Comment by mah11** [comment]
What are the IDs?

**Comment by Antonialock** [comment]
and suggested they redefined our term instead - we (I) have used it quite a bit as a recombination site term. 

The only place it had been used as a TF site term was for PMID:15448137 - I changed these to CRE

**Comment by Antonialock** [comment]
SO:0001900 @mah11 
It's only if it's been used for tf binding...i guess it depends on if they merge or create a new term for m26 reocmbination site. I'll tag you in the SO ticket,.

**Comment by Antonialock** [comment]
I added the PMID refs from so to
https://github.com/pombase/website/blob/master/src/docs/browse-curation/dna-binding-sites.md

I also alphabetised the table. Really annoying github doesn't let you sort tables in a clever way.
