### ISSUE TITLE
CArG box & Pho7 question

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2142]
Any idea why we have:
CArG box | (C/T)TA(T/A)4TA(G/A) |   | SO:0002156

(no genes annotated as far as I can see)

**Comment by ValWood** [comment]
Also 
Pho7 binding site | [5'-TCG(G/C)(A/T)xxTTxAA] | Pho7

no SO ID, is this pending?

**Comment by ValWood** [comment]
Out for CC I guess

Defining the DNA Binding Site Recognized by the Fission Yeast Zn2Cys6 Transcription Factor Pho7 and Its Role in Phosphate Homeostasis.

Schwer B, Sanchez AM, Garg A, Chatterjee D, Shuman S.

MBio. 2017 Aug 15;8(4). pii: e01218-17. doi: 10.1128/mBio.01218-17.

PMID: 28811350

**Comment by ValWood** [comment]
You are on it!
https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/440

**Comment by Antonialock** [comment]
yes still waiting for that SO term.

I guess map1 should be annotated to binding the Carg box but I don't know of any papers that have shown that specifically

**Comment by ValWood** [comment]
maybe can use TAS?

**Comment by ValWood** [comment]
this can probably close

**Comment by Antonialock** [comment]
I removed carg because I can't find any mentions in pombe....only that plant MADS type TFs bind this motif.
