### ISSUE TITLE
tyrosine kinases

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2153]
lkh1 and pek1 have IEA to tyrosine kinase, is this likely?

**Comment by Antonialock** [comment]
pek1 - ok, phosphorylates pmk1 on tyrosine (parentage issue?)
lkh1 - ok (lammer kinases have dual specificity)

**Comment by Antonialock** [comment]
I don't know how straight forward it is to instate tyrosine kinase activity as a parent to MAPKK kinase activity...it currently has the parent protein serine/threonine/tyrosine kinase activity

**Comment by ValWood** [comment]
let's quietly ignore...
