### ISSUE TITLE
should this orthologous group split?  bit2/bit61?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2154]
http://pombase-dev.bioinformatics.nz/gene/SPAC6B12.03c

@Antonialock ?

**Comment by Antonialock** [comment]
this paper
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5618247/

suggests that they are paralogs if that helps
<img width="700" alt="screen shot 2018-08-30 at 10 31 16" src="https://user-images.githubusercontent.com/12727506/44843306-ee8dfd00-ac3f-11e8-8416-3363addbb372.png">

**Comment by ValWood** [comment]
Well they are paralogs,
but  I don't know if they resolve 1:1, they might but I would not know which way

https://www.flyrnai.org/cgi-bin/DRSC_orthologs.pl?input_species=4896&output_species=0&additional_filter=None&search_fields=***&search_datasets=***&gene_list=SPAC6B12.03c

**Comment by ValWood** [comment]
this doesn't help either. 
http://www.treefam.org/family/TF314826#tabview=tab1

Need to wait, can't do anything except 2:2 right now (duplication since divergence), although I agree thus is more likely a  pre divergence duplication.

Often in these cases the evolutionary pressure, (via co evolution of binding partners)  makes the within-organism members seem to be more similar than the between organism members (ribosomes and histones).  It is however likely that 2 copies did exist inthe common ancestor. But based on available info we can't  show this....

**Comment by ValWood** [comment]
We would need information showing that one was in one pathway/complex and one in another pathway. It isn't possible from sequence data alone.
