### ISSUE TITLE
check ubiquinone biosynthesis

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2157]
most are probably coenzyme Q deficiency disease causing?

**Comment by ValWood** [comment]
after
https://github.com/pombase/curation/issues/2130
check that these have disease annotated

**Comment by Antonialock** [comment]
azr1 can't find

**Comment by Antonialock** [comment]
To date mutations in 8 genes (PDSS1, PDSS2, COQ2, COQ4, COQ6, ADCK3, ADCK4, and COQ9) have been associated with CoQ10 deficiency presenting with a wide variety of clinical manifestations. 

all that have orthologs are annotated
PDSS1, PDSS2 - no ortholog, COQ2, COQ4, COQ6, ADCK3 - no ortholog, ADCK4 - no ortholog, and COQ9

**Comment by ValWood** [comment]
probably dpl1 is  PDSS1 & PDSS2

abc8  is ADCK3 (primary name COQ8A) and ADCK4 (COQ8B)

**Comment by ValWood** [comment]
azr1 https://www.pombase.org/gene/SPAC1556.03 is human PTC7

**Comment by Antonialock** [comment]
> azr1 https://www.pombase.org/gene/SPAC1556.03 is human PTC7
> where can't you find it?

nowhere....I said that PDSS2, ADCK3 and ADCK4 don't have annotated orthologs

**Comment by ValWood** [comment]
OK the othologs are annotated.

I was referring to the comment"can't find azr1" I  was presuming this was also about ortholgos.I f not this can stay closed
