### ISSUE TITLE
Number of "viable and inviable" message creeping up

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#2158]
The list of warnings about genes that are both viable and inviable is slowing getting longer.

eg. https://curation.pombase.org/dumps/builds/pombase-build-2018-08-19/logs/log.2018-08-19-22-11-58.web-json-write

I'm making an issue in case it's getting overlooked.

**Comment by ValWood** [comment]
odd, these are both from the deletion collection.

https://www.pombase.org/gene/SPAC17A2.08c

I these cases maybe I shpuld remove the original.

@JackyVH ?

**Comment by JackyVH** [comment]
I'll check this to see what's happened and  which one is correct

**Comment by JackyVH** [comment]
I’ve check this and in both papers the gene is reported as essential. The phenotype description in the second paper is germination with and without germ tube elongation. I guess the viable population annotation for the second paper is not correct?

**Comment by JackyVH** [comment]
I’ve check this and in both papers the gene is reported as essential. The phenotype description in the second paper is germination with and without germ tube elongation. I guess the viable population annotation for the second paper is not correct?

**Comment by JackyVH** [comment]
Val It just dawned on me that n the phenotype paper we also reported deletions that had been remade and and now had a different phenotype I wonder of some of these are also conflicting , viable / essential

**Comment by ValWood** [comment]
Yes I will double check this in the original; spreadsheet.  I think we decided to 'over ride" the  older data with the newer data, if a deletant was re-made and had a different viability, is that correct?

**Comment by JackyVH** [comment]
Yes I agreed, I think this is what we should do

**Comment by JackyVH** [comment]
I can't remember but I think that is what we should do

**Comment by ValWood** [comment]
I transferred this one to
https://github.com/pombase/curation/issues/1038
It will get checked when  I rerun the script.
