### ISSUE TITLE
frataxin  BP IC does not align with MF

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2160]
https://www.pombase.org/gene/SPCC1183.03c

GO:0044571 | [2Fe-2S] cluster assembly | IC from ferredoxin-NADP+ reductase activity

but MF is not
ferredoxin-NADP+ reductase activity

**Comment by ValWood** [comment]
also is

heme biosynthetic process

correct?

**Comment by Antonialock** [comment]
fixed the MF

correct heme biosynthesis (contributes to final step). I ISSd it based on 15123683
