### ISSUE TITLE
iron-sulfur transferase activity query

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2167]
our isu1 has
iron-sulfur transferase activity
but the human ortholog has:

ISCU
Iron-sulfur cluster assembly enzyme ISCU, mitochondrial protein-containing complex scaffold activity HGNC

is this catalytic, or scaffold?

**Comment by Antonialock** [comment]
reopen if not ok

**Comment by ValWood** [comment]
I think its transferase with contributes_to?

But I'm not really sure. Is there a nice pic or review?

**Comment by Antonialock** [comment]
Work in bacteria and yeast model systems suggests that a dedicated chaperone–co-chaperone pair of proteins participates in cluster transfer from the primary scaffold, ISCU, to recipient Fe-S proteins. The co-chaperone is known to be HSC20 (a DNAJ protein), whereas the chaperone is an HSP70 homolog that has not yet been clearly identified in mammalian cells. The role of a putative HSC70 protein is proposed here. HSC20 binds ISCU, and the HSC20-ISCU complex probably then binds to its HSC70 partner through two different binding sites: HSC20 contacts the N-terminus of HSC70 and its binding partner, ISCU, binds to the C-terminal substrate-binding domain region of HSC70. The J domain region of HSC20 contains three residues [His (H) Pro (P) and Asp (D); HPD] that activate the ATPase activity of HSC70. Upon activation, a conformational change is proposed to occur in the substrate-binding domain of HSC70 that affects bound ISCU, resulting in extrusion of a peptide containing the residues LPPVK from the ISCU globular protein. The LPPVK peptide then binds to a groove in the substrate-binding domain of HSC70, which consolidates or perhaps further enhances the conformational change in ISCU, which might convert it to a conformation that facilitates donation of its cluster to recipient proteins. In this model, HSC20 helps protect the vulnerable Fe-S cluster bound to ISCU as it dissociates from the multimeric assembly complex, and HSC20 then escorts ISCU to form a trimeric complex with HSC70. The consumption of ATP probably provides a powerful impetus to drive conformational changes of ISCU and the substrate-binding domain of HSC70; these changes might facilitate release of the Fe-S cluster from ISCU. By capturing the energy released by ATP hydrolysis and coupling it to conformational changes, the chaperone–co-chaperone pair help the Fe-S cluster to reach its target proteins. 



<img width="1202" alt="screen shot 2018-10-05 at 09 36 49" src="https://user-images.githubusercontent.com/12727506/46525078-940d3f80-c882-11e8-8082-63dbbc28ff6c.png">

**Comment by Antonialock** [comment]
let me know if you want me to change it back to transferase activity

**Comment by ValWood** [comment]
So, ISCU is an adaptor that binds the iron sulfur cluster to various other proteins that it is transferred between, is that correct?

@pgaudet,  do you agree that  molecular adaptor activity is the correct term? and if so do we need a specific subtype?  It does not fit either of the 3 existing types of adaptor.

**Comment by Antonialock** [comment]
the cluster is assembled onto iscu. the cluster is then transferred from iscu onto another protein. ISCU doesn't have catalytic activity in its own right to make the transfer happen (but there is some sort of conformational change within the protein happening at some point which I guess triggers other reactions).

**Comment by pgaudet** [comment]
I think if ISCU binds and transfers the iron sulfur cluster, then I would annotate to 'molecular carrier activity' (def:"Directly binding to a specific ion or molecule and delivering it either to an acceptor molecule or to a specific location.") 

@pedruzzi does that seem OK to you ? 

Thanks, Pascale

**Comment by Antonialock** [comment]
but the def implies physical relocation which isn't really true for ISCU?

(it is currently annotated to molecular adaptor activity
Def: The binding activity of a molecule that brings together two or more molecules through a selective, non-covalent, often stoichiometric interaction, permitting those molecules to function in a coordinated way.)

**Comment by ValWood** [comment]
I think molecular carrier activity is probably correct.

So @Antonialock  this is defined as
Directly binding to a specific ion or molecule and delivering it either to an acceptor molecule or to a specific location.

This does not imply directed movement like "transport" it is much more general so it can be used for instance for the  ACP
https://en.wikipedia.org/wiki/Acyl_carrier_protein
https://www.sciencedirect.com/science/article/pii/S0022283617304977#f0005
which is absolutely not a "transporter actvity"
see the parentage:
https://www.ebi.ac.uk/QuickGO/term/GO:0000036

delivery isn't necessarily transport.
I agree that "to a specific location"  seems a bit odd, because the movement  for 'delivery'  is very small....

**Comment by Antonialock** [comment]
it's annotated to carrier now so this can close?
