### ISSUE TITLE
where are logs for obsolete phenotypes?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2173]
I couldn't approve this session because phenotype is gone, But I don't remember ever seeing a log file for these. Is there one?

If so, I can fix the others ....

![log](https://user-images.githubusercontent.com/7359272/44719315-d3de4b80-aaba-11e8-89fd-a3cd5bff56e9.jpg)

I fixed this one to parent (maybe this could be a merge, so reannotation unnecessary?)

**Comment by mah11** [comment]
- you requested obsoletion (https://github.com/pombase/fypo/issues/3332#issuecomment-405581596)

- reports are in the Canto log (curation-tool-data-load-output file name)

- I've been working through them gradually, and got about a third of the way through. I'm happy to carry on with the bulk of them, but don't let that stop you doing any that bother you before I get to them ;)

**Comment by ValWood** [comment]
Ah OK, obsoletion is fine, I   remember now requested so that we could specify residue if possible.

I'll leave this with you if you are working through the logs, there is no hurry. I  suddenly thought I had never seen the obsolete phenotype error in the logs, but if it is there no worries.
