### ISSUE TITLE
mitotic competence  (G0)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2175]
After
https://github.com/pombase/fypo/issues/3346

may need to revisit

However, in a previous study, we identified 164 strains from a temperature-sensitive mutant library containing point mutations defective in MC maintenance under −N (24).
24. K. Sajiki, M. Hatanaka, T. Nakamura, K. Takeda, M. Shimanuki, T. Yoshida, Y. Hanyu, T. Hayashi, Y. Nakaseko, M. Yanagida, Genetic control of cellular quiescence in S. pombe. J. Cell. Sci. 122, 1418–1429 (2009).
We designated these mutated genes as “super housekeeping (SHK)” genes with regard to GZE, since they are required for both VE growth at high temperature and MC maintenance in the G0 phase.

**Comment by Antonialock** [comment]
i have opened https://github.com/pombase/fypo/issues/3485

**Comment by ValWood** [comment]
Hmm, I don't remember what some of these are!
MC=mitotic competence
GZE= ?
VE= vegetative something?

**Comment by Antonialock** [comment]
well the paper you mentione say GZE- G-Zero Essential
