### ISSUE TITLE
find and fix! incorrect relation for BP

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2176]
2 | directly_negatively_regulates | biological_process
  2 | directly_positively_regulates | biological_process

**Comment by ValWood** [comment]
@kimrutherford  could you find these annotations (we shouldn't use this relation with BP)
v

**Comment by kimrutherford** [comment]
> could you find these annotations

They are in the annotation for PMID:19056896.  Here are the two genes:

https://curation.pombase.org/pombe/curs/fc9305f756e323a2/feature/gene/view/18/ro
https://curation.pombase.org/pombe/curs/fc9305f756e323a2/feature/gene/view/8/ro

**Comment by ValWood** [comment]
Antonia could you take a look at this? We can't use 

directly_negatively_regulates 
directly_positively_regulates 
with process. 

Is this what you mean? Can chat about this at some point if you like.

**Comment by Antonialock** [comment]
I think you'll need to have that chat with yourself xD they were your annotations Val

I changed them to has_regulation_target

**Comment by ValWood** [comment]
;) I have!
