### ISSUE TITLE
add gene names to alleles 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2181]
https://www.pombase.org/term/FYPO:0000705

quite a lot visible here, good ones to fix
![fill in](https://user-images.githubusercontent.com/7359272/44808144-5f430400-abc3-11e8-83cc-3ea585bd42c3.jpg)

Also in this list, a lot of  alleles beginning with an uppercase gene name. They should ALL be lower case....

**Comment by ValWood** [comment]
| FYPO:0000705 | abolished protein-protein interaction
-- | -- | --
(105-624) (105-624 Δaa) | affecting mdb1affecting mdb1 | Co-immunoprecipitation experiment |   | Luo S et al. (2015)
1-187 (188-569 Δaa) | affecting gad8affecting sin1 | Co-immunoprecipitation experiment |   | Tatebe H et al. (2017)
1-200 (201-1401 Δaa) | affecting wis4 affectingwin1 | Other |   | Morigasaki S et al. (2013)
1-200 fragment (201-886 Δaa) | affecting sog2affecting nak1 | cell growth assay evidence |   | Kume K et al. (2013)
1-285 (286-1115 Δaa) | affecting mto1affecting alp4 | Co-immunoprecipitation experiment |   | Samejima I et al. (2008)
1-300 (301-971 Δaa) | affecting swi1 affectingswi3 | Western blot assay |   | Noguchi C et al. (2012)
1-500 fragment (501-886 Δaa) | affecting sog2affecting nak1 | cell growth assay evidence |   | Kume K et al. (2013)
1-850 (851-991 Δaa) | affecting dhp1affecting din1 | Other |   | Xiang S et al. (2009)
1-88 (89-140 Δaa) | affecting shk1affecting skb5 | Other |   | Yang P et al. (1999)
1-900 (901-1471 Δaa) | affecting rng9 affectingmyo51 | Co-immunoprecipitation experiment |   | Wang N et al. (2014)
1037-1401 (1-1036 Δaa) | affecting wis4 affectingwin1 | Other |   | Morigasaki S et al. (2013)
180-557 expressed (1-179 Δaa) | affecting prp45affecting cyp1 | Other |   | Skruzný M et al. (2001)
200-500 fragment (1-199, 501-886 Δaa) | affecting sog2affecting nak1 | cell growth assay evidence |   | Kume K et al. (2013)
247-380 (1-246, 381-665 Δaa) | affecting gad8affecting sin1 | Co-immunoprecipitation experiment |   | Tatebe H et al. (2017)
250-1037 (1-249, 1038-1401 Δaa) | affecting wis4 affectingwin1 | Other |   | Morigasaki S et al. (2013)
301-400 (1-300, 401-665 Δaa) | affecting gad8affecting sin1 | Co-immunoprecipitation experiment |   | Tatebe H et al. (2017)
329-665 (1-328 Δaa) | affecting gad8affecting sin1 | Co-immunoprecipitation experiment |   | Tatebe H et al. (2017)
3PA (unknown) | affecting cdc15affecting rgf3 | Other |   | Ren L et al. (2015)
500-1037 (1-499, 1038-1401 Δaa) | affecting wis4 affectingwin1 | Other |   | Morigasaki S et al. (2013)
500-800 (1-499, 801-971 Δaa) | affecting swi1 affectingswi3 | Western blot assay |   | Noguchi C et al. (2012)
558-853 (1-557, 854-1436 Δaa) | affecting wis4 affectingwin1 | Other |   | Morigasaki S et al. (2013)
650-886 fragment (1-649 Δaa) | affecting sog2affecting nak1 | cell growth assay evidence |   | Kume K et al. (2013)
703-1123 (1-702, 1124-1436 Δaa) | affecting wis4 affectingwin1 | Other |   | Morigasaki S et al. (2013)
750-886 fragment (1-749 Δaa) | affecting sog2affecting nak1 | cell growth assay evidence |   | Kume K et al. (2013)
846-1123 (1-845, 1124-1436 Δaa) | affecting wis4 affectingwin1 | Other |   | Morigasaki S et al. (2013)
94-328 (1-93, 329-665 Δaa) | affecting gad8affecting sin1 | Co-immunoprecipitation experiment |   | Tatebe H et al. (2017)
A286D (A286D aa) | affecting ofd1 affectingsre1 | Co-immunoprecipitation experiment |   | Clasen SJ et al. (2017)

**Comment by ValWood** [comment]
I have done some, handing it over to you @Antonialock

**Comment by Antonialock** [comment]
done
