### ISSUE TITLE
annotation check

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2182]
I had this saved, as an example (for something else)

![question2](https://user-images.githubusercontent.com/7359272/44835177-43734880-ac2b-11e8-9744-75e4bcd521e0.jpg)

but I can't see the annotation for
rad3-delta pmk1 delta  cdc2-as in the multi gene section.

I expected to see this at
abolished protein phosphorylation during cellular response to hydroxyurea
after the residue specific merge (Or obsoletion?)

So I thought it must be  still in the logs, but I couldn't see it there either

**Comment by mah11** [comment]
see https://github.com/pombase/curation/issues/2173#issuecomment-416550148

**Comment by ValWood** [comment]
I think you already told me this ;) Durr.

**Comment by mah11** [comment]
remembering what I said and where is how I keep my job ;)
