### ISSUE TITLE
chp2 is not annotate to SHREC complex

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2183]
A fraction of the Clr3 protein joins the Snf2-related chromatin-remodeling factor Mit1, the Zn-finger-containing protein Clr1, the CD protein Chp2, and the Clr2 protein to form the SHREC complex [12,13].

**Comment by mah11** [comment]
chp2 is in SHREC2 but not SHREC (see https://github.com/geneontology/go-ontology/issues/16400 & PMID:19111658)
