### ISSUE TITLE
protein stabilization 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2190]
- [x]  hsp78 | SPBC4F6.17c | mitochondrial heatshock protein Hsp78 (predicted)
(removed ISS, seems incorrect)

sty1 | SPAC24B11.06c | MAP kinase Sty1
has input srk1 during single-celled organism vegetative growth phase | IMP | López-Avilés S et al. (2008)

(Maybe this is more of a function?)

**Comment by ValWood** [comment]
no action until
https://github.com/geneontology/go-ontology/issues/16360

**Comment by Antonialock** [comment]
https://github.com/pombase/curation/issues/2190
Well, it does seem to stabilise the protein (protects it from degradation during non stressed conditions), but maybe that's not interesting to capture? I removed since you don't think the term sounds right.

**Comment by Antonialock** [comment]
Well, it does seem to stabilise the protein (protects it from degradation during non stressed conditions), but maybe that's not interesting to capture? I removed since you don't think the term sounds right.

**Comment by ValWood** [comment]
in this case the term used should  be related to  degradation or catabolism?

**Comment by Antonialock** [comment]
do you think it should be annotated to neg reg of catabolism or degradation?

**Comment by ValWood** [comment]
that sounds correct for stability (if that is why)

**Comment by ValWood** [comment]
actually, no, lets leave this
