### ISSUE TITLE
make slim more specific under "multicellular organismal process"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2194]
"multicellular organismal process"

NOT REQUIRED FOR PAPER

from
https://github.com/pombase/curation/issues/2066

**Comment by Antonialock** [comment]
what is this ticket about?

**Comment by ValWood** [comment]
It won't be such a big job

These 723 identifiers were not annotated in the slim, but they had non-root annotations that were not in the slim: 

It bumps the current "BP but no slim" up by ~200

**Comment by ValWood** [comment]
replaced by https://github.com/pombase/curation/issues/2206
