### ISSUE TITLE
human ortholog

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2198]
The TRAPPC was precipitated through the Flag tag and blotted for endogenous TRAPPC4 and TRAPPC12 subunits. In the absence of TRAPPC13, TRAPPC2 was still able to bind to TRAPPC4 and TRAPPC12, indicating that the overall architecture of TRAPPC is likely not disrupted upon TRAPPC13 depletion (Fig. S1B). Interestingly, Trs65p, a non-essential yeast protein with homology to TRAPPC13, is required for TRAPPII oligomer stabilization but does not disturb association of other TRAPPII-specific subunits 

28536105

**Comment by ValWood** [comment]
yep I'll go with that one....

**Comment by ValWood** [comment]
note to self, see if families can be linked to confirm

**Comment by ValWood** [comment]
http://www.ebi.ac.uk/interpro/entry/IPR010378/taxonomy
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR28159

yep...Nice one.... We haven't had one of those for ages. I  havn't even looked at the alignment but I'm sure its right...

**Comment by ValWood** [comment]
included
