### ISSUE TITLE
human gene annotatable 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2203]
These look obviously annotatable via ISS based  on product description
We need to provide a separate spreadsheet of ISS for these, then, if necessary this can be adjusted if required during review.

A0A1B0GW35
A5YM69
A6NGE4
A6NLU5
B4DZS4
O43402
O60308
P0C7Q5
P0C7Q6
P0C7V8
P0CK96
P0DP72
P0DPA2
Q3SXM0
Q5H9J9
Q5JWF8
Q5SRI9
Q5SZL2
Q5T1B0
Q5TBK1
Q5UCC4
Q5VSG8
Q5VW00
Q5VWI1
Q67FW5
Q6GMV3
Q6ICL7
Q6NUT3
Q6T311
Q6ZSS7
Q7Z769
Q86VR7
Q86Y79
Q8IW00
Q8IWD5
Q8N0Z9
Q8N4U5
Q8N6S5
Q8N808
Q8N8L6
Q8NBP5
Q8NDC0
Q8TBE7
Q8TC94
Q8TDY3
Q8WV83
Q96GE4
Q96IQ7
Q96K17
Q96K37
Q96KT7
Q96M02
Q9BQ75
Q9BYD9
Q9C0F1
Q9H7M9
Q9NRP2
Q9NUJ3
Q9NYJ1
Q9UG63
Q9Y3B6
Q9Y4F5

**Comment by ValWood** [comment]
false alarm

**Comment by ValWood** [comment]
Actually, no we DO need to annotate these. The are currently classed as "unknown'

**Comment by ValWood** [comment]
not enough info to annotate these


A0A1B0GW35 | EXOC1L |  
-- | -- | --
A5YM69 | ARHGEF35 |  
A6NGE4 | DCAF8L1 |  
A6NLU5 | VSTM2B |  
B4DZS4 | TCP11X1 |  
Q5H9J9 | TCP11X2 |  
Q5SZL2 | CEP85L |  
O60308 | CEP104 |  
Q96GE4 | CEP95 |  
Q9Y4F5 | CEP170B |  
Q96GE4 | CEP95 |  
Q9C0F1 | CEP44 |  
P0C7Q5 |   |  
P0C7Q6 |   |  
P0C7V8 | DCAF8L2 |  
P0DP72 | VSIG10L2 |  
P0DPA2 | VSIG8 |  
Q3SXM0 | DCAF4L1 |  
Q5JWF8 | ACTL10 |  
Q5TBK1 | N4BP2L1 |  
Q5VSG8 | MANEAL |  
Q5VW00 | DCAF12L2 |  
Q5VWI1 | TCERG1L |  
Q67FW5 | B3GNTL1 |  
Q6GMV3 | PTRHD1 |  
Q6T311 | ARL9 |  
Q86VR7 | VSIG10L |  
Q86Y79 | PTRH1 |  
Q8IW00 | VSTM4 |  
Q8N0Z9 | VSIG10 |  
Q8N4U5 | TCP11L2 |  
Q8N6S5 | ARL6IP6 |  
Q8N808 | SLC35G3 |  
Q8N8L6 | ARL10 |  
Q8NDC0 | MAPK1IP1L
Q8TBE7 | SLC35G2 |  
Q8TC94 | ACTL9 |  
Q8TDY3 | ACTRT2 |  
Q8WV83 | SLC35F5 |  
Q96IQ7 | VSIG2 |  
Q96K17 | BTF3L4 |  
Q96KT7 | SLC35G5 |  
Q96M02 | C10orf90 |  
Q9BYD9 | ACTRT3 |  
Q9H7M9 | VSIR |  
Q9NUJ3 | TCP11L1 |  
Q9NYJ1 | COA4 |  
Q9UG63 | ABCF2 |  

I'll porvide a spreadsheet for the rest.

**Comment by ValWood** [comment]
file attached.

@Antonialock  we don't need to refer to these in the paper.
we can add them in review if we need to change anything, otherwise it's not important.

However, when you send your annotations to uniprot can you add these on?
[human.txt](https://github.com/pombase/curation/files/2453932/human.txt)

**Comment by ValWood** [comment]
DId these get included in the spreadsheet?

**Comment by Antonialock** [comment]
Nope sorry, the 'unknowns' label would have helped.

I added the ones that are ticked off in this ticket. 
https://github.com/pombase/curation/issues/2192

**Comment by ValWood** [comment]
no worries, keep this open with no action. I will pass the list to pascale (to PAINT)
