### ISSUE TITLE
wee1  multigene allele check

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2204]
wee1-50 (G850E aa) wee1-50 (G850E aa)
https://www.pombase.org/reference/PMID:7262540

might be  wee1-50 (G850E aa) diploid?

**Comment by ValWood** [comment]
Also 

cdc2-l67(C67laa wee1-50(G850E aa)
AND
cdc2-L67(C67Laa wee1-50(G850E aa)


fix but do we need a check for same case alleles?

**Comment by ValWood** [comment]
Well this is weird anyway, it can't be a I and an L at cdc2 pos 67 ...

@JackyVH

**Comment by ValWood** [comment]
Oh got it....derr

**Comment by mah11** [comment]
The wild-type allele has Cys at that position. Both mutant alleles are named for the residue that Cys has been changed _to_.
