### ISSUE TITLE
M-specific trancription factors

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2207]
These no longer slim, but they have some annotations, should they?

mat1-Mi | SPBC23G7.17c | M-specific trancription factor Mi
mat3-Mi | SPMTR.03 | silenced M-specific trancription factor Mi

**Comment by Antonialock** [comment]
I can probably cram out an annotation from an old paper, but this should also be fixed by
#2209 

remember that we do not want mat3-Mi annotated....we could change it's gene type from 'protein coding' to something else? @mah11 suggested some other SO term in a separate discussion?

Problem is genes at mat2.

**Comment by mah11** [comment]
>  @mah11 suggested some other SO term in a separate discussion?

might've been this - https://github.com/pombase/curation/issues/2136#issuecomment-411448468

**Comment by Antonialock** [comment]
mat3-mi isn't expressed....mat1-mi is the expressed copy. 
Do you want the nonexpressed gene to have MFs?

**Comment by ValWood** [comment]
not necessarily, but these appear as protein coding genes in the list download. This needs to change, is there a ticket about this?

**Comment by Antonialock** [comment]
there's https://github.com/pombase/website/issues/1304 for the duplicated copies.

what should I change the type to? I think they should have gene pages
they are not exactly "protein coding genes", they are "protein coding gene templates"

**Comment by Antonialock** [comment]
@kimrutherford

**Comment by ValWood** [comment]
we can change it to a misc_feature, and add the appropriate SO term (this is how we describe other non-gene features).

However this feature has associated phenotypes annotated, so it might break things to change to a misc_feature right now (@kimrutherford ?)

In the meantime, you can check that there is a sensible SO term to use.

**Comment by Antonialock** [comment]
well there is SO:0000127 silenced_gene ?

**Comment by ValWood** [comment]
That would work.

**Comment by Antonialock** [comment]
so at last there are only 2 mat1 genes, 2 mat2 genes and 2 mat 3 genes....hopefully there will be no unexpected issues from it.

**Comment by Antonialock** [comment]
I updated this FAQ https://github.com/pombase/website/blob/master/src/docs/faq/how-are-the-mating-type-specific-gene-pages-organized.md
