### ISSUE TITLE
cell cycle switching, mitotic to meiotic

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2212]
Follow on from #2209

a number of genes annotated to
cell cycle switching, mitotic to meiotic (and signal transduction involved in cell cycle switching, mitotic to meiotic)

for this axis:

matpi/matmi upregulates mei3
mei3 inhibits pat1
inhibition of pat1 activates mei2/sme2
mei2/sme2 somehow activates mei4
mei4 is needed to proceed into meiosis I (I think cells can do premeiotic DNA replication without it but not proceed into meiosis)

this should perhaps change
signal transduction involved in positive regulation of meiosis I?

**Comment by ValWood** [comment]
So is it regulating the interphase to meiotic prophase I transition? (i.e entry into meiosis I??)

**Comment by Antonialock** [comment]
I can't say for sure...I need to read more about it

**Comment by Antonialock** [comment]
I want to do an overhaul of all the mating annotation...just need to find the time!

**Comment by Antonialock** [comment]
good to have tickets so I don't forget.

**Comment by ValWood** [comment]
activation of meiosis (GO:0090427)?

**Comment by Antonialock** [comment]
Yeah just need to make sure it is not more upstream....need to have a read

**Comment by Antonialock** [comment]
activation of meiosis (GO:0090427) "Any process that starts the inactive process of meiosis"....this doesn't sound right, meiosis is not inactive, it's suppressed?

**Comment by Antonialock** [comment]
I'm more happy with the current term selection, than changing to activation
