### ISSUE TITLE
Results for: DNA-binding transcription activator activity, RNA polymerase II-specific (GO:0001228)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2215]
we only have 38 genes annotated to this, most are at the parent, and need moving down to activator (anything with +ve regulation of transcription for starters)

**Comment by ValWood** [comment]
- [x]  rst2
 - [ ]  sep1
- [ ] pho7
- [ ]  pap1
- [ ]  map1
- [ ] cuf1
- [ ]  cdc10


adn3 | SPCC1494.10 | transcription factor Adn3
atf21 | SPBC2F12.09c | transcription factor, Atf-CREB family Atf21
atf31 | SPAC22F3.02 | transcription factor Atf31
bur6 | SPAC17G8.03c | transcription regulator complex subunit Bur6 (predicted)
cha4 | SPBC1683.13c | transcription factor Cha4 (predicted)
cuf2 | SPCC584.02 | middle-meiotic transcription factor Cuf2
esc1 | SPAC56F8.16 | transcription factor Esc1 (predicted)
fhl1 | SPAC1142.08 | forkhead transcription factor Fhl1
gsf1 | SPBC15D4.02 | transcription factor, zf-fungal binuclear cluster type Gsf1
hsf1 | SPAC2E12.02 | transcription factor Hsf1
hsr1 | SPAC3H1.11 | transcription factor Hsr1
mbx1 | SPBC19G7.06 | MADS-box transcription factor Mbx1
mbx2 | SPBC317.01 | MADS-box transcription factor Pvg4
mca1 | SPAPB1A11.04c | transcription factor, zf-fungal binuclear cluster type Mca1
moc3 | SPAC821.07c | transcription factor Moc3
pcr1 | SPAC21E11.03c | transcription factor Pcr1
phx1 | SPAC32A11.03c | stationary phase-specific homeobox transcription factor Phx1
rap1 | SPBC1778.02 | shelterin complex telomere binding subunit Rap1
rsv1 | SPBP4H10.09 | transcription factor Rsv1
rsv2 | SPBC1105.14 | transcription factor Rsv2
scr1 | SPBC1D7.02c | transcription factor Scr1
sre2 | SPBC354.05c | membrane-tethered transcription factor Sre2
zip1 | SPAC25G10.03 | transcription factor Zip1

**Comment by ValWood** [comment]
Done except for 

- [ ]  map1  (Activator)
- [ ] pho7 (Activator?)

@Antonialock  could you do these as  yyou looked at the sessions?

I'll  move bur6 to a new ticket.

**Comment by Antonialock** [comment]
done
