### ISSUE TITLE
disease ontology oddities

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2222]
these need weeding out from our annotations (associations from GWAS studies)

http://pombase-dev.bioinformatics.nz/reference/PMID:23934111

this is causing some of the differences between our neurological disorders and malacards.

**Comment by ValWood** [comment]
but there are also clearly 
associations missing from malacards:
http://pombase-dev.bioinformatics.nz/gene/SPBC947.01

**Comment by ValWood** [comment]
seems a bit crazy:

60 | (disease of metabolism (DOID:0014667) AND metabolic disorders (PBO:0025419)) | ...
-- | -- | --
  | 147 | disease of metabolism (DOID:0014667) | ...
  | 144 | metabolic disorders (PBO:0025419)

but maybe because of the ones which do not map...

**Comment by Antonialock** [comment]
could we try to add different tickets for different tasks or I get really confused wrt what I have done and not?

**Comment by ValWood** [comment]
Well, I'm not really sure  exactly what the tasks are at this point, but yes separate them out if you want.

**Comment by Antonialock** [comment]
epilepsy annotations are ok. 

SPAP14E8.03, muscular dystrophy seems ok, it comes from clinvar https://www.ncbi.nlm.nih.gov/clinvar/?term=(GOSR2[Gene%20Name])%20AND%20Muscular%20Dystrophy
also PMID:29855340

dbl8 ALS annotation is ok (loads of genes have pathogenic ALS variants from memory)
https://www.omim.org/entry/608465?search=setx&highlight=setx
