### ISSUE TITLE
 unknowns paper urgent

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2223]
- [x]  @Antonialock confirm the slim used to create the .tab files is the one in SUPP table 1

- [x]  @Antonialock  document changes to the final  slim in 
https://docs.google.com/document/d/1LVu3e8R2GmqS63KhAcjSbkBMngJ-y0Nd8uyBuWw0gFk/edit
(the documented slim is  smaller than the submitted slim)

- [x]  @ValWood prepare a list of  S. cerevisiae unknowns
(the safest way to do this is to extract the inverse of the slimmed IDs from the slim.tab file in the absence of the saved list)
the S. cerevisiae list is here (979 entries is that correct for the histogram?)
[sc_unknowns.txt](https://github.com/pombase/curation/files/2545798/sc_unknowns.txt)

- [x]  @ValWood prepare a list of  S. pombe unknowns 

- [x]  @Antonialock prepare a list of  human unknowns
[human unknowns.txt](https://github.com/pombase/curation/files/2562561/human.unknowns.txt)

-  [x]  @ValWood  update flow diagram with correct number (do we quote the number of terms in the slim in the text?)

- [ ]  @mah11  add unknowns lists to supplementart and repackage 

Also when reading the paper, is you wanted one of the SUPP tables you have to look at them all to find the one you are interested in . Is there any way we can indicate which range of SUPP files contains which datasets?)

**Comment by ValWood** [comment]
This will get the slimmed IDs from  the tab file

cut -f 3 -d % final_S6_SP_slimTab\ \(1\).txt | perl -p -e 's/,/\n/g' |perl -p -e 's/\t//g' |perl -p-e 's/ //g'| cut -f 3 -d % final_S6_SP_slimTab\ \(1\).txt | perl -p -e 's/,/\n/g' |perl -p -e 's/\t//g' |perl -p -e 's/ //g' |sort |uniq |wc

pombe     4394  

(Its actually 4393 because the first line needs removing).

This is a slight problem because this  slim is using the  GO database and not our data, so the numbers  don't agree with my figure 4 (Because of the inclusion of PAINT data).
So there are 38 fewer unknowns in here than there should be.
When we have the final slim I will rerun the pombe  slim with our GAF from the same day which will reduce the difference (I have queried most of these PAINT annotations).

**Comment by mah11** [comment]
> Also when reading the paper, i[f] you wanted one of the SUPP tables you have to look at them all to find the one you are interested in . Is there any way we can indicate which range of SUPP files contains which datasets?)

The LaTeX/preprint version that I emailed you includes a list with brief file descriptions in the main text. (I'm not sure the google drive is up to date for that file, so I'll copy it over again now just in case. This illustrates why I think we should have manuscripts-in-prep under real version control, not in google drive.)

For the Science submission, that list went into the separate "supplementary materials" doc, per their instructions. We could copy it back in to the main text for Open Biology if that's OK by their guidelines.

Also let me know if the supp description list needs updating based on other things in this ticket.

**Comment by mah11** [comment]
> do we quote the number of terms in the slim in the text?

no

**Comment by ValWood** [comment]
- [ ]   check openbiology submission format.
May need to change naming of SUPP files in text

- [ ]  update @mah11  if the supp description list needs updating based on other things in this ticket.

**Comment by Antonialock** [comment]
I updated 
Wood_unknowns_table_S1
https://docs.google.com/spreadsheets/d/15K6iP-F7_R5PqQ8nK1UUCPnm0PoNVhoql7ByeG-uGv0/edit#gid=155457003
@mah11 

the other supp table 1s will need updating too (the xls and tsv files)? Unless they are cleverly linked....I can't check, things go horribly confusing when I try to open these.

**Comment by mah11** [comment]
There's no linking; I just downloaded the google spreadsheets and saved in the other formats.

**Comment by Antonialock** [comment]
yeah I think I'm spawning new docs when I tried to open them. I'll try and delete these

**Comment by mah11** [comment]
it's bonkers, innit?

**Comment by Antonialock** [comment]
yes, sorry, I think I deleted the right one. I  don't think (/hope) I was editing in two places....it should be fine now

**Comment by ValWood** [comment]
I think somebody tidied up and moved your S1 back (I had moved the exisitng one to the archive).

So just to confirm. S1 is now the current list. I can go from there.

**Comment by ValWood** [comment]
I will double check it all.

**Comment by ValWood** [comment]
I checked the  "explainer"
This all looks reasonable but there were still duplications.


GO:0008380 RNA splicing in twice
GO:2000001 regulation of DNA damage checkpoint
GO:0006576 cellular biogenic amine metabolic process
GO:0009636 response to toxic substance 
GO:0048870 cell motility

I removed these which leaves 110

However in  Supp table 1
https://drive.google.com/drive/folders/1pGfAkCdGha6A1-g1UFZZPu42mQBow0nt

There are 119 terms? I will check this next...

**Comment by ValWood** [comment]
There was only one duplicate in the spreadsheet so there is still a difference
GO:0006575

**Comment by ValWood** [comment]
GO:0006605	biological_process	protein targeting
GO:0016192	biological_process	vesicle-mediated transport
GO:0006913	biological_process	nucleocytoplasmic transport
GO:0055085	biological_process	transmembrane transport
GO:0030437	biological_process	ascospore formation
GO:0000747	biological_process	conjugation with cellular fusion
GO:0140013	biological_process	meiotic nuclear division

**Comment by ValWood** [comment]
This is fine. They were swapped out for less general terms for human, but nothing we say about unknowns will be wrong if we include them.

Now I only need to derive the unknown sets, and check if the final terms made any difference to the SGD slim.

**Comment by ValWood** [comment]
I extracted the human "unknowns" by extracting all of the IDs in the slim, and subtracting them from the total.

I get 3382
[human_unknown.txt](https://github.com/pombase/curation/files/2563060/human_unknown.txt)
@Antonialock  can you confirm that this agrees with the number you reported to get the %'s?

Q should we report the actual numbers in the histogram legend? I don't think we say them anywhere?

**Comment by ValWood** [comment]
@Antonialock  I see you also prepared a file. I can't parse this with unix? it seems to have some funny encoding even when saved as plain text, so I can't parse with unix commands.
Could you upload a plain text version? It says it is  plain text when I open in textedit?

**Comment by ValWood** [comment]
@kimrutherford  can you make Antonia's file attached to first comment 
human unknowns.txt unix parsable?
I can't figure out what the problem is and I want to compare to mine.

**Comment by kimrutherford** [comment]
human_unknown.txt seems OK to me.  The content is normal text with UNIX line endings.

**Comment by ValWood** [comment]
Weird. When I "cat" it I only see the end line....

**Comment by ValWood** [comment]
anyway 3382/3383 I can live with that.... it's probably a header line somewhere... we have the same list...

**Comment by ValWood** [comment]
OK, lets see how that goes...
