### ISSUE TITLE
pombe data not getting to GO?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2224]
Sandra just reported that
https://www.pombase.org/reference/PMID:30089908
annotations are not in GO.

Is the update pipeline working?

 @mah11  can you double check before I open a GO ticket?

**Comment by mah11** [comment]
Annotations from PMID:30089908 are in the GAF that has been at the location where GO's supposed to get it since 15 Oct. Open the GO ticket, unless it's expected to take that long to percolate ...

**Comment by ValWood** [comment]
that is probably OK. I think Amigo is updated monthly now. I'm not sure which day that happens.
