### ISSUE TITLE
 Get journal recommendations to get biosharing/fairsharing "recommended" tag

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2226]
Try
Elsevier, PLOS, and Springer Nature's Scientific 

See e-mail thread from Pete.

**Comment by kimrutherford** [comment]
Or maybe try Wellcome?

**Comment by ValWood** [comment]
> FlyBase has been recommended by Elsevier, PLOS, and Springer Nature's Scientific Data.

**Comment by ValWood** [comment]
Moved to furture doc
