### ISSUE TITLE
large and small daughter nuclei.

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2244]
check annotation

**Comment by Antonialock** [comment]
didn't we do that in the curator meeting? maybe not..

**Comment by ValWood** [comment]
I think I just need to check. I think cut8? and something else (fatty acid synthase related), need to move down to the new more specific term.... I will remember when I look......

**Comment by ValWood** [comment]
mitotic catastrophe with abnormal nuclear envelope partitioning FYPO:0006691

is the correct term

**Comment by ValWood** [comment]
I'm a bit confused by this. I need to ask @JackyVH  again.

I thought that Jacky said that large and small daughter cells had no chromosome segregation defect but  it seems that the chromosomes don't separate and all end up in one nucleus?


Two fission yeast temperature-sensitive mutants, cut6 and lsd1, show a defect in nuclear division. The daughter nuclei differ dramatically in size (the phenotype designated lsd, large and small daughter). Fluorescence in situ hybridization (FISH) revealed that sister chromatids were separated in the lsd cells, but appeared highly compact in one of the two daughter nuclei. EM showed asymmetric nuclear elongation followed by unequal separation of nonchromosomal nuclear structures in these mutant nuclei. The small nuclei lacked electron-dense nuclear materials and contained highly compacted chromatin. The cut6+ and lsd1+ genes are essential for viability and encode, respectively, acetyl CoA carboxylase and fatty acid synthetase, the key enzymes for fatty acid synthesis. Gene disruption of lsd1+ led to the lsd phenotype. Palmitate in medium fully suppressed the phenotypes of lsd1. Cerulenin, an inhibitor for fatty acid synthesis, produced the lsd phenotype in wild type. The drug caused cell inviability during mitosis but not during the G2-arrest induced by the cdc25 mutation. A reduced level of fatty acid thus led to impaired separation of non-chromosomal nuclear components. We propose that fatty acid is directly or indirectly required for separating the mother nucleus into two equal daughters.
--

**Comment by mah11** [comment]
That's why we needed three terms. Read the definitions for FYPO:0006715 and its two subclasses, FYPO:0000284 and FYPO:0006716.

**Comment by mah11** [comment]
p.s. I'll add more to the FYPO:0000284 definition to make it more explicit that that one has a chromosome segregation problem, but it's already there in the name and links.

**Comment by ValWood** [comment]
so I use FYPO:0006716 for cut6 and fas2. Got it...

**Comment by ValWood** [comment]
cut6 has 

cut with abnormal chromosome segregation
PMID:16453724
PMID:27687771
PMID:29931271
PMID:8769419

which must be incorrect too.

**Comment by ValWood** [comment]
arggh, I'm so confused

cut6 does have a chromosome segregation defect
Two fission yeast temperature-sensitive mutants, cut6 and lsd1, show a defect in nuclear division. The daughter nuclei differ dramatically in size (the phenotype designated lsd, large and small daughter). Fluorescence in situ hybridization (FISH) revealed that sister chromatids were separated in the lsd cells, but appeared highly compact in one of the two daughter nuclei

@JackyVH  what is the difference between  cut6 and fas2 and the other cuts?

**Comment by ValWood** [comment]
@JackyVH

**Comment by ValWood** [comment]
done! goodbye!
