### ISSUE TITLE
add disease association 30389790

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2246]
needs adding
https://www.ncbi.nlm.nih.gov/pubmed/30389790

from @ValWood  I think this is the type of study that WormBAse explicity classifies as a 'disease model"

**Comment by Antonialock** [comment]
@ValWood 

I guess it depends on what you mean by a disease model?

I don't know about wormbase but at healx a disease model is more than knocking out the gene mutated in disease and seeing what's going on.

For us a disease model is a strain + an assay + a phenotype (readout) = 
This means that you can test drugs in it.

The phenotype could be anything - cell growth in cancer cells, a behavioural mouse phenotype for neurological disorders, or a biochemical readout. 

If by 'disease model' wormbase means any strain that has a mutation that causes disease...yeah then we have loads of these... 
The

**Comment by ValWood** [comment]
I misread the abstract.

 Golgi expression of human endomannosidase partially restored normal growth in Δgls1-S cells. We propose that accumulation of G3M9-bearing glycoproteins is toxic and at least partially responsible for defects observed in MOGS-CDG.

I was thinking that they somehow shoed that the specific mutation was related to the disease variant, but they don't.

but what you say above  is what I'm trying to tease apart. Things can be models at different levels. A  set of qualifiers might be useful here (this is what I suggested to WormBAse. Their "disease model'  is stricter. Probably like HealX one but I could not establish precisely what it was (criteria). It was more than phenotype (qualiier=potential model?).

This should probably be its own ticket ;) 

Decide qualifiers for different levels of disease model....

**Comment by ValWood** [comment]
The disease assoication in this ticket was added.

I'll open a  new ticket to thrash out different level/types of gene models
