### ISSUE TITLE
seems odd that ngg1 binds klp is  this correct. 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2259]
I don't see ngg1 in abstract

**Comment by mah11** [comment]
Yep, they call ngg1 "kap1", and show the interaction data in figure 6. We don't call anything else kap1, but ngg1 has it as an "obsolete name". Do you want to change it to a synonym? (We do have the krp1 alias they use for klp3.)

**Comment by ValWood** [comment]
yeah should prob have as a synonym, not obsolete.

**Comment by mah11** [comment]
done, so closing
