### ISSUE TITLE
looking for powerpoint in drop box

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2260]
I'm looking for the powerpoint that I used for this

![pptx](https://user-images.githubusercontent.com/7359272/49331650-c0022400-f598-11e8-829b-e60eec6f0dd8.jpg)

I thought it was in the drop box, but it isn't there (I can't find the figure either so I'm not sure I'm in the correct directory)

anyway it would be good to refresh the background to  this, so it looks like something happened this year

![update figure](https://user-images.githubusercontent.com/7359272/49331681-f9d32a80-f598-11e8-9402-9d8082817d09.jpg)

**Comment by mah11** [comment]
unless you changed the file name, you only put the .jpg in the dropbox
(Dropbox/pombase/frontpage_rotations/community\ curation\ feed/papers\ curated.jpg)

**Comment by ValWood** [comment]
no worries I'll leave as it is for now.

**Comment by ValWood** [comment]
google drive...
