### ISSUE TITLE
negative regulation of response to iron starvation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2263]
I don't understand this GO term. Should it be obsoleted?
How can you negatively regulate a reponse?

Only used once, by us: fep1
http://pombase-dev.bioinformatics.nz/gene/SPAC23E2.01
also is this in response to starvation, or replete?
negative regulation of ferrichrome biosynthetic process in response to iron (GO:0097739)

**Comment by Antonialock** [comment]
fep1 also has 
negative regulation of transcription from RNA polymerase II promoter in response to iron

maybe that's enough if the other term is confusing? removed.
