### ISSUE TITLE
refine wtf gene structures

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2264]
PMID:30475921

we annotated the gene correctly based on long read RNA seq data from Kuang et al. This is also how the two transcripts were identified.

**Comment by mah11** [comment]
PMID:30475921 
https://curation.pombase.org/pombe/curs/6c6dece2e0762651

**Comment by ValWood** [comment]
I can't find this phrase in PMID:30475921.

I thought @Lilindu published revised  wtf gene structures?

**Comment by lilindu** [comment]
In PMID:28631610, we did publish our annotation of the gene structures of wtf genes as Figure 5—source data 2. However, that annotation was mostly based on Augustus prediction and did not take into account the Iso-Seq data of Kuang et al. For pseudogenes, Augustus tends to introduce errors as it tries to maximize a reading frame. As a result, I think around 10 wtf genes were not correctly annotated in Figure 5—source data 2.

**Comment by ValWood** [comment]
Hi Li Lin.

I was just looking at that dource data. I downloaded a fasta file, but I could not figure it out- it does not seem to be fasta.

It looks like this:

taaggaaagctaagttggggtgaataaaaagggca--gtgacaaaataaatgtgtcag--aagtaatt-cac
tgcctcgttcagttttttcgttcttc-ttttttt------atgccattgtttgaaggaa---ttagttggaa
atttgtttg-aacaattttattattttgttaaaaagtctttaaagcgattgga-attggact----acagag
cgaatattcttgatttcgctgtttcgtttgtcgcaatcacagcaatta------attcg--cgcatgtgttt
tattaaata--------aagaatgatcttgatgaaatgaagaatgattacacttctttgaaaagtcctctag
atgaagaagatg---aattgaagacagatcatgaaa------------------tcgatttggaaaaaggac
cactcccagaatatgattcggaggaagagggcgcattacctccatattcaggtaagaattgta---------
---aataataagaaaggaa------ttactcaatggaaagttgaaacttgccatc-ttgtca----------
------aattgcat-gctttggtca-ttgtttacagtcggc------------catgcaat-gcacacaatt
t------------g-atacatgctc-tttctttact------------------------------------
-----------------------------------------------aaagtatt-tcaatcata-------
-----------------ttaatttaaacagatcacgcactt-------------------------------
----------gtaaataatcctcct---------------aacacacatagagaaaacaatccttcc-----
------------------------aggtcgacagataattctt---------------cccctttcttgata

**Comment by ValWood** [comment]
Do you know if there are coordinates anywhere for the features? This would be easiest.

**Comment by lilindu** [comment]
The plain text format file in Figure 5—source data 2 is meant to be loaded into Jalview as an annotation file for the DNA sequence alignment in Figure 5—source data 1. Please do not bother with that annotation. I will email you a set of updated annotation that has taken into account the Iso-Seq data.

**Comment by mah11** [comment]
> I can't find this phrase in PMID:30475921.

What do you mean by "this phrase"? If it refers to the text in the original ticket summary, that's from the message-to-curators in the PMID:30475921 Canto session (linked above). There's a diagram of reads in figure S3; might have to ask Maria for actual coordinates, or pull them out of PMID:27856494 supplemental data.

**Comment by lilindu** [comment]
PMID:27856494 Supplemental Table S1 seems to have some errors. We have now mapped the Iso-Seq data ourselves and found that looking at the read mapping results on a genome browser provides more reliable understanding of the transcripts.

**Comment by lilindu** [comment]
Dear Val,

My student gave me a bed12 format file (see attachment). Please see whether you can use it. If not, I will ask my student to generate annotation file of a different format, for example, GenBank format.

Best regards,

Li-Lin

**Comment by ValWood** [comment]
I made these changes today:

wtf1
5064305..5066231 pseudo ->  coding
join(5064781..5064919,5065087..5065332,5065380..5065610,5065652..5065705,5065760..5065836)
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"

wtf12
join(1401530..1401668,1401900..1402172,1402490..1402551,1402553..1402672)
to
join(1401530..1401668,1401900..1402172,1402221..1402448,1402490..1402672)
introduces stop codon @274
PMID:28631610

wtf13
complement(join(1580123..1580613,1580650..1581006,1581055..1581327,1581559..1581694))
to
complement(join(1580123..1580268,1580319..1580381,1580422..1580613,1580650..1581006,1581055..1581327,1581559..1581694))
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"

wtf17
complement(join(1805166..1805242,1805299..1805352,1805393..1805614,1805664..1805909,1806076..1806225,1806411..1806450))
to
complement(join(1805166..1805242,1805299..1805352,1805393..1805614,1805664..1805909,1806076..1806214))
/db_xref="PMID:28631610"
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"

wtf18
complement(join(1807004..1807131,1807182..1807244,1807285..1807476,1807513..1807726,1807760..1807836,1807885..1808157,1808396..1808534))
to
complement(join(1807004..1807131,1807182..1807244,1807285..1807476,1807513..1807836,1807885..1808157,1808396..1808534))
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"

wtf22   introduces stop codon @50 (was already pseudo)
complement(join(2109181..2109395,2109432..2109608,2109645..2109923,2109973..2110221,2110391..2110528))
to
complement(join(2109178..2110528,2109178..2109281,2109333..2109395,2109436..2109608,2109645..2109923,2109973..2110221,2110391..2110528))
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"


stop codon @145
wtf24    (was already pseudo)
join(2181204..2181342,2181510..2181758,2181808..2182031,2182077..2182371,2182422..2182504)
to
join(2181204..2181342,2181510..2181758,2181808..2182031,2182077..2182268,2182309..2182371,2182422..2182504)


wtf3 (still pseudo, no methionine)
complement(join(219185..219261,219294..219368,219409..219684,219734..219979,220148..220283)
to
complement(join(219185..219261,219315..219368,219409..219684,219734..219979,220148..220286)
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"

wtf4
complement(join(221199..221335,221395..221457,221498..221689,221726..222016,222065..222337,222566..222701))
to
complement(join(221199..221344,221395..221457,221498..221689,221726..222016,222065..222337,222566..222701))
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"


wtf6 introduces stop codon @25
complement(join(297354..297655,297705..297950,298119..298194))
to
complement(join(297140..297216,297266..297307, 297349..297655,297705..297950,298119..298258))
/pseudo
/colour=13
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"

wtf7
join(320608..320755,320964..321335,321387..321523)
to
join(320617..320755,320964..321335,321387..321523)
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"

wtf8 -> pseudo stop codon @138
join(427445..427583,427752..427997,428072..428290,428336..428527,428568..428630,428681..428763)
to
join(427445..427583,427752..427997,428047..428290,428336..428527,428568..428630,428681..428763)
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"

wtf2 (still pseudo)
complement(join(593188..593261,593311..593368,593437..593575)
to
complement(join(593185..593261,593393..593368,593437..593575)
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:28631610; date=20200501"


no change
wtf10
wtf11
wtf14
wtf15
wtf16
wtf19
wtf20
wtf21
wtf23
wtf25
wtf5
wtf9

Committed revision 6246.

I will ask Maria to confirm these changes  based on their data and add 
/controlled_curation="term=warning, gene structure updated; db_xref=PMID:30475921; date=20200501"
as support for  the Zanders's lab  annotation.

Therefore although the above changes should appear in PomBase tomorrow they may require final tweaks.

@mar these will need adding to 
https://www.pombase.org/status/gene-coordinate-changes
once we have the final set.

**Comment by ValWood** [comment]
still to look at:



II	blank	transcript	1804234	1804472	.	-	.	transcript_id "wtf7-frag;
III	blank	transcript	1932673	1933026	.	-	.	transcript_id "wtf20-frag;
II	blank	transcript	2163229	2163347	.	-	.	transcript_id "wtf25-frag;

**Comment by ValWood** [comment]
Maria says  all these are correct.

I added these additiona refs:

PMID:30475921 for wtf13 and wtf18, and we also reported the structure for the other S. pombe wtf genes using Kuang et al data and are reported in PMID:30991417 (Supp Fig 1).

**Comment by lilindu** [comment]
I wonder whether PomBase can allow multiple transcript isoforms to be annotated. For four wtf genes in the reference genome, wtf4, wtf13, wtf19, and wtf23, a transcript isoform starting from within intron 1 is expressed and is the "poison" isoform that can cause the spore killing effect. Both the Zanders lab (PMID:30475921) and us (unpublished results) have found that wtf13 is an active killer in the reference strain, and thus at least for wtf13, this alternative isoform is biologically relevant.

**Comment by ValWood** [comment]
Hi @lilindu  we plan to add this for functional isoforms. For now we have been collecting examples https://github.com/pombase/curation/issues/61
and ignoring them.
We need need to make a few changes (not fully specified yet),  to display them on the website.

For wtf it is pretty important to get this working. We can use the wtfs to test.

Can you provide the coordinates of the known functional transcripts. Are these sense strand RNAs (I forget)...

I think we can create transcript features and give them transcript IDs and I suspect these will load into the Chado curation database, and the browser OK.

Then we will probably only need to think about how to represent on gene pages.

I can't think now why I thought this might be complicated. Probably some of the issues have gone away since we don't use Ensembl.

@kimrutherford

**Comment by mah11** [comment]
What is the task for me here?

**Comment by ValWood** [comment]
Just the 
https://www.pombase.org/status/gene-coordinate-changes

**Comment by mah11** [comment]
That is a website task, so I have opened https://github.com/pombase/website/issues/1507

**Comment by ValWood** [comment]
Products currently look like this:
https://www.pombase.org/term_genes/PBO:0002829
If we keep as wtf element and only update to

wtf meiotic driver or
wtf meiotic drive-related element
 once tested.

I don't think all would be correctly labelled though?

The pseudogenes are also inconsistently labelled (although I though I fixed that yesterday)

**Comment by ValWood** [comment]
I forgot to commit my changes. It will look better tomorrow...

**Comment by mah11** [comment]
Re product descriptions - I agree, we shouldn't call them all meiotic drivers because some have been tested and shown *not* to do meiotic drive. Also, some only do the suppression part, i.e. make antidote but not poison ...

**Comment by lilindu** [comment]
Yes, the "poison" transcript is also sense strand transcript and the reading frame is the same as the longer and already annotated "antidote" transcript. Maybe I should not have used the term "transcript" in my request of adding the annotation of the "poison" isoform. The wtf annotation file I sent you contains CDS annotations, not transcript annotations, as the first and the last exons are "coding exons" and do not correspond to the exons in the transcript. Thus, I think what I hope to add to the PomBase annotation is the annotation of the "poison" CDS.

For the "poison" transcripts of wtf4 and wtf13, the start codon of the "poison" CDS is inside intron 1. For the "poison" transcripts of wtf19 and wtf23, the start codon of the "poison" CDS is inside exon 2. Below are the coordinates of the first nucleotide of the start codon of the "poison" CDS for each of these 4 genes that are capable of expressing "poison" product:
wtf4: 222347
wtf13: 1581337
wtf19: 2018097
wtf23: 2146142

**Comment by ValWood** [comment]
I'll close this and make a dedicated ticket to annotate the poison isoform.
