### ISSUE TITLE
php4 hould have repressor activity

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2267]
Php4, which induced under low-iron conditions and acts as a negative regulatory subunit of the constitutively expressed CCAAT binding Php2/Php3/Php5 heterotrimer (Labbe et al., 2013; Labbe et al., 2007).
When iron is replete, Php4 dissociates from the CCAAT binding factor and translocates into cytosol, and genes involved in iron utilization are up-regulated, whereas genes involved in iron acquisition are repressed by Fep1 (Labbe et al., 2013).

**Comment by Antonialock** [comment]
fixed, curated PMID:18223116
