### ISSUE TITLE
disease association (disease 'models')

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2269]
from val
needs adding
https://www.ncbi.nlm.nih.gov/pubmed/30389790
I think this is the type of study that WormBAse explicity classifies as a 'disease model"

**Comment by Antonialock** [comment]
I think anything where a cell line or animal recapitulates an aspect of a disease, or allows testing of a disease can be thought of as a model

I think for pombe you'd need the correct mutations at the minimum...

in animals a lot of CROs seem to be happy to use any old mouse that display a phenotype that resembles the human phenotype (and are not fussed about what triggers the phenotype for example the mice don't need to have the same genetic mutations as human....I suspect this is one reason why stuff don't translate well from mice to human...)

**Comment by ValWood** [comment]
PMID: 29655802 Charcot-Marie-Tooth disease
https://www.pombase.org/gene/SPBC17A3.04c

**Comment by ValWood** [comment]
this is an example of a 'disease' model too. It's cerevisiae, but I presume this would also apply...
https://www.ncbi.nlm.nih.gov/pubmed/30530630?dopt=Abstract

it might be worth speaking to Sara Mole and doing a 'mini-project" on this...
