### ISSUE TITLE
which mitochondrial membrane?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2271]
integral component of mitochondrial membrane

- [x] ppr4 extrinsic, inner
- [x] ppr5 mitochondria only
-  [x] SPAC1834.10c inner
- [x]  SPBC27B12.14 integral component of mitochondrial inner membrane from human

**Comment by ValWood** [comment]
pet117
extrinsic component of matrix side of mitochondrial inner membrane

**Comment by ValWood** [comment]
SPBC27B12.14
- [ ]  A mutation in the human CBP4 ortholog UQCC3 impairs complex III assembly, activity and cytochrome b stability.

**Comment by ValWood** [comment]
Also disease association  SPBC27B12.14
Complex III deficiency is a severe multisystem disorder
PMID: 25008109

**Comment by ValWood** [comment]
@Antonialock Antonia I'll sign over to you to add the disease association

**Comment by Antonialock** [comment]
Ive put it on my list of ones to add once we have the new system
DOID:0080118

**Comment by ValWood** [comment]
OK closing then
