### ISSUE TITLE
 interactions involving genomic loci

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2272]
From Maria

"there are starting to appear papers where they performed HiC, 4C… and there are descriptions of interactions between different loci of the genome. It might be too complicated to implement in pombase but I think this is really informative data. might be worth to have a thought about it in your next meeting."

**Comment by ValWood** [comment]
yeah we can look for webservices to host.

Mark moved to the team at the EBI developing these, but I can't find anything.

we can see if this group plans to introduce any web applications...
https://bmcresnotes.biomedcentral.com/articles/10.1186/s13104-018-3507-2

**Comment by ValWood** [comment]
Moved to "future" doc
