### ISSUE TITLE
process not correctly described, urease accessory proteins

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2275]
PMID:12471450

which are required for the insertion of the nickel ion at the active site,

**Comment by ValWood** [comment]
Assigning to you since the process might be analogous to iron insertion?

Absolutle no hurry for this but might be interesting to do with the iron stuff

**Comment by Antonialock** [comment]
Requested 
Protein maturation by nickel ion transfer

Add to ure4,6,7

https://github.com/geneontology/go-ontology/issues/17378

**Comment by Antonialock** [comment]
added.
