### ISSUE TITLE
opa3 broken link

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2278]
BP ISO to MGI, find correct linking format

**Comment by ValWood** [comment]
I forget where to look!

**Comment by ValWood** [comment]
I knew it was wacko....

**Comment by mah11** [comment]
OK, I've committed the double-prefix workaround. I'll close this if that fixes it in the next update.

**Comment by mah11** [comment]
Drat. That just spawns log messages because the loader (quite reasonably) expects one prefix per ID. I'll open a chado ticket, and change back to one "MGI:" in the meantime.

**Comment by mah11** [comment]
I put the ticket on the pombase-legacy tracker - first one there! https://github.com/pombase/pombase-legacy/issues/1

**Comment by mah11** [comment]
fixed by the linked pombase-legacy ticket
