### ISSUE TITLE
check disease associations for exosome

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2283]
Given its ubiquitous role in RNA metabolism, it is not surprising that genetic lesions in subunits and co-factors of the exosome are linked to pathological conditions in human including multiple myeloma, pontocerebellar hypoplasia, and retinitis pigmentosa (Morton et al., 2018; Weißbach et al., 2015).

**Comment by Antonialock** [comment]
associated pontocerebellar hypoplasia with 3 genes
retinitis pigmentosa - found a syndrome called SHRF associated with rrp4 (term pending)
for MM exosomes seems to play a contributory role in disease
