### ISSUE TITLE
mating type TFs do not have any GO process annotation (no longer slim)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2286]
mat3-Mc | SPMTR.04 | silenced M-specific trancription factor Mc
-- | -- | --
mat3-Mc | SPBC1711.02 | mating type M-specific HMG-box transcription factor Mc at silenced MAT3 locus
mat3-Mi | SPMTR.03 | silenced M-specific trancription factor Mi
mat3-Mi | SPBC1711.01c | mating type M-specific polypeptide Mi at silenced MAT3 locus

**Comment by ValWood** [comment]
Also gene product has typo!

**Comment by mah11** [comment]
The descriptions say these are the silenced copies, and some older tickets say we decided not to have GO annotation for them - #2137, #2207, #2209

**Comment by ValWood** [comment]
#2209 says
For this reason we need to:
annotate the silent genes mat2-Pc and mat2-Pi (we have no mat1-Pc and mat1-Pi to annotate to)

**Comment by ValWood** [comment]
@Antonialock  could you put this one near to the top of the list. It's confusing...

**Comment by Antonialock** [comment]
I wrote this faq item https://www.pombase.org/faq/how-are-mating-type-specific-gene-pages-organized

I don't know what we can do about this additionally. 

we need to keep mat2pc and mat2pi becuase we need to be able to hang annotations on to them.

we talked about changing gene type for these....to silenced?  Is there something I could change in artemis?

**Comment by Antonialock** [comment]
they are not even silenced to be honest...they are never expressed. They are just template genes.

**Comment by ValWood** [comment]
That's good. I think people will understand. We can write a "warning" to appear on the page.

But the ones we are using need the 
https://www.pombase.org/gene/SPMTR.01

GO:0003700    DNA-binding transcription factor activity
annotation. That's all I need. At the moment they don't  have the function.

**Comment by ValWood** [comment]
in this case, the action is to move the annotation off 
https://www.pombase.org/gene/SPMTR.01
onto the ones we are using...

**Comment by Antonialock** [comment]
we are using https://www.pombase.org/gene/SPMTR.01 unfortunately

"real" pombe has 4 silenced genes

Our version has 6 silenced genes - 4 M and 2 P

We have to annotate the 2xP
We don't have to annotate any of the silenced Ms (because we have two expressed Ms to annotate to)

**Comment by ValWood** [comment]
So the issue is some have "transcription" BP term but no MF.
FOr the ones that should not be annotated, they should have NO annotation at all.
That's all I need.

For the transcription overhaul I am trying to get MF on all trancription where possible. These are coming up as having BP but no MF. They should have both, or neither...

**Comment by Antonialock** [comment]
I dont think there is a problem? 

Mat1mc and mi have bp and mf
mat3-pc and pi have mf and bp

if the confusion is mat3mc and mi I updated their descriptions and changed the feature type from cds go 'gene' so they should disappear from the gene pages so we dont have duplicated genes....Kim said that should work int he load tomorrow....will check back..
