### ISSUE TITLE
two genes named mtl1

### ISSUE THREAD

**Issue by mah11** [pombase/curation#2293]
I happened to look at the "chado checks" log for the first time in a while, and noticed that we now have two genes with mtl1 as the primary name.

Further digging revealed SPBC215.13 had the mtl1 name added in rev. 5198 (2018-11-13), whereas SPAC17H9.02 was named much earlier (rev. 1440 2013-12-169).

Which gene gets to keep mtl, the usual first claimant, SPAC17H9.02? Any idea what name the other gene should get (in addition to moving mtl1 to a synonym)?

**Comment by ValWood** [comment]
'twas supposed to be mtl2

https://www.ncbi.nlm.nih.gov/pubmed?Db=pubmed&Cmd=ShowDetailView&TermToSearch=23907979

will fix. Not ideal, but not so bad...

**Comment by mah11** [comment]
but mtl2 got added for SPAC11G7.01 in the same commit (r 5198) ...

**Comment by ValWood** [comment]
Oh crap.
OK...

**Comment by ValWood** [comment]
OK, now
SPBC215.13 plasma membrane-associated serine-rich cell wall sensor Mtl1
 only has /synonym="mtl1"

and no primary name. We have had this situation before.
I  really can't think of what else to call it. 

mtl3 maybe would be sensible  since SPAC11G7.01 has an mtl name....

**Comment by mah11** [comment]
I have no reason to object to mtl3 ...

**Comment by ValWood** [comment]
OK mtl3 primary, mtl1 synonym
