### ISSUE TITLE
disease association , sir2? Pho92 (alliance checks) PFY1

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2301]
https://www.yeastgenome.org/locus/YDL042C#disease

**Comment by ValWood** [comment]
https://www.yeastgenome.org/locus/YDR374C#disease

In Alliance, thee have the qualifier is_implicated in

(we can download alliance associations as a spreadsheet, and see if we are missing any)

We need to find out what the qualifiers mean and if they are useful

**Comment by ValWood** [comment]
https://www.yeastgenome.org/locus/YOR122C#disease

**Comment by Antonialock** [comment]
I think the causative ones will be covered by #2376
