### ISSUE TITLE
ddr48, DNA damage responsive ortholog

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2302]
https://www.pombase.org/gene/SPAC23H3.15c
has decription
DNA damage-responsive protein ortholog DDr48

but it's  Schizo specific.

What should the ortholog be?

**Comment by mah11** [comment]
> What should the [ddr48] ortholog be?

I have no idea. I have never worked on any aspect of this gene, let alone an ortholog or the taxon category.

You added the current product description in revision 4685 (2018-03-23 22:25:21).

**Comment by ValWood** [comment]
Ah OK, I'm confusing it with  those double -strand break localizing ones that  that Li lin named

I clearly never finished this.
/controlled_curation="term=misc, small conserved  C term region 
SMGDKMKGNMEKMAGKLTRDPELVQKGEDLKTG; date=20180317"

I think I submitted to Pfam and was waiting for the family to be built before making the changes.

**Comment by ValWood** [comment]
Closing, I can't find this now. I will add a comment to the ortholog list to look in more detail. I must have  sone some funky search.
