### ISSUE TITLE
Check some malacards associations

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2304]
I was surprised we had so many annotations to "immune system diseases"

and by some of the assignments
https://www.pombase.org/term_genes/DOID:2914

Lig4 has
https://www.pombase.org/term/DOID:0060010

but according to DO Omenn syndrome (DOID:0060010)
A severe combined immunodeficiency that has_material_basis in the RAG1 and RAG2 genes on chromosome 11p and the Artemis gene on chromosome 10p. It is characterized by erythroderma, desquamation, alopecia, chronic diarrhea, failure to thrive, lymphadenopathy, and hepatosplenomegaly.

So this gene doesn't have anything to do with Omenn syndrome (DOID:0060010)

**Comment by Antonialock** [comment]
I spotted some too. I'll compile a list and send to malacards. I guess we should remove any bad associations that we spot. Can make a record of the scores in case we want to tweak the cut off

**Comment by Antonialock** [comment]
actually this particular case looks ok. 

"Omenn syndrome (OS) is a fatal variant of severe combined immunodeficiency (SCID), unless treated with allogeneic bone marrow transplant (BMT). Initially OS was associated with mutations in the recombination activating gene (RAG) 1 and 2.1 Subsequently, we and others identified mutations in genes such as RNA component of ribonuclease mitochondrial RNA, adenosine deaminase, IL-2 receptor γ, and IL-7 receptor α in patients with OS.2 We report here, for the first time, the occurrence of OS in a patient with a novel mutation in the DNA ligase IV gene, which was corrected after allogeneic bone marrow transplant."

**Comment by ValWood** [comment]
Yes it made sense to me afterwards. DNA repair machinery is probably required for VDJ recombination

**Comment by Antonialock** [comment]
Yeah but I have definitelh come across at least one example where child records got merged into parent records so that multiple genes got assigned multiple disorders (even though each represented specific subtypes).....I'll open a ticket to dig those out.
