### ISSUE TITLE
SRA pombe studies

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2306]
list generated back in 2013:

Study ERP002090 (CENP-A (Cnp1)) AE
Study SRP019199 (Schizosaccharomyces pombe fission yeast deletion library barcode sequencing)
Study SRP005690 (Schizosaccharomyces pombe NCYC132 Genome Sequencing)
Study SRP001891 (GSE18582: Nuclear retention of fission yeast dicer is a prerequisite for RNAi-mediated heterochromatin assembly) AE 
Study SRP006459 (GSE28839: Genome-wide nucleosome position data for 3 yeast species)
Study SRP007460 (GSE30549: An Extended dsRBD with a Novel Zinc-Binding Motif Mediates Nuclear Retention of Fission Yeast Dicer) AE
Study SRP004492 (DELISEQ)
Study ERP001483 (Transcription profiling by high throughput sequencing of Schizosaccharomyces pombe transcriptome during both proliferation and quiescence) AE 
Study SRP002804 (Mapping of long-range associations throughout the fission yeast genome reveals global genome organization linked to transcriptional regulation)
Study SRP007676 (Tf1 transposition)
Study SRP005691 (Schizosaccharomyces pombe SPK1820 Genome Sequencing)
Study SRP006807 (Reversion of yMWB3-15 suppression phenotype)
Study SRP014477 (GSE39498: Genome-Wide Characterization of the Phosphate Starvation Response in Schizosaccharomyces pombe ChIP-Seq data) AE 
Study SRP009399 (Genome-wide identification and characterization of replication origins by deep sequencing)
Study SRP017390 (Schizosaccharomyces pombe 927 Epigenomics)
Study SRP000417 (TRAMP-mediated RNA surveillance prevents spurious entry of RNAs into the S. pombe siRNA pathway)
Study SRP001040 (High-throughput sequencing of retrotransposon integration provides a saturated profile of target activity in Schizosaccharomyces pombe)
Study SRP004862 (CENP-B preserves genome integrity at replication forks paused by retrotransposon LTR)
Study SRP010613 (GSE35376: Post-transcriptional regulation of cell-cell interaction protein-encoding transcripts by Zfs1p in S. pombe (RNA-Seq)) AE
Study ERP001075 (High throughput sequenceing of fission yeast to survey the dynamic repertoire of a eukaryotic transcriptome at the single nucleotide resolution) AE
Study SRP011412 (Telomere-binding protein Taz1 controls global replication-timing through its localization near late replication origins in fission yeast)
Study SRP007661 (Tf1 transposition)
Study SRP015005 (GSE40298: The unfolded protein response in fission yeast modulates stability of select mRNAs to maintain protein homeostasis) AE
Study SRP001054 (Sequencing of Taxon:4896)
Study SRP010743 (GSE35524: Mediator promotes CENP-A incorporation at fission yeast centromeres ChIP-seq) AE
Study ERP000180 (S. pombe wild type strains genomes)
Study SRP002456 (Global fitness profiling of fission yeast deletion strains by barcode)
Study SRP007662 (Hermes transposition)
Study SRP007677 (Tf1 transposition)
Study ERP000979 (S_pombe_genetic_diversity)
Study ERP001679 (Genome_Evolution_to_Environmental_Stress_in_Fission_Yeast)
Study SRP007590 (GSE31016: RNAi promotes heterochromatic silencing through replication-coupled release of RNA pol II (ChIP-seq))
Study SRP016495 (GSE41634: RNAi triggered by specialized machinery silences developmental genes and retrotransposons) AE 
Study SRP001896 (GSE20330: Hairpin RNA induces secondary small interfering RNA synthesis and silencing in trans in fission yeast)
Study ERP000759 (A pre-mRNA degradation pathway that selectively targets intron-containing genes requires the nuclear poly(A)-binding protein) AE 
Study SRP001085 (Whole genome sequencing of Schizosaccharomyces pombe)
Study SRP001978 (GSE19734: Argonaute Surveillance and Dicer-Independent priRNAs TriggerRNAi and Heterochromatin Formation) AE 
Study SRP004908 (A piggyBac transposon-based mutagenesis system for the fission yeast Schizosaccharomyces pombe)
Study SRP015313 (GSE40451: Hrp3 controls nucleosome positioning to suppress non-coding transcription in eu- and heterochromatin MNase-Seq) AE
Study SRP002730 (Genome-wide identification of nucleosome positions in fission yeast)
Study SRP005611 (RNA sequencing of Schizosaccharomyces pombe SPY73 975 h+)
Study SRP014145 (GSE39166: Strand-specific ChIP-seq profiling of Rad52 localization) AE 
Study SRP007526 (GSE30827: RNAi promotes heterochromatic silencing through replication-coupled release of RNA pol II)
AE indicates that the ENA study accession is found as a secondary accession on an ArrayExpress experiment

**Comment by ValWood** [comment]
We will never host all of these unless there is a way to automate. We need to be user-led with hosting, unless we specifically need a dataset for gene structures etc. We will just bother people to get the important ones. We haven't really done that.
