### ISSUE TITLE
shu1 disallowed term

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2311]
can you figure why and fix
shu1 | GO:0098706 | [UNKNOWN TERM] | IMP | has_qualifier NOT | Antonia Lock

**Comment by ValWood** [comment]
I can't reapprove the session because of this...it might be an ontology issue...

**Comment by mah11** [comment]
GO:0098706 is correctly restricted to organisms that have outer cell membranes, which are all bacteria. For cells that have single cell membranes, try GO:0098711 ! iron ion import across plasma membrane.

(GO:0098760 is one of the terms along the path discussed at exhaustive length in https://github.com/geneontology/go-ontology/issues/16829.)

**Comment by ValWood** [comment]
OK sorted.
