### ISSUE TITLE
cut11, annotate as Spindle pole body anchor

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2316]
I was sure I did this already

**Comment by ValWood** [comment]
weird, the session has:

cut11 | GO:0043495 | protein membrane anchor | IDA | has_input mitotic spindle pole body | 

@mah11  is this not allowed by GO?

anyway changed to
cut11 | GO:0106166 | spindle pole body anchor

**Comment by mah11** [comment]
Our configuration doesn't allow has_input for any GO MF. I think has_direct_input would work for this, and it's allowed.

**Comment by ValWood** [comment]
That makes sense. Although I seem to think GO has changed things so MD uses has_input  not has_direct_input. I have seen stuff on the tracker. This hasn't been announced though so I don't know the rationale, or when it takes effect...

**Comment by mah11** [comment]
What's MD?

We could change our configuration to allow either has_input or has_direct_input with MFs, but it would still make sense to use has_direct_input in this particular case.

The [GO documentation](https://github.com/geneontology/annotation_extensions/tree/master/doc) allows either, depending on whether the gp that executes the function binds the target - if it binds, use the 'direct' version. So for a term in the 'binding' branch ...

and if they want to change, we'll follow along when, and not before, they update said documentation

**Comment by ValWood** [comment]
D is next to F ....

**Comment by ValWood** [comment]
Spindle pole body anchor 
still isn't showing though....

**Comment by ValWood** [comment]
warning in 36f40baed62fc60c: has_input() not allowed for molecular_function, annotation: SPAC1786.03.1 <-> spindle pole body anchor

OK fixing now to "has_direct_input"

**Comment by mah11** [comment]
I also added has_input to our list of allowed MF extension relations since GO allows it, although I still think has_direct_input is correct for the SPB anchor annotations because it's binding.

**Comment by ValWood** [comment]
Yes we'll continue to use it until told otherwise...

**Comment by ValWood** [comment]
yay!
