### ISSUE TITLE
slim term, regulation of mitotic cell cycle phase transition

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2329]
should this be less specific, crs1 doesn't slim since 'mitotic' is specified (crs1 controls meiotic)

**Comment by Antonialock** [comment]
4 genes 

4 | (regulation of meiotic cell cycle phase transition (GO:1901993) NOT regulation of mitotic cell cycle phase transition (GO:1901990))
-- | --



Gene name | Systematic ID | Product
-- | -- | --
crs1 | SPBC2G2.09c | meiosis specific cyclin Crs1
mei2 | SPAC27D7.03c | RNA-binding protein involved in meiosis Mei2
mes1 | SPAC5D6.08c | meiotic APC inhibitor Mes1
mfr1 | SPBC1198.12 | meiotic APC activator Mfr1

**Comment by ValWood** [comment]
I wanted to keep this mitotic  for the modularization.

Instead I will change 
meiotic nuclear division (GO:0140013)
to
meiotic cell cycle process (GO:1903046)

**Comment by ValWood** [comment]
I'll hang on because I think we need another couple of refinements, will do soon.

**Comment by ValWood** [comment]
requested
