### ISSUE TITLE
remove nas

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2336]
once svn is back 

map1

DNA-binding transcription factor activity, RNA polymerase II-specific
--
  | regulates mam2

**Comment by ValWood** [comment]
but it does regulate mam2 right?

**Comment by Antonialock** [comment]
I think, to the best of published knowledge, map1 is primarily involved in h+ cell gene expression. Mam2 is a h- gene.

the mating circuitry is under the control of ste11

things happen though once a zygote is formed....and it's probably needed for a full response in that scenario but it's not worth annotating it until someone has described it properly int he literature..

I removed the nas
