### ISSUE TITLE
phenotype annotations to gene conversion and cross over terms

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2340]
check phenotype annotations to gene conversion and cross over terms - should these be inter and intragenic reocmbination

 from Gerry lab (Ellermeier and Smith 2005: 
PMID:16043696).

I understand we can use gene conversion/intragenic recombination and crossing  over/intergenic recombination. The intragenic recombination assays measure gene conversion events, and the intergenic recombination assays measure crossing over events. 

"We assayed crossing over as intergenic recombination, a valid measure, because gene conversion in S. pombe occurs at low frequency for markers other than hotspots such as ade6-M26 (on average <0.1% convertants per chromatid; P. Munz, personal communication cited in ref. 16). Gene conversion was measured as intragenic recombination, because where tested, >98% of intragenic recombinants in S. pombe are nonreciprocal (22)."

**Comment by ValWood** [comment]
this might be done but seems related to the GO  recombination ticket?

**Comment by mah11** [comment]
I don't see any obvious problems with the annotations from PMID:16043696, and there's no indication that there's anything to do for other papers.
