### ISSUE TITLE
Publications to delete

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#2341]
There are a bunch of publications in Canto with low PMIDs (like "PMID:3") that could be deleted:
https://curation.pombase.org/pombe/view/list/all_publications?model=track

It doesn't matter in Canto but the publications with sessions that are triaged as "CURATABLE" are leaking through to the main site:
  https://www.pombase.org/reference/PMID:1
  https://www.pombase.org/reference/PMID:9

**Comment by ValWood** [comment]
I thought only approved papers would be displayed?

**Comment by kimrutherford** [comment]
> I thought only approved papers would be displayed?

We currently have a reference page for any publication that has annotation and for any publication that has a session in Canto.  If the session isn't approved it says "This publication has no annotations in PomBase because it hasn't been curated yet. "

I thought it was only showing publications from Canto that are triaged as "Curatable" but it isn't.  I'll fix that which will filter out some of the dodgy publications.

**Comment by kimrutherford** [comment]
> I thought it was only showing publications from Canto that are triaged as "Curatable" but it isn't. I'll fix that
> which will filter out some of the dodgy publications.

I've made that change.  But there are two publications that are not triaged as Curatable but have annotations and are approved in Canto:

 PMID:10593605 - Not physically mapped - https://curation.pombase.org/pombe/view/object/pub/5500?model=track
  PMID:27825338 - Method or reagent - https://curation.pombase.org/pombe/view/object/pub/11646?model=track

The Canto code now exports the Curatable sessions and approved sessions, which covers those two publications.  But maybe their triage status needs changign?

**Comment by ValWood** [comment]
I changed PMID:10593605  to curatable

I'll keep PMID:27825338 as method or reagent, even though it has annotations.

After the grant we need to discuss the ability to assign multiple labels. Initially I was using the labels to have a handle on the paper status through the pipeline  it's good to have a single label for this purpose, but we will use them in multple ways post curation.

**Comment by ValWood** [comment]
All now have "loaded in error" and no session.
anything else to do here?

**Comment by ValWood** [comment]
I think this one is done?
