### ISSUE TITLE
add ND annotations for human unknowns

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2359]
@RLovering  suggested

If you have the list of UniProt IDs Alex can edit the field on each record as a batch.
Topic: GO Annotation Complete
Along with the aspect ND annotations as required

we did discuss doing this and I think we should. It will pull some human proteins into GO  that are currently absent.

I would use a date stamp for when you *began* checking, so we know that anything is after this date

**Comment by Antonialock** [comment]
I submitted this.
