### ISSUE TITLE
deafness

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2361]
it seems that
1) not all deafness diseases map to:
https://www.pombase.org/term/DOID:2742

2) this does not have "deafness synonym" (at least I didn't find with searching

@Antonialock  could you report.

Also useful new paper summarizes that 
Over 360 genes are known to be involved in human or mouse deafness
and identifies  38 new ones.

The fact that we only have 18 implies that our sources are not including the known deafness genes. If this could be reported too.
This will take a while to filter through so we should get the list of human names, and ask Kim to query for the conserved set.

https://www.ncbi.nlm.nih.gov/pubmed/30973865

**Comment by Antonialock** [comment]
I went through all the deafness Disease Ontology terms and checked the genes (probably around 250), added the ones we were missing

also added SPNS2 & requested synonym
