### ISSUE TITLE
Is this really a protease? pgp1

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2363]
seems unlikely. I don't think you can get that from IGI?
GO:0004252 | serine-type endopeptidase activity | IGI with krp1 | Ladds G et al. (2000)

**Comment by Antonialock** [comment]
That's an old artemis annotation. I'm not sure, perhaps at least 'peptidase activity' is ok from this? 

this is the relevant section:
The growth defect of the krp1ts strain was rescued by overexpression of a zinc metalloprotease belonging to the M22 family of peptidases (Rawlings and Barrett, 1995)....we propose calling the enzyme Pgp1.

Glycoproteases have been reported in bacteria, plants, nematodes, yeast and mammals. The prototypic member of the family is O-sialoglycoprotein endopeptidase from Pasteurella haemolytica This neutral metallopeptidase is highly specific for O-sialo-glycoproteins and does not cleave unglycosylated proteins, desialylated glycoproteins or glycoproteins that are only N-glycosylated. Two glycoproteases have been identified by sequencing projects in S. cerevisiae, but there is almost no functional information available about these enzymes. There is no information available about the substrate specificity of the yeast enzymes, but it is perhaps signifi- cant that cleavage of glycophorin A by the P. haemolytica glycoprotease is primarily after Arg-31 (Sutherland et al., 1992). A similar specificity for Pgp1 could explain its ability to recognize substrates processed by Krp1.

**Comment by Antonialock** [comment]
@ValWood

**Comment by ValWood** [comment]
1.
the https://www.uniprot.org/uniprot/A0A248ZZW5 Pasteurella haemolytica 
mentioned is not an otholog
It has completely different domains:

InterProi | View protein in InterProIPR036709 Autotransporte_beta_dom_sfIPR011040 SialidaseIPR026856 Sialidase_famIPR036278 Sialidase_sfIPR008377 Sialidase_trypan
PANTHERi | PTHR10628 PTHR10628﻿, 1 hit
Pfami | View protein in PfamPF13859 BNR_3﻿, 1 hit

2. I think the protease motif is a likely False positive from prosite

3. Is known to be
GO:0061711 | N(6)-L-threonylcarbamoyladenine synthase activity | IEA with 2.3.1.234
(domains, EC, orthologs)

4. Overexpression complementing doesn't indicate the same function

I will remove all references to "protease" unless there is more information.

**Comment by Antonialock** [comment]
ok!
