### ISSUE TITLE
nice uses of GO to support hypothesis

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2370]
Analysis where GO is used substantially to support  hypothesis driven questions.

**Comment by ValWood** [comment]
Translational Control of Cell Division by Elongator
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3388810/

**Comment by ValWood** [comment]
![go](https://user-images.githubusercontent.com/7359272/56608979-edad3f80-6603-11e9-80ba-956bfaad3af4.jpg)

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6393241

![olaf](https://user-images.githubusercontent.com/7359272/56608919-c7879f80-6603-11e9-8f4d-dd2ac62e80b5.jpg)

**Comment by ValWood** [comment]
Mechanisms connecting the conserved protein kinases Ssp1, Kin1, and Pom1 in fission yeast cell polarity and division
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5760279/#SD1
Figure S2

![go_from_moseley](https://user-images.githubusercontent.com/7359272/56610913-804fdd80-6608-11e9-9d5b-960928f8bafe.jpg)

**Comment by jrr-cpt** [comment]
@ValWood thanks! These are great examples.

@jimhu-tamu
@sandyl27

**Comment by ValWood** [comment]
closing. I have a GOogle doc
