### ISSUE TITLE
missing human ortholog

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2375]
Sssca1 - SPBC3B8.08

**Comment by ValWood** [comment]
weird I check that all disease associated have human orthologs and i did it recently...

**Comment by ValWood** [comment]
s'ok systems are working

https://curation.pombase.org/dumps/latest_build/logs/ortholog_problems.txt
ay

Must have had a name update... fixing now

**Comment by kimrutherford** [comment]
> Must have had a name update

Yep looks like it:
https://curation.pombase.org/dumps/builds/pombase-build-2019-04-30/logs/log.2019-04-30-22-49-13.manual-1-1-orths-output

There are two other issues here:
https://curation.pombase.org/dumps/builds/pombase-build-2019-04-30/logs/log.2019-04-30-22-49-13.manual-multi-orths-output

**Comment by ValWood** [comment]
oddly official name is ZNRD2 not sssca1, fixing to this

https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:11328

**Comment by ValWood** [comment]
although we have 
mRNA SPBC15D4.10c.1: ortholog (NUPL2) not found
currently which is confusing as this seems to not be a previous name?

**Comment by ValWood** [comment]
note to self
can't find feature in Chado for SEPT12
can't find feature in Chado for SEPT1

these are from
conserved_multi.txt:SPAC821.06	SEPT3,SEPT12

and
conserved_multi.txt:SPAC4F10.11	SEPT7,SEPT2,SEPT4,SEPT5,SEPT1

it seems odd that 2 human septin names changed, query with HGNC

ALSO SPAC821.06 seems that it should be SEPT9, not SEPT3 from the consensus:
https://www.flyrnai.org/cgi-bin/DRSC_orthologs.pl?input_species=4896&output_species=0&additional_filter=None&search_fields=***&search_datasets=***&gene_list=SPAC821.06

**Comment by kimrutherford** [comment]
> although we have
> mRNA SPBC15D4.10c.1: ortholog (NUPL2) not found
> currently which is confusing as this seems to not be a previous name?

I don't understand your comment.  The warning makes sense to me given the annotation?:
```
FT                   /controlled_curation="term=human NUPL2 ortholog;
FT                   date=20091118"       
```

**Comment by ValWood** [comment]
SEPT12 now SEPTIN12
SEPT3 now SEPTIN3
other septins seem to have changed too (only the first violation in a row gets reported so I need to fix all)

**Comment by ValWood** [comment]
> I don't understand your comment. The warning makes sense to me given the annotation?:

yes but this should be a synonym or previous name here, and it isn't, which is odd...
https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:11328

also I wonder why  HGNC changed from 
SSSCA1 (Sjogren syndrome/scleroderma autoantigen 1)

to the non-specific
ZNRD2  (zinc ribbon domain containing 2)

@Antonialock is this actually 'disease causing' mutant or is it a diagnostic tool, or similar?

**Comment by kimrutherford** [comment]
> yes but this should be a synonym or previous name here, and it isn't, which is odd...
> https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:11328

NUPL2 is a synonym here:
https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:17010

**Comment by ValWood** [comment]
even weirder, so  it seems that it had totally the incorrect ortholog at some point....

should def be SSSCA1 now oddly  ZNRD2

**Comment by ValWood** [comment]
ok

- [ ] SPBC3B8.08 previously   SSSCA1 now oddly ZNRD2 

- [ ]  @kimrutherford SPBC3B8.08 was not in the logs as far as I can see ?

- [ ] NUPL2 SPBC15D4.10c  is a different gene (I must have still had SPBC3B8.08 in my copy paste)
needs fixing to NULP42

- [ ]   SEPT* -> SEPTIN*

- [ ] SPAC821.06 seems that it should be SEPT9, not SEPT3 

- [ ]  @Antonialock is SSSCA1 definitely *disease causing*

**Comment by ValWood** [comment]
- [ ]  @Antonialock is SSSCA1 definitely *disease causing*
I don't think this is a real disease gene association

**Comment by Antonialock** [comment]
I'll look into it...I don't think there are any known causative gene's of Sjogren's

**Comment by ValWood** [comment]
only these with this name. I'll remove the association (but keep the existing product description, as I think that's how people know it).


Subcellular localization of p27 and prostate cancer recurrence: automated digital microscopy analysis of tissue microarrays.
Ananthanarayanan V, Deaton RJ, Amatya A, Macias V, Luther E, Kajdacsy-Balla A, Gann PH.
Hum Pathol. 2011 Jun;42(6):873-81. doi: 10.1016/j.humpath.2010.10.006. Epub 2011 Feb 2.
PMID: 21292307 Free PMC Article

Select item 19574837
Expression of CRM1 in human gliomas and its significance in p27 expression and clinical prognosis.
Shen A, Wang Y, Zhao Y, Zou L, Sun L, Cheng C.

**Comment by kimrutherford** [comment]
> @kimrutherford SPBC3B8.08 was not in the logs as far as I can see ?

Which log file is it missing from?

**Comment by ValWood** [comment]
I don't known but the HGNC name was incorrect and so the ortholog section
had disappeared from the page
https://www.pombase.org/gene/SPBC3B8.08

but as far as I can see it wasn't reported in any of the ortholog logs....maybe HGNC is not updating properly. I think they changed some things recently...

**Comment by ValWood** [comment]
fixed via
Committed revision 5536.

will move the outstanding question to Chado tracker

**Comment by ValWood** [comment]
ignore. I was confusing the  files

https://curation.pombase.org/dumps/builds/pombase-build-2019-04-30/logs/log.2019-04-30-22-49-13.manual-1-1-orths-output
