### ISSUE TITLE
150 potential new disease associations

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2376]
Monarch now (since March!) includes 'causative' genes. 
I think I have filtered down to human genes causing disease, with pombe orthologs, that do not have current disease associations (150 genes!) 

looks like they all have references so should be quickish to check and add.

https://monarchinitiative.org/disease/MONDO:0000001#gene-causal

- [x]  ADAT3
- [x]  ARCN1
- [x]  ARHGDIA
- [x]  ARPC1B
- [x]  ARV1
- [x]  ASNS
- [x]  ATAD1
- [x]  BCAP31
- [x]  BRPF1
- [x]  CCNQ
- [x]  CDC42
- [x]  CDK13
- [x]  CNKSR2
- [x]  CNNM4
- [x]  COG2
- [x]  COPB2
- [x]  CORO1A
- [x]  CTDP1
- [x]  CTPS1
- [x]  CTU2
- [x]  CUL4B
- [x]  CWC27
- [x]  CYCS
- [x]  CYP26C1
- [x]  DGAT1
- [x]  DHODH
- [x]  DMXL2
- [x]  DPH1
- [x]  EARS2
- [x]  EIF2AK4
- [x]  EIF4A3
- [x]  ELP2
- [x]  EPRS
- [x]  GFM1
- [x]  GGT1
- [x]  GLRX5
- [x]  GLUL
- [x]  GPAA1
- [x]  GPI
- [x]  GPT2
- [x]  GTF2E2
- [x]  HDAC6
- [x]  HIBCH
- [x]  HMGB3
- [x]  HMGCS2
- [x]  HNRNPK
- [x]  HSPA9
- [x]  HUWE1
- [x]  IARS
- [x]  ISCU
- [x]  ITPA
- [x]  KIF22
- [x]  KNL1
- [x]  LARP7
- [x]  LIAS
- [x]  LIPT1
- [x]  LMAN1
- [x]  LNPK
- [x]  LONP1
- [x]  MAPRE2
- [x]  MCM4
- [x]  MOGS
- [x]  MPC1
- [x]  MRPS16
- [x]  MRPS7
- [x]  MSMO1
- [x]  MSTO1
- [ ]  MTAP
- [x]  MTHFD1
- [x]  MTO1
- [x]  NAXE
- [x]  NBAS
- [x]  NCAPH
- [x]  NPRL3
- [x]  NSDHL
- [x]  NSMCE3
- [x]  OPLAH
- [x]  PAK3
- [x]  PCBD1
- [x]  PCNA
- [x]  PDHX
- [x]  PDP1
- [x]  PGK1
- [x]  PGM3
- [x]  PHF8
- [x]  PI4KA
- [x]  PIGH
- [x]  PIGL
- [x]  PIGW
- [x]  PIGY
- [x]  PLAA
- [x]  PLD1
- [x]  PNPO
- [x]  POMP
- [x]  PPP1CB
- [x]  PRUNE1
- [x]  PSMB4
- [x]  PTRH2
- [x]  PUS1
- [x]  QARS
- [x]  RBM10
- [x]  RHAG
- [x]  RMND1
- [x]  ROGDI
- [x]  RPIA
- [x]  RPSA
- [x]  SC5D
- [x]  SEC61A1
- [x]  SIN3A
- [x]  SLC13A5
- [x]  SLC36A2
- [x]  SLC39A13
- [x]  SLC46A1
- [x]  SMARCAD1
- [x]  SMARCD2
- [x]  SPATA5
- [x]  SPRTN
- [x]  SRCAP
- [x]  SUMO1
- [x]  SUN5
- [x]  TAF2
- [x]  TAF6
- [x]  TALDO1
- [x]  TBCD
- [x]  TGDS
- [x]  THOC2
- [x]  TIMM50
- [x]  TNRC6A
- [x]  TRAPPC2
- [x]  TRAPPC6B
- [x]  TRMT5
- [x]  TSFM
- [x]  TTC37
- [x]  TTI2
- [x]  TUBGCP6
- [x]  TUFM
- [x]  TXNL4A
- [x]  UBA5
- [x]  UBE2A
- [x]  UBE3B
- [x]  UBTF
- [x]  UPF3B
- [x]  USP8
- [x]  VARS
- [x]  VARS2
- [x]  VPS45
- [x]  WBP2
- [x]  XPR1
- [x]  YARS2

**Comment by ValWood** [comment]
Excellent. Our coverage will be awesome (in the real way!)

**Comment by Antonialock** [comment]
all annotated or added to requests.

**Comment by ValWood** [comment]
Excellent!
