### ISSUE TITLE
need to decide  how PR: ids should be consistently curated and displayed

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2388]
for example here the modified form is on both partners:

![which?](https://user-images.githubusercontent.com/7359272/57570981-12752580-7400-11e9-94e4-3b0e2667f816.jpg)

**Comment by mah11** [comment]
also see https://github.com/pombase/website/issues/67 (warning: old, long, and headmelty)

**Comment by mah11** [comment]
That example does make sense, though - the first annotation says Rad24 acts on the specific form of Clp1 that the PR:nnn ID represents (GAF col 16), and the second says that same form of Clp1 binds Rad24 (GAF col 17).

We could do with a nicer bit of display text in place of "column_17", in addition to whatever we do with the PR ID.

**Comment by ValWood** [comment]
closing, see next gen

https://github.com/pombase/website/issues/1626
https://github.com/pombase/website/issues/1625
https://github.com/pombase/website/issues/1623
