### ISSUE TITLE
Tim22 and disease

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2397]
we have 1 subunit. Check others:

  | Pacheu-Grau  D, Callegari S, Emperador S, Thompson K, Aich A, Topol SE, Spencer EG,  McFarland R, Ruiz-Pesini E, Torkamani A, Taylor RW, Montoya J, Rehling  P. | Related Articles
-- | -- | --
  | Mutations of the mitochondrial carrier translocase channel subunit TIM22 cause early-onset mitochondrial myopathy.
  | Hum Mol Genet. 2018 Dec 1;27(23):4135-4144.
  | PMID: 30452684

**Comment by Antonialock** [comment]
done
Requested from do, had a look around for other mito ones.
