### ISSUE TITLE
iron uptake, storage & regulation thereof

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2402]
we had a few tickets and the annotation is a bit messy so checking and improving it.

need to add to this story....

**1) TRANSCRIPTIONAL REGULATION**

**HIGH IRON**

Fep1 transcriptionally negatively regulates php4 and iron acquisition genes (e.g. frp1, fio1, fip1, str1,2,3)
Tup11/12 are corepressors
Grx4 bound to iron sulphur cluster activates fep1

Grx4 bound to iron sulphur cluster binds php4, and promotes its nuclear export

Php2/3/5 transcriptionally positively regulates iron requiring genes

_positive regulation of transcription from RNA polymerase II promoter in response to iron_
Php2
Php3
Php5

_negative regulation of transcription from RNA polymerase II promoter in response to iron_
fep1
tup11
tup12

**LOW IRON**

when grx4 is not bound to iron php4 is allowed to interact with php2/3/5. Fe using genes are no longer expressed

when grx4 is not bound to iron fep1 can't bind DNA and Fe transport genes are activated

_negative regulation of transcription from RNA polymerase II promoter in response to iron ion starvation_
Php4  

_What's the GO term for the 'switch'?_
Grx4 - cellular iron ion homeostasis

**2) IRON UPTAKE**

**REDUCTIVE SYSTEM**
Frp1 reduces ferric iron to ferrous
Fio1/fip1 transports the ferrous iron across PM into cell

_Reductive iron assimilation_
Fio1
fip1
Frp1

**NONREDUCTIVE UPTAKE**
Siderophore uptake: str1 -> add GO:0015344
Ferrixomaine B iron: str2 -> add GO:0015344

_heme transporter activity_
str3

_heme import across plasma membrane_
Shu1
Str3

**3) IRON STORAGE, METABOLISM**

In high iron, iron is stored in vacuoles (possibly as ferrichromes) 

Pcl1: in high iron, pal1 transports Fe from cytosol into vacuole
Abc3: In low iron abc3 transports iron from vacuole to cytosol

Siderophore ferrichrome biosynthesis: Sib2-SPBC17G9.06c-sib1

_intracellular sequestering of iron ion_
pcl1 

some form of _heme import_ that goes across PM to vacuole
https://github.com/pombase/curation/issues/2406
shu1

requested _heme export from vacuole_
abc3

HEME BIOSYNTHESIS
We have 13 genes annotated to this, but "In Schizosaccharomyces pombe, these eight enzymes are respectively encoded by the following genes: hem1+, hem2+, hem3+, ups1+, hem12+, hem13+, hem14+, and hem15+. "
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4400333/

hemin storage shu1? "Consistent with this observation, results have shown that in response to elevated concentrations of hemin or ZnMP, Shu1 undergoes internalization from the cell surface to the vacuole (8)." Heme assimilation in Schizosaccharomyces pombe requires cell-surface-anchored protein Shu1 and vacuolar transporter Abc3

**Comment by Antonialock** [comment]
leae out str2 and str3 "In the case of Str2, its physiological role in S. pombe is still unclear, and the ORFeome global analysis of protein localization indicates that Str2 localizes to the membrane vacuole (15). Str3 displays the lowest sequence identity with Str1 and Str2 (11). Although Str3 localizes to the plasma membrane of cells (15), its heterologous expression in an iron uptake–deficient S. cerevisiae strain fails to restore growth in the presence of siderophores, including ferrichrome and ferroxiamine B (11). The biological function of Str3 remains therefore undetermined."

**Comment by Antonialock** [comment]
aside from the heme transmembrane issue the rest looks fine

**Comment by ValWood** [comment]
Is that from this paper?

https://www.pombase.org/reference/PMID:29549126
The major facilitator transporter Str3 is required for low-affinity heme acquisition in Schizosaccharomyces pombe .

**Comment by ValWood** [comment]
This is fine, later "automated modelling" should resolve any outstanding issues.
