### ISSUE TITLE
standardize phosphomimic/phosphomimetic

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2405]
see https://user-images.githubusercontent.com/7359272/58381615-cd7ff000-7fb6-11e9-8680-6b94bc9c57d1.jpg

@kimrutherford  could you let me know which sessions have "phosphomimetic"?

**Comment by kimrutherford** [comment]
> @kimrutherford could you let me know which sessions have "phosphomimetic"?

Just 77f717dc87015fe5 I think.

**Comment by ValWood** [comment]
ok that was easy, fixed
