### ISSUE TITLE
heme import across plasma membrane

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2406]
just want advice on what to annotate to PMID:28193844

so to my understanding in fungi, exogenous heme -> endocytosis  (likely, observed in other fungi) -> vacuole -> cytosol

these two terms exist:
1. heme import across plasma membrane: The directed movement of heme from outside of a cell, across the plasma membrane and into the cytosol.
& 
2. endocytic iron import into cell

1 doesn't feel quite right since import is via the vacuole. 
2 doesn't specify heme (is it restricted to any iron?)

Should I request a new term?
"heme import across plasma membrane into vacuole" or  
"endocytic heme import into cell"?

**Comment by ValWood** [comment]
Good questions. heme transport looks a bit inconsistent anyway. There are grouping terms for 'heme export' but not heme 'import'. 
Presumably heme is always imported into the vacuole for storage whichever way it enters the cell (guessing?)

"endocytic heme import" would seem to be enough 
(and the def could say that the heme is imported into the vacuole if this is always true.

@pgaudet any thoughts. We'll open a ticket once we know what to ask for.

**Comment by pgaudet** [comment]
**x import across plasma membrane**

means transmembrane transport. It would be nice to make that clearer - suggestions are welcome. 
Of we agree on this, then TM transport from the extracellular to the vacuole is an addition step - what is the mechanism here ? (seems like we are defining functions :( 

**(endocytic) import into cell** 
The problem with just 'import' is this is used for 'import into cell', 'import into mitochondria', etc, and as such is a weird grouping term. You can imagine import into the cell being either from the cytoplasm or from an organelle. 

Pascale

**Comment by Antonialock** [comment]
heme transport seems to differ slightly between fungi, but the overall chain of events seem to be:

heme endocytosis to vacuole -> vacuole acts as a store of iron (probably heme in pombe, other organisms may use eg ferritin) -> when iron is needed it is mobilized from the vacuole (in some form) -> cytoplasm (and then I guess it would generally be taken to the mitochondria?)

I don't know if endocytosis is just a fungal thing but bacteria seem to do it differently
![Screenshot 2019-05-28 at 09 30 01](https://user-images.githubusercontent.com/12727506/58463179-44d69080-812b-11e9-8975-9779884e3a0b.png)

human
![Screenshot 2019-05-28 at 09 34 53](https://user-images.githubusercontent.com/12727506/58463656-2d4bd780-812c-11e9-9012-efc269a4672c.png)

**Comment by Antonialock** [comment]
maybe we need a new term to mean an uptake pathway? 

"heme uptake via endocytosis" ?

**Comment by ValWood** [comment]
> x import across plasma membrane
means transmembrane transport. It would be nice to make that clearer - suggestions are welcome.

import could mean via endocytosis or transmembrane transport, so probably these should be 
explicit (i.e  heme transmembrane import across the plasma membrane) 

Antonia I don't think you need to encode the final destination  into the import . that will be described by other steps

**Comment by Antonialock** [comment]
ok so this isn't transmembrane transport as such? 

endocytic heme import across plasma membrane ?

**Comment by Antonialock** [comment]
or is heme import across plasma membrane sufficient?

**Comment by pgaudet** [comment]
'across the plasma membrane' was supposed to mean transmembrane.... 
I am just concerned that MF and BP are identical in this case. 

I dont know how to avoid that ?

**Comment by ValWood** [comment]
Which MF and BP are identical?

**Comment by pgaudet** [comment]
We have in MF:  ATPase-coupled heme transmembrane transporter activity
and if we knew of a heme cargo receptor, we should probably create this activity under 'cargo receptor activity'; right ?

**Comment by ValWood** [comment]
Antonia I don't think 
"endocytic heme import across plasma membrane ?" works because 
heme isn't imported *across the plasma membrane* - the vesicle buds off the membrane, the membrane isn't traversed. It is import into cell, but not import across the plasma membrane.

Which gene product were you trying to annotate here?

**Comment by ValWood** [comment]
I see shu1

In GO we have

GO:0097037    heme export | is_a
-- | --
GO:0020028    endocytic hemoglobin import | is_a

so probably we could have 

heme import, or endocytic heme import? @pgaudet

**Comment by pgaudet** [comment]
I will check. This is definitely on the unfinished list of transport/transporters. 

Pascale

**Comment by Antonialock** [comment]
> Which gene product were you trying to annotate here?


str3 and shu1

**Comment by Antonialock** [comment]
> We have in MF: ATPase-coupled heme transmembrane transporter activity
> and if we knew of a heme cargo receptor, we should probably create this activity under 'cargo receptor activity'; right ?

maybe it would be better as a MF... 

what would be a better description of the process, heme assimilation? it's a bit unsatisfactory to only have MF, and not describe what the function is used for.... 

> Taken together, these results indicate that Str3 is a second cell-surface membrane protein for > > acquisition of exogenous heme in S. pombe.
> http://www.jbc.org/content/early/2018/03/16/jbc.RA118.002132.full.pdf


we also have "heme export from vacuole to cytoplasm" is that heme mobilisation?

**Comment by ValWood** [comment]
It still feels to me that it should be part of some import process

"endocytic heme import/uptake"

what is the MF. Is it some sort of GO:0038024  cargo receptor activity?

**Comment by ValWood** [comment]
str3 has
heme transporter activity  | part of heme import across plasma membrane

shu1
has
 heme import across plasma membrane

this one needs fixing (heme endocytosis, it isn't tm transport IIRC?)

**Comment by ValWood** [comment]
Asked the author. Quicker...

**Comment by ValWood** [comment]
From Simon Labbe

As far as we know, Shu1 is attached to the membrane via a GPI anchor.

A current model suggests that Shu1 binds exogenous hemin at the cell surface (like a heme receptor), and then undergoes internalization from the cell surface to the vacuole.  This mechanism requires Nbr1 and proteins of the ESCRT complex.  We found that several proteins are ubiquitinated when cells are taking up exogenous hemin as a sole source of heme.  We have shown that a subgroup of Ubi4-dependent ubiquitinated proteins interacts with Shu1.

We know that the presence of Nbr1 (most probably ubiquitinated) is required to trigger Shu1 internalization to the vacuolar membrane.

Furthermore, hemin-mediated Shu1 vacuolar targeting also requires the ubiquitin-binding proteins Hse1 (ESCRT-0) and Sst6 (ESCRT-I).

In fact, co-IP experiments have shown that Shu1 associates with both Nbr1 and Hse1 in hemin-treated cells.

Heme import across plasma membrane : is correct for Shu1, though it is not a transmembrane transporter.  Shu1 is a cell surface-anchored heme-binding protein.

The exact mechanism whereby Shu1 is internalized when bound to hemin is still an open question…

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/18671#issuecomment-579279461
will fix
