### ISSUE TITLE
cell pole annotation

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2411]
![Screenshot 2019-05-29 at 19 16 04](https://user-images.githubusercontent.com/12727506/58580955-3df07080-8246-11e9-9307-115f10e2a318.png)

**Comment by ValWood** [comment]
I always ise cell tip

but GO

Either of two different areas at opposite ends of an axis of a cell.
Comments
Note that this term differs from 'cell tip ; GO:0051286' in that it is applicable to a broad range of cell shapes including spherical and cuboidal.

which implies cell tip should be is_a cell pole?

**Comment by Antonialock** [comment]
I also thought it looked like it should be an is_a

**Comment by Antonialock** [comment]
opened a ticket on go tracker.

**Comment by ValWood** [comment]
fixed
