### ISSUE TITLE
pkd2 human ortholog

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2413]
pkd2 conserved in fungi only

from PMID:31116668
"There are two human homologues of Pkd2p, PKD1 and the MS channel PKD2 (Hanaoka et al., 2000; Nauli et al., 2003). "

there are no alignments or mentions of taxonomic conservation in the referenced papers
Hanaoka, PMID: 11140688
Nauli, PMID: 12514735

thought you might want to check.
If you think theya re orthologous then assign to me to add disease assoc.

**Comment by ValWood** [comment]
It could be but I can't see a connection.  I would say they are homologs rather than orthologs...
