### ISSUE TITLE
some things no longer slim that used to:

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2415]
SPAC1B1.02c |   | NAD/NADH kinase (predicted)
SPBC1778.03c |   | NADH pyrophosphatase (predicted)
SPCC24B10.02c |   | NAD/NADH kinase (predicted)

SPCC965.03 | vma8 | V-type ATPase V1 subunit D (predicted)
https://github.com/geneontology/go-ontology/issues/17439

SPCC736.04c | gma12 | alpha-1,2-galactosyltransferase Gma12
SPAC22E12.06c | gmh3 | alpha-1,2-galactosyltransferase Gmh3
https://github.com/geneontology/go-ontology/issues/17440

SPAC9E9.05 | bsp1 | synaptojanin to cortical actin cytoskeletal adaptor Bsp1 (predicted)

It is possible these never slimmed:-
SPBC3H7.09 | erf2 | palmitoyltransferase Erf2
SPAC3F10.07c | erf4 | palmitoyltransferase complex subunit Erf4
SPBC13G1.07 | swf1 | palmitoyltransferase Swf1 (predicted)
SPAC2F7.10 | akr1 | palmitoyltransferase Akr1 (predicted)

ipk1 -> signalling?

**Comment by kimrutherford** [comment]
I you let me know an example term and the term ID of the category it should be in, I'll check Chado and GO.

**Comment by ValWood** [comment]
Don't worry, these will be GO parentage changes. I can work through them- reported on already...
https://github.com/geneontology/go-ontology/issues/17439
