### ISSUE TITLE
inviable at temperature

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2416]
check

INVIABLE CELL AT HIGH TEMPERATURE

cam1-E1 (E67V, E104V, E140V aa)[Overexpression] | FYPO:0001801 | inviable cell at high temperature | cell growth assay evidence | YESagar plates | Moser MJ et al. (1995)

cam1-E13 (E67V, E140V aa)[Overexpression] |   | cell growth assay evidence | YESagar plates | Moser MJ et al. (1995)
cam1-E34 (E31V, E67V aa)[Overexpression] |   | cell growth assay evidence | YESagar plates | Moser MJ et al. (1995)
cam1-E4 (E31V, E67V, E104V aa)[Overexpression] |   | cell growth assay evidence | YESagar plates | Moser MJ et al. (1995)
cdc1-18 (G293S aa) |   | cell growth assay evidence | agar plates | MacNeill SA et al. (1996)
cdc1-M78 (W381R aa) |   | cell growth assay evidence | agar plates | MacNeill SA et al. (1996)
cdc11-136 (unknown) |   | cell growth assay evidence | YESagar plates | Schmidt S et al. (1997)
cdc14-118 (unknown) |   | cell growth assay evidence | agar platesYES | Schmidt S et al. (1997)
cdc15-140 (unknown) |   | cell growth assay evidence | YESagar plates | Schmidt S et al. (1997)
cdc16-116 (unknown) |   | cell growth assay evidence | agar platesYES | Schmidt S et al. (1997)
cdc17-K42 (E298K aa) |   | cell growth assay evidence |   | Rowley R et al. (1992)
cdc17-K42 (E298K aa)[Wild type product level] |   | cell growth assay evidence |   | Nasmyth KA (1979)
cdc7-24 (unknown) |   | cell growth assay evidence | YESagar plates | Schmidt S et al. (1997)
cdc7-A20 (unknown) |   | cell growth assay evidence | agar platesYES | Schmidt S et al. (1997)
cut14-G655E (G655E aa)[Wild type product level] |   | cell growth assay evidence | high temperature | Xu X et al. (2019)
cut14-L492P (L492P aa)[Wild type product level] |   | cell growth assay evidence | high temperature | Xu X et al. (2019)
cut14-L608P (L608P aa)[Wild type product level] |   | cell growth assay evidence | high temperature | Xu X et al. (2019)
cut14-L617P (L617P aa)[Wild type product level] |   | cell growth assay evidence | high temperature | Xu X et al. (2019)
cut14-L676P (L676P aa)[Wild type product level] |   | cell growth assay evidence | high temperature | Xu X et al. (2019)
cut3-G777E (G777E aa)[Wild type product level] |   | cell growth assay evidence | high temperature | Xu X et al. (2019)
cut3-L641P (L641P aa)[Wild type product level] |   | cell growth assay evidence | high temperature | Xu X et al. (2019)
cut3-L709P (L709P aa)[Wild type product level] |   | cell growth assay evidence | high temperature | Xu X et al. (2019)
cut3-L732P (L732P aa)[Wild type product level] |   | cell growth assay evidence | high temperature | Xu X et al. (2019)
cut7-T1011A (T1011A aa)[Wild type product level] |   | cell growth assay evidence |   | Akera T et al. (2015)
hmg1-1 (W234->opal) |   | cell growth assay evidence | agar platesYPD | Takami T et al. (2012)
mok1-664 (unknown) |   | cell growth assay evidence | glucose MMagar plates | Villar-Tajadura MA et al. (2008)
mor2-786 (A1673G nt) |   | cell growth assay evidence | agar platesYPD | Kume K et al. (2013)
nak1-125 (T198I nt) |   | cell growth assay evidence | YPDagar plates | Kume K et al. (2013)
orb6-25 (unknown) |   | cell growth assay evidence | agar platesYPD | Kume K et al. (2013)
pcp1-14 (K848R, L1187P aa) | has penetrance complete | cell growth assay evidence | high temperatureYES | Tang NH et al. (2019)
pcp1-15 (I172T, K543E, I624T, E732G, A1022V, I1153V, H1163R aa)[Wild type product level] | has penetrance complete | cell growth assay evidence | high temperatureYES | Tang NH et al. (2019)
pcp1-17 (Q375P, L508P, L672P aa) | has penetrance complete | cell growth assay evidence | YEShigh temperature | Tang NH et al. (2019)
pcp1-18 (L254S, L717P aa)[Wild type product level] | has penetrance complete | cell growth assay evidence | high temperatureYES | Tang NH et al. (2019)
pep12Δ |   | cell growth assay evidence | YESagar plates | Hosomi A et al. (2011)
pmo25-35 (T236A nt) |   | cell growth assay evidence | agar platesYPD | Kume K et al. (2013)
rad4.116 (unknown)[Wild type product level] |   | cell growth assay evidence |   | Fenech M et al. (1991)
rpn12-1 (unknown) |   | cell growth assay evidence | agar platesYES | Yen HC et al. (2003)
rpt2-1 (unknown) |   | cell growth assay evidence | agar platesYES | Yen HC et al. (2003)
sec3-913 (W150R, T541L aa) | has penetrance high | cell growth assay evidence |   | Kampmeyer C et al. (2017)
spo9Δ |   | cell growth assay evidence | agar platesYPD | Takami T et al. (2012)
vrg4Δ |   | cell growth assay evidence | YEShigh temperature | Bredeston LM et al. (2017)
ypt3-ki8 (A74V aa) |   | cell growth assay evidence | high temperatureYES | Imada K et al. (2016)

alp7-20 (Y344R aa)[Wild type product level] cut7Δ pkl1Δ | FYPO:0001801 | inviable cell at high temperature | cell growth assay evidence | YEShigh temperature | Yukawa M et al. (2017)
-- | -- | -- | -- | -- | --
cut7-22 (P1021S aa) klp9Δ pkl1Δ |   | cell growth assay evidence | YEShigh temperature | Yukawa M et al. (2017)

**Comment by ValWood** [comment]
INVIABLE CELL AT HIGH TEMRPERATURE



cam1-E12 (E104, E140V aa)[Overexpression] | FYPO:0000282 | viable cell at high temperature | cell growth assay evidence | YESagar plates | Moser MJ et al. (1995)
-- | -- | -- | -- | -- | --
cam1-E123 (E140V aa)[Overexpression] |   | cell growth assay evidence | agar platesYES | Moser MJ et al. (1995)
cam1-E124 (E104V aa)[Overexpression] |   | cell growth assay evidence | agar platesYES | Moser MJ et al. (1995)
cam1-E134 (E67V aa)[Overexpression] |   | cell growth assay evidence | YESagar plates | Moser MJ et al. (1995)
cam1-E14 (E67V, E104V aa)[Overexpression] |   | cell growth assay evidence | YESagar plates | Moser MJ et al. (1995)
cam1-E2 (E31V, E104V, E140V aa)[Overexpression] |   | cell growth assay evidence | agar platesYES | Moser MJ et al. (1995)
cam1-E23 (E31V, E140V aa)[Overexpression] |   | cell growth assay evidence | YESagar plates | Moser MJ et al. (1995)
cam1-E234 (E31V aa)[Overexpression] |   | cell growth assay evidence | YESagar plates | Moser MJ et al. (1995)
cam1-E24 (E31V, E104V aa)[Overexpression] |   | cell growth assay evidence | agar platesYES | Moser MJ et al. (1995)
cdc42-L160S (L160S aa)[Wild type product level] |   | cell growth assay evidence | + sorbitolhigh temperature | Estravis M et al. (2012)
cek1Δ |   | cell growth assay evidence |   | Samejima I et al. (1994)
cut1-21 (T545S aa)[Wild type product level] |   | cell growth assay evidence | + rapamycin | Ikai N et al. (2011)
cut1-693 (A1816T aa)[Wild type product level] |   | cell growth assay evidence | + rapamycin | Ikai N et al. (2011)
cut2-447 (L296S aa)[Wild type product level] |   | cell growth assay evidence | + rapamycin | Ikai N et al. (2011)
erg4Δ |   | cell growth assay evidence | YPDagar plates | Takami T et al. (2012)
etd1Δ |   | cell growth assay evidence |   | García-Cortés JC et al. (2009)
krp1+[Overexpression] |   | cell growth assay evidence |   | Ladds G et al. (2000)
krp1ts (F425S aa) |   | cell growth assay evidence |   | Ladds G et al. (2000)
tor2-51 (unknown) |   | cell growth assay evidence |   | Alvarez B et al. (2006)


cdc2-A21 (D90N aa) cdc25+[Overexpression] wee1-50 (wee1-50 (G850E)/wee1-50 (G850E) homozygous diploid) | FYPO:0000282 | viable cell at high temperature | cell growth assay evidence | YESstandard temperature | Ayscough K et al. (1992)

cdc2-E8 (D213N aa) cdc25+[Overexpression] wee1-50 (wee1-50 (G850E)/wee1-50 (G850E) homozygous diploid) |   | cell growth assay evidence | YESstandard temperature | Ayscough K et al. (1992)

cdc2-E9 (D242N aa) cdc25+[Overexpression] wee1-50 (wee1-50 (G850E)/wee1-50 (G850E) homozygous diploid) |   | cell growth assay evidence | standard temperatureYES | Ayscough K et al. (1992)

**Comment by ValWood** [comment]
viable cell at low temperature


	cam1-E1 (E67V, E104V, E140V aa)[Overexpression]	FYPO:0002171	
viable cell at low temperature
cell growth assay evidence	
agar plates
YES
Moser MJ et al. (1995)
cam1-E12 (E104, E140V aa)[Overexpression]	
cell growth assay evidence	
YES
agar plates
Moser MJ et al. (1995)
cam1-E123 (E140V aa)[Overexpression]	
cell growth assay evidence	
agar plates
YES
Moser MJ et al. (1995)
cam1-E124 (E104V aa)[Overexpression]	
cell growth assay evidence	
YES
agar plates
Moser MJ et al. (1995)
cam1-E13 (E67V, E140V aa)[Overexpression]	
cell growth assay evidence	
YES
agar plates
Moser MJ et al. (1995)
cam1-E134 (E67V aa)[Overexpression]	
cell growth assay evidence	
agar plates
YES
Moser MJ et al. (1995)
cam1-E14 (E67V, E104V aa)[Overexpression]	
cell growth assay evidence	
YES
agar plates
Moser MJ et al. (1995)
cam1-E2 (E31V, E104V, E140V aa)[Overexpression]	
cell growth assay evidence	
YES
agar plates
Moser MJ et al. (1995)
cam1-E23 (E31V, E140V aa)[Overexpression]	
cell growth assay evidence	
YES
agar plates
Moser MJ et al. (1995)
cam1-E234 (E31V aa)[Overexpression]	
cell growth assay evidence	
agar plates
YES
Moser MJ et al. (1995)
cam1-E24 (E31V, E104V aa)[Overexpression]	
cell growth assay evidence	
YES
agar plates
Moser MJ et al. (1995)
cam1-E34 (E31V, E67V aa)[Overexpression]	
cell growth assay evidence	
agar plates
YES
Moser MJ et al. (1995)
cam1-E4 (E31V, E67V, E104V aa)[Overexpression]	
cell growth assay evidence	
YES
agar plates
Moser MJ et al. (1995)
cek1Δ	
cell growth assay evidence	
Samejima I et al. (1994)

**Comment by mah11** [comment]
Canto session IDs are in the curation-tool-data-load-output logs - look for "FYPO:0001801 is an obsolete term".

**Comment by ValWood** [comment]
OK I will do these ones...

**Comment by ValWood** [comment]
oh yes sorry...

**Comment by ValWood** [comment]
I think I did them all, there might be  a few stragglers...
