### ISSUE TITLE
Update where necessary to store allele synonyms

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2417]
check these, reported in
https://github.com/pombase/pombase-chado/issues/400

cdc2-M55 is a synonym of cdc2-M26.
Cdc2-130 is a synonym of  cdc2-56 (G183E aa).
Cdc2-2w is a synonym of cdc2-1w.

ksg1 also has one allele described in 2 ways
FYPO:0000046 decreased cell population growth Cell growth assay ksg1-358 (G159E)
FYPO:0000247 decreased cell population growth at high temperature Cell growth assay ksg1-208 (G159E)
(I don't think this difference appears in the logs?)

decide which is 'primary'  and transfer the other names as allele synonyms

**Comment by ValWood** [comment]
These are the only examples of allele synonyms I could find on the trackers. Are there any others. I don't think the same description with 2 names is reported in the logs is it?

 I could only find the same name with different descriptions
"does not match the existing allele with the same name"
(lots, 116).

**Comment by ValWood** [comment]
Are these the only examples of allele synonyms that we have?

**Comment by ValWood** [comment]
Clarification required. To add a synonym of an allele, I only need to add it on one session and it will propagate right?

Just in case, I will record the session I add it to.

**Comment by ValWood** [comment]
PMID:6828164 cdc2-M55(unknown) cdc2-M26 (this implies that we must know the description of M55?)

**Comment by ValWood** [comment]
hmmph. This is tricky. There are more cdc2-M26 (P137S aa).
So really, I want to change all instances of  cdc2-M55(unknown) -> cdc2-M26 (P137S aa)
and add the symonym cdc2-M55

**Comment by ValWood** [comment]
cdc2-M55 (unknown)   PMID:6828164 PMID:3322810 PMID:7262540 PMID:16453733

**Comment by ValWood** [comment]
Cdc2-130  all PMID:7262540

**Comment by ValWood** [comment]
Cdc2-2w PMID:6828164 odd  that cdc2-1w (G146D) is also in this paper. I wonder how we know that cdc2-2w is cdc2-1w

**Comment by mah11** [comment]
> I wonder how we know that cdc2-2w is cdc2-1w

Found it in the google books incarnation of the 2012 Molecular Biology of the Fission Yeast book (Buetow et al., ISBN:0323140068):

> ... two new cdc2w alleles were obtained (Fantes, 1981). One of the latter, *cdc2-2w* (= *wee2-2*), was very similar to *cdc2-1w* both in size and in strength of *cdc25* suppression, and it has recently been shown to have the same amino acid substitution as *cdc2-1w* (S. MacNeill and P. Nurse, personal communication).

So I changed the genotype in the PMID:6828164 session - it was the only one that used the cdc2-2w name.

**Comment by mah11** [comment]
I've opened https://github.com/pombase/pombase-chado/issues/752 with my stash of allele synonyms attached, so am closing this.
