### ISSUE TITLE
test for diploid

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2418]
Test from logs
https://curation.pombase.org/dumps/latest_build/logs/log.2019-06-02-22-46-46.curation-tool-data-load-output

and fix the  existing alleles  with incorrect 'type" (we now know the mutation for wee1-50, I fixed this in the original session and thought it would propagate but it needs to be fixed in every session)

~50(G850E)/wee1-50(G850E) homozygous diploid)" (from session 3352c7c843c04aca)
warning in 493636e956e2fa13: allele_type for new allele "wee1-50(amino_acid_mutation)" does not match the existing allele with the same name "wee1-50(other)" (from session 3352c7c843c04aca)~
https://curation.pombase.org/pombe/curs/3352c7c843c04aca

warning in 0b8d0d593c3d5404: description for new allele "wee1-50(G850E)" does not match the existing allele with the same name "wee1-50(wee1-50(G850E)/wee1-50(G850E) _**homozygous diploid**_)" (from session 3352c7c843c04aca)

warning in 0b8d0d593c3d5404: allele_type for new allele "wee1-50(amino_acid_mutation)" does not match the existing allele with the same name "wee1-50(other)" (from session 3352c7c843c04aca)

warning in a265654194a9e17a: description for new allele "wee1-50(G850E)" does not match the existing allele with the same name "wee1-50(wee1-50(G850E)/wee1-50(G850E) _**homozygous diploid**_)" (from session 3352c7c843c04aca)
warning in a265654194a9e17a: allele_type for new allele "wee1-50(amino_acid_mutation)" does not match the existing allele with the same name "wee1-50(other)" (from session 3352c7c843c04aca)

**Comment by ValWood** [comment]
Actually life is too short to fix these manually

grep wee1.50 log.2019-06-02-22-46-46.curation-tool-data-load-output.txt   |wc
      32   

I'll ask @kimrutherford  to fix  globally (I think there is a ticket for this)?

**Comment by ValWood** [comment]
I can't find a ticket but this is related to discussion last week. I have only  updated the allele in the first session used. 
If "other"  or "unknown" allele named and  given a description, the name  and description should propagate to existing alleles.

**Comment by ValWood** [comment]
most of the diploids are type "other" in
https://curation.pombase.org/dumps/latest_build/logs/log.2019-06-02-22-46-46.alleles_of_type_other

**Comment by ValWood** [comment]
to fix


rct1+/rct1-,SPBC17G9.05:allele-2,heterozygous diploid,{789cb7143f17138e}
cam1+/cam1-,SPAC3A12.14:allele-4,heterozygous diploid,{894e3c36003ab516}
cpc2-/cpc2-,SPAC6B12.15:allele-3,homozygous diploid,{5e0bcd0a5a6d9347}
cut12+/cut12-,SPBC649.05:allele-8,heterozygous diploid,{ed12ab2f3f0456f6}
atf1-/atf1-,SPBC29B5.01:allele-6,homozygous diploid,{87780c68f55805a1}
crb2delta/crb2delta,SPBC342.05:allele-4,homozygous diploid,{e6d26db4caf74ac5}
cdc13+ / cdc13-des2,SPBC582.03:allele-6,heterozygous diploid,{d51e46afca090869}
spk1-/spk1-,SPAC31G5.09c:allele-4,homozygous diploid,{986cd0e5341a9fe8,ad5cdccac663e13f}
alg9+/alg9-,SPAC1834.05:allele-2,heterozygous diploid,{9a1022fd353bacb9}
tor2+/tor2-,SPBC216.07c:allele-37,heterozygous diploid,{ed12ab2f3f0456f6}
rad24+/rad24-,SPAC8E11.02c:allele-6,heterozygous diploid,{894e3c36003ab516}
byr1-/byr1-,SPAC1D4.13:allele-7,homozygous diploid,{803cfb382ebb41c6}
act1+/act1-,SPBC32H8.12c:allele-7,heterozygous diploid,{ed12ab2f3f0456f6}
cdc2-asM17/cdc2-asM17,SPBC11B10.09:allele-93,homozygous diploid,{6e5ece46806fb848}
mcs2+/mcs2-,SPBP16F5.02:allele-3,heterozygous diploid,{9a1022fd353bacb9}
homozygous diploid,SPAC22H10.07:allele-4,ral3mutant/ral3mutant,{423a987e520829e2}
gea1+/gea1-,SPBC211.03c:allele-3,heterozygous diploid,contains ~50% gea1 RNA,{fa30fa9e2e0880e6}
tif35+/tif35-,SPBC18H10.03:allele-2,heterozygous diploid,{ed12ab2f3f0456f6}
pcr1-/pcr1-,SPAC21E11.03c:allele-4,homozygous diploid,{aefacb75b8af3f8a}
ste13-/ste13-,SPBC776.09:allele-5,diploid construct,{e8aedfc4412e4268}
pik3+/pik3-,SPAC458.05:allele-3,heterozygous diploid,{ed12ab2f3f0456f6}
erg10+/erg10-,SPBC215.09c:allele-2,heterozygous diploid,{9a1022fd353bacb9}
taf4+/taf4-,SPAC23G3.09:allele-2,heterozygous diploid,{9a1022fd353bacb9}
cdc2+/cdc2-,SPBC11B10.09:allele-55,heterozygous diploid,{ed12ab2f3f0456f6}
homozygous diploid,SPBC21.05c:allele-3,ral2mutant/ral2mutant,{423a987e520829e2}
rad3-136/rad3-136,SPBC216.05:allele-22,homozygous diploid,{e6d26db4caf74ac5}
heterozygous diploid,SPBC1289.03c:allele-5,spi1::ura4/-,{e113c7320f53efc5}
its3+/its3-,SPAC19G12.14:allele-5,heterozygous diploid,{ed12ab2f3f0456f6}
ste4-/ste4-,SPAC1565.04c:allele-12,homozygous diploid,{0dd384fe368bd279}
spl1+/spl-,SPATRNAPRO.02:allele-3,heterozygous diploid,{1305068212b0226d}
chk1delta/ck1delta,SPCC1259.13:allele-3,homozygous diploid,{e6d26db4caf74ac5}
fus1-B20/fus1-B20,SPAC20G4.02c:allele-3,homozygous diploid,{ef2da839886aa260}
wtf13delta/wtf13+,SPCC162.04c:allele-6,diploid heterozygous for deletion,{6c6dece2e0762651}
pop1delta/pop1delta,SPBC1718.01:allele-4,homozygous diploid,{3e366f2127c72b67}
rad9delta/rad9delta,SPAC664.07c:allele-17,homozygous diploid,{e6d26db4caf74ac5}
tor1-/tor1- diploid,SPBC30D10.10c:allele-17,homozygous diploid,{3c604e8199f9bf8b}
suc1+/suc1-,SPBC1734.14c:allele-9,heterozygous diploid,{ed12ab2f3f0456f6}
rad1delta/rad1delta,SPAC1952.07:allele-5,homozygous diploid,{e6d26db4caf74ac5}
lsg1-/lsg1-,SPCC4B3.08:allele-2,homozygous diploid,{f14b30da9b0b94c4}
byr2-/byr2-,SPBC1D7.05:allele-8,homozygous diploid,{803cfb382ebb41c6}
gpa1-/gpa1-,SPBC24C6.06:allele-4,homozygous diploid,{986cd0e5341a9fe8}
pac2+/pac2+ diploid,SPAC31G5.11:allele-3,pac2 OEP in diploid,{e25a10ee7a1d5416}
clr4+ / clr4-681,SPBC428.08c:allele-10,heterozygous diploid,{8e262e350ffaf1d4}
bgs2+/bgs2-,SPAC24C9.07c:allele-4,heterozygous diploid,{67f41f34003a2a4c}
heterozygous diploid,SPAC17H9.09c:allele-15,D59T/+,{a64b97197e845b5b}
spi1+/spi1-,SPBC1289.03c:allele-4,heterozygous diploid,{894e3c36003ab516}
ste7-111/ste7-111,SPAC23E2.03c:allele-8,homozygous diploid,{34e3d6fc4ce28886}
map1-/map1-,SPAC11E3.06:allele-3,homozygous diploid,{bf6ebbd7a7fa9fb9}
delta/delta,SPAC18B11.07c:allele-11,deletion in diploid,{47797c5ac471b4da}
pat1+/pat1+,SPBC19C2.05:allele-8,homozygous diploid,{b2b393b33cecb3fd}
skp1-/skp1-,SPAC1687.15:allele-2,homozygous diploid,{d37836a2104d53bc}
wtf13delta/wtf13delta,SPCC162.04c:allele-5,homozygous diploid deletion,{6c6dece2e0762651}
homozygous diploid,SPAC1D4.13:allele-10,byr1::LEU2/byr1::LEU2,{a64b97197e845b5b}
cig2delta/cig2delta,SPAPB2B4.03:allele-13,homozygous diploid,{6e5ece46806fb848}
ste7+/ste7+,SPAC23E2.03c:allele-9,homozygous diploid,{34e3d6fc4ce28886}
ras1-/ras1-,SPAC17H9.09c:allele-11,homozygous diploid,{803cfb382ebb41c6}
wtf18delta/wtf18+,SPCC285.07c:allele-2,diploid heterozygous for deletion,{6c6dece2e0762651}
70% deleted/ 70% deleted,SPAC22F3.03c:allele-4,homozygous diploid,{ccbd850b80722817}
homozygous diploid,SPAC16E8.09:allele-4,ral1mutant/ral1mutant,{423a987e520829e2}
asa1+/asa1-,SPAC1006.02:allele-2,heterozygous diploid,{9a1022fd353bacb9}
map1 mutant / map1 mutant,SPAC11E3.06:allele-5,homozygous diploid,{cd202708cc47017a,1cfea3361eac50c}
spn5delta/spn5delta,SPAC24C9.15c:allele-2,homozygous diploid,{f831b1df28d18c1a}
lsk1-/lsk1-,SPAC2F3.15:allele-4,homozygous diploid,{f14b30da9b0b94c4}
wee1-50,SPCC18B5.03:allele-3,wee1-50(G850E)/wee1-50(G850E) homozygous diploid,{3352c7c843c04aca,f3b2e78baad1483c,eb090de8a5e6eecf,20c49543a65c7422,a475a61f06526c04,e6d26db4caf74ac5,6788fbad2542709a,7cc0d044cd0fd080,e0f7d8e22ba14953,abf32a065b08bcd5,abf32a065b08bcd5,69acd91fe4ac8649,69acd91fe4ac8649,f655c12afd36086c,493636e956e2fa13,f4425b94136060a0,d9011560b1887e36,0b8d0d593c3d5404,9ef4b740616f8870,a265654194a9e17a,774b7f1a9f489629,52e0036cabf3303e,50a497b4c268664e,5b00ac57e2eaf984,0cad091b0886ebbf,35c498b7a5ea246c,f372ba194a5d127c,6ff4c9edff12167b,50a71e0348432087,b94d5bebcfaa526b,890568af6939d0d6,890568af6939d0d6,c7ebad4e7cc6e618,aba22b8a34948b96,5d9d97db30265d3a,9a74e80e076097ef,7b0762e353cab896,65c76fa511461156,65c76fa511461156,e254a152e54d321b,b5e73159bb3ebdf8,5bd08da8d2043fd0,eef07d879f4207d2,20d4154e6b32a4f3,acb154d034f85813,a42509fe62ac69ca,e5a15cdcd4aa21c4,298401f5017b6d28,33ab85af0ca986c2,69269d206e6ff52a,55f39e07322aab36,0c7d8adf97f44a9f,f8fd03e7d6da971d,7c80e0a2a39ec200,915dd27f11d0b65d,59258724594b2b0c,440ff0786082ec49,ea7f33ab6887fe6d,4c718237e0521f89,697b0dd703952f05,adf22222853d160f,912779b70ccb0c4b,97c70bbdfd19df1d,1bc92c0f892db627,1bc92c0f892db627,2db803bca64eaafd,93c624d8e120755e,6c335a4e1d1a262d,91da8e4c4e7b6d48,d8cd69d2eda564a7,77e60bd014f07c05,8777f8b41d27a041,31390a94c8f8643a,635732abd73e57de,d059583508b7eaab,6a5d03f63d343148,9442751303a5f327,3d3eef26565fa966,1725c65795f1d1b9,c7de46ee1570b585,1cf6a37d7872772f,7dda0b52c4bd8bfa,7240ad7f25f52209,223cbaaac1c064d0,873988311eb85ee1,1249fce88c3284d4}
spn3+/spn3-,SPBC16A3.01:allele-2,heterozygous diploid,{9a1022fd353bacb9}
cut7+/cut7-,SPAC25G10.07c:allele-18,heterozygous diploid,{894e3c36003ab516}
SPBC19C2.10+/SPBC19C2.10-,SPBC19C2.10:allele-2,heterozygous diploid,{9a1022fd353bacb9}
zfs1-/zfs1- diploid,SPBC1718.07c:allele-9,homozygous diploid,{67506e3e78c72666}
top2+/top2-,SPBC1A4.03c:allele-49,heterozygous diploid,{894e3c36003ab516}
rad1delta / rad1delta,SPAC1952.07:allele-4,homozygous diploid,{e6d26db4caf74ac5}
rad24-/rad24-,SPAC8E11.02c:allele-4,homozygous diploid,{c8cdfb930f378170}
ste7-delta/ste7-delta diploid,SPAC23E2.03c:allele-7,homozygous diploid,{34e3d6fc4ce28886}
spn2delta/spn2delta,SPAC821.06:allele-3,homozygous diploid,{f831b1df28d18c1a}
sty1-/sty1-,SPAC24B11.06c:allele-15,homozygous diploid,{87780c68f55805a1}
chk1delta/chk1delta,SPCC1259.13:allele-4,homozygous diploid,{e6d26db4caf74ac5}
rst2delta/rst2delta,SPAC6F12.02:allele-7,homozygous diploid,{81b55b09766cafa9}
cgs1delta/cgs1-1,SPAC8C9.03:allele-4,heterozygous diploid,{0c872033a21c238e}
lsc1-/lsc1-,SPBC530.13:allele-2,homozygous diploid,{f14b30da9b0b94c4}
mip1+/mip1-,SPAC57A7.11:allele-6,heterozygous diploid,{c22385c0fd392e28}
heterozygous diploid,SPAC4A8.12c:allele-12,sds22::ura4/+,{c93df2f114eaee6e}
pog1-/pog1+,SPCC24B10.22:allele-2,heterozygous diploid,{48e19f4911beba5f}
crs1delta/crs1delta,SPBC2G2.09c:allele-3,homozygous diploid,{6e5ece46806fb848}
ste7-1/ste7-1 diploid,SPAC23E2.03c:allele-6,homozygous diploid,{34e3d6fc4ce28886}
moe1-/moe1-,SPAC637.07:allele-4,homozygous diploid,{2de3ef290c749683}
cig1delta/cig1delta,SPCC4E9.02:allele-4,homozygous diploid,{6e5ece46806fb848}
sum1+/sum1-,SPAC4D7.05:allele-5,heterozygous diploid,{ed12ab2f3f0456f6}
fkh1-/fkh1-,SPBC839.17c:allele-3,homozygous diploid,{ae029b5da42522e3}
tuf1+/tuf1-,SPBC9B6.04c:allele-3,heterozygous diploid,{ed12ab2f3f0456f6}
cds1delta/cds1delta,SPCC18B5.11c:allele-14,homozygous diploid,{e6d26db4caf74ac5}
tif45+/tif45-,SPAC16E8.15:allele-2,heterozygous diploid,{ed12ab2f3f0456f6}
int6-/int6-,SPBC646.09c:allele-4,homozygous diploid,{2de3ef290c749683}
wtf18delta/wtf18delta,SPCC285.07c:allele-3,homozygous diploid deletion,{6c6dece2e0762651}
dic1+/dic1-,SPBC646.17c:allele-2,heterozygous diploid,{9a1022fd353bacb9}
spn6delta/spn6delta,SPCC188.12:allele-2,homozygous diploid,{f831b1df28d18c1a}
srk1-/srk1-,SPCC1322.08:allele-4,homozygous diploid,{ec6c2870725e0368}

**Comment by ValWood** [comment]
we can all take a few...

**Comment by ValWood** [comment]
I could not see the diploid option even though I was logged in?

**Comment by ValWood** [comment]
waiting until ready to test

**Comment by ValWood** [comment]
diploids of type "other" from

log.2019-06-05-22-47-53.curation-tool-data-load-output.txt

warning in e6d26db4caf74ac5: allele_type for new allele "rad17delta(other)" does not match the existing allele with the same name "rad17delta(deletion)" (from session 54db84e4ca91c654)
warning in e6d26db4caf74ac5: allele_type for new allele "hus1delta(other)" does not match the existing allele with the same name "hus1delta(deletion)" (from session 54db84e4ca91c654)
warning in e6d26db4caf74ac5: description for new allele "pat1-114(aaV155G,P219S,L291F)" does not match the existing allele with the same name "pat1-114(V155G,P219S,L291F)" (from session 27591db8eb4a97ec)
warning in e6d26db4caf74ac5: allele_type for new allele "pat1-114(other)" does not match the existing allele with the same name "pat1-114(amino_acid_mutation)" (from session 27591db8eb4a97ec)
warning in e6d26db4caf74ac5: allele_type for new allele "mik1delta(other)" does not match the existing allele with the same name "mik1delta(deletion)" (from session 7240ad7f25f52209)
warning in e6d26db4caf74ac5: allele_type for new allele "chk1delta(other)" does not match the existing allele with the same name "chk1delta(deletion)" (from session 54db84e4ca91c654)
warning in e6d26db4caf74ac5: description for new allele "wee1-50(wee1-50(G850E)/wee1-50(G850E) homozygous diploid)" does not match the existing allele with the same name "wee1-50(G850E)" (from session 1bc92c0f892db627)
warning in e6d26db4caf74ac5: allele_type for new allele "wee1-50(other)" does not match the existing allele with the same name "wee1-50(amino_acid_mutation)" (from session 1bc92c0f892db627)
warning in e6d26db4caf74ac5: allele_type for new allele "cds1delta(other)" does not match the existing allele with the same name "cds1delta(deletion)" (from session 54db84e4ca91c654)

**Comment by Antonialock** [comment]
done all except 91da8e4c4e7b6d48 because that session is bugging
https://github.com/pombase/canto/issues/1956

I checked all the wee1-50 ones but many didn't contain diploid phenotypes, only some did. All other sessions contained diploids that were updated.

**Comment by ValWood** [comment]
thanks!

**Comment by ValWood** [comment]
did you also do the ones of type "other"? (next box)

**Comment by Antonialock** [comment]
yes did those in https://github.com/pombase/curation/issues/2431
