### ISSUE TITLE
mrc1 allele discrepancy

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2422]
new one is most likely correct?

warning in f54393989e565d1a: description for new allele "mrc1-3A(S604A,T645A,T653A)" does not match the existing allele with the same name "mrc1-3A(S604T,T645A,T653A)"

**Comment by mah11** [comment]
yep, the one with S604T looks like a typo (probably mine ... there were some papers with a ton of alleles flying every which way)

**Comment by ValWood** [comment]
further on in log

505fabad6506e06e: description for new allele "mrc1-3A(S604A,T645A,T653A)" does not match the existing allele with the same name "mrc1-3A(S604T,T645A,T653A)" (from session f54393989e565d1a)

**Comment by mah11** [comment]
fixed
