### ISSUE TITLE
brc1 check if amino acid or nucleotide mutation (same residues reported)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2424]
warning in 5313616a6253c909: allele_type for new allele "brc1-T672A(amino_acid_mutation)" does not match the existing allele with the same name "brc1-T672A(nucleotide_mutation)" (from session 31248641de1cbfdc)

warning in 08562810fce65760: allele_type for new allele "brc1-T672A(amino_acid_mutation)" does not match the existing allele with the same name "brc1-T672A(nucleotide_mutation)" (from session 31248641de1cbfdc)

warning in 31248641de1cbfdc: allele_type for new allele "brc1-T672A(amino_acid_mutation)" does not match the existing allele with the same name "brc1-T672A(nucleotide_mutation)" (from session 31248641de1cbfdc)

warning in 5b5e46476125df7d: allele_type for new allele "brc1-T672A(amino_acid_mutation)" does not match the existing allele with the same name "brc1-T672A(nucleotide_mutation)" (from session 31248641de1cbfdc)

**Comment by mah11** [comment]
fixed
