### ISSUE TITLE
ctp1 alleles, looks like typo

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2426]
warning in 7622b54e59b561d0: description for new allele "ctp1-2A(S87A,T89A)" does not match the existing allele with the same name "ctp1-2A(T79A,T89A)" (from session e36b99ed5d28ee19)

**Comment by ValWood** [comment]
warning in 48be31dcce9039d3: allele_type for new allele "ctp1-delta-N60(partial_amino_acid_deletion)" does not match the existing allele with the same name "ctp1-delta-N60(amino_acid_mutation)"

**Comment by mah11** [comment]
corrected name for T79A,T89A to ctp1-2TA
