### ISSUE TITLE
nucleotide vs amino acid allele description

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2427]
I process all of the logs except for these:

NUCLEOTIDE VS AMINO ACID

What if we record the nucleotide variation in the "genotype comment"?

~warning in b94d5bebcfaa526b: description for new allele "cdc2-4w(C67F)" does not match the existing allele with the same name "cdc2-4w(G200T)" (from session 2db803bca64eaafd)
warning in b94d5bebcfaa526b: allele_type for new allele "cdc2-4w(amino_acid_mutation)" does not match the existing allele with the same name "cdc2-4w(nucleotide_mutation)" (from session 2db803bca64eaafd)~

warning in 26c650fccd11e213: description for new allele "prp2-1(G1160A)" does not match the existing allele with the same name "prp2-1(C387Y)" (from session bdeb75b22f017c39)
warning in 26c650fccd11e213: allele_type for new allele "prp2-1(nucleotide_mutation)" does not match the existing allele with the same name "prp2-1(amino_acid_mutation)" (from session bdeb75b22f017c39)
warning in 16802f31036c5732: description for new allele "cut8-563(S201P)" does not match the existing allele with the same name "cut8-563(T601C)" (from session 20b51f83ef3dce69)
warning in 16802f31036c5732: allele_type for new allele "cut8-563(amino_acid_mutation)" does not match the existing allele with the same name "cut8-563(nucleotide_mutation)" (from session 20b51f83ef3dce69)
warning in d68db45202ee441d: description for new allele "prp1-4(C1846A,C2336T)" does not match the existing allele with the same name "prp1-4(L616I,S779L)" (from session 
13cff5989c78e70f)
warning in d68db45202ee441d: allele_type for new allele "prp1-4(nucleotide_mutation)" does not match the existing allele with the same name "prp1-4(amino_acid_mutation)" (from session 13cff5989c78e70f)
warning in d5d0ef3568cea1fd: description for new allele "prp2-1(G1160A)" does not match the existing allele with the same name "prp2-1(C387Y)" (from session bdeb75b22f017c39)
warning in d5d0ef3568cea1fd: description for new allele "prp2-1(G1160A)" does not match the existing allele with the same name "prp2-1(C387Y)" (from session bdeb75b22f017c39)
warning in d5d0ef3568cea1fd: allele_type for new allele "prp2-1(nucleotide_mutation)" does not match the existing allele with the same name "prp2-1(amino_acid_mutation)" (from session bdeb75b22f017c39)
warning in bdeb75b22f017c39: description for new allele "prp2-1(G1160A)" does not match the existing allele with the same name "prp2-1(C387Y)"
warning in bdeb75b22f017c39: description for new allele "prp1-4(C1846A,C2336T)" does not match the existing allele with the same name "prp1-4(L616I,S779L)" (from session 13cff5989c78e70f)
warning in 24a3853610543a99: description for new allele "prp2-1(G1160A)" does not match the existing allele with the same name "prp2-1(C387Y)" (from session bdeb75b22f017c39)
warning in 24a3853610543a99: description for new allele "prp1-4(C1846A,C2336T)" does not match the existing allele with the same name "prp1-4(L616I,S779L)" (from session 13cff5989c78e70f)
warning in acb154d034f85813: description for new allele "cdc2-4w(C67F)" does not match the existing allele with the same name "cdc2-4w(G200T)" (from session 2db803bca64eaafd)
warning in acb154d034f85813: allele_type for new allele "cdc2-4w(amino_acid_mutation)" does not match the existing allele with the same name "cdc2-4w(nucleotide_mutation)" (from session 2db803bca64eaafd)
warning in a87bae2017e8cda0: allele_type for new allele "cdc6-L591G(amino_acid_mutation)" does not match the existing allele with the same name "cdc6-L591G(nucleotide_mutation)" (from session 593e1f8fb43caaa9)
warning in cec0408e1de768d2: description for new allele "prp2-1(G1160A)" does not match the existing allele with the same name "prp2-1(C387Y)" (from session bdeb75b22f017c39)
warning in 58d8ad0dec113279: description for new allele "cdc10-M17(G1179A)" does not match the existing allele with the same name "cdc10-M17(A393T)" (from session 5b00ac57e2eaf984)
warning in 58d8ad0dec113279: description for new allele "cdc10-K30(C1286T)" does not match the existing allele with the same name "cdc10-K30(T429I)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: allele_type for new allele "cdc10-K30(nucleotide_mutation)" does not match the existing allele with the same name "cdc10-K30(amino_acid_mutation)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: description for new allele "cdc10-MBC4(C2119T)" does not match the existing allele with the same name "cdc10-MBC4(R707->STOP)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: allele_type for new allele "cdc10-MBC4(nucleotide_mutation)" does not match the existing allele with the same name "cdc10-MBC4(amino_acid_mutation)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: description for new allele "cdc10-M47(G1459A)" does not match the existing allele with the same name "cdc10-M47(A487T)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: allele_type for new allele "cdc10-M47(nucleotide_mutation)" does not match the existing allele with the same name "cdc10-M47(amino_acid_mutation)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: description for new allele "cdc10-M4(G1177A)" does not match the existing allele with the same name "cdc10-M4(A393T)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: allele_type for new allele "cdc10-M4(nucleotide_mutation)" does not match the existing allele with the same name "cdc10-M4(amino_acid_mutation)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: description for new allele "cdc10-K28(P383S,R610C)" does not match the existing allele with the same name "cdc10-K28(C1147T,C1557T,C1828T)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: allele_type for new allele "cdc10-K28(amino_acid_mutation)" does not match the existing allele with the same name "cdc10-K28(nucleotide_mutation)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: description for new allele "cdc10-M15(A393T)" does not match the existing allele with the same name "cdc10-M15(G1177A)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: allele_type for new allele "cdc10-M15(amino_acid_mutation)" does not match the existing allele with the same name "cdc10-M15(nucleotide_mutation)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: description for new allele "cdc10-MBC41(T429I)" does not match the existing allele with the same name "cdc10-MBC41(C1286T)" (from session 58d8ad0dec113279)
warning in 58d8ad0dec113279: allele_type for new allele "cdc10-MBC41(amino_acid_mutation)" does not match the existing allele with the same name "cdc10-MBC41(nucleotide_mutation)" (from session 58d8ad0dec113279)

**Comment by ValWood** [comment]
https://github.com/pombase/pombase-chado/issues/172

**Comment by ValWood** [comment]
ACtually, let's represent all as amino acid and just record the equivalences here
pombase/pombase-chado#172

**Comment by ValWood** [comment]
warning in b94d5bebcfaa526b: description for new allele "cdc2-4w(C67F)" does not match the existing allele with the same name "cdc2-4w(G200T)" (from session 2db803bca64eaafd)
warning in b94d5bebcfaa526b: allele_type for new allele "cdc2-4w(amino_acid_mutation)" does not match the existing allele with the same name "cdc2-4w(nucleotide_mutation)" (from session 2db803bca64eaafd)

but on the cdc2 page, I do not see cdc2-4w(G200T)

**Comment by mah11** [comment]
notes on cdc2-4w:
- session IDs in comment above are out of date; G200T description found in current log file and changed to amino acid description
- store cdc2-4w = aa C67F = ntG200T in allele comment when they become addable/editable

**Comment by mah11** [comment]
finally purged all the warnings
