### ISSUE TITLE
session with wee1-50 (diploids)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2431]
curs/3352c7c843c04aca

has entries in the logs:
warning in e6d26db4caf74ac5: description for new allele "wee1-50(wee1-50(G850E)/wee1-50(G850E) homozygous diploid)" does not match the existing allele with the same name "wee1-50(G850E)" (from session 1bc92c0f892db627)
warning in e6d26db4caf74ac5: allele_type for new allele "wee1-50(other)" does not match the existing allele with the same name "wee1-50(amino_acid_mutation)" (from session 1bc92c0f892db627)
warning in e6d26db4caf74ac5: allele_type for new allele "cds1delta(other)" does not match the existing allele with the same name "cds1delta(deletion)" (from session 4dfa9e1e417a7efe)

but in this session, I can't see any reference to diploid alleles.  This might be becase the diplod annotation was in "other" and I fixed it to the correct type "amino acid substitution"  . This would lose any text stored in other (I thought diploid was recorded in background).

However, it seems unnecessary to fix this becasuse the genotype in question hasno annotations. There are quite a few  multi gene genotypes  in this session with no annotations, so this could be an oversight.

Could you double check the session, and create the correct alleles as diploids where necessary?

**Comment by Antonialock** [comment]
done
