### ISSUE TITLE
List "allowable phenotypes" for genetic interaction types

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2433]
Most general phenotypes applicable to each genetic interaction type

GI | final phenotype terms term(s) | gene A phenotype terms
 --- | --- | ---
Dosage Growth Defect - Overexpression/increased dosage of one gene causes a growth defect in a strain that is mutated/deleted for another gene (e.g. PMID: 15166139). | FYPO:0000139 cell population growth phenotype | NORMAL POPULATION GROWTH
Dosage Lethality - Overexpression/increased dosage of one gene causes lethality in a strain that is mutated/deleted for another gene (e.g. PMID: 10805723, Fig. 3). | FYPO:0002059 inviable cell population | FYPO:0002058 viable cell population
Dosage Rescue - Overexpression/increased dosage of one gene rescues the lethality or growth defect of a strain mutated/deleted for another gene (e.g. PMID: 12207708, Fig. 3) | FYPO:0000139 cell population growth phenotype OR FYPO:0002059 inviable cell population | NORMAL POPULATION GROWTH OR FYPO:0002058 viable cell population
Negative Genetic - Mutations/deletions in separate genes, each of which alone causes a minimal phenotype, but when combined in the same cell results in a more severe fitness defect or lethality under a given condition (e.g. PMID: 20093466). This term is reserved for high or low throughput studies with scores. | N/A - excluded from Canto | -
Phenotypic Enhancement - Mutation/deletion/overexpression of one genes results in enhancement of any phenotype (other than lethality/growth defect) associated with mutation/deletion/overexpression of another gene, for example response to DNA damage or transcriptional output (e.g. PMID: 11890933, Fig. 2).|  NOT (FYPO:0000139 cell population growth phenotype OR FYPO:0002059 inviable cell population) | SAME AS FINAL
Phenotypic Suppression - Mutation/deletion/overexpression of one gene results in suppression of any phenotype (other than lethality/growth defect) associated with mutation/deletion/overexpression of another gene (e.g. PMID: 10073572). | NOT (FYPO:0000139 cell population growth phenotype OR FYPO:0002059 inviable cell population) |  SAME AS FINAL
Positive Genetic - Mutations/deletions in separate genes, each of which alone causes a minimal phenotype, but when combined in the same cell results in a less severe fitness defect than expected under a given condition.(e.g. PMID: 20093466). This term is reserved for high or low throughput studies with scores. | N/A - excluded from Canto | -
Synthetic Growth Defect - Mutations/deletions in separate genes, each of which alone causes a minimal phenotype, but when combined in the same cell results in a significant growth defect under a given condition (e.g. PMID: 12871902, Fig. 8). | FYPO:0000139 cell population growth phenotype (possibly can be more specific, reduced growth?) | -
Synthetic Haploinsufficiency - A genetic interaction is inferred when mutations or deletions in separate genes, at least one of which is hemizygous, cause a minimal phenotype alone but result in lethality when combined in the same cell under a given condition (e.g. PMID: 17167106). |  FYPO:0002059 inviable cell population (MUST BE A HAPLOID/DIPLOID) | -
Synthetic Lethality - Mutations/deletions in separate genes, each of which alone causes a minimal phenotype, but when combined in the same cell results in lethality under a given condition (e.g. PMID: 14690608). | FYPO:0002059 inviable cell population | FYPO:0002058 viable cell population
Synthetic Rescue - Mutation/deletion of one gene rescues the lethality or growth defect of a strain mutated/deleted for another gene (e.g. PMID: 14734533, Fig. 1). | FYPO:0002058 viable cell population | FYPO:0002059 inviable cell population

**Comment by ValWood** [comment]
Here  we can collect the *most general* phenotypes applicable to each genetic interaction type
while the implementation is in progress.

Please add as you do curation over the next few weeks.

**Comment by ValWood** [comment]
Actually, I think I have done it.
We should be able to limit the  existing phenotype annotations presented by quite a lot using this ...

**Comment by mah11** [comment]
Edited the table to reflect the fact that Negative Genetic and Positive Genetic aren't included in Canto, because they're used only for scored values that we collect in bulk-format files.

**Comment by ValWood** [comment]
I tried to add an extra column to this table but I stuffed it up

**Comment by ValWood** [comment]
I added gene a phenotypes

**Comment by mah11** [comment]
note: we've never used Synthetic Haploinsufficiency ...

**Comment by ValWood** [comment]
Interaction type  |  phenotype to record | Other
--- | --- | ---
Dosage growth defect
Dosage lethality
Dosage rescue
Phenotypic enhancement
Phenotypic supression
Synthetic growth defect
Synthetic haploinsufficiency
Synthetic lethality
Synthetic rescue

**Comment by ValWood** [comment]
see
https://github.com/pombase/canto/issues/2301#issuecomment-765535014
