### ISSUE TITLE
diploids to fix

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2435]
crs1delta/crs1delta,SPBC2G2.09c:allele-3,homozygous diploid,{6e5ece46806fb848}
cig1delta/cig1delta,SPCC4E9.02:allele-2,homozygous diploid,{6e5ece46806fb848}
cig2delta/cig2delta,SPAPB2B4.03:allele-9,homozygous diploid,{6e5ece46806fb848}

**Comment by Antonialock** [comment]
think they are done now
