### ISSUE TITLE
move GFP to "background"?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2436]
- [x]  ndc80-GFP,SPBC11C11.03:allele-6,ndc80 tagged with GFP,{fe7a0f32d4e76d5d}
keeper - added double mutant phenotypes for genes in fig 2 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5674884/
- [x] GFP-pps1,SPCC1442.12:allele-4,N-terminal GFP fusion,{61b0bcb9898f64f7}
ok, C-term tag has abnormal phenotype, N term tag has normal phenotype

- [x] GFP-cnp1,SPBC1105.17:allele-9,N-terminally tagged cnp1,{440ff0786082ec49}
ok, C-term tag has abnormal phenotype, N term tag has normal phenotype

- [x] GFP-wsp1,SPAC4F10.15c:allele-7,N-terminal GFP fusion,{6eeb7666f8d6b4bf}
ok, has phenotypes

- [x] cdc17-1-175/M20A-GFP,SPAC20G8.01:allele-17,N-terminal 175 amino acids of cdc17,with M20A mutation,fused to GFP,{b2890d84738249aa}
changed alleles from "other" to partial deletion and removed the GFP

- [x] GFP-N-Pxl1,SPBC4F6.12:allele-15,GFP fused to Pxl1-1-257,{296b721850a6d19b}
removed GFP part

- [x] cdc15-gc1,SPAC20G8.05c:allele-19,Hypomorphic allele cdc15-GFP,{80b382d361649949}
ok GFP-tagging of Cdc15 at the C-terminus makes the protein partially nonfunctional, generating a hypomorphic allele also referred as cdc15-gc1

- [x] myo1-GFP-H,SPBC146.13c:allele-9,myo1-H(delta772-1217) with N-terminal GFP fusion,{f9a2c4769a3f8ab9}
fixed

- [x] ypt4-GFP+,SPAC1B3.11c:allele-4,C-terminally tagged ypt4,{00e0a3ede15887bf}
ok

etc

**Comment by Antonialock** [comment]
sometimes tagging with GFP leads to a phenotype (also sometimes a C-term tag gives a phenotype but not the N-term tag - usually proteins are C terminally tagged) I think it is good to include the ones that give a phenotype as a reference that some lab has seen that the tag interferes with function)

**Comment by ValWood** [comment]
ok makes sense-  are the instructions clear about this?
If so we can close.

**Comment by Antonialock** [comment]
what instructions? It's an allele....even if it's normal I don't think it's wrong to state eg. "normall vegetative cell population growth " or "viable veg cell with normal morphology" (I wouldn't go out of my way to add this but actually for an experimentalist it is valuable information)

**Comment by ValWood** [comment]
https://curation.pombase.org/pombe/docs/fypo_annotation

should say something about only including a TAG in foreground if it affects the phenotype....

but I guess we can just fix any anomalies when checking
