### ISSUE TITLE
PubMed idd appear in "evidence" column for disease?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2437]
PMID:10497270                                                             | disease_ontology         |     2
 PMID:11463848                                                             | disease_ontology         |     1
 PMID:21653323                                                             | disease_ontology         |     1
 PMID:24782769                                                             | disease_ontology         |     7
 PMID:26610878                                                             | disease_ontology         |     1
 PMID:29432562                                                             | disease_ontology         |     1
 PMID:30190335                                                             | disease_ontology         |     1
 PMID:9542324                                                              | disease_ontology         |     1

from
https://curation.pombase.org/dumps/latest_build/logs/log.2019-06-17-22-46-35.annotation_counts_by_cv

**Comment by ValWood** [comment]
PMID:11463848                                                             | disease_ontology         |     1
 PMID:21653323                                                             | disease_ontology         |     1
 PMID:30190335                                                             | disease_ontology         |     1
 PMID:29432562                                                             | disease_ontology         |     1

**Comment by ValWood** [comment]
PMID:24782769                                                             | disease_ontology         |     7

**Comment by ValWood** [comment]
PMID:10497270                                                             | disease_ontology         |     2
 PMID:11463848                                                             | disease_ontology         |     1
 PMID:21653323                                                             | disease_ontology         |     1
 PMID:24782769                                                             | disease_ontology         |     7
 PMID:26610878                                                             | disease_ontology         |     1
 PMID:29432562                                                             | disease_ontology         |     1
 PMID:30190335                                                             | disease_ontology         |     1
 PMID:9542324                                                              | disease_ontology         |     1

**Comment by kimrutherford** [comment]
There were some tabs missing in pombe-embl/external_data/disease/pombase_disease_associations.txt
so the PMIDs were in the evidence column.  I've checked in a fix.  It think I was in time for the change to be visible in the morning.

**Comment by kimrutherford** [comment]
Fixed!
