### ISSUE TITLE
Matrix paper, annotation removal date

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2439]
This annotation was removed in one round but I don't have the date.
What is the easiest way to find the approximate date of removal?

  | PomBase |   | gpt1 | S. pombe | endoplasmic reticulum unfolded protein response | signaling | IMP | annotation error, incorrect term selected |   |   |   | changed to "ER associated misfolded protein catabolic process |   |

**Comment by ValWood** [comment]
and

  | PomBase | SPBC2D10.09 | snr1 | S. pombe | stress activated MAPK cascade | signaling | IPI | annotation error, pathway target |   |

**Comment by mah11** [comment]
I don't know of any *easy* way to find a removal date.

**Comment by kimrutherford** [comment]
> This annotation was removed in one round but I don't have the date.

If it was removed since mid-November 2018 I can find out with some querying as all the Chado databases since then are live on oliver1.  Older Chados are archived.

**Comment by ValWood** [comment]
no worries, I will collect them and figure a way...

**Comment by ValWood** [comment]
I am going to put "unknown" for those I can't find and will get t Seth to query if reviewers complain (unlikely)
