### ISSUE TITLE
php5 GO:0140110

### ISSUE THREAD

**Issue by mah11** [pombase/curation#2447]
The GO annotation checks are flagging an annotation to GO:0140110 because the term is in the do-not-annotate set. I had a quick look at the paper but I'm not sure which more specific term would work. Could you have a look, since you curated the paper? thx

http://snapshot.geneontology.org/reports/pombase-report.html

WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms -- PomBase SPBC3B8.02 php5 GO:0140110 PMID:9372932 IMP F CCAAT-binding factor complex subunit Php5 protein taxon:4896 20190517 PomBase part_of(GO:1903759)

**Comment by ValWood** [comment]
USED
transcription coactivator activity
since it doesn't bind DNA directly

**Comment by mah11** [comment]
cheers, that'll take us back to 0 errors :)
