### ISSUE TITLE
A few annotations without evidence codes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#2448]
While working on pombase/canto#1965 I noticed 3 annotations from 2014 that have no evidence code.  Since they are so old and there are only a few, I suspect there was a temporary bug back then.

molecular function:
https://curation.pombase.org/pombe/curs/760045d7bb2de1aa

physical interaction (2):
https://curation.pombase.org/pombe/curs/ad3a8b0c8d718477

**Comment by ValWood** [comment]
weird that they managed to do that. Both are in session not yet submitted...

**Comment by ValWood** [comment]
@kimrutherford  anything to do here. I guess if it is only in unsubmitted sessiosn we could fix later?

**Comment by ValWood** [comment]
I added the evidence to these. I guess this can close as this was a bug that is now fixed.
