### ISSUE TITLE
elongator and disease

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2453]
Only elp2 &4 have disease association.

elp3 is too:
https://github.com/geneontology/go-annotation/issues/2540

I imagine all are....

**Comment by Antonialock** [comment]
Existing publications suggest it's a disease modifier / susceptibility loci - not disease causing on its own?
https://www.ncbi.nlm.nih.gov/pubmed/?term=elp3+disease

Also no annotation made in omim
https://www.omim.org/entry/612722?search=elp3&highlight=elp3

leave for now?

**Comment by ValWood** [comment]
yep OK...
