### ISSUE TITLE
	Group II intron splicing

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2456]
this is non-nuclear/non-spliceosomal (although I'm not sure this is absolutely clear from the def)

**Comment by ValWood** [comment]
https://www.pombase.org/term/GO:0000373

**Comment by ValWood** [comment]
fixed

**Comment by Antonialock** [comment]
I have no idea what this ticket was about :D

**Comment by ValWood** [comment]
I removed "group II intron splicing" (it isn't group II splicing, this is a different mechanism)
