### ISSUE TITLE
CNP-T-W-S-X complex

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2460]
Xiangwei He 

Cnp20, wip1, mhf1, mhf2

**Comment by ValWood** [comment]
This is the CENP-A containing nucleosome
https://www.pombase.org/term/GO:0043505
Also called CenH3

**Comment by ValWood** [comment]
and CENP-S-T-W-X

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/17629
