### ISSUE TITLE
Nbr1 autophagy 

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2464]
Nbr1 is annotated to macroautophagy but according to LL it’s involved in escrt mediated endosomal microautophagy...he cited 2015 publication. 

Maybe go:0120113 protein localization by the NVT pathway
Need additional parentage? 

Also might be possible to add an MF to nbr1
(Cargo receptor activity(

**Comment by ValWood** [comment]
Form this my  talk my understanding was that nbr1  is a cargo receptor for  macroautophagy, but in GO this is restricted to  endocytosis, bo this  woud need to be adressed.


I find "protein localization by the NVT pathway " a really strange term. Then I notice that a synonym is 
cytoplasm to vacuole targetting. Tagretting is  part of transport, but this term does not have a transport parentage, only localization. 

I will open a ticket for this part now...

**Comment by ValWood** [comment]
actually that is essentially what you said...

**Comment by ValWood** [comment]
cargo receptor activity
--
  | has direct input ape2 part of cytoplasm to vacuole transport by the NVT pathway


will remove ISS "

macroautophagy and  close for now.

**Comment by ValWood** [comment]
PMID:26365378

So, what is the relationship between
GO:0120113 | cytoplasm to vacuole transport by the NVT pathway
(the term LL used)
and microautophagy?

**Comment by ValWood** [comment]
I removed the ISS  above but 
	cytoplasm to vacuole transport by the NVT pathway
is  not related to autophagy. Should it be?

**Comment by Antonialock** [comment]
not sure - it's delivering hydrolases to vacuoles, so I guess it is required for autophagy

it relies on
GO:0032509 endosome transport via multivesicular body sorting pathway ?

"Here, we show that fission yeast Nbr1, a homolog of mammalian autophagy receptor NBR1, interacts with and facilitates the transport of two cytosolic hydrolases into vacuoles........
......NVT components colocalize with ESCRTs at multivesicular bodies (MVBs) and rely on ubiquitination for their transport."

**Comment by ValWood** [comment]
I think this is OK now, improvements  might require better organization of GO
