### ISSUE TITLE
Rits complex

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2465]
Has 3 members according to Jin qw 
Ago1 tas3 chp1

We have a 4th subunit annotated

**Comment by ValWood** [comment]
Weird. That uses colocalizes_with, but we don't use co-localizes with for complexes. It should be complex binding

**Comment by Antonialock** [comment]
removed the CC annotations. 

It is involved in assembling the complex. It already had "protein binding" part of RITS complex assembly
which seems spot on
