### ISSUE TITLE
Polyphosphate biosynthesis

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2467]
Not anoitated vtc1,2,3

**Comment by Antonialock** [comment]
Vtc4 catalytic subunit

**Comment by ValWood** [comment]
The transporter shouldn't be biosynthsis though should it?

**Comment by Antonialock** [comment]
On a quick mobile look it seems like it could be

https://jcs.biologists.org/content/127/23/5093

**Comment by ValWood** [comment]
cool. I was trying to find out about these recently. The polyphosphate  related activities are some of the things that don't slim. Maybe we need a slim term for "storage"?

**Comment by Antonialock** [comment]
maybe? SPBC713.07c has 'energy reserve metabolic process"

I added
/GO="aspect=P; term=energy reserve metabolic process; GOid=GO:0006112; evidence=IC; db_xref=GO_REF:0000111; from=GO:0006799; date=20191115"

/GO="aspect=P; term=polyphosphate biosynthetic process; GOid=GO:0006799; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000000874; date=20191115"

to Vtc1,2,4
Also added exopolyphosphatase activity to SPBC713.07c, it only had endopolyphosphatase activity but it does both
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0119594
