### ISSUE TITLE
gene nomenclature at JCS

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#247]
The Journal of Cell Science has a nice set of recommendations and links for genetic nomenclature, but their list doesn't include either budding or fission yeast. Could pester the editors to add links; maybe also cc SGD curators ...

http://jcs.biologists.org/site/author/manuscript_preparation.xhtml#genetic

wonder if any other journals have similar ...?

Original comment by: mah11

**Comment by ValWood** [comment]
Put this as "blue sky" as we have very few nomenclature issues it isn't high priority. But it is something we should keep on the radar and do...

**Comment by ValWood** [comment]
actually  - we could craft a letter to journals about both
https://github.com/pombase/curation/issues/2226

**Comment by ValWood** [comment]
future doc
