### ISSUE TITLE
Cut12, polo, wee1

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2476]
Cut12 activates plo1 which inactivates wee1

http://m.genesdev.cshlp.org/content/17/12/1507.short

**Comment by Antonialock** [comment]
https://www.ncbi.nlm.nih.gov/m/pubmed/15917811/

**Comment by ValWood** [comment]
cut12 isn't really activation, it's recruitment....

**Comment by ValWood** [comment]
great, this omission was noted here:
https://github.com/pombase/curation/issues/1638
I wasn't sure where the data was

**Comment by ValWood** [comment]
You were right cut12 does seem to directly regulate plo1
