### ISSUE TITLE
glycosylation diseases a heads up

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2478]
I added
/controlled_curation="term=disease associated, MOGS-CDG disorder; db_xref=PMID:30389790; date=20190723"

to 
gls1

FYI
The congenital disorders of glycosylation (CDG) are a group of more than 100 human inherited syndromes, most of them (70%) produced by deficiencies in protein N-glycosylation pathways (7). The clinical features of these disorders involve many organ systems but are especially common in the nervous, hepatic, visual, and immune systems. Patients display patholo- gies that include delayed growth, developmental disabilities, low muscle tone, visual problems, and incomplete brain devel- opment. Type I CDG are caused by defects in the biosynthesis of lipid-linked oligosaccharides (LLO) and their transfer to pro- teins, whereas type II CDG are caused by defects in the glycan processing of protein-linked oligosaccharides (NLO). The first type results in glycoprotein hypoglycosylation (normally occu- pied glycosylation sites are empty), but the remaining glycans
Downloaded from http://www.jbc.org/ at Cambridge University Library on July 23, 2019
have almost normal structures, and in the second type there is a normal occupation of glycosylation sites, but the attached glycans have abnormal structures (7). Regarding the type II diseases, MOGS-CDG (also known as CDG-IIb) is produced by mutations in GI, the enzyme responsible for the first step in N-glycan processing (Fig. 1). The clinical course of the disease is progressive and characterized by multiple neuro- logical complications, severe hypogammaglobulinemia, hep- atomegaly, hypoventilation, feeding problems, seizures, and sometimes a fatal outcome (8, 9).

**Comment by Antonialock** [comment]
we have this annotation already.; Added one with the ref and capture ref for model.
