### ISSUE TITLE
sen1 NOT annotation

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2480]
I removed GO:0006369  termination of RNA polymerase II transcription from sen1 
based on RT ticket #7021

in the ticket it is said that this process is not conserved to pombe, and it can get a NOT annotation from this paper:

PMID:30341288
https://curation.pombase.org/pombe/view/object/pub/12477?model=track

I resent the paper to the community curator.

**Comment by Antonialock** [comment]
on hold for a while, hopefully the community curator will pick it up

**Comment by ValWood** [comment]
OK closing if session assigned
