### ISSUE TITLE
move "inhibited_by"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2483]
Database | GeneID | Gene product | Qualifier | GO ID | Reference | ECO | With/From | Aspect |   | Synonyms | Type

PomBase | SPAC6F12.02 | rst2 |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | PMID:24155978 | IDA |   | F | transcription factor Rst2
PomBase | SPAC6F12.02 | rst2 |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | PMID:24155978 | IDA |   | F | transcription factor Rst2
PomBase | SPAC6F12.02 | rst2 |   | GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific | PMID:24155978 | IDA |   | F | transcription factor Rst2
PomBase | SPAC1B3.03c | wis2 |   | GO:0003755 | peptidyl-prolyl cis-trans isomerase activity | PMID:14644438 | IDA |   | F | cyclophilin family peptidyl-prolyl cis-trans isomerase Wis2 | cyp5
PomBase | SPAC57A10.03 | cyp1 |   | GO:0003755 | peptidyl-prolyl cis-trans isomerase activity | PMID:14644438 | IDA |   | F | cyclophilin family peptidyl-prolyl cis-trans isomerase Cyp1
PomBase | SPBC1709.04c | cyp3 |   | GO:0003755 | peptidyl-prolyl cis-trans isomerase activity | PMID:14644438 | IDA |   | F | cyclophilin family peptidyl-prolyl cis-trans isomerase Cyp3
PomBase | SPBC28F2.03 | ppi1 |   | GO:0003755 | peptidyl-prolyl cis-trans isomerase activity | PMID:14644438 | IDA |   | F | cyclophilin family peptidyl-prolyl cis-trans isomerase Cyp2 | cyp2
PomBase | SPBP8B7.25 | cyp4 |   | GO:0003755 | peptidyl-prolyl cis-trans isomerase activity | PMID:14644438 | IDA |   | F | cyclophilin family peptidyl-prolyl cis-trans isomerase Cyp4
PomBase | SPAC22G7.06c | ura1 |   | GO:0003922 | GMP synthase (glutamine-hydrolyzing) activity | PMID:8590465 | IGI | SGD:S000003666 | F | carbamoyl-phosphate synthase (glutamine hydrolyzing), aspartate carbamoyltransferase Ura1
PomBase | SPBC2F12.14c | gua1 |   | GO:0003938 | IMP dehydrogenase activity | PMID:4309177 | IDA |   | F | IMP dehydrogenase Gua1
PomBase | SPBC2F12.14c | gua1 |   | GO:0003938 | IMP dehydrogenase activity | PMID:4309177 | IDA |   | F | IMP dehydrogenase Gua1
PomBase | SPBC2F12.14c | gua1 |   | GO:0003938 | IMP dehydrogenase activity | PMID:4309177 | IDA |   | F | IMP dehydrogenase Gua1
PomBase | SPBC428.11 | met17 |   | GO:0003961 | O-acetylhomoserine aminocarboxypropyltransferase activity | PMID:6526818 | IDA |   | F | homocysteine synthase Met17 | cys2
PomBase | SPBP35G2.07 | ilv1 |   | GO:0003984 | acetolactate synthase activity | PMID:4821071 | IDA |   | F | acetolactate synthase catalytic subunit
PomBase | SPBP35G2.07 | ilv1 |   | GO:0003984 | acetolactate synthase activity | PMID:4698210 | IDA |   | F | acetolactate synthase catalytic subunit
PomBase | SPAC4G9.03 | adk1 |   | GO:0004017 | adenylate kinase activity | PMID:8496185 | IDA |   | F | adenylate kinase Adk1
PomBase | SPAC144.03 | ade2 |   | GO:0004019 | adenylosuccinate synthase activity | PMID:4708672 | IDA |   | F | adenylosuccinate synthetase Ade2 | min3\|min10
PomBase | SPAC144.03 | ade2 |   | GO:0004019 | adenylosuccinate synthase activity | PMID:8346915 | IDA |   | F | adenylosuccinate synthetase Ade2 | min3\|min10
PomBase | SPAP7G5.04c | lys1 |   | GO:0004043 | L-aminoadipate-semialdehyde dehydrogenase activity | PMID:8590464 | IMP |   | F | aminoadipate-semialdehyde dehydrogenase
PomBase | SPAC22G7.06c | ura1 |   | GO:0004070 | aspartate carbamoyltransferase activity | PMID:8590465 | IGI | SGD:S000003666 | F | carbamoyl-phosphate synthase (glutamine hydrolyzing), aspartate carbamoyltransferase Ura1
PomBase | SPAC22G7.06c | ura1 |   | GO:0004088 | carbamoyl-phosphate synthase (glutamine-hydrolyzing) activity | PMID:8590465 | IGI | SGD:S000003666 | F | carbamoyl-phosphate synthase (glutamine hydrolyzing), aspartate carbamoyltransferase Ura1
PomBase | SPAC22A12.11 | dak1 |   | GO:0004371 | glycerone kinase activity | PMID:10091325 | IDA |   | F | dihydroxyacetone kinase Dak1
PomBase | SPAC3G9.07c | hos2 |   | GO:0004407 | histone deacetylase activity | PMID:9781677 | IDA |   | F | histone deacetylase (class I) Hos2 | phd1\|hda1
PomBase | SPAC23C11.11 | cka1 |   | GO:0004674 | protein serine/threonine kinase activity | PMID:25410910 | IDA |   | F | serine/threonine protein kinase Cka1 | orb5
PomBase | SPBC216.05 | rad3 |   | GO:0004674 | protein serine/threonine kinase activity | PMID:21084840 | IDA |   | F | ATR checkpoint kinase Rad3
PomBase | SPBC216.07c | tor2 |   | GO:0004674 | protein serine/threonine kinase activity | PMID:22645648 | IDA |   | F | serine/threonine protein kinase Tor2 | SPBC646.01c
PomBase | SPAC19D5.01 | pyp2 |   | GO:0004725 | protein tyrosine phosphatase activity | PMID:8256510 | IDA |   | F | tyrosine phosphatase Pyp2
PomBase | SPAC26F1.10c | pyp1 |   | GO:0004725 | protein tyrosine phosphatase activity | PMID:8256510 | IDA |   | F | tyrosine phosphatase Pyp1
PomBase | SPBC1677.03c | tda1 |   | GO:0004794 | L-threonine ammonia-lyase activity | PMID:4698209 | IDA |   | F | threonine ammonia-lyase Tda1
PomBase | SPCC548.07c | ght1 |   | GO:0005358 | high-affinity glucose:proton symporter activity | PMID:9090050 | IMP |   | F | plasma membrane high-affinity glucose:proton symporter Ght1
PomBase | SPCC548.07c | ght1 |   | GO:0005358 | high-affinity glucose:proton symporter activity | PMID:9090050 | IMP |   | F | plasma membrane high-affinity glucose:proton symporter Ght1
PomBase | SPBC1347.06c | cki1 |   | GO:0005524 | ATP binding | PMID:8692811 | IDA |   | F | serine/threonine protein kinase Cki1 | ck1
PomBase | SPCC1753.04 | tol1 |   | GO:0008441 | 3'(2'),5'-bisphosphate nucleotidase activity | PMID:10850973 | IDA |   | F | 3'(2'),5'-bisphosphate nucleotidase/inositol-1,4- bisphosphate 1-phosphatase
PomBase | SPCC1753.04 | tol1 |   | GO:0008441 | 3'(2'),5'-bisphosphate nucleotidase activity | PMID:10850973 | IDA |   | F | 3'(2'),5'-bisphosphate nucleotidase/inositol-1,4- bisphosphate 1-phosphatase
PomBase | SPBP18G5.02 | pgs1 |   | GO:0008444 | CDP-diacylglycerol-glycerol-3-phosphate 3-phosphatidyltransferase activity | PMID:9468529 | IDA |   | F | CDP-diacylglycerol-glycerol-3-phosphate3-phosphatidyltransferase Pgs1
PomBase | SPBC2G2.01c | liz1 |   | GO:0015233 | pantothenate transmembrane transporter activity | PMID:15075270 | IGI | SGD:S000000623 | F | plasma membrane pantothenate transmembrane transporter Liz1 | SPBC4B4.13c
PomBase | SPAPB8E5.03 | mae1 |   | GO:0015366 | malate:proton symporter activity | PMID:1293882 | IDA |   | F | plasma membrane malate/succinate:proton symporter Mae1
PomBase | SPAC977.10 | nhe1 |   | GO:0015385 | sodium:proton antiporter activity | PMID:1314171 | IMP |   | F | plasma membrane/prospore membrane sodium ion/proton antiporter Nhe1/Sod2 | sod2
PomBase | SPBC15D4.15 | pho2 |   | GO:0016791 | phosphatase activity | PMID:1645660 | IDA |   | F | 4-phosphoerythronate phosphastase/2-phosphoglycolate phophatase, involved in detoxification of glycolytic by-products
PomBase | SPCC320.14 | sry1 |   | GO:0030378 | serine racemase activity | PMID:24314397 | IDA |   | F | serine racemase Sry1 | SPCC330.15c
~PomBase | SPBC1683.07 | mal1 |   | GO:0032450 | maltose alpha-glucosidase activity | PMID:18556189 | IDA |   | F | maltase alpha-glucosidase Mal1~
~PomBase | SPBC1683.07 | mal1 |   | GO:0032450 | maltose alpha-glucosidase activity | PMID:18556189 | IDA |   | F | maltase alpha-glucosidase Mal1~
~PomBase | SPBC1683.07 | mal1 |   | GO:0032450 | maltose alpha-glucosidase activity | PMID:18556189 | IDA |   | F | maltase alpha-glucosidase Mal1~
~PomBase | SPBC1683.07 | mal1 |   | GO:0032450 | maltose alpha-glucosidase activity | PMID:18556189 | IDA |   | F | maltase alpha-glucosidase Mal1~
~PomBase | SPBC1683.07 | mal1 |   | GO:0032450 | maltose alpha-glucosidase activity | PMID:18556189 | IDA |   | F | maltase alpha-glucosidase Mal1~
~PomBase | SPBC1683.07 | mal1 |   | GO:0032450 | maltose alpha-glucosidase activity | PMID:18556189 | IDA |   | F | maltase alpha-glucosidase Mal1~
~PomBase | SPBC1683.07 | mal1 |   | GO:0032450 | maltose alpha-glucosidase activity | PMID:18556189 | IDA |   | F | maltase alpha-glucosidase Mal1~
~PomBase | SPBC1683.07 | mal1 |   | GO:0032450 | maltose alpha-glucosidase activity | PMID:18556189 | IDA |   | F | maltase alpha-glucosidase Mal1~
~PomBase | SPBC1683.07 | mal1 |   | GO:0032450 | maltose alpha-glucosidase activity | PMID:18556189 | IDA |   | F | maltase alpha-glucosidase Mal1~
PomBase | SPAPB24D3.10c | agl1 |   | GO:0032450 | maltose alpha-glucosidase activity | PMID:11298744 | IDA |   | F | maltose alpha-glucosidase Agl1 | agl
PomBase | SPAC29B12.10c | pgt1 |   | GO:0034634 | glutathione transmembrane transporter activity | PMID:18662319 | IDA |   | F | plasma membrane glutathione transmembrane transporter Pgt1 | opt1
PomBase | SPAC29B12.10c | pgt1 |   | GO:0034634 | glutathione transmembrane transporter activity | PMID:18662319 | IDA |   | F | plasma membrane glutathione transmembrane transporter Pgt1 | opt1
PomBase | SPCC1884.02 | nic1 |   | GO:0044750 | high-affinity nickel cation transmembrane transporter activity | PMID:10748059 | IMP |   | F | plasma membrane NiCoT heavy metal ion transmembrane transporter Nic1 | SPCC757.01
PomBase | SPAC8F11.10c | pvg1 |   | GO:0046919 | pyruvyltransferase activity | PMID:23422075 | IDA |   | F | Golgi pyruvyltransferase Pvg1 | SPACUNK4.18
PomBase | SPAC8F11.10c | pvg1 |   | GO:0046919 | pyruvyltransferase activity | PMID:23422075 | IDA |   | F | Golgi pyruvyltransferase Pvg1 | SPACUNK4.18
PomBase | SPAC8F11.10c | pvg1 |   | GO:0046919 | pyruvyltransferase activity | PMID:23422075 | IDA |   | F | Golgi pyruvyltransferase Pvg1 | SPACUNK4.18
PomBase | SPAC8F11.10c | pvg1 |   | GO:0046919 | pyruvyltransferase activity | PMID:23422075 | IDA |   | F | Golgi pyruvyltransferase Pvg1 | SPACUNK4.18
PomBase | SPAC8F11.10c | pvg1 |   | GO:0046919 | pyruvyltransferase activity | PMID:23422075 | IDA |   | F | Golgi pyruvyltransferase Pvg1 | SPACUNK4.18
PomBase | SPBC25D12.04 | suc22 |   | GO:0051063 | CDP reductase activity | PMID:16317005 | IDA |   | F | ribonucleotide reductase small subunit Suc22
PomBase | SPAC1F7.05 | cdc22 |   | GO:0051063 | CDP reductase activity | PMID:16317005 | IDA |   | F | ribonucleoside reductase large subunit Cdc22
PomBase | SPBC2G2.02 | syj1 |   | GO:0052658 | inositol-1,4,5-trisphosphate 5-phosphatase activity | PMID:15316017 | IDA |   | F | inositol-polyphosphate 5-phosphatase, synaptojanin homolog 1
PomBase | SPAC26H5.06 | pot1 |   | GO:0098505 | G-rich strand telomeric DNA binding | PMID:22978652 | IDA |   | F | shelterin complex subunit Pot1
PomBase | SPAC1071.10c | pma1 |   | GO:1901691 | proton binding | PMID:1310980 | IDA |   | F | plasma membrane P-type proton exporting ATPase, P3-type Pma1

**Comment by ValWood** [comment]
inhibited by will be excluded as an allowed extension on MF
If we want to capture the information  of inhibition by a chemical we will need to define another way to do it

part of positive regulation of transcription from RNA polymerase II promoter in response to glucose starvation inhibited by 3',5'-cyclic AMP
--
  | part of positive regulation of transcription from RNA polymerase II promoter in response to glucose starvation inhibited by N-acetyl-L-cysteine
  | part of positive regulation of transcription from RNA polymerase II promoter in response to glucose starvation inhibited by nitric oxide

**Comment by Antonialock** [comment]
maybe a controlled curation note?

**Comment by ValWood** [comment]
It would be good if eventually we could append it to the function section,  However, for now we could use the controlled curation qualifier "misc" ....actually do we display that?

If we use some standard syntax, will be easy to mine later....

**Comment by ValWood** [comment]
SPAC212.08c

 /controlled_curation="term=genome organization, telomeric
FT                   duplication; cv=genome_org; date=19700101"
FT                   /controlled_curation="term=sequence feature, N-terminal
FT                   signal sequence; qualifier=predicted; cv=sequence_feature;
FT                   date=19700101"

appears, but 


FT                   /controlled_curation="term=misc functional group, cell
FT                   surface glycoprotein; cv=m_f_g; date=20100104"


doesn't.

I will open a ticket about that.

You can create a new "sub-type" for these...

**Comment by ValWood** [comment]
I need to open a ticket about the missing CC notes

**Comment by ValWood** [comment]
misc functional group is appearing now...

**Comment by ValWood** [comment]
https://github.com/geneontology/go-annotation/issues/2719

**Comment by ValWood** [comment]
I'll take this one, can chip away

**Comment by Antonialock** [comment]
I wasn't sure what needed to be done :)

**Comment by ValWood** [comment]
That's OK, I thought your time would . be used better on other tasks that I will find hard :)

**Comment by ValWood** [comment]
done!
