### ISSUE TITLE
use of occurs at with CC-SO

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2486]
PomBase | SPBC16D10.04c | enables | GO:0003682 | chromatin binding | PMID:22682245 | ECO:0000314 |   | 20140205 | PomBase | happens_during(GO:0031297),occurs_at(GO:0043596 nuclear replication fork) |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PomBase | SPCC18.06c | enables | GO:0003682 | chromatin binding | PMID:28404620 | ECO:0000269 |   | 20170524 | PomBase | occurs_at(GO:1990421 subtelomeric heterochromatin subtelomeric heterochromatin) |  
PomBase | SPBC11B10.09 | enables | GO:0004693 | cyclin-dependent protein serine/threonine kinase activity | PMID:9303310 | ECO:0000315 |   | 20180530 | PomBase | has_direct_input(PomBase:SPBC32F12.09),occurs_at(GO:0000307  CC:cyclin-dependent protein kinase holoenzyme  complex),part_of(GO:1900087) |  
PomBase | SPBC32F12.09 | enables | GO:0004861 | cyclin-dependent protein serine/threonine kinase inhibitor activity | PMID:9303310 | ECO:0000314 |   | 20180412 | PomBase | happens_during(GO:0000080),has_regulation_target(PomBase:SPBC582.03),occurs_at(GO:0000307  CC:cyclin-dependent protein kinase holoenzyme  complex),part_of(GO:0031647),part_of(GO:0045930) |  
PomBase | SPBC428.08c | enables | GO:0046974 | histone methyltransferase activity (H3-K9 specific) | PMID:11283354 | ECO:0000314 |   | 20190303 | PomBase | occurs_at(GO:0031934 CC: mating-type region heterochromatin),part_of(GO:0030466) |  
PomBase | SPAC17G8.12 | enables | GO:0005546 | phosphatidylinositol-4,5-bisphosphate binding | PMID:28765280 | ECO:0000304 |   | 20170814 | PomBase | occurs_at(GO:0005886 CC: plasma membrane),part_of(GO:0090522) |  
PomBase | SPBC106.20 | enables | GO:0005546 | phosphatidylinositol-4,5-bisphosphate binding | PMID:28765280 | ECO:0000304 |   | 20170814 | PomBase | occurs_at(GO:0005886 CC: plasma membrane),part_of(GO:0090522) |  
PomBase | SPBC11B10.09 | enables | GO:0004674 | protein serine/threonine kinase activity | PMID:26804917 | ECO:0000314 |   | 20171215 | PomBase | has_direct_input(PomBase:SPBC16G5.15c),occurs_at(GO:0000307  CC:cyclin-dependent protein kinase holoenzyme  complex),part_of(GO:0051446),part_of(GO:1903026) |  
PomBase | SPAC57A10.02 | enables | GO:0004674 | protein serine/threonine kinase activity | PMID:29514920 | ECO:0000269 |   | 20180627 | PomBase | has_direct_input(PomBase:SPCC18B5.03),occurs_at(GO:0071341 CC:medial cortical node CC:medial cortical node),part_of(GO:0120047) |  
PomBase | SPAC644.06c | enables | GO:0004674 | protein serine/threonine kinase activity | PMID:29514920 | ECO:0000269 |   | 20180627 | PomBase | has_direct_input(PomBase:SPCC18B5.03),occurs_at(GO:0071341 CC:medial cortical node CC:medial cortical node) |  
PomBase | SPAC12G12.05c | enables | GO:0016251 | RNA polymerase II general transcription initiation factor activity | GO_REF:0000024 | ECO:0000266 | SGD:S000004849 | 20180604 | PomBase | occurs_at(GO:0005669 transcription factor TFIID complex),part_of(GO:0006367) |  
PomBase | SPBC13G1.13 | enables | GO:0016251 | RNA polymerase II general transcription initiation factor activity | GO_REF:0000024 | ECO:0000266 | SGD:S000006043 | 20180608 | PomBase | occurs_at(GO:0005675 CC: transcription factor TFIIH holo complex),part_of(GO:0006367) |  
PomBase | SPBC19F8.07 | enables | GO:0016251 | RNA polymerase II general transcription initiation factor activity | GO_REF:0000024 | ECO:0000305 | GO:0005675 CC: transcription factor TFIIH holo complex | 20180608 | PomBase | occurs_at(GO:0005675 CC: transcription factor TFIIH holo complex),part_of(GO:0006367) |  
PomBase | SPBC30B4.07c | enables | GO:0016251 | RNA polymerase II general transcription initiation factor activity | GO_REF:0000024 | ECO:0000266 | SGD:S000006260 | 20180608 | PomBase | occurs_at(GO:0005675 CC: transcription factor TFIIH holo complex),part_of(GO:0006367) |  
PomBase | SPBC776.18c | enables | GO:0016251 | RNA polymerase II general transcription initiation factor activity | GO_REF:0000024 | ECO:0000305 | GO:0070985 CC:transcription factor TFIIK complex | 20180608 | PomBase | occurs_at(GO:0070985 CC:transcription factor TFIIK complex),part_of(GO:0006367) |  
PomBase | SPAC22H12.02 | enables | GO:0016251 | RNA polymerase II general transcription initiation factor activity | PMID:15616156 | ECO:0000305 | GO:0005669 transcription factor TFIID complex | 20180608 | PomBase | occurs_at(GO:0005669 transcription factor TFIID complex),part_of(GO:0006367) |

**Comment by ValWood** [comment]
GO has questioned the use of occurs at SO:xxx why not has input
I think this is because we  use this term for  chromatin IP.
However this raised the issue of why there were binding terms.
I actually think most of these look OK

@pgaudet can you remind me why these are queried?

**Comment by ValWood** [comment]
this one is odd though:

PomBase | SPAC22H12.02 | enables | GO:0016251 | RNA polymerase II general transcription initiation factor activity | PMID:15616156 | ECO:0000305 | GO:0005669 transcription factor TFIID complex | 20180608 | PomBase | occurs_at(GO:0005669 transcription factor TFIID complex),part_of(GO:0006367)

**Comment by ValWood** [comment]
and this one:
PomBase | SPBC776.18c | enables | GO:0016251 | RNA polymerase II general transcription initiation factor activity | GO_REF:0000024 | ECO:0000305 | GO:0070985 CC:transcription factor TFIIK complex | 20180608 | PomBase | occurs_at(GO:0070985 CC:transcription factor TFIIK complex),part_of(GO:0006367)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by mah11** [comment]
1. The annotations in the summary above are all from the occurs_at(GO) tab in the spreadsheet (https://docs.google.com/spreadsheets/d/1LMsw75fwfKBi5H-BFt3opKVV1VuEcT7HUE34bHtOSq4/edit#gid=715469260). They fall into two groups:

- Annotations where the "main" GO term is an activity (all but one are TF activities; the exception is a kinase), and the occurs_at entry is a complex (again, all but one are TFs). These don't make sense to me - I don't understand what the occurs_at extension is supposed to add. If it's intended to say the gene product has X activity when it's part of a Y complex, occurs_at and has_input are both wrong, but we should ask GO how they do want it done.

- Ones that look fine, and has_input would not do instead. They're either binding terms or kinase activity terms, for which the input is what's bound (chromatin or an inositol phosphate), and I don't see a better way to say where it happens in an extension. I also don't happen to know how it would be done in a GO-CAM either.

For chromatin binding, the input is either DNA or one or more proteins, but if we could tell which, we wouldn't have to use the chromatin binding term in the first place. See below on DNA binding ...



2. I also looked at the occurs_at(SO) tab. The vast majority of our annotations there are DNA binding, and should use occurs_at.

For DNA binding, the input is DNA. An occurs_at(SO) extension identifies where (i.e. at which sequence feature(s)) a gene product binds. Using MSO would not help, because the molecule is still the entire piece of DNA in a chromosome, and we'd still need the SO term to specify where along that huge DNA molecule the binding happens.

There are just a handful that could be changed to has_input + an MSO term, plus a few others that look a bit odd for different reasons.

I'll put my sorted lists in follow-up comments.

**Comment by mah11** [comment]
OK occurs_at(GO):

    SPBC16D10.04c   GO:0003682      chromatin binding       PMID:22682245   ECO:0000314     happens_during(GO:0031297),occurs_at(GO:0043596 nuclear replication fork)
    SPCC18.06c      GO:0003682      chromatin binding       PMID:28404620   ECO:0000269     occurs_at(GO:1990421 subtelomeric heterochromatin subtelomeric heterochromatin)
    SPBC32F12.09    GO:0004861      cyclin-dependent protein serine/threonine kinase inhibitor activity     PMID:9303310    ECO:0000314     happens_during(GO:0000080),has_regulation_target(PomBase:SPBC582.03),occurs_at(GO:0000307 CC:cyclin-dependent protein kinase holoenzyme complex),part_of(GO:0031647),part_of(GO:0045930)
    SPBC428.08c     GO:0046974      histone methyltransferase activity (H3-K9 specific)     PMID:11283354   ECO:0000314     occurs_at(GO:0031934 CC: mating-type region heterochromatin),part_of(GO:0030466)    
    SPAC17G8.12     GO:0005546      phosphatidylinositol-4,5-bisphosphate binding   PMID:28765280   ECO:0000304     occurs_at(GO:0005886 CC: plasma membrane),part_of(GO:0090522)
    SPBC106.20      GO:0005546      phosphatidylinositol-4,5-bisphosphate binding   PMID:28765280   ECO:0000304     occurs_at(GO:0005886 CC: plasma membrane),part_of(GO:0090522)
    SPAC57A10.02    GO:0004674      protein serine/threonine kinase activity        PMID:29514920   ECO:0000269     has_direct_input(PomBase:SPCC18B5.03),occurs_at(GO:0071341 CC:medial cortical node CC:medial cortical node),part_of(GO:0120047)
    SPAC644.06c     GO:0004674      protein serine/threonine kinase activity        PMID:29514920   ECO:0000269     has_direct_input(PomBase:SPCC18B5.03),occurs_at(GO:0071341 CC:medial cortical node CC:medial cortical node)

**Comment by mah11** [comment]
occurs_at(GO) to change once they recommend how:

    SPBC11B10.09    GO:0004693      cyclin-dependent protein serine/threonine kinase activity       PMID:9303310    ECO:0000315                     20180530        has_direct_input(PomBase:SPBC32F12.09),occurs_at(GO:0000307 CC:cyclin-dependent protein kinase holoenzyme complex),part_of(GO:1900087)
    SPBC11B10.09    GO:0004674      protein serine/threonine kinase activity        PMID:26804917   ECO:0000314     has_direct_input(PomBase:SPBC16G5.15c),occurs_at(GO:0000307 CC:cyclin-dependent protein kinase holoenzyme complex),part_of(GO:0051446),part_of(GO:1903026)
    SPAC12G12.05c   GO:0016251      RNA polymerase II general transcription initiation factor activity      GO_REF:0000024  ECO:0000266     occurs_at(GO:0005669 transcription factor TFIID complex),part_of(GO:0006367)
    SPBC13G1.13     GO:0016251      RNA polymerase II general transcription initiation factor activity      GO_REF:0000024  ECO:0000266     occurs_at(GO:0005675 CC: transcription factor TFIIH holo complex),part_of(GO:0006367)
    SPBC19F8.07     GO:0016251      RNA polymerase II general transcription initiation factor activity      GO_REF:0000024  ECO:0000305     occurs_at(GO:0005675 CC: transcription factor TFIIH holo complex),part_of(GO:0006367)
    SPBC30B4.07c    GO:0016251      RNA polymerase II general transcription initiation factor activity      GO_REF:0000024  ECO:0000266     occurs_at(GO:0005675 CC: transcription factor TFIIH holo complex),part_of(GO:0006367)
    SPBC776.18c     GO:0016251      RNA polymerase II general transcription initiation factor activity      GO_REF:0000024  ECO:0000305     occurs_at(GO:0070985 CC:transcription factor TFIIK complex),part_of(GO:0006367)
    SPAC22H12.02    GO:0016251      RNA polymerase II general transcription initiation factor activity      PMID:15616156   ECO:0000305     occurs_at(GO:0005669 transcription factor TFIID complex),part_of(GO:0006367)

**Comment by mah11** [comment]
occurs_at(SO) to change to has_input(MSO):

    SPBC29A10.09c GO:0000175      3'-5'-exoribonuclease activity  PMID:24095277   ECO:0000314     occurs_at(SO:0001905)
    SPBC29A10.09c GO:0000175      3'-5'-exoribonuclease activity  PMID:24095277   ECO:0000314     occurs_at(SO:0000871)
    SPBC119.11c   GO:0004525      ribonuclease III activity       PMID:9326493    ECO:0000314     occurs_at(SO:0000209)
    SPCC736.11    GO:0003723      RNA binding     PMID:24095277   ECO:0000314     occurs_at(SO:0000646)
    SPCC736.12c   GO:0003723      RNA binding     PMID:26670050   ECO:0000353     occurs_at(SO:0001877)
    SPCC736.11    GO:0003723      RNA binding     PMID:28541282   ECO:0000314     occurs_at(SO:0001905)
    SPAC20G8.09c  GO:1990883      rRNA cytidine N-acetyltransferase activity      PMID:25402480   ECO:0000315     occurs_at(SO:0000407)

**Comment by mah11** [comment]
other queries from occurs_at(SO) list:
 - SPBC1718.07c GO:0035925      mRNA 3'-UTR AU-rich region binding      PMID:18042546   ECO:0000353     occurs_at(SO:0001180) - extension is redundant with term
 - SPAC1250.04c GO:0032132      O6-alkylguanine-DNA binding     PMID:23112169   ECO:0000314     occurs_at(SO:0000305) - redundant
 - SPCC736.12c  GO:0097157      pre-mRNA intronic binding       PMID:26670050   ECO:0000353     occurs_at(SO:0000188) - redundant
 - SPCC736.12c  GO:0097157      pre-mRNA intronic binding       PMID:26670050   ECO:0000353     occurs_at(SO:0000188) - redundant
 - SPBC1198.11c GO:0110035      rDNA spacer replication fork barrier binding, bending   PMID:27035982   ECO:0000314     occurs_at(SO:0001860) - redundant
 - SPBC1711.17  GO:0003723      RNA binding     PMID:28231281   ECO:0000314     occurs_at(SO:0001898) - wrong SO term?
 - SPAC222.09   GO:0003723      RNA binding     PMID:28367989   ECO:0000314     occurs_at(SO:0002213),part_of(GO:0030846) - wrong SO term?
 - SPAC222.09   GO:0003723      RNA binding     PMID:28367989   ECO:0000353     occurs_at(SO:0002213),part_of(GO:0030846) - wrong SO term?
 - SPBC336.09c  GO:0001164      RNA polymerase I CORE element sequence-specific DNA binding     PMID:25410910   ECO:0000314     occurs_at(SO:0001848),part_of(GO:0060261) - check term/extension combo makes sense; if so, it's OK

**Comment by ValWood** [comment]
re

SPAC12G12.05c   GO:0016251      RNA polymerase II general transcription initiation factor activity      GO_REF:0000024  ECO:0000266     occurs_at(GO:0005669 transcription factor TFIID complex),part_of(GO:0006367)

I agree these can go.

**Comment by ValWood** [comment]
The 
SPBC11B10.09    GO:0004693      cyclin-dependent protein serine/threonine kinase activity       PMID:9303310    ECO:0000315                     20180530        has_direct_input(PomBase:SPBC32F12.09),occurs_at(GO:0000307 CC:cyclin-dependent protein kinase holoenzyme complex),part_of(GO:1900087)
SPBC11B10.09    GO:0004674      protein serine/threonine kinase activity        PMID:26804917   ECO:0000314     has_direct_input(PomBase:SPBC16G5.15c),occurs_at(GO:0000307 CC:cyclin-dependent protein kinase holoenzyme complex),part_of(GO:0051446),part_of(GO:1903026)

ones can go to. This was a placeholder for
https://github.com/pombase/curation/issues/2022

**Comment by mah11** [comment]
GO folks have voted me down, and will insist on has_input(SO). It looks wrong, but oh well.

**Comment by mah11** [comment]
Actually, if they're going to allow occurs_in(SO) maybe we should use that. "In" is the wrong preposition, but it would let us put the same relation for any GO term/SO extension combination instead of having to configure some for has_input and others for occurs_in.

@ValWood @Antonialock thoughts?

**Comment by ValWood** [comment]
I think whichever is easiest.
If it annoys us, we can always add different display labels.

For "happens during" I think the readibility of the compound terms was much better before:
https://www.pombase.org/gene/SPAC24B11.06c
especially if there is more than one involved in, although we are not particularly consistent with  using happens_during vs part_of...

**Comment by mah11** [comment]
yeah, I'm going to have a look at configurations in a bit ... that's gonna be "fun"

**Comment by mah11** [comment]
everything here is deleted, fixed, or will be automagically converted to what GO wants to see
