### ISSUE TITLE
disease associations in tRNA modifiers

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2490]
For example, yeast TAD2 and TAD3 are required for
inosine modification of the wobble nucleotide A34 and are essential [10], and a mutation in the
corresponding human ADAT3 gene is associated with intellectual disability and strabismus

**Comment by ValWood** [comment]
. Similarly, yeast pus3Δ mutants have growth defects due to lack of pseudouridine (C) at
U38 and U39 and are temperature sensitive due to tRNAGln(UUG) [18], and a mutation in the
corresponding human PUS3 gene is associated with syndromic intellectual disability and
reduced pseudouridine [1

**Comment by Antonialock** [comment]
added pending mondo switch
