### ISSUE TITLE
rpb1 disease association

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2493]
| De Novo Heterozygous POLR2A Variants Cause a Neurodevelopmental Syndrome with Profound Infantile-Onset Hypotonia.
-- | --
  | Am J Hum Genet. 2019 Jul 20;. [Epub ahead of print]
  | PMID: 31353023

**Comment by Antonialock** [comment]
Good spot..not even in omim yet

**Comment by Antonialock** [comment]
in spreadsheet...I asked DO when they were doing their next update but havent heard back
