### ISSUE TITLE
targets of protein complex subunits which do not have the activity , or indirectly upstream in processes (i.e. cannot connect as substrate)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2498]
https://github.com/geneontology/go-annotation/issues/2577

How should we handle these?

**Comment by ValWood** [comment]
related issues
phosphatase activity
https://github.com/pombase/curation/issues/1513

https://github.com/pombase/curation/issues/2345
https://github.com/pombase/curation/issues/2022
https://github.com/pombase/curation/issues/487

**Comment by ValWood** [comment]
@mah11  do I remember you making a model to see what was exported in this situation?
If not I will try to knock one together.

**Comment by mah11** [comment]
Not exactly. The closest thing I've done is this one, which covers the "regulation of x's kinase activity" part of the story:

http://noctua.geneontology.org/editor/graph/gomodel:5b318d0900000714

This doesn't address anything about the activities of non-catalytic subunits of a complex, let alone how to describe a "substrate specificity determinant" role for a subunit.

**Comment by ValWood** [comment]
Discussion
1. We really need complex pages to assign MF substrates too.

2. We can work around and make sure that the catalytic substrate always has the substrate represented, and use the same paper with EXP based on the fact that an experiment exists from which the substrate can be inferred.

**Comment by ValWood** [comment]
Example issues Srw1 https://www.pombase.org/gene/SPAC144.13c

**Comment by ValWood** [comment]
Out of date
