### ISSUE TITLE
happens during response to osmotic stress

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2501]
this is MAPK pathway so should these be "involved in"?

happens_during.tsv:Not a biological phase - review			PomBase	SPAC24B11.06c	sty1		GO:0004707	PMID:18272791	IDA		F	MAP kinase Sty1	phh1|spc1	protein	taxon:4896	20171013	PomBase	directly_positively_regulates(PomBase:SPCC1322.08),happens_during(GO:0071470),part_of(GO:0010972)
happens_during.tsv:Not a biological phase - review			PomBase	SPBC29B5.01	atf1		GO:0001228	PMID:10731689	IDA		F	transcription factor, Atf-CREB family Atf1	gad7|sss1|mts1	protein	taxon:4896	20170724	PomBase	happens_during(GO:0071470),has_regulation_target(PomBase:SPCC757.07c)
happens_during.tsv:Not a biological phase - review			PomBase	SPCC1322.08	srk1		GO:0004674	PMID:18272791	IDA		F	MAPK-activated protein kinase Srk1	mkp1	protein	taxon:4896	20170804	PomBase	happens_during(GO:0071470),has_direct_input(PomBase:SPAC24H6.05),part_of(GO:0010972)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC24B11.06c	sty1		GO:0004707	PMID:18272791	IDA		F	MAP kinase Sty1	phh1|spc1	protein	taxon:4896	20171013	PomBase	directly_positively_regulates(PomBase:SPCC1322.08),happens_during(GO:0071470),part_of(GO:0010972)
happens_during.tsv:Not a biological phase - review			PomBase	SPBC29B5.01	atf1		GO:0001228	PMID:10731689	IDA		F	transcription factor, Atf-CREB family Atf1	gad7|sss1|mts1	protein	taxon:4896	20170724	PomBase	happens_during(GO:0071470),has_regulation_target(PomBase:SPCC757.07c)
happens_during.tsv:Not a biological phase - review			PomBase	SPCC1322.08	srk1		GO:0004674	PMID:18272791	IDA		F	MAPK-activated protein kinase Srk1	mkp1	protein	taxon:4896	20170804	PomBase	happens_during(GO:0071470),has_direct_input(PomBase:SPAC24H6.05),part_of(GO:0010972)
Val-Woods-MacBook-Pro:Desktop val$

**Comment by Antonialock** [comment]
bit hard to read but I think that's all
