### ISSUE TITLE
cid1 , this should def be part_of, not happens during

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2502]
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPBC32H8.12c)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPBC3H7.06c)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPCC13B11.01)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPAC140.02)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPAC19D5.03)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPAC23C11.12)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPBC32H8.12c)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPBC3H7.06c)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPCC13B11.01)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPAC140.02)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPAC19D5.03)
happens_during.tsv:Not a biological phase - review			PomBase	SPAC19D5.03	cid1		GO:0050265	PMID:19430462	IMP		F	terminal uridylyltransferase Cid1		protein	taxon:4896	20140207	PomBase	happens_during(GO:0036450),has_direct_input(PomBase:SPAC23C11.12)

**Comment by Antonialock** [comment]
fixed
