### ISSUE TITLE
CBS2 diseases/ Move disease annotation 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2503]
https://www.pombase.org/gene/SPAC1556.08c
this isn't the mitochondrial CBS2 so the disease associations need moving.

**Comment by ValWood** [comment]
Actually the author wants the new gene to be confidential.
Just past the annotations into this ticket, and when we can we will add them to the correct gene with the  ortholog data.

**Comment by Antonialock** [comment]
I removed mitochondrial dis, the other annotations are fine.

the author's gene doesn't have a human homolog, so closing,

**Comment by ValWood** [comment]
maybe mitochondrial disease was ok for this too then?
I see that human ortholog is related to mitochondrial functions?

**Comment by Antonialock** [comment]
I can't find that connection, and I can't see the mitochondrial function on the human ortholog

![Screenshot 2019-08-15 at 09 40 10](https://user-images.githubusercontent.com/12727506/63083493-c24ab980-bf40-11e9-9c16-c385ecbaef5b.png)

**Comment by ValWood** [comment]
OK
