### ISSUE TITLE
orb6 missing substrates

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2510]
To date, the only reported substrates of Orb6 are Gef1 and Sts5, both of which were phosphorylated in vitro by Orb6 in immuno- precipitates of the Orb6 coactivator Mob2 (Das et al., 2015; Nun ̃ ez et al., 2016; Wiley et al., 2003).

**Comment by ValWood** [comment]
Might be out for CC, we got the others up to date.
https://github.com/pombase/curation/issues/1565

**Comment by Antonialock** [comment]
I resent invitation to 26246599 (Das) and  27474797 (Nunez)

Wiley 2003 was done already

**Comment by ValWood** [comment]
After Steve fest/ Kims visit, we will start a community curation push.
...lots of ideas, targetting by gene, area, more tutorials. I think people will do these soon when we focus...

**Comment by ValWood** [comment]
closing, as is assigned and will happen when curated,
