### ISSUE TITLE
expanding drug target inventory

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2519]
Chembl
Inxight https://drugs.ncats.io/
IUPHAR https://www.guidetopharmacology.org/
Drugbank
- little letter icon next to the target:
A - Pharmacologically active = the listed target is confirmed to be related to the clinical effect of the drug
U - Pharmacological Action Unkown = the listed target is not confirmed to be related to the clinical effect of the drug, there might be evidence indicating this but this evidence has not been confirmed.
N - Pharmacologically inactive = the listed target is confirmed to not be related to the clinical effect of the drug. There has been confirmed a binding but it is not related to the clinical effect of the drug.

**Comment by ValWood** [comment]
Added to future doc
