### ISSUE TITLE
disease datasets to prioritise for browser loading

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2521]
https://www.ncbi.nlm.nih.gov/gds/?term=(disease+OR+cancer)+AND+(schizosaccharomyces+pombe%5BOrganism%5D+NOT+saccharomyces+cerevisiae%5BOrganism%5D)

**Comment by Antonialock** [comment]
need to look through list and see what is in there, will move to website tracker once we know what we want

**Comment by ValWood** [comment]
closing this
