### ISSUE TITLE
were these converted recently from IC to ISS?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2524]
WARNING - Violates GO Rule: GORULE:0000016: All IC annotations should include a GO ID in the "With/From" column -- PomBase SPAC3A12.09c ure4 GO:0110147 PMID:24115911 IC UniprotKB:P25178 P urease accessory protein UreD protein taxon:4896 20190712 PomBase
WARNING - Violates GO Rule: GORULE:0000016: All IC annotations should include a GO ID in the "With/From" column -- PomBase SPAC29A4.13 ure6 GO:0110147 PMID:24115911 IC UniprotKB:Q09065 P urease accessory protein UreF protein taxon:4896 20190712 PomBase
WARNING - Violates GO Rule: GORULE:0000016: All IC annotations should include a GO ID in the "With/From" column -- PomBase SPCPB16A4.05c ure7 GO:0110147 PMID:24115911 IC UniprotKB:Q09066 P urease accessory protein UreG protein taxon:4896 20190712 PomBase

**Comment by mah11** [comment]
> were these converted recently from IC to ISS?

No.

The GO pipeline hasn't picked up the file I committed on Monday, in which these are fixed.
