### ISSUE TITLE
remove malacards associatiuon

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2528]
Kim, I want to remove Dravet syndrome from SPCC584.05

The reference is malacards - I went to look in
malacards_data_for_chado.tsv

but I cannot see dravet syndrome in there? Where should I be removing it from?

**Comment by kimrutherford** [comment]
I think it's this one:

```
epileptic encephalopathy, early infantile, 6    epileptic_encephalopathy_early_infantile_6      Epileptic Encephalopathy, Early Infantile, 6    STXBP1  DOID:0060171
```

The DOID matches.

**Comment by Antonialock** [comment]
ok, I'm confused so I added PomBase mappings to the correct terms and removed all the malacards ones to stx1b. 

Just need to check dravet syndrom disappears from sec1

**Comment by Antonialock** [comment]
gone. Also remove RP from CLN3

**Comment by Antonialock** [comment]
sec1 done

Also change RP on CLN3 to retinal degeneration, or similar, need to check for ref

"ecent studies show that CLN3 mutations may also result in a nonsyndromic retinal degeneration whose onset differs considerably from classical Batten disease. "
https://onlinelibrary.wiley.com/doi/epdf/10.1002/mgg3.859

**Comment by Antonialock** [comment]
non syndromic retinal degeneration caused by splicing defect but ortholog has no introns

**Comment by Antonialock** [comment]
CLN3 fixed
