### ISSUE TITLE
 rec27, rec25 and rec8

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2531]
looks like the GO annotation could be improved

Davis L, Rozalén AE, Moreno S, Smith GR, Martin-Castellanos C (2008) Rec25 and Rec27, novel linear-element components, link cohesin to meiotic DNA breakage and recombination. Curr Biol 18:849–854.

the Rec8 cohesin subunit, which is required for loading of the LinE proteins Rec25 and Rec27 (31) (ref above),

**Comment by ValWood** [comment]
I think this is fine.
Cohesin isn't really a "loader" I think these are just phenotypes. Linear elements don't localize properly if cohesion is disturbed.

FYPO:0006164 | decreased protein localization to linear element
-- | --
affecting rec25 | rec8Δbackground: pat1-114/pat1-114; homozygous diploid | Microscopy |   | Davis L et al. (2008)
affecting rec27 | rec8Δbackground: pat1-114/pat1-114; homozygous diploid | Microscopy |   | Davis L et al. (2008)
