### ISSUE TITLE
disease log files

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2532]
https://curation.pombase.org/dumps/latest_build/logs/qualifier_problems.txt
Lots of errors in here. Do you know about them?

number 986 so only 14 away from 1000.
We should definitely announce then if the slim is ready or not...

**Comment by ValWood** [comment]
@Antonialock

**Comment by ValWood** [comment]
and 
https://curation.pombase.org/dumps/latest_build/logs/log.2019-10-17-21-56-08.malacards_data

this is a lot with no DO ID? Is this real. I will write to them properly can you send me a summary of what you are waiting for?

**Comment by ValWood** [comment]
and
https://curation.pombase.org/dumps/latest_build/logs/log.2019-10-17-21-56-08.disease_associations

**Comment by Antonialock** [comment]
done with the mappings.
