### ISSUE TITLE
mitochondrial rna names

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2537]
two ribosomal RNAs (rnl and rns)

**Comment by ValWood** [comment]
nmaes need annotating in the mitochondrial genome.

This might help
PMID: 15811919

**Comment by mah11** [comment]
Could you clarify the task - do features exist? The paper implies that there are two rRNA genes on the mitochondrial chromosome: "The mtDNA of S. pombe (Fig. 1) carries genes for two ribosomal RNAs (rnl, rns) ..."

There are two rRNA features annotated in the contig file, with different names. Are rnl and rns synonyms for these existing genes?

**Comment by ValWood** [comment]
As far as I am aware all of the mitochondrial genome features are annotated.

These names are from the paper above, so I guess they are synonyms of the 2 already annotated RNAs. 

The task is to figure out if these are synonyms and if so, of what.....

**Comment by ValWood** [comment]
I can take this,
PMID: 12527786 
the large and small mitochondrial ribosomal RNAs (rnl and rns),

**Comment by ValWood** [comment]
/product="21S rRNA, rnl"
/gene="21S_rRNA"
/systematic_id="SPRRNA.01"
/primary_name="rnl"
/synonym="21S_rRNA"

/product="15S rRNA, rns"
/gene="15S_rRNA"
/synonym="15S_rRNA"
/systematic_id="SPRRNA.02"
/primary_name="rns"
