### ISSUE TITLE
NPC1 missnig ortholog

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2543]
don't we have this one? Conserved in all other models.

**Comment by ValWood** [comment]
weird- we have  YHR042W/NCr1 (sc orth of NPC1)  as the ortholog of scp1 but that isn't true. 

	SREBP-SCAP complex is not present in S.c. I will remove that.

will have a look at npc1 later...

**Comment by ValWood** [comment]
I don't think we have this...
