### ISSUE TITLE
BER

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2544]
the BER pathway is missing GO terms and annotations

eg
<img width="488" alt="Screenshot 2019-10-31 at 17 03 29" src="https://user-images.githubusercontent.com/12727506/67969107-74208a80-fc00-11e9-9136-2c00893de97a.png">
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC549418/

**Comment by ValWood** [comment]
Which genes? I wouldn't do this as a priority considering all the disease stuff and browser dataset hosting tickets. @mah11  could look at this as part of DNA metabolism.

**Comment by ValWood** [comment]
Although, all of the genes in this figure are annotated to BER?

**Comment by Antonialock** [comment]
ah I was looking at the ontology, there are specific terms for some steps of BER but not others
