### ISSUE TITLE
png1 and png2

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2546]
png1 and png2 are annotated to ubiquitin ligase activity & protein modification by small protein conjugation or removal? 

but they are part of histone deacetylase complex?

**Comment by ValWood** [comment]
they are  ubiquitin ligases (	Zinc finger, FYVE/PHD-type)

**Comment by Antonialock** [comment]
That's not what the Interpro description says?
"The FYVE zinc finger domain is conserved from yeast to man, and is named after four proteins that it has been found in: Fab1, YOTB/ZK632.12, Vac1, and EEA1. It functions in the membrane recruitment of cytosolic proteins by binding to phosphatidylinositol 3-phosphate (PI3P), which is found mainly on endosomes [7, 5]."

**Comment by ValWood** [comment]
hmm, they used to be thought to be ub ligases...

but
https://www.ncbi.nlm.nih.gov/pubmed/12791292

**Comment by ValWood** [comment]
but maybe thats because the ub-ligase activity requires histine binding
https://www.cell.com/molecular-cell/pdf/S1097-2765(11)00387-X.pdf

**Comment by ValWood** [comment]
http://www.jbc.org/content/282/25/18397.full

**Comment by ValWood** [comment]
https://en.wikipedia.org/wiki/Ubiquitin_ligase
Ubiquitin ligase families
Humans have an estimated 500-1000 E3 ligases, which impart substrate specificity onto the E1 and E2.[8] The E3 ligases are classified into four families: HECT, RING-finger, U-box, and PHD-finger.[8] The RING-finger E3 ligases are the largest family and contain ligases such as the anaphase-promoting complex (APC) and the SCF complex (Skp1-Cullin-F-box protein complex). SCF complexes consist of four proteins: Rbx1, Cul1, Skp1, which are invariant among SCF complexes, and an F-box protein, which varies. Around 70 human F-box proteins have been identified.[9] F-box proteins contain an F-box, which binds the rest of the SCF complex, and a substrate binding domain, which gives the E3 its substrate specificity.[8]

**Comment by ValWood** [comment]
I remioved ubiquitin ligase from PHD fingers≥ 2 are  still ubiquiting ligases, but via another domain
