### ISSUE TITLE
these look like they should be diploids?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2553]
PMID:10521402

wee1	wee1-50(aaG850E)[Not assayed] / wee1-50(aaG850E)[Not assayed]	0	
	rad3	        rad3-136(unknown)[Not assayed] / rad3+[Wild type product level]	0

**Comment by mah11** [comment]
Those genotypes do appear in the single-locus "Diploid/multiploid genotype" table. Reopen if there's anything to do here.
