### ISSUE TITLE
exists_during "conjugation"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2558]
Can any of these be "involved in"?

If not  do we need a "phase" term corresponding to "conjugation stage"?

 

- [x] SPAC458.04c.1   | cell cortex [exists_during] karyogamy involved in conjugation with cellular fusion

 - [x] SPBC1347.12.1   | cell cortex of cell tip [exists_during] karyogamy involved in conjugation with cellular fusion
- [x]  SPCC645.07.1    | cell tip [exists_during] conjugation with cellular fusion
- [x]  SPAC27D7.13c.1  | cortical microtubule plus-end [exists_during] cell morphogenesis involved in conjugation with cellular fusion
 - [x] SPAC27D7.13c.1  | cortical microtubule plus-end [exists_during] karyogamy involved in conjugation with cellular fusion
 - [x] SPAC458.04c.1   | cortical microtubule plus-end [exists_during] karyogamy involved in conjugation with cellular fusion
- [x]  SPBC23G7.17c.1  | cytoplasm [exists_during] conjugation with cellular fusion
 - [x] SPCC1322.08.1   | cytoplasm [exists_during] karyogamy involved in conjugation with cellular fusion
- [x]  SPAC27D7.13c.1  | cytoplasmic microtubule [exists_during] cell morphogenesis involved in conjugation with cellular fusion
- [x]  SPBC646.12c.1   | mating projection [exists_during] cell morphogenesis involved in conjugation with cellular fusion
- [x]  SPAC20G4.02c.1  | mating projection [exists_during] conjugation with cellular fusion
- [x]  SPBC19F8.01c.1  | mating projection septin ring [exists_during] conjugation with cellular fusion
- [x]  SPCC188.12.1    | mating projection septin ring [exists_during] conjugation with cellular fusion
- [x]  SPAC24C9.15c.1  | mating projection septin ring [exists_during] conjugation with cellular fusion
- [x]  SPAC821.06.1    | mating projection septin ring [exists_during] conjugation with cellular fusion
- [ ]  SPBC32F12.04.1  | mating projection tip [exists_during] agglutination involved in conjugation with cellular fusion
- [ ]  SPAC16E8.09.1   | mating projection tip [exists_during] cell morphogenesis involved in conjugation with cellular fusion
 - [ ] SPBC19G7.05c.1  | mating projection tip [exists_during] cell morphogenesis involved in conjugation with cellular fusion
 - [ ] SPAC22H10.07.1  | mating projection tip [exists_during] cell morphogenesis involved in conjugation with cellular fusion
 - [ ] SPAC110.03.1    | mating projection tip [exists_during] cell morphogenesis involved in conjugation with cellular fusion
 - [ ] SPAC29A4.05.1   | mating projection tip [exists_during] conjugation with cellular fusion
 - [ ] SPAC3A12.14.1   | mating projection tip [exists_during] karyogamy involved in conjugation with cellular fusion
- [ ]  SPBC11B10.09.1  | meiotic spindle pole body [exists_during] karyogamy involved in conjugation with cellular fusion
- [ ]  SPAC458.04c.1   | meiotic spindle pole body [exists_during] karyogamy involved in conjugation with cellular fusion
- [ ]  SPAC16C9.07.1   | mitochondrion [exists_during] conjugation with cellular fusion
 - [ ] SPAC3H8.10.1    | nucleus [exists_during] conjugation with cellular fusion
- [x]  SPMTR.02.1      | nucleus [exists_during] conjugation with cellular fusion
- [ ]  SPAC27D7.03c.1  | nucleus [exists_during] conjugation with cellular fusion
- [ ]  SPBC11B10.09.1  | nucleus [exists_during] karyogamy involved in conjugation with cellular fusion
 - [ ] SPBC23G7.17c.1  | Pi Mi complex [exists_during] conjugation with cellular fusion
 - [x] SPMTR.02.1      | Pi Mi complex [exists_during] conjugation with cellular fusion
 - [ ] SPBC23G7.17c.1 | nucleus [exists_during] cytogamy
 - [ ] SPCC16A11.17.1 | nuclear chromatin [exists_during] mitotic cell cycle G1 arrest in response to pheromone

**Comment by ValWood** [comment]
SPBC23G7.17c.1  | nucleus [exists_during] cytogamy

**Comment by ValWood** [comment]
SPAC8C9.03.1    | cytoplasm [exists_during] karyogamy
 SPBC106.10.1    | cytoplasm [exists_during] karyogamy
 SPAC1093.06c.1  | meiotic spindle astral microtubule [exists_during] karyogamy

**Comment by ValWood** [comment]
SPCC16A11.17.1 | nuclear chromatin [exists_during] mitotic cell cycle G1 arrest in response to pheromone

**Comment by Antonialock** [comment]
I don't think "involved in" is allowed with cellular components? exists_during is the correct relationship?

**Comment by ValWood** [comment]
Sorry, I got that wrong,

https://github.com/geneontology/go-annotation/issues/2677

The suggestion is to 
The suggestion is to change the annotations from
CC exists_during BP
to BP occurs_in CC

**Comment by mah11** [comment]
yeah, I still don't get why they suggest that change - they don't mean the same thing (as some curators point out on the GO ticket)

**Comment by ValWood** [comment]
If not started hang fire with this one. I want to ask GO more questions...

**Comment by ValWood** [comment]
I'll steal this one.

**Comment by ValWood** [comment]
will start again from
#2535
