### ISSUE TITLE
exists_during replication related

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2570]
could these be involved in, or during mitotic S-phase?

SPBC1347.10.1   | nuclear chromatin [coincident_with] origin_of_replication [exists_during] mitotic DNA replication initiation
 SPAC23C4.18c.1  | nuclear chromatin [coincident_with] origin_of_replication [exists_during] mitotic DNA replication initiation
 SPCC16A11.17.1  | nuclear chromatin [coincident_with] origin_of_replication [exists_during] mitotic DNA replication initiation
 SPBC216.05.1    | nuclear chromatin [exists_during] mitotic DNA replication checkpoint
 SPBP8B7.14c.1   | nuclear chromatin [exists_during] mitotic DNA replication initiation [coincident_with] origin_of_replication
 SPBC211.04c.1   | nuclear chromatin [exists_during] premeiotic DNA replication
 SPBC4.04c.1     | nuclear chromatin [exists_during] premeiotic DNA replication
 SPCC16A11.17.1  | nuclear chromatin [exists_during] premeiotic DNA replication
 SPBC216.05.1    | nuclear chromatin [part_of] nuclear replication fork [exists_during] replication fork processing
 SPAC664.07c.1   | nuclear chromatin [part_of] nuclear replication fork [exists_during] replication fork processing
 SPCC16A11.17.1  | nuclear chromatin [part_of] nuclear replication fork [exists_during] replication fork processing
 SPAC14C4.13.1   | nuclear chromatin [part_of] nuclear replication fork [exists_during] replication fork processing
 SPBC14C8.07c.1  | nucleus [exists_during] premeiotic DNA replication

**Comment by mah11** [comment]
> could these be involved in

Using involved in to extend a cellular component annotation feels weird somehow (as well as overinterpreting results).

> during mitotic S phase

I hope it's obvious why that wouldn't work at all for the  [exists_during] premeiotic DNA replication ones ;)

For the ones that are actually mitotic, using mitotic S phase would lose so much specificity that there's not much point keeping the extension.

**Comment by mah11** [comment]
done

**Comment by ValWood** [comment]
Note that, if we think these are useful, and the changes don't make sense, we could make an argument for keeping the relationship. We have over 1000 annotations  after all and it is a 
the relation that was used in the paper:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4039540/figure/F2/
