### ISSUE TITLE
Tay's phospho sites

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2578]
from
https://github.com/pombase/pombase-chado/issues/726

see helpdesk ticket
Re: Confirmation of curation session for PMID:30726745

https://www.pombase.org/documentation/modification-data-bulk-upload-format

Ye Dee Tay's phosphorylation sites 

orb6 phosphorylation sites (proteomics data)
like the Mathew Swaffer dataset?
https://www.pombase.org/reference/PMID:27984725

we can include all as modifications "affected by ' orb6

**Comment by Antonialock** [comment]
done pending loading works, will check tomorrow.
