### ISSUE TITLE
regulates_activity_of solution

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2579]
fix as per
https://github.com/geneontology/go-annotation/issues/2613#event-2577891127

- [x] Pending |   |   |   | PomBase | SPBC32F12.09 | rum1
- [x] Pending |   |   |   | PomBase | SPBC32F12.09 | rum1
- [x] Pending |   |   |   | PomBase | SPBC19F5.01c | puc1
- [x] Pending |   |   |   | PomBase | SPAC57A7.04c | pabp
- [x] Pending |   |   |   | PomBase | SPAC57A7.04c | pabp

Pending |   |   |   | PomBase | SPAC1F5.04c | cdc12
Pending |   |   |   | PomBase | SPAC20G4.06c | adf1
Pending |   |   |   | PomBase | SPAC4A8.15c | cdc3
Pending |   |   |   | PomBase | SPBC1778.06c | fim1
Pending |   |   |   | PomBase | SPBC1778.06c | fim1

Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8

**Comment by ValWood** [comment]
Hi @mah11  I'll assign to you. I think these are mainly yours so can you check if has_input is OK (or would some be better as  a MF (binding inhibitor or suchlike?)

**Comment by ValWood** [comment]
is duplicate https://github.com/pombase/curation/issues/2509

**Comment by mah11** [comment]
> or would some be better as a MF (binding inhibitor or suchlike?)

If an MF would work I would have used one in the first place.

**Comment by mah11** [comment]
changed to has_input ... not very satisfying, due to loss of specificity & nuance, but if GO wants to lump everything that's their lookout.

**Comment by ValWood** [comment]
But "competitive inhibition" seems that it is a molecular function, not a process?

@pgaudet this has cropped up quite a lot. It seems that we need a way to capture inhibition of binding in GO? currently described as "negative regulation of actin filament binding"

**Comment by mah11** [comment]
deleting comment from wrong ticket, and closing

**Comment by ValWood** [comment]
This is the ticket I meant to put the comment in?

**Comment by ValWood** [comment]
Replacing the comment

But "competitive inhibition" seems that it is a molecular function, not a process?

@pgaudet this has cropped up quite a lot. It seems that we need a way to capture inhibition of binding in GO? currently described as "negative regulation of actin filament binding"

**Comment by pgaudet** [comment]
Hi @ValWood 

Where was 'competitive inhibition' mentioned?

**Comment by pgaudet** [comment]
Isn't 'competitive inhibition of binding' the same as sequestering ?

**Comment by ValWood** [comment]
For example in this paper:
https://www.pombase.org/reference/PMID:20705471
https://linkinghub.elsevier.com/retrieve/pii/S0960982210009280

microfilament motor is actin-dependent
cdc8 binds actin and displaces myo1 (this seems to be  competitive inhibition with actin as the competing substrate)

**Comment by ValWood** [comment]
Sequestering seems odd in some contexts though. This would be actin filament sequestering?
I will see if this fits other examples I came across though.

I guess this example can only be captured by a full GO -cam where  cdc8 "sequesters" actin -> negatively  regulates myo1(actin binding)

**Comment by mah11** [comment]
This stuff about binding, sequestering, etc, is all still on the wrong ticket. Please move it.

**Comment by ValWood** [comment]
So for these, we now have "has_input" which just looks weird for our users on gene pages.

It would be better if we kept as "has_regulation_target" and exported has_input to GO...

**Comment by ValWood** [comment]
All the stuff about  a longer term solution to  this type of "regulation of MF" -> "Mf regulator"
is here:
https://github.com/pombase/curation/issues/2597

**Comment by pgaudet** [comment]
It seems like 'actin sequestering' is being used in the scientific literature, for eg: 
https://www.tebu-bio.com/blog/2015/02/23/capping-bundling-sequestering-the-role-of-actin-binding-proteins/

https://www.nature.com/articles/s41598-019-42977-2


@mah11 please move this comment to the correct ticket ! 

Thanks, Pascale

**Comment by mah11** [comment]
@pgaudet Val linked a new PomBase ticket in the comment above yours, but it really looks like most of it would fit nicely on the GO ontology tracker.

**Comment by mah11** [comment]
> So for these, we now have "has_input" which just looks weird for our users on gene pages.
> 
> It would be better if we kept as "has_regulation_target" and exported has_input to GO...

changed (again; would be good not to have to redo any more)
