### ISSUE TITLE
annotations seem odd lap2 and ape2

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2590]
lap2 and ape2 are peptidases?

cytoplasm to vacuole transport by the NVT pathway

  | ape2 transports lap2
  | lap2 transports ape2

**Comment by mah11** [comment]
note to self: PMID:26365378

**Comment by mah11** [comment]
Li-Lin made both annotations, and I can see why he did: phenotypes indicate that both Lap2 and Ape2 contribute to each other's localization:

> Interestingly, the vacuolar localizations of Lap2 and Ape2 were mutually dependent (Figures 1E, 1F, S1C, and S1D). In addition, the extent of vacuolar processing of Nbr1-mCherry was significantly decreased in the absence of either Lap2 or Ape2 (Figures 1G and 1H). Thus, similar to the way S. cerevisiae Ape1 acts in the Cvt pathway, Lap2 and Ape2 are more than mere cargos in their vacuolar targeting process. These results indicate that Nbr1, Lap2, and Ape2 are cooperative components of a Cvt-like vacuolar-targeting pathway, which we named Nbr1-mediated vacuolar targeting (NVT).

Is there a better way to capture this? If not, I'll leave it as is, and we'll have this ticket to record the reason.

**Comment by ValWood** [comment]
Ok, it looks odd,  (more like phenotypes) but I   guess future experiments will clarify.
