### ISSUE TITLE
new drug target

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2593]
mycophenolic acid
inhibits IMP dehydrogenase and thus limits cellular GTP pools (10).
MPA exacerbates growth impairment in mutants defective in transcript elongation (8, 11, 50), although the precise mechanism of this effect is unknown (34)

10.is
Escobar-Henriques M, Balguerie A, Monribot C, Boucherie H, Daig- nan-Fornier B. 2001. Proteome analysis and morphological studies reveal multiple effects of the immunosuppressive drug mycophenolic acid specifically resulting from guanylic nucleotide depletion. J. Biol. Chem. 276:
46237– 46242.

we need to make this page/data more visible...

from PMID:22508988 but the primary paper is the one above. I don't know what we record

**Comment by Antonialock** [comment]
I used the primary ref
