### ISSUE TITLE
Missing human ortholog

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2594]
FKBP12 - fkh1

**Comment by Antonialock** [comment]
<img width="1441" alt="Screenshot 2020-01-23 at 14 02 40" src="https://user-images.githubusercontent.com/12727506/72991011-0d6ad180-3de9-11ea-869d-ac2bda3182cb.png">

**Comment by Antonialock** [comment]
and https://www.pombase.org/reference/PMID:11335722

**Comment by ValWood** [comment]
fixed!
