### ISSUE TITLE
EcoGene no longer maintained 

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#2595]
https://github.com/geneontology/go-site/commit/b8a34346f92a8fc7e1fe62bc40d47c33ed7a924d#diff-20c49b5866419d3b2e72f80936960031

I noticed because it has been removed from GO.xrf_abbs so we can't link to it anymore.

**Comment by ValWood** [comment]
Do we have any links to EcoGene?

**Comment by kimrutherford** [comment]
There are only a handful, ~6 in the contig files.

from chromosome3.contig:
```
with=EcoGene:EG14102
```

https://www.pombase.org/gene/SPCC4G3.17

**Comment by ValWood** [comment]
I will replace these tomorrow

**Comment by ValWood** [comment]
I only see this one?

grep "EcoGene" *.contig
chromosome3.contig:FT                   db_xref=GO_REF:0000024; with=EcoGene:EG14102;

**Comment by ValWood** [comment]
I only see this one in the gaf  too. Please reopen if there are some more...

**Comment by mah11** [comment]
case differences (which I guess were getting corrected automagically somewhere in the pipeline)

chromosome1.contig

	FT                   /GO="aspect=F; term=DNA-3-methyladenine glycosylase
	FT                   activity; GOid=GO:0008725; evidence=IGI;
	FT                   db_xref=PMID:8921872;
	FT                   with=ECOGENE:EG10986,ECOGENE:EG11222; date=20120830"

	FT                   /GO="aspect=F; term=DNA-7-methylguanine glycosylase
	FT                   activity; GOid=GO:0043916; evidence=IGI;
	FT                   db_xref=PMID:8921872;
	FT                   with=ECOGENE:EG10986,ECOGENE:EG11222; date=20120830"

	FT                   /GO="aspect=F; term=tRNA(Ile)-lysidine synthase;
	FT                   GOid=GO:0032267; evidence=ISO; db_xref=GO_REF:0000024;
	FT                   with=ECOGENE:EG13357; date=20060922"

chromosome2.contig

	FT                   /GO="aspect=P; term=histidine biosynthesis;
	FT                   qualifier=heterologous_system; GOid=GO:0000105;
	FT                   evidence=IGI; db_xref=PMID:8299169; with=ECOGENE:EG10451;
	FT                   date=20130412"

	FT                   /GO="aspect=F; term=phosphoribosyl-AMP cyclohydrolase
	FT                   activity; qualifier=heterologous_system; GOid=GO:0004635;
	FT                   evidence=IGI; db_xref=PMID:8299169; with=ECOGENE:EG10451;
	FT                   date=20130412"

chromosome3.contig

	FT                   /GO="aspect=P; term=pyrimidine nucleotide metabolic
	FT                   process; GOid=GO:0006220; evidence=ISO;
	FT                   db_xref=GO_REF:0000024; with=EcoGene:EG14102;
	FT                   date=20190129"

**Comment by ValWood** [comment]
Thanks!

**Comment by mah11** [comment]
grep -i ftw!
