### ISSUE TITLE
regulates_activity_of solution

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2597]
sigh...

follow on from
https://github.com/pombase/curation/issues/2579

which is  follow on from

Pending |   |   |   | PomBase | SPAC1F5.04c | cdc12
Pending |   |   |   | PomBase | SPAC20G4.06c | adf1
Pending |   |   |   | PomBase | SPAC4A8.15c | cdc3
Pending |   |   |   | PomBase | SPBC1778.06c | fim1
Pending |   |   |   | PomBase | SPBC1778.06c | fim1

Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8
Pending |   |   |   | PomBase | SPAC27F1.02c | cdc8

These annotations seem as though they should be described as molecular functions but it is not clear how to do this.

@ValWood 
But "competitive inhibition" seems that it is a molecular function, not a process?
@pgaudet this has cropped up quite a lot. It seems that we need a way to capture inhibition of binding in GO? currently described as "negative regulation of actin filament binding"

@pgaudet
Isn't 'competitive inhibition of binding' the same as sequestering ?

@ValWood 
For example in this paper:
https://www.pombase.org/reference/PMID:20705471
https://linkinghub.elsevier.com/retrieve/pii/S0960982210009280
microfilament motor s actin-dependent
cdc8 binds actin and displaces myo1 (this seems to be competitive inhibition with actin as the competing substrate)

Sequestering seems odd in some contexts though. This would be actin filament sequestering?
I will see if this fits other examples I came across though.
I guess this example can only be captured by a full GO -cam where cdc8 "sequesters" actin -> negatively regulates myo1(actin binding)

**Comment by ValWood** [comment]
Note, some of the existing annotations 
GO:1904622 | negative regulation of actin-dependent ATPase activity Clayton JE et al. (2010)
GO:0120080 | negative regulation of microfilament motor activity Clayton JE et al. (2010)
will be made redundant  by
https://github.com/geneontology/go-ontology/issues/18664

Also, since the ATPase activity is regulated via indirectly via  affecting
negative regulation of actin filament binding (The myosin ATPase motor is actin-dependent),
some "regulation of function" annotations may not be required.

This is the model:
<img width="485" alt="Screenshot 2020-01-28 at 11 46 25" src="https://user-images.githubusercontent.com/7359272/73261385-dff49e00-41c3-11ea-96d7-96294aa31703.png">

**Comment by mah11** [comment]
looks like mostly GO ontology fodder ...

**Comment by ValWood** [comment]
Yes but I want to have a bit more of an idea what is required first. Once it's clearer what the issues are I will  open a ticket on the GO tracker.

**Comment by mah11** [comment]
> But "competitive inhibition" seems that it is a molecular function, not a process?

Hmm. To me it doesn't feel like a molecular function or a process. It's a phenomenon, and seems more analogous to a phenotype ...

> Isn't 'competitive inhibition of binding' the same as sequestering ?

No. Sequestering keeps X in one place to prevent it going somewhere else. Competitive binding is where X or Y can bind Z, but not both at once.

It doesn't make a lot of sense to say "competitive inhibition of binding" because "competitive inhibition" is a concept relevant to *catalytic* activities (and is as opposed to "noncompetitive inhibition" and "uncompetitive inhibition", which are different from competitive and from each other; if you need me to I'll dredge up the distinctions).

**Comment by mah11** [comment]
@pgaudet (transferred from #2579):

> It seems like 'actin sequestering' is being used in the scientific literature, e.g.:
> https://www.tebu-bio.com/blog/2015/02/23/capping-bundling-sequestering-the-role-of-actin-binding-proteins/
> 
> https://www.nature.com/articles/s41598-019-42977-2

For actin, "sequestering" is used specifically for binding to actin monomers (aka G-actin), to prevent them being added to actin filaments.

**Comment by ValWood** [comment]
Yeah I remember. I got a biochemistry degree. Don't tell anyone - I forgot it all.

Nothing seems quite right, I find this all the time with "binding inhibitors"   there's often no good way to describe this MF.
