### ISSUE TITLE
TETHERING AND ANCHORING

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2599]
From notes on my desktop. I might have done some of these...

- [x] protein membrane anchor tcb1 tcb2 
/GO="aspect=F; term=protein membrane adaptor activity; GOid=GO:0043495; evidence=ID; db_xref=GO_REF:0000111; from=GO:0005543|GO:0061817; date=20200319"
- [x] tcb3 
- [ ] LEM?
- [ ] sbg1	SPBP22H7.03	plasma membrane-actinomyosin ring linker protein Sbg1
out for community curation
- [x] mod5 SPBC530.04	Tea1 anchoring protein Mod5
- [x] tea4	SPBC1706.01	tip elongation aberrant protein Tea4
- [x] cortical protein anchoring mcp5 (num1)

**Comment by mah11** [comment]
GO:1903474 has gone obsolete, so these warnings now come up in the GO checks:

    WARNING - Obsolete class with no replacement: Violates GORULE:0000020 (GO:1903474) -- PomBase SPAC20G8.05c cdc15 GO:1903474 PMID:19139265 IMP P F-BAR domain protein Cdc15 protein taxon:4896 20120731 PomBase

    WARNING - Obsolete class with no replacement: Violates GORULE:0000020 (GO:1903474) -- PomBase SPAC20G8.05c cdc15 GO:1903474 PMID:26702831 IMP P F-BAR domain protein Cdc15 protein taxon:4896 20180308 PomBase

    WARNING - Obsolete class with no replacement: Violates GORULE:0000020 (GO:1903474) -- PomBase SPBC11C11.02 imp2 GO:1903474 PMID:19139265 IMP P F-BAR domain protein Imp2 protein taxon:4896 20170916 PomBase

    WARNING - Obsolete class with no replacement: Violates GORULE:0000020 (GO:1903474) -- PomBase SPBC577.06c stt4 GO:1903474 PMID:28784611 IMP P 1-phosphatidylinositol 4-kinase Stt4 protein taxon:4896 20170912 PomBase

    WARNING - Obsolete class with no replacement: Violates GORULE:0000020 (GO:1903474) -- PomBase SPBC83.18c fic1 GO:1903474 PMID:19139265 IMP P C2 domain protein Fic1 protein taxon:4896 20170914 PomBase

    WARNING - Obsolete class with no replacement: Violates GORULE:0000020 (GO:1903474) -- PomBase SPCC794.08 efr3 GO:1903474 PMID:28784611 IMP P phosphatidylinositol-4 kinase plasma membrane scaffold Efr3 protein taxon:4896 20170911 PomBase

Do you want me to fix them?

**Comment by ValWood** [comment]
Hmm, I thought I had done those. I will take a look...

**Comment by mah11** [comment]
If you did them already, it could just be a lag getting through GO. Next update on Monday ...

**Comment by mah11** [comment]
yup, the obsolete warnings are gone now, since Monday's GAF update

**Comment by ValWood** [comment]
- [x] tcb1 /GO="aspect=F; term=protein membrane adaptor activity; GOid=GO:0043495; evidence=ID; db_xref=GO_REF:0000111; from=GO:0005543|GO:0061817; date=20200319"

**Comment by ValWood** [comment]
At revision 6171.

**Comment by mah11** [comment]
you gonna fix the typo? 

> ; evidence=ID; 

if not I'll get to it when the logs catch it

**Comment by ValWood** [comment]
whoops.
fixed Committed revision 6174.
