### ISSUE TITLE
ELL complex

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2602]
This might be a "work in progress" but

Definition | Parents
-- | --
A heterodimeric protein complex that acts as an RNA polymerase II elongation factor; the complex is conserved from yeast to humans, and is present in S. pombe, but absent from S. cerevisiae.

has 3 annotations?

**Comment by mah11** [comment]
https://github.com/geneontology/go-ontology/issues/17203
(read the whole ticket)

also Canto session https://curation.pombase.org/pombe/curs/ba41ae11a8a2c405 & helpdesk ticket 6893
