### ISSUE TITLE
student project; figure out where tandem fusions are cleaved so we can annotate individual proteins

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#261]
Add notes about this later.
List of tandem fusions can re retrieved with PBO:0000229

Original comment by: ValWood

**Comment by ValWood** [comment]
when we can do this, we can link orthologs, go terms etc correctly to the correct CDS (i.e etp1/cox...)

**Comment by ValWood** [comment]
I'm not sure, but somebody might even be working on this issue...

**Comment by ValWood** [comment]
See "future" doc
