### ISSUE TITLE
check if these sessions should be approved (browser datasets are hosted already)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2610]
These should probably be community assigned, and approved (or completed)

     pmid      | canto_curator_name |    canto_triage_status    | canto_annotation_status 
---------------+--------------------+---------------------------+-------------------------
 - [ ] PMID:21981922 | François Bachand   | Curatable                 | SESSION_CREATED
This one has data for curation

 - [ ] PMID:25665008 | Daniel Jeffares    | Curatable                 | CURATION_IN_PROGRESS
 - [x] PMID:22531001 |                    | Curatable                 | 
 - [x]  PMID:24152550 |                    | Curatable                 | 
 - [x]  PMID:31077324 |                    | Curatable                 | 
- [x]   PMID:30566651 |                    | Curatable                 | 
- [x] PMID:24709818 |                    | Browser datasets, to host |

**Comment by ValWood** [comment]
check others

**Comment by mah11** [comment]
What is the task here?

**Comment by ValWood** [comment]
These are sessions that have browser datasets hosted, but are  'in limbo', need to be 'approved'  BUT might also have small scale data  (the Bachand one does, not sure about the 
Jaffares one, I think probably not). I checked/approved the others.

**Comment by ValWood** [comment]
Actually I can take this one, it isn't urgent. I was trying to divvy up a bit but this tracker isn't looking as daunting as it was....

**Comment by mah11** [comment]
OK; I was just wondering because the two remaining papers have sessions assigned to authors, so it wasn't clear whether you meant to remind them or seize the sessions back.

**Comment by ValWood** [comment]
Ah OK, Maybe I can  get the authors to do them...

**Comment by ValWood** [comment]
We need to  quickly check each  publication in the browser.
Add a list here:

**Comment by ValWood** [comment]
We can divvy this between us, first I need to remember where the spreadsheet is.....

**Comment by mah11** [comment]
> We need to quickly check each publication in the browser.

Check for what?

> I need to remember where the spreadsheet is

What spreadsheet?

**Comment by ValWood** [comment]
This was related to
https://github.com/pombase/website/issues/1435
