### ISSUE TITLE
 GEF 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2617]
Systematic ID | Gene name | Product description
-- | -- | --
 - [x] SPBC211.03c | gea1 | guanyl-nucleotide exchange factor (predicted)
- [x] SPAC4D7.01c | sec71 | Sec7 domain protein, ARF GEF (predicted)
- [x]  SPAC30.01c | sec72 | Sec7 domain protein, ARF GEF Sec72
- [x] SPAC19A8.01c | sec73 | guanyl-nucleotide exchange factor Sec73 (predicted)
- [x] SPAC26F1.01 | sec74 | guanyl-nucleotide exchange factor Sec74 (predicted)
- [x] SPAC6G9.04 | spo7 | sporulation protein Spo7
- [x] SPAC11E3.11c | syt22 | guanyl-nucleotide exchange factor Syt22

Standardise to
ArfGEF name
(don't need domain any more)

**Comment by ValWood** [comment]
Systematic ID | Gene name | Product description
-- | -- | --
SPAC644.18c | bet3 | TRAPP complex subunit Bet3 (predicted)
SPAC3G9.16c | bet5 | TRAPP complex subunit Bet5 (predicted)
SPAC23C4.10 | sec2 | guanyl-nucleotide exchange factor Sec2 (predicted)
SPAC23H4.14 | vam6 | guanyl-nucleotide exchange factor, HOPS complex subunit Vam6 (predicted)
SPCC297.05 |   | DENN domain Rab GDP-GTP exchange factor, implicated in endosomal transport (predicted)


Standardize to 
x complex Rab GEF subunit
or
Rab GEF

**Comment by ValWood** [comment]
Systematic ID | Gene name | Product description
-- | -- | --
SPBC19G7.08c | art1 | arrestin family protein Art1
SPAC24H6.09 | gef1 | Cdc42 RhoGEF Gef1
SPAC31A2.16 | gef2 | RhoGEF Gef2
SPBC29A3.17 | gef3 | Cdc42/Rho3/Rho4 RhoGEF Gef3
SPCC645.07 | rgf1 | RhoGEF for Rho1, Rgf1
SPAC1006.06 | rgf2 | RhoGEF Rgf2
SPCC645.06c | rgf3 | RhoGEF Rgf3
SPAC16E8.09 | scd1 | RhoGEF Scd1

**Comment by ValWood** [comment]
spo14
S. cerevisiae sec12 is described as GEF
but the paper has "GDP dissociation stimulator" is that GEF? @mah11

**Comment by ValWood** [comment]
Ras1 guanyl-nucleotide exchange factor Efc25
guanyl-nucleotide exchange factor Ste6

Ras GEF

**Comment by ValWood** [comment]
SPBC29A10.11c | vps902 | guanyl-nucleotide exchange factor, CUE domain absent Vps902
SPAC23D3.13c |   | guanyl-nucleotide exchange factor (predicted)
SPBC3E7.04c |   | Ric8 family guanine nucleotide exchange factor, human synembryn family

SPBC1778.05c | lam2 | Ragulator complex subunit, human LAMTOR2 ortholog
SPAC4F8.03 | sdo1 | SBDS family ribosome assembly protein Sdo1 (predicted)
SPCC1183.12 | spo13 | sporulation specific guanyl-nucleotide exchange factor Spo13

**Comment by mah11** [comment]
> spo14
> S. cerevisiae sec12 is described as GEF
> but the paper has "GDP dissociation stimulator" is that GEF? @mah11

Similar enough that it's probably OK - a GEF increases the probability that a bound guanyl nucleotide will come off and be replaced by another. It usually results in releasing GDP because any GTP that binds gets converted by the GTPase activity.
