### ISSUE TITLE
post-transcriptional RNA stability regulator Mkt1 - check and update

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2622]
@Antonialock 
Is  all of this related to mkt1?

From that 2020 paper 31822915 they say

A possible consequence of impaired post-transcriptional
downregulation of pericentromeric transcripts could be increased
accumulation of these transcripts on chromatin,
possibly resulting in increased DNA:RNA hybrid formation,
which has been implicated in defective heterochromatin
assembly (57,58).

Then they did some experiments where they observed increased DNA:RNA hybrids, and that suppressing them promoted heterchromatin formation

"suggesting
that suppressing DNA:RNA hybrid accumulation can partially
rescue the heterochromatin defect"

"These
findings are consistent with a model whereby, when transcription
at pericentromeres is high (either in an establishment
scenario, or when transcriptional silencing is impaired),
RNAi- and Mkt1-dependent post-transcriptional
silencing promotes heterochromatin assembly at least in
part through prevention of over-accumulation of pericentromeric
transcripts on chromatin."

so mkt1 is involved in "RNAi-mediated silencing"

the abnormal heterochromatin assembly is an indirect phenotype resulting from lots of RNA sticking to the DNA obstructingheterochromatin formation?

**Comment by ValWood** [comment]
and mkt1 product description update from





- [ ] XP-G family nuclease Mkt1
to

post-transcriptional RNA stability regulator Mkt1 ?

**Comment by ValWood** [comment]
"RNAi-mediated silencing" happens via heterochromatin assembly
 BUT All the BP annotations appear  to be indirect phenotypes. I removed them this morning while revising some transcription stuff. They should be phenotype only.


- [ ]  this the one we were discussing last night? If so it has a conserved  role  in mRNA processing?

**Comment by ValWood** [comment]
@Antonialock  do my 2 actions make sense to you?
DO you have anything I can ISS to?

**Comment by ValWood** [comment]
Interesting.
I found the paper we looked at
https://www.ncbi.nlm.nih.gov/pubmed/24470144

and I think pombe Zc3H11 might be
https://www.pombase.org/gene/SPAC3A11.02

anyway for now I updated the product. Also need to report and suppress the InterPro mapping

**Comment by Antonialock** [comment]
Yes I thought https://www.ncbi.nlm.nih.gov/pubmed/24470144 was a very good characterization paper. 

I am annotating Q587E3 (trypanosome mkt1) to mRNA stabilization
I know we discussed this term but in comparison to neg reg of mrna catabolism it does have the additional parent posttranscriptional regulation of gene expression which might be useful? It can be merged into something else automatically if the ontology changes...

I'm not great at pitching product descriptions, do you like

 post-transcriptional RNA stability regulator Mkt1 
or
Post-transcriptional regulator MKT1

better?

**Comment by Antonialock** [comment]
Zc3H11 is zfs1
you are thinking of lsm12?

**Comment by ValWood** [comment]
also mailed InterPro about the description here:
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR022039/

**Comment by ValWood** [comment]
no i have 

Ortholog species | Ortholog gene | Ortholog description | Reference
-- | -- | -- | --
Homo sapiens | ZFP36L1 (HGNC:1107) | ZFP36 ring finger protein like 1 |  
Homo sapiens | ZFP36L2 (HGNC:1108) | ZFP36 ring finger protein like 2 |  
Homo sapiens | ZFP36 (HGNC:12862) | ZFP36 ring finger protein

for zfs1?

**Comment by ValWood** [comment]
essentially waiting for Q587E3 
https://www.uniprot.org/uniprot/Q587E3
GO terms to make a better process ISS

**Comment by Antonialock** [comment]
I annotated it to
mRNA stabilization
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q587E3

I know it is on your do not annotate term set, but I didn't know what else to annotate to. 
see discussion in https://github.com/geneontology/go-ontology/issues/16360

**Comment by Antonialock** [comment]
hang on, that GO ticket is about protein stabilization, not mRNA stabilization (so ignore that GO ticket here) - maybe mRNA stabilization is ok?
