### ISSUE TITLE
new disease association PISD

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2624]
https://www.pombase.org/gene/SPBC16E9.18

  | <i>PISD</i> is a mitochondrial disease gene causing skeletal dysplasia, cataracts, and white matter changes.
  | Life Sci Alliance. 2019 Apr;2(2).
  | PMID: 30858161 [PubMed]

**Comment by ValWood** [comment]
@Antonialock  what do I need to do with this?

**Comment by ValWood** [comment]
Liberfarb syndrome
https://github.com/monarch-initiative/mondo/issues/1724

**Comment by Antonialock** [comment]
sorry only saw now. Yes I would look it up in OLS (more up to date than MONDO website) https://www.ebi.ac.uk/ols/search?q=Liberfarb+&groupField=iri&start=0&ontology=mondo 

can also search on OMIM ID e.g. 618889
https://omim.org/entry/618889?search=liberfarb%20syndrome&highlight=%28syndrome%7Csyndromic%29%20liberfarb

**Comment by ValWood** [comment]
https://github.com/monarch-initiative/mondo/issues/1724
MONDO_0030045 'liberfarb syndrome'

**Comment by ValWood** [comment]
done but check tomorrow
