### ISSUE TITLE
big drop in trancription  448 -> 406

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2628]
Not sure what caused this. A parent of something must have been deleted. Not sure how to trouble shoot right now

**Comment by ValWood** [comment]
It's because
transcription, DNA-templated (GO:0006351)
no longer inherits from
regulation of transcription, DNA-templated (GO:0006355)

The regulates parentage is still there (in QuickGO at least)


360 | regulation of transcription, DNA-templated (GO:0006355) | ...
-- | -- | --
  | 474 | (regulation of transcription, DNA-templated (GO:0006355) OR transcription, DNA-templated (GO:0006351)) | ...
  | 406 | transcription, DNA-templated (GO:0006351)

Can anyone see a reason for this? Some ontology or relationship change?

@mah11 
@kimrutherford 
@kimrutherford

**Comment by ValWood** [comment]
Actually the issue is more subtle than that.

292 | (regulation of transcription, DNA-templated (GO:0006355) AND transcription, DNA-templated (GO:0006351))


So only *Some* regulation of transcription does not end up in the transcription bin

**Comment by ValWood** [comment]
in
regulation of transcription by RNA polymerase II

**Comment by ValWood** [comment]
but not all

262 | (regulation of transcription by RNA polymerase II (GO:0006357) AND transcription, DNA-templated (GO:0006351))
-- | --

**Comment by ValWood** [comment]
heterochromatin assembly involved in chromatin silencing

propagates to "regulation of txn" but not to txn

Probably this OK, because it isn't really part of transcription.
(it also still slims -  to chromatin organization)

**Comment by kimrutherford** [comment]
Let me know if there's anything you'd like me to check.
