### ISSUE TITLE
should be "subtelomeric"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2634]
Need to move 
"nuclear telomeric hterochromatin" 
annotations to "chromsome telomeric region"

(telemeres aren't heterochromatin)

**Comment by ValWood** [comment]
Need to move 
"nuclear telomeric hterochromatin" 
annotations to "chromsome telomeric region"

(telemeres aren't heterochromatin)

**Comment by ValWood** [comment]
except these are "subtelomeric heterochromatin"
SPCC622.08c hta1 histone H2A alpha
SPAC19G12.06c hta2 histone H2A beta

this one I'm not sure. I didn't know it localized to telomeres...
SPAC15A10.15 sgo2 inner centromere protein, shugoshin Sgo2

**Comment by ValWood** [comment]
-  [ ] ago1 | ↑is_a GO:0000784 | nuclear chromosome, telomeric region | IEA with KW-0779 | GO_REF:0000043 | 55
-  [ ] ark1 | during mitotic metaphase | IDA | Reyes C et al. (2015)
-  [ ] arp6 |   | IDA | Ueno M et al. (2004)
-  [ ] bqt1 | during meiotic prophase I | IDA | Chikashige Y et al. (2006)
-  [ ] bqt2 | during meiotic prophase I | IDA | Chikashige Y et al. (2006)
-  [ ] bud32 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] ccq1 |   | IDA | Flory MR et al. (2004)
-  [ ] ccq1 |   | IDA | Miyoshi T et al. (2008)
-  [ ] cdc20 | during mitotic S phase | IDA | Moser BA et al. (2009)
-  [ ] cdc6 | during mitotic S phase | IDA | Moser BA et al. (2009)
-  [ ] cgi121 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] clr1 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] clr2 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] clr3 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] dna2 |   | IDA | Tomita K et al. (2004)
-  [ ] elg1 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] est1 |   | IC from telomerase holoenzyme complex | GO_REF:0000111
-  [ ] gon7 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] mcm2 | during mitotic S phase | IDA | Moser BA et al. (2009)
-  [ ] mit1 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] mre11 |   | IDA | Tomita K et al. (2003)
-  [ ] nbs1 |   | IDA | Moser BA et al. (2009)
-  [ ] pcc1 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] pku70 |   | IDA | Miyoshi T et al. (2003)
-  [ ] pku80 |   | IDA | Miyoshi T et al. (2003)
-  [ ] pol1 | during mitotic S phase | IDA | Moser BA et al. (2009)
-  [ ] pot1 |   | IDA | Moser BA et al. (2009)
-  [ ] poz1 |   | IDA | Miyoshi T et al. (2008)
-  [ ] rad26 | during mitotic S phase | IDA | Moser BA et al. (2009)
-  [ ] rap1 |   | IDA | Moser BA et al. (2009)
-  [ ] rdp1 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] sir2 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] ssb1 |   | IDA | Ono Y et al. (2003)
-  [ ] ssb1 | during mitotic S phase | IDA | Moser BA et al. (2009)
-  [ ] ssb3 |   | ISO with S000003709 | GO_REF:0000024
-  [ ] stn1 |   | IDA | Moser BA et al. (2009)
-  [ ] sua5 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] taz1 |   | IDA | Chikashige Y et al. (2001)
-  [ ] taz1 |   | IDA | Tomaska L et al. (2004)
-  [ ] taz1 |   | IDA | Moser BA et al. (2009)
-  [ ] taz1 | at telomeric_repeat | IDA | Rozenzhak S et al. (2010)
-  [ ] tbf1 |   | IDA | Pitt CW et al. (2008)
-  [ ] tcg1 |   | IC from single-stranded telomeric DNA binding | Pang TL et al. (2003)
-  [ ] teb1 |   | ISS with P54274 | GO_REF:0000024
-  [ ] tel1 |   | IEA with KW-0779 | GO_REF:0000043
-  [ ] tlh1 |   | IDA | Mandell JG et al. (2005)
-  [ ] tlh2 |   | IDA | Mandell JG et al. (2005)
-  [ ] tpz1 |   | IDA | Miyoshi T et al. (2008)
-  [ ] trt1 | during mitotic S phase | IDA | Moser BA et al. (2009)

**Comment by ValWood** [comment]
nuclear telomeric heterochromatin
--
  - [ ] cay1, 
  - [ ]  grc3, 
  - [ ] hta1, 
  - [ ] hta2,
  - [ ]  lem2
  - [ ] pku70
  - [ ]  pot1
  - [ ]  poz1
  - [ ]  rap1
  -  [ ]  rif1
  - [ ]  stn1
  - [ ] taz1
  - [ ]  ten1
  - [ ]  brc1 during mitotic S phase
  - [ ] cdc13 during meiotic G2 phase
  - [ ]  cdc2 during meiotic G2 phase
  - [ ] pfh1 at G_quartet

**Comment by ValWood** [comment]
check
-- | -- | --
SPBC16C6.10 | chp2 | heterochromatin (HP1) family chromodomain protein Chp2
SPAC1783.04c | hst4 | histone deacetylase, Sirtuin family, NAD-dependent Hst4
SPAC3A11.08 | pcu4 | cullin 4
SPCC613.12c | raf1 | CLRC ubiquitin ligase complex WD repeat subunit Raf1/Dos1
SPCC970.07c | raf2 | CLRC ubiquitin ligase complex subunit Raf2
SPBC16D10.07c | sir2 | histone deacetylase, Sirtuin family, NAD-dependent Sir2
SPBP8B7.28c | stc1 | CLRC ubiquitin ligase complex linker protein, LIM-like Stc1

**Comment by RLovering** [comment]
Please note that in humans it might not be possible to have data to separate the location of a gp in the telomere from location in the subtelomere and that we really need a grouping term
Ruth

**Comment by ValWood** [comment]
@RLovering  I agree a grouping term will be useful, also for searching-  this is the Pombase tracker though ;)

**Comment by ValWood** [comment]
Will be fixed when SPKW filtered.
More to do later when 
"chromsome telomeric region" will need to be migrated to a new descendant term
