### ISSUE TITLE
new GNC mailing list

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2643]
I just realised that we no longer have a GNC mailing list.
We should set up a new one. That is the royal 'we' ;)

**Comment by ValWood** [comment]
Could you do this, and one for our advisory board too using the mailman?

We will leave some people off GNC  (And appoint 2 new). We can zoom about that some time...

no hurry

**Comment by mah11** [comment]
How do you want these done? Options:

1. I can set up a mail alias in the "@pombase.org" domain that simply goes to the specified individuals, OR
2. We can request a full-fledged mailing list in the lists.cam.ac.uk system, as we've done for pombelist.

For both GNC and SAB, we have a small group that doesn't change often, so option 1 ought to work well, and option 2 seems like overkill. But "mailman" applies only to option 2, so I wanted to clarify what you prefer.

Either way, just get the list of GNC members to me once you've decided (I'll also update the relevant web page). Once that's done, option 1 has a same-day turnaround. GOK* how long option 2 might take.


*Gawd Only Knows

**Comment by ValWood** [comment]
I wasn't sure which would be best. But let's  go with the easy options....

The GNC members can be the current list minus Matthius (retired) and Steve(no longer works on fy).

**Comment by mah11** [comment]
It's Friday afternoon, so ... I've done my bit on this. Two new aliases should start working in the next hour or two:

gnc (at) pombase.org
sab (at) pombase.org
