### ISSUE TITLE
fragmented DNA 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2661]
I'm curating an old Lid2 paper,. The DNA is described as 'fragmented' but it looks like this:

<img width="761" alt="Screenshot 2020-04-07 at 17 04 07" src="https://user-images.githubusercontent.com/7359272/78692599-0cc6df00-78f2-11ea-82a2-431bc4962f82.png">

I don't think we can really say this is fragmented can we? It's just 'disorganized heterochromatin'
@mah11  what do you think?

**Comment by ValWood** [comment]
fig D lid2-j

**Comment by mah11** [comment]
The term itself is legit - the annotations from PMID:9649516 have gel evidence, and PMID:18047809 uses a TUNEL assay (evidence "other"). But I think you're right to suspect annotations using microscopy evidence (unless any of them are also TUNEL), and the flow cytometry ones from PMID:19366728 are just bonkers; those should use DNA content terms.

I'll fix PMID:19366728 ...

**Comment by ValWood** [comment]
OK I will check through the others  soonish...

**Comment by ValWood** [comment]
PMID:9649516
PMID:8119981
PMID:27168121
PMID:12181326
PMID:12925774
PMID:26446992
PMID:9115279
PMID:18047809
PMID:30810475
PMID:20410137
PMID:18344406
PMID:27168121
PMID:29316864

**Comment by ValWood** [comment]
PMID:10521402
Intranuclear spindles were formed but were disorganized, SPBs were duplicated and separated, and the nucleus disintegrated into several fragments.

I now think "fragmented nucleus" is a better term to use  for this phenotype, and it fits other similar:
https://www.pombase.org/results/from/id/742622fc-8186-4144-bcd2-91cda9e6e5db

**Comment by ValWood** [comment]
remaining to check
- [ ] SPBC216.05 | rad3 | ATR checkpoint kinase Rad3
- [ ] SPBC776.12c | hsk1 | Dbf4(Dfp1)-dependent protein kinase Hsk1
- [ ] SPAC8F11.07c | cdc24 | DNA replication protein Cdc24
- [ ] SPAC1783.04c | hst4 | histone deacetylase, Sirtuin family, NAD-dependent Hst4
- [ ] SPAC1805.17 | crm1 | karyopherin/importin beta family nuclear export signal receptor Crm1
- [ ] SPAC17C9.08 | pnu1 | mitochondrial endodeoxyribonuclease Pnu1
- [ ] SPAC110.02 | pds5 | mitotic and meiotic cohesin loader subunit Pds5
- [ ] SPAC16A10.06c | nse2 | Smc5-6 complex non-SMC SUMO ligase subunit Nse2
- [ ] SPCC550.05 | nse1 | Smc5-6 complex ubiquitin-protein ligase E3 subunit Nse1

**Comment by ValWood** [comment]
Two annotations remaining are fragmented DNA
