### ISSUE TITLE
PMID:8227198  gits

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2666]
I put this through temporarily because it is the source of the signalling pathway annotations for the gits

GO:0010619 | adenylate cyclase-activating glucose-activated G protein-coupled receptor signaling pathway

 BUT
it has no phenotypes - need adding

curs/219e86a87274fe5f

**Comment by ValWood** [comment]
@mah11  feel free to take this one if you are curating older papers and I haven't got to it first

**Comment by mah11** [comment]
done
