### ISSUE TITLE
negated extensions? PMID:22438582

### ISSUE THREAD

**Issue by mah11** [pombase/curation#2677]
GOA still runs some syntax checks on GAFs, which caught the NOT annotations from PMID:22438582 (https://curation.pombase.org/pombe/curs/5524d2f4237ade3e). An annotation shouldn't have both NOT and an extension.

As far as I know, GOC has not yet come up with an "official" way to make negation apply specifically to an extension. The only thing we can do for now is change to a negated extension (not_exists_during), which will get stripped out from the GAF that goes to GO. I can do that if you want - just let me know.

    Line 36353:	ERROR	Annotation_extension can not be supplied with NOT-qualified annotations	[exists_during(GO:0007128)]
    36353> PomBase	SPAC23C11.16	plo1	NOT	GO:0035974	PMID:22438582	IDA		C	Polo kinase Plo1		protein	taxon:4896	20200220	PomBase	exists_during(GO:0007128)	
    Line 36355:	ERROR	Annotation_extension can not be supplied with NOT-qualified annotations	[exists_during(GO:0007128)]
    36355> PomBase	SPBC649.05	cut12	NOT	GO:0035974	PMID:22438582	IDA		C	spindle pole body protein Cut12	stf1	protein	taxon:4896	20200220	PomBase	exists_during(GO:0007128)	
    Line 36356:	ERROR	Annotation_extension can not be supplied with NOT-qualified annotations	[exists_during(GO:0007128)]
    36356> PomBase	SPAC6G9.06c	pcp1	NOT	GO:0035974	PMID:22438582	IDA		C	gamma tubulin complex linker, pericentrin/kendrin Pcp1		protein	taxon:4896	20200220	PomBase	exists_during(GO:0007128)	
    Line 36359:	ERROR	Annotation_extension can not be supplied with NOT-qualified annotations	[exists_during(GO:0007128)]
    36359> PomBase  SPAC1F3.06c     spo15   NOT     GO:0035974      PMID:22438582   IDA             C       mitotic and mieotic spindle pole body protein Spo15             protein taxon:4896      20200220        PomBase exists_during(GO:0007128)

**Comment by ValWood** [comment]
I just removed them. I don't usually do negative phase specific localization and the actual prophase localization  (kinetochore) is covered.
