### ISSUE TITLE
wtf poison and antidote MF, and products

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2684]
We can give these different molecular function terms and /or products?

Would the driver poisons fit 
GO:0090729    toxin activity
Molecular Function

Definition (GO:0090729 GONUTS page)
Interacting selectively with one or more biological molecules in another (target) organism, initiating pathogenesis (leading to an abnormal, generally detrimental state) in the target organism. The activity should refer to an evolved function of the active gene product, i.e. one that was selected for. Examples include the activity of botulinum toxin, and snake venom.
Secondary IDs?

Then we could have "toxin inhibitor activity" too ?

**Comment by ValWood** [comment]
CC @lilindu

**Comment by ValWood** [comment]
From https://github.com/pombase/curation/issues/2264


Re product descriptions - I agree, we shouldn't call them all meiotic drivers because some have been tested and shown not to do meiotic drive. Also, some only do the suppression part, i.e. make antidote but not poison ...

**Comment by ValWood** [comment]
So we need a definitive list of which of the existing  structures  are  poison, and which are suppressors
(for GO and products)

**Comment by mah11** [comment]
Maria's more recent paper hasa nice summary of wtf classes and which ones have been tested (fig 1 & fig S1)

https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008350

PMID:32032353

**Comment by ValWood** [comment]
@mah11 I assigned this one to you.

**Comment by mah11** [comment]
product description updates done as best I can tell from PMID:32032353 (I haven't changed the class 3 ones from "wtf element")

I'm not convinced enough is known about molecular mechanisms to support GO MF annotations for either the poisons or the antidotes, so perhaps it would be better to open a new ticket when more details emerge.
