### ISSUE TITLE
Warnings from loading the disease annotation files with MONDO IDs

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#2691]
I couldn't find the ticket for this so I've made a new one.

Here are the current load warnings for the disease annotations files.

Warnings from pombe-embl/external_data/disease/pombase_disease_associations_mondo_ids.txt:

can't load annotation for SPAC25H1.10c - MONDO:0018859 not found in database
Waiting for monarch-initiative/helpdesk#18

~can't load annotation for SPBC1604.20c - MONDO:0000844 not found in database~
see below

Warnings from pombe-embl/external_data/disease/malacards_data_for_chado_mondo_ids.tsv:

~could not find cvterm for MONDO:0013019 - maybe obsolete?  Skipping annotation for SPBC27.08c / brachyolmia_type_4_with_mild_epiphyseal_and_metaphyseal_changes~                                                                                                               
see below

~no MONDO ID for myopathy_centronuclear_x_linked -> MTM1 (SPAC19A8.03)~
see below

Waiting for https://github.com/monarch-initiative/helpdesk/issues/18
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPBC1215.01 / leigh_syndrome_nuclear_dna_mutation
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPAC22E12.10c / leigh_syndrome_nuclear_dna_mutation
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPCC1840.09 / leigh_syndrome_nuclear_dna_mutation
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for 
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPBC365.02c / leigh_syndrome_nuclear_dna_mutation
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPAC644.07 / leigh_syndrome_nuclear_dna_mutation
SPMIT.07 / leigh_syndrome_nuclear_dna_mutation
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPAC1556.02c / leigh_syndrome_nuclear_dna_mutation
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPMIT.04 / leigh_syndrome_nuclear_dna_mutation
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPBC119.06 / leigh_syndrome_nuclear_dna_mutation
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPBC18E5.10 / leigh_syndrome_nuclear_dna_mutation
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPBC1198.10c / leigh_syndrome_nuclear_dna_mutation
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPCC24B10.22 / leigh_syndrome_nuclear_dna_mutation
could not find cvterm for MONDO:0018859 - maybe obsolete?  Skipping annotation for SPAC1805.09c / leigh_syndrome_nuclear_dna_mutation

~could not find cvterm for MONDO:0060722 - maybe obsolete?  Skipping annotation for SPAC23A1.12c / neurodevelopmental_disorder_with_brain_liver_and_lung_abnormalities~
see below                                                      

~could not find cvterm for MONDO:0011865 - maybe obsolete?  Skipping annotation for SPAC16A10.03c / brain_small_vessel_disease_with_or_without_ocular_anomalies~
    see below

~no MONDO ID for acetyl_coa_carboxylase_deficiency -> ACACA (SPAC56E4.04c)~
see below

**Comment by ValWood** [comment]
I will work through these.

could not find cvterm for MONDO:0013019 - maybe obsolete?  Skipping annotation for SPBC27.08c / brachyolmia_type_4_with_mild_epiphyseal_and_metaphyseal_changes                                                                                                                
no MONDO ID for myopathy_centronuclear_x_linked -> MTM1 (SPAC19A8.03)

appears to be correct, at least on the website.
https://monarchinitiative.org/disease/MONDO:0013019

**Comment by ValWood** [comment]
I need more info for these

"not a disease" doesn't look like a MONDO ID - skipping
"phenotype" doesn't look like a MONDO ID - skipping
"phenotype" doesn't look like a MONDO ID - skipping                                          
"phenotype" doesn't look like a MONDO ID - skipping
"not a disease" doesn't look like a MONDO ID - skipping
"phenotype" doesn't look like a MONDO ID - skipping
"blood group" doesn't look like a MONDO ID - skipping
"phenotype" doesn't look like a MONDO ID - skipping
"blood group" doesn't look like a MONDO ID - skipping
"blood group" doesn't look like a MONDO ID - skipping
"phenotype" doesn't look like a MONDO ID - skipping
"blood group" doesn't look like a MONDO ID - skipping
"can't find literature references to this" doesn't look like a MONDO ID - skipping
"not a single disease" doesn't look like a MONDO ID - skipping
"phenotype" doesn't look like a MONDO ID - skipping
"not a single disease" doesn't look like a MONDO ID - skipping                                                                                                          
"doesn't map, no mondo ID - phenotype?" doesn't look like a MONDO ID - skipping
"maps to HPO" doesn't look like a MONDO ID - skipping
"These are two conditions" doesn't look like a MONDO ID - skipping
"These are two conditions" doesn't look like a MONDO ID - skipping

@Antonialock ?

**Comment by ValWood** [comment]
no MONDO ID for myopathy_centronuclear_x_linked -> MTM1 (SPAC19A8.03)
is
X-linked centronuclear myopathy MONDO:0010683 (Redirected from MONDO:0006025)

**Comment by ValWood** [comment]
can't load annotation for SPBC1604.20c - MONDO:0000844 not found in database
seems to be present
https://monarchinitiative.org/disease/MONDO:0000844

**Comment by ValWood** [comment]
monarch-initiative/helpdesk#18
could not find cvterm for MONDO:0060722 - maybe obsolete? Skipping annotation for SPAC23A1.12c / neurodevelopmental_disorder_with_brain_liver_and_lung_abnormalities

according to 
https://www.uniprot.org/uniprot/Q9NSD9
this is 
Rajab interstitial lung disease with brain calcifications
https://monarchinitiative.org/disease/MONDO:0013346

**Comment by ValWood** [comment]
no MONDO ID for acetyl_coa_carboxylase_deficiency -> ACACA (SPAC56E4.04c)
https://www.uniprot.org/diseases/DI-01164
https://monarchinitiative.org/disease/MONDO:0013493

**Comment by ValWood** [comment]
could not find cvterm for MONDO:0011865 - maybe obsolete?  Skipping annotation for SPAC16A10.03c / brain_small_vessel_disease_with_or_without_ocular_anomalies
    https://monarchinitiative.org/disease/MONDO:0011865

**Comment by ValWood** [comment]
@kimrutherford  let me know if the ones which are still on the website are really not present. I'll open a ticket about that.

I have remapped all of the ones that I can for now.

Need more info for the lines with no genes.

**Comment by kimrutherford** [comment]
> appears to be correct, at least on the website.
> https://monarchinitiative.org/disease/MONDO:0013019

It's marked as obsolete in the OBO file:
```
[Term]
id: MONDO:0013019
name: obsolete spondyloepimetaphyseal dysplasia, Pakistani type
is_obsolete: true
replaced_by: MONDO:0019666
```


> I need more info for these

In those cases there is a message instead of a MONDO term ID in the term ID column of pombe-embl/external_data/disease/malacards_data_for_chado_mondo_ids.tsv 


> no MONDO ID for myopathy_centronuclear_x_linked -> MTM1 (SPAC19A8.03)
> is
> X-linked centronuclear myopathy MONDO:0010683 (Redirected from MONDO:0006025)

I've added MONDO:0010683 for myopathy_centronuclear_x_linked in malacards_data_for_chado_mondo_ids.tsv


> can't load annotation for SPBC1604.20c - MONDO:0000844 not found in database
> seems to be present

It's also obsolete in the OBO file.


> monarch-initiative/helpdesk#18
> could not find cvterm for MONDO:0060722 - maybe obsolete? Skipping annotation for SPAC23A1.12c / neurodevelopmental_disorder_with_brain_liver_and_lung_abnormalities
> 
> according to
> https://www.uniprot.org/uniprot/Q9NSD9
> this is
> Rajab interstitial lung disease with brain calcifications
> https://monarchinitiative.org/disease/MONDO:0013346

I've changed MONDO:0060722 to MONDO:0013346 in malacards_data_for_chado_mondo_ids.tsv


> no MONDO ID for acetyl_coa_carboxylase_deficiency -> ACACA (SPAC56E4.04c) https://www.uniprot.org/diseases/DI-01164
> https://monarchinitiative.org/disease/MONDO:0013493

I've added that to malacards_data_for_chado_mondo_ids.tsv


> https://monarchinitiative.org/disease/MONDO:0011865

Obsolete in the OBO file.

**Comment by ValWood** [comment]
For these:

[Term]
id: MONDO:0013019
name: obsolete spondyloepimetaphyseal dysplasia, Pakistani type
is_obsolete: true
replaced_by: MONDO:0019666

You can use "replaced_by"

Replaced by should be a safe  term for term replacement. If a term no longer maps to a single entry  (i.e for term split) the "replaced_by" can't be  used.

**Comment by ValWood** [comment]
Is there a replaced by for 
 MONDO:0018859 ?

**Comment by kimrutherford** [comment]
> You can use "replaced_by"

Ah, thanks.


> Is there a replaced by for
> MONDO:0018859 ?

Yep!

```
[Term]
id: MONDO:0018859
name: obsolete Leigh disease
is_obsolete: true
replaced_by: MONDO:0009723
```

I've substituted those two replacement terms in the malacards file.

**Comment by kimrutherford** [comment]
There's only one warning left that doesn't look like a note from Antonia:

could not find cvterm for MONDO:0011865 - maybe obsolete?  Skipping annotation for SPAC16A10.03c / brain_small_vessel_disease_with_or_without_ocular_anomalies

**Comment by ValWood** [comment]
Weird, because  SPAC16A10.03c  does not currently have   
 brain_small_vessel_disease_with_or_without_ocular_anomalies
has 2 others diseases  So I would say as long as it has something we can ignore that warning...

**Comment by Antonialock** [comment]
> There's only one warning left that doesn't look like a note from Antonia:
> 
> could not find cvterm for MONDO:0011865 - maybe obsolete? Skipping annotation for SPAC16A10.03c / brain_small_vessel_disease_with_or_without_ocular_anomalies

that is MONDO:0011865

**Comment by Antonialock** [comment]
> Weird, because SPAC16A10.03c does not currently have
> brain_small_vessel_disease_with_or_without_ocular_anomalies
> has 2 others diseases So I would say as long as it has something we can ignore that warning...

did that use to be col4a1 ortholog?

hypomyelinating leukodystrophy 12 is correct for vps11

**Comment by Antonialock** [comment]
ah
COL4A1-related familial vascular leukoencephalopathy MONDO:0011865
has many synonyms, one of them is "brain small vessel disease with or without ocular anomalies"

but this is not right for vps11 so it can be removed

**Comment by kimrutherford** [comment]
> ah
> COL4A1-related familial vascular leukoencephalopathy MONDO:0011865
> has many synonyms, one of them is "brain small vessel disease with or without ocular anomalies"
> but this is not right for vps11 so it can be removed

Thanks.  Is there a replacement MONDO term we could use instead?

**Comment by Antonialock** [comment]
no I think it can be removed. Col4a1 is (I guess) a collagen protein and VPS11 is something totally different. 

VPS11 ortholog is annotated to 
hypomyelinating leukodystrophy 12
and thats the only disease associated with that gene in omim, so that's ok
https://omim.org/entry/608549?search=vps11&highlight=vps11

**Comment by kimrutherford** [comment]
OK, great.  I've removed that mapping.

**Comment by Antonialock** [comment]
ah ok, phew, no ortholog oddities. 

In malacards_data_for_chado, malacards did have an association between VPS11 and that disease....but that association as been removed

**Comment by kimrutherford** [comment]
Thanks Antonia.  I think we can close this now.
