### ISSUE TITLE
Improve Disease slim across orthogonal categories

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2692]
from https://github.com/pombase/website/issues/1108

We need to add new grouping terms and subsets.
To be listed here:
@Antonialock

**Comment by ValWood** [comment]
@Antonialock  I am assigning  you too so you can approve of the changes I make

**Comment by ValWood** [comment]
Or disapprove ;)

**Comment by Antonialock** [comment]
remove  cerebral degeneration
it is_a neurdegenerative disease

**Comment by Antonialock** [comment]
I think we can also remove paraplegia (presumably is_a neurodegenerative)

**Comment by Antonialock** [comment]
where do I edit this?

**Comment by mah11** [comment]
https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json

or I can do it tomorrow

**Comment by ValWood** [comment]
> I think we can also remove paraplegia (presumably is_a neurodegenerative)

nope... isn't neurodegenerative.
Is 
 nervous system disorder but that might be too broad at this stage  (547). Let's try deleting paraplegia because it is possible everything will map alternatively anyway. If we need it we can always add it back. It''s an odd term for the slim...

**Comment by ValWood** [comment]
> remove cerebral degeneration
yup agreed, looks wierd anyway because it is 0 but that's a MONDO parentage issue

**Comment by Antonialock** [comment]
> 
> 
> > I think we can also remove paraplegia (presumably is_a neurodegenerative)
> 
> nope... isn't neurodegenerative.
> Is
> nervous system disorder but that might be too broad at this stage (547). Let's try deleting paraplegia because it is possible everything will map alternatively anyway. If we need it we can always add it back. It''s an odd term for the slim...

ah ok, I guess 'neurodegenerative' implies progressive disorders, paraplegia can result from sudden trauma.

**Comment by ValWood** [comment]
I moved the immediate changes required to the website tracker.
https://github.com/pombase/website/issues/1538

This ticket is for the longer term problem of slimming simultaneously across the orthogonal categories of tissue level/ cell level/ and type of inheritance.

We will deal with this later, because we can't make any sensible assessments  on this until  these are done:
https://github.com/monarch-initiative/mondo/issues/created_by/ValWood

**Comment by ValWood** [comment]
I think we are OK here for now. We can make improvements to the slim organically.
