### ISSUE TITLE
review missing curated diseases

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2696]
our import of 'curated diseases from other sources'  is out of date and slightly flawed.

once migration do->mondo is done:

a. quickfix
compare pombe:human 1:1 orthologs without a disease association against human genes with a disease association
(this was easy with old mondo website...not sure now...)

b. trickier-but-more-comprehensive fix 
compare pombe gene disease associations vs 1:1 ortholog disease association
(some genes will have more than one disease associated with them - we might have incompletely curated genes)

**Comment by ValWood** [comment]
- [x] done the new additions to Mondo https://github.com/pombase/website/issues/1537
 - [x] sorting out the slim eventually is here https://github.com/pombase/curation/issues/2692
