### ISSUE TITLE
MFs missing (improve MF slim coverage)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2697]
sensors
- [x] fep1	iron-sensor Fra2 -> iron sensor (https://github.com/geneontology/go-ontology/issues/19433)
- [x] ofd1	hypoxic oxygen sensor, prolyl-3,4-dihydroxylase Ofd1 -> GO:0019826    oxygen sensor activity?
- [x] shu1 | cell-surface heme acquisition protein Shu1  (heme receptor) (https://github.com/geneontology/go-ontology/issues/19699)

- [x] los1 karyopherin/importin-beta family nuclear import receptor Los1 (predicted) -> nuclear export signal receptor activity GO:0005049)

- [ ] rft1 ER Man5GlcNac2-PP-Dol translocation protein Rft1 -> more specific ?
https://github.com/geneontology/go-ontology/issues/19470
trying to figure if I can be more specific... 
asked SGD https://www.yeastgenome.org/locus/YBL020W if they can add an MF

- [x] SPCC663.18		GTPase interacting protein involved in vesicle tethering at the Golgi  -> GTPAse?

I misread, this is GTPase interacting, not GTPase . But the human ortholog seems to have a strong connection to autophagy @lilindu

**Comment by ValWood** [comment]
- [ ]  nbr1 | cargo receptor for selective autophagy pathway
- [ ]  cbf11 | CBF1/Su(H)/LAG-1 family transcription factor Cbf11
- [ ] cbf12 | CBF1/Su(H)/LAG-1 family transcription factor Cbf12
- [ ] shu1 | cell-surface heme acquisition protein Shu1
- [ ] cda1 | chitin deacetylase Cda1
- [ ]  fhl1 | forkhead transcription factor Fhl1
- [ ]  fkh2 | forkhead transcription factor Fkh2
- [ ]  sep1 | forkhead transcription factor Sep1

not sure why we have DNA binding TFs not mapping because I reviewed them recently...

**Comment by ValWood** [comment]
Ah OK, I must have omitted from the slim...

**Comment by ValWood** [comment]
SPBC428.01c | nup107 | nucleoporin Nup107
SPBC3B9.16c | nup120 | nucleoporin, WD repeat Nup120
SPAC30D11.04c | nup124 | nucleoporin Nup124
SPBP35G2.06c | nup131 | nucleoporin, WD repeat Nup131
SPAC1805.04 | nup132 | nucleoporin, WD repeat Nup132
SPAC23D3.06c | nup146 | nucleoporin, WD repeat Nup146
SPAC4F10.18 | nup37 | nucleoporin, WD repeat Nup37
SPAC19E9.01c | nup40 | nucleoporin Nup40
SPBC17G9.04c | nup85 | nucleoporin Nup85

**Comment by ValWood** [comment]
SPBC359.05 | abc3 | vacuolar heme ABC transmembrane exporter Abc3
 missing parentge to report, I assume

**Comment by ValWood** [comment]
SPAC1F8.03c | str3 | plasma membrane heme transmembrane transporter Str3
SPBC21B10.13c | yox1 | MBF complex corepressor Yox1
SPAC22H10.13 | zym1 | metallothionein Zym1

will be more but this will be a good start.

**Comment by ValWood** [comment]
adaptors and tethers
pep7 prevacuole/endosomal FYVE tethering component Pep7 (predicted)

**Comment by ValWood** [comment]
SPAC16C9.03 | nmd3 | export adaptor Nmd3 (predicted)
-- | -- | --

**Comment by ValWood** [comment]
Sequestering
rad25 14-3-3 protein Rad25

**Comment by ValWood** [comment]
SPAC4G8.05 | ppk14 | serine/threonine protein kinase Ppk14 (predicted)

**Comment by ValWood** [comment]
SPBC725.10 | tps0 | mitochondrial lipid translocator protein, tspO

**Comment by lilindu** [comment]
We have not come across SPCC663.18 in our research on autophagy.

**Comment by Antonialock** [comment]
hmm, I don't have accesss to the tsp0 paper right now, but it sounds like it could still be controversial?
'suggesting that...'

**Comment by ValWood** [comment]
I didn't look closely but they confirm alternatively, and conclude that it is....

**Comment by Antonialock** [comment]
> 
> 
> I didn't look closely but they confirm alternatively, and conclude that it is....

 the evidence isn't very elegant but they basically show that with an inhibitor import goes down, and with overexpression it goes up, I guess that's good enough for an initial characterization.

**Comment by ValWood** [comment]
Definitely. Author intent. High probability. I would annotate this,  it will either be confirmed or refuted...

**Comment by ValWood** [comment]
rad26 kinase regulator?

**Comment by ValWood** [comment]
I still don't have a MF on SPBC725.10 or rft1 but I'll  ahve another look at the dropout in 12 months or so. This was a reasonable improvement
