### ISSUE TITLE
Sequence update, followed by EMBL update

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#27]
• Hideki, gap filling ?
• Sasaki M, Idiris A, Tada A, Kumagai H, Giga-Hama Y, Tohda H. 
Yeast. 2008 Sep;25\(9\):673-9.PMID: 18727152 new telomeric clone
pending
http://www.sanger.ac.uk/Projects/S\_pombe/sequence\_updates.shtml
http://www.sanger.ac.uk/Projects/S\_pombe/sequence\_discrepancies.shtml

from trac ticket:
https://sourceforge.net/apps/trac/pombase/ticket/30

Original comment by: mah11

**Comment by ValWood** [comment]
duplicate of
https://github.com/pombase/curation/issues/633
