### ISSUE TITLE
 lost disease mapping

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2701]
See table

**Comment by ValWood** [comment]
check everything mapped by MOndo to everything mapped by DO to check if any others lost altogether.

The parentage issues should resolve in time, but we don't want to completely lose any existing annotations

**Comment by ValWood** [comment]
myopathy, lactic acidosis, and sideroblastic anemia 1
--
  | pus1

**Comment by kimrutherford** [comment]
> X-linked sideroblastic anemia with ataxia

Could you give me some more information on that?  It's not in the two input files:
 - pombase_disease_associations_mondo_ids.txt
 - malacards_data_for_chado_mondo_ids.tsv

**Comment by ValWood** [comment]
I  just did a diff these are the things which have a DO in PomBAse now  bit are not in the Mondo list


Systematic ID | Gene name | Product description
-- | -- | --
SPAC15A10.01 | atm1 | mitochondrial iron-sulfur cluster exporter Atm1
SPAC25H1.10c | atp19 | F1-FO ATP synthase subunit K (predicted)
SPBC25H2.12c | cct7 | chaperonin-containing T-complex eta subunit Cct7
SPAC20G8.05c | cdc15 | F-BAR domain protein Cdc15
SPCC737.06c | gcs2 | glutamate-cysteine ligase regulatory subunit Gcs2 (predicted)
SPCC126.03 | pus1 | TruA family tRNA/ U2 snRNA pseudouridine synthase Lsp1
SPBC646.16 | scl1 | 20S proteasome complex subunit alpha 1
SPCC794.09c | tef101 | translation elongation factor EF-1 alpha Ef1a-a
SPBC839.15c | tef103 | translation elongation factor EF-1 alpha Ef1a-c
SPAC323.06c | uba5 | NEDD8 activating enzyme E1-type Uba5 (predicted)
SPAC22G7.06c | ura1 | carbamoyl-phosphate synthase (glutamine hydrolyzing), aspartate carbamoyltransferase Ura1

**Comment by ValWood** [comment]
We can worry about these missing ones later. I will open a curation tracker ticket for that. I might not get to it today. I  now did the stuff which I needed to do before DO disappears, but not I need to do some  new slides for the GO meeting....

**Comment by ValWood** [comment]
ah this is on the curation tracker. TIme for food...

**Comment by ValWood** [comment]
grrrrr

**Comment by ValWood** [comment]
how hard can it be !&*£!!

**Comment by ValWood** [comment]
yay!

**Comment by ValWood** [comment]
@kimrutherford These are the MONDO mappings for the'drop-outs'. What do we need to do with them?

**Comment by kimrutherford** [comment]
> These are the MONDO mappings for the'drop-outs'. What do we need to do with them?

Thanks for those.  I'll add them to
pombe-embl/external_data/disease/pombase_disease_associations_mondo_ids.txt

**Comment by ValWood** [comment]
Did these get added? can I close?

**Comment by kimrutherford** [comment]
I added them to the file but made a typo so they didn't get loaded.  Fixed now so they should be in tomorrow morning.
