### ISSUE TITLE
check ISS outliers/stale ISS

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#271]
There are a LARGE number of ISS annotations which are "unsupported"
i.e the with column target does not have the annotation
A few may need removing but I think most probably need more granular at SGD. In some cases it is possible that the original annotation was removed from SGD (It would be great if there was some alerting for this!)
There is a Goose MySQL query to get the numbers.
Maybe this should link to a wiki page with a link to the query where we periodically check the total?
I don't really intend to do this as a task, but in general the numbers should obviously decrease.
It also might be a nice training exercise for Antonia (or us) to check a few of these and either
i) ask SGD if the annotation should be moved down
or
ii) find other supporting evidence
or
iii) remove if incorrect

from trac ticket:
https://sourceforge.net/apps/trac/pombase/ticket/4

Original comment by: mah11

**Comment by ValWood** [comment]
unless GO insists all ISS annotations are annotated and not just annotatable, this isn't going to happen. Rapid  erosion of ISS will make it unnecessary anyway...

**Comment by ValWood** [comment]
Added to "future" doc
