### ISSUE TITLE
PomBase/ Monarch differences

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2710]
<img width="956" alt="Screenshot 2020-05-15 at 10 57 28" src="https://user-images.githubusercontent.com/7359272/82038058-e20f3980-969a-11ea-832a-6edaf4f2bf3c.png">

List1 = All monarch disease causing
List 2 = All pombase disease associations
List 3 =  All  pombe proteins with human ortholog (human orthologs exported, will include  paralogs)

**Comment by ValWood** [comment]
These appear to be the things we have missing
42 common elements in "List 1" and "List 3":
ACTL6A
ACTL6B
ANAPC1
AP1B1
AP2M1
ARF1
ARHGAP24
BRSK2
CAP2
CUX1
CUX2
DHX38
DNMBP
EXOC6B
GPKOW
GRAP
KMT2E
MARCHF6
NUP160
NUP37
NUP85
NUP88
OXR1
PANK4
PARS2
PIGS
POLR3H
PPCS
PPIP5K2
RBSN
RFC1
RINT1
RPS15A
SARS1
SMARCC2
SRSF2
TARS1
TBC1D8B
TRMT1
USP45
WARS1
WEE2

**Comment by ValWood** [comment]
We have a lot of things which Monarch does not.

This could be because the method I used I  would pull in the paralogs of all the human disease causing genes which might not be disease causing,. PLus we have all the disease genes from the cancer census which might just be dispositions.
This is that diff:

762 common elements in "List 2" and "List 3":
ABCB1
ABCC1
ABCC3
ABHD4
ACACB
ACSL3
ACTBL2
ACTL7A
ACTL7B
ACTRT1
ACTRT2
ADAD1
ADAD2
ADARB1
ADARB2
ADD1
ADD2
ADH1A
ADH1B
ADH4
ADH5
ADH6
ADH7
ADRM1
AGGF1
AGPAT1
AIFM3
AKAP10
ALAS1
ALDH1A1
ALDH1A2
ALDH1B1
ALG10
ALG10B
ALG1L
ALPG
ALPI
ALPL
ALPP
AMMECR1L
AMPH
ANO8
AP3D1
ARFGEF1
ARG2
ARHGDIB
ARHGEF3
ARPC1A
ARSJ
ATAD2
ATAD2B
ATG16L1
ATG16L2
ATG5
ATP13A3
ATP13A5
ATP2A3
ATP2B1
ATP2B2
ATP2B4
ATP2C2
ATP5MD
ATP6V0A1
ATP6V1E2
ATP8A1
ATXN2L
ATXN7L1
ATXN7L2
AURKA
AURKB
AWAT2
AZIN1
AZIN2
BAIAP3
BCAP29
BDH1
BHMT
BHMT2
BIN2
BIRC2
BIRC3
BLCAP
BRD1
BRD2
BRD3
BRD4
BRDT
BRPF3
C15orf40
C15orf48
C1orf35
C9orf78
CALM3
CALML3
CALML4
CALML5
CARS1
CCNT1
CCNT2
CCT7
CDC14B
CDK12
CDK5
CDY1
CDY2A
CDYL2
CENPS
CENPX
CEP57L1
CERS2
CERS4
CERS5
CERS6
CFL1
CHCHD2P9
CHIC1
CHIC2
CHKA
CHMP4A
CHMP4C
CHN2
CLCN3
CLCN6
CLIP2
CLIP3
CLIP4
CMPK1
CNIH1
CNIH2
CNIH3
CNIH4
CNKSR1
CNKSR3
CNTRL
COA7
COMT
COQ5
COQ7
CORO1B
CORO1C
COX4I1
COX6B2
CSNK1E
CSNK2A2
CTAG1A
CTAG2
CTPS2
CUL4A
CWF19L2
CYB5B
CYB5R1
CYB5R2
CYP26A1
CYP51A1
DAZAP1
DCTN2
DCTN3
DDO
DDX10
DDX17
DDX3Y
DDX4
DDX5
DDX52
DDX6
DGAT2L6
DHX16
DIAPH2
DIP2A
DIP2C
DMC1
DMXL1
DNAJB1
DNAJB4
DNAJB5
DNAJC15
DNAJC5B
DNAJC5G
DPP10
DPP4
DRAM1
DSTN
DUS2
DYNLT1
EEF1A1
EIF1AY
EIF2AK2
EIF3E
EIF4A2
ELAC1
ELL
ELOVL1
ELOVL2
ELOVL7
ELP4
ENO1
ENO2
EP400
EPS15
ERCC6
ESS2
EVI5
EVI5L
EXO1
FAAH
FAP
FBP2
FBXO24
FBXW2
FBXW7
FEN1
FER1L5
FER1L6
FHIT
FIGNL1
FIP1L1
FMO1
FMO2
FMO4
FMO5
FOLH1
FOLH1B
FRG1
GALK2
GCLM
GDI2
GEMIN2
GET1
GFM2
GFPT2
GGT2
GGT3P
GGT5
GGTLC1
GGTLC2
GGTLC3
GIGYF1
GIGYF2
GLUD2
GLUL
GMPS
GNB2
GOLGA7
GOLGA7B
GOLPH3
GOLPH3L
GPD2
GPT
GSPT1
GSPT2
GYG2
GYG2P1
H3-3A
H4C1
HACD2
HACL1
HDAC10
HHATL
HID1
HINT2
HIP1
HIP1R
HK2
HK3
HMGB1
HMGB2
HMGB3
HMGB4
HMGCS1
HSD17B12
HSD17B2
HSDL1
HSP90AA1
HSP90AB1
HSPB2
HSPB6
HSPD1
HTRA3
HTRA4
IDE
IDH3G
IGF2R
ILVBL
IMPA2
IMPDH2
ING2
ING3
ING4
ING5
INPP5J
IPCEF1
JAZF1
KARS1
KAT7
KAT8
KDM2A
KDM2B
KDM5A
KDM5D
KDM6B
KDM7A
KIF13A
KIF13B
KIF16B
KIF20B
KMT5C
LASP1
LCP1
LETM1
LETM2
LIG1
LIPF
LIPJ
LIPK
LIPM
LMAN1L
LMAN2
LPIN3
LY96
MAPK7
MAPRE1
MARS1
MAT2A
MBD6
MCM5
ME1
ME2
ME3
MED12L
MEF2A
MEF2B
MEF2D
MFN1
MFSD11
MGAM
MINPP1
MLLT3
MOGAT1
MOGAT2
MOGAT3
MSI1
MSI2
MSRB2
MTMR1
MTMR6
MTMR7
MTMR8
MTMR9
MYH1
MYH10
MYH13
MYH15
MYH4
MYL1
MYL10
MYL12A
MYL12B
MYL5
MYL6
MYL6B
MYL7
MYL9
MYLPF
MYO1F
MYO5C
MYOF
NAA11
NAA16
NAALAD2
NAALADL1
NACA
NAE1
NCAPD2
NCAPH
NCKIPSD
NDUFA4L2
NEB
NEBL
NEDD4
NET1
NME2
NME2P1
NME3
NME4
NMNAT2
NMNAT3
NOM1
NOX1
NOX3
NOX4
NRAP
NSUN5
NUP62CL
NUP98
ODC1
OGDHL
OSBP
OSBP2
OSBPL1A
OTUD6A
PABPN1L
PAFAH2
PAK1
PAK2
PAPSS1
PAXIP1
PBRM1
PCBD2
PCBP1
PCBP2
PCBP3
PCBP4
PCYT1B
PDE4DIP
PDHA2
PDIA2
PDIA3
PDIA4
PDK1
PDK2
PDK4
PDP2
PEX11A
PEX5L
PFKL
PFKP
PGAM1
PGAM4
PGD
PGK2
PGM5
PHB
PHF2
PIF1
PIGK
PIK3C3
PIP5K1A
PIP5K1B
PKM
PLA2G15
PLA2G4B
PLA2G4C
PLA2G4D
PLA2G4E
PLA2G4F
PLCB2
PLCB3
PLCD3
PLCD4
PLCG1
PLCH1
PLCH2
PLCL1
PLCL2
PLD2
PLS1
PMM1
PNPLA7
POLK
POLR2A
POTEE
POTEF
PPA1
PPIC
PPP1CA
PPP1CC
PPP2R2A
PPP2R2C
PPP2R2D
PPP2R5A
PPP2R5B
PPP2R5C
PPP2R5E
PPP3CB
PPP3CC
PRKACB
PRKAG1
PRKAG3
PRKAR2A
PRKAR2B
PRKCA
PRKCB
PRKCE
PRKCH
PRKCQ
PRKX
PRODH2
PRPS2
PRTFDC1
PRUNE2
PSMA6
PSMB11
PSMB5
PSMD10
PSTPIP2
PTENP1
PTPN1
PTPN2
PTTG1
PTTG2
PTTG3P
PUM2
PXMP2
PYCR3
RABGAP1
RABGAP1L
RABGGTA
RAD17
RAD21L1
RAD51B
RAD9A
RAD9B
RANBP1
RANBP2
RBM5
RBM6
RBPJL
RDH13
REEP3
REEP4
REEP5
RGPD1
RGPD2
RGPD3
RGPD4
RGPD5
RGPD6
RGPD8
RHBG
RHCG
RNF113B
RNF166
RNF180
RPL10L
RPL22
RPL26L1
RPL27
RPN1
RPS27
RPS27L
RPS4X
RPS4Y1
RPS4Y2
RPS6KA1
RPS6KA2
RPS6KA6
RPS6KB2
RRM2
RTN1
RTN3
RTN4
SAC3D1
SAMD3
SAR1A
SDHAF3
SEC23IP
SEC24C
SEC31A
SEC31B
SEC61A2
SEM1
SETD1A
SETD1B
SFXN1
SFXN2
SFXN3
SFXN5
SGK1
SGK2
SGK3
SH3GL2
SH3GL3
SIN3B
SLC11A1
SLC13A1
SLC13A2
SLC13A3
SLC13A4
SLC16A10
SLC16A11
SLC16A13
SLC16A14
SLC16A3
SLC16A4
SLC16A5
SLC16A6
SLC16A7
SLC16A8
SLC16A9
SLC17A1
SLC17A2
SLC17A3
SLC17A4
SLC17A6
SLC17A7
SLC25A16
SLC25A18
SLC25A23
SLC25A25
SLC25A31
SLC25A41
SLC25A5
SLC25A6
SLC26A1
SLC26A6
SLC26A7
SLC26A9
SLC30A5
SLC30A7
SLC35D2
SLC36A3
SLC36A4
SLC39A7
SLC45A3
SLC46A2
SLC4A10
SLC4A2
SLC4A3
SLC4A7
SLC4A8
SLC4A9
SLC7A1
SLC7A10
SLC7A11
SLC7A13
SLC7A2
SLC7A3
SLC7A4
SLC7A5
SLC7A6
SLC7A8
SLC9A9
SMARCD1
SMARCD3
SMC1B
SMNDC1
SMPDL3A
SMPDL3B
SNAP23
SNAP91
SORCS2
SORCS3
SORT1
SPAG4
SPNS1
SPNS2
SPNS3
SPTLC3
SSB
STX19
STX1A
STX2
STX4
STXBP3
SUMO1
SUMO2
SUMO3
SUMO4
SUN1
SUN2
SUN3
SYNJ2
TACC1
TACC2
TACC3
TAF1L
TAF6L
TBC1D1
TBC1D20
TBC1D4
TBCC
TBL1X
TBL1Y
TBPL2
TCEA1
TCEA2
TCEA3
TCEANC
TCTE3
TCTEX1D1
TCTEX1D4
THADA
THOC1
TIMM8B
TKTL1
TKTL2
TM7SF2
TMEM150A
TMEM150B
TMEM150C
TOP1
TOP1MT
TP53BP1
TPR
TPTE
TPTE2
TRAPPC2B
TRAPPC6A
TRMT10B
TSG101
TSN
TSNAX
TTC7B
TTLL1
TTLL2
TTLL4
TTLL7
TTLL9
TUBA1B
TUBA1C
TUBA3C
TUBA3E
TUBA4B
TUBB6
TUBG2
TUT1
TXN
TXN2
TXNDC2
U2AF1
U2AF1L4
UBA7
UBB
UBC
UBE2B
UBQLN1
UBQLN3
UBQLN4
UBR2
UGGT1
UGGT2
UNC13A
UNC13B
UNC13C
UNC45A
UNC93A
UNC93B1
UPF3A
UQCRC1
UTY
VAPA
VPS41
VPS4A
WAS
WASL
WBP2NL
WDFY3
WDFY4
WDR7
WIPF2
XPNPEP1
XPNPEP2
XRCC3
YEATS4
YJEFN3
YWHAB
YWHAE
YWHAH
YWHAQ
YWHAZ
ZCCHC13
ZNRD2

**Comment by ValWood** [comment]
Although from eyeballing this list, I know many of these are 1:1 like
AMMECR1L (Allport syndrome) and PIG-K,  so Monarch could be missing quite a bit.

I wil pull out any of these that are 1:1's for Monarch.

@nicolevasilevsky @cmungall

**Comment by ValWood** [comment]
@Antonialock  I get why you were going on about 1:1 now ;)

**Comment by Antonialock** [comment]
:-) I'll try have a stab at the slim this w/e

inbetween installling the staircase! house is danger zone at the mo (sitting on the landing dangling feet over the edge is not laptop safe!)

**Comment by ValWood** [comment]
I don't think the slim will improve much until these  tickets are done.
https://github.com/pombase/curation/issues/2700
So I wouldn't worry about improving  at the moment.

I will map these stragglers now..
