### ISSUE TITLE
 PMID:29549126 missing phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2715]
This paper is curated, but doesn't have any of the heme acquisition phenotypes? (fig1 fig3)

**Comment by ValWood** [comment]
Assigning to you because I'm drowning in this tracker again.
I'm going to have a stab at getting it under control one day next week...

**Comment by mah11** [comment]
The phenotypes in figures 1 & 3 are cell population growth, and are curated. I added some annotations from figure 4.
