### ISSUE TITLE
GO annotation G0/ stationary phase

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#273]
GO TERMS 
GO:0070315 G1 to G0 transition involved in cell differentiation
GO:0070317 negative regulation of G0 to G1 transition
regulation of cell quiesence
PAPERS
PMID: 19833516 yanagida G0 genes 
PMID:17535257 
PMID 19366728 sajiki at oist.jp \(Kenich Sajiki\)
PMID: 20133687 
PMID: 20418666 
others?

from trac ticket:
https://sourceforge.net/apps/trac/pombase/ticket/12

Original comment by: mah11

**Comment by ValWood** [comment]
Its likely that all these papers have been done by Antonia,   not high priority to fix anything or fill gaps as far as I know so closing....
