### ISSUE TITLE
non coding RNA GO annotation evidence update

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#274]
i\) Most noncoding RNAs \(rRNA, sno, etc\) are annotated with RCA, need updating to ISS
ii\) tRNA annotations \(specific codons\) need checking

from trac ticket:
https://sourceforge.net/apps/trac/pombase/ticket/13

Original comment by: mah11

**Comment by mah11** [comment]
Antonia took care of the tRNA codons in #375

**Comment by mah11** [comment]
Val - do you have any plans for what, if anything, would go in the 'with' field for ISS? If it was tRNASCAN, the GO docs allow ISS without a 'with' entry, but I want to make sure ...

**Comment by ValWood** [comment]
It was tRNAscan!

**Comment by mah11** [comment]
oh good. that will make this job MUCH easier :D

**Comment by mah11** [comment]
did this on Friday but forgot to close
