### ISSUE TITLE
paper not reported a "not been through Canto"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2756]
https://www.pombase.org/reference/PMID:24793650

what 'status' dos this have?

**Comment by ValWood** [comment]
@mah11  can you look at this paper sometime? 
I was alerted to it my an elongation annotation which is in my soft check for GO do not annotate (can always be more specific). 
This comes from uniprot, but it doesn't seem quite right?

**Comment by mah11** [comment]
> This comes from uniprot, but it doesn't seem quite right?

By "this", do you mean the "elongation annotation" you mentioned? What kind of elongation (replication, transcription, translation, something else)?

Anyway, I have curated the paper in Canto so will close this.
