### ISSUE TITLE
merge allele

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2757]
https://www.pombase.org/genotype/mph1-kd-D459A-amino_acid_mutation-expression-not_assayed
https://www.pombase.org/genotype/mph1-kinase_dead-D459A-amino_acid_mutation-expression-not_assayed

**Comment by ValWood** [comment]
FIxed.
@mah11 This would be in the logs so I don't need to  tracker these as a rule?

**Comment by mah11** [comment]
That's correct - there's a big long list of alleles with the same description but different names in the chado-checks log. (I've fixed a few on the occasional Friday afternoon, but that's barely made a dent.) The mph1-kd versions did appear at least once ;)

**Comment by ValWood** [comment]
Ah OK, I will try to. pitch in with a few!
