### ISSUE TITLE
ATG2, lipid transfer activity ISS

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2761]
ATG2B

  | Osawa T, Ishii Y, Noda NN. | Related Articles
-- | -- | --
  | Human ATG2B possesses a lipid transfer activity which is accelerated by negatively charged lipids and WIPI4.
  | Genes Cells. 2019 Nov 12;. [Epub ahead of print]
  | PMID: 31721365

**Comment by ValWood** [comment]
GO:0120013   lipid transfer activity

**Comment by ValWood** [comment]
interesting because it also implicates
https://www.pombase.org/gene_subset/interpro:IPR026854
in lipid transfer  (cusative genes for early onset Parkinson's)

**Comment by ValWood** [comment]
@Lilindu

**Comment by lilindu** [comment]
Yes, Atg2 and Vps13 are now considered to be related lipid transfer proteins (https://www.sciencedirect.com/science/article/abs/pii/S0955067420300314).

**Comment by ValWood** [comment]
OK thanks. So if they tether and transfer this sounds similar to ERMES complex...

**Comment by ValWood** [comment]
updated....
