### ISSUE TITLE
fix diploids in background

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2769]
118900a57ae7a3da,homozygous diploid,homozygous diploid
18e97108cb413e18,heterozygous diploid,heterozygous diploid
1ebe4a1548de4aff,homozygous diploid,homozygous diploid
1ebe4a1548de4aff,nmt81-pcp1/nmt81-pcp1 homozygous diploid,homozygous diploid
1ebe4a1548de4aff,pat1-114/pat1-114 homozygous diploid,homozygous diploid
22e0aeba5f85fb0e,diploid  homozygous for rad50delta, also with ura4+/ura4-D18 ade6-M210/ade6-M216,diploid homozygous for also with ura4+
29ac2c8c97f2cc6c,heterozygous diploid,heterozygous diploid
46c89f342f117ca5,diploid,diploid
4770a22740e77442,heterozygous diploid,heterozygous diploid
4770a22740e77442,homozygous diploid,homozygous diploid
6378670e7a31c356,homozygous diploid,homozygous diploid
6378670e7a31c356,pat1-114/pat1-114; homozygous diploid,pat1-114; homozygous diploid
6a9c8e26d513116c,pat1-114/pat1-114 homozygous diploid,homozygous diploid
6c6dece2e0762651,assayed in diploid,assayed in diploid
7169c40527631f2c,mei4delta/mei4delta; homozygous diploid,mei4delta; homozygous diploid
7169c40527631f2c,pat1-114/pat1-114; homozygous diploid,pat1-114; homozygous diploid
8945fdb7cb39b74b,homozygous diploid,homozygous diploid
938360b9812110c8,ctp1d/ctp1d homozygous diploid,ctp1d ctp1d homozygous diploid
b447b564f630559e,homozygous diploid,homozygous diploid
bbe966c7c31d9042,diploid,diploid
bfaf9bdc389abc6d,homozygous diploid,homozygous diploid
c92c4fac293808ab,homozygous diploid,homozygous diploid
c92c4fac293808ab,smt-0/smt-0 non-sporulating homozygous diploid,smt-0 smt-0 non-sporulating homozygous diploid
dd81766bd2cc050a,homozygous diploid,homozygous diploid
f08c0f4e1a2f2ba5,heterozygous diploid,heterozygous diploid
f08c0f4e1a2f2ba5,homozygous diploid,homozygous diploid
f30149c5fcc7f553,diploid,diploid

**Comment by mah11** [comment]
done
