### ISSUE TITLE
no MF (not in slim)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2782]
I may have asked before, but  can any of these. get a MF so they are in the slim?
SPCC553.09c | spb70 | DNA polymerase alpha B-subunit
SPAC27E2.05 | cdc1 | DNA polymerase delta small subunit Cdc1
SPBP8B7.14c | dpb2 | DNA polymerase epsilon catalytic subunit B, Dpb2

(I could add DNA binding to the slim, I was trying to avoid binding terms that are not specific for a function where possible)

**Comment by mah11** [comment]
dpb2:
Hardly anything has been done experimentally in pombe (3 PubMed hits). Recent, mostly structural, work on the S. cerevisiae pol epsilon suggests that dpb2 does not bind DNA directly. It's a bit harder to translate what it is doing into GO MF annotations - PMID:30498216 shows lots of contacts with Pol2 and GINS subunits, and the authors conclude that "... Dpb2 must play a structural role in the replisome". In PMID:32572031 the authors end with "he likely function of the Dpb2 OB domain in bridging the helicase and polymerase in directing the leading strand through the replisome."

So we may want to do NOT GO:0003677 ISO with S.c., ref PMID:30498216. Any ideas what MF terms might work for the "positive" annotation from the above?? I'm stumped.

**Comment by mah11** [comment]
cdc1

I pretty much only found interaction and viability phenotypes in the pombe literature. Skimming structural papers on the human (p50) and S.c. (cdc31) proteins suggests that they interact with PCNA but don't bind DNA directly. It wasn't easy to tease more out. Maybe a contributes_to DNA polymerase activity by ISO wouldn't be outrageous (tho' the experimental annotations haven't been made for either human or S.c.), if only the new ruled allowed it (they don't).

PMIDs 28737709, 31582849, 32111820

**Comment by mah11** [comment]
spb70

Even less done in pombe than for the other two :P A lot of the stuff from other species jsut refers to it as the "B subunit" or "accessory subunit" of the polymerase part of the pol alpha/primase complex and then goes on to discuss any or all of the other subunits. I haven't found a clear statement of what (if anything) it does besides sit there.

**Comment by mah11** [comment]
To sum up, frustrating tho it is, no MF slim-worthy annotation isn't that bad a representation of what is and isn't known about these (unless you can think of something for dpb2).

**Comment by ValWood** [comment]
No worries, I thought I would check because I always assume we know what the DNA replications parts are doing...
