### ISSUE TITLE
ascospore formation troubleshooting

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2795]
Annotation number has recently dropped by >20
Need to find out why and report to GO

**Comment by ValWood** [comment]
Nothing is jumping out at me...

@mah11  do you have a way to see what the  descendants of "ascospore formation" were until ~month ago?

**Comment by mah11** [comment]
I can look at older versions of GO in OBO-Edit (go-basic.obo) or Protege (full-blown GO). Either way, I don't see any evidence of changes in the ascospore formation branch in the last 2 or 3 months. Let me know if you want me to look further back.

**Comment by ValWood** [comment]
No. That's really odd though, it was really recent.

I guess a mapping could have been removed but that seem odd too. I could not find anything that was obviously missing either...

**Comment by ValWood** [comment]
Found the difference, I found an old slim


We used to annotate  meitoci drivers to "negative regulation of sporulation" but that might be incorrect?

I will check into  nem1 and nem2


Systematic ID | Gene name | Product description
-- | -- | --
SPBC902.03 | nem2 | Nem1-Spo7 complex regulatory subunit (predicted)
SPBC3B8.10c | nem1 | Nem1-Spo7 phosphatase complex catalytic subunit Nem1 (predicted)
SPCC548.03c | wtf4 | wtf antidote element Wtf4 (predicted)
SPCC1919.06c | wtf25 | wtf element
SPCC1183.10 | wtf10 | wtf element Wtf10
SPCC1281.08 | wtf11 | wtf element Wtf11
SPCC622.21 | wtf12 | wtf element Wtf12 (truncated)
SPCC663.02 | wtf14 | wtf element Wtf14
SPCC663.17 | wtf15 | wtf element Wtf15
SPCC1450.08c | wtf16 | wtf element Wtf16
SPCC285.06c | wtf17 | wtf element Wtf17 (no initiator methionine)
SPCC1906.03 | wtf19 | wtf element Wtf19
SPCC1906.04 | wtf20 | wtf element Wtf20
SPCC1739.15 | wtf21 | wtf element Wtf21
SPCC1620.02 | wtf23 | wtf element Wtf23
SPCC794.02 | wtf5 | wtf element Wtf5
SPCC553.05c | wtf6 | wtf element Wtf6 (frameshifted)
SPCC736.05 | wtf7 | wtf element Wtf7
SPCC306.10 | wtf8 | wtf element Wtf8 (frameshifted)
SPCC970.11c | wtf9 | wtf element Wtf9
SPCC285.07c | wtf18 | wtf meiotic drive-related element Wtf18
SPCC162.04c | wtf13 | wtf meiotic driver Wtf13

**Comment by ValWood** [comment]
Will close

**Comment by mah11** [comment]
> We used to annotate meiotic drivers to "negative regulation of sporulation" but that might be incorrect?

That is indeed incorrect, so I removed those annotations. Not all of the wtfs do exactly the same thing (some seem to be antidote only; others aren't active), but even for the ones that do both poison and antidote, the mode of action isn't to regulate sporulation.

**Comment by ValWood** [comment]
Before we had a specific meiotic drive term Li Lin recommended "negative regulation of sporulation"
because sporulation is inhibited in the spores with an active driver.

**Comment by mah11** [comment]
If there are spores, then sporulation wasn't inhibited. Spores get made, and then some of them die (i.e. the driving spore killing takes place after sporulation).
