### ISSUE TITLE
replace NAS for tf mfs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2807]
/GO="aspect=F; term=RNA polymerase II cis-regulatory region sequence-specific DNA binding; GOid=GO:0000978; evidence=ISM; db_xref=GO_REF:0000050; with=InterPro:IPR002112; date=20200805"

/GO="aspect=F; term=DNA-binding transcription factor activity, RNA polymerase II-specific; GOid=GO:0000981; evidence=ISM; db_xref=GO_REF:0000050; with=InterPro:IPR002112; date=20200805"

- [x]  yox1 (removed)
- [x] php5 (removed)
- [x]  ams2 (chr3) (not required, has EXP)
- [x]  atf21 (chr2)  + GO:0000981
- [x] mbx2  (chr2)IPR002100  

- [x] fil1   (chr3)  ISM IPR000679
- [x] map1 (chr1)   ISM  IPR002100
- [ ] rsv1   PMID: 31472097
- [x] scr1   (chr2) ISS both to SGD:S000000830
- [x] zip1   (chr1) GO:0000978  IPR004827

**Comment by mah11** [comment]
These should use db_xref=GO_REF:0000050.

**Comment by ValWood** [comment]
Ah sorry I thought it was 24 for sequence based, ISM/ISO/ISS

so ISM=50
I really need to write these down and pin them on my fridge!

**Comment by mah11** [comment]
ISO is 24; ISM is 50

ISS is a superclass/parent of ISO, ISM, and a few others, so it doesn't map unambiguously to a single GO_REF.

**Comment by ValWood** [comment]
Committed revision 6469.
Outstanding is  rsv1 PMID: 31472097
waiting for feedback from @Antonialock whether to  remove session and send out for CC
