### ISSUE TITLE
non-coding RNA dataset hosting

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2809]
old ticket
https://github.com/pombase/curation/issues/2007

We currently have 1528 ncRNAs, but there are many additional datasets.

The current suggestion from @bahler lab is to remove all non characterised ncRNAs from the annotation and host as study specific-data tracks

Procedure

- List all data providers here
PMID:29914874 waiting for gff file from Maria ncRNAs SPNCRNA.2000 to SPNCRNA.7770

- Host all data tracks

- remove all "non characterised" ncRNAs from genome annotation

Questions and problems if we implemented this suggestion:
- ncRNAs would no longer be available to the query builder (this is probably OK, they have no annotation)
- This represents a return to multiple redundant datasets (but each dateset will be downloadable)
- We would need some way to assign IDs  for all  RNAs which do not have them (perhaps RNA central can help with this?)
- in the past some ncRNAs have been merged, this is probably OK if we keep the  currently annotated set of Bahler RNAs as the "curated set" of features for the bahler data
- Many RNAs will be redundant between datasets Possibly this does not matter if we  have the data in separate tracks and  we only 'promote' characterised RNAs to the  reference annotation set
- What to supply to RNACentral (because of the redundancy and overlaps)

Disadvantages
- Contig files would no longer represent all genome features
- Difficult to get a non-redundant dataset

Advantages
- Easy to add and remove entire datasets.

**Comment by ValWood** [comment]
After hols double-check with everyone what  exactly is desired solution. I have been reading through some of the old e-mails. I did not yet get answers to my previous questions. The request seems to be for ncRNA  data to only be hosted on data tracks and not part of the sequence annotation, but to be included in the sequence annotation files. These 2 requests are mutually incompatible. The data can be made available in separate files but not  in the annotated contigs. Need clarification.

**Comment by bahler** [comment]
I am discussing this with Maria and we will get back to you. Things are a bit frantic with a looming grant deadline..

**Comment by ValWood** [comment]
- Although it will be a PINTA to maintain a non-redundant data-set,  there would be quite a lot of value. Maybe the cryptic, rapidly degraded transcripts are not so useful,  but others ?

- There is a lot of redundancy between the old and the new. For example:
ncRNA
/db_xref="PMID:18488015"
/synonym="SPNG1066"
/product="non-coding RNA (predicted)"
/controlled_curation="term=warning, this transcript could be on either strand"
/controlled_curation="term=warning, no detectable long open reading frame; date=20071008"
/systematic_id="SPNCRNA.279"

was from non-strand specific method. The new data has an almost identical RNA on. the opposite strand
complement(5504431..5505464)

perhaps we should bite the bullet and  merge redundant?

Here is another example:
2 non strand-specificc should probably merge:
<img width="224" alt="Screenshot 2021-03-05 at 16 21 44" src="https://user-images.githubusercontent.com/7359272/110143243-f01b7b80-7dce-11eb-83bd-ca7b662c3ba7.png">

**Comment by ValWood** [comment]
- [ ] SPNCRNA.659 is described as a CUT in new data but is primary transcript for  snZ's (was labelled as antisense). We would need to be very careful about removing   some of the older ones into a track.
- [ ]  Also need to consider the provenence, as these are derived from multiple sources

**Comment by ValWood** [comment]
out of date
