### ISSUE TITLE
single annotations to "complex" terms to fix

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#281]
This list might be out of date now, but  somewhere I have the MySQL query to retreive the list of complexes with only one annotation
at some point a good consistency check would be to see why
\(are OK if the complex is multiple copies of the same subunit but for others should be possible to annotate other subunits....\)

GO:0032045 guanyl-nucleotide exchange factor complex 1
GO:0017102 methionyl glutamyl tRNA synthetase complex 1
GO:0005961 glycine dehydrogenase complex \(decarboxylating\) 1
GO:0000164 protein phosphatase type 1 complex 1
GO:0000798 nuclear cohesin complex 1
GO:0043224 nuclear SCF ubiquitin ligase complex 1
GO:0000113 nucleotide-excision repair factor 4 complex 1
GO:0031464 Cul4A-RING ubiquitin ligase complex 1
GO:0005968 Rab-protein geranylgeranyltransferase complex 1
GO:0005942 phosphoinositide 3-kinase complex 1
GO:0043505 centromere-specific nucleosome 1
GO:0005945 6-phosphofructokinase complex 1
GO:0009349 riboflavin synthase complex 1
GO:0005954 calcium- and calmodulin-dependent protein kinase complex 1
GO:0043614 multi-eIF complex 1
GO:0031201 SNARE complex 1
GO:0031588 AMP-activated protein kinase complex 1
GO:0000941 inner kinetochore of condensed nuclear chromosome 1
GO:0005745 m-AAA complex 1

Original comment by: ValWood

**Comment by ValWood** [comment]
homo-oligomers
GO:0009349 riboflavin synthase complex 1
GO:0005745 m-AAA complex 1

**Comment by ValWood** [comment]
current list

GO:0061617 micos complex
	GO:0000113	nucleotide-excision repair factor 4 complex
	GO:0000444	MIS12/MIND type complex
	GO:0000928	gamma-tubulin small complex, spindle pole body
	GO:0000931	gamma-tubulin large complex
	GO:0005668	RNA polymerase transcription factor SL1 complex
	GO:0005745	m-AAA complex
	GO:0005754	mitochondrial proton-transporting ATP synthase, catalytic core
	GO:0005827	polar microtubule
	GO:0005945	6-phosphofructokinase complex
	GO:0009337	sulfite reductase complex (NADPH)
	GO:0009349	riboflavin synthase complex
	GO:0017102	methionyl glutamyl tRNA synthetase complex
	GO:0017177	glucosidase II complex
	GO:0030685	nucleolar preribosome
	GO:0030869	RENT complex
	GO:0031201	SNARE complex
	GO:0032777	Piccolo NuA4 histone acetyltransferase complex
	GO:0032797	SMN complex
	GO:0033100	NuA3 histone acetyltransferase complex
	GO:0033203	DNA helicase A complex
	GO:0033254	vacuolar transporter chaperone complex
	GO:0033290	eukaryotic 48S preinitiation complex
	GO:0036087	glutathione synthase complex
	GO:0036449	microtubule minus-end
	GO:0038037	G-protein coupled receptor dimeric complex
	GO:0038038	G-protein coupled receptor homodimeric complex
	GO:0043505	CENP-A containing nucleosome
	GO:0043614	multi-eIF complex
	GO:0044612	nuclear pore linkers
	GO:0044615	nuclear pore nuclear basket
	GO:0044796	DNA polymerase processivity factor complex
	GO:0045267	proton-transporting ATP synthase, catalytic core
	GO:0055031	gamma-tubulin large complex, equatorial microtubule organizing center
	GO:0061495	gamma-tubulin small complex, mitotic spindle pole body
	GO:0070772	PAS complex
	GO:0071008	U2-type post-mRNA release spliceosomal complex
	GO:0071013	catalytic step 2 spliceosome
	GO:0071014	post-mRNA release spliceosomal complex
	GO:0097648	G-protein coupled receptor complex
	GO:0098802	plasma membrane receptor complex
	GO:1903600	glutaminase complex
	GO:1990537	mitotic spindle polar microtubule
	GO:1990574	meiotic spindle astral microtubule

**Comment by ValWood** [comment]
GO:0061617  micos complex.
DONE MIC10 SPAPJ691.03
DONE MIC19 SPBC25H2.09
MIC26 annotated  added mic27 as paralog
DONE MIC60 SPBC3E7.05c
mic12? YBR262C

added
/GO="aspect=P; term=cristae formation; GOid=GO:0042407; evidence=ISO; db_xref=GO_REF:0000024; with=SGD:S000007547; date=20160209"
/GO="aspect=C; term=mitochondrial crista junction; GOid=GO:0061617; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000007547;  date=20160209"
/GO="aspect=C; term=micos complex; GOid=GO:0061617; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000007547; date=20160209

changed some from unknown to predicted.

**Comment by ValWood** [comment]
Grouping complex term, filter from Complex file and GO annotation
GO:0097648 SNARE complex
GO:0098802	plasma membrane receptor complex
GO:0097648	G-protein coupled receptor complex
GO:0044796 DNA polymerase processivity factor complex
GO:0038037	G-protein coupled receptor dimeric complex
GO:0045267	proton-transporting ATP synthase, catalytic core

**Comment by ValWood** [comment]
Assembly intermediate
GO:0034457
GO:0005754 mitochondrial proton-transporting ATP synthase, catalytic core
GO:0030685 nucleolar preribosome

**Comment by ValWood** [comment]
filter, can’t be sure about pombe
GO:0017102
GO:0044796 	DNA polymerase processivity factor complex
GO:0032777	Piccolo NuA4 histone acetyltransferase complex
GO:0033100	NuA3 histone acetyltransferase complex
GO:0000113	nucleotide-excision repair factor 4 complex

**Comment by ValWood** [comment]
annotated some new complexes by ISS

This is not on my ongoing tasks list with other complex files checks so closing this. There are about 5 remaining that I'll fix next time
