### ISSUE TITLE
reciprocal binding, or move to Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2812]
- [x] mcl1  SPAPB1E7.02c. protein binding [happens_during] mitotic S phase  PMID:15643072
- [x]  SPBC646.13 protein binding [happens_during] G1 to G0 transition PMID:9242669 
- [x] SPAC3H5.06c.protein binding [happens_during] mitotic S phase 
- [x]  SPCC188.07 protein binding [happens_during] meiotic cell cycle PMID:15546621
- [x] SPBC11C11.04c| unfolded protein binding [has_substrate] SPBC26H8.07c [part_of] protein folding ISS add reciprocal? deleted has a has_substrate annotation
- [x] SPAC328.08c unfolded protein binding [has_substrate] SPBC26H8.07c [part_of] protein folding ISS add reciprocal?
- [x]   SPAC8E11.02c protein binding [has_substrate] transcription factor ste11 phosphorylated  PMID:11702950

**Comment by ValWood** [comment]
Committed revision 6473.

**Comment by kimrutherford** [comment]
The load failed because of the missing semicolon after the extension here:
```
FT                   /GO="aspect=F; term=protein binding; GOid=GO:0005515;
FT                   evidence=IPI; db_xref=PMID:15546621;
FT                   with=PomBase:SPCC188.07;
FT                   annotation_extension=happens_during(GO:0098762)
FT                   date=20080414"
```

I've fixed it and I'll make the loader handle that better.  It should have warned rather than failed.
