### ISSUE TITLE
rec12 papers

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2818]
From Gerry,

Rec12 has the active site for making the DSB; that’s why the rec12-Y98F mutation is Rec- (Cervantes et al., Mol Cell, 2000).  Evidence for covalent linkage is in Cromie et al. (PLoS Genet 2007) and Fowler et al. (Genome Res 2014).  If convenient, I think all three should be cited.  I don’t know of more direct evidence that Rec12-Y98 makes the covalent link, but the strong homology with S. cerevisiae Spo11 is good indirect evidence.  If you wish the Spo11 evidence, let me know and I’ll try to find it.

 Cervantes at al PMID: 10882124
Cromie et al PMID: 17722984 
Fowler et al 2014 PMID: 25024163 reassigned to Kyle

**Comment by ValWood** [comment]
I updated the product to "DSB forming protein"
and removed the  endonuclease associated ISS and IEA

**Comment by mah11** [comment]
PMID:10882124 done (yesterday).

For PMID:17722984 I added a few GO annotations, but most of the paper is genome-wide DSB detection and Rec12 localization. Maybe we could ask for browser track data?

**Comment by ValWood** [comment]
> Maybe we could ask for browser track data?

We have got a few browser tracks in the pipeline which seem to be later data for rec12 localization. So most likely these later tracks will be better. At least it isn't one of the papers Gerry included in the list ...
Once we have  received the current bunch and hosted I will ask Gerry if there are any more historical datasets that would be useful.....

**Comment by mah11** [comment]
OK. If the big picture of "track data from Gerry's lab" is in hand, I'll close this.
