### ISSUE TITLE
wtf location

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2819]
I notice wtfs have  annotation to various components HDA.

I usually filter them if they are not the location of action.

Name | Term | Genes
-- | -- | --
endoplasmic reticulum | GO:0005783 | 3
Golgi apparatus | GO:0005794 | 3
nucleus | GO:0005634 | 1
vacuole | GO:0005773 | 4

I will filter these

@mah11 can we make an appropriate plasme membrane annotation?   I  presume there is some data for this, if not TAS would work ?

**Comment by mah11** [comment]
> can we make an appropriate plasme membrane annotation?

No, plasma membrane is not appropriate.

>  I presume there is some data for this, if not TAS would work?

A few of the wtfs (4, 7, 13, 14, 15) have experimental CC annotations (and wtf14 is indeed in the ER). For the rest, the best thing to do depends on the class, per PMID:32032353 - class 1 = poison+antidote (known or putative driver); class 2 = antidote only (known or putative drive suppressor); class 3 = no predicted function.

The class 1 and class 2 wtfs that have been experimentally localized have antidote in spore cytoplasm and poison in spore cytoplasm + ascus epiplasm. ISS with the experimentally determined ones in the same class would probably do well enough for these two classes. wtf14 is class 3, but that class seems to be all over the place, so I think we're far safer admitting we don't have data to support CC annotations for the others.

There is no strong argument in favor of making TAS annotations.

**Comment by ValWood** [comment]
OK, but odd that they have function in cytoplasm  if they form a membrane pore?
Clearly we don't know enough...

**Comment by mah11** [comment]
>  if they form a membrane pore?

Where's the data for this? I haven't seen it, but I may not have read all the papers yet.

The ones that have been tested (by fluorescence microscopy) appear in the cytoplasm, and the poisons also in the ascus epiplasm.

**Comment by ValWood** [comment]
I can't remember. I thought they were membrane pores. Which  would make sense since they have 8   TM domains topologically arranged in a very "pore-like" configuration.

**Comment by ValWood** [comment]
Maybe it is this that I saw:
https://onlinelibrary.wiley.com/doi/full/10.1002/yea.3305
but it is only a hypothesized mechanism...

**Comment by ValWood** [comment]
fig 1c

**Comment by mah11** [comment]
I haven't seen any experimental data on a mechanism, and the localization tends not to look like plasma membrane at all. I don't think internal membranes are ruled out, esp. given the TM domains ... but I wouldn't go more specific than cytoplasm from any localization data I've seen (let alone any ISS from it).

**Comment by ValWood** [comment]
Yes plasma membrane would not make sense anyway, since it needs to be gamete specific.

**Comment by mah11** [comment]
I've put in a bunch of ISS annotations, mostly to spore cytoplasm; I also included ascus epiplasm for the poison forms. I didn't add anything for the pseudos, truncations, etc. (1, 3, 6, 8, 12, 17, 22, 24) in case the alteration changes the localization or even whether a protein is made, and I also didn't do the unknown-function class 3 'cos they're weird even by wtf standards.

That's probably all we can do until more data roll in. But that may not take them long now ...
