### ISSUE TITLE
SSA function update?

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2824]
TF co-activator activity

neoformans
https://pubmed.ncbi.nlm.nih.gov/17040492/

cerevisiae
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6690698/

**Comment by Antonialock** [comment]
although
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5225068/

**Comment by ValWood** [comment]
What's SSA?

**Comment by Antonialock** [comment]
ssa1/2, one of them :-)

**Comment by Antonialock** [comment]
just looked like it would be a really conserved thing, and totally different from protein refolding

**Comment by ValWood** [comment]
Ah I see. I don't think this makes it a "coregulator". A coregulator interacts with a transcription factor when it is DNA bound.

This seems to prevent DNA-binding transcription factor binding (is that right, I only looked at the abstract?).
In this case it would be a 
GO:0140416 DNA-binding transcription factor inhibitor activity
https://www.ebi.ac.uk/QuickGO/term/GO:0140416

An activity that stops, prevents, or reduces the activity of a DNA binding transcription factor activity

Comments
An example is TCF23 Q7RTU1 is an example of a protein that regulates transcription factors by heterodimerising or binding to DbTFs and prevent DNA binding and their specific genomic binding site where the dbTF would have activated or repressed transcription. Also an example is NFKBIA P25963 which has a different way of regulating transcription factor activity by sequestering the dbTF (complex) in the cytoplasm. Another example is the HSP90 and HSP23 proteins that sequester steroid receptors away from the DNA.

**Comment by Antonialock** [comment]
a yes, cerevisiae papers are different. Thought it would be exciting. It's just the neoformans paper reporting the activity

"The Hsp70 member, Ssa1, acts as a DNA-binding transcriptional co-activator of laccase in Cryptococcus neoformans "
PMID: 17040492

**Comment by ValWood** [comment]
You used

GO:0140416 DNA-binding transcription factor inhibitor activity
though, not the co-activator term?

**Comment by Antonialock** [comment]
for neoformans I used coactivator activity. It's what they show in the paper

"The GCrE‐binding protein was purified and identified to be a Hsp70 homologue, Ssa1. Further analysis showed that Ssa1 acts as a GCrE DNA‐binding transcriptional co‐activator, interacting with HSF to mediate the activation of laccase in response to stress, and is required for full fungal virulence. "

**Comment by Antonialock** [comment]
@ValWood

**Comment by ValWood** [comment]
So hsp70 has 2 mechanisms,  sequestering the DNA binding TF and as a coactivator?

**Comment by Antonialock** [comment]
in the cerevisiae paper I looked at, it looks like hsp70 binds and inhibits the DNA binding TF hsf1 on DNA. When there are misfolded proteins around, the misfolded proteins "sequester" hsp70; they bind to it, and it falls off the TF, so the TF can drive transcription. 

This function was not shown for the neoformans protein, but the authors were not looking at thermostress, they were looking at glucose starvation. Maybe there's different regulatory mechanisms in play?

**Comment by ValWood** [comment]
If "hsp70 binds and inhibits the DNA binding TF hsf1 on DNA"
it isn't a co activator it's a
GO:0140416 DNA-binding transcription factor inhibitor activity
(but this is also sequestering, so  perhaps there should be a combined term)

a coactivator activates transcription by binding to a DNA-bound transcription factor.

@pgaudet is this correct?

**Comment by Antonialock** [comment]
yes in cerevisiae. I thought this novel function might be applicable to other yeasts, but it doesn't appear that current evidence supports it. Ticket closed :-) 

The present studies thus deﬁne a new role for a hsp70
homologue, Ssa1, acting as a transcriptional co-activator
that requires binding to DNA within the 5′-UAS region of
laccase and activates gene expression in concert with the
formation of a complex with HSF under conditions of
glucose starvation. Interestingly, this activation occurs
even in the absence of heat shock, although previous
studies in S. cerevisiae have shown Ssa1 to accumulate
in the nucleus in response to glucose starvation in the
absence of heat shock (Shulga et al., 1996), which sup-
ports the ability of Ssa1 to participate in such complexes
in the absence of heat shock. This is also supported by
the present studies which found that SSA1 transcription
itself was induced by glucose starvation in the absence of
heat shock – conditions that stimulate laccase gene
expression (Fig. S3). Taken together, the experiments
presented here deﬁne a novel role for a Hsp70 family
member, Ssa1, in the co-activation of gene expression
through direct DNA interaction

**Comment by ValWood** [comment]
But if it binds to DNA specifically,  that would make it a DNA-binding transcription factor?

**Comment by Antonialock** [comment]
yes I was wondering about that...they say it is not a TF since it lacks (an obvious) activation domain, but they show it has DNA binding activity and TF binding activity (at least that's what I make out)

PMID:17040492:
"Several lines of evidence suggested that Ssa1 may interact with HSF during laccase expression. These included:
(i) the proximity and similar role in temperature regulation of the HSE and the GCrE within the laccase promoter (Fig. 1B), 
(ii) the lack of an obvious activation domain in Hsp70 suggesting a requirement for a co-activator, and (iii) a Kd value in the low nanomolar range, more typical of interacting transcription factors such as fos-jun (Kwon et al., 2001). Thus, we assessed for a possible interaction of the Ssa1 protein with HSF during conditions of laccase induction

...Recovery of HSF in the GCrE–Ssa1 complex thus suggests an interaction between Hsp70 and HSF during GCrE-dependent laccase expression.

...Combined with the presence of an immunoreactive band using an anti- TBP antibody after anti-Ssa1 antibody immunoprecipitation demonstrates that Ssa1 and HSF form complexes in induced nuclear extracts with the TATA-binding protein (TBP) complex during laccase expression.


...suggest that the Hsp70–HSF complex communicates with the basal transcription machinery containing TBP, and that Ssa1 participates in the transcriptional regulatory complexes during laccase expression.

**Comment by Antonialock** [comment]
@ruthlovering (can I tag Ruth here? I can move the question otherwise) have you come across an example like this? In other fungi it looks like a HSP70 protein binds the heat shock factor TF and inhibits its activity. In neoformans it is shown it binds DNA + the TF and helps activate transcription. They call it a coactivator and say it doesn't look like a TF in its own right.

**Comment by Antonialock** [comment]
@RLovering (can I tag Ruth here? I can move the question otherwise) have you come across an example like this? In other fungi it looks like a HSP70 protein binds the heat shock factor TF and inhibits its activity. In neoformans it is shown it binds DNA + the TF and helps activate transcription. They call it a coactivator and say it doesn't look like a TF in its own right.

**Comment by ValWood** [comment]
Also tagging @colinlog

**Comment by pgaudet** [comment]
Hi @ValWood @Antonialock 

We looked at this with @colinlog and @RLovering and this is *not* a transcription factor. Also, it may be part of a complex that binds DNA, but that doesn't make it a transcription factor. HSP are quite promiscuous and maybe the assay is a bit artifactual. 

WRT questions in earlier comments: 

> If "hsp70 binds and inhibits the DNA binding TF hsf1 on DNA"
it isn't a co activator it's a
GO:0140416 DNA-binding transcription factor inhibitor activity
(but this is also sequestering, so perhaps there should be a combined term)

Yes, this is right 

> But if it binds to DNA specifically, that would make it a DNA-binding transcription factor?

Yes it does, but you need to be very careful about the assay - that DNA binding is clearly shown, that the purified protein is used and not nuclear extracts - those are the main issues usually. 

 
Let us know if you would like us to look at specific data. 

Thanks, Pascale

**Comment by ValWood** [comment]
I was also worried about  it being an artefact.  A lot of highly abundant proteins form what is commonly referred to as the "crapome" and bind to everything...

**Comment by Antonialock** [comment]
Yes that would be great. Note that this paper is for neoformans. They call the protein Ssa1 but there seems to be a number of paralogs.

The paper is from 2006

First they show that a complex binds GCrE (GC rich element).
To see if binding is direct, they use HSP70/Ssa1 purified from E. coli
Fig 2C: "Interestingly, the immobilized GCrE also adsorbed recombinant Ssa1 directly from E. coli extracts under the same incubation conditions, suggesting again that Ssa1 binds directly to DNA.

caveat: there was a cross-linking element to the assay
"Affinity pull-down experiments were performed as described in Experimental procedures using cryptococcal nuclear extracts (NE) or cell extracts of E. coli-expressing rSsa1 incubated with an immobilized days-oligonucleotide of GCrE or an identical days-oligonucleotide containing three G-T mutations within the GCrE consensus sequence (GCrEm). The immobilized DNA–protein material was extensively washed and the protein–DNA complex was stabilized by UV cross-linking, and eluted by boiling in SDS sample buffer followed by SDS-PAGE and autoradiography (left) or Western blot using the indicated antibodies (right)."

If I (should I?) remove the DNA binding annotation, can I keep the coactivator term? The authors seem pretty confident it is acting as an activator (the title of the paper is 'The Hsp70 member, Ssa1, acts as a DNA-binding transcriptional co-activator of laccase in Cryptococcus neoformans'
I'm attaching the paper. Also accessible here: https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2958.2006.05422.x

[17040492.pdf](https://github.com/pombase/curation/files/5275429/17040492.pdf)

**Comment by colinlog** [comment]
I could not find a competition assay with a mutant oligo in this paper. Without that control, the DNA sequence-specificity proof is rather weak, even though there is an EMSA with a mutant that shows no binding. I would have liked to see such an unlabelled mutant oligo used in side by side competition with the unlabelled  'specific' oligo so as to objectively compare their relative affinities for SSA1.

For the transcription activation part I would be very prudent too. HSP70 mutant cells will show pleiotropic effects and thus also 'non-specific' 'indirect' gene activity changes. The authors do not show that the phenotypic phenomenology they report requires SSA1 binding to the response element in vivo. Considering we are talking about a well-known protein chaperone component, demonstrating specificity at the protein level, for example by showing that SSA1, but the other HSP70 homologues of this organism, is specifically involved would have been more convincing. Classically, co-activation is demonstrated by linking the coactivating protein to a heterologous DNA binding domain and showing that this increases transcription from a promoter bearing the heterologous DBD target, only when the target DNA motif is present.

All in all, the burden of proof for a heat shock factor's involvement in another process than protein (un)folding, such as the presently proposed sequence-specific DNA binding activity  or transcription co-activator activity is high, and it may not have been met by this study ...  So, no I would not recommend annotating SSA1 to either dbTF or co-regulator, unless more 'orthogonal' evidence is available, in this organism or in another species.

**Comment by Antonialock** [comment]
Thank you all for your input. I thought it was a very novel finding. I know from the recent GO workshop that it is a difficult to annotate area, but the paper was fairly recent, published by a respectable journal & university, and the wording was such it seemed strange not to take it at face value. I'll amend the annotations & put a note on the paper - if more evidence comes to light in the future they can be changed at that point. 

So where is that annotation degree I meant to obtain...

**Comment by ValWood** [comment]
The problem here is the review process. I think the fission yeast community are a   bit more stringent and would ask for additional experiments (mostly), but  for species with not such a strong community with a lot of experience it is likely the reviewers are not as experienced.

I probably would have annotated this too...
