### ISSUE TITLE
DIP22 mug62 / SPAC22F3.04 and SPAC56F8.02

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2831]
SPAC56F8.02

this might be useful for dip2

PMID: 30672040 DOI: 10.1002/cbin.11106
Abstract Disconnected interacting protein 2 (DIP2) is a highly conserved protein family among 
invertebrates and vertebrates, but its function remains unclear. In this paper, we summarized the conservation of gene sequences and protein domains of DIP2 family members and predicted that they may have a similar functional role in acetyl-coenzyme A (acetyl-CoA) synthesis. We then used the most characterized member, disconnected interacting protein 2 homolog A (DIP2A), for further study. DIP2A is a cytoplasmic protein that is preferentially localized to mitochondria, and its acetyl-CoA synthetase activity has been demonstrated in vitro. Furthermore, the level of acetyl-CoA in HEK293 cells overexpressing DIP2A was increased, which is consistent with its metabolically related function. Together, these data enrich the evolutionary and functional characterization of dip2 genes and provide significant insights into the identification and application of other homologs of DIP2.

**Comment by ValWood** [comment]
@Antonialock  looks like a useful paper...

**Comment by ValWood** [comment]
submitted to UniProt helpdesk.  Updated product and will add GO if it 'passes'

**Comment by ValWood** [comment]
I was sure I updated these but apparently now. I will wait for uniprot and then add

**Comment by Antonialock** [comment]
I see this has been done in P2GO, it got acetyl-CoA biosynthetic process + mitochondrion. Did you expect any MFs?

**Comment by ValWood** [comment]
no,  I think the process will do for now.
I did this but I did not ISS to mitochondria. Will do that now.

**Comment by ValWood** [comment]
although odd that pombe or cerevisiae have never been detected in mitochondrion.
I'll risk it, can fix later.
