### ISSUE TITLE
create in-house PRO display names

### ISSUE THREAD

**Issue by mah11** [pombase/curation#2851]
For any protein ontology term directly used in annotation:

- GO "active form", i.e. GAF column 17
- GO extension (has_input, has_substrate, has_direct_input)
- FYPO extension (assayed_using)

create a synonym and flag it for use in our displays (see website tickets [1623](https://github.com/pombase/website/issues/1623), [1624](https://github.com/pombase/website/issues/1624), and [1625](https://github.com/pombase/website/issues/1625)).

@kimrutherford - this ticket is a good place to put the list of PR:nnn IDs

**Comment by kimrutherford** [comment]
I've attached the IDs that are in use, queried from Chado.

The easy solution to the display issue (for me at least) is to edit the term names in the mini-OBO file.  That would mean no code changes and no special cases.  The down side is that the PRO term names in Chado won't be the official term names.

The second easiest solution is to add synonyms but give them a unique synonym type like "DISPLAY", eg.
```
synonym: "Spom-ste11/UnMod" DISPLAY [POMBASE:kmr]
```
That would make the synonyms very easy to pull out for display.

The other options are more... challenging.

[pro_terms_in_annotations.txt](https://github.com/pombase/curation/files/5387941/pro_terms_in_annotations.txt)

**Comment by ValWood** [comment]
Well the good thing is that there are not so many!

If we need this - others will too, and that is a good argument  for PRO to include such a label  for display. It  seems a bit bonkers that we need to maintain a file of biologist-friendly labels.
@nataled?  do you think we could persuade PRO to include such label (basically we want a very contracted label with gene name+modified residue). 

You can see some of the historical discussion in the linked tickets.
v

**Comment by nataled** [comment]
What you are describing (in general) is what we call the PRO-short-label, developed precisely for display purposes. However, the short label as it is does not attempt to indicate the modified residues, for several reasons:

1) The result will often be not short at all, as it will depend on the number of positions modified
2) Not all modified positions are absolute. Consider PR:000044738 ("DNA-directed RNA polymerase II subunit rpb1 phosphorylated 5 (Schizosaccharomyces pombe)"), defined as "A DNA-directed RNA polymerase II subunit rpb1 (Schizosaccharomyces pombe) that has been post-translationally modified to include phosphoserine at position 2 of one or more C-terminal heptad repeats (YSPTSPS)."

That being said, I attempted to make what you refer to as a display name for cases where positional information is known. Please see attached spreadsheet.
[PomBase_PRO.xlsx](https://github.com/pombase/curation/files/5396555/PomBase_PRO.xlsx)

One other thing: the identifier given for 'protection of telomeres protein tpz1 sumoylated 1 (Schizosaccharomyces pombe 972h-)' is for something else. Please use PR:000050457.

**Comment by mah11** [comment]
@nataled 
Thanks! I'll fix the tpz1 ID. 

> The result will often be not short at all, as it will depend on the number of positions modified

I think we're less concerned about absolute length of the string, and more with finding a balance between conciseness and specificity. We're aiming for somethingf that's less wordy than, say, PR:000049980's "DNA repair protein rad9 phosphorylated 1 (Schizosaccharomyces pombe)" and that indicates the modified position(s) where that's realistic. We also don't want to force a user to do a separate lookup to find that the difference between Spom-rad9/Phos:1 and Spom-rad9/Phos:2 is phosphorylation on S423 vs. T412.

> Not all modified positions are absolute. Consider PR:000044738 ("DNA-directed RNA polymerase II subunit rpb1 phosphorylated 5 (Schizosaccharomyces pombe)"

We're well aware that the RNA Pol II CTD is a special case, and that there are a few others, but we don't want those cases to stop us coming up with biologist-friendly display text. I'll craft some display strings for the woollier cases.

**Comment by mah11** [comment]
@ValWood @kimrutherford 
If the display synonyms from Darren look good, I'll add them to our local pombe_mini_PR.obo file.

@kimrutherford 
> The second easiest solution is to add synonyms but give them a unique synonym type

I was already planning to go the Option 2 route (editing term names in an external ontology would be a non-starter for both logical/technical and good-citizenship reasons).

Note that the all-caps item isn't the synonym *type*, it's the synonym *scope*, i.e. one of EXACT|RELATED|BROAD|NARROW, and I don't plan to add anything new to that set. The type will appear after the scope, separated from the scope and the dbxref(s) by spaces. Watch for something like 

`synonym: "crb2/Phos:(T187,T215,T235)" EXACT PomBase_display_name [PomBase:mah]`

**Comment by ValWood** [comment]
Looks good to me!

**Comment by kimrutherford** [comment]
> The type will appear after the scope

Those types are ignored when loading OBO files because there is no field in Chado to store them in.

**Comment by mah11** [comment]
>> The type will appear after the scope
> 
> Those types are ignored when loading OBO files because there is no field in Chado to store them in.

Drat. How horrible would it be to get them into our web pages somehow, either by adapting Chado or bolting them on "afterwards"? What do other ontologies do? (And how t f has Chado lasted this long - everywhere, not just PomBase - without accommodating synonym types? They've been around for at least 15 years. ... OK, rant over.)

I really do not want to try to stuff a type into the scope field, because it would be appallingly bad practice.

**Comment by kimrutherford** [comment]
> How horrible would it be to get them into our web pages somehow, either by adapting Chado or bolting them on "afterwards"?

I'll write a script to process the OBO file into a form for loading into Chado.  Probably I'll replace the term name with the PomBase_display_name synonym so there are no special cases in the Chado loading code or the website code.

> And how t f has Chado lasted this long - everywhere, not just PomBase - without accommodating synonym types?

I assume nobody has needed them.  It has taken 9 years for us to have a use case.

**Comment by mah11** [comment]
I made some additions and other changes - see cells in pretty colors. From now on, I'm going to do edits in the local obo file and not try to keep spreadsheets in sync.
[PomBase_PRO-3_mah-2020-10-19.xlsx](https://github.com/pombase/curation/files/5403240/PomBase_PRO-3_mah-2020-10-19.xlsx)

**Comment by mah11** [comment]
I've updated the pombe_mini_PR.obo file with the new display synonyms.

>  Probably I'll replace the term name with the PomBase_display_name synonym so there are no special cases in the Chado loading code or the website code.

Can't quite bring myself to cheer for this, but I am entirely willing to look the other way so we can show sensible descriptions without reinventing half the pombase code. :wink:

**Comment by ValWood** [comment]
Yeah it isn't sustainable.
Where doe the miniPRO live. Can I edit it easily? I will be adding lots of these...

**Comment by mah11** [comment]
> Where doe the miniPRO live?

svn - Artemis/pombe-embl/mini-ontologies/pombe_mini_PR.obo

> Can I edit it easily?

That kind of depends on what you'd find "easy" ... but if it looks daunting, you can always pop a list of additions here (or in a new ticket). All I really need is the PR:nnn ID and the display synonym you want, and I can munge that into obo file additions.

**Comment by nataled** [comment]
@mah11 I believe you'll want to change PR:000037299 to "cds1/Phos:(T11) dimer". Also, be aware that the change made to PR:000027533 (from Spom-prz1/Phos:1 to prz1/PhosRes+) could potentially cause duplication of display label. That's because in PRO "PhosRes+" would specifically mean the prz1 is phosphorylated at least once, while "Phos:1" means that there are either known sites, known ambiguous sites (that is, might be "here or there"), or known conditions under which the modification occurs. This particular example is the latter. At the moment this isn't a problem, but there is a formal possibility that we would create a term of true PhosRes+ form in the future.

@ValWood I wrote a script to create the positional information, so if you have a list of PRO IDs needing such information, please create a ticket for me and I will get the information back to you. At the moment the script isn't fully generalized (that will take quite a bit of work that I won't have time for in the very near future), but I probably can modify on a case by case basis.

**Comment by mah11** [comment]
@nataled 
> I believe you'll want to change PR:000037299 to "cds1/Phos:(T11) dimer"

OK, done

> Also, be aware that the change made to PR:000027533 (from Spom-prz1/Phos:1 to prz1/PhosRes+) could potentially cause duplication of display label ...

Thanks for the heads-up, but I think we'll leave that one as is until we have more forms that need to be disambiguated. Our big concern is that the additional specificity of the "Phos:1"-type designations is totally opaque to our users, so it's worth occasionally doing some manual intervention to create more informative text.

**Comment by kimrutherford** [comment]
I've added the script to process the mini OBO file before loading.

Tonight's load failed due to a typo in PR:000027529.  The synonym value was missing:
```
warning "unknown synonym format: "" EXACT PomBase_display_name [PomBase:curators]
```

I've removed that line in pombe_mini_PR.obo and I'm about to restart the load.

**Comment by kimrutherford** [comment]
> I'm about to restart the load.

Done now.  Seems OK?: https://www.pombase.org/term/GO:0046974

**Comment by ValWood** [comment]
OMG, that's amazing. Very happy with that change. It's so much more humanly parsable ;).  ~I think PomBAse users will really appreciate this.
Thanks all! I thought that would take weeks to implement.

**Comment by mah11** [comment]
>  PR:000027529. The synonym value was missing:
> ...
> I've removed that line in pombe_mini_PR.obo

Thanks. I've committed the file with the missing synonym in place.

**Comment by mah11** [comment]
I'm gonna close this so we can enjoy the sense of accomplishment :wink:

Open new ticket(s) for any more display synonyms you don't want to add yourself.
