### ISSUE TITLE
new spreadsheet for PMID:30726745 modifications

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2854]
I asked "Y-D-Tay for a revised spreadsheet with the amino acid:

[Orb6 dataset curation_final_revised201015.xlsx](https://github.com/pombase/curation/files/5385173/Orb6.dataset.curation_final_revised201015.xlsx)

**Comment by mah11** [comment]
What is the task?

**Comment by ValWood** [comment]
I forwarded the e-mail. If it's straightforward we don't need to bother KIM. Its the phosphosites that show up without the AA residue.

**Comment by mah11** [comment]
It's not all of them; there's one other paper mentioned in https://github.com/pombase/pombase-chado/issues/758

**Comment by mah11** [comment]
both done

**Comment by ValWood** [comment]
Excellent, and an old ticket got closed ;)
