### ISSUE TITLE
vps74/gpp74 name question

### ISSUE THREAD

**Issue by mah11** [pombase/curation#2855]
PMID:32918581 uses the name gpp74 for vps74/SPAC5D6.13, on the grounds that the deletion has no effect on vacuolar protein sorting, but does cause some Golgi localization to go awry. I'm adding a synonym now, but should we swap and use gpp74 as the primary name now that it's been published that way?

**Comment by ValWood** [comment]
Yes switch 'em. The vps labels  all come from early screens and some are very far away from vacuolar protein sorting, histone chaperones and mitochondrial protein. So they are often pretty confusing.

**Comment by mah11** [comment]
done; cheers
