### ISSUE TITLE
MAPK pathway  annotate  atf4 substrates and inhibition of pmk1

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2857]
<img width="295" alt="Screenshot 2020-10-15 at 18 47 57" src="https://user-images.githubusercontent.com/7359272/96238192-1febf300-0f96-11eb-870c-4bc85722c6e3.png">

**Comment by ValWood** [comment]
These atf1 targets are also missing

**Comment by ValWood** [comment]
and inhibition of pmk1 by pyp1/2

**Comment by ValWood** [comment]
and inhibition of pmk1 by ptc2/3

**Comment by Antonialock** [comment]
Fungal phosphorelays have three components (bacteria have two), i think this is how it happens:
1. Mak 1/2/3 are autophosphorylates on on a histidine, and then transfers the phosphate to an asp residue on itself
2. The phosphate is relayed to a histidine in the 'shuttle protein' Mpr1 (this protein is not present in bacteria), 
3, the phosphate is relayed to an Asp residue in the response regulator Mcs4

it looks like the GO terms are specific to bacteria....maybe we need a fungal version of this pathway? 
"The two-component sensor is a histidine kinase that autophosphorylates a histidine residue in its active site. The phosphate is then transferred to an aspartate residue in a downstream response regulator, to trigger a response."

**Comment by ValWood** [comment]
@Antonialock  but what is the activity of mcs4?

**Comment by Antonialock** [comment]
I don't know, maybe it just causes a conformational change in bound proteins?

**Comment by ValWood** [comment]
protein kinase activator activity !
(SGD used)

**Comment by ValWood** [comment]
mcs4 targets are done. Still need to do:

atf1 targets
inhibition of pmk1 by pyp1/2
inhibition of pmk1 by ptc2/3

**Comment by ValWood** [comment]
or We have recently shown that Pyp1, Pyp2, and Ptc1, whose transcriptional activation is dependent on Sty1– Atf1 function, interact also with Pmk1 in vivo and may participate in its dephosphorylation, thus providing a first evidence for the existence of “cross-talk” between the two MAP kinase (MAPK) pathways in S. pombe (Madrid et al., 2007).

**Comment by ValWood** [comment]
Hi @JackyVH PMID:19625445 reports pck2 as 'short'. I was going to classify as wee but it seems odd that this never came up in yours or Fran's screen. Do you think these cells are not small but stubby?
To me here they look shorter, but n to really wider. What do you think?
It's figure 1
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2743619/

**Comment by ValWood** [comment]
In fission yeast the stress-induced expression of pyp1􏰅 and pyp2􏰅 genes is regulated by Sty1 through Atf1 forming a negative-feedback loop (Degols et al., 1996; Shiozaki and Russell, 1996; Wilkinson et al., 1996

**Comment by ValWood** [comment]
Under moderate to high concentrations of hy- drogen peroxide (naturally occurring, for example, in re- sponse to glucose arrest) nuclear accumulation of Pap1 is delayed until the expression of Atf1-dependent genes pro- motes its conversion to the active oxidized conformation that translocates into the nucleus and enhances Pap1-depen- dent gene expression (Madrid et al., 2004; Vivancos et al., 2006).

what is responsible for the activation of pap1?

**Comment by ValWood** [comment]
see
https://github.com/pombase/curation/issues/2900
