### ISSUE TITLE
cdc15/cut12  PRO request?

### ISSUE THREAD

**Issue by mah11** [pombase/curation#2860]
I have removed the "column_17 PR:000044734" entry from the cdc15 GO:0106006 annotation from PMID:29343550 (canto session 1068c5e5c8e4b6df; pre-edit annotation in screenshot below). It made no sense, because PR:000044734 is not a specific isoform or modified form of cdc15 -- in fact, it's neither cdc15 nor isoform-specific; it's non-form-specific cdc12.

I'm also not sure what cdc15 isoform to request from PRO, hence this ticket.

![PMID_29343550_cdc15_before_edit](https://user-images.githubusercontent.com/5196259/96474999-660db480-122b-11eb-9498-79e27dff891b.png)

**Comment by ValWood** [comment]
It should be has_input
cdc15 anchors the unmodified cdc12 (I think) but I will double check that

**Comment by mah11** [comment]
OK, thanks. Looks like one of us will have to request unmodified cdc12 ...

**Comment by ValWood** [comment]
I can do that, I'm working on this sporadically...

**Comment by mah11** [comment]
great - that lets me get PRO stuff off my plate for a while (just committed display synonyms ...)

**Comment by ValWood** [comment]
requested PRO term

**Comment by ValWood** [comment]
Corrected to:
![Uploading Screenshot 2020-11-13 at 13.12.05.png…]()
