### ISSUE TITLE
PAINT functions and components and process checking

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2870]
- [x] 1,3-beta-glucanosyltransferase activity	GO:0042124	5
- [x] actin binding	GO:0003779	46
- [x] ATPase activity	GO:0016887	221
- [x] catalytic activity, acting on a protein	GO:0140096	522
- [x] catalytic activity, acting on a tRNA	GO:0140101	102
- [x] catalytic activity, acting on DNA	GO:0140097	119
- [x] catalytic activity, acting on RNA	GO:0140098	378
- [x] cell adhesion mediator activity	GO:0098631	14
- [x] cyclase activity	GO:0009975	3
- [x] deacetylase activity	GO:0019213	15
- [x] disulfide oxidoreductase activity	GO:0015036	21
- [x] DNA-binding transcription factor activity	GO:0003700	99
- [x] enzyme regulator activity	GO:0030234	238
- [x] exonuclease activity	GO:0004527	48 (probably some more to weed out here)
- [x] general transcription initiation factor activity	GO:0140223	57
- [x] GTPase activity	GO:0003924	75
- [x] guanyl-nucleotide exchange factor activity	GO:0005085	41
- [x] histone demethylase activity	GO:0032452	10
- [x] hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds	GO:0016810	69
- [x] hydrolase activity, acting on ester bonds	GO:0016788	271
- [x] hydrolase activity, acting on glycosyl bonds	GO:0016798	59
- [x] intramembrane lipid transporter activity	GO:0140303	9
- [x]  isomerase activity	GO:0016853	73
- [x] kinase activity	GO:0016301	197
- [x] ligase activity	GO:0016874	107
- [x] lipid binding	GO:0008289	115
- [x] lipid transfer activity	GO:0120013	21
- [x] lyase activity	GO:0016829	83
- [x] microtubule binding	GO:0008017	36
- [x] molecular adaptor activity	GO:0060090	351
- [x] molecular carrier activity	GO:0140104	27
- [x] motor activity	GO:0003774	18
- [x] nucleocytoplasmic carrier activity	GO:0140142	15
- [x] nucleoside-triphosphate diphosphatase activity	GO:0047429	5
- [x] nucleotidyltransferase activity	GO:0016779	97
- [x] oxidoreductase activity	GO:0016491	293
- [x]  peptidase activity	GO:0008233	141
- [x] peptide N-acetyltransferase activity	GO:0034212	17
- [x] peroxiredoxin activity	GO:0051920	5
- [x] pheromone activity	GO:0005186	4
- [x] phosphoprotein phosphatase activity	GO:0004721	39
- [x] phosphotransferase activity, for other substituted phosphate groups	GO:0016780	13
- [x] protein deacetylase activity	GO:0033558	12
- [x] protein kinase activity	GO:0004672	121
- [x] protein methyltransferase activity	GO:0008276	38
- [x] protein sequestering activity	GO:0140311	5
- [x] protein tag	GO:0031386	10
- [x] protein transporter activity	GO:0140318	20
- [x] signal sequence binding	GO:0005048	22
- [x] signaling receptor activity	GO:0038023	9
- [x] structural molecule activity	GO:0005198	315
- [x] topological DNA entrapment activity	GO:0061776	6
- [x] transcription coactivator activity	GO:0003713	55
- [x] transcription coregulator activity	GO:0003712	85
- [x] transcription elongation regulator activity	GO:0003711	11
- [x] transferase activity, transferring acyl groups	GO:0016746	98
- [x] transferase activity, transferring aldehyde or ketonic groups	GO:0016744	3
- [x] transferase activity, transferring alkyl or aryl (other than methyl) groups	GO:0016765	37
- [x] transferase activity, transferring glycosyl groups	GO:0016757	95
- [x] transferase activity, transferring nitrogenous groups	GO:0016769	23
- [x] transferase activity, transferring one-carbon groups	GO:0016741	121
- [x] transferase activity, transferring sulfur-containing groups	GO:0016782	14
- [x] translation factor activity, RNA binding	GO:0008135	58
- [x] transmembrane transporter activity	GO:0022857	303
- [x] ubiquitin-like protein transferase activity	GO:0019787	104
- [x] unfolded protein binding	GO:0051082	54

**Comment by ValWood** [comment]
actin cortical patch | GO:0030479 | 52
actin cytoskeleton | GO:0015629 | 111
cell cortex | GO:0005938 | 223
cell surface | GO:0009986 | 75
cell wall | GO:0005618 | 59
chromosome | GO:0005694 | 557
contractile ring | GO:0070938 | 50
cytoplasmic stress granule | GO:0010494 | 37
cytoplasmic vesicle | GO:0031410 | 209
cytosol | GO:0005829 | 2326
cytosolic ribosome | GO:0022626 | 202
division septum | GO:0000935 | 38
endoplasmic reticulum | GO:0005783 | 566
endoplasmic reticulum membrane | GO:0005789 | 234
endosome | GO:0005768 | 130
extracellular region | GO:0005576 | 27
Golgi apparatus | GO:0005794 | 371
kinetochore | GO:0000776 | 69
microtubule cytoskeleton | GO:0015630 | 251
mitochondrion | GO:0005739 | 773
mitotic spindle | GO:0072686 | 97
nuclear periphery | GO:0034399 | 52
nuclear pore | GO:0005643 | 56
nucleolus | GO:0005730 | 370
nucleoplasm | GO:0005654 | 290
nucleus | GO:0005634 | 2720
P-body | GO:0000932 | 36
peroxisome | GO:0005777 | 33
phagophore assembly site | GO:0000407 | 29
plasma membrane | GO:0005886 | 318
preribosome | GO:0030684 | 102
prospore membrane | GO:0005628 | 32
spindle pole body | GO:0005816 | 157
vacuole | GO:0005773 | 218

**Comment by ValWood** [comment]
- [x] actin cytoskeleton organization | GO:0030036 | 122 | esyN
apoptotic process | GO:0006915 | 15 | esyN
- [x]  ascospore formation | GO:0030437 | 60 | esyN
- [ ]  autophagy | GO:0006914 | 70 | esyN
- [ ] carbohydrate metabolic process | GO:0005975 | 149 | esyN
- [ ] cell adhesion | GO:0007155 | 23 | esyN
- [ ] cell wall organization or biogenesis | GO:0071554 | 117 | esyN
- [x] cellular amino acid metabolic process | GO:0006520 | 193 | esyN
- [ ] chromatin organization | GO:0006325 | 269 | esyN
- [ ] conjugation with cellular fusion | GO:0000747 | 100 | esyN
- [ ] cytoplasmic translation | GO:0002181 | 486 | esyN
- [x] detoxification | GO:0098754 | 86 | esyN
- [x] DNA recombination | GO:0006310 | 147 | esyN
- [x] DNA repair | GO:0006281 | 214 | esyN
- [x] DNA replication | GO:0006260 | 125 | esyN
- [ ] establishment or maintenance of cell polarity | GO:0007163 | 85 | esyN
- [x] generation of precursor metabolites and energy | GO:0006091 | 134 | esyN
- [x] iron-sulfur cluster assembly | GO:0016226 | 26 | esyN
(2 seem to be post assembly -check)
- [x] lipid metabolic process | GO:0006629 | 250 | esyN
- [x] meiotic drive | GO:0110134 | 21 | esyN
- [x] meiotic nuclear division | GO:0140013 | 158 | esyN
- [x] membrane organization | GO:0061024 | 175 | esyN
- [ ] metal ion homeostasis | GO:0055065 | 74 | esyN
- [x] microtubule cytoskeleton organization | GO:0000226 | 91 | esyN
- [x] mitochondrial gene expression | GO:0140053 | 184 | esyN
- [x] mitochondrion organization | GO:0007005 | 178 | esyN
- [x] mitotic cytokinesis | GO:0000281 | 81 | esyN
- [x] mitotic sister chromatid segregation | GO:0000070 | 185 | esyN
- [x]  mRNA metabolic process | GO:0016071 | 312 | esyN
- [ ] nitrogen cycle metabolic process | GO:0071941 | 17 | esyN
- [ ] nucleobase-containing small molecule metabolic process | GO:0055086 | 198 | esyN
- [x] nucleocytoplasmic transport | GO:0006913 | 120 | esyN
- [ ] organelle localization by membrane tethering | GO:0140056 | 50 | esyN
- [ ] peroxisome organization | GO:0007031 | 24 | esyN
- [ ] protein catabolic process | GO:0030163 | 268 | esyN
- [ ] protein folding | GO:0006457 | 90 | esyN
- [x] protein glycosylation | GO:0006486 | 76 | esyN
- [x] protein maturation | GO:0051604 | 85 | esyN
- [ ] protein modification by small protein conjugation or removal | GO:0070647 | 206 | esyN
- [ ] protein targeting | GO:0006605 | 130 | esyN
- [ ]  protein-containing complex assembly | GO:0065003 | 428 | esyN
- [x] pteridine-containing compound biosynthetic process | GO:0042559 | 13 | esyN
- [x]  regulation of mitotic cell cycle phase transition | GO:1901990 | 175 | esyN
- [x] regulation of transcription, DNA-templated | GO:0006355 | 438 | esyN
- [x] ribosome biogenesis | GO:0042254 | 380 | esyN
- [x] secondary metabolic process | GO:0019748 | 10 | esyN
- [ ] signaling | GO:0023052 | 408 | esyN
- [x] snoRNA metabolic process | GO:0016074 | 25 | esyN
- [x] snRNA metabolic process | GO:0016073 | 26 | esyN
- [ ] sulfur compound metabolic process | GO:0006790 | 126 | esyN
- [x] telomere organization | GO:0032200 | 56 | esyN
- [x] tetrapyrrole metabolic process | GO:0033013 | 16 | esyN
- [x] transcription, DNA-templated | GO:0006351 | 450 | esyN
- [x] transmembrane transport | GO:0055085 | 347 | esyN
- [x] tRNA metabolic process | GO:0006399 | 172 | esyN
- [x] ubiquinone biosynthetic process | GO:0006744 | 16 | esyN
- [ ] vesicle-mediated transport | GO:0016192 | 341 | esyN
- [x] vitamin metabolic process | GO:0006766 | 46 | esyN

**Comment by ValWood** [comment]
@pgaudet
@marcfeuermann

These are the lists I checked. I think I will have caught most stuff.

**Comment by ValWood** [comment]
Also checked signalling. Closing now....

**Comment by marcfeuermann** [comment]
Thanks Val,
Nice job and helped a lot to improve the PAINT annotation. I will be on vacation next week, but we should be able to complete the updates soon after.
Stay healthy.
Best regards,
Marc.

**Comment by ValWood** [comment]
Enjoy your break. The PAINT is looking really good!
