### ISSUE TITLE
signal transduction involved in.....

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#289]
We need GO terms to be able to distinguish general regulation from regulation via signal transduction pathways

For example, the cell cycle can be regulated by via mechanisms involving regulation of nuclear export, regulating some aspects of metabolism
or more directly by the major cell cycle regultors \(i.e signal transduction\).
So then we would need
signal transduction involved in regulation of mitotic cell cycle 
child of reguation of mitotic cell cycle
and
signal transduction

\(To retrieve cell cycle regulators as a set you need to query all
signal transduction AND regulation of mitotic cell cycle
but means that this set is not avaialable to enrichment analyses\)

I am requesting this term now, but we will need to request terms to cover the minimally the high level processes for which signal transduction pathways \(or molecules\) have been identified.

http://old.genedb.org/amigo-cgi/term-assoc.cgi?term=GO:0007165&session\_id=7897amigo1314286083

Original comment by: ValWood

**Comment by ValWood** [comment]
On my GO list
