### ISSUE TITLE
missing GO annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2899]
These 29 identifiers were found to be unannotated: Systematic ID SPBC32H8.03 SPCC622.21 SPBC27.04 SPCC663.02 SPCC736.05 SPBC21C3.07c SPCC285.07c SPCC1906.04 SPCC1183.10 SPCC1281.08 SPCC663.17 SPCC970.11c SPCC1450.08c SPCC794.02 SPAC12G12.16c SPAC1F7.06 SPCC1620.02 SPCC1739.15 SPBC354.08c SPAC11D3.13 SPCC162.04c SPBC649.05 SPAC144.19 SPCC548.03c SPBC3H7.11 SPCC1919.06c SPCC1906.03 SPBC947.09

**Comment by mah11** [comment]
What's that from? There are annotations for all of those genes in the GAF, although some are NDs.

**Comment by ValWood** [comment]
It's from
https://github.com/geneontology/go-annotation/issues/3305
so it might now be rectified by the addition of PAINT annotations....

Looking at the heading I think this was a GO term slimmer output.

**Comment by ValWood** [comment]
Out of date anyway

**Comment by mah11** [comment]
PAINT doesn't really explain it ... there's quite a mix of sources & dates.
[curation_2899_gaf.txt](https://github.com/pombase/curation/files/5567659/curation_2899_gaf.txt)

**Comment by ValWood** [comment]
Yeah but I had already targetted some of them for annotation from other tickets. Cut12, for example I annoted recently, as it had no process annotation.

 It is definitely GO term slimmer output, so I will reslim  to check.

**Comment by ValWood** [comment]
from https://go.princeton.edu/cgi-bin/GOTermMapper
today 

These 28 identifiers were found to be unannotated: SPBC32H8.03 SPAC144.19 SPCC1183.10 SPCC1739.15 SPCC162.04c SPCC663.17 SPBC649.05 SPCC622.21 SPCC794.02 SPCC1450.08c SPAC1F7.06 SPCC1620.02 SPCC736.05 SPBC21C3.07c SPCC1919.06c SPBC354.08c SPAC12G12.16c SPBC27.04 SPCC548.03c SPCC663.02 SPCC1906.03 SPCC1906.04 SPBC3H7.11 SPCC285.07c SPAC11D3.13 SPBC947.09 SPCC1281.08 SPCC970.11c

**Comment by ValWood** [comment]
This is weird. I queried cut12 with Marc because it wasn't coming in the slim. 
Marc responded that it isn't in the GO database. Then I noticed that it is one of these...
SPBC649.05

**Comment by ValWood** [comment]
GO term finder issue. In resolution.
