### ISSUE TITLE
possible annotation for unknowns

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2902]
Although one statement in this paragraph is incorrect! this  dataset provides  strong functional clues for some of the unknowns. 

<img width="440" alt="Screenshot 2020-11-26 at 15 26 21" src="https://user-images.githubusercontent.com/7359272/100368693-cc8cac00-2ffb-11eb-9edd-0890c20c4c30.png">

Multiplexed proteome profiling of carbon source perturbations in two yeast species with SL-SP3-TMT
PMID: 31626996

@bahler

**Comment by bahler** [comment]
Interesting, thanks Val!

Cheers,
-Jürg

**Comment by ValWood** [comment]
I had a quick scan of this and I think we can do 2 HTP phenotype spreadsheets.

increased protein level on pyruvate carbon source
decreased protein level on pyruvate carbon source.

However, I don't see these lists, they seem to provide only a summary table so I'll ask the authors for the 2 lists.

**Comment by ValWood** [comment]
mailed the author

**Comment by ValWood** [comment]
this was done:
https://www.pombase.org/reference/PMID:31626996
