### ISSUE TITLE
file conversion required to add possible disease genes via SGD

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2905]
more potential  diesase genes, from SGD/ SGDAlliance

I will supply both lists as there is not much overlap between them?

user-34-187:Desktop val$ cut -f4 DiseaseAnnotationDataDump.20190116.tsv |sort |uniq |wc
     210     

user-34-187:Desktop val$ cut -f2 alliance_SGD_diseases_downloads.txt |sort|uniq|wc 
     232    

catted togetether
user-34-187:Desktop val$ cat tmp1 tmp2 |sort |uniq |wc
     419     

???

[alliance_SGD_diseases_downloads.txt](https://github.com/pombase/pombase-chado/files/2775350/alliance_SGD_diseases_downloads.txt)
[DiseaseAnnotationDataDump.20190116.txt](https://github.com/pombase/pombase-chado/files/2775351/DiseaseAnnotationDataDump.20190116.txt)

 - [ ]  @kimrutherford  could you take the  SGD gene names (no orf names, unfortunately)

column 4 in DiseaseAnnotationDataDump.20190116.tsv
column 2 in  alliance_SGD_diseases_downloads.txt

convert to  SGD orf names, pull our pombe ortholog names.

We can then easily upload the list and intersect with our disease annotated to see if we can pick up any more.

**Comment by ValWood** [comment]
Hi KIm,
I would like to do this now.
In summary we have a file and I would like to check that we have all the gene associations covered.
https://www.alliancegenome.org/downloads
we can check the files for human and  for yeaset.

Essentalli all I want is the rows from these files   where the pombe orthologs do not have disease associations. I would be able to do it in the query builder upload but
the S. cerevisiae file provides these IDs
SGD:S000000037	CYC3
which are not accepted by the upload.

**Comment by ValWood** [comment]
From the human file we should use anything with "is_implicated_in"
the other tags are for bio markers (and strangely, for orthology??)

**Comment by kimrutherford** [comment]
> I would be able to do it in the query builder upload but the S. cerevisiae file provides these IDs
> SGD:S000000037 CYC3
> which are not accepted by the upload.

It's worth trying the gene names in the new ID mapper:
http://dev.pombase.kmr.nz/identifier-mapper

Select "S. cerevisiae" from the drop-down and then on the results page click "Send matching S. pombe gene list to the advanced search"

**Comment by ValWood** [comment]
Yes I was looking for that! It will be a good test!

**Comment by ValWood** [comment]
I might have encountered a bug.
I tried with this file: (HGNC:ID's)

The file uploads bu the buttons stay greyed out.

[human_disease_IDs.txt](https://github.com/pombase/curation/files/5714688/human_disease_IDs.txt)

**Comment by ValWood** [comment]
It might just be slow?
this is the same file ex-duplicates
[human_disease_IDs_2.txt](https://github.com/pombase/curation/files/5714701/human_disease_IDs_2.txt)

**Comment by ValWood** [comment]
Wow, that's embarrassing. Alliance only has 4470 *human* genes with disease mappings!

**Comment by ValWood** [comment]
That might be corrrect. I think its ~15,000 diseases, but they might map to only ~4000 genes...

**Comment by ValWood** [comment]
Is this ID form acceptable?

HGNC:10001
HGNC:10004
HGNC:10006

(should specify in the drop down)

**Comment by ValWood** [comment]
I got it to work with names..... IDs will be better because the names change a lot and they will be classed as "Not found" if out of date

**Comment by kimrutherford** [comment]
> I might have encountered a bug.

Yep, it's a bug.  If you load from a file it doesn't enable the lookup button until you edit the list in some way, even just by adding a space.  I'll work on fixing that.

**Comment by kimrutherford** [comment]
> Is this ID form acceptable?

Yep.  I tried your file (human_disease_IDs.txt) and it worked after I added a space in the box.

**Comment by kimrutherford** [comment]
> Yep. I tried your file (human_disease_IDs.txt) 

http://dev.pombase.kmr.nz/results/from/id/a0739ec3-4d58-43ca-bc0b-3ad7e09ed017

**Comment by ValWood** [comment]
Also, I had a one  blank line in a file and that failed too.

**Comment by ValWood** [comment]
Also, it might be worth parking the unmapped IDs in a list. Otherwise it is difficult to see the results if you have a lot of unmapped IDs:

<img width="1234" alt="Screenshot 2020-12-18 at 09 23 06" src="https://user-images.githubusercontent.com/7359272/102605769-b31fe100-411d-11eb-8e0b-3c388773e461.png">

**Comment by kimrutherford** [comment]
> Also, I had a one blank line in a file and that failed too.

In what way did it fail?

**Comment by ValWood** [comment]
The button was still greyed out I think. I scrolled down tot he bottom of the list  and removed a blank line.

**Comment by kimrutherford** [comment]
> The button was still greyed out I think. I scrolled down tot he bottom of the list and removed a blank line.

Sounds like it might be the same bug.

**Comment by ValWood** [comment]
So I also reied with this file for SGD, but this doesn't work right now:

[Yeast_names_disease_alliance.txt](https://github.com/pombase/curation/files/5715744/Yeast_names_disease_alliance.txt)
(no blank lines in this file)

and I tried with
SGD:S000000671
but that didn't work

**Comment by kimrutherford** [comment]
> So I also tried with this file for SGD, but this doesn't work right now:

In what way didn't it work?  I've now fixed the bug that caused the lookup button to be greyed out if you upload a file.

> SGD:S000000671

We don't load those IDs at the moment.

**Comment by kimrutherford** [comment]
> Also, it might be worth parking the unmapped IDs in a list.

I'm not sure what you mean by parking in a list.

Would it make sense to have something like this instead of showing the full list:

```
  42 identifiers could not be found, view ...
```
and make "view ..." a link/button that expands the list?

**Comment by ValWood** [comment]
yes, that's what I meant, have them in a linked list so you don't miss the results.

**Comment by kimrutherford** [comment]
I've implemented a compromise:

![Screenshot from 2020-12-22 17-37-47](https://user-images.githubusercontent.com/90474/102850298-068d7a00-4411-11eb-82bf-e4ea11756398.png)

Is that OK?

We should probably move the discussion to: https://github.com/pombase/website/issues/1539

**Comment by ValWood** [comment]
perfect!

**Comment by kimrutherford** [comment]
Can we close this?

**Comment by ValWood** [comment]
yep!
