### ISSUE TITLE
QC: check whether allele names are unique genome wide

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#2906]
They might not be any, but we can disambiguate if we find out how many there are.

Original comment by: ValWood

**Comment by mah11** [comment]
All of the lists in older comments are out of date now.

The Canto logs flag cases where one allele name has been used with more than one description - 'description for new allele "yada'" does not match the existing allele with the same name "yada2"'. I've fixed various things for that check over the past months (maybe years), including one today, which leaves just one outstanding name:

    warning in b5b9e2e7b7d1213e: description for new allele "clp1-6A(S396A,S408A,S467A,S468A,S493A,S513A)" does not match the existing allele with the same name "clp1-6A(S187A,T363A,T382A,T388A,T453A,S479A)" (from session 3472d1b25692f40c)
    warning in b5b9e2e7b7d1213e: description for new allele "clp1-6A(S396A,S408A,S467A,S468A,S493A,S513A)" does not match the existing allele with the same name "clp1-6A(S187A,T363A,T382A,T388A,T453A,S479A)" (from session 3472d1b25692f40c)
    warning in b5b9e2e7b7d1213e: description for new allele "clp1-6A(S396A,S408A,S467A,S468A,S493A,S513A)" does not match the existing allele with the same name "clp1-6A(S187A,T363A,T382A,T388A,T453A,S479A)" (from session 3472d1b25692f40c)

I checked the papers, and it looks like `clp1-6A` really has been published as the name for two different sets of 6 something-to-alanine substitutions. Dunno how you want to resolve that!

**Comment by ValWood** [comment]
I see clp1-6A (S187A, T363A, T382A, T388A, T453A, S479A aa) 
but I don't see a different one?

**Comment by mah11** [comment]
Where are you looking? Only one description reaches pombase pages, but in Canto there are two sessions with different descriptions.

**Comment by ValWood** [comment]
OK PMID:16950131 gets the primary allele name.

PMID:18951025 becomes clp1-6A-b with clp1-6A synonym.

**Comment by ValWood** [comment]
fixed
