### ISSUE TITLE
rad24 target

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2908]
PMID:11818066 

I was hoping I could add this to rad24 but the paper hasn't been through yet.

rad24 sequesters mei2 (phosphorylated by pat1) from meiRNA prior to meiosis I

rad24 sequesters mei2 (phosphorylated by pat1) from ? prior to premeiotic DNA replication

**Comment by ValWood** [comment]
One for the New Year

**Comment by mah11** [comment]
Curation done (BioGRID did the interactions); @Antonialock if you have time to check the annotations it won't hurt a bit -- I don't know the pombe meiosis stuff as well as you do, and some of the phenotypes did my head in a bit. 

As far as I could tell, the paper doesn't have enough detail to establish the "prior to meiosis I" or "prior to premeiotic DNA replication" of the statements in the ticket summary. That stuff only comes up in the discussion.

Let me know if anything needs to be added or fixed!

https://curation.pombase.org/pombe/curs/9431349797d152cf
