### ISSUE TITLE
BUG annotation in the current gaf appear to be duplicated

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2913]
I was just checking number of EXP GO annotations for Elixir presentation, and it appears to be double. I think everything in the file is currently duplicated?

**Comment by mah11** [comment]
committed a corrected GAF, so it should reach the website tomorrow

**Comment by mah11** [comment]
('twas cruft from testing a script to create a 2.2-compliant file ... which worked, but I forgot to tidy everything up afterward)

**Comment by ValWood** [comment]
I got very excited adding up the annotation numbers then it was like oh, actually this is not  really possible :)
