### ISSUE TITLE
disease mapping fixes

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2919]
- [x] mRNA SPAC644.09.1: can't find new term for Epilepsy, early-onset, vitamin B6-dependent in mapping for mondo: failed to load qualifier 'term=disease associated, Epilepsy, early-onset, vitamin B6-dependent; date=20180910' from SPAC644.09
-> MONDO:0015005

- [x] ncRNA SPNCRNA.214.1: can't find new term for telomere syndromes in mapping for mondo: failed to load qualifier 'term=disease associated, telomere syndromes; date=20180407' from SPNCRNA.214

- [x] mRNA SPAC19B12.10.1: can't find new term for microcephaly-capillary malformation syndrome (MICCAP) in mapping for mondo: failed to load qualifier 'term=disease associated, microcephaly-capillary malformation syndrome (MICCAP); date=20151204' from SPAC19B12.10

- [x] mRNA SPBC29A3.14c.1: can't find new term for telomere syndromes in mapping for mondo: failed to load qualifier 'term=disease associated, telomere syndromes; date=20180407' from SPBC29A3.14c

- [x] mRNA SPBC16A3.11.1: can't find new term for DNA repair-deficiency disorders in mapping for mondo: failed to load qualifier 'term=disease associated, DNA repair-deficiency disorders; date=20160105' from SPBC16A3.11

- [x] mRNA SPCC584.05.1: term 'MONDO:0016021' in mondo is obsolete: failed to load qualifier 'term=disease associated, encephalopathy; db_xref=PMID:24938147; date=20141024' from SPCC584.05

**Comment by ValWood** [comment]
and these !

can't load annotation for SPBC11C11.04c - MONDO:0014964 not found in database
can't load annotation for SPAC25H1.10c - MONDO:0018859 not found in database
can't load annotation for SPBC17A3.01c - MONDO:0016021 not found in database
can't load annotation for SPBC1604.20c - MONDO:0000844 not found in database
can't load annotation for SPBC1685.05 - MONDO:0014988 not found in database
can't load annotation for SPAC23G3.12c - MONDO:0014988 not found in database
can't load annotation for SPAC22G7.06c - MONDO:0016021 not found in database

**Comment by ValWood** [comment]
and these (which I thought I fixed, but maybe there  are 2 things to fix)

could not find cvterm for MONDO:0009314 - maybe obsolete?  Skipping annotation for SPAC17A5.13 / BH4-deficient_hyperphenylalaninemia_A
could not find cvterm for MONDO:0011643 - maybe obsolete?  Skipping annotation for SPAC4F8.07c / diabetes_mellitus_permanent_neonatal
could not find cvterm for MONDO:0014964 - maybe obsolete?  Skipping annotation for SPBC11C11.04c / encephalopathy_progressive_early_onset_with_brain_atrophy_and_thin_corpus_callosum
could not find cvterm for MONDO:0014988 - maybe obsolete?  Skipping annotation for SPAC23G3.12c / 3_methylglutaconic_aciduria_type_viii
could not find cvterm for MONDO:0017959 - maybe obsolete?  Skipping annotation for SPAC4A8.13c / autoinflammation_lipodystrophy_and_dermatosis_syndrome
no MONDO ID for precocious_puberty_central_2 -> MKRN3 (SPAC3A11.02)
no MONDO ID for sifrim_hitz_weiss_syndrome -> CHD4 (SPBP35G2.10)
"not a disease" doesn't look like a MONDO ID - skipping
could not find cvterm for MONDO:0013346 - maybe obsolete?  Skipping annotation for SPAC23A1.12c / neurodevelopmental_disorder_with_brain_liver_and_lung_abnormalities
no MONDO ID for renal_dysplasia_cystic -> BICC1 (SPBC28E12.02)
could not find cvterm for MONDO:0010059 - maybe obsolete?  Skipping annotation for SPAC1A6.01c / spinal_muscular_atrophy_type_i_with_congenital_bone_fractures
could not find cvterm for MONDO:0016021 - maybe obsolete?  Skipping annotation for SPCC1682.09c / epileptic_encephalopathy_early_infantile_15
could not find cvterm for MONDO:0016021 - maybe obsolete?  Skipping annotation for SPBC24C6.06 / epileptic_encephalopathy_early_infantile_15
could not find cvterm for MONDO:0016021 - maybe obsolete?  Skipping annotation for SPAC18B11.11 / infantile_epileptic_encephalopathy
no MONDO ID for brain_small_vessel_disease_with_or_without_ocular_anomalies -> VPS11 (SPAC16A10.03c)
no MONDO ID for idiopathic_central_precocious_puberty -> MKRN3 (SPAC3A11.02)
could not find cvterm for MONDO:0016021 - maybe obsolete?  Skipping annotation for SPBC30D10.11 / epileptic_encephalopathy_early_infantile_15
could not find cvterm for MONDO:0016021 - maybe obsolete?  Skipping annotation for SPAC23C11.04c / epileptic_encephalopathy_early_infantile_15
could not find cvterm for MONDO:0016021 - maybe obsolete?  Skipping annotation for SPAC22A12.13 / epileptic_encephalopathy_early_infantile_15
no MONDO ID for renal_dysplasia_diffuse_cystic -> BICC1 (SPBC28E12.02)

**Comment by ValWood** [comment]
@kimrutherford  first a question. I think these are mainly remappings, so maybe we are missing the replacements. Is the MONDO ontology up to date?

**Comment by ValWood** [comment]
hang on, I think I am still looking at yesterdays log fille...

**Comment by kimrutherford** [comment]
> hang on, I think I am still looking at yesterdays log fille...

The load failed last night because there were some spaces instead of tabs in the disease file.  I've fixed the file for the next load.

**Comment by kimrutherford** [comment]
> Is the MONDO ontology up to date?

Yep, we're using the most recent release from 2020-12-02
