### ISSUE TITLE
gad8 kinase targets

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2926]
abolished protein phosphorylation
  | gad8Δ modified residue T1972 affecting tor1
  | gad8KD (kinase dead mutant) modified residue T1972 affecting tor1

abolished protein phosphorylation during vegetative growth
  | gad8KD (kinase dead mutant) modified residue S1975 affecting tor2

I am having trouble "reading" these annotations.

gad8 is downsteam of tor1
I can't figure out how altering the gad8 kinase can affect the phosphorylation status of an upstream kinase?

@Antonialock can you help? Am I missing something obvious?

**Comment by ValWood** [comment]
Apparently gad8 does Phosphorylate TOR

**Comment by ValWood** [comment]
I do have a question though. How do we decide between annotating the phenotype as abolished/decreased kinase or abolished/decreased phosphorylation?

i.e.
abolished protein kinase activity
  | gad8-T387A (aa) affecting activity of gad8 affecting substrate fkh2
and
abolished protein phosphorylation
  | gad8Δ modified residue T1972 affecting tor1


@mah11  ?

**Comment by ValWood** [comment]
ignore that too.....

**Comment by mah11** [comment]
> How do we decide between annotating the phenotype as abolished/decreased kinase or abolished/decreased phosphorylation?

It depends on the assay. If they assay the activity of a specific kinase (in vitro, or an in vivo setup that's convincingly specific), I use the kinase activity terms; otherwise I use phosporylation.

(Tangent: "[qualifier] protein phosphorylation" all too often really stands in for "[qualifier] level of phosphorylated protein" but I don't have time 'n energy to fight that battle.)

**Comment by Antonialock** [comment]
Yes I agree with Midori. 

I also agree "level of phosphorylated protein" is better than "protein phosphorylation"

**Comment by ValWood** [comment]
yes I realised this after I made the ticket, I meant to close it when I commented.....
