### ISSUE TITLE
revise "cut" terms combining conditions

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2928]
cut during cellular response to hydroxyurea
cut during cellular response to bleomycin
cut during cellular response to ionizing radiation
cut during cellular response to methyl methanesulfonate
cut during cellular response to salt stress
cut during cellular response to streptonigrin

**Comment by mah11** [comment]
I've gone through and converted almost all the "cut during yada response" annotations to cut + conditions. The only paper I didn't do is PMID:23697806, which is Jacky's deletion library screen. Do you want to do that one, or should I just update the PHAF directly?

Either way, once it's done we can open a FYPO ticket to do the obsoletions.

**Comment by ValWood** [comment]
Now you can update the PHAF but might be best to wait until next week to edit this file just to make sure everything worked OK....

**Comment by mah11** [comment]
updated the PHAF and opened a [FYPO ticket](https://github.com/pombase/fypo/issues/3885)
