### ISSUE TITLE
atg43 deletion collection allele update

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2930]
- [x] change allele in bioneer data to
  | atg43 | atg43-1(atg43::kanMX4(nt49-203))

changed pombe-embl/external_data/phaf_files/chado_load/htp_phafs
PMID_23697806_phaf.tsv
cc @kimrutherford incase of chado load problem

SPAC14C4.01c	FYPO:0002177	49-203	Null	975 h+		h+ ura4-D18 leu1-32 ade6-M210		atg43-1		nucleotide deletion	Microscopy	FYECO:0000005,FYECO:0000137	FYPO_EXT:0000001			PMID:23697806	4896	20120101	
SPAC14C4.01c	FYPO:0002060	49-203	Null	975 h+		h+ ura4-D18 leu1-32 ade6-M210		atg43-1		nucleotídeos deletion	Microscopy	FYECO:0000005,FYECO:0000137				PMID:23697806	4896	20120101

**Comment by ValWood** [comment]
Hayles et al 

Also need to update these phenotypes if they used the Pioneer library
Malecki M et al. (2016)
Sideri T et al. (2014)
(But check library version as the deletions might have been updated after publication, I can't remember)

Gregan one is OK as it predates the library (2005)

**Comment by ValWood** [comment]
when I do this ticket I will work through these:
https://github.com/pombase/curation/issues/1038

**Comment by bahler** [comment]
Yes, with auxotrophic markers crossed out

Best,
-Jürg

**Comment by ValWood** [comment]
updated
PMID_27887640_phaf.tsv 
SPAC14C4.01c    FYPO:0000251    49-203          null    972 h-          H1::hygr                                nucleotide deletion     Cell growth assay       FYECO:0000148,FYECO:0000005             FYPO_EXT:0000003                PMID:27887640   4896    2017-03-08    


Also add to allele comments

"bioneer collection atg43 deletion is atg43-1(atg43::kanMX4(nt49-203)"  (pers. comm Li-lin DU but I think we can only add refernces to allele comments?)
