### ISSUE TITLE
Variety of evidence codes in modification files

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#2932]
I noticed today that the modification files in `pombe-embl/external_data/modification_files/` mostly use ECO codes but two use "IDA".  That's not a problem for Chado loading but it seems inconsistent.

| file | code |
|---|----|
| PMID_18257517_modifications.tsv     |   IDA         |
| PMID_21712547_modifications.tsv     |   ECO:0000006 |
| PMID_22633491_modifications.tsv     |   ECO:0001096 |
| PMID_23297348_modifications.tsv     |   ECO:0001096 |
| PMID_24763107_modifications.tsv     |   ECO:0000006 |
| PMID_25720772_modifications.tsv     |   IDA         |
| PMID_26412298_modifications.tsv     |   ECO:0001096 |
| PMID_26537787_modifications.tsv     |   ECO:0001096 |
| PMID_26644575_modifications.tsv     |   ECO:0001096 |
| PMID_27984725_modifications.tsv     |   ECO:0007464 |
| PMID_29996109_modifications.tsv     |   ECO:0007464 |
| PMID_30726745_modifications.tsv     |   ECO:0007464 |
| PMID_32062975_modification.tsv      |   ECO:0007464 |

Here are the current evidence counts for all modifications in Chado for comparision:

| evidence code                                                             | count |
|---------------------------------------------------------------------------|-------|
| Inferred from Sequence or Structural Similarity                           |   101 |
| Inferred from Sequence Model                                              |     2 |
| mass spectrometry evidence                                                |  3202 |
| Traceable Author Statement                                                |     1 |
| tryptic phosphopeptide mapping assay evidence used in automatic assertion | 18370 |
| experimental evidence                                                     |  2091 |
| Inferred from Direct Assay                                                | 14758 |
| Inferred from Mutant Phenotype                                            |     1 |

**Comment by mah11** [comment]
I updated the IDAs to ECO.
