### ISSUE TITLE
 Question about redundancy filtering

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2937]
We have annotated scd1 to 

positive regulation of mating projection assembly.
We are picking up a PAINT mapping to
conjugation with cellular fusion.

But this is redundant with/ancestral to  
positive regulation of mating projection assembly.

<img width="748" alt="Screenshot 2021-01-04 at 14 33 35" src="https://user-images.githubusercontent.com/7359272/103545837-0b830c80-4e9a-11eb-83f2-bb25b039e68b.png">

**Comment by ValWood** [comment]
Also transferring to curation tracker or it will fall of my radar.

**Comment by mah11** [comment]
also see https://github.com/pombase/pombase-chado/issues/838

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/3019
same thing, will be dealt with by a long GO question
