### ISSUE TITLE
New PomGeneEx terms for constitutive and exclusively

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#2939]
Hi Midori.

If we go ahead with using the PomGeneEx terms for all qualitative gene expression annotation (https://github.com/pombase/pombase-chado/issues/802) we'll need two extra terms in `pombase_gene_expression_ontology.obo`.  We're terms to handle:

 - RNA level constitutive
 - RNA level exclusively

They're not used often.  This is what we have in Chado:

  PMID   | cvterm_name |    qualifier     
---------------|-------------|--------------
 null          | RNA level   | exclusively
 null          | RNA level   | exclusively
 PMID:10835385 | RNA level   | constitutive
 PMID:1538696  | RNA level   | constitutive
 PMID:16816948 | RNA level   | constitutive
 PMID:18367542 | RNA level   | exclusively
 PMID:18367542 | RNA level   | exclusively
 PMID:20298435 | RNA level   | exclusively
 PMID:25736293 | RNA level   | exclusively
 PMID:25736293 | RNA level   | exclusively
 PMID:7634333  | RNA level   | exclusively
 PMID:7634333  | RNA level   | exclusively
 PMID:7634333  | RNA level   | exclusively
 PMID:8618924  | RNA level   | constitutive
 PMID:8799335  | RNA level   | constitutive
 PMID:9167972  | RNA level   | exclusively

**Comment by mah11** [comment]
Are these from Artemis/contig files? I'll go and review them. 

I suspect we can use "RNA level unchanged" for "constitutive", but if not I'll add a term.

In any case "exclusively" makes no sense so I'll check what it should be.

**Comment by kimrutherford** [comment]
> Are these from Artemis/contig files?

Yep, looks like it:

  PMID   | cvterm_name |    qualifier     |     source      
---------------|-------------|--------------|--------------------
 null          | RNA level   | exclusively  | chromosome1.contig
 null          | RNA level   | exclusively  | chromosome2.contig
 PMID:10835385 | RNA level   | constitutive | chromosome2.contig
 PMID:1538696  | RNA level   | constitutive | chromosome2.contig
 PMID:16816948 | RNA level   | constitutive | chromosome2.contig
 PMID:18367542 | RNA level   | exclusively  | chromosome3.contig
 PMID:18367542 | RNA level   | exclusively  | chromosome2.contig
 PMID:20298435 | RNA level   | exclusively  | chromosome1.contig
 PMID:25736293 | RNA level   | exclusively  | chromosome1.contig
 PMID:25736293 | RNA level   | exclusively  | chromosome2.contig
 PMID:7634333  | RNA level   | exclusively  | chromosome1.contig
 PMID:7634333  | RNA level   | exclusively  | chromosome1.contig
 PMID:7634333  | RNA level   | exclusively  | chromosome1.contig
 PMID:8618924  | RNA level   | constitutive | chromosome2.contig
 PMID:8799335  | RNA level   | constitutive | chromosome1.contig
 PMID:9167972  | RNA level   | exclusively  | chromosome1.contig

**Comment by mah11** [comment]
OK, I'll chase them up.

**Comment by ValWood** [comment]
> exclusively

I'm intrigued. I have no recollection of this!

**Comment by mah11** [comment]
I've checked them all over, and adjusted the annotations to avoid the need for new terms.
