### ISSUE TITLE
mid1 mini-PRO entry

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2941]
now modified/unmodified  forms

Phosphorylated: PR:000050492 mid1/Phos(S110, S127, S218, S227, S329, S432, S452, S464, S531)
Unphosphorylated: PR:000050493 mid1/UnPhos(S110, S127, S218, S227, S329, S432, S452, S464, S531)

For now, the display labels can be just  P form and Un-P form like cdc15 (I suspect it's a similar scenario)

https://github.com/PROconsortium/PRoteinOntology/issues/225#issuecomment-764986433

**Comment by mah11** [comment]
added
