### ISSUE TITLE
cdc15 active form display name

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2942]
cdc15/UnPhos(S405/T419/T492/S511/S527/S605/S636/S702/S710/S721/S732/S743/S752/S774/S785/S786/S813/S821/S831/S836/S840)

(is it possible to give this the display name  just 
cdc15/UnPhos?)

**Comment by mah11** [comment]
https://github.com/PROconsortium/PRoteinOntology/issues/224

**Comment by mah11** [comment]
OK, I've added PR:000050489 to mini-PRO with just "cdc15/UnPhos" as the display name. I also included another synonym with all the residues, but without the "display name" synonym category, so it'll just sit there in case we do need to show all the specificity -- we won't have to go scrounging around to find the info (I feel clever now).
