### ISSUE TITLE
hem14 disease mapping

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2943]
SPAC1F5.07c

these look like symptoms, remove from hem14 (human  PPOX)
- MONDO:0002203 | constipation disorder | MalaCards | Rappaport N et al. (2017) | 1
- MONDO:0005277 | migraine disorder | MalaCards | Rappaport N et al. (2017)

**Comment by ValWood** [comment]
@kimrutherford  I can't find these in either file gripping with
SPAC1F5.07c or PPOX
(I actually thought I had already removed them, but they are still visible)

**Comment by mah11** [comment]
I find both of those in the malacards_data_for_chado_mondo_ids.tsv file

**Comment by ValWood** [comment]
I think I must have still been in the ortholog directory

anyway I only see this now so I presume things just need to catch up:

malacards_data_for_chado_mondo_ids.tsv:porphyria variegata	porphyria_variegata	Porphyria Variegata	PPOX	MONDO:0008297

**Comment by ValWood** [comment]
I just can't get rid of the constipation or the migraine!

**Comment by kimrutherford** [comment]
> I just can't get rid of the constipation or the migraine!

Yes, awkward.

I think it would make sense when we store a pombe disease assocation to record in Chado which human gene has the Malacards annotation.  That will make it find query to find duplicates and to trace back to the row in the malacards data file when needed.

**Comment by ValWood** [comment]
They are gone, I  was looking too soon. I don't need the human ID, as I can grep on the assigned one. It's all fine.
