### ISSUE TITLE
Human/cerevisiae/pombe genes where paralogs need checking

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#2948]
The list has the pombe genes that are missing human orthologs and the pombe gene paralogs that look OK to help out.  There are about 23 genes that need checking/fixing.

- [x] [genes_with_odd_paralogs.txt](https://github.com/pombase/curation/files/5913998/genes_with_odd_paralogs.txt)

(I think I did these)

**Comment by kimrutherford** [comment]
Here's the same thing for cerevisiae:

[cerevisiae_odd_genes.txt](https://github.com/pombase/curation/files/5914077/cerevisiae_odd_genes.txt)

**Comment by ValWood** [comment]
Oh not so bad, I can do these soon.

**Comment by ValWood** [comment]
I think I fixed akll these. @kimrutherford could you check?
or is it in. a log file?

noote to self,
SPAC22A12.06c	fsh2	FSH2
SPCC1223.08c	dfr1	FSH1,FSH2,DFR1,FSH3
will not be fixed because one paralog is a tandem fusion.

**Comment by kimrutherford** [comment]
There isn't a log file.  I checked by finding all the pombe genes with a human ortholog, then looking up those human orthologs in the ID mapper to see if I get back to the same list of pombe genes.

The only human IDs that look weird are:
NUP133 - orthologs:  nup132 (SPAC1805.04) and nup131 (SPBP35G2.06c)
NUP155 - orthologs:  nup132 (SPAC1805.04)  nup155 (SPAC890.06)  nup131 (SPBP35G2.06c)

The cerevisiae orthologs look OK to me.  Although I noticed these two IDs:
  - ADE5,7
  - ARG5,6

which aren't going to work well in the ID mapper because it assumes that ID can't contain commas.  That's so the user can upload a csv separated list of IDs.

**Comment by ValWood** [comment]
Will fix the human tomorrow.

Yup gene names with commas, not a good idea !  I wonder how other things cope with that? comma separated ids as input are so common...

**Comment by kimrutherford** [comment]
I've thought I'd double check things with a bit of Perl.  That turned out to be sensible because my strategy of just using the ID mapper to look for problems didn't find everything.

For cerevisiae, this looks odd:

```
SPCC417.05c     ACK1,SHC1
SPBC3E7.12c     ACK1,SHC1,SKT5
SPBC1289.01c    SKT5
```

And sorry, quite a few more for human:

```
SPAC4A8.05c     MYH11,MYH9
SPCC645.05c     MYH1,MYH10,MYH11,MYH13,MYH14,MYH15,MYH2,MYH3,MYH4,MYH6,MYH7,MYH7B,MYH8,MYH9

SPBC16D10.06    SLC39A1,SLC39A2,SLC39A3
SPCC126.09      SLC39A1,SLC39A11,SLC39A2,SLC39A3

SPBC19F8.06c    SLC7A1,SLC7A14,SLC7A2,SLC7A3,SLC7A4
SPAC869.10c     SLC7A10,SLC7A11,SLC7A13,SLC7A4,SLC7A5,SLC7A6,SLC7A7,SLC7A8,SLC7A9

SPAC29A4.05     CALM1,CALM2,CALM3,CALML3,CALML4,CALML5
SPAC3A12.14     CALM1,CALM2,CALML3,CALML4,CALML5

SPCC330.02      FBXL2,FBXL20
SPBC25B2.11     FBXL13,FBXL14,FBXL2,FBXL20,FBXL7

SPCC74.03c      MELK,PRKAA1,PRKAA2
SPBC4F6.06      PRKAA1,PRKAA2

SPAC17G6.05c    PDCD6IP,PTPN23
SPAC2G11.05c    PDCD6IP

SPAC27D7.13c    CLIP1
SPAC3C7.12      CLIP1,CLIP2,CLIP3,CLIP4

SPAC631.02      BRD3,BRD4
SPCC1450.02     BRD2,BRD3,BRD4,BRDT

SPAC16.02c      SRSF4,SRSF5,SRSF6
SPAC222.18      SRSF3,SRSF4,SRSF5,SRSF6,SRSF7

SPAC1002.17c    UCK1,UCK2,UCKL1
SPCC162.11c     UCKL1

SPAC22H10.12c   GDI1,GDI2
SPBC15C4.03     CHM,GDI1,GDI2

SPAC22A12.15c   HSPA5
SPCC1739.13     HSPA1A,HSPA1B,HSPA1L,HSPA2,HSPA5,HSPA6,HSPA8
```

**Comment by ValWood** [comment]
?
SPCC1739.13     HSPA8,HSPA6,HSPA1A,HSPA1B,HSPA1L,HSPA2,HSPA5
SPBC1709.05     HSPA8,HSPA6,HSPA1A,HSPA1B,HSPA1L,HSPA2,HSPA5
SPAC13G7.02c    HSPA8,HSPA6,HSPA1A,HSPA1B,HSPA1L,HSPA2,HSPA5

**Comment by ValWood** [comment]
can't trace SPBC15C4.03
MONDO:0001071 | intellectual disability | PomBase | PB_REF:0000003
@kimrutherford  I want to remove but I cant locate?

**Comment by mah11** [comment]
> can't trace SPBC15C4.03 MONDO:0001071

There's a matching line in pombase_disease_associations_mondo_ids.txt

**Comment by ValWood** [comment]
I think I fixed all but there might be some knock-on effects.
@kimrutherford  could you re-run the script to check?

thanks,

Val

**Comment by kimrutherford** [comment]
There are still quite a few.  I'll run it again on Sunday or Monday in case some changes aren't on the main site yet.

```
SPCC330.02      FBXL2,FBXL20
SPBC25B2.11     FBXL13,FBXL14,FBXL2,FBXL20,FBXL7

SPAC1002.17c    UCK1,UCK2,UCKL1
SPCC162.11c     UCKL1

SPAC22A12.15c   HSPA5
SPAC13G7.02c    HSPA1A,HSPA1B,HSPA1L,HSPA2,HSPA5,HSPA6,HSPA8

SPAC890.06      NUP155
SPAC1805.04     NUP133,NUP155

SPCC645.05c     MYH1,MYH10,MYH11,MYH13,MYH14,MYH15,MYH2,MYH3,MYH4,MYH6,MYH7,MYH7B,MYH8,MYH9
SPAC4A8.05c     MYH11,MYH9

SPAC22H10.12c   GDI1,GDI2
SPBC15C4.03     CHM,GDI1

SPAC222.18      SRSF3,SRSF4,SRSF5,SRSF6,SRSF7
SPAC16.02c      SRSF4,SRSF5,SRSF6

SPAC17G6.05c    PDCD6IP,PTPN23
SPAC2G11.05c    PDCD6IP

SPBC32C12.03c   PRKAA1,PRKAA2
SPCC74.03c      MELK,PRKAA1,PRKAA2

SPCC330.02      FBXL2,FBXL20
SPBC25B2.11     FBXL13,FBXL14,FBXL2,FBXL20,FBXL7
```

**Comment by kimrutherford** [comment]
>  I'll run it again on Sunday or Monday in case some changes aren't on the main site yet.

I just checked and got the same result.

**Comment by ValWood** [comment]
yeah I think sometimes orthologas are listed in artemis and in the flat files. Easy to sort...

**Comment by ValWood** [comment]
Damn. I don't think I updated. 
Could you rerun tomorrow (I think there are still fixes required but  hopefully I will catch them all. this time)

**Comment by ValWood** [comment]
OK I wnet through them again. I think I got them all this time. One more check?

**Comment by kimrutherford** [comment]
I'll run the script again tomorrow and let you know.

**Comment by kimrutherford** [comment]
> I'll run the script again tomorrow and let you know.

The load had a glitch (failed to download the biogrid data) so I had to restart.  It will probably finish at 9am or so.

**Comment by kimrutherford** [comment]
Sorry, there are still a few to fix.  My script wasn't reporting all the pombe IDs:

```
SPAC13G7.02c    HSPA1A,HSPA1B,HSPA1L,HSPA2,HSPA5,HSPA6,HSPA8
SPCC1739.13     HSPA1A,HSPA1B,HSPA1L,HSPA2,HSPA5,HSPA6,HSPA8
SPBC1709.05     HSPA1A,HSPA1B,HSPA1L,HSPA2,HSPA5,HSPA6,HSPA8
SPAC22A12.15c   HSPA5

SPAC890.06      NUP155
SPBP35G2.06c    NUP133,NUP155
SPAC1805.04     NUP133,NUP155

SPAC22H10.12c   GDI1,GDI2
SPBC15C4.03     CHM,GDI1
```

**Comment by ValWood** [comment]
I'm pretty sure these are all fixed.  I think I forgot to svn update for the last few...

**Comment by kimrutherford** [comment]
> I'm pretty sure these are all fixed. I think I forgot to svn update for the last few...

Yep!  All fixed on the main site.
