### ISSUE TITLE
New warnings about duplicates during Canto loading

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#2949]
From tomorrow there will be a bunch of extra duplicate annotation warnings in the Canto log file (the one the looks like "log.2021-01-31-21-17-29.curation-tool-data-load-output").

**Comment by kimrutherford** [comment]
The warnings aren't great at the moment but I hope there is enough for you to track down the problem:

**warning in 7fae84167ce708af: storing feature_cvterm from 7fae84167ce708af-genotype-2 to increased protein localization to plasma membrane during vegetative growth [assayed_using] SPAC869.11 - failed to store feature_cvterm: that annotation has already been stored in Chado with properties:  evidence: "Microscopy"**

That example is about the two annotations at the bottom of this table:
https://curation.pombase.org/pombe/curs/7fae84167ce708af/feature/genotype/view/2/ro

All of the new warnings are for phenotype annotations and have the internal genotype ID ("7fae84167ce708af-genotype-2") in the log message.  It's difficult to get more detail at this point in the loading so as a temporary step I've added a column in the annotation table which shows the internal ID, but only during approval:

![genotype-id-column-1](https://user-images.githubusercontent.com/90474/106662814-bf95c580-6607-11eb-87d2-3fa49d0c161a.png)

I'll work on a better solution.

If any of the log messages don't make sense please let me know.

Sorry there are so many.

**Comment by kimrutherford** [comment]
> If any of the log messages don't make sense please let me know.

And if it all makes sense this issue can be closed.

**Comment by ValWood** [comment]
also this one

**Comment by ValWood** [comment]
Presume I can close this one too?

**Comment by kimrutherford** [comment]
> Presume I can close this one too?

I think so.

There are still lots of warnings in the log file but they can be chipped away at over time:
https://curation.pombase.org/dumps/builds/pombase-build-2021-02-14/logs/log.2021-02-14-23-13-29.curation-tool-data-load-output

Sorry about the "some data from annotation isn't used: old_term_ontid" messages.  They should be gone tomorrow.
