### ISSUE TITLE
Duplicates in pombe-embl/external_data/qualitative_gene_expression_data/Duncan_29432178.txt

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#2951]
This line occurs three times in `Duncan_29432178.txt`:

```
SPCC1393.08             translation     ECO:0007087     increased       during(GO:1903832)      PMID:29432178   4896    2018-03-09
```

**Comment by kimrutherford** [comment]
I've removed two of the copies of that line so I can re-start the load.

**Comment by ValWood** [comment]
this might be done @mah11 ?

**Comment by mah11** [comment]
See Kim's comment above.

**Comment by ValWood** [comment]
OK I wasn't sure if that was a temporary fix for the load, or if any annotations needed changing.
