### ISSUE TITLE
how to curate PMID:32059768

### ISSUE THREAD

**Issue by mah11** [pombase/curation#2962]
This is the session that was moved from the demo server (https://github.com/pombase/canto/issues/2338).

https://curation.pombase.org/pombe/curs/934c9e88c393b2ff/

I've had a very quick look at the paper, and dealing with the genotypes is really not the problem -- actually only ~one~ a few mutants used (including pom1Δ).

The main challenge is that most of the data are of types that don't fit neatly into either existing Canto types or browser tracks, but it's clever stuff and it would be a shame to throw out everything. Some of it might be amenable to "gene expression" if we add more qualifiers, and maybe more expression types. I'll start thinking about it in more detail when I have time, hopefully next week. Input welcome.

**Comment by mah11** [comment]
Additional wittering, as promised (not polished at all!):

possible phenotype annotations:
- **cdc25-22** and **wee1-50** to
  - normal transcription scaling fypo:new1 (list smFISH-ed genes in extensions?)
  - FYPO:0006021 (normal distribution on chromatin) assayed using rpb1
- maybe these diploids: **myo1Δ/myo1+**, **pan1Δ/pan1+**, **rpb1Δ/rpb1+**
  - decreased RNA level fypo:1117 assayed using self
  - normal linear scaling fypo:new1
- **cdc11-119**: any ideas how to represent that the multinucleate cells have "normal scaling relative to total nuclear volume" but "scaling lost in any individual nucleus"?
- **pom1Δ**
  - scaling with nuclear size fypo:new2

new fypo terms
1. normal transcription scaling (coordination of transcription rates with cell size is normal; scaling maintains biomolecule concentrations as cells grow and divide; maybe specify "scales linearly" in name and/or def?)
2. abnormal transcription scaling with nuclear size (trancription rate scales linearly with nuclear size instead of total cell size)


possible expression annotations:

- RNA level
     - urg1	increased	+uracil
     - sib1	increased	+2,2-dipyridyl
would need new evidence for FISH (manual ECO:0001182; parent ECO:0001047; could even do without fluorescence & use plain in situ hyb - manual ECO:0001838, parent ECO:0001836)

- protein level
   - rpb1	constant/unchanged during mitotic cell cycle GO:0000278 microscopy
   - rpb9	constant/unchanged during mitotic cell cycle GO:0000278 microscopy
again, need new evidence option

any way to capture -- or at least approximate -- "transcriptional scaling is mediated by an increase in RNAPII initiation rates coordinated with cell size"? e.g. add "RNA polymerase occupancy" as expression type? and subtype 'increased' ... hmm, during cell growth (GO:0016049)?

For "RNAPII Amounts on Chromatin Increase with Cell Size" ... RNAPII on chromatin is GO CC, but I don't know of any way to do an extension or anything else for the increase with cell size.

Also nothing yet on the stuff that doesn't correlate with scaling (RNA degradation; transcription elongation or termination) ...


I'll give it a couple days for more comments before I add FYPO terms or email anyone.

**Comment by ValWood** [comment]
>cdc11-119: any ideas how to represent that the multinucleate cells have "normal scaling relative to total nuclear volume" but "scaling lost in any individual nucleus"?

hmmph. Maybe just say it as it is (I'm guessing a logical def will be out of scope for this!)
normal total  transcription scaling  in multinucleate cells, with abolished scaling in individual nuclei

**Comment by ValWood** [comment]
I see this was tricky, think this is a good approach. V. nice paper !

**Comment by mah11** [comment]
Heh, none of the phenotypes could get logical definitions :P

Any thoughts specifically on the "RNA polymerase occupancy" idea?

**Comment by ValWood** [comment]
I missed that question. I like the idea of "RNA occupancy " as an expression type, and during"cell growth" would be a good way to indicate the scaling.  I think it would be clear on reading what it meant, and "RNA occupancy" is likely to be a useful type anyway with the single-cell stuff. 

Actually it's quite nice to increase the scope of "expression"  to cope with this fancy stuff !

**Comment by mah11** [comment]
Another point about "RNA polymerase occupancy" (every time I look, I notice something else!) - it's the conclusion they draw from Rpb1 ChIP, and would pretty much apply to every sodding gene (all protein-coding and almost all ncRNA). It wouldn't be much work to make a bulk-load file for it, but it's got me second-guessing whether we should, or if just hosting the ChIP-seq data is the way to go. I'll do the expression thing if you think it's worth it -- it would make something show up in the expression department on gene pages.

**Comment by ValWood** [comment]
Of course, they all scale. Maybe just the CHIP data is enough. You could ask Sam if he has any other ideas.

**Comment by mah11** [comment]
OK, I've opened [Canto](https://github.com/pombase/canto/issues/2429) and [FYPO](https://github.com/pombase/fypo/issues/3936) tickets, and I'll email Sam early next week. Let's see if my subconscious coughs up anything clever in the meantime, because I"ve hit my brain limit on this one now.

**Comment by mah11** [comment]
I've implemented various things in the session, so I'll close this. We can reopen or do a new ticket if Sam & Xi-Ming ask for any changes.
