### ISSUE TITLE
use post-Met-removal residue numbering in display names for histone modified forms

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2967]
https://github.com/PROconsortium/PRoteinOntology/issues/228#issuecomment-785981633
I think this is possible?

**Comment by mah11** [comment]
What is "community numbering"?

**Comment by ValWood** [comment]
standard numbering used by the community for histones (I don't know what  else to call it)

**Comment by mah11** [comment]
I need a description, not a rephrasing. Do you mean counting or not counting the initiator methionine?

**Comment by ValWood** [comment]
Not counting the initiator. So that Histone H3K9 is  displayed as histone H3-K9 (as everyone calls it), not histone H3-K10.

All of the curated modifications for histones seem to match ex-Met naming. I have never seen anyone use  a naming system for histone modifications which includes the methionine in a publication, have you?

**Comment by mah11** [comment]
done (revision 6980)
