### ISSUE TITLE
in_absence_of() and has_direct_input() in extensions

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#2977]
I'm sure you knew this but GO obsoleted `in_absence_of` and `in_presence_of` ages ago.  But because we've been using an outdated version of gorel.obo it hasn't caused any problems for us.
Now that the load script is using the latest OBO file from Git, the two relations are missing from Chado and the load failed.

The load failed because the qualitative annotation loader couldn't cope with:
`pombe-embl/external_data/qualitative_gene_expression_data/PMID_31626996_Paulo_qualitative_expression.txt`

I noticed that we have a file maintained by Midori that has the missing relations:
`mini-ontologies/gene_ex_extension_relations.obo`

We used to load this file but I removed it from the load script 4 years ago because it wasn't needed.  I've added the back into the script and restarted the load.  If that's the right plan please close this issue.  :-)

**Comment by kimrutherford** [comment]
Unfortunately adding `gene_ex_extension_relations.obo` didn't fix things.
I think it's because we are still loading obsolete terms and relations from all the input OBO files.  The loader didn't like having two relations with the same ID.  The term IDs are just "in_absence_of" and "in_presence_of".  

We probably don't need to load obsolete terms and relations since there are no annotations to obsolete terms and they shouldn't be used anywhere else.  I'll try a test load without them and check it's OK.

**Comment by mah11** [comment]
I didn't do the PMID_31626996_yada file, so I don't know whether it could be changed.

**Comment by kimrutherford** [comment]
> I don't know what it could change to....

Both relations are used in the contig files too for gene expression annotation.

> hey used to be in the GO relations file, but that no longer exists and we now use RO?

There is still a GO relations file.  The change is that those two relations have been made obsolete in that file.

It should all be fine for us because we have them in our on relations file.  The loader isn't coping with having a obsolete and non-obsolete version of the relation but I'm working on that.

**Comment by kimrutherford** [comment]
> It should all be fine for us because we have them in our on relations file. The loader isn't coping with having a obsolete and non-obsolete version of the relation but I'm working on that.

I sort of fixed that by changing the namespace in `gene_ex_extension_relations.obo` to "go/extensions/gorel" (which is a big hack) and giving the terms unique IDs like "POMBASE_GENE_EX_REL:in_absence_of".

But now that's fixed I noticed lots of warning about

**Comment by kimrutherford** [comment]
I forgot to say that I haven't updated the main site with the latest nightly load because of the missing Canto annotation due to the warnings.  The dev site is updated though: http://dev.pombase.kmr.nz/

**Comment by mah11** [comment]
> Should I add has_direct_input to gene_ex_extension_relations.obo too?

I think so ... we could swap in `has_input` because specifying `direct` doesn't gain us much, but it would be a PITA to retrofit annotations manually.

**Comment by ValWood** [comment]
> has_input because specifying direct doesn't gain us much

also for MF has_input is always direct (enforced in. the  usage rules). i.e it should be implicit.
For MF annotations we can replace all instances of has_direct_input with has_input.

Kim could you do this?

**Comment by kimrutherford** [comment]
Yep, I should be able to change the Canto annotations.
There are annotations in pombe-embl/external_data/external-go-data/.  Should I change those too?

**Comment by kimrutherford** [comment]
I think I've fixed the has_direct_input warnings so that the Canto annotation loads.  I had to restart the nightly load once I'd fixed things so it probably won't finish until 8 or 9am.

I've added has_direct_input to gene_ex_extension_relations.obo and that seemed to fix the problem.

As usual, I'll check the load when it's done.

**Comment by mah11** [comment]
> There are annotations in pombe-embl/external_data/external-go-data/. Should I change those too?

Sure. Might as well be consistent.

**Comment by kimrutherford** [comment]
> I had to restart the nightly load once I'd fixed things so it probably won't finish until 8 or 9am.

It worked much better.  But there were still a few extension relations that have been obsoleted by GO that are still in use in Canto annotations: not_exists_during, not_happens_during and regulates_activity_of.  The session IDs are in the log file:
https://curation.pombase.org/dumps/builds/pombase-build-2021-03-11/logs/log.2021-03-12-02-43-34.curation-tool-data-load-output

There are only 10-ish annotations that failed to load because of those extension relations.

I haven't updated the main site because there are no extra community sessions since the last successful update and I still want to do a bit more checking that everything is OK after the GO repo changes.

Also the latest load has 4030 curated publications but the previous successful load has 4031.  I'm going to check up on that tomorrow.

**Comment by kimrutherford** [comment]
> I haven't updated the main site because there are no extra community sessions since the last successful update and I still want to do a bit more checking that everything is OK after the GO repo changes.

It's updated now and the nightly loads have been fine for the last few days.

> Also the latest load has 4030 curated publications but the previous successful load has 4031. I'm going to check up on that tomorrow.

I checked that and it's all OK.  There was one extra approved admin session and two community taken out of APPROVED status (one reactivated and one back into approval mode).

> For MF annotations we can replace all instances of has_direct_input with has_input.

I haven't done that yet.

**Comment by kimrutherford** [comment]
> For MF annotations we can replace all instances of has_direct_input with has_input

I've changed the relation in Canto, the contig files and in the GAF files from pombe-embl/external_data/external-go-data/

I'll check the load on Wednesday morning.

**Comment by kimrutherford** [comment]
> I'll check the load on Wednesday morning.

There are now no MF has_direct_input extensions in Chado.  There are a handful on modification annotations.

**Comment by ValWood** [comment]
hmm, how do we use it there???

**Comment by kimrutherford** [comment]
I can only see two features that use these relations:
 - https://www.pombase.org/gene/SPAC6F6.15
 - https://www.pombase.org/gene/SPCC1795.06

**Comment by ValWood** [comment]
OK these are fine. They refer to modifications where the input is itself a modified residue. Neat ;)
