### ISSUE TITLE
regulation targets as process extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2982]
comment from Antonia in https://github.com/pombase/curation/issues/1278#issuecomment-278035856_

~I really don't like 
"+ve regulation G2/M transition" has regulation target cdc25
the extension should be an extension of the GO term? Cdc25 is not a "G2/M transition" so it doesn't make sense to add it here? @mah11 what do you think?~

I reported a similar thing for srw1, it's annotated to
mitotic G1 cell cycle arrest in response to nitrogen starvation
regulates cdc2

same thing here, the extension does not make sense as an extension to the GO term.

_Originally posted by @Antonialock in https://github.com/pombase/curation/issues/1278#issuecomment-278035856_

**Comment by mah11** [comment]
> the extension should be an extension of the GO term? Cdc25 is not a "G2/M transition" so it doesn't make sense to add it here?

I don't understand this fully -- extensions *are*, by definition and implementation, extensions of the annotated term, and I don't know what 'Cdc25 is not a "G2/M transition"' could even mean -- but I agree that it does not make sense to say that any gene product is a target of regulation of a cell cycle phase transition. The transition itself is the regulated entity, i.e. the target.

**Comment by ValWood** [comment]
I'm not sure which gene was  being referred to in the first comment.

But
https://www.pombase.org/gene/SPAC144.13c
Doesn't look right. There are. better ways to capture the substrates of the pathway.

**Comment by ValWood** [comment]
see
https://github.com/pombase/curation/issues/2498
