### ISSUE TITLE
odd relations for extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2985]
~I see:
decreased protein localization to chromatin at RNA polymerase II promoter during vegetative growth
  | ams2-C1 (1-143 aa) affecting ams2
  | lsk1Δ affecting activity of rpb3 affecting substrate ste11
  | rpb1-S2A  affecting activity of rpb3 affecting substrate ste11
I'm not sure what   "affecting activity of rpb3" "affecting substrate ste11"
mean in this context, but I could not see these relations in Cant for this term either.~

These are fixed, but  others still to fix..

**Comment by mah11** [comment]
I agree these don't make sense. The Canto configuration only offers "assayed enzyme" and "assayed substrate" for phenotypes defined using GO catalytic activity or catalytic activity regulator terms. Any of those extensions on biological process phenotypes must have been done manually (or transferred by mistake).

The really bonkers protein localization extensions all seem to come from PMID:20605454.

I also see some used with phosphorylation phenotype terms in several papers including PMID:11160827, PMID:24741065, PMID:18235227 and PMID:22976295 (probably a few more but I stopped looking). The phosphorylation ones aren't as nonsensical but they still don't fit the usage we've defined for the enzyme & substrate extensions on FYPO terms.

**Comment by mah11** [comment]
I fixed extensions in PMID:20605454. I think that just leaves the less perplexing "phosphorylation" stuff.

**Comment by ValWood** [comment]
I can do those "phosphorylation"  at some point as a break from RNA's. I'm sort of looking at them anyway  as part of the thinking about go-cam modelling so they were on my radar....

**Comment by ValWood** [comment]
See folder "substrate relations to fix"

**Comment by ValWood** [comment]
I think this is out of date.
