### ISSUE TITLE
human orthologs , gemin

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2987]
- [x] gem6 G2TRK8 GEMIN6 PMID:33754639
 - [x] gem8 Q9USY8 GEMIN8 PMID:33754639
 - [ ]  mail Pfam

**Comment by mah11** [comment]
Remy asked about updating the "taxonomic conservation" annotation too ... I assured him you're on the case ;) but shout if you want me to do anything.

**Comment by ValWood** [comment]
sorted. I won't miss a species specific -> human ortholog.

**Comment by mah11** [comment]
perish the thought!
