### ISSUE TITLE
active form query mei2

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2993]
PMID:11818066

has

rad24 sequesters mei2/Phos:(S438,T527)

but also 
mei2 binds sme2 active form mei2/Phos:(S438,T527)

doesn't mei2 unphoshphorylated form bind sme2? ( That would be expe cted if the phosphorylated form is sequestered)?

**Comment by ValWood** [comment]
Rad24p binds preferentially to Mei2p phosphorylated by Pat1 kinase. It inhibits association of meiRNA to the phosphorylated form of Mei2p but not to the unphosphorylated form in vitro.

**Comment by mah11** [comment]
Mei2 can bind sme2 whether it (Mei2) is phosphorylated or not (the col17 entry therefore wasn't wrong but was incomplete, so I've added another annotation). 

> Rad24p binds preferentially to Mei2p phosphorylated by Pat1 kinase. It inhibits association of meiRNA to the phosphorylated form of Mei2p 

The Rad24 GO:0140311 annotation captures this.

> but not to the unphosphorylated form in vitro.

Is there a way to represent this part?
