### ISSUE TITLE
unique products

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#3]
add product heirarchy here
announce to pombelist

Original comment by: ValWood

**Comment by ValWood** [comment]
we don't need this ticket.

For reference, here id the product naming heirarchy:
https://curation.pombase.org/pombase-trac/wiki/GeneProductNaming

**Comment by ValWood** [comment]
for the record, these are *the only* none unique protein products:


2 40S ribosomal protein S10 (predicted)
   2 40S ribosomal protein S11 (predicted)
   2 40S ribosomal protein S12 (predicted)
   2 40S ribosomal protein S14 (predicted)
   2 40S ribosomal protein S15 (predicted)
   2 40S ribosomal protein S15a (predicted)
   2 40S ribosomal protein S16 (predicted)
   2 40S ribosomal protein S17 (predicted)
   2 40S ribosomal protein S18 (predicted)
   2 40S ribosomal protein S19 (predicted)
   2 40S ribosomal protein S23 (predicted)
   2 40S ribosomal protein S24 (predicted)
   2 40S ribosomal protein S25 (predicted)
   2 40S ribosomal protein S26 (predicted)
   2 40S ribosomal protein S30 (predicted)
   2 40S ribosomal protein S5 (predicted)
   2 40S ribosomal protein S6
   2 40S ribosomal protein S8 (predicted)
   2 5'-methylthioribulose-1-phosphate dehydratase, adducin (predicted)
   2 5-oxoprolinase (ATP-hydrolizing) (predicted)
   2 6-phosphofructo-2-kinase (predicted)
   2 60S acidic ribosomal protein A2
   2 60S ribosomal protein L10
   2 60S ribosomal protein L10a
   2 60S ribosomal protein L11 (predicted)
   2 60S ribosomal protein L12.1/L12A
   2 60S ribosomal protein L19
   2 60S ribosomal protein L21 (predicted)
   2 60S ribosomal protein L23
   2 60S ribosomal protein L24 (predicted)
   2 60S ribosomal protein L25 (predicted)
   2 60S ribosomal protein L27/L28
   2 60S ribosomal protein L3
   2 60S ribosomal protein L30 (predicted)
   2 60S ribosomal protein L34
   2 60S ribosomal protein L36
   2 60S ribosomal protein L37 (predicted)
   2 60S ribosomal protein L37a (predicted)
   2 60S ribosomal protein L38 (predicted)
   2 60S ribosomal protein L4 (predicted)
   2 60S ribosomal protein L9
   2 AMP binding enzyme (predicted)
   2 ATP-dependent DNA helicase/ ubiquitin-protein ligase E3 (predicted)
   2 But2 family protein
   2 CAAX prenyl protease (predicted)
   2 ClC chloride channel (predicted)
  2 DUF1769 family protein
   2 DUF2009 protein
   2 DUF726 family protein
   2 Erd1 homolog (predicted)
   2 FKBP-type peptidyl-prolyl cis-trans isomerase (predicted)
   2 GNS1/SUR4 family protein (predicted)
   2 Golgi Ca(2+)/H(+) antiporter Gdt1
   2 LEA domain protein
   2 NAD binding dehydrogenase family protein
   2 NADPH dehydrogenase (predicted)
   2 NADPH-hemoprotein reductase (predicted)
   2 RNA-binding protein, rrm type
   2 Rab GTPase binding (predicted)
   2 S. pombe specific GPI anchored protein family 1
   2 Schizosaccharomyces specific multicopy membrane protein family 1
   2 Schizosaccharomyces specific protein, predicted GPI anchor
   2 ThiJ domain protein (predicted)
   2 ThrE amino acid transmembrane transporter family protein
   2 U3 snoRNP-associated protein Cic1/Utp30 family (predicted)
   2 WD repeat protein, human WDR44 family
   2 acetyl-CoA ligase (predicted)
   2 agmatinase (predicted)
   2 alanine racemase (predicted)
   2 alcohol dehydrogenase (predicted)
   2 alpha,alpha-trehalose-phosphate synthase (predicted)
   2 alpha-1,2-galactosyltransferase (predicted)
   2 alpha-glucosidase (predicted)
   2 aminotransferase class-III, possible transaminase, unknown specificity
   2 cell surface glycoprotein, adhesion molecule (predicted)
   2 cysteine transmembrane transporter (predicted)
   2 cytochrome b5 (predicted)
   2 enolase (predicted)
   2 glucose-6-phosphate 1-dehydrogenase (predicted)
   2 glutathione-dependent formaldehyde dehydrogenase (predicted)
   2 glyoxylate reductase (predicted)
   2 hydantoin racemase family (predicted)
   2 hydroxyacid dehydrogenase (predicted)
   2 hypothetical protein
   2 inositol polyphosphate phosphatase (predicted)
   2 lectin family glycoprotein receptor (predicted)
   2 lysophospholipase (predicted)
   2 methionine synthase reductase (predicted)
   2 mitochondrial S-adenosylmethionine transmembrane transporter (predicted)
   2 mitochondrial calcium uniporter regulator (predicted)
   2 mitochondrial iron ion transmembrane transporter (predicted)
   2 mitochondrial ribosomal protein subunit L16 (predicted)
   2 mitochondrial ribosomal protein subunit L19 (predicted)
   2 mitochondrial ribosomal protein subunit L27 (predicted)
   2 mitochondrial ribosomal protein subunit L28 (predicted)
   2 mitochondrial ribosomal protein subunit L51-b (predicted)
   2 mitochondrial ribosomal protein subunit L9 (predicted)
   2 mitochondrial ribosomal protein subunit S18 (predicted)
   2 mitochondrial translation elongation factor G (predicted)
   2 myosin type V
   2 nifs homolog, possible cysteine desulfurase
   2 omega-amidase (predicted)
   2 palmitoyl-(protein) hydrolase (predicted)
 2 phospho-2-dehydro-3-deoxyheptonate aldolase (predicted)
   2 phosphoglucomutase (predicted)
   2 protein with a role in clearing protein aggregates (predicted)
   2 pseudouridine-5'-phosphatase (predicted)
   2 pyridoxamine 5'-phosphate oxidase (predicted)
   2 pyridoxine-pyridoxal-pyridoxamine kinase (predicted)
   2 ribonuclease H2 complex subunit (predicted)
   2 ribose-phosphate pyrophosphokinase (predicted)
   2 ribosome biogenesis protein Rrp14 (predicted)
   2 serine protease (predicted)
   2 sphingolipid biosynthesis protein (predicted)
   2 trans-aconitate 3-methyltransferase (predicted)
   2 transcription factor, zf-fungal binuclear cluster type
   2 transcription factor, zf-fungal binuclear cluster type(predicted)
   2 translation elongation factor eIF5A (predicted)
   2 ubiquitin family protein (predicted)
   3 40S ribosomal protein S4 (predicted)
   3 60S ribosomal protein L13/L16 (predicted)
   3 60S ribosomal protein L8 (predicted)
   3 G-patch RNA-binding protein, involved in splicing (predicted)
   3 HECT-type ubiquitin-protein ligase E3 (predicted)
   3 MatE family transmembrane transporter (predicted)
   3 NAD/NADH kinase (predicted)
   3 P-type ATPase (predicted)
   3 RNA polymerase II associated Paf1 complex (predicted)
   3 ThiJ domain protein
   3 WW domain containing conserved fungal protein
   3 acetylglucosaminyltransferase (predicted)
   3 acid phosphatase (predicted)
   3 acyl-coenzyme A thioesterase
   3 aldehyde dehydrogenase (predicted)
   3 alpha-amylase homolog (predicted)
   3 aromatic aminotransferase (predicted)
   3 extracellular 5'-nucleotidase, human NT5E family (predicted)
   3 guanyl-nucleotide exchange factor (predicted)
   3 mannan endo-1,6-alpha-mannosidase (predicted)
   3 metallopeptidase (predicted)
   3 mitochondrial DNA binding endonuclease (predicted)
   3 mitochondrial conserved protein (predicted)
   3 oxidoreductase (predicted)
   3 phosphoglycerate mutase family
   3 phosphomethylpyrimidine kinase (predicted)
   3 protein disulfide isomerase (predicted)
   3 tRNA (cytosine-5-)-methyltransferase (predicted)
   3 triglyceride lipase-cholesterol esterase (predicted)
   3 uracil phosphoribosyltransferase (predicted)
   3 urea transmembrane transporter (predicted)
   3 xylose and arabinose reductase (predicted)
   4 L-asparaginase (predicted)
   4 RNA-binding protein
   4 RNase P and RNase MRP subunit (predicted)
   4 carboxylic acid transmembrane transporter (predicted)
   4 conserved protein
   4 dipeptidyl peptidase (predicted)
   4 hydrolase (predicted)
   4 inorganic phosphate transmembrane transporter (predicted)
   4 methyltransferase (predicted)
 3 P-type ATPase (predicted)
   3 RNA polymerase II associated Paf1 complex (predicted)
   3 ThiJ domain protein
   3 WW domain containing conserved fungal protein
   3 acetylglucosaminyltransferase (predicted)
   3 acid phosphatase (predicted)
   3 acyl-coenzyme A thioesterase
   3 aldehyde dehydrogenase (predicted)
   3 alpha-amylase homolog (predicted)
   3 aromatic aminotransferase (predicted)
   3 extracellular 5'-nucleotidase, human NT5E family (predicted)
   3 guanyl-nucleotide exchange factor (predicted)
   3 mannan endo-1,6-alpha-mannosidase (predicted)
   3 metallopeptidase (predicted)
   3 mitochondrial DNA binding endonuclease (predicted)
   3 mitochondrial conserved protein (predicted)
   3 oxidoreductase (predicted)
   3 phosphoglycerate mutase family
   3 phosphomethylpyrimidine kinase (predicted)
   3 protein disulfide isomerase (predicted)
   3 tRNA (cytosine-5-)-methyltransferase (predicted)
   3 triglyceride lipase-cholesterol esterase (predicted)
   3 uracil phosphoribosyltransferase (predicted)
   3 urea transmembrane transporter (predicted)
   3 xylose and arabinose reductase (predicted)
   4 L-asparaginase (predicted)
   4 RNA-binding protein
   4 RNase P and RNase MRP subunit (predicted)
   4 carboxylic acid transmembrane transporter (predicted)
   4 conserved protein
   4 dipeptidyl peptidase (predicted)
   4 hydrolase (predicted)
   4 inorganic phosphate transmembrane transporter (predicted)
   4 methyltransferase (predicted)
   4 oxysterol binding protein (predicted)
   4 phospholipase (predicted)
   4 phosphoprotein phosphatase (predicted)
   4 pyruvate decarboxylase (predicted)
   4 sulfate transmembrane transporter (predicted)
   5 N-acetyltransferase (predicted)
   5 amino acid permease (predicted)
   5 conserved fungal family
   5 spermidine family transmembrane transporter (predicted)
   6 amino acid transmembrane transporter (predicted)
   6 esterase/lipase (predicted)
   7 mug2/mug135/meu2 family
   8 GTPase activating protein (predicted)
   8 S. pombe specific 5Tm protein family
   8 transcription factor, zf-fungal binuclear cluster type (predicted)
  11 short chain dehydrogenase (predicted)
  12 ubiquitin-protein ligase E3 (predicted)
  13 retrotransposable element/transposon Tf2-type
  14 transcription factor (predicted)
  30 transmembrane transporter (predicted)
  71 conserved fungal protein
  87 Schizosaccharomyces pombe specific protein
 120 Schizosaccharomyces specific protein


mostly there is some differentia in the product names. Will continue ad hoc refinement...

**Comment by ValWood** [comment]
For the record,  4271/~5050 protein coding genes now have unique products.
Many of the rest are paralogs (ribosomals) and would be disambiguated by adding the protein name to the end of the product line....
