### ISSUE TITLE
check manual uniprot annotations not covered

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#300]
After global uniprot update

Original comment by: ValWood

**Comment by mah11** [comment]
I'm going to close this because it's really amazingly old, unhelpfully vague, and probably superseded by zillions of more specific tickets and edits.

**Comment by ValWood** [comment]
Ah I know what this means....
Its 

   1 IC
  82 IDA
   2 IGI
  25 IMP
  72 IPI

but it isn't important. I think it will reduce once  more logical filtering is implemented

https://github.com/pombase/pombase-chado/issues/594

and I'll check then to see if there are any oddities
