### ISSUE TITLE
	normal protein phosphorylation during mitotic G2/M transition

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3001]
normal protein dephosphorylation during mitotic G2/M transition

for
PMID:7626804

**Comment by mah11** [comment]
It's [FYPO](https://github.com/pombase/fypo/issues/3993). If you don't need a separate curation ticket we can close this.

**Comment by ValWood** [comment]
Thanks! Doh!
I was looking at it this morning thinking I don't even know what curation this refers to!
