### ISSUE TITLE
ISS updates

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3007]

**Comment by ValWood** [comment]
&nbsp; | Godinho CP, Costa R, Sá-Correia I. | Related&nbsp;Articles
-- | -- | --
&nbsp; | The ABC transporter Pdr18 is required for  yeast thermotolerance due to its role in ergosterol transport and plasma  membrane properties.
&nbsp; | Environ Microbiol. 2020 Sep 28;. [Epub ahead of print]
&nbsp; | PMID: 32985771

**Comment by ValWood** [comment]
| Gnugnoli M, Casari E, Longhese MP. | Related Articles
-- | -- | --
  | The chromatin remodeler Chd1 supports MRX and Exo1 functions in resection of DNA double-strand breaks.
  | PLoS Genet. 2021 Sep 14;17(9):e1009807. [Epub ahead of print]
  | PMID: 34520455 [PubMed - as supplied by publisher]

**Comment by ValWood** [comment]
| Laborenz  J, Bykov YS, Knöringer K, Räschle M, Filker S, Prescianotto-Baschong C,  Spang A, Tatsuta T, Langer T, Storchová Z, Schuldiner M, Herrmann JM. | Related Articles
-- | -- | --
  | The ER protein Ema19 facilitates the degradation of non-imported mitochondrial precursor proteins.
  | Mol Biol Cell. 2021 Feb 17;:mbcE20110748. [Epub ahead of print]
  | PMID: 33596095

**Comment by ValWood** [comment]
@kimrutherford 
exsiting product was:
ER membrane integral protein, implicated in sterol metabolism (predicted)

i.e. still has 'predicted"

I changed this one to 
Integral ER membrane protein involved in protein targeting to mitochondrion
but we might have a conflict?

**Comment by kimrutherford** [comment]
Hi Val.  I don't understand this issue.  You closed it but also tagged me.  Is there anything I need to do?

**Comment by ValWood** [comment]
It's OK, ignore. I think you must be stripping "predicted" during the loading rather than altering the Artemis files directly (because I still see them there).
I was worried that I had changed a product and caused a conflict.
