### ISSUE TITLE
product and name changes pending

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3017]
Product and name changes

- [x] Pap1 
stress-responsive DNA-binding transcription factor Pap1/Caf
->
oxidative stress-responsive DNA-binding transcription factor Pap1/Caf

- [x]  SPAC18B11.11 
GTPase activating protein (predicted)
->
GTPase activating protein, Tsc2 paralog

- [x] Spo4
serine/threonine protein kinase Spo4 
-> 
serine/threonine protein kinase (DDK family) Spo4

- [x] Ckk2
calcium/calmodulin-dependent (CaMKK) protein kinase kinase Ckk2
->
calcium/calmodulin-dependent (CaMKK) protein kinase kinase Ckk2/Ppk34

- [x] Scr1
DNA-binding transcription factor Scr1
->
DNA-binding transcription repressor Scr1

- [x] Mis6 
CENP-I ortholog Mis6
->
inner centromere connector, CENP-I ortholog Mis6

- [x] Hse1
STAM like protein Hse1 ->  
sorting receptor for ubiquitinated membrane proteins, ESCRT 0 complex subunit Hse1

- [x]  SPAC1556.08c | cbs2 | AMPK protein kinase gamma subunit Cbs2
->serine/threonine protein kinase AMPK (gamma) subunit Cbs2

- [x]  SPCC1919.03c | amk2 | AMPK protein kinase regulatory (beta) subunit Amk2
-> serine/threonine protein kinase AMPK (beta) regulatory subunit Amk2

- [x] SPCC1795.10c	svp26	Sed5 Vesicle Protein Svp26 (predicted)
+	COPII-coated ER to Golgi transport vesicle protein

- [x] SPCC1827.02c	pcy1	cholinephosphate cytidylyltransferase Pcy1 (predicted)

- [x] thiosulfate sulfurtransferase, involved in tRNA wobble position thiolation Tum1
->mitochondrial

Add names
- [x] SPCC24B10.16c	+pac4
- [x] SPCC18.08	+msk1

**Comment by ValWood** [comment]
@kimrutherford I didn't want to add these yet. I was wondering about japonicus updating. With the currently proposed table we would then need to manually update the japonicus names.

I am wondering if there is a better way? Maybe  the japonicus community only need to maintain the names/products of those not conserved in pombe and we keep everything else in synch automatically.

Anyway until we decide I will record any changes (I haven't done these yet)

**Comment by kimrutherford** [comment]
> Maybe the japonicus community only need to maintain the names/products of those not conserved in pombe and we keep everything else in synch automatically.

Yep, that the plan:  https://github.com/japonicusdb/japonicus-config/issues/12
I'll have a go at that after I fix the GO annotation transfer.

**Comment by ValWood** [comment]
OK so I can go ahead and update pombe products and names without worrying about keeping the japonicus ones in synch.

**Comment by kimrutherford** [comment]
Yep!  Any changes you make will be visible in JaponicusDB next time I update.

Once I implement  japonicusdb/japonicus-config#12 you'll be able to override the pombe names and products where necessary.

**Comment by ValWood** [comment]
perfect! I forgot how this was going to work ;)

**Comment by ValWood** [comment]
done
