### ISSUE TITLE
gene structure updates  

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3024]
1. update coordinates  in art
2. /controlled_curation="term=warning, gene structure updated;  date=20220401"
3. Add to "https://www.pombase.org/status/gene-coordinate-changes"
4. remove UTR
5. check  for alleles

gene structure updates:

- [x] ddx27 
trim to MET at AA41 new exon coordinates 1116415..1118292

- [x] ppt1
complement(join(1133226..1134283,1134332..1134356))
->complement(1133226..1134302)

- [x] cut6
old first exon 1253430..1253559))
new first exon 1253430..1253460))
trim to MET at AA34
(complement)
all alleles are unknown

- [x]  tup12
old first exon  376993..377200
new first exon 376993..377116
(complement)

- [ ] allele to fix tup12-N (67-271)

- [x]  trm2
old first exon 776013-775641
new first exon 775863,775641
(complement)

- [x]  snf5 
complement(546664..548562)->
complement(546664..548460)

- [x] lsd2    
old join(446679..446770,446679..449241,449295..450530)
new join(446770..449241,449295..450530)

- [x] yos9   
old first exon 514552..515674 ->  
new first exon 
515534..515608))
complement

- [x] tcd1
truncate at MAG (AA~20)
old 1090678..1092135
new 1090729..1092135

- [x] cdc48
old first exon 1306439..1306512,
new first exon (1306457..1306512, 

- [ ]  cdc48 lots of alleles to fix

- [x] ssz1 
complement(join(1515089..1516663,1516789..1516914)) ->
complement(join(1515089..1516663,1516789..1516866))

**Comment by ValWood** [comment]
ssz1 
complement(join(1515089..1516663,1516789..1516914)) ->
complement(join(1515089..1516663,1516789..1516866))

**Comment by ValWood** [comment]
Pam17
old
 complement(join(….,1554381..1554827 ))
new
complement(join(  ……,1554381..1554791))

**Comment by ValWood** [comment]
lys2
1675730..1677895->
1675730..1677895
/score=1320.44 tss

**Comment by ValWood** [comment]
mrx1
join(1798347..1798830,1798960..1799015)
-> 1798347..1798835
remove final exon

SPAC1002.12c
complement(1818695..1820338)
1818695..1820191

dbr1  trim to MRVGVQGC
old complement(join(1754033..1754145,1754186..1754310,1754350..1755118,1755164..1755285,1755331..1755638))
new complement(join(1754033..1754145,1754186..1754310,1754350..1755118,1755164..1755285,1755331..1755593))

urg2 remove
MSTTTTVSAIRTVEE
them to
MSNITISSHPV
new complement(1831012..1831581)

**Comment by ValWood** [comment]
snt2
old complement(1961710..1965105)
new complement(1961710..1965063)

ste24, fasta
old join(1938900..1939004,1939075..1940394)
new join(1938990..1939004,1939075..1940394)
new start MGIL

**Comment by ValWood** [comment]
med13
before
complement(join(3095075..3098590,3098626..3098781,3098878..3098883))
after
complement(join(3095075..3098590,3098626..3098667))
truncated 40 AA

rim1
join(3127647..3127813,3127862..3128780)
after
join(3127689..3127813,3127862..3128780)
truncated 14 AA

rga2
old
complement(3348569..3352396)
new
complement(3348569..3352258)


elo2
before
complement(join(2811438..2812368,2812412..2812485))
after complement(join(2811438..2812368,2812412..2812464))
to get /score=2039.31
MDLTGAH remove

**Comment by ValWood** [comment]
SPAC4H3.06
before
join(3837431..3837519,3837568..3837751,3837811..3837890,3837940..3838000)
after
join(3837449..3837519,3837568..3837751,3837811..3837890,3837940..3838000)

gpi17
before
join(3818668..3818907,3818954..3819677,3819720..3820420)
after
join(3818803..3818907,3818954..3819677,3819720..3820420)

spac1071.09
before
complement(3870660..3871508)
after
complement(3870660..3871427)

**Comment by ValWood** [comment]
dri1 remove  MSKLPSPT
old complement(2009905..2011719)
complement(2009905..2011695)

**Comment by ValWood** [comment]
SPAC25B8.08
before 4168212..4169984
after
4168263..4169984

trm5
before
join(3974310..3974485,3974541..3974629,3974674..3974775,3974879..3975132,3975193..3975429,3975485..3975832,3975882..3975962,3976014..3976079)
after
join(3974340..3974485,3974541..3974629,3974674..3974775,3974879..3975132,3975193..3975429,3975485..3975832,3975882..3975962,3976014..3976079)

**Comment by ValWood** [comment]
sap45
 before
complement(4804630..4806435)
after
complement(4804630..4806387)

rex1 /systematic_id="SPAC637.09"
before
4555399..4557294
after
4555423..4557294

**Comment by mah11** [comment]
There's a shiny new file now - see https://github.com/pombase/website/issues/1781#issuecomment-965592838

**Comment by ValWood** [comment]
mrps18 before
complement(4967223..4967894)
after
complement(4967223..4967756)

otu2
before
join(4971117..4971548,4971595..4972137)
after
join(4971189..4971548,4971595..4972137)

**Comment by ValWood** [comment]
rec24
complement(join(4996030..4996763,4996904..4997222))
complement(join(4996030..4996763,4996904..4997171))

aif1
old
5146165..5148000
new

pnn1
old
complement(join(5181982..5182122,5182191..5182632,5182721..5182731))
new
complement(join(5181982..5182122,5182191..5182628))

**Comment by ValWood** [comment]
tpp2
old
complement(5336815..5340639)
new
complement(5336815..5340471)

**Comment by ValWood** [comment]
chromosome2 gene structure updates:

mas2
before complement(2096528..2098036)
after
complement(2096528..2098036)

brc1
before complement(join(426160..428547,428634..428771,428903..429013))
after complement(join(426160..428547,428634..428771,428873..428896))

gene structure updates
omh5  
before complement(join(1465811..1466035,1466138..1467057,1467311..1467431))
after ?????

rmt3
before complement(join(1376341..1377734,1377814..1377909,1378224..1378365))
after complement(join(1376341..1377734,1377814..1377909,1378224..1378266))

met7 
befor join(1132170..1132253,1132300..1132431,1132741..1134042)
after join(1132227..1132253,1132300..1132431,1132741..1134042)

cho1
before join(1058347..1058951,1059007..1059067)
after join(1058422..1058951,1059007..1059067)

naa38 
before join(676629..676908,677057..677127)
after join(676761..676908,677057..677127)

rpn7 
before complement(430551..431780
after complement(430551..431744)

nup107 
before
complement(join(439274..441187,441229..441337,441392..441484,441541..441667,441718..441751,441793..441840,441916..442032))
after
complement(join(439274..441187,441229..441337,441392..441484,441541..441667,441718..441751,441793..441840,441916..441975))


SPBC582.08
before join(432550..433012,433204..434003,434057..434311)
after join(432595..433012,433204..434003,434057..434311)

cdt1
before 477365..478699
after 477431..478699

eri1
before join(1320692..1320819,1320897..1321004,1321066..1321471,1321534..1321833)
after join(1320740..1320819,1320897..1321004,1321066..1321471,1321534..1321833)

**Comment by ValWood** [comment]
SPBC30D10.09c
before join(3083317..3083483,3083527..3083648,3083742..3084106)
after. join(3083470..3083483,3083527..3083648,3083742..3084106)

tvp23 
before complement(join(2956469..2956904,2956966..2957189))
after complement(join(2956469..2956904,2956966..2957132))

pof10  before
join(2925512..2925620,2925675..2927554)
after
join(2925563..2925620,2925675..2927554)

orc2 old
2781958..2783565
orc2 new 2782066..2783565


tif512 
before complement(2758761..2759270)
after complement(2758761..2759234)
SPBC19G7.04
before join(2349593..2349654,2349697..2350344,2350388..2350766)
after join(2349611..2349654,2349697..2350344,2350388..2350766)

cut2 
before complement(2203316..2204221)
cut2 after complement(2203316..2204206)

skb1 
beforejoin(2277215..2277464,2277514..2279012,2279059..2279247)
after join(2277275..2277464,2277514..2279012,2279059..2279247)

**Comment by ValWood** [comment]
SPCC569.03
Before complement(join(2430334..2430776,2430840..2431524))
After complement(join(2430334..2430776,2430840..2431347))

Apl4 
before 2401980..2404577
after 2402067..2404577

cwf26
before join(2163205..2164118,2164159..2164165)
After join(2163220..2164118,2164159..2164165)

sec65
Before complement(join(2142679..2143055,2143109..2143373))
after complement(join(2142679..2143055,2143109..2143331))

qcr9 
Before join(371230..371286,371353..371438,371498..371546,371612..371677)
After join(371284..371286,371353..371438,371498..371546,371612..371677)

srp68 
before complement(join(379065..379652,379728..380604,380660..380922,380969..381034))
After complement(join(379065..379652,379728..380604,380660..380823))

naa40 
Before complement(1030256..1030870)
After complement(1030256..1030828)

gid1 
Before complement(join(1056598..1056737,1056787..1057191,1057239..1057880,1057925..1058213))
After complement(join(1056598..1056737,1056787..1057191,1057239..1057880,1057925..1058189))

SPCC622.11 
Before join(1417100..1417438,1417634..1418983)
After join(1417271..1417438,1417634..1418983)

**Comment by ValWood** [comment]
SPBC31F10.17c
Before complement(join(3788317..3788649,3788725..3788799))
After complement(join(3788317..3788649,3788725..3788775))

**Comment by ValWood** [comment]
trm1 before 3723383..3725029
trm1 after 3723455..3725029

mrpl38 before
join(3551318..3551389,3551433..3551490,3551554..3551834)
after join(3551348..3551389,3551433..3551490,3551554..3551834)

rns1
before complement(join(3727332..3727657,3727705..3727810,3727877..3728176))
after complement(join(3727332..3727657,3727705..3727810,3727877..3728068))

**Comment by ValWood** [comment]
>

**Comment by ValWood** [comment]
@juanmatacambridge  to check a few start sites

**Comment by juanmatacambridge** [comment]
Confirmed experimentally by translation initiation mapping and CAGE

SPAC25B8.08
2nd AUG used, TSS (CAGE) between AUG1 and AUG2
before 4168212..4169984
after 4168263..4169984

Ddx27
3rd AUG used, TSS (CAGE) between AUG2 and AUG3

Ppt1
Unclear from our data

Cut6
2nd AUG used, TSS (CAGE) between AUG1 and AUG2

Tup12
3rd AUG used, TSS (CAGE) between AUG2 and AUG3 – a bit confusing – the TSS is too close to the translated AUG 

Trm2 
No data in our experiment, CAGE suggests annotation is wrong

Snf5
3rd AUG used, TSS (CAGE) between AUG2 and AUG3

Lsd2
First translated AUG starts  on 446770

Lys2
First translated AUG starts on 1675823


There are a few more, let me know if you want the data from the experiment

**Comment by juanmatacambridge** [comment]
Confirmed experimentally by translation initiation mapping and CAGE

SPAC25B8.08
2nd AUG used, TSS (CAGE) between AUG1 and AUG2
before 4168212..4169984
after 4168263..4169984

Ddx27
3rd AUG used, TSS (CAGE) between AUG2 and AUG3

Ppt1
Unclear from our data

Cut6
2nd AUG used, TSS (CAGE) between AUG1 and AUG2

Tup12
3rd AUG used, TSS (CAGE) between AUG2 and AUG3 - a bit confusing - the TSS is too close to the translated AUG

Trm2
No data in our experiment, CAGE suggests annotation is wrong

Snf5
3rd AUG used, TSS (CAGE) between AUG2 and AUG3

Lsd2
First translated AUG starts  on 446770

Lys2
First translated AUG starts on 1675823

**Comment by ValWood** [comment]
Hi Juan,
So you agree with all of these new predictions,  or are there some that you did not agree with?
Val

**Comment by juanmatacambridge** [comment]
SPAC25B8.08 confirmed
Trm5 unclear, cannot confirm from our data
Ddx27 confirmed
PPt1 unclear from our data
Cut6 confirmed
Tup12 confirmed
Trm2 no data
Snf5 unclear from our data
Lsd2 confirmed from our data
Lys2 first translated AUG on 1,675,823 (corresponds to 3rd in-frame AUG from annotated CDS)


From: Val Wood ***@***.***>
Reply to: pombase/curation ***@***.***>
Date: Monday, 25 April 2022 at 08:32
To: pombase/curation ***@***.***>
Cc: Juan Mata ***@***.***>, Mention ***@***.***>
Subject: Re: [pombase/curation] gene structure updates (#3024)


Hi Juan,
So you agree with all of these new predictions, or are there some that you did not agree with?
Val

**Comment by ValWood** [comment]
- [ ] lsd2 change
https://www.pombase.org/status/gene-coordinate-changes
SPAC23E2.02 | lsd2 | join(446491..446513,446679..449241,449295..450530) | join(446679..446770,446679..449241,449295..450530) |   |   | 2021-06-11

to
SPAC23E2.02 | lsd2 | join(446491..446513,446679..449241,449295..450530) | 
join(446770..449241,449295..450530)

(removed first exon)

**Comment by ValWood** [comment]
Hi @manulera 

I fixed the remainder of these gene structure alterations today. I will hand the rest of the ticket over to you  for the following tasks:

1. Every change below med13 above, plus lys2 needs adding to 
 https://www.pombase.org/status/gene-coordinate-changes

i) you don't need to add the complete 'before' and 'after' coordinates. Most of these are alterations to the N terminal exon (or the 2 N-term exons). They are all N-terminal truncations and  could be reported more concisely  as: 
before  exon1 complement(2430840..2431524)
After  exon1 complement(2430840..2431347)
or similar (but do the complete string if you think this is better

ii. The  comment for all is  "inferred by curator based on PMID:30566651 CAGE data (*) " (also for the ones already added from this ticket )

iii. All of the ones Juan confirmed can have an additional comment  "independently confirmed pers. comm. Juan Mata"

iv) The existing  entry on the web page for lsd2 needs altering, the change reported was not the final change (see comment above)

v) I still need to figure out omh5 but I might need to postpone that one for now, can be added later.

(*) These changes were not directly reported in the publication, but I used this dataset for the new UTRs. These proteins were clearly over-extended based on the actual transcription start site. This is not surprising because I always selected the longest translation in the absence of homology.  Most of these changes are also now supported by pairwise alignment with the other Schizos.

2. Now for the really horrible part: there are a number of  genes which have published alleles referring to the pre-existing amino acid sequence:
tup12, cdc48, rga2, elo2, dri1, brc1, cdt1, orc2, cut2, skb1 
These alleles will need the aa substitution description recalculating.  The previous names (if they had the AA change embedded in the allele name) and descriptions should be recorded in the allele synonyms field

3. For later, I am not sure if, when a gene structure has changed previously, that alleles have always been "recalculated". In fact, I am pretty sure that they haven't always, but most changes have been for unpublished genes,, or if we are curating older papers we might not always be mindful that a sequence change has been made that post-dated the allele designation. Longer term, it would be very nice if there was some sort of "app"  that could report if an amino acid substitution description did not match the current amino acid designation. This QC check might also be useful for Genestorian?
https://github.com/pombase/pombase-chado/issues/131

**Comment by ValWood** [comment]
Although the allele fixing part of this is non urgent, it would be useful to do task 1 next time you are on PomBAse tasks  so that if people want to look up the changes they are in the table.

**Comment by manulera** [comment]
Ok!

**Comment by ValWood** [comment]
the missing change:

Omh5 
Old
complement(join(1465811..1466035,1466138..1467057,1467311..1467431))
New
complement(join(1465811..1466035,1466138..1467057,1467311..1467317))

**Comment by ValWood** [comment]
note that cut2-Ea2 is already fixed  to these coordinated as part of "pattern not matched to fix"

**Comment by manulera** [comment]
Hi @ValWood I think there are some errors in the gene coordinate changes:

In the coordinate file (`gene-coordinate-change-data.tsv`) for crd1:

The second one is the coordinates for `SPAC22A12.08c.1`, but the first one does not match the coordinates of `SPAC22A12.08c.2` in the contig:

```
# In the tsv file
complement(join(1169939..1170029,1170169..1170260,1170307..1170461,1170504..1170724,1170801..1171270,1171362..1171856,1171900..1171956,1171999..1172126))
# In the contig file
complement(join(1170705..1170724,1170801..1171270,1171362..1171856,1171900..1171956,1171999..1172126))

```

**Comment by ValWood** [comment]
Right. I noticed recently that it did not have a stop codon, so I added it. So the contigs are correct. I  should have checked the gene structure changes file also! 
and correctly I should have reported it, in this file, but I assumed  it just got committed recently ommitted when the splice variant was added (all CDS used to have stop codons for sure).

**Comment by ValWood** [comment]
- [ ] 
tra1 <img width="707" alt="___________tra1_update" src="https://user-images.githubusercontent.com/7359272/209119491-4acceceb-07e5-44b1-ac17-1601904fac37.png">

**Comment by manulera** [comment]
These are now automated
