### ISSUE TITLE
Japonicus LTRs and transposons

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3025]
This is the list from the publication, but I don't think these are annotated in the sequence:

S. japonicus | Tj7 partial               retrotransposon | 1 | 6302 | 6626
-- | -- | -- | -- | --
S.               japonicus | Tj10-1 | 1 | 8433 | 15449
S.               japonicus | Tj9 partial retrotransposon | 1 | 15466 | 15690
S.               japonicus | Tj10 partial retrotransposon | 1 | 15694 | 16213
S.               japonicus | Tj9 partial retrotransposon | 1 | 16212 | 16315
S.               japonicus | Tj9 partial retrotransposon | 1 | 16519 | 16900
S.               japonicus | Tj10-type LTR | 1 | 17038 | 17302
S.               japonicus | Tj5 partial retrotransposon | 1 | 70603 | 70698
S.               japonicus | Tj5-type LTR | 1 | 116685 | 116777
S.               japonicus | Tj6-type LTR | 1 | 1226726 | 1226861
S.               japonicus | Tj3-type LTR | 1 | 1772863 | 1773105
S.               japonicus | Tj10-type LTR | 1 | 1773116 | 1773423
S.               japonicus | Tj3 partial retrotransposon | 1 | 1773971 | 1775917
S.               japonicus | Tj2 partial retrotransposon | 1 | 1784019 | 1786985
S.               japonicus | Tj2 partial retrotransposon | 1 | 1787804 | 1789777
S.               japonicus | Tj7 partial retrotransposon | 1 | 1793309 | 1793526
S.               japonicus | Tj7-type LTR | 1 | 1793596 | 1793806
S.               japonicus | Tj7 partial retrotransposon | 1 | 1793807 | 1794141
S.               japonicus | Tj7 partial retrotransposon | 1 | 1798443 | 1799776
S.               japonicus | Tj7 partial retrotransposon | 1 | 1799825 | 1800437
S.               japonicus | Tj7 partial retrotransposon | 1 | 1800740 | 1805493
S.               japonicus | Tj3 partial retrotransposon | 1 | 1807565 | 1807844
S.               japonicus | Tj1-type LTR | 1 | 1810410 | 1810553
S.               japonicus | Tj1-type LTR | 1 | 1814905 | 1815044
S.               japonicus | Tj1 partial retrotransposon | 1 | 1819503 | 1824403
S.               japonicus | Tj1-type LTR | 1 | 1824730 | 1824873
S.               japonicus | Tj6 partial retrotransposon | 1 | 1825097 | 1825578
S.               japonicus | Tj7-type LTR | 1 | 1825579 | 1825789
S.               japonicus | Tj6 partial retrotransposon | 1 | 1825789 | 1828782
S.               japonicus | Tj7 partial retrotransposon | 1 | 1830098 | 1830311
S.               japonicus | Tj7 partial retrotransposon | 1 | 1830366 | 1831709
S.               japonicus | Tj6 partial retrotransposon | 1 | 1832964 | 1833470
S.               japonicus | Tj10 partial retrotransposon | 1 | 1833471 | 1834093
S.               japonicus | Tj7 partial retrotransposon | 1 | 1835170 | 1836530
S.               japonicus | Tj7 partial retrotransposon | 1 | 1836585 | 1836754
S.               japonicus | Tj6 partial retrotransposon | 1 | 1838046 | 1841058
S.               japonicus | Tj7-type LTR | 1 | 1841058 | 1841269
S.               japonicus | Tj6 partial retrotransposon | 1 | 1841270 | 1841781
S.               japonicus | Tj1-type LTR | 1 | 1841974 | 1842117
S.               japonicus | Tj6 partial retrotransposon | 1 | 1844491 | 1847040
S.               japonicus | Tj6 partial retrotransposon | 1 | 1847614 | 1848759
S.               japonicus | Tj7-type LTR | 1 | 1848810 | 1849021
S.               japonicus | Tj6 partial retrotransposon | 1 | 1849022 | 1849535
S.               japonicus | Tj10 partial retrotransposon | 1 | 1850229 | 1851632
S.               japonicus | Tj5 partial retrotransposon | 1 | 1853107 | 1853648
S.               japonicus | Tj3 partial retrotransposon | 1 | 1855410 | 1855677
S.               japonicus | Tj5-type LTR | 1 | 1856921 | 1857169
S.               japonicus | Tj9 partial retrotransposon | 1 | 1857282 | 1858159
S.               japonicus | Tj6 partial retrotransposon | 1 | 1858434 | 1859029
S.               japonicus | Tj3 partial retrotransposon | 1 | 1860552 | 1861017
S.               japonicus | Tj9 partial retrotransposon | 1 | 1981079 | 1982736
S.               japonicus | Tj3 partial retrotransposon | 1 | 1982735 | 1983499
S.               japonicus | Tj3 partial retrotransposon | 1 | 1984573 | 1985706
S.               japonicus | Tj8 partial retrotransposon | 1 | 1985707 | 1988401
S.               japonicus | Tj9 partial retrotransposon | 1 | 1988401 | 1990843
S.               japonicus | Tj9 partial retrotransposon | 1 | 1992264 | 1993730
S.               japonicus | Tj5 partial retrotransposon | 1 | 1993734 | 1994260
S.               japonicus | Tj8 partial retrotransposon | 1 | 1994699 | 1996942
S.               japonicus | Tj3 partial retrotransposon | 1 | 1996963 | 1998977
S.               japonicus | Tj9 partial retrotransposon | 1 | 1998978 | 2001069
S.               japonicus | Tj5-type LTR | 1 | 2001070 | 2001227
S.               japonicus | Tj9-type LTR | 1 | 2001491 | 2001867
S.               japonicus | Tj9-type LTR | 1 | 3511108 | 3511362
S.               japonicus | Tj4-type LTR | 1 | 3511455 | 3511736
S.               japonicus | Tj2-type LTR | 1 | 3511805 | 3511907
S.               japonicus | Tj10-type LTR | 1 | 4226143 | 4226394
S.               japonicus | Tj3 partial retrotransposon | 1 | 4226727 | 4226904
S.               japonicus | Tj4-type LTR | 1 | 4227254 | 4227402
S.               japonicus | Tj10 partial retrotransposon | 1 | 4232960 | 4233782
S.               japonicus | Tj10 partial retrotransposon | 1 | 4234059 | 4235109
S.               japonicus | Tj3-1 | 1 | 4235110 | 4240620
S.               japonicus | Tj2-type LTR | 1 | 4243472 | 4243569
S.               japonicus | Tj4 partial retrotransposon | 1 | 4243570 | 4247588
S.               japonicus | Tj4 partial retrotransposon | 1 | 4264645 | 4267637
S.               japonicus | Tj4 partial retrotransposon | 1 | 4269499 | 4271056
S.               japonicus | Tj2 partial retrotransposon | 1 | 4271990 | 4272610
S.               japonicus | Tj2 partial retrotransposon | 1 | 4290578 | 4291456
S.               japonicus | Tj9 partial retrotransposon | 2 | 656 | 1174
S.               japonicus | Tj5 partial retrotransposon | 2 | 1173 | 1693
S.               japonicus | Tj5 partial retrotransposon | 2 | 2754 | 3240
S.               japonicus | Tj10 partial retrotransposon | 2 | 22219 | 22486
S.               japonicus | Tj8 partial retrotransposon | 2 | 22519 | 22775
S.               japonicus | Tj10-type LTR | 2 | 23983 | 24232
S.               japonicus | Tj8-type LTR | 2 | 92887 | 93107
S.               japonicus | Tj1-type LTR | 2 | 965579 | 965772
S.               japonicus | Tj6-type LTR | 2 | 971022 | 971140
S.               japonicus | Tj6-type LTR | 2 | 1048090 | 1048208
S.               japonicus | Tj9-type LTR | 2 | 1827054 | 1827445
S.               japonicus | Tj5-type LTR | 2 | 1827706 | 1827863
S.               japonicus | Tj9-2 | 2 | 1827864 | 1833799
S.               japonicus | Tj9 partial retrotransposon | 2 | 1834184 | 1834356
S.               japonicus | Tj8 partial retrotransposon | 2 | 1834357 | 1838569
S.               japonicus | Tj10 partial retrotransposon | 2 | 1840391 | 1843843
S.               japonicus | Tj10 partial retrotransposon | 2 | 1844118 | 1845243
S.               japonicus | Tj8 partial retrotransposon | 2 | 1846185 | 1847669
S.               japonicus | Tj9 partial retrotransposon | 2 | 1847670 | 1849344
S.               japonicus | Tj10-type LTR | 2 | 1849345 | 1849466
S.               japonicus | Tj9 partial retrotransposon | 2 | 1849470 | 1852184
S.               japonicus | Tj9-type LTR | 2 | 3826981 | 3827184
S.               japonicus | Tj2-type LTR | 2 | 3827306 | 3827520
S.               japonicus | Tj2 partial retrotransposon | 2 | 3827881 | 3829106
S.               japonicus | Tj9 partial retrotransposon | 2 | 3829603 | 3830155
S.               japonicus | Tj9 partial retrotransposon | 2 | 3830155 | 3830270
S.               japonicus | Tj8-type LTR | 2 | 3830271 | 3830525
S.               japonicus | Tj3 partial retrotransposon | 2 | 3830612 | 3831489
S.               japonicus | Tj9-type LTR | 2 | 3831490 | 3831963
S.               japonicus | Tj8 partial retrotransposon | 2 | 3832453 | 3832754
S.               japonicus | Tj5-type LTR | 2 | 3832755 | 3833001
S.               japonicus | Tj8 partial retrotransposon | 2 | 3833002 | 3833387
S.               japonicus | Tj2-type LTR | 2 | 3833388 | 3833508
S.               japonicus | Tj9 partial retrotransposon | 2 | 3833958 | 3835595
S.               japonicus | Tj9-1 | 2 | 3844777 | 3850818
S.               japonicus | Tj9 partial retrotransposon | 2 | 3850835 | 3851722
S.               japonicus | Tj9 partial retrotransposon | 2 | 3855279 | 3856797
S.               japonicus | Tj9 partial retrotransposon | 2 | 3856795 | 3859766
S.               japonicus | Tj9-type LTR | 2 | 3865841 | 3866205
S.               japonicus | Tj8 partial retrotransposon | 2 | 3866206 | 3866997
S.               japonicus | Tj1-type LTR | 3 | 463398 | 463627
S.               japonicus | Tj9-type LTR | 3 | 849083 | 849555
S.               japonicus | Tj8 partial retrotransposon | 3 | 849763 | 850017
S.               japonicus | Tj3 partial retrotransposon | 3 | 850819 | 852006
S.               japonicus | Tj9 partial retrotransposon | 3 | 852007 | 852716
S.               japonicus | Tj9 partial retrotransposon | 3 | 852716 | 854150
S.               japonicus | Tj8 partial retrotransposon | 3 | 854151 | 854406
S.               japonicus | Tj9-3 | 3 | 854593 | 860527
S.               japonicus | Tj9 partial retrotransposon | 3 | 863504 | 863961
S.               japonicus | Tj8 partial retrotransposon | 3 | 864427 | 868555
S.               japonicus | Tj10-type LTR | 3 | 3035381 | 3035590
S.               japonicus | Tj3 partial retrotransposon | 4 | 13787 | 15714
S.               japonicus | Tj5 partial retrotransposon | 4 | 35278 | 37290
S.               japonicus | Tj8 partial retrotransposon | 4 | 37979 | 38534
S.               japonicus | Tj5 partial retrotransposon | 4 | 43082 | 43549
S.               japonicus | Tj3 partial retrotransposon | 4 | 43550 | 46302
S.               japonicus | Tj2-type LTR | 4 | 46349 | 46580
S.               japonicus | Tj8 partial retrotransposon | 4 | 46581 | 50237
S.               japonicus | Tj3 partial retrotransposon | 4 | 50238 | 50504
S.               japonicus | Tj8 partial retrotransposon | 4 | 50505 | 51234
S.               japonicus | Tj3 partial retrotransposon | 4 | 51235 | 52156
S.               japonicus | Tj5-2 | 4 | 52157 | 57975
S.               japonicus | Tj3 partial retrotransposon | 4 | 57975 | 58442
S.               japonicus | Tj8 partial retrotransposon | 4 | 58441 | 59267
S.               japonicus | Tj2-type LTR | 4 | 59268 | 59606
S.               japonicus | Tj8 partial retrotransposon | 4 | 59607 | 59981
S.               japonicus | Tj5-1 | 4 | 60041 | 65323
S.               japonicus | Tj3 partial retrotransposon | 4 | 65324 | 66242
S.               japonicus | Tj8 partial retrotransposon | 4 | 66243 | 67183
S.               japonicus | Tj10 partial retrotransposon | 4 | 67353 | 68007
S.               japonicus | Tj6-2 | 4 | 75171 | 80201
S.               japonicus | Tj6 partial retrotransposon | 4 | 83354 | 83592
S.               japonicus | Tj10 partial retrotransposon | 4 | 83891 | 88136
S.               japonicus | Tj4 partial retrotransposon | 4 | 88164 | 89317
S.               japonicus | Tj10-type LTR | 4 | 89318 | 89487
S.               japonicus | Tj9 partial retrotransposon | 4 | 91205 | 95332
S.               japonicus | Tj5 partial retrotransposon | 4 | 95332 | 95858
S.               japonicus | Tj7 partial retrotransposon | 4 | 107052 | 107329
S.               japonicus | Tj4 partial retrotransposon | 4 | 118983 | 120012
S.               japonicus | Tj2-type LTR | 4 | 124195 | 124533
S.               japonicus | Tj6-1 | 4 | 133352 | 138381
S.               japonicus | Tj6 partial retrotransposon | 4 | 143217 | 145268
S.               japonicus | Tj10-type LTR | 4 | 146633 | 146844
S.               japonicus | Tj6 partial retrotransposon | 4 | 147375 | 148991
S.               japonicus | Tj9 partial retrotransposon | 5 | 133 | 600
S.               japonicus | Tj9 partial retrotransposon | 5 | 3528 | 4555
S.               japonicus | Tj9 partial retrotransposon | 5 | 4245 | 5364
S.               japonicus | Tj9-type LTR | 5 | 5481 | 5758
S.               japonicus | Tj10-type LTR | 5 | 9370 | 9634
S.               japonicus | Tj4-type LTR | 5 | 9671 | 10015
S.               japonicus | Tj2-type LTR | 5 | 10011 | 10236
S.               japonicus | Tj8-type LTR | 5 | 10602 | 10836
S.               japonicus | Tj5 partial retrotransposon | 5 | 39887 | 40414
S.               japonicus | Tj5 partial retrotransposon | 5 | 44982 | 45507
S.               japonicus | Tj9 partial retrotransposon | 5 | 45598 | 47129
S.               japonicus | Tj5 partial retrotransposon | 5 | 47124 | 47737
S.               japonicus | Tj5 partial retrotransposon | 5 | 48009 | 49232
S.               japonicus | Tj10-type LTR | 5 | 54564 | 54828
S.               japonicus | Tj2 partial retrotransposon | 5 | 55187 | 55939
S.               japonicus | Tj5 partial retrotransposon | 5 | 56157 | 56320
S.               japonicus | Tj1 partial retrotransposon | 5 | 56635 | 57720
S.               japonicus | Tj10 partial retrotransposon | 5 | 57812 | 59021
S.               japonicus | Tj10 partial retrotransposon | 5 | 59296 | 59771
S.               japonicus | Tj10 partial retrotransposon | 5 | 59998 | 61032
S.               japonicus | Tj3 partial retrotransposon | 5 | 61033 | 63136
S.               japonicus | Tj3 partial retrotransposon | 5 | 68360 | 72206
S.               japonicus | Tj9 partial retrotransposon | 5 | 72743 | 73112
S.               japonicus | Tj7 partial retrotransposon | 5 | 73775 | 73868
S.               japonicus | Tj10 partial retrotransposon | 5 | 83373 | 83774
S.               japonicus | Tj10 partial retrotransposon | 5 | 84049 | 84871
S.               japonicus | Tj7-type LTR | 5 | 87264 | 87476
S.               japonicus | Tj4 partial retrotransposon | 5 | 87477 | 89323
S.               japonicus | Tj10 partial retrotransposon | 5 | 89537 | 91409
S.               japonicus | Tj10 partial retrotransposon | 5 | 91684 | 92506
S.               japonicus | Tj4 partial retrotransposon | 6 | 64313 | 65391
S.               japonicus | Tj6 partial retrotransposon | 6 | 69842 | 74816
S.               japonicus | Tj6 partial retrotransposon | 7 | 2722 | 2894
S.               japonicus | Tj3 partial retrotransposon | 7 | 2895 | 3162
S.               japonicus | Tj2-1 | 7 | 3728 | 9347
S.               japonicus | Tj4-type LTR | 7 | 9693 | 9915
S.               japonicus | Tj2-type LTR | 7 | 9937 | 10037
S.               japonicus | Tj3-2 | 7 | 11316 | 16818
S.               japonicus | Tj5 partial retrotransposon | 7 | 16819 | 17209
S.               japonicus | Tj2 partial retrotransposon | 8 | 100 | 440
S.               japonicus | Tj10 partial retrotransposon | 8 | 441 | 713
S.               japonicus | Tj10 partial retrotransposon | 8 | 485 | 912
S.               japonicus | Tj4-1 | 8 | 1033 | 10907
S.               japonicus | Tj9-type LTR | 8 | 11099 | 11320
S.               japonicus | Tj9-type LTR | 8 | 13751 | 14206
S.               japonicus | Tj10 partial retrotransposon | 10 | 332 | 5220
S.               japonicus | Tj3 partial retrotransposon | 11 | 1 | 730
S.               japonicus | Tj3-type LTR | 11 | 916 | 1183
S.               japonicus | Tj3 partial retrotransposon | 11 | 2769 | 2955
S.               japonicus | Tj9 partial retrotransposon | 11 | 8916 | 10283
S.               japonicus | Tj5 partial retrotransposon | 11 | 10283 | 10759
S.               japonicus | Tj9 partial retrotransposon | 11 | 11120 | 14055
S.               japonicus | Tj10 partial retrotransposon | 11 | 14056 | 14366
S.               japonicus | Tj6 partial retrotransposon | 12 | 8 | 377
S.               japonicus | Tj6 partial retrotransposon | 12 | 376 | 699
S.               japonicus | Tj7-type LTR | 12 | 2461 | 2627
S.               japonicus | Tj6 partial retrotransposon | 12 | 3658 | 4053
S.               japonicus | Tj6 partial retrotransposon | 12 | 4073 | 4367
S.               japonicus | Tj7-type LTR | 12 | 6158 | 6324
S.               japonicus | Tj6 partial retrotransposon | 12 | 7012 | 7746
S.               japonicus | Tj7-type LTR | 12 | 9809 | 9971
S.               japonicus | Tj6 partial retrotransposon | 12 | 11822 | 12145
S.               japonicus | Tj5 partial retrotransposon | 13 | 9553 | 9733
S.               japonicus | Tj10 partial retrotransposon | 13 | 9988 | 10433
S.               japonicus | Tj10-type LTR | 14 | 1563 | 1814
S.               japonicus | Tj3 partial retrotransposon | 14 | 2147 | 2324
S.               japonicus | Tj3-3 | 14 | 2749 | 8229
S.               japonicus | Tj6 partial retrotransposon | 15 | 4 | 1033
S.               japonicus | Tj2 partial retrotransposon | 15 | 1506 | 3291
S.               japonicus | Tj3 partial retrotransposon | 15 | 3822 | 7930
S.               japonicus | Tj8 partial retrotransposon | 17 | 459 | 2100
S.               japonicus | Tj10 partial retrotransposon | 17 | 2100 | 2533
S.               japonicus | Tj8 partial retrotransposon | 17 | 3680 | 5237
S.               japonicus | Tj9 partial retrotransposon | 17 | 5236 | 5898
S.               japonicus | Tj3 partial retrotransposon | 18 | 25 | 254
S.               japonicus | Tj5 partial retrotransposon | 18 | 746 | 1278
S.               japonicus | Tj3 partial retrotransposon | 18 | 2650 | 4100
S.               japonicus | Tj5 partial retrotransposon | 18 | 4182 | 4608
S.               japonicus | Tj9 partial retrotransposon | 18 | 4649 | 4845
S.               japonicus | Tj9 partial retrotransposon | 18 | 4962 | 5073
S.               japonicus | Tj7 partial retrotransposon | 19 | 4693 | 4975
S.               japonicus | Tj5 partial retrotransposon | 19 | 4974 | 5169
S.               japonicus | Tj4 partial retrotransposon | 20 | 706 | 1431
S.               japonicus | Tj9 partial retrotransposon | 20 | 2868 | 3317
S.               japonicus | Tj3 partial retrotransposon | 20 | 4771 | 5123
S.               japonicus | Tj5 partial retrotransposon | 21 | 1 | 578
S.               japonicus | Tj3 partial retrotransposon | 21 | 579 | 3504
S.               japonicus | Tj9 partial retrotransposon | 21 | 4043 | 4211
S.               japonicus | Tj9 partial retrotransposon | 22 | 1 | 652
S.               japonicus | Tj9 partial retrotransposon | 22 | 769 | 1163
S.               japonicus | Tj8 partial retrotransposon | 22 | 2824 | 3388
S.               japonicus | Tj5 partial retrotransposon | 22 | 3389 | 4188
S.               japonicus | Tj5 partial retrotransposon | 23 | 1 | 862
S.               japonicus | Tj10-type LTR | 23 | 862 | 1119
S.               japonicus | Tj5 partial retrotransposon | 23 | 1127 | 2691
S.               japonicus | Tj3 partial retrotransposon | 23 | 2692 | 2887
S.               japonicus | Tj9 partial retrotransposon | 24 | 797 | 1105
S.               japonicus | Tj8 partial retrotransposon | 24 | 1114 | 1661
S.               japonicus | Tj3 partial retrotransposon | 24 | 2784 | 2947
S.               japonicus | Tj7 partial retrotransposon | 28 | 178 | 1170
S.               japonicus | Tj6 partial retrotransposon | 28 | 1296 | 1574
S.               japonicus | Tj1-type LTR | 28 | 1858 | 2001
S.               japonicus | Tj8 partial retrotransposon | 29 | 1 | 2014
S.               japonicus | Tj3 partial retrotransposon | 29 | 2015 | 2345
S.               japonicus | Tj9 partial retrotransposon | 30 | 427 | 2145

**Comment by mah11** [comment]
should this go on the japonicus tracker?
