### ISSUE TITLE
prp10-1 find allele description

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3035]
We took advantage of the thermosensitive growth phenotype of the yeast prp10-1 mutant
strain [35], which harbors two point mutations in SAP155, initially selected in a genetic screen, to study
the ability of various Sap155 alleles to restore growth at restrictive temperature (37 C).

**Comment by mah11** [comment]
done; was in PMID:9837997:

"Sequencing the 1.7 kb region between a HindIII site and the stop codon revealed two mutation sites. One is present at position 3266 and results in replacement of alanine with valine. The other mutation is located at position 3290, leading to a change from serine to phenylalanine."

gotta love 'em - nt positions & aa changes!
