### ISSUE TITLE
browser dataset, origins

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3045]
There might be a japonicus browser dataset here that we can host? It would be nice to include at least one dataset.
 
Genome-wide identification and characterization of replication origins by deep sequencing.
Xu J, Yanagisawa Y, Tsankov AM, Hart C, Aoki K, Kommajosyula N, Steinmann KE, Bochicchio J, Russ C, Regev A, Rando OJ, Nusbaum C, Niki H, Milos P, Weng Z, Rhind N.
Genome Biol. 2012 Apr 24;13(4):R27. doi: 10.1186/gb-2012-13-4-r27.
PMID: 22531001 Free PMC article.
RESULTS: We have taken a combined experimental and bioinformatic approach to identify and characterize origins of replication in three distantly related fission yeasts: Schizosaccharomyces pombe, Schizosaccharomyces octosporus and Schizosaccharomyces japonicus. Using singl …

**Comment by ValWood** [comment]
@mah11  if you get chance could you have a poke around and see if there is data. I spotted it when looking for the S. j. genome paper (again).
Just about to go down the transposon ally...

**Comment by mah11** [comment]
https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP009399

**Comment by ValWood** [comment]
We  already host the pombe data too.
https://www.pombase.org/jbrowse/?loc=I%3A4566597..4586597&tracks=Forward%20strand%20features%2CReverse%20strand%20features&highlight=

**Comment by mah11** [comment]
I've had a little more of a poke round, and I think the main thing is to get the data in bigWig format.

@kimrutherford - we have a few tracks with data from SRA (e.g. PMID:32101745), so do you remember what we/you did to get bigWig files? I've made a note of which SRA data files we'd need out of the SRP009399 set.

Once we have bigWig files somewhere sensible, the track metadata will be a doddle.

**Comment by mah11** [comment]
Update from chat today: ask Nick Rhind if they have bigWig files.

**Comment by mah11** [comment]
I have finally got round to emailing Nick.

**Comment by ValWood** [comment]
I'll close this one.
