### ISSUE TITLE
Bio Tools entry needs claiming/updating. 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3055]
I can't figure out how to edit.
Mentions Ensembl and EBI.
https://bio.tools/t?page=1&q=%27PomBase%27&sort=score

I don't know who set this up but PomBase doesn't show up in the expected categories (like [MOD] + [phenotype and genotype], so definitely not us...

Thre are a couple of other weird things that show ina search for PomBase

**Comment by mah11** [comment]
From looking at https://biotools.readthedocs.io/en/latest/contributors_guide.html, I gather we could open a ticket at https://github.com/bio-tools/biotoolsRegistry/issues.

Note that they have a [PomBase](https://bio.tools/pombase) entry and a separate entry for the [motif search](https://bio.tools/pombase_motif_search); the latter looks wronger (it's the one that mentions Ensembl and EBI).

p.s. I also found email from May 2020 about the pombase entry, subject line "wtf?"

**Comment by ValWood** [comment]
hmm, maybe I should delete that line, but yes wtf!

Did you also see 
PomBase data slicer
Pombase VEP
PomBase assembly converter.

These should be  renamed and handed over to Ensembl

**Comment by mah11** [comment]
It's Friday afternoon, so I took a stab at it:
https://github.com/bio-tools/biotoolsRegistry/issues/530

**Comment by ValWood** [comment]
What's still to do here, did they do the edits?

**Comment by ValWood** [comment]
OK, I can take this from here.

**Comment by kimrutherford** [comment]
I've requested ownership of PomBase and the motif search.

**Comment by ValWood** [comment]
This is added to teh periodic checks list
