### ISSUE TITLE
Linear elements too many components

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#3077]
I was stealthily trying to go in and delete

-- | -- | -- | -- | --
hop1 | GO:0030998 | linear element | IDA |  
mek1 | GO:0030998 | linear element | IDA

PMID:15226405

but they are from the embl files and I can't update those any longer

"Four components
of LinEs have been identified: Rec10, Rec25, Rec27, and
very recently Mug20"

and in PMID:15226405 the authors just say that hop1 and mek1 localize to the LinEs

**Comment by Antonialock** [comment]
also

19756689
16532353

**Comment by Antonialock** [comment]
(recent paper agrees only those 4 proteins are core components: https://pubmed.ncbi.nlm.nih.gov/33825974/)

**Comment by ValWood** [comment]
The components should probably be annotated  in https://pubmed.ncbi.nlm.nih.gov/33825974/
also, it's good confirmation. Will add that too.

**Comment by mah11** [comment]
Pity GO has thrown `coincident_with` on the trash heap ... hop1 & mek1 hanging around LinEs is exactly the sort of situation that qualifier was intended for.

**Comment by ValWood** [comment]
I thought we were keeping occurs_it internally?

Does colocalizes with work?

**Comment by mah11** [comment]
I don't understand the question. `occurs_in` is not for CC annotations.

**Comment by mah11** [comment]
I think I could try annotating hop1 & mek1 to `colocalizes_with` linear element ... turns out LinE doesn't have a path to protein complex ...

**Comment by ValWood** [comment]
Occurs_at

**Comment by ValWood** [comment]
>I think I could try annotating hop1 & mek1 to colocalizes_with linear element ... turns out LinE doesn't have a path to protein complex ...

right that could work. I tend not to use colocalized with but it does seem a shame to lose the connection here...

**Comment by mah11** [comment]
> Occurs_at

is still not for CC annotations

**Comment by mah11** [comment]
done
