### ISSUE TITLE
problem with rec15 external reference

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#3078]
Rec15 uniprot external reference links to hop1

**Comment by mah11** [comment]
Links on rec15 gene page look fine to me too. Which link(s) on which page(s) went wrong?

**Comment by Antonialock** [comment]
I can#t see the issue now.

**Comment by mah11** [comment]
might've been fixed by the website fixes Kim just did

**Comment by Antonialock** [comment]
I'm sure I double checked I was on the correct gene page! But ya never know...xD
