### ISSUE TITLE
Function for unknown

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3089]
FYI
@bahler Jurg
@snezhkaoliferenko  you will like this one!

Current annotation
https://www.pombase.org/gene/SPAC3H5.09c

mitochondrial protein, human KIAA0100 ortholog

New paper from Fly:
<html><head></head><body>

  | Neuman SD, Jorgensen JR, Cavanagh AT, Smyth JT, Selegue JE, Emr SD, Bashirullah A. | Related Articles

  | The Hob proteins are novel and conserved lipid-binding proteins at ER-PM contact sites.
  | J Cell Sci. 2022 Mar 1;135(5).
  | PMID: 34415038

**Comment by ValWood** [comment]
Very confusing that   they call it hob2 since we already have hob1 & hob3 for BAR domain proteins.

**Comment by ValWood** [comment]
i.e. https://www.yeastgenome.org/locus/YPR117W has now been named HOB2 in S. cerevisiae, although no mention of the paralog FMP27

**Comment by ValWood** [comment]
For now I have gone with
/colour=7
/product="ER-PM contact site phospholipid-binding protein Hob2 (predicted)"
/GO="aspect=P; term=endoplasmic reticulum-plasma membrane tethering; GOid=GO:0061817; evidence=TAS; db_xref=PMID:34415038; date=20210823"
/GO="aspect=F; term=protein-membrane adaptor activity; GOid=GO:0043495; annotation_extension=part_of(GO:0061817); evidence=TAS; db_xref=PMID:34415038;  date=20210823"
/GO="aspect=F; term=phosphatidylinositol binding; GOid=GO:0035091; evidence=TAS; db_xref=db_xref=PMID:34415038; date=20210823"
/primary_name="hob2"


and added the name as it will be universal nomenclature.

**Comment by snezhkaoliferenko** [comment]
oh cool melikes!
