### ISSUE TITLE
Incorrect orfome ID for SPCC11E10.07c

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3090]
This gene has two "SPD:" db_xrefs.  The first looks correct (http://www2.riken.jp/SPD/19/19F10.html) but the "SPD:23/23B01" looks wrong.  SPAC21E11.06 also has "SPD:23/23B01" as a db_xref.

I noticed this while testing a change in the code that generates the website.  Sometime the SPCC11E10.07c page had the "19/19F10" links in External references and sometimes "SPD:23/23B01".

I've checked Chado and there are no other genes with two SPD db_xrefs.  And there are no other SPD dx_xrefs that appear in two different CDS features.

```
FT   CDS             complement(join(1464773..1465061,1465158..1465600,1465656..1465795,1465853..1466006))
FT                   /colour=2
FT                   /product="translation initiation factor eIF2B alpha
FT                   subunit Gcn3"
FT                   /db_xref="SPD:19/19F10"
FT                   /db_xref="SPD:23/23B01"
FT                   /gene="SPCC11E10.07c"
FT                   /systematic_id="SPCC11E10.07c"
```

**Comment by mah11** [comment]
Well spotted. I deleted SPD:23/23B01 from SPCC11E10.07c. Val can reopen this if there was any reason not to fix it that way.
