### ISSUE TITLE
2 genes with the same primary name

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3098]
Somehow we seem to have 2 eri1's

I will remove from
https://www.pombase.org/gene/SPAC227.19c(unpublished)
I thought we had a check for this?, check

**Comment by mah11** [comment]
> I thought we had a check for this?

Yes, it's been reported in the chado_checks log since Aug. 18th (log.2021-08-18-21-53-04.chado_checks)

I didn't fix it because I didn't know which one was correct, and I was too busy with manuscripts to ask ;)

**Comment by ValWood** [comment]
OK, I now remember I added the eri1 recently. I must not have done the full due diligence before I added. Now removing....
