### ISSUE TITLE
after multi-gene phenotypes implemented

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#311]
Once multigene phenotypes are implemented, these annotation will need migrating|:

&gt; There are only 12.  I'm currently storing them as properties in Chado
&gt; with type "with", just like IPI/IGIs.  It was easy to do and they're
&gt; easy to find and model in a different way later if needed.

Original comment by: ValWood

**Comment by Antonialock** [comment]
SPAC11E3.09-delta  is elongated in WT background PMID:1464318

for rsc4 it looks like there are quite a few dbl mutant phenotypes and the paper hasnt been done yet so it can wait until full curation
