### ISSUE TITLE
different relation display

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3114]
https://www.pombase.org/reference/PMID:28771613

sometimes displays part_of and sometimes involved_in

<img width="899" alt="Screenshot 2021-09-13 at 14 52 05" src="https://user-images.githubusercontent.com/7359272/133117338-9cb796af-aea3-4f48-a384-80f6cc697c62.png">

Can we make it always 'involved_in' ?

**Comment by mah11** [comment]
Hang on, previous comment is about the other extension; sorry!

Same approach should work for the part_of vs. involved_in, though - remove the existing extension, and add one using the "involved in biological process" option. I'll check & make sure the website config will do something sensible.

**Comment by mah11** [comment]
both say 'involved in' now
