### ISSUE TITLE
fix alleles from other to 'amino acid insertion'

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3123]
These all seem to be in the same session and it isn't in Canot, so am assuming a spreadsheet:

F47,SPAC23D3.02:allele-36,aa 306-340 deleted; GYPSKVQNIHETF inserted after K305,{}
K22,SPAC23D3.02:allele-23,GVPLL inserted after L48,{}
K32,SPAC23D3.02:allele-18,GYPSQ inserted after Q36,{}
F49,SPAC23D3.02:allele-30,RGTPF inserted after F124,{}
K33,SPAC23D3.02:allele-19,GVPQV inserted after V42,{}
K9,SPAC23D3.02:allele-26,GYPLM inserted after M82,{}
K8,SPAC23D3.02:allele-3,GVPLD inserted after D331,{}
K35,SPAC23D3.02:allele-33,RGTPY inserted after Y251,{}
K19,SPAC23D3.02:allele-9,RGTPS inserted after S67,{}
K33deltaK27,SPAC23D3.02:allele-20,aa 42-46 deleted; GVPQK inserted after V42,{}
K10,SPAC23D3.02:allele-16,RGTPP inserted after P6,{}
D4E-2,SPNCRNA.98:allele-107,G160C,GC inserted after nt 158,GC inserted after nt 164,{}
F37,SPAC23D3.02:allele-12,LGYPC inserted after C157,{}
,SPNCRNA.98:allele-68,C180U,U inserted after nt 176,{}
K11A,SPAC23D3.02:allele-4,GVPPGLVPPGLVPTPGVPPGLVFHE inserted after E94,{}
snu1-5' extension,SPSNRNA.01:allele-18,AU inserted at 5' end,{}
,SPNCRNA.98:allele-9,A146U,G159U,nt148-150 deletion,{}
K27,SPAC23D3.02:allele-22,GVPQK inserted after K45,{}
K11,SPAC23D3.02:allele-27,GVPHE inserted after E94,{}
D4E-3,SPNCRNA.98:allele-117,GC inserted after nt 164,{}
F41,SPAC23D3.02:allele-2,GVPRV inserted after V242,{}
K26a,SPAC23D3.02:allele-37,RGTPGVGTPD inserted after D183,{}
K3,SPAC23D3.02:allele-25,RGTPN inserted after N50,{}
K17,SPAC23D3.02:allele-5,RGTPP inserted after P27,{}
K33deltaK22,SPAC23D3.02:allele-21,aa 42-46 deleted; GVPLL inserted after V42,{}
F44,SPAC23D3.02:allele-35,GVPLL inserted after L258,{}
K23,SPAC23D3.02:allele-24,KGYPS inserted after S49,{}
K26,SPAC23D3.02:allele-31,RGTPD inserted after D183,{}
,SPNCRNA.98:allele-10,U88G,nt84 deletion,8 nucleotides inserted after nt83,{}
K20,SPAC23D3.02:allele-28,RGTPI inserted after I99,{}
K23deltaK14,SPAC23D3.02:allele-6,aa 49-57 deleted; KGYP inserted after S49,{}
K1,SPAC23D3.02:allele-32,GVPLA inserted after A195,{}
K5,SPAC23D3.02:allele-14,GVPLS inserted after S171,{}
K26b,SPAC23D3.02:allele-38,RGTPGGVGPGVGTPD inserted after D183,{}
F45,SPAC23D3.02:allele-10,RGTPT inserted after T146,{}
K12,SPAC23D3.02:allele-17,KGYPN inserted after N8,{}
F42,SPAC23D3.02:allele-15,RGTPC inserted after C174,{}
K18,SPAC23D3.02:allele-8,RGTPG inserted after G64,{}
,SPNCRNA.98:allele-1,U88G,nt84-88 deletion,131 nucleotides inserted after nt83,{}
F46,SPAC23D3.02:allele-29,GVPLF inserted after F124,{}
K15,SPAC23D3.02:allele-34,RGTPI inserted after I254,{}
D4E-1,SPNCRNA.98:allele-106,GC inserted after nt 158,GC inserted after nt 164,{}
F39,SPAC23D3.02:allele-13,RGTPL inserted after L170,{}
K1a,SPAC23D3.02:allele-39,GVPPVGLGPGLVPLA inserted after A195,{}

These should  all be L170-RGTPL  etc.
(note that the prompt currently requests 170-RGTPL but I think we should allow and encourage 
the reporting of the AA at the insertion site as this will allow  automated QC of alleles to sequence)
I will open a ticket to update the prompt.

Also  @mah11  the munging of spreadsheet data should probably be on your list (although I don't think we need any specific documentation for this)

**Comment by ValWood** [comment]
Allele detatis should also be preceded by "rfc2-"

**Comment by mah11** [comment]
> These all seem to be in the same session and it isn't in Canto

If they aren't in Canto, they aren't in any session.

**Comment by ValWood** [comment]
I mean same publication.

**Comment by mah11** [comment]
done
