### ISSUE TITLE
fix PRO IDs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3124]
PRO IDs used for more than one gene - CHECK FAILURE:  expected 0 but got 4
  PR:000028992	4d5512a5dc8ea4bc	SPBC19C2.09.1
  PR:000028992	4d5512a5dc8ea4bc	SPBC6B1.08c.1
  PR:000044737	7c2513328f82d364	SPBC28F2.12.1
  PR:000044737	7c2513328f82d364	SPCC757.07c.1

**Comment by ValWood** [comment]
First one:
PR:000028992 4d5512a5dc8ea4bc SPBC6B1.08c.1

refers to
ofd1 protein sequestering activity
  | sequesters sre1 part of negative regulation of SREBP signaling pathway during cellular response to hypoxia active form sre1/Clv:(1-440)

will fix to "sequesters sre1" to 
"sre1/Clv:(1-440)"
(active form is for ofd1 'annotated entity')
need to also do a global check that active form is only used with the  'annotated entity'

**Comment by ValWood** [comment]
fixed  4d5512a5dc8ea4bc  to PR: substrate.
check.

**Comment by mah11** [comment]
I can add PomBase systematic IDs to our mini-pro OBO file using `property_value` tags, e.g.

    property_value: pombase_gene_id SPAC20G8.05c

Would that help with linking? If so, I'll get on it while Kim's on holiday.

OBO format documentation on `property_value`:
> **property_value**
> This tag binds a property to a value in this instance. The value of this tag is a relationship type id, a space, and a value specifier. The value specifier may have one of two forms; in the first form, it is just the id of some other instance, relationship type or term. In the second form, the value is given by a quoted string, a space, and datatype identifier. See IDs for more information on legal datatype identifiers.

**Comment by mah11** [comment]
oops, just noticed @kimrutherford wasn't already tagged here

**Comment by kimrutherford** [comment]
> Would that help with linking? If so, I'll get on it while Kim's on holiday.

I think so.  It would be good to start recording the genes like that.

A bit of work is needed at my end to change the OBO loader to handle properties: pombase/chobo#16

**Comment by ValWood** [comment]
Rremember that long discussion we had yesterday about not being able to use 
PomBase:xxx,PRO:xxxx
I was having a total brain fart. I just started typing the ticket and remembered that wasn't actually the problem. The problem was that I had used the same PRO: form on different genes.
However I think it will still be good to include the PomBase ID explicit;y. It will allow us to run checks  that we have the correct gene-pro combination.
I will open a discussion as to whether we want to force  PomBase,PRO if a PRO ID is used.

**Comment by mah11** [comment]
> I think so. It would be good to start recording the genes like that.

OK, I'll add them to the mini-ontology file. 

> A bit of work is needed at my end to change the OBO loader to handle properties

There are already `property_value` tags in some of the ontologies we use, so I don't think it'll cause problems for them to be ignored in one more obo file in the meantime.

**Comment by kimrutherford** [comment]
> I've committed a pombe_mini_PR.obo file with property_value tags in place.

Thanks!  I think this is a good solution.

**Comment by ValWood** [comment]
Do I need to open a website ticket  for the next step?

**Comment by kimrutherford** [comment]
> Do I need to open a website ticket for the next step?

I'm not sure.  I'm a bit lost about this.  Is this related?: pombase/website#1710

**Comment by ValWood** [comment]
Yes that is the ticket!

**Comment by ValWood** [comment]
I think this can close then/
