### ISSUE TITLE
strip "(predicted)"off PomBase protein coding products

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3126]
I was going to do this with a perl one-liner, BUT I can't because I don't think we want to strip the (predicted) off the non-coding RNAs. A lot of these are really tentative....

chromosome3.contig:FT                   /product="acetyl-CoA ligase Pcs60 (predicted)"
chromosome3.contig:FT                   /product="intergenic RNA (predicted)"
chromosome3.contig:FT                   /product="non-coding RNA (predicted)"
chromosome3.contig:FT                   catabolic process Vms1 (predicted)"
chromosome3.contig:FT                   /product="nucleolar RNA-binding protein NIFK (predicted)"
chromosome3.contig:FT                   (predicted)"
chromosome3.contig:FT                   /product="antisense RNA (predicted)"
chromosome3.contig:FT                   /product="SPX/EXS domain protein (predicted)"
chromosome3.contig:FT                   /product="non-coding RNA, poly(A)-bearing (predicted)"
chromosome3.contig:FT                   /product="ribosome biogenesis protein Nsa2 (predicted)"
chromosome3.contig:FT                   (predicted)"
chromosome3.contig:FT                   /product="aromatic aminotransferase (predicted)"
chromosome3.contig:FT                   /product="non-coding RNA, poly(A)-bearing (predicted)"

**Comment by kimrutherford** [comment]
> We should be able to do that in the code that reads the contig files.

Would you like me to do this in the loading code?

**Comment by ValWood** [comment]
OK that might be safer!

**Comment by ValWood** [comment]
Action is jsut to remove "prredicted" from the protein product lines for now.

**Comment by kimrutherford** [comment]
> Would you like me to do this in the loading code?

That's done for tonight's load.  I'll check on Tuesday morning.

**Comment by ValWood** [comment]
Right, I might need to do my change again, it is for tonights load. I'll fix tomorrow.

**Comment by kimrutherford** [comment]
> That's done for tonight's load. I'll check on Tuesday morning.

Looks OK.
