### ISSUE TITLE
Canto wikipedia

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3140]
we need to update this Wikipedia entry
https://en.wikipedia.org/wiki/Canto_(gene_curation_tool)

**Comment by ValWood** [comment]
Existing 
Canto is a web-based tool that encourages community curation of genes. The tool allows professional curators and published authors alike to collaborate and increase inclusion in public biological database.[1] Canto is developed as part of the PomBase project,[2] which looked at Schizosaccharomyces pombe (fission yeast), and funded by the Wellcome Trust. Currently, Canto is used for Schizosaccharomyces pombe, Komagataella pastoris, and Generic Gene Ontology Implementation. However, it can be configured to use gene identifiers for any species or ontology, making it a diverse program.

**Comment by ValWood** [comment]
suggestions please - this text needs replacing!

**Comment by ValWood** [comment]
Canto is a web-based tool that provides an intuitive curation interface for both curators and researchers, to support community curation [1]. Canto was developed as part of the PomBase project (University of Cambridge /Ucl) [2], but  now supports pathogen-host interactions for PHi-base (Rothamsted research) and the curation of  phenotypes and genetic interactions at FlyBase (University of Cambridge).

**Comment by ValWood** [comment]
the person who wrote this wiki page knows Canto pretty well...

**Comment by ValWood** [comment]
I just  revised and updated (first ever Wikipedia edits- much easier than when I last attempted).
@Antonialock @kimrutherford  would you mind checking and suggesting any revisions.

**Comment by kimrutherford** [comment]
Looks good to me!  I've added a link from the PomBase wiki page to the Canto page.

**Comment by ValWood** [comment]
thanks!

**Comment by Antonialock** [comment]
🥇
