### ISSUE TITLE
human ortholog

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3142]
SPAC6B12.14c C16orf72 
(source jackhmmer)

**Comment by ValWood** [comment]
@bahler this might interest you.  Unknown - previously only identified in yeast, now conserved to human. I still can't find any functional info.

**Comment by bahler** [comment]
Interesting that priority unstudied can go up as well as down..

Cheers,
-Jürg

**Comment by ValWood** [comment]
Yes, I think it would go up quite a bit if all of the fungal conserved unknown proteins were assessed to see if the conservation  could be extended to metazoa.
