### ISSUE TITLE
Duplicate publication: Maturation of Krp1 (/Krpl?), an endopeptidase from the fission yeast Schizosaccharomyces pombe

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3143]
These two PMIDs have the same title.  Both have annotation.  And both have separate PubMed pages?

https://www.pombase.org/reference/PMID:8736869
https://www.pombase.org/reference/PMID:8879047

There are separate journal pages but one title contains "Krpl" and one contains "Krp1":

https://portlandpress.com/biochemsoctrans/article-abstract/24/2/211S/92914/Maturation-of-Krpl-an-endopeptidase-from-the?redirectedFrom=fulltext
https://portlandpress.com/biochemsoctrans/article-abstract/24/3/503S/91506/Maturation-of-Krp1-an-endopeptidase-from-the?redirectedFrom=fulltext

**Comment by ValWood** [comment]
These two PMIDs have the same title. Both have annotation. And both have separate PubMed pages?

https://www.pombase.org/reference/PMID:8736869
https://www.pombase.org/reference/PMID:8879047

different annotations too!
I think these Phil transactions  were a bit weird, sometimes they do seem to be duplicates of other papers.
This was @Antonialock  PhD supervisor, - do you remember anything about these ? (long shot!)

**Comment by ValWood** [comment]
Despite having the same title, and very similar content, these are, in fact, slightly different publications. Image 3 is differently presented in the 2 (more rows in the gel are shown). It is all a bit weird but I say we quietly ignore. I think  they might be conference proceedings which often end up very similar.
