### ISSUE TITLE
Disease genes with no human ortholog

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3147]
I think I've asked about this before, but just in case:

There are some disease genes with no human ortholog:

https://www.pombase.org/results/from/id/12b3b1b6-1d10-4379-ad77-e2994ae5ecae

**Comment by ValWood** [comment]
Yup, the histones are in the logs ATM,  HGNC have recently renamed all the histones and this one still needs fixing.

The others are mainly RNAs and I have not (yet) routinely curated orthologs  for those, but I will add for these 2)

**Comment by ValWood** [comment]
These are all fixed.

I added the RNA orthologs to the conserved_one_to_one.txt as
SPNCRNA.214     URS00004A7003_9606
SPNCRNA.82      URS00003B7E88_9606
I'm not sure if these will parse?

**Comment by kimrutherford** [comment]
> I'm not sure if these will parse?

**Comment by kimrutherford** [comment]
> I'm not sure if these will parse?

The human genes IDs have to be gene names from HGNC.  At the moment at least.

**Comment by ValWood** [comment]
Brain fart. Fixed teh telomerase RNA to HGNC:ID
However i can't find RNAase MRP identifier ,  have asked. Will fix shortly.

**Comment by mah11** [comment]
> RNAase MRP identifier

https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:19273

**Comment by ValWood** [comment]
fixed
