### ISSUE TITLE
check that these alleles are in independent copies of cdc2

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3150]
are these really 2 copies of cdc2
cdc2-33 (A177T aa) cdc2-L55M (aa)
cdc2-33 (A177T aa) cdc2-T167E (aa)
cdc2-33 (A177T aa) cdc2-E179R (aa)
cdc2-33 (A177T aa) cdc2-T167Y (aa)
see
https://github.com/pombase/website/issues/1255

**Comment by mah11** [comment]
Looks like they are.

I only checked the multiples involving cdc2-33, but of those, I fixed one and all the rest really are two copies of cdc2. Papers: PMID:1655416, PMID:7774573, PMID:8437586, PMID:2038306 all OK; fixed cdc2+ cdc2-33 orb3-167 from PMID:8522609.

**Comment by ValWood** [comment]
Thanks for that..I remember there are quite a lot of experiments with different cdc2 variations
