### ISSUE TITLE
help prompts in HTP submission form

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3152]
It might be useful to have an example row 
https://www.pombase.org/documentation/phenotype-data-bulk-upload-format

(a submitter just supplied WT in the strain background column which seems reasonable. 

- [ ] Could we have an example row ? or at least a note about this row in the spreadsheet header?

- [ ] Is there any restriction on database prefixes? This submission used "BioProject".
Should we start with a list of known repositories + an 'other' option? 
We will need to check that new ones are recognised repositories that we can link to,  and have an entry in the  database abbreviations file  (where is this again?)

**Comment by ValWood** [comment]
@mah11 do you have time to do this?

**Comment by ValWood** [comment]
I will need @kimrutherford help here, but it should be quick to implement on a call

**Comment by ValWood** [comment]
When I opened this ticket, it sounds as though there is a "mock spreadsheet"  but I cannot find that.
@kimrutherford  do you know. If we do not have such a thing I can close this ticket.


Although @manulera  when you are preparing the spreadsheet for Maria's phenotypes you might have suggestions how the submission of the HTP datasets might be made more user friendly.

**Comment by kimrutherford** [comment]
> When I opened this ticket, it sounds as though there is a "mock spreadsheet" but I cannot find that.

That sounds familiar but I can't find it.

**Comment by ValWood** [comment]
Maybe we talked about having a spreadsheet with a sample row for each  datatype, but never did it?

There seems to be quite a barrier for providing the data in the correct format (which is understandable), although we have had partail success. 

I wonder if some sort of submission app  to create and validate  could be a student project?

**Comment by ValWood** [comment]
I will close this. For now I have added a  this task to potential student project list.
@manulera  if you can suggest easy ways to improve this (either the process or the documentation), please open a ticket
