### ISSUE TITLE
Decide priority for "chaperoned by" and "activated by" in target of section

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3155]
There's a warning in the log about "chaperoned by" and "activated by":

https://curation.pombase.org/dumps/builds/pombase-build-2021-11-28/logs/log.2021-11-28-19-33-26.web-json-write

So currently they always appear at the bottom of the list.

The configuration is here: https://github.com/pombase/pombase-config/blob/47d29fa35f24d16b57ffe6edf14080d366129fd1/website/pombase_v2_config.json#L5198

**Comment by kimrutherford** [comment]
I've added documentation: https://github.com/pombase/website/wiki/Config-file#target_of_config

**Comment by ValWood** [comment]
No priority configured for "activated by" (from SPBC29A10.04)
No priority configured for "chaperoned by" (from SPBC1105.17)
No priority configured for "chaperoned by" (from SPMIT.11)
No priority configured for "activated by" (from SPAC644.14c)
No priority configured for "activated by" (from SPAC644.14c)
No priority configured for "activated by" (from SPAC644.14c)
No priority configured for "activated by" (from SPAC644.14c)
No priority configured for "chaperoned by" (from SPBC11B10.10c)

I don't understand what 'priority'  is in this context. @mah11  can you explain?

**Comment by kimrutherford** [comment]
The two relations need to be added to the `relation_priority` setting for the "Target of" section in `pombase_v2_config.json`.

There's a bit about that in the documentation: https://github.com/pombase/website/wiki/Config-file#target_of_config

**Comment by mah11** [comment]
Priority is how we specify the order in which extensions appear. It works the same way for "forward" extensions and for "target of" reciprocals but both need to be set (e.g. yfg 1 activated by yfg2 during M phase vs. yfg1 during M phase activated by yfg2).

As an aside, in the file the "forward" priority list is called `extension_relation_order` whereas the "target of" list is `relation_priority` ... but they basically work the same way.

**Comment by ValWood** [comment]
Done
