### ISSUE TITLE
Investigate triage status in web-json-write log file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3156]
I'm not sure if these messages point to a problem or are pointless:

reference PMID:30569039 has no canto_triage_status
reference PMID:23442799 has no canto_triage_status
reference PMID:28615445 has no canto_triage_status
reference PMID:15123683 has no canto_triage_status
reference PMID:18408053 has no canto_triage_status
reference PMID:16754953 has no canto_triage_status
reference PMID:25266290 has no canto_triage_status
reference PMID:29440398 has no canto_triage_status
reference PMID:25776556 has no canto_triage_status
reference PMID:33256608 has no canto_triage_status
reference PMID:12220683 has no canto_triage_status
reference PMID:20923774 has no canto_triage_status
reference PMID:26016518 has no canto_triage_status
reference PMID:11083870 has no canto_triage_status
reference PMID:20802492 has no canto_triage_status
reference PMID:9256449 has no canto_triage_status
reference PMID:29937227 has no canto_triage_status
reference PMID:10219083 has no canto_triage_status
reference PMID:19933165 has no canto_triage_status
reference PMID:29514954 has no canto_triage_status
reference PMID:29411923 has no canto_triage_status
reference PMID:32908386 has no canto_triage_status
reference PMID:2989945 has no canto_triage_status
reference PMID:18591258 has no canto_triage_status
reference PMID:28335716 has no canto_triage_status

**Comment by kimrutherford** [comment]
> everything should have a triage status, I think.
> Ill look/fix

Thanks.  It could be a bug so if it's not obvious what's going on, please let me know.

**Comment by mah11** [comment]
These all have triage status "Wrong organism":
PMID:23442799
PMID:18408053
PMID:16754953
PMID:25776556
PMID:12220683
PMID:20923774
PMID:9256449
PMID:10219083
PMID:18591258

The rest aren't in Canto at all.

**Comment by kimrutherford** [comment]
Thanks Midori.

The warnings are from incorrect code which I've now fixed.

While checking the PMID list I noticed that some reference pages didn't show the orthologs from the publication (PMID:19933165 for example).  I've fixed that bug so the warnings ended up being indirectly useful.

The code was originally added in pombase/website#628
