### ISSUE TITLE
Lots of warnings from new qualitative gene expression data file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3157]
There are lots of errors from this file:
pombe-embl/external_data/qualitative_gene_expression_data/PMID_12529438_qualitative_expression.txt

At least some of the errors are because of existing annotations in the contig files.

https://curation.pombase.org/dumps/builds/pombase-build-2021-11-30/logs/log.2021-12-01-00-07-47.qualitative

**Comment by ValWood** [comment]
If the exact annotation is in the contigs, we  can just delete the contig entries for PMID:12529438.
What is the easiest way to do that?

**Comment by ValWood** [comment]
@mah11  do you know anything about this? It seems that a new  files is present  (good plan!) for the 
Chen data which  has legacy data in the config file. Can you easily remove the legacy data, or do you want @kimrutherford  t do it.

**Comment by mah11** [comment]
Done.
