### ISSUE TITLE
long non-coding RNA rse1

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3159]
We have reported that the long non-coding RNA rse1, which regulates gametogenesis in fission yeast, potentially interacts with the tRNA D-synthase Dus2 (Cassart et al., 2012; Fauquenoy et al., 2018).

**Comment by ValWood** [comment]
SPNCRNA.111
updated, name and "colour=2" (we can later display characterised in bold?)

**Comment by ValWood** [comment]
I made these changes in December.

/synonym="SPNCRNA.1652"
/product="cis-acting lincRNA Ste11 repressor"
/systematic_id="SPNCRNA.111"
/primary_name="rse1"
/colour=2

I didn't expect characterization status to work, but I thought the primary name and product update would.\
@kimrutherford  What am I missing?

**Comment by kimrutherford** [comment]
Looks like there two features with the ID "SPNCRNA.111" and it's only loading the second.  That definitely needs a load warning!

**Comment by ValWood** [comment]
It might be good to look at this ticket at the same time.
https://github.com/pombase/pombase-chado/issues/953

I am sure that I merged some RNas and that the ones I merged are no longer merged. Although I don't see a record of any merges here https://www.pombase.org/status/gene-coordinate-changes
so maybe I misremembered. There are definitely ncRNAs that *should be merged (I made a list of many but there will be others).

It is one of the things I want Manu to look at, but it would be useful if you can see any  genes which obviously have the same identifier, I can fix these.

**Comment by ValWood** [comment]
What is the status here?

I thought it would be covered by
https://github.com/pombase/curation/issues/3241?

but 
SPNCRNA.11 is not in the list.

**Comment by kimrutherford** [comment]
> What is the status here?

I've made a separate issue for warning about duplicate IDs: pombase/pombase-chado/issues/968

> I thought it would be covered by
> https://github.com/pombase/curation/issues/3241?

I did a Chado query to get the list in that issue but your feature isn't getting into Chado so it won't be in the list.

> but SPNCRNA.11 is not in the list.

That's probably because there is still a duplicate ID in the contig files.  This bit is still true:

> Looks like there two features with the ID "SPNCRNA.111" and it's only loading the second.

```
FT   ncRNA           complement(3978331..3982106)
FT                   /db_xref="PMID:29914874"
FT                   /db_xref="PMID:18488015"
FT                   /db_xref="EMBL:AU009915"
FT                   /db_xref="PMID:21511999"
FT                   /db_xref="PMID:29395921"
FT                   /synonym="SPNGAF1"
FT                   /synonym="SPNCRNA.1652"
FT                   /product="cis-acting lincRNA Ste11 repressor"
FT                   /systematic_id="SPNCRNA.111"
FT                   /primary_name="rse1"
FT                   /colour=2
FT   ncRNA           complement(3978616..3980728)
FT                   /db_xref="PMID:29914874"
FT                   /systematic_id="SPNCRNA.111"
FT                   /product="non-coding RNA"
```

**Comment by ValWood** [comment]
RIght, historically I merged a number of largely identical features, after approval from the originators.
It looks like Maria's data did not observe the merges.

Once I have a list  of the duplicates, I can  re-merge these.
I knew this wouldn't be so straightforward.....

**Comment by ValWood** [comment]
Ignore me. They have the same IDs...(I think I was expecting the other systematic ID that the entry was merged into, but this isn't necessary)
