### ISSUE TITLE
updates to drug list

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3176]
These results show that micafungin selectively inhibits the function of Bgs4, whereas Bgs1 and Bgs3 are not affected by this antifungal.
PMID:34959732

 The same results were previously described for the other two classes of GS inhibitors, the glycopeptide papulacandin B and the acidic terpenoid enfumafungin that also selectively inhibited Bgs4 [29].

Cytokinesis is blocked in both wild-type and pbr1-8 strains treated with lethal concentrations of the echinocandin drug anidulafungin, suggesting that this drug affects the function of Bgs4 and Bgs1 and/or Bgs3

**Comment by ValWood** [comment]
Hi @kimrutherford 

could you add these rows:

micafungin || bgs4 || 1,6 branched 1,3-beta-glucan synthase || cell wall synthesis || Bgs1 and Bgs3 are unaffected || PMID:34959732
papulacandin B ||  bgs4 || 1,6 branched 1,3-beta-glucan synthase || cell wall synthesis  || Bgs1 and Bgs3 are unaffected || PMID: 21115488
enfumafungin ||  bgs4 || 1,6 branched 1,3-beta-glucan synthase || cell wall synthesis  || Bgs1 and Bgs3 are unaffected || PMID: 21115488
echinocandin (anidulafungin) ||  bgs4 bgs1 and/or bgs3 || 1,6 branched 1,3-beta-glucan synthase || cell wall synthesis/ cytokinesis is blocked    || PMID:34959732

to
https://www.pombase.org/browse-curation/drugs-known-pombe-targets

and remove the existing row for echinocandin

**Comment by kimrutherford** [comment]
> echinocandin (anidulafungin)

The chebi page says `anidulafungin is a echinocandin` so do you need both chemicals in the table?

**Comment by kimrutherford** [comment]
I've added those rows and tidied the table a little bit - some of the columns references were in the wrong column.

I think I committed the changes before the load got the point of processing the documentation so it should be visible in the morning.

**Comment by ValWood** [comment]
It can be just anidulafungin. I might be tempted to add   echinocandin in the note field because this is used more and likely what users will search for in the table. The echinocandins
are caspofungin, micafungin and anidulafungin. At some point we could have a think how to include some of these on gene pages with chebi links , but not soon.

**Comment by kimrutherford** [comment]
> It can be just anidulafungin.

I added "see also echinocandin" in the "Other" column.  Is that OK?

> At some point we could have a think how to include some of these on gene pages with chebi links , but not soon.

I was going to ask you about that.  :-)
