### ISSUE TITLE
Links for centromeres

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3182]
https://www.pombase.org/status/centromeres

links don't show features, figure out why

**Comment by ValWood** [comment]
@kimrutherford  do you know what is required to display these features?
 not urgent.

**Comment by kimrutherford** [comment]
Sorry that was my fault.  I renamed the tracks when we deployed japonicusdb.org but I forgot to update the links in the documentation.  I've done that now so it should be fixed in the morning.
