### ISSUE TITLE
PMID:20051244 binds annotations with E. coli

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3183]
I think they're coming from IntAct.  I assume they need to be filtered?

I noticed because there was an error displaying the extensions.

https://www.pombase.org/reference/PMID:20051244

![binds-e-coli-2](https://user-images.githubusercontent.com/90474/149645672-c962f89e-b4f0-4fab-acea-932c8db451f0.png)

**Comment by ValWood** [comment]
That's right, I opened a ticket about these last week:
https://github.com/pombase/pombase-chado/issues/917

**Comment by kimrutherford** [comment]
Duplicate
