### ISSUE TITLE
allele descriptions, nucleotide

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3191]
nucleotide substitutions should fit the
T123A
T123A,T124A
syntax, but I spotted this earlier in the week.

<img width="302" alt="__kim_allele _errorr" src="https://user-images.githubusercontent.com/7359272/151614665-ae876059-5203-49cf-a215-c09148f242ab.png">

Do we check for non-standard (I  don't think I saw this in the logs)
Unfortunately, I did not record which gene so you might already report these. I just wanted to double-check.

**Comment by kimrutherford** [comment]
> Found it (using intermine!)

Does PombeMine include the session IDs?  I didn't think it did.

**Comment by ValWood** [comment]
Nope but it was enough info to find the gene (which I stupidly committed from the ticket), so that  I could locate the paper and the session.

**Comment by ValWood** [comment]
fixed
