### ISSUE TITLE
Duplicate annotations for PMID:14765108

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3192]
https://www.pombase.org/reference/PMID:14765108

It looks like there are three identical annotations:
```
dis2   has substrate chk1   IDA
dis2   has substrate chk1   IDA
dis2   has substrate chk1   IDA
```

One really is a `has_substrate` annotation.  The other are identical but the relation is `has_direct_input` in Chado.  It's configured to display as "has substrate" as a descendant of GO:0030234 "catalytic activity".

**Comment by kimrutherford** [comment]
> I guess others will be caught by 'exact duplicates' log?

Yep!  The `dis2   has substrate chk1   IDA` annotation is in the duplicates log.  I didn't think to check that.  I made this issue because I thought there could be a bug somewhere.

**Comment by ValWood** [comment]
RIght I haven't been checking all of the logs recently. Concentrating on the allele ones!

**Comment by ValWood** [comment]
fixes dis2 duplicate.
Others will be fixed in logs.
