### ISSUE TITLE
nucleotide allele needs checking

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3197]
I don't think the nucleotides are numbered correctly. + numbering should begin from first base of CDS

  SPBC649.04:allele-2	1187-1225	partial_nucleotide_deletion	d1e54bf1d660f4c8
  SPBC649.04:allele-3	1187-1238	partial_nucleotide_deletion	d1e54bf1d660f4c8
  SPBC649.04:allele-4	1204-1221	partial_nucleotide_deletion	d1e54bf1d660f4c8
  SPBC649.04:allele-5	1183-1223	partial_nucleotide_deletion	d1e54bf1d660f4c8

also check all other un-named alleles in Canto sessions  have disappeared from

 https://curation.pombase.org/dumps/latest_build/logs/log.2022-02-23-22-06-03.chado_checks.unnamed_alleles

**Comment by ValWood** [comment]
You might have this covered...

**Comment by manulera** [comment]
These are fixed. I guess you did it? I fixed in canto the coordinates of 1204-1221, which had been annotated as (-1204)-1221 (minus missing from 1221).

**Comment by ValWood** [comment]
I don't remember doing it!
