### ISSUE TITLE
NOT and not-NOT annotation for the same feature and term

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3198]
I don't know if this is a big deal but:

ecm14 / SPBC337.07c has an annotation for GO:0004181 / metallocarboxypeptidase activity:
https://www.pombase.org/gene/SPBC337.07c

and there is a also a NOT annotation here (sorry big page):
https://www.pombase.org/reference/GO_REF:0000024

The NOT annotation isn't appearing on the gene page, but is in Chado and is in the output GAF files.

**Comment by kimrutherford** [comment]
> The NOT sill does not appear on the page

I didn't commit my fix in time for the load.

**Comment by ValWood** [comment]
OK I will wait to see it  before I remove it!

**Comment by kimrutherford** [comment]
> OK I will wait to see it before I remove it!

Thanks.  The NOT annotation is there now: https://www.pombase.org/gene/SPBC337.07c

**Comment by ValWood** [comment]
Acccording to @Antonialock  it does not have another critical residue
https://github.com/geneontology/go-annotation/issues/3979 GLU at 458
and the NOt isn't outs it is from UniPFrot.

So, I will  keep the NOT and supress the PANTHER annotation instead.
