### ISSUE TITLE
modified forms Term issue: phosphorylated forms for Byr1 and Spk1 (Issue #269)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3209]
byr1/Phos:(S22) = PR:000050583
spk1/Phos:(T199/Y201) = PR:000050584

[Term]
id: PR:000050583
name: protein kinase byr1 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A protein kinase byr1 (Schizosaccharomyces pombe) that has been phosphorylated at the position equivalent to Ser-22 of the amino acid sequence represented by UniProtKB:P10506. Example: UniProtKB:P10506, Ser-22, MOD:00046." [PRO:DAN, PomBase:VW, PMID:33823663]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-byr1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:P10506, Ser-22, MOD:00046" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050581 ! protein kinase byr1 (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050584
name: mitogen-activated protein kinase spk1 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A mitogen-activated protein kinase spk1 (Schizosaccharomyces pombe) that has been phosphorylated at positions equivalent to Thr-199 and Tyr-201 of the amino acid sequence represented by UniProtKB:P27638. Example:UniProtKB:P27638, Thr-199, MOD:00047|Tyr-201, MOD:00048." [PRO:DAN, PomBase:VW, PMID:33823663]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-spk1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:P27638, Thr-199, MOD:00047|Tyr-201, MOD:00048" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050582 ! mitogen-activated protein kinase spk1 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
added with
synonym: "byr1/Phos:(S22)" EXACT PomBase_display_name [PomBase:curators]
property_value: pombase_gene_id SPAC1D4.13
and
synonym: "spk1/Phos:(T199)" EXACT PomBase_display_name [PomBase:curators]
property_value: pombase_gene_id  SPAC31G5.09c

The instructions also say
Parent needs a stanza 
Minimally

[terrm]
Id:
Name:
is_a root node protein

Example
Term]
id: PR:000050516
name: SNF1-like protein kinase ssp2 (Schizosaccharomyces pombe)
def: "A protein that is a translation product of the ssp2 gene in Schizosaccharomyces pombe." [PRO:DAN]
is_a: PR:000000001 ! protein
property_value: pombase_gene_id SPCC74.03c

but these already seem to have one?i wonder if parent stanzas have already been added for everything?

@kimrutherford  this is a 'heads up' in case anything fails as this is the first time I edited this file.

Once  I know this one is OK, I will do the other one.

**Comment by kimrutherford** [comment]
> but these already seem to have one?i wonder if parent stanzas have already been added for everything?

I don't understand that.

If you're adding a new term it needs a parent.  The parent can just be "PR:000000001" because we're not using the structure of the ontology anywhere.

So this is all that's needed in new terms:

```
is_a: PR:000000001 ! protein
```

**Comment by ValWood** [comment]
but is that really needed if they already have (for example) 

is_a: PR:000050581 ! protein kinase byr1 (Schizosaccharomyces pombe)

that seems redundant?

**Comment by kimrutherford** [comment]
> but is that really needed if they already have (for example)
> is_a: PR:000050581 ! protein kinase byr1 (Schizosaccharomyces pombe)

The reasoning is that we shouldn't refer to parent terms that aren't in the file because then it's not a valid OBO file.  PR:000050581 isn't in the file.

There probably isn't a big problem having missing parent terms as we don't to use parent child relations in Chado or on the web site.

**Comment by ValWood** [comment]
OK, but I thought I got 
 PR:000050581 ! protein kinase byr1 (Schizosaccharomyces pombe)
from the file?

I will just use 
is_a: PR:000000001 ! protein

**Comment by ValWood** [comment]
I think I was misreading the instructions...does everything now have

is_a: PR:000000001 ! protein

**Comment by kimrutherford** [comment]
> OK, but I thought I got
> PR:000050581 ! protein kinase byr1 (Schizosaccharomyces pombe)
> from the file?

It's not in our file.  Did you copy and paste that line from the full OBO file?

> I think I was misreading the instructions...does everything now have
> is_a: PR:000000001 ! protein

Lots of terms have that line, but lots don't.  It's a bit inconsistent.

**Comment by ValWood** [comment]
OK, I just checked and all of the ones I added have an is_a to a protein (although I used the is_a to the specific  protein entry in the file  rather than the more general

is_a: PR:000000001 ! protein

from now on I will just use is_a: PR:000000001 ! protein

**Comment by ValWood** [comment]
Is OK
