### ISSUE TITLE
ppk21, missing info

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3229]
A previous study reported that cells deleted for ppk21+ displayed multiple defects in mitosis (Bimbó et al., 2005b)
from
- [x] Bimbó, A., Liu, J., and Balasubramanian, M. K. (2005b). Roles of Pdk1p, a fission yeast protein related to phosphoinositide-dependent protein kinase, in the regulation of mitosis and cytokinesis. Mol. Biol. Cell 16, 3162–3175. doi: 10. 1091/mbc.e04- 09- 0769
(partial curation, predates pombase)

- [x] bimbo PMID:15821139
oddly these are not curated:
Although the remaining 89 protein kinase mutants were able to form colonies under optimal growth conditions, 46% of the mutants exhibited hypersensitivity to at least 1 of the 17 different stress factors tested.

**Comment by ValWood** [comment]
Hi @manu when you have done Marias phenotype data could you do a PHAF file the data from this old protein kinase  screen which has never been curated.

**Comment by manulera** [comment]
Hi @ValWood this is done.

@kimrutherford I added this HTP file to the repo (`PMID_15821139_phaf.tsv`) and it has a new FYECO and FYPO terms that have not been added to the release yet. I guess those will fail to load now, but I am aware and they should be available in the next release.

**Comment by ValWood** [comment]
That's OK, they just go into the logs which reminds me, I haven't looked at for a couple of weeks...

**Comment by kimrutherford** [comment]
> I guess those will fail to load now, but I am aware and they should be available in the next release.

OK, thanks.

**Comment by kimrutherford** [comment]
Hi @manulera

I've changed the contents of the `severity` column of `PMID_15821139_phaf.tsv` to FYPO_EXT terms (from `pombe-embl/mini-ontologies/fypo_extension.obo`) to fix some load warnings.

**Comment by kimrutherford** [comment]
> I've changed the contents of the severity column of PMID_15821139_phaf.tsv to FYPO_EXT terms

All good now: https://www.pombase.org/reference/PMID:15821139
