### ISSUE TITLE
Add cellular component GO:0035974 to pkl1

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3236]
Meiotic spindle pole body is missing. Most likely because the current annotation comes from a paper where they use SPB-less spindles. However, the same paper shows that in normal meiotic spindles pkl1-GFP also localises to the SPBs (see A and C):

![](https://cob.silverchair-cdn.com/cob/content_public/journal/jcs/134/16/10.1242_jcs.253799/1/m_jcs25379903.png?Expires=1653555010&Signature=RfXoEV7iy7MVZM0DmYv92U9-u1nZGZKwHO~-cOH9FjNdvIuJ~7kjP5Lo-dDD3vEIKn0mWrJBqNASBTKHmL-cUrWaHDWfPOm4uTL7v3olP67mwy0oVplParocpNa7fJ7ZLM3OEPRkOFR4Jdgc47E9jqi3ytgVCR~kLumyv~CDMxG9fBWA9Y-qqcb5-jzaFEa9xHYYPrkVFIvP836432QYl5qzePsntY9B79H9sDXHJUZt7EyMjvlI3ESS9OqxNdZtmMCE985hh27jB~cFNtz2EOhDvZBpoOOIm3tjJ0skqsb9yGn4rPFfkOyNZxxabWJzWBn2uK7dGtEAibOfmi5LKQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA)

**Comment by ValWood** [comment]
which PMID is this one?

**Comment by manulera** [comment]
PMID:34346498
https://www.pombase.org/reference/PMID:34346498
