### ISSUE TITLE
Difference between GO:0097431 and GO:0044732

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3237]
## Difference between GO:0097431 and GO:0044732

Writing regarding the difference between cellular component spindle pole (GO:0097431) and cellular component spindle pole body (GO:0044732) in pombe. If assessed with light microscopy and not EM, these two are probably used alike. 

GO:0097431 has only three annotations from light microscopy evidence. One is Ase1 which I think should not be included (see below).

I think annotations from pombe could be safely moved to a single category since they were probably used alike.

However, I think there is even more to it if you look at where the terms are located in the GO tree. I think we should discuss this more in detail (in my todo list), but for these annotations to make sense across-species they should also point somehow to the spindle pole (right now they don't). For example, the function of spindle pole-focusing of kinesin-14 in Drosophila embryos is similar to the pkl1 (also kinesin-14) function in SPB organisation during mitosis.

At the same time, not all proteins that anchor microtubules to the SPBs do so during mitosis/meiosis. There are others that do so during interphase, for nuclear positioning. I imagine that the same is true for other fungi.

![download](https://user-images.githubusercontent.com/22526102/165505100-47b63773-d156-414b-9d47-2465dff813e6.png)

## Ase1 annotation

Also, I am not sure about ase1 annotation inside GO:0097431, which comes from PMID:32502403 (from 2020).

![Screenshot 2022-04-27 at 14 34 20](https://user-images.githubusercontent.com/22526102/165530795-025c7dfa-7093-4243-9201-4b19467f3812.png)

While Ase1 does colocalize with SPBs. It was shown to be outside of the nucleus, bundling the astral microtubules at the outer side of the nucleus and not inside. This was shown in PMID:15647375, by deleting MboI/Mod20 a nonessential component of the fission yeast γ-tubulin complex that is required for nucleation of cytoplasmic astral microtubules during mitosis. In the deletion background, Ase1 does not go to the pole:

![Screenshot 2022-04-27 at 14 36 58](https://user-images.githubusercontent.com/22526102/165531642-7b5df885-0145-4e4f-b47e-2b5105da7109.png)

**Comment by ValWood** [comment]
Yes, there are a couple of reasons for this arrangement in GO. The parents must always be true and obviously the spindle pole body isn't always part of the "spindle". But I agree with you, so I avoid using ""mitotic spindle pole" for annotation (although I see we have 3, so I will migrate those across to "mitotic spindle pole body".


Another outstanding problem is that GO should be species agnostic, and the same concept should be represented by the same term. So I think we should eventually have a single term for "spindle pole/centrosome". I have raised this in the past but there was  a bit of push back from SGD. However many pombe researchers now use "centrosome" in their  publications.

"mitotic spindle pole body" is defined " the microtubule organizing center that forms as part of the mitotic cell cycle"; 
so it also refers to the spindle pole body during intephase. The reason we have separate terms for meiotic /mitotic is that the meiotic SPB seems t be quite structurally different (and the involvement in spore membrane assembly etc).
We could probably have better term names if you can think of them.

At present we can use:
mitotic spindle pole body during (mitotic_interphase) which probably looks a bit bonkers to you!

**Comment by ValWood** [comment]
For the time being I deleted ase1, and migrated plo1 and cka1 to 'mitotic spindle pole body'

**Comment by manulera** [comment]
> mitotic spindle pole body during (mitotic_interphase) which probably looks a bit bonkers to you!

I see, that makes sense. The only thing is that many of these proteins (specially motors and microtubule associated proteins) will have functions similar to those of proteins that localize to the spindle pole in species that do not have SPBs, so it would make sense that there would be a link to spindle pole for those that are in `mitotic spindle pole body during (mitotic_interphase)`

**Comment by ValWood** [comment]
We can discuss this with Pascale.

**Comment by ValWood** [comment]
Actually, I think a lot of my annotations are wrong.
So, the SPB is only during interphase and then it is called the "spindle pole" after elongation?


If this is the case the term label is misleading.
We can discuss this next time we speak.  MAy need to move some annotations too...

**Comment by manulera** [comment]
We can close this, what mattered here was the discussion.
