### ISSUE TITLE
PMID:29188185  genome editing for lactic acid production from glucose and cellobiose

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3239]
@snezhkaoliferenko  mentioned in her talk that some of the biotech papers were a useful source of metabolic data.  I tend to ignore these, but here is one such example:

We could use this as published support for 

https://www.pombase.org/gene/SPAC186.08c
L-lactate dehydrogenase
and maybe some other gene/proteins in this paper?

i wonder how 
https://www.pombase.org/gene/SPAPB1A11.03
cytochrome b2 (L-lactate cytochrome-c oxidoreductase)
fits in?

There may also be some info here about the specificity of SPBC337.11 which we have currently an "unknown".

<img width="921" alt="PMID_29188185-curatable" src="https://user-images.githubusercontent.com/7359272/166450669-3096e15b-2921-4903-baa4-8578c257d71c.png">

FYI @dexink @bahler

**Comment by ValWood** [comment]
the Rhea resource will be useful for these projects:

https://www.rhea-db.org/
You can search on chemicals that are expected to be in reactions.

I also hope  InterMIne will  include Rhea based on the rhea to GO mappings to make it possible to interrogate reaction components
https://github.com/intermine/pombemine/issues/40

**Comment by dexink** [comment]
SPAPB1A11.03 is described as an FMN-binding domain of a Lactate 2-monooxygenase (CDD, Pombase-listed annotations). Maybe they cooperate together as one singular unit would otherwise do on its own? Maybe permitting for an FMN-independent manner of this activity in addition to the FMN-dependent one? This would mean that the current main annotation of cytochrome b2 is misleading re. function (as per the domain annotations).

**Comment by dexink** [comment]
The two proteins linked from rhea are listed under lactate 2-monooxygenase: SPAPB1A11.03 (Q9HDX2, "Uncharacterized lactate 2-monooxygenase PB1A11.03") in addition to one of Mycolicibacterium smegmatis (P21795). The structure of the latter entry's structure in UniProt is shown as a toroid-like homotetrameric complex, while that of S. pombe is shown as a monomer (model, AlphaFold). Do we think it is possible that the quaternary structure shown in UniProt for P21785 is incorrect in that it neglects an additional contributor to the proposed complex? The quaternary structure that is shown, to be honest, does not appear to be a homotetramer as it has been annotated; I counted around ~7 monomer units just looking at it briefly, so this, at least, seems incorrect/inaccurate.

**Comment by dexink** [comment]
The follow are listed evidence for the links between SPAPB1A11.03 and SPAC186.08c in STRING:
KEGG (curated)[https://string-db.org/cgi/setevidence?taskId=bfghjZfnIFHa&sessionId=bpePPi5dB07b&data_channel=database&node1=1809487&node2=1811163]
the comment on this annotation reads: "Manually curated metabolic and signalling pathways were imported from KEGG (February 2021). Pathway neighbors and subunits of the same enzyme/complex were given association links"

**Comment by ValWood** [comment]
This paper 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC554653/pdf/emboj00277-0219.pdf
that is used to support "[L-lactate dehydrogenase (cytochrome) activity], and which we have ISS'd from

"The inactivation of the chromosomal cytochrome b2 gene by
integrative transformation led to a deficiency in L(+)-lactate
dehydrogenase activity and consequently to the inability to
use L(+)-lactate as a sole source of carbon."

I think I need to delete the 
L-lactate dehydrogenase (cytochrome) activity from SGD in favour of the 

lactate 2-monooxygenase activity from Rhea (and update the product description).

Do you agree?

**Comment by ValWood** [comment]
>  I feel that it should be noted that KEGG also lists Glutathione S-transferase Gst1 (SPCC191.09c) as a paralog of
SPAPB1A11.03

I think that is incorrect.  If they are related, it is very distantly as there is no family overlap even at the superfamily level and both have independent orthologs (and other much more closely related proteins).

**Comment by ValWood** [comment]
i can't find a single asssay for 
"L-lactate dehydrogenase (cytochrome) activity" in the  literature?

**Comment by dexink** [comment]
> i can't find a single asssay for "L-lactate dehydrogenase (cytochrome) activity" in the literature?

It seems that annotation from Fusarium may have been the source:
[PaperBLAST Results of SPAPB1A11.03](https://papers.genomics.lbl.gov/cgi-bin/litSearch.cgi?query=>sp|Q9HDX2|YKN3_SCHPO+Uncharacterized+lactate+2-monooxygenase+PB1A11.03+OS%3DSchizosaccharomyces+pombe+(strain+972+%2F+ATCC+24843)+OX%3D284812+GN%3DSPAPB1A11.03+PE%3D3+SV%3D1MFRNYNWFDAKEPISYESEIYAKGLKFQRPQITVDGRHWEQLAVERMTKDAAGYVYGCAGKRETYDKNMESFKKWSIIPNRLIKSGFPDLSTTVFGQKYPFPIALAPVGVQKIFNPEGESGSCAAATREHIPYIISTASATSFEDIEKASGPGERWYQLYWPSNDHQDITISLLNRAKKTGCRVLIVTLDTFILGWRPSDMDNGYDPFLNPDSIGVEHGFSDPVFRKQFKEKHGVEVEENMLEAAKEFAGIVFPGISHDWEDLKFLRKHWDGPIVLKGIMNVPDAKKAVEYGMQGIVVSNHGGRQQDGGVASLTMLPKIVDAVGDKLDVLFDSGVRSGADIAKALALGAKMVLIGRPYVYGLALEGSSGVSHVIRCLLGDLELTLHLSGIVSVKPKDLNRDVLYKEE&Search=Search)

**Comment by dexink** [comment]
> This paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC554653/pdf/emboj00277-0219.pdf that is used to support "[L-lactate dehydrogenase (cytochrome) activity], and which we have ISS'd from
> 
> "The inactivation of the chromosomal cytochrome b2 gene by integrative transformation led to a deficiency in L(+)-lactate dehydrogenase activity and consequently to the inability to use L(+)-lactate as a sole source of carbon."
> 
> I think I need to delete the L-lactate dehydrogenase (cytochrome) activity from SGD in favour of the
> 
> lactate 2-monooxygenase activity from Rhea (and update the product description).
> 
> Do you agree?

[This paper](https://pubmed.ncbi.nlm.nih.gov/4593578/) is from '74 characterizing the same protein, allegedly (as referenced by PMID: 27853284)

**Comment by dexink** [comment]
> This paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC554653/pdf/emboj00277-0219.pdf that is used to support "[L-lactate dehydrogenase (cytochrome) activity], and which we have ISS'd from
> 
> "The inactivation of the chromosomal cytochrome b2 gene by integrative transformation led to a deficiency in L(+)-lactate dehydrogenase activity and consequently to the inability to use L(+)-lactate as a sole source of carbon."
> 
> I think I need to delete the L-lactate dehydrogenase (cytochrome) activity from SGD in favour of the
> 
> lactate 2-monooxygenase activity from Rhea (and update the product description).
> 
> Do you agree?

I agree that this is likely the first to report the nucleotide sequence and state the biochemical value to the organism, simultaneously; however, do we believe that this is truly the only enzyme with "L-lactate dehydrogenase (cytochrome)" activity in yeast? Also, why is the "cytochrome" status of the enzyme co-reported as though it is a synonym for lactate dehydrogenase? Is this generally agreed upon? (_the latter two naive questions I answer, myself, below_)

Because I was less familiar with the nomenclature surrounding these enzymes and their respective etymology, here is what I was able to dig up on the distinctions between "L-lactate dehydrogenase", "L-lactate dehydrogenase (cytochrome)", "cytochrome", and "Lactate oxidoreductase":
- "L-lactate dehydrogenase (cytochrome)" and "L-lactate cytochrome c oxidoreductase" are synonyms for the same enzyme ([IUBMB Enzyme Nomenclature](https://iubmb.qmul.ac.uk/enzyme/EC1/1/2/3.html))
- Earliest description of the enzyme and its activity was in 1946 (again, [IUBMB Enzyme Nomenclature](https://iubmb.qmul.ac.uk/enzyme/EC1/1/2/3.html))
- EC number is 1.1.2.3 ([BRENDA](https://www.brenda-enzymes.org/enzyme.php?ecno=1.1.2.3)), and is described as being included within the family of "1 Oxidoreductases"-"1.1 Acting on the CH-OH group of donors"-"1.1.2. With a cytochrome as acceptor"
- For the BRENDA EC number [search results of 1.1.2.3](https://www.brenda-enzymes.org/search_result.php?a=27&W[2]=&l=10&os=1&RN=&W[1]=1.1.2.3&T[1]=1&V[3]=1&W[3]=&T[3]=2&V[4]=1&W[4]=&T[4]=2&W[5]=&T[5]=2&Search=Search), there are 4 hits total with one of them described as "the hydride transfer mechanism involves the transfer of the lactate hydroxyl proton to H373 while the substrate a H atom is transferred as a hydride to the flavin mononucleotide (FMN) prosthetic group anchored in the active site" (PMID: 27220613)

**Comment by dexink** [comment]
A blast using SGD of Cyb2 in S. cerevisiae against other fungi retrieved the expected SPAPB1A11.03 sequence as:

> [gi|12038982](https://www.ncbi.nlm.nih.gov/nuccore/12038982)|emb|CAC19728.1| cytochrome b2 (L-lactate cytochrome-c...  165     [7e-45](https://www.yeastgenome.org/blast-fungal?uploadFile=&program=blastp#12038982)

**Comment by dexink** [comment]
Interestingly, [KEGG has SPAPB1A11.03](https://www.kegg.jp/entry/spo:SPAPB1A11.03) listed as a lactate 2-monooxygenase with the EC number 1.13.12.4, which contradicts what is put forth by other resources and the previously-noted publications.
Additionally, they have [SPAC186.08c](https://www.kegg.jp/entry/spo:SPAC186.08c) listed as a L-lactate dehydrogenase with an EC number of 1.1.1.27 (not 1.1.2.3)

[Here they are, both, shown in the organism's KEGG pathway](https://www.kegg.jp/kegg-bin/show_pathway?spo00620) (_S. pombe_, Pyruvate Metabolism)

**Comment by dexink** [comment]
> Interestingly, [KEGG has SPAPB1A11.03](https://www.kegg.jp/entry/spo:SPAPB1A11.03) listed as a lactate 2-monooxygenase with the EC number 1.13.12.4, which contradicts what is put forth by other resources and the previously-noted publications. Additionally, they have [SPAC186.08c](https://www.kegg.jp/entry/spo:SPAC186.08c) listed as a L-lactate dehydrogenase with an EC number of 1.1.1.27 (not 1.1.2.3)
> 
> [Here they are, both, shown in the organism's KEGG pathway](https://www.kegg.jp/kegg-bin/show_pathway?spo00620) (_S. pombe_, Pyruvate Metabolism)

According to a sequence-based search of [SPAPB1A11.03 in the CATH database](http://www.cathdb.info/version/v4_3_0/superfamily/3.20.20.70/funfam/132/ec), EC 1.13.12.4 was formerly 1.1.3.2. It seems unclear how 1.1.2.3 is related to 1.1.3.2 historically or as it links to this particular lactate dehydrogenase.

**Comment by dexink** [comment]
DeepGOWeb results for SPAPB1A11.03:
![image](https://user-images.githubusercontent.com/7029234/166672957-a2942607-0b3c-4298-82b8-d6a57d21b32c.png)

**Comment by dexink** [comment]
The following advanced search in UniProt retrieved 0 hits:
organism:"Schizosaccharomyces pombe (Fission yeast) [4896]" ec:"(S)-2-hydroxy-acid oxidase [1.1.3.15]"

...suggesting that there is no hydroxy-acid oxidase in _S. pombe_, despite the ubiquity of the protein family.

_S. cerevisiae_ has a family member listed (in absence of _S. pombe_), P00175 (Cyb2), with the description "L-lactate dehydrogenase (cytochrome)"

It seems that this enzyme has not yet been annotated in _S. pombe_.

**Comment by ValWood** [comment]
The problem is probably partly  that UniProt  curators are no longer obligated  annotate to EC numbers because they are no longer  maintained (i.e new enzymes are not necessarily assigned an EC number, and it is not necessarily updated). It is better to use  GO or Rhea instead for activities.

**Comment by ValWood** [comment]
We know that SPAPB1A11.03 is the ortholog of S. cerevisiae Cyb2. My main question  is are both of these annotations correct?

<img width="1295" alt="Screenshot 2022-05-04 at 12 47 37" src="https://user-images.githubusercontent.com/7359272/166675248-752c300e-e26b-4d84-9149-b2d59487de90.png">


One I made based on ortholog to S. cerevisiae cyb2, 
GO:0004460 | L-lactate dehydrogenase (cytochrome) activity
EC | 1.1.2.3/ RHEA | 19909

and one  [L-lactate dehydrogenase (cytochrome) activity GO:0004460)is imported from the Uniprot entry Rhea mapping
(this is EC | 1.13.12.4 RHEA | 16513)

 Rhea are very rarely wrong. @Antonialock how dopes this look to you?

**Comment by ValWood** [comment]
>Interestingly, [KEGG has SPAPB1A11.03](https://www.kegg.jp/entry/spo:SPAPB1A11.03)

KEGG is largely uncurated (particularly for fission yeast). They reconstruct the pathway based on EC numbers,  but are not responsible for the curation. If the EC number is incorrectly assigned the pathway will be misrepresented.

**Comment by dexink** [comment]
I think that lactate 2-monooxygenase is no longer used for the same enzyme. Additionally, the support for that GO annotation is IEA

**Comment by dexink** [comment]
From what is indicated by UniProt, it seems like Pombase may be the last remaining resource referring to this GO term, which does not appear to be based on experimental evidence.

**Comment by ValWood** [comment]
That is weird because we get the data nightly from GOA (which comes directly from Rhea), I will look into it.

**Comment by ValWood** [comment]
Are you referring to 
[lactate 2-monooxygenase activity](https://www.ebi.ac.uk/QuickGO/term/GO:0050040) Source: UniProtKB-EC?

This annotation is still in the UniPRot entry:
https://www.uniprot.org/uniprot/Q9HDX2
and this is where we pull it from.

It seems to come from an EC to GO mapping, and an EC to GO mapping:
i) I will filter the annotation from PomBase
ii) it seems that  the term should be merged or obsoleted)

**Comment by ValWood** [comment]
I'm still a bit confused by this...I will asked UniPRot the source of the 
[GO:0050040]  lactate 2-monooxygenase activity  annotation

**Comment by dexink** [comment]
In UniProt, [Reactome annotations (subsection: "Enzyme and pathway databases")](https://www.uniprot.org/uniprot/Q9HDX2) predicts the localization of SPAPB1A11.03 as peroxisomal, also based on homology to human homolog

**Comment by dexink** [comment]
The closest hit in PaperBLAST focused specifically on characterizing a homolog is that of QulF ([46% identity, 96% coverage](https://papers.genomics.lbl.gov/cgi-bin/showAlign.cgi?def1=sp|Q9HDX2|YKN3_SCHPO%20Uncharacterized%20lactate%202-monooxygenase%20PB1A11.03%20OS=Schizosaccharomyces%20pombe%20(strain%20972%20/%20ATCC%2024843)%20OX=284812%20GN=SPAPB1A11.03%20PE=3%20SV=1&def2=QULF_PENCI%20/%20P0DUR7&seq1=MFRNYNWFDAKEPISYESEIYAKGLKFQRPQITVDGRHWEQLAVERMTKDAAGYVYGCAGKRETYDKNMESFKKWSIIPNRLIKSGFPDLSTTVFGQKYPFPIALAPVGVQKIFNPEGESGSCAAATREHIPYIISTASATSFEDIEKASGPGERWYQLYWPSNDHQDITISLLNRAKKTGCRVLIVTLDTFILGWRPSDMDNGYDPFLNPDSIGVEHGFSDPVFRKQFKEKHGVEVEENMLEAAKEFAGIVFPGISHDWEDLKFLRKHWDGPIVLKGIMNVPDAKKAVEYGMQGIVVSNHGGRQQDGGVASLTMLPKIVDAVGDKLDVLFDSGVRSGADIAKALALGAKMVLIGRPYVYGLALEGSSGVSHVIRCLLGDLELTLHLSGIVSVKPKDLNRDVLYKEE&acc2=SwissProt::P0DUR7)), which examines the homolog's role in Quinolactacin A2 biosynthesis. 
Here is an excerpt from the paper than describes the precise mechanism:

> The FMN- dependent alpha-hydroxy acid dehydrogenase qulF than functions as an oxidative decarboxylase which converts N-methylkynurenine into 2- aminobenzoylacetamide via 2 tandem reactions, including dehydrogenation and decarboxylation (PubMed:32663343).

**Comment by ValWood** [comment]
@marcfeuermann  UniPRot says

Hi Val,
SPAPB1A11.03 was last updated by Viv Junker 14 years ago. At that time, we did not tag the evidence and I was not able to retrace the origin of the annotation. Anyway, I agree that the lactate-2 monooxygenase-related annotation must be removed (which I did). I've propagated data from CYB2 of S. cerevisiae, but I still have a doubt. In S. cerevisiae and other yeasts, CYB2 consists of two discrete domains, an N-terminal cytochrome b domain and a C-terminal flavin-binding domain. The cytochrome b domain is required for efficient cytochrome c reduction.
Moreover, all have predicted mitochondrial targeting signals. SPAPB1A11.03 lacks both the targeting signal and the N-terminal cytochrome b domain, so I wondered if it is really an ortholog of S. cerevisiae CYB2. In the absence of any experimental data, I think we should not associate any reaction to SPAPB1A11.03.
What do you think ?
Thanks.
Marc.


---

This agrees with @dexink  I agree, there so I will:
1.  annotate as very generic
FMN-dependent alpha-hydroxy acid dehydrogenase 
2. remove orthologs
3. Remove GO annotation and revert to 'unknown" (process )

**Comment by ValWood** [comment]
> I am also somewhat skeptical of the CDS after looking at the ORF

I checked and I think the CDS is OK, aligns well with Cryophillus start:

<img width="628" alt="Screenshot 2022-05-06 at 14 52 53" src="https://user-images.githubusercontent.com/7359272/167146994-76385577-1b45-4802-80a4-c294d2181c4b.png">

**Comment by dexink** [comment]
> > I am also somewhat skeptical of the CDS after looking at the ORF
> 
> I checked and I think the CDS is OK, aligns well with Cryophillus start:
> 
> <img alt="Screenshot 2022-05-06 at 14 52 53" width="628" src="https://user-images.githubusercontent.com/7359272/167146994-76385577-1b45-4802-80a4-c294d2181c4b.png">

Excellent! Then we're all in agreement then.
With the last find I mentioned with the biosynthetic cluster, I tried looking through Pombase for genes assigned related GO terms; as a result, I think the kynurenine pathway annotations may need to be improved in S. pombe

**Comment by ValWood** [comment]
Great, that gives us a good starting point for Monday!

**Comment by dexink** [comment]
It certainly does!
I will probably continue checking things over the weekend, though, in between doing some "touristy" things in London.
For example, nearly all of the [biosynthetic gene annotations (spo00400)](https://www.pombase.org/term/KEGG_PW:spo00400) have come directly from KEGG. [Aro1](https://www.pombase.org/gene/SPAC1834.02) is described as "pentafunctional" while all of the assigned GO terms list the evidence code IEA via UniRule.

**Comment by ValWood** [comment]
We shoulds open a new ticket for the  kynurenine pathway related.

**Comment by dexink** [comment]
I was just about to ask about whether there was already a ticket! ha
...Because the more I check into Aro1, the more I don't like it.
The length, weight, etc., were originally published in 1987. It is purported as being conserved across all domains of life, but the orthology links from the Pombase entry page almost all fail to return hits in other eukaryotes, with the exception of the western clawed frog and zebrafish homologs via Flybase (the pair of them have always given me problems in the past when it comes to reliable annotations of CDSs).
![image](https://user-images.githubusercontent.com/7029234/167165875-b7172f09-ca54-411b-acfa-1caaaaee4fa1.png)

BLAST in ENSEMBL Fungi against other Schizosaccharomyces species fails to return a single hit, most of them returning 5 per genome, which tracks if the gene was in fact poorly predicted.
![image](https://user-images.githubusercontent.com/7029234/167165488-ddd89ae3-b14d-4065-a419-5e81bd7d725d.png)

**Comment by ValWood** [comment]
I started a new ticket for  "kynurenine pathway" with the comment above.

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/3242

**Comment by Antonialock** [comment]
Oxidoreductase seems correct from this paper?
https://www.pnas.org/doi/pdf/10.1073/pnas.0506939102

**Comment by ValWood** [comment]
Which protein?

**Comment by Antonialock** [comment]
whoa, I did not comment on this 23 hours ago! I deleted the comment, I don't know where that came from.

**Comment by ValWood** [comment]
@PCarme  PMID:29188185 looks like it may have useful experimental data

**Comment by ValWood** [comment]
I completely forgot about PMID:29188185 most pdc101, pdc102, gut2, adh8 of these are still "unpublished"
but I think we can close the ticket.

I will open a new ticket about SPAPB1A11.03
