### ISSUE TITLE
Publications in Canto, missing from PubMed

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3243]
There are 17 publications in Canto that are now gone from PubMed.   Some have sessions:

|name                          |uniquename   |link                                                                |session                                                 |
|------------------------------|-------------|--------------------------------------------------------------------|--------------------------------------------------------|
|Cell composition or WT feature|PMID:25519574|https://curation.pombase.org/pombe/view/object/pub/10646?model=track|                                                        |
|Curatable                     |PMID:11032848|https://curation.pombase.org/pombe/view/object/pub/5099?model=track |https://curation.pombase.org/pombe/curs/b0fb13950d3eadd5|
|Curatable                     |PMID:24888876|https://curation.pombase.org/pombe/view/object/pub/10400?model=track|https://curation.pombase.org/pombe/curs/c8d46642c97d787e|
|Curatable                     |PMID:24888877|https://curation.pombase.org/pombe/view/object/pub/10399?model=track|https://curation.pombase.org/pombe/curs/4ab8ff9b6cc0a980|
|Curatable                     |PMID:27392239|https://curation.pombase.org/pombe/view/object/pub/11348?model=track|https://curation.pombase.org/pombe/curs/67026591584779dd|
|Curatable                     |PMID:27913728|https://curation.pombase.org/pombe/view/object/pub/11679?model=track|https://curation.pombase.org/pombe/curs/a9f7569dbb433a9d|
|Erratum                       |PMID:24009652|https://curation.pombase.org/pombe/view/object/pub/10064?model=track|                                                        |
|Erratum                       |PMID:25078613|https://curation.pombase.org/pombe/view/object/pub/10495?model=track|                                                        |
|Erratum                       |PMID:25217569|https://curation.pombase.org/pombe/view/object/pub/10537?model=track|                                                        |
|Loaded in error               |PMID:22275432|https://curation.pombase.org/pombe/view/object/pub/230?model=track  |https://curation.pombase.org/pombe/curs/b686a59680dc93ac|
|Other                         |PMID:25776683|https://curation.pombase.org/pombe/view/object/pub/10746?model=track|                                                        |
|Review or comment             |PMID:22976396|https://curation.pombase.org/pombe/view/object/pub/9589?model=track |                                                        |
|Review or comment             |PMID:27002055|https://curation.pombase.org/pombe/view/object/pub/11215?model=track|                                                        |
|Review or comment             |PMID:27687092|https://curation.pombase.org/pombe/view/object/pub/11596?model=track|                                                        |
|Review or comment             |PMID:28872942|https://curation.pombase.org/pombe/view/object/pub/12008?model=track|                                                        |
|Wrong organism                |PMID:23018174|https://curation.pombase.org/pombe/view/object/pub/9578?model=track |                                                        |
|Wrong organism                |PMID:27002032|https://curation.pombase.org/pombe/view/object/pub/11216?model=track|                                                        |

**Comment by ValWood** [comment]
Odd. I have no idea why these have disappeared.

Most will cause us a problem if we drop them as they do not have annotations associated. Except for PMID:27392239 > for the others	I have removed the associated empty curation sessions.

My assumptions that these paper s were duplicated that were eventually merged, but I cant think why the PMID would not be tracable if it once existed. This makes no sense.  I also do not know how to find what PMID:27392239  migrated to because I don't know the title. I think we will need to look in an old db for that?

**Comment by kimrutherford** [comment]
>  I also do not know how to find what PMID:27392239 migrated to because I don't know the title. I think we will need to look in an old db for that?

I did that.  Details below.

I checked my email and we discussed this publication at the end of Jan 2021 with the subject line "very close".  It was missing from PubMed back then.

Here are the details.  The paper has two sessions and both have annotations.  This is the newer session with the correct PubMed ID: 

https://pubmed.ncbi.nlm.nih.gov/27560651/
https://curation.pombase.org/pombe/curs/3bd00175a6e61e42/ro
https://www.pombase.org/reference/PMID:27560651

The effect of magnesium on mitotic spindle formation in Schizosaccharomyces pombe.

Uz G, Sarikaya AT

Magnesium (Mg2+), an essential ion for cells and biological systems, is involved in a variety of cellular processes, including the formation and breakdown of microtubules. The results of a previous investigation suggested that as cells grow the intracellular Mg2+ concentration falls, thereby stimulating formation of the mitotic spindle. In the present work, we used a Mg2+-deficient Schizosaccharomyces pombe strain GA2, in which two essential membrane Mg2+ transporter genes (homologs of ALR1 and ALR2 in Saccharomyces cerevisae) were deleted, and its parental strain Sp292, to examine the extent to which low Mg2+ concentrations can affect mitotic spindle formation. The two S. pombe strains were transformed with a plasmid carrying a GFP-α2-tubulin construct to fluorescently label microtubules. Using the free Mg2+-specific fluorescent probe mag-fura-2, we confirmed that intracellular free Mg2+ levels were lower in GA2 than in the parental strain. Defects in interphase microtubule organization, a lower percentage of mitotic spindle formation and a reduced mitotic index were also observed in the GA2 strain. Although there was interphase microtubule polymerization, the lower level of mitotic spindle formation in the Mg2+-deficient strain suggested a greater requirement for Mg2+ in this phenomenon than previously thought.

**Comment by kimrutherford** [comment]
There are some term differences.  Is that OK?  Like

"abnormal microtubule cytoskeleton morphology during mitotic interphase" vs "abnormal cytoplasmic microtubules"

"growth auxotrophic for magnesium" vs  "decreased cellular magnesium level"

**Comment by ValWood** [comment]
I should check it.

**Comment by ValWood** [comment]
You could do this now. Basically it is a paper with 2 PMIDs  (Once of which disappeared, somehow got curated twice) and we need to make sure that the extant  ID has all of the relevant  annotations.

**Comment by ValWood** [comment]
not at all urgent.

**Comment by manulera** [comment]
I had a look and I think the old session (from PMID:27392239) could be safely removed. The annotations are slightly different, but they are correct. My only question:

* [ ] Should leu1-32 ura4-D18 and ade6-M12 (auxotrophies) be removed from background? I guess yes

**Comment by ValWood** [comment]
>  Should leu1-32 ura4-D18 and ade6-M12 (auxotrophies) be removed from background?

The are not required, but if people add them I usually leave them. The main. reason  we don't add them is time constraints. They don't do any harm and although I don't love the inconsistency of randomly having them, or not I think on balance because they are not worg, we can keep.

**Comment by manulera** [comment]
Ok removed the orphaned one
