### ISSUE TITLE
distant orthologs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3248]
SPBC19F8.05 = MS26/PET123 human MRPS26
- [x] change to inferrred
- [x] update taxon dist
- [x] update product
- [x]  add orthologs
- [x] add GO annotation
- [x] check disease association (none)
- [x] inform Nathalie

**Comment by ValWood** [comment]
ppr5 / SPAC1093.01 human PTCD1 (S. cerevisiae currently conflicting)

**Comment by ValWood** [comment]
@kimrutherford  where do we get S. cerevisiea orthologs from currently?

I had added YOR158W to the contigs, and I though I had done it incorrectly but it did work?
https://www.pombase.org/gene/SPBC19F8.05

(For human ortholog, both mechanisms work (contig or ortholog files) , we can add to the contigs or the external files  so maybe either will work for 
fission yeast too (and the pipeline merges the identical duplicates).

**Comment by kimrutherford** [comment]
> @kimrutherford where do we get S. cerevisiea orthologs from currently?

Just from the contig files.

For human it can be contig files or from SVN.

For japonicus they all come from a files in SVN.

**Comment by ValWood** [comment]
Right so iI need to fix this one in the contigs!

**Comment by ValWood** [comment]
I mean SPBC28F2.11
