### ISSUE TITLE
Cannot delete annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3249]

**Comment by kimrutherford** [comment]
> I just tried again it is fine.

It still sounds like a bug I should have a look at.  Which session was it?

**Comment by ValWood** [comment]
It was PMID:15509865

**Comment by kimrutherford** [comment]
> It was PMID:15509865

Thanks.  Unfortunately I couldn't reproduce the problem and I can't see see anything wrong with the session in the database.  I think we'll have to put it down to a temporary network problem.
