### ISSUE TITLE
causally upstream vs. regulation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3250]
@manulera  (for discussion about "regulation" terms in GO and their use)

see https://www.pombase.org/term/GO:0061805

I am not sure that asp1 is  "regulation" in the GO sense- but I am also not sure if it is part_of the process, or upstream, which is why it is currently annotated to this term.
This  will depend on  how the beginnings and ends of the processes are defined, and often this is not articulated in the term def.

All of our BP annotations have the entity-term relation "involved_in" (Although we do not display it). You can see it in the qualifier field here:
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0061805

- When we next chat I can show you when I use "regulation terms" and which I think should eventually be 'causally upstream' instead.  
- However, I have some issues with the "causally upstream" relation because it has a slightly different meaning when it is used in the qualifier field, than when it is used to make connections between activities in GO-cam models.
 - I also need to check that this is correct with GO because there are no clear guidelines on the differences. I suspect people are annotating slightly differently in traditional GO annotation, and Noctua and we need to align.
- In the case where we are trying to make connections between an entity and a downstream process  I wonder if we should not be doing this as gene x is upstream of process y (which seems a bit _ad hoc_ and unsustainable), but we should be capturing more generally when we know that  process x is upstream of process y.

(sorry this ticket is a bit of a stream of consciousness, I will explain some time next week)

- If you do have any suggestions for beginnings and ends of GO processes these are always useful).

**Comment by manulera** [comment]
Ok I will link to it in my curation repo so we talk about it eventually.
