### ISSUE TITLE
tht1 alleles

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3254]
Hello,

So while checking the annotations for the [FYPO:0000512](https://www.pombase.org/term/FYPO:0000512), I had a look at tht1 gene page because it's mentioned in PMID:9442101.

We have the following alleles listed in the page:

* [tht1-1 (W541->stop)](https://www.pombase.org/genotype/tht1-1-W541-%3Estop-nonsense_mutation-expression-not_assayed)
* [tht1-N163D (aa)](https://www.pombase.org/genotype/tht1-N163D-N163D-amino_acid_mutation-expression-not_assayed)
* [tht1-N372D (aa)](https://www.pombase.org/genotype/tht1-N372D-N372D-amino_acid_mutation-expression-not_assayed)
* [tht1-D543* (D543->stop)](https://www.pombase.org/genotype/tht1-D543*-D543-%3Estop-nonsense_mutation-expression-not_assayed)

I think tht1-D543* (D543->stop) is wrongly named, it is not mentioned in the text, and the alleles listed in the paper are the following:

![](http://europepmc.org/articles/PMC2132580/bin/JCB14647.f10.jpg)

tht1-1 has a a premature stop codon in which the protein misses the last 3 aa, that leads to the phenotype of abolished nuclear fusion. They do other mutations in the same region with similar results, so I think they can be omitted since they come to show the same thing (these last 3 aas are important).

If you agree, I will remove the allele tht1-D543* (D543->stop)  and its annotation.

**Comment by ValWood** [comment]
Agreed, I did it.
