### ISSUE TITLE
cut7 in PMID:9490630

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3256]
I added the allele sequences, and the fact that wt cut7 is expressed in the background in certain strains.

The below statement
> and an additional 30.0% of cells were anucleate indicating a strong mitotic defect

is anotated once more to FYPO:0006339. I guess this could be moved once more to "FYPO:0000252" increased spontaneous diploidization. In this case they did not go mechanistically into it, so we cannot annotate to "increased spontaneous diploidization due to abolished sister chromatid separation". If you give me the green light, I change the annotation.

**Comment by ValWood** [comment]
OK!

**Comment by manulera** [comment]
Done
