### ISSUE TITLE
Where is this isoForm ID coming from? wtf4

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3262]
pombemine have 2 isoform ID  represented as 2 genes:

SPCC548.03c.1
and
SPCC548.03c.2

<img width="572" alt="Screenshot 2022-05-23 at 12 05 39" src="https://user-images.githubusercontent.com/7359272/169806040-90ae7f61-883e-4869-9649-ed1a3081f5b5.png">

We can't work out where these are coming from because they are not in the json file?

I wondered if it was something to do with the way UniPRot is representing the isoform annotations, that they somehow come in via  names in UniProt entries? These names are not in the UniProt entries names table.

<img width="655" alt="Screenshot 2022-05-23 at 12 11 49" src="https://user-images.githubusercontent.com/7359272/169807072-d6277c92-654a-4b9a-88b3-ed7ed012e91e.png">

So then, I wondered if they were somehow in the GO GAF because UniProt had exported the UniProt isoforms 
Q9P3V0-1 (antidote)
Q9P3V0-2 (poison)
but I  also don't see these names linked to the PomBase idenfiers in  the gene name column

Weirdly though, UniProt does have isoform specific GO annotation for wtf4,  I can see it here for isofrom1 and isoform2 
but I cannot see *ANY* mention of these isoforms in the GO gaf column 17 (I know that @Antonialock  curated wtf a while back)

<img width="980" alt="Screenshot 2022-05-23 at 12 04 06" src="https://user-images.githubusercontent.com/7359272/169806458-177a0373-80e1-46bc-9a1b-52d4ab9c2bf8.png">

So what  is UniProt doing with them?

**Comment by ValWood** [comment]
Maybe this is a red-herring, I'm not sure that there is any isoform specific annotation from UniPRot (but this is odd based on the above table)
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q9P3V0

These locations are all inferred automatically.
I'm a bit baffled by this. I can figure it out later. 

- [ ] Also   pombe gene product is named for the "antidote", because I think for isoforms we display the longest product name. This doesn't really work.

**Comment by Antonialock** [comment]
this is the curation I made for wtf4 

you can see a general function comment, and then a function comment relating to isoform 1 (antidote) and 2 (poison)

the subcellular localization comment is for each isoform, I guess this is what generates the GO inferences?

I am not sure what the problem is bu happy to fix things if needed.

![image](https://user-images.githubusercontent.com/12727506/169874490-7c8c609c-adf3-46ba-bf86-4f953f0d70e1.png)
