### ISSUE TITLE
Small typo in mini-ontologies/pombe_mini_PR.obo: "PomaBase VW"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3265]
Line 2688:
def: "A septation initiation network scaffold protein cdc11 (Schizosaccharomyces pombe) that lacks phosphorylated residues." [PRO:DAN, PomaBase VW, PMID:12546793, PMID:11676915]

**Comment by ValWood** [comment]
Fixed. This stanza is CP from PRO so @nataled you might want to fix too.

**Comment by nataled** [comment]
I must have caught it at some point myself, as it is not in our base file and never made it to public release. Note that stanzas sent via issue tracker are for information only, and haven't gone through our vetting process that occurs prior to release.

**Comment by ValWood** [comment]
OK thanks, will keep that in mind. We will prrob. change how we do this down the line.
