### ISSUE TITLE
Fix RNA orthologs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3268]
mrp1 RNAse MRP SPNCRNA.82 Is RNase MRP RF00030

We have human ortholog 
RPPH1 (HGNC:19273)	ribonuclease P RNA component H1 but this is RF00009

RMRP  is the  human RF00030 member

SPNCRNA.128	rrk1	RNase P K-RNA is the ribonuclease P RNA component
Is RF00009 = human RPPH1

to do
- [x] SPNCRNA.82 remove RPPH1 add RMRP (disease association is correct for RMRP)
- [x] SPNCRNA.128 add RPPH1 

@sartweedie
@manulera

**Comment by manulera** [comment]
Hey @ValWood how do you annotate this? I can see in artemis that SPNCRNA.128 has an annotation `/controlled_curation="term=orthologous to S. cerevisiae RPR1; date=20070206"` but I don't see one for human. Do we do this in canto?
