### ISSUE TITLE
Only export the GO format extension  relations to the GO file that Intermine uses

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3269]
I suspect that Intermine is not using the GO compliant GO Gaf 
because they include relations in addition to

168 coincident_with
180 existence_overlaps
669 happens_during
1834 has_input
218 occurs_in
702 part_of

like 
has_direct _input (this is no longer a valid relation, it was decided that for MF terms "has_input" should always be direct because it represents substrates.

Also "directly_positily_regulates" and "directly_necatively-regulates" are not valid extension relations. We are using them as a placeholder until
https://github.com/pombase/canto/issues/2482 is done.

So  I think there must be 2 formats of the GO output. That is not immediately obvious to me from here
https://www.pombase.org/downloads/go-annotations.

If there is another version of the file, we need to point InterMIne to the GO-compliant version.
If not I'm a bit stumped because these annotations would not get through the GO gaf checking system.

**Comment by kimrutherford** [comment]
> Which file are INtermIne using do you know? They should use the GO one.

I don't know sorry.

**Comment by ValWood** [comment]
covered by other tickets
https://github.com/pombase/curation/issues/3293
https://github.com/pombase/curation/issues/3292
