### ISSUE TITLE
standardise the way we refer to rpb1 CTD repeat residues

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3272]
<img width="1260" alt="Screenshot 2022-06-08 at 12 36 46" src="https://user-images.githubusercontent.com/7359272/172629731-b46b120a-fbf3-4437-b839-fa23bad3e6bd.png">

Also some of these will collapse together if serine is specified

**Comment by ValWood** [comment]
@manulera  
How should we standardize CTD repeat residues in modification extensions?

CTD-S5  
CTD_S5 (we have some underscores in existing but '-' seems more appropriate, maybe?

**Comment by manulera** [comment]
What were these CTD residues?

**Comment by ValWood** [comment]
The only apply to two  proteins.

rpb1 https://www.pombase.org/gene/SPBC28F2.12
and 
spt5 https://www.pombase.org/gene/SPAC23C4.19

**Comment by ValWood** [comment]
For modifications I have standardized the "CTD ser5" to match the majority CTD_S5  so at least they are all the same If we decide to change it.
