### ISSUE TITLE
dpb3Δ allele for bur6

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3276]
Hi Val.

I've noticed an oddity.

We have a gene named dpb3: https://www.pombase.org/gene/SPCC16C4.22
And dpb3 is a synonym of bur6: https://www.pombase.org/gene/SPAC17G8.03c

We also have dpb3Δ: https://www.pombase.org/genotype/dpb3delta
but on that page is says the gene for dpb3Δ is bur6.

dpb3Δ appears in annotations on both gene pages.

It might have something to do with this session:
 https://curation.pombase.org/pombe/curs/08dc04f357b0310b/ro

It looks to "dpb3+[Knockdown]" is also attached to bur6.

I noticed this while checking the PHAF output implementing: pombase/pombase-chado#983

**Comment by ValWood** [comment]
This paper

PMID:15388803
 originally identified SPAC17G8.03c as dpb3

later it was shown that this was incorrect and that  a new gene [SPCC16C4.22]was dbp3.


"although this is demonstrated to be a DNA polymerase epsilon interactor and named Dpb3, it appears to be the ortholog of S. cerevisiae BUR6 and human DRAP1. The Dpb3 ortholog appears to be the recently identified SPCC16C4.22"

I need to change any residual deletion alleles of dpb3 on  SPAC17G8.03c to deltabur6  


[although this is demonstrated to be a DNA polymerase epsilon interactor and named Dpb3, it appears to be the ortholog of S. cerevisiae BUR6 and human DRAP1. The Dpb3 ortholog appears to be the recently identified SPCC16C4.22](https://www.pombase.org/term/PBO:0034729)

**Comment by ValWood** [comment]
done, I think
