### ISSUE TITLE
abc1delta is sometimes a coq8 allele, sometimes ybt1

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3280]
coq8 / abc1delta:  https://www.pombase.org/genotype/abc1delta
https://curation.pombase.org/pombe/curs/619a912c82d69329/ro/
https://curation.pombase.org/pombe/curs/b00ed4a71aeee523/ro/

ybt1 / abc1delta: https://curation.pombase.org/pombe/curs/b00a5065fbeb471/ro/

**Comment by ValWood** [comment]
check

**Comment by ValWood** [comment]
fixed
