### ISSUE TITLE
Gamma-tubulin complexes in GO

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3284]
To be discussed, following PMID:35622906

**Comment by manulera** [comment]
Following an email discussion on whether mozart mzt1 should be annotated to gamma-tusc GO:0008275.

The definition from GO:
> A complex usually comprising two gamma-tubulin molecules and two conserved non-tubulin proteins. Some gamma-tubulin small complexes are thought to be the repeating unit making up the core of the gamma-tubulin ring complex.

So from its definition the canonical components would be:
    - gtb1
    - gcp2 / alp4
    - gcp3 / alp6

However, since mzt1 binds to the complex, also in vitro, we annotate it there.

* We also have a propagated annotation of alp16 to the complex, but I think this one is not correct. As alp16 is in the gamma-turc complex, of which gamma-tusc is part_of (I requested this relationship in this [GO issue](https://github.com/geneontology/go-ontology/issues/23740)):
  * Annotation is here: https://www.pombase.org/term/GO:0008275

**Comment by ValWood** [comment]
Yes, go ahead!

**Comment by ValWood** [comment]
IIRC the definition of the gamma tubulin complexes pre-dates the discovery of mozart, so the definition could be revised.

**Comment by ValWood** [comment]
we need to report the incorrect mapping of alp16 here:
https://github.com/geneontology/go-annotation/issues

I think part of the problem is that other databases have used gamma tubulin small complex" where they should have used "gamma tubulin complex" (at least the SGD one, I did not see any mention of 'small'. do you agree? )  Although this inference also comes from Pombase alp16 itself and we don't have this annotation (but maybe we did and it was fixed?)

**Comment by ValWood** [comment]
drosphila annotation (Grip91) seems that it should TuRC not TuSC 
see https://github.com/geneontology/go-ontology/issues/23740
@sjm41 @hattrill  do you agree?

**Comment by ValWood** [comment]
Actually this  looks like a propagation error. 
SGD SPC98 and drosophila Grip91 are Alp6 orthologs, not pombe alp16.

There is no identified alp16 in S. cerevisiae (I will check this tomorrow).  The fly Alp16 ortholog is most likely CG18109

**Comment by manulera** [comment]
I have moved our annotations to ring complex

**Comment by manulera** [comment]
Here the S. cerevisiae gamma-tusc:

From PMID:20631709
<img width="365" alt="Screenshot 2022-07-21 at 09 26 34" src="https://user-images.githubusercontent.com/22526102/180167425-77eaba99-6aa0-467f-a76b-0e385f26aa76.png">

**Comment by manulera** [comment]
Annotations to gamma-tusc seem to be correct in SGD.

https://www.yeastgenome.org/go/GO:0008275

Also the inferred ones (computational) are correct.

**Comment by manulera** [comment]
From PMID:34660584

> In Drosophila γ-TuSC is composed of two γ-tubulins and two Grip proteins, Grip84 and Grip91; while γ-TuRC comprises multiple γ-TuSC proteins and three or four additional Grip proteins, Grip75, Grip128, Grip163, and Grip71 ([Gunawardane et al., 2000](https://www.frontiersin.org/articles/10.3389/fcell.2021.727264/full#B12); [Veìrollet et al., 2006](https://www.frontiersin.org/articles/10.3389/fcell.2021.727264/full#B31)).

So I think both SGD and FlyBase have correct annotations. Perhaps the alp6 / alp16 orthology is not correctly mapped from pombe to these organisms?

**Comment by manulera** [comment]
In FlyBase they also have http://flybase.org/reports/FBgn0026432 Dmel\Grip163 which is not mentioned there, but it binds to gamma-tubulin, so it might be like mzt1 that is annotated to the complex just because it goes there?

**Comment by ValWood** [comment]
reported propagation issue
https://github.com/geneontology/go-annotation/issues/4243
