### ISSUE TITLE
Update Identifiers.org registry

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3285]
https://registry.identifiers.org/registry/pombase

The gene URL is incorrect and the main site needs to be HTTPS.

**Comment by ValWood** [comment]
@kim Is this done?

**Comment by kimrutherford** [comment]
I haven't look at this yet.

**Comment by ValWood** [comment]
I tried to  register to do this. The https seems to be fixed but the gene URL is still wrong.

I need to verify my account but despite trying multiple times and checking my spam I ne er get the e-mails.

Could anyone else try? @manulera @kimrutherford  should only take a minute and then can close.

I will also make a list of all of these types of external places where we need to keep records up to date. Where should we keep it?

**Comment by manulera** [comment]
I just created an account and it worked for me, what should I do?

**Comment by kimrutherford** [comment]
Thanks @manulera 

We need to change "http://www.pombase.org/" to "https://www.pombase.org/" and change "http://www.pombase.org/spombe/result/{$id}" to "https://www.pombase.org/gene/{$id}"

(both with "https")

**Comment by manulera** [comment]
I see, but I guess I don't have the permissions to do this.

I have sent a ticket requesting the changes / instructions./

> Hello,
> 
> I am a biocurator in Pombase. We noticed that the Home URL and URL Pattern are not correct in the identifiers.org website:
> 
> https://registry.identifiers.org/registry/pombase
> 
> Home URL
> http://www.pombase.org/
> https://www.pombase.org/
> 
> URL Pattern:
> Now is http://www.pombase.org/spombe/result/{$id}
> should be https://www.pombase.org/gene/{$id}
> 
> This matter has been discussed in the PomBase organisation GitHub, see this issue: https://github.com/pombase/curation/issues/3285
> 
> Could you please change this, or let us know how to change it on our side?
> 
> 
> Kind regards,
> Manu

**Comment by kimrutherford** [comment]
It looks like this is fixed now.  Thanks Manu.

**Comment by manulera** [comment]
Yep! I just forwarded the email
