### ISSUE TITLE
gorule-0000008 "No annotations should be made to uninformative high level terms"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3290]
I don't know if this is an issue but there are some warnings here: http://current.geneontology.org/reports/pombase-report.html#gorule-0000008

Example:

WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms -- PomBase SPAC27F1.02c cdc8 enables GO:0098772 PMID:12796476 IDA F tropomyosin fus4 protein taxon:4896 20200317 PomBase has_input(PomBase:SPAC1F5.04c)

**Comment by ValWood** [comment]
Yes, the GO errors are on my radar. I will give them some attention soon. This one is just a warning, but there's a  ticket on the ontology tracker somewhere for a new MF term....but I'm not sure about the annotation....

**Comment by kimrutherford** [comment]
> Yes, the GO errors are on my radar. I will give them some attention soon.

OK, thanks.

By the way, I've just fixed `supporting_files/legacy_go_annotations_from_contigs.txt` to get rid of these warnings from the GO report:

    WARNING - Invalid identifier: GORULE:0000027: assigned_by is not present in groups reference (PomBas) -- PomBase SPAC26F1.03 pda1 involved_in GO:0009060 GO_REF:0000111 IC GO:0005967 P pyruvate dehydrogenase e1 component alpha subunit Pda1 protein taxon:4896 20220629 PomBas
    WARNING - Invalid identifier: GORULE:0000027: assigned_by is not present in groups reference (PomBas) -- PomBase SPAC644.11c pkp1 involved_in GO:0009060 GO_REF:0000111 IC GO:0005967 P mitochondrial pyruvate dehydrogenase (lipoamide) kinase Pkp1 protein taxon:4896 20220629 PomBas
    WARNING - Invalid identifier: GORULE:0000027: assigned_by is not present in groups reference (PomBas) -- PomBase SPBC30D10.13c pdb1 involved_in GO:0009060 GO_REF:0000111 IC GO:0005967 P pyruvate dehydrogenase e1 component beta subunit Pdb1 agg1 protein taxon:4896 20220629 PomBas
    WARNING - Invalid identifier: GORULE:0000027: assigned_by is not present in groups reference (PomBas) -- PomBase SPCC1259.09c pdx1 involved_in GO:0009060 GO_REF:0000111 IC GO:0005967 P pyruvate dehydrogenase protein x component, Pdx1 protein taxon:4896 20220629 PomBas
    WARNING - Invalid identifier: GORULE:0000027: assigned_by is not present in groups reference (PomBas) -- PomBase SPCC794.07 lat1 involved_in GO:0009060 GO_REF:0000111 IC GO:0005967 P dihydrolipoamide S-acetyltransferase E2, Lat1 protein taxon:4896 20220629 PomBas

**Comment by ValWood** [comment]
oops!

**Comment by ValWood** [comment]
Closing because it is covered by the GO logs and I'm  waiting for terms
