### ISSUE TITLE
add external links to micropublication

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3291]
Rob Andrews  would like to use this  paper in some of his FAIR data training, showing micropublications as a way of making data FAIR, We chose this one because it has associated datasets (sequence and variation). 

https://www.pombase.org/reference/PMID:34017941
https://www.micropublication.org/journals/biology/micropub-biology-000390

So we only need to associate the dataset URLs with the publication.
https://data.caltech.edu/records/1964
https://data.caltech.edu/records/1965

@bahler  I see a link to the genotype metadata, and a link to the variant calls. Is there no associated raw sequence data (i.e ENA)?

**Comment by ValWood** [comment]
thanks!

**Comment by ValWood** [comment]
@kimrutherford  can you remind me how to do this?

**Comment by kimrutherford** [comment]
Hi Val.

You'll need to add a new entry to the `reference_page_extra_links` setting in the main website config file: https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json
