### ISSUE TITLE
check these relations

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3292]
~1 | activated_by                  | molecular_function~ changed to "during response to
   ~1 | regulates_activity_of         | biological_process~ removed
   43 | occurs_at                     | biological_process
     5 | occurs_in                     | biological_process OK (cell type)
 17 | not_exists_during             | cellular_component
    39 | part_of                       | cellular_component

**Comment by ValWood** [comment]
@kimrutherford 
43 | occurs_at | biological_process
can you provide this list?

**Comment by kimrutherford** [comment]
> can you provide this list?

Try this:
```
curl https://curation.pombase.org/dumps/latest_build/misc/pombase_style_gaf.tsv | grep occurs_at | grep -P '\tP\t'
```

**Comment by ValWood** [comment]
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by ValWood** [comment]
I remember now how we use the. 

we still use occurs_at for heterochromatin features (rather than the official occurs_in) and we convert them   t occurs_in for submission

**Comment by ValWood** [comment]
It's OK we display as except_during.
I am going to review and most likely remove these.
PMID:12631727
PMID:12972571
PMID:16899242
PMID:24006488
PMID:2569363
PMID:9852154

**Comment by kimrutherford** [comment]
> curl failed to verify the legitimacy of the server

That's bad!  Could you run the same command with but add the "-v" flag to curl?:

```
curl -v https://curation.pombase.org/dumps/latest_build/misc/pombase_style_gaf.tsv | grep occurs_at | grep -P '\tP\t'
```

Thanks.  I'd like to get to the bottom of that.

**Comment by ValWood** [comment]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 131.111.36.16...
* TCP_NODELAY set
* Connected to curation.pombase.org (131.111.36.16) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/local/share/curl/curl-ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [108 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4030 bytes data]
* TLSv1.2 (OUT), TLS alert, certificate expired (557):
} [2 bytes data]
* SSL certificate problem: certificate has expired
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by kimrutherford** [comment]
Thanks for that.  I was able to Google for the error and confirm it's a problem with `curl` on Macs rather than with the Canto server.
