### ISSUE TITLE
amino acid deletion described as substitutions

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3296]
fix

sap1 | SPCC1672.02c | sap1delta1-21,144-254 | 1-21,144-254
sap1 | SPCC1672.02c | sap1delta1-21,151-254 | 1-21,151-254
sap1 | SPCC1672.02c | sap1delta137-254 | 137-254
sap1 | SPCC1672.02c | sap1delta144-254 | 144-254
sap1 | SPCC1672.02c | sap1delta151-254 | 151-254
sap1 | SPCC1672.02c | sap1delta158-254 | 158-254
sap1 | SPCC1672.02c | sap1delta204-254 | 204-254
sap1 | SPCC1672.02c | sap1delta241-254 | 241-254
gms1 | SPCC1795.03 | gms1delta73 | 280-353

ctp1	SPCC338.08	ctp1-1-150	151-294
ctp1	SPCC338.08	ctp1-1-60	61-294
ctp1	SPCC338.08	ctp1-151-294	1-150
ctp1	SPCC338.08	ctp1-delta100-120	100-120
ctp1	SPCC338.08	ctp1-delta60+120	60-120
ctp1	SPCC338.08	ctp1-delta60-100	60-100
ctp1	SPCC338.08	ctp1-delta60-80	60-80
ctp1	SPCC338.08	ctp1-delta80+120	80-120
taf5 | SPCC5E4.03c | taf5delta3-37 | 3-37
pcn1 | SPBC16D10.09 | pcn1-38
uaf2 | SPAP8A3.06 | uaf2delta53-113 | 53-113

rad9 | SPAC664.07c | rad9delta411-426 | 411-426

(request a report of malformed alleles of this type)

**Comment by manulera** [comment]
These are now automatically fixed
