### ISSUE TITLE
fix hyphens in amino acid mutation descriptions etc

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3297]
taf12 | SPAC15A10.02 | taf12-5A | S217A-T218A-S220A-T221A-T283A
-- | -- | -- | --
taf12 | SPAC15A10.02 | taf12-5DE | S217D-T218E-S220D-T221E-T283E
rad4 | SPAC23C4.18c | rad4-C13Y-E368K | C13Y-E368K
rad4 | SPAC23C4.18c | rad4-C13Y-K56R | C13Y-K56R
rad4 | SPAC23C4.18c | rad4-F305S-E368K | F305S-E368K
rad4 | SPAC23C4.18c | rad4-K56R-E368K | K56R-E368K
spt5 | SPAC23C4.19 | spt5-(T1E)7 | CTR-T1E

**Comment by ValWood** [comment]
remove nmt1 from description field
res1 | SPBC725.16 | res1-S130A OE | nmt1-S130A

**Comment by ValWood** [comment]
xlf1 | SPCC24B10.14c | nmt1-xlf1.AA | T180A,S192 nmt high-level overexpression
-- | -- | -- | --
xlf1 | SPCC24B10.14c | nmt41-xlf1.AA | T180,S192A nmt41 medium-level overexpression

[xlf1](http://pombemine.rahtiapp.fi/pombemine/report/Gene/1141217)	[SPCC24B10.14c](http://pombemine.rahtiapp.fi/pombemine/report/Gene/1141217)	[nmt1-xlf1.AA](http://pombemine.rahtiapp.fi/pombemine/report/Allele/17102890)	[T180A,S192 nmt high-level overexpression](http://pombemine.rahtiapp.fi/pombemine/report/Allele/17102890)
[xlf1](http://pombemine.rahtiapp.fi/pombemine/report/Gene/1141217)	[SPCC24B10.14c](http://pombemine.rahtiapp.fi/pombemine/report/Gene/1141217)	[nmt41-xlf1.AA](http://pombemine.rahtiapp.fi/pombemine/report/Allele/17102880)	[T180,S192A nmt41 medium-level overexpression](http://pombemine.rahtiapp.fi/pombemine/report/Allele/17102880)

**Comment by ValWood** [comment]
not "unknown"
 ksg1	SPCC576.15c	ksg1-208	unknown	G159E

**Comment by ValWood** [comment]
pof8 | SPAC17G6.17 | pof8delta2-10 | amino_acid_insertion_and_deletion | 2-10 | Wild type product level

**Comment by ValWood** [comment]
cdc6 | SPBC336.04 | cdc6-C1043A | amino_acid_insertion_and_mutation | C1043A | Wild type product level
cdc6 | SPBC336.04 | cdc6-C1053A | amino_acid_insertion_and_mutation | C1053A | Wild type product level
cdc6 | SPBC336.04 | cdc6-C1058A | amino_acid_insertion_and_mutation | C1058A | Wild type product level
cdc6 | SPBC336.04 | cdc6-C1058S | amino_acid_insertion_and_mutation | C1058S

**Comment by ValWood** [comment]
pmt3 | SPBC365.06 | pmt3-His6SUMO-L109K | amino_acid_insertion | L109K
mcs4 | SPBC887.10 | mcs4-D512N | amino_acid_insertion | D512N
cdc31 | SPCC1682.04 | cdc31-1 | amino_acid_insertion | A62T | Not assayed
cdc31 | SPCC1682.04 | cdc31-5 | amino_acid_insertion | P108S




ams2 | SPCC290.04 | ams2-C1 | amino_acid_deletion_and_mutation | 1-143



myo2 | SPCC645.05c | myo2-LT | amino_acid_insertion | + myp2-aa1622-2104 | Wild type product level
myo2 | SPCC645.05c | myo2-ST | amino_acid_insertion | +myp2-aa1923-2104
pil1 | SPCC736.15 | pil1N | amino_acid_deletion_and_mutation | pil1(1-266)
alp14 | SPCC895.07 | alp14-26 | amino_acid_insertion_and_mutation | C450R

**Comment by ValWood** [comment]
I guess these will also be fixed by the script?

**Comment by manulera** [comment]
I will close when alleles go into canto
