### ISSUE TITLE
nonsense mutations are described in 3 ways

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3298]
1 Some as truncations form where the stop is inserted.
2 Some as AA mutations  AA->stop
3. Some as  "nonsense mutations" (we probably don't need a special 'type' for these, especially as it gets confusing what to use for nonsense +  some other mutation

**Comment by manulera** [comment]
We should describe it with a star `*` to be consistent with the aminoacid code in FASTA files, at least that's what I did in the standardising pipeline.
