### ISSUE TITLE
PMID:15857958 - GO term annotation

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3305]
Hi @ValWood 

A question about GO annotation.

From the abstract:

> Pdk1p localizes to the spindle pole body and the actomyosin ring in early mitotic cells. Cells deleted for pdk1 display multiple defects in mitosis and cytokinesis, all of which are exacerbated when the function of fission yeast polo kinase, Plo1p, is partially compromised. We conclude that Pdk1p functions in concert with Plo1p to regulate multiple processes such as the establishment of a bipolar mitotic spindle, transition to anaphase, placement of the actomyosin ring and proper execution of cytokinesis. We also present evidence that the effects of Pdk1p on cytokinesis are likely mediated via the fission yeast anillin-related protein, Mid1p, and the septation initiation network. 

Essentially they show that deletion of this kinase leads to problems in kinetochore attachment and cytokinesis, which may lead to multi-nucleated cells. In addition, this kinase physically localises to the sites where the process is happening (spb and spindle).
I wonder whether it should be annotated to kinetochore attachment and ring assembly, or it is considered to be "upstream", and should be annotated differently.

**Comment by ValWood** [comment]
Good question. In this case I would make a regulation annotation. I make a regulation annotation if it is a signalling pathway (real regulation, not just 'affecting')

Plo1 , the redundant kinase is already annotated to analogous terms

GO:0140429 | positive regulation of mitotic sister chromatid biorientation
(which is a descendent of attachment)

and
positive regulation of mitotic division septum assembly

which is a child of cytokinesis.

NOTE It is possible in GO we have gone a bit too granular with some of the regulation term (and we do not need terms for regulation of all of the subparts, like '...biorientation...', possibly just 'regulation of attachment' would be sufficient here (I'm not even sure that biorientation and '...attachment of mitotic spindle...'are separable processes?) but if terms are made less specific later, the annotations will still be correct - it is difficult to know right now which regulatory events are the different signalling pathways until these pathways are more fully fleshed out, and the way we curate regulation in GO has been changing and is also still not fully fleshed out. I think we are fairly internally consistent though, which will help once we have better rules.

Does that make sense?

**Comment by manulera** [comment]
Sounds good, I will annotate to regulation of attachment and septum assembly.
