### ISSUE TITLE
Frameshift alleles, how to standardize?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3311]
Frameshifts can probably be described as amino acid  "partial deletion" and amino acid change?
So should we do this (it is how I have curated them, where possible)

<img width="1257" alt="_____________annotating  fameshifts" src="https://user-images.githubusercontent.com/7359272/182593511-3398ab42-cf57-4186-bcdd-8ad7e3a60719.png">

and in this case the verbose frameshift information could  be retained in a comment.

Questions:
Would this be a bit much if there are a lot of amino acids inserted from the alternative reading frame ? (but it does make it obvious to the reader what they are looking at, these additional amino acids could contain degrons or localization signals!)

If we decide yes, there are a bunch to fix, but  these are a dying breed of mutant type so I doubt we will have many more.

lem2-1,SPAC18G6.10:allele-17,frameshift,truncating@561,{83bb6f203d9fe65a}
caf4-Y34frameshift*3,SPAC664.15:allele-5,Y34frameshift*3,{e8e4518f9c7db116}
ctp1-5,SPCC338.08:allele-47,frameshift at W288 truncating at position 292,{f137dd00ee869867}
dnm1-L52frameshift*96,SPBC12C2.08:allele-9,L52frameshift*96,{e8e4518f9c7db116}
cgs2-2,SPCC285.09c:allele-3,frameshifted allele,{219e86a87274fe5f,0d638c12aef4db07}
dnm1-L164frameshift*96,SPBC12C2.08:allele-8,L164frameshift*96,{e8e4518f9c7db116}
cmp7-7,SPBC1604.18c:allele-2,frameshift@285,truncated@287,{83bb6f203d9fe65a}
caf4-V603frameshift*9,SPAC664.15:allele-8,V603frameshift*9,{e8e4518f9c7db116}
caf4-N146frameshift*5,SPAC664.15:allele-4,N146frameshift*5,{e8e4518f9c7db116}
git1-1,SPBC21C3.20c:allele-2,frameshift F995,{39e9205957ce5637,219e86a87274fe5f,30f38f2aa9fa78d1,45ffde2cb6f9e878,beb013202ef91cd2}
fis1-N119frameshift*48,SPBC11G11.01:allele-3,N119frameshift*48,{e8e4518f9c7db116}

**Comment by ValWood** [comment]
I think  these might be  frameshifts too:

cdc48-353sup-18,SPAC1565.08:allele-10,G338D,Q781-stop,{16d769aa2fc305a4}
cdc24-G1,SPAC8F11.07c:allele-3,abolished splicing intron 5 + premature stop codon,{c9a5bcda9f0382fa,a64fc9a5b004423d}
cdc1-E2,SPAC27E2.05:allele-16,Q27->GVPK-stop,{82c72ac61a6cf9b2,82c72ac61a6cf9b2}
sep9-307,SPBC14C8.17c:allele-2,nt_1067delta,aa353->stop,{e0d72f6e0665c15c,a02efb01ac764f2e}

**Comment by ValWood** [comment]
You might have a different plan for these?

**Comment by manulera** [comment]
Hi @ValWood, I think frameshifts should be described at the nucleotide level when possible.
