### ISSUE TITLE
UTR  and intron mutations described as "other"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3313]
It should be possibe to convert these to nucleotide mutations

prp16-DAmP,SPBC1711.17:allele-4,disrupted 3' UTR,{ba57135bde9e7e32}
pyp2-no UTRs,SPAC19D5.01:allele-5,deleted 5' and 3' UTRs,{223cbaaac1c064d0}
cdc25-d1,SPAC24H6.05:allele-7,5'UTRdel,{7cc0d044cd0fd080,5b029ec9b56c8283,473f08550050fe95}
usp107-DAmP,SPBC839.10:allele-2,disrupted 3' UTR,{ba57135bde9e7e32}
Pcig2-lacZ,SPAPB2B4.03:allele-12,cig2 2kb 5'UTR-LacZ fusion,{4fc60b01472378b1}
prp43-DAmP,SPBC16H5.10c:allele-2,disrupted 3' UTR,{ba57135bde9e7e32}
uap2-DAmP,SPBC1289.02c:allele-2,disrupted 3' UTR,{ba57135bde9e7e32}
cwf15-DAmP,SPBC337.06c:allele-2,disrupted 3' UTR,{ba57135bde9e7e32}
dim1-DAmP,SPCC16A11.05c:allele-2,disrupted 3' UTR,{ba57135bde9e7e32}
rum1d3'1,SPBC32F12.09:allele-6,lacks AU rich elements in 3' UTR,{c22fae2b021bf85d}
prp22-DAmP,SPAC10F6.02c:allele-3,disrupted 3' UTR,{ba57135bde9e7e32}
ste11-D5'-UTR,SPBC32C12.02:allele-12,2137 OF 2181 5' UTR deleted,{33497d588756c658}
cul4-1,SPAC3A11.08:allele-3,marker gene insertion at 3'-UTR,{a09af17a2956146d}

fus1-TR2 deleted,SPAC20G4.02c:allele-27,TR2 promoter box at -238 deleted,{ef2da839886aa260}

**Comment by ValWood** [comment]
SPCC1442.04c-int2delta,SPCC1442.04c:allele-2,intron 2 deletion,{1f991e4ad5694cb6}
spo14-B221,SPBC3H7.01:allele-3,5th intron branch point CTAAT->CTAAA,{6aac558546fde9fb,bcc4dde202655d0c,bcc4dde202655d0c,33226bef0daaac44,b39e24367b203705}

**Comment by ValWood** [comment]
vam6-532,SPAC23H4.14:allele-2,splice site mutant,{8c6ccb0ae9834279}
sng1-,SPAC18B11.07c:allele-9,splice site mutant,{1c94c9b00e24bffa}

**Comment by ValWood** [comment]
The majority of splicing factors in fission yeast are essential and are perturbed in the EMAP screen as “decreased abundance by mRNA perturbation” (DAmP) alleles, where an antibiotic resistance cassette has been inserted into the gene between the stop codon and the 3′ untranslated region (UTR) to reduce the gene's expression ([Schuldiner et al. 2005](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5411709/#NISSENGAD295287C41)).

So the majority of these should be straightforward, since we know the precise insertion point of the DAmP

**Comment by manulera** [comment]
This is how the description of Damp alleles is written with new syntax:

CDS.prp16:natMX6:3UTR.prp16

As for the others, they can be described at the nucleotide level (with negative or positive coordinates, accordingly). I will close, since I will go through these in the final sweep.
