### ISSUE TITLE
TEV constructs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3314]
Should these be described as truncations? (they can still have TEV in the name to distinguish them)

- [x] rec8(TEV),SPBC29A10.14:allele-10,rec8-TEV(cleavable),{db9b5a7b5f36c25c}
(need to edit if we decide to omit gene name from description)

- [ ] cdc23-S424::Tcs,SPBC1347.10:allele-12,TEV cleavage site introduced after Ser424; TEV protease removes C-terminal 170 amino acids,{4488533ca5f8fdc3}
Question below

cnp3C-TEV,SPBC1861.01c:allele-26,protease inactivated,{7d2c05ef7277f909,2a8be2bb0239204b}
cnd2-TEV,SPCC306.03c:allele-8,protease inactivated,{7d2c05ef7277f909}
hsp-tev-2,SPAC926.04c:allele-4,TEV cleavable 2,{a82c265e16b26ca6}
alp14-KTdelta,SPCC895.07:allele-8,TEVcleavable,{6c1cc5fd9503d415}
pol3-T2,SPBC336.04:allele-19,TEV cleavage site S979,{44ae5ece389a1b0a}
pab1-1,SPAC227.07c:allele-3,nucleotides 673-684 duplicated; inserts amino acids TEVI after I228,{d9011560b1887e36}

These 2 are the same construct:
plo1-TEVAA341,SPAC23C11.16:allele-53,tev-site@AA341,{2a8be2bb0239204b}
plo1-TEV(tev-site@AA341),SPAC23C11.16:allele-48,protease cleavable,{e13e49a2df6b7722,e13e49a2df6b7722}

**Comment by ValWood** [comment]
description gene-AA341::TEV

allele  comment "TEV cleavable"

protein truncated by TEV protease

**Comment by ValWood** [comment]
@manulera 
I standardized cdc23-S424
description :
TEV cleavage site introduced after Ser424; TEV protease removes C-terminal 170 amino acids,
 to
(AA424::TEV)
I did not include the gene in the description, because we don't do this for description of most alleles.

Q should we always include the gene in alleles of type 'other' ? or only when they are fusions to other genes to denote the order?

there is another TEV allele in the same session (cdc23-tstd)   which includes  
i) a ts allele (aa change)  ii) a TEV site and  iii) a degron.

currently
[cdc23-tstd (N-terminus of Cdc23 with temperature-sensitive cdc23-IE2 mutation  (C239Y) fused to DHFR degron)]

 It now looks like this
fusion;C239Y,AA424::TEV,degron

(acquiring fusion; from the  syntax  for degron suggested here:
https://github.com/pombase/curation/issues/3319

Q does it seem odd to include fusion; for degron, but not for TEV sites?  (would it be more consistent to also call TEV sites 'fusions'?)

Q Same question, do we need to explicitly include the gene name in the allele name ? (currently we included it in the description here https://github.com/pombase/curation/issues/3319 ) 

Let me know what you think.

**Comment by ValWood** [comment]
@manulera  I guess this can close since  we made a decision how to describe these and will be implemented by the pipeline?

**Comment by manulera** [comment]
Hi @ValWood. So these will not be fixed by the pipeline, as it only works on allele descriptions of variants, but I am fixing them as part of the fusion_or_chimera bunch. For example, a recent one: `cdc23(1-424)-(ENLYFQGAS)-cdc23(425-593)`. `ENLYFQGAS` is the cleavage sequence for the TEV protease.
