### ISSUE TITLE
annotation check, reduced chromatin silencing

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#332]
These genes are annotated to 'abnormal chromatin silencing at...)
I suspect should all be 'reduced'

SPBC25H2.13c	cdc20	DNA polymerase epsilon catalytic subunit Pol2	protein_coding	II	1	3253690	3260706
SPAC12G12.13c	cid14	poly(A) polymerase Cid14	protein_coding	I	1	321764	324129
SPBC428.08c	clr4	histone H3 lysine methyltransferase Clr4	protein_coding	II	-1	458487	453996
SPCC188.13c	dcr1	dicer	protein_coding	III	-1	1510574	1504949
SPCC830.03	grc3	polynucleotide kinase Grc3 (predicted)	protein_coding	III	1	2183590	2187389
SPBC19G7.16	iws1	transcription elongation factor complex subunit Iws1 (predicted)	protein_coding	II	1	2380487	2382242
SPAC23G3.01	rpb2	RNA polymerase II complex subunit Rpb2	protein_coding	I	1	850591	854385
SPBC577.15c	sim3	NASP family CENP-A chaperone	protein_coding	II	-1	782579	780599
SPAC1F7.01c	spt6	nucleosome remodeling protein Spt6	protein_coding	I	-1	4216888	4212476

Original comment by: ValWood

**Comment by Antonialock** [comment]
all done and some additional tidying of old sessions also done!
