### ISSUE TITLE
alleles of type other (overview)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3320]
started with around 760, now down to 536.

Of these: removing (all covered in tickets)
cat alleles_of_type_other_3.txt |grep -v frameshift | grep -v stop | grep -v chimera | grep -v fusion | grep -v fused | grep -v targeted| grep -v tethered | grep -v ectopic | grep -v NLS | grep -v GBP | grep -v CTD | grep -v constitutive |grep -v TEV | grep -v UTR  | grep -v GFP |grep -v RNA | grep -v fus1-TR2 | grep -v "promoter swap" |grep -v promoter-swap | grep -v promoter | grep -v nmt | grep -v pREP | grep -v excluded |grep -v TetR |grep -v exogenous | grep -v myc |grep -v YFP | grep -v degron | grep -v intron | grep -v splice | wc

120 remain
of these the following are in progress, should be classified as existing allele types  (being investigated waiting for author response )
grep -v sla1 | grep -v  swr1 | grep -v msp1 |   grep -v clp1 | grep -v mcp5 | grep -v cut14 | grep -v gaf1 | grep -v nsk1 | grep -v sid2-as4 | grep -v cdc42 | grep -v 345d6b0c8bf7e493 | grep -v msc1 | grep -v  mde4 |  grep -v cdc12 | grep -v chk1 | grep -v myo1 | grep -v mug28 | grep -v fin | grep -v rad21 | grep -v rad26 |grep -v rad3 | grep -v set1 | grep -v dis2 | grep -v a73237e21c888959 | grep -v e976a54955ad43a4 | grep -v bzz1 | grep -v mrc1 | grep -v spo5 | grep -v cdr2-D1 | grep -v mek1-FHAD | grep -v rho1 |grep -v mae2 |grep -v nup189 |grep -v nup98 | grep -v "P-factor" |grep -v zas1 | grep -v cdc2: | grep -v  bgs1 | grep -v cdc4 |grep -v gsa1 | grep -v cdc20 |grep -v wis1

These 17 remain

mid1-NES-delta1-150,SPCC4B3.15:allele-15,NES-delta1-150,{38a5be55b66fa29b}
GST Spg1-GTP,SPAC1565.06c:allele-22,tagged Spg1-GTP bound form,{709eb266115f50d4}
orp2-3HA,SPBC685.09:allele-5,orc2+ with 3 x HA epitope at C terminus,{30da765280e4ffe0}
sum1-ts,SPAC4D7.05:allele-3,sum1+ with N-terminal 3xHA tagged,{207d1283e42dcc66}
exg1-WT-inverted,SPBC1105.05:allele-3,Inverted orientation,{d21245ab5467d47b}
mcm3-HA,SPCC1682.02c:allele-3,mcm3+ with 3 x HA epitope,{062614007433f668}
cnp1-FH,SPBC1105.17:allele-22,cnp1+-C:3xFLAG:6His,{cfa0410c2c949ac3}
dfp1-motif-M+spacer,SPCC550.13:allele-27,aa1-222,336-545 deleted; spacer inserted between 222-,{7f0cc1dde6a7ce20}
fkh2-3HA,SPBC16G5.15c:allele-4,HA tagged fkh2,{386eb2f16aa6dee7}
pac1-AA,SPBC119.11c:allele-2,Anchor-away,{f5403fffd3ecaf81}
cdc13-RLuc,SPBC582.03:allele-9,hypomorph,{ab08277b7b3bc9c4}

Test If I can do these as WT with different names:
cdm1+(3 copies),SPBC12D12.02c:allele-3,wild type,{b5089e77a1ba9a37}
cdc6+(1 copy),SPBC336.04:allele-11,wild type,{b5089e77a1ba9a37}
cdc27+(3 copies),SPBC1734.02c:allele-35,wild type,{b5089e77a1ba9a37}
cdc27+(1 copy),SPBC1734.02c:allele-34,wild type,{b5089e77a1ba9a37}
cdc6+(3 copies),SPBC336.04:allele-12,wild type,{b5089e77a1ba9a37}
cdm1+(1 copy),SPBC12D12.02c:allele-2,wild type,{b5089e77a1ba9a37}

**Comment by ValWood** [comment]
Down to 433,  will leave until chimeras etc are removed and see if any remaining can be fixed.

**Comment by manulera** [comment]
We are down to 63 right now. Will do a final sweep after publication is submitted. Closing then.
