### ISSUE TITLE
other 'tagged' constructs (GFP, Myc/myc/YFP)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3322]
- GFP 29 only curated if the tag gives a detrimental phenotype
- Myc/myc 5? only curated if the tag gives a detrimental phenotype
- YFP 2 only curated if the tag gives a detrimental phenotype (check)

Should we only allow the tag to be in the name if there are mutants, but the tag is know to affect the phenotype?

**Comment by ValWood** [comment]
standardize descriptions

GFP-N-Pxl1-Ppb1,SPBC4F6.12:allele-19,chimera GFP-Pxl1-1-257 fused to Ppb1,{296b721850a6d19b}
nup189n-GFP,SPAC1486.05:allele-6,GFP fusion gene,{6ad90d4a01aee5f2}
cdc42-GFP-N,SPAC110.03:allele-12,GFP fused to N-terminus,{8c5b305baa755d41}
tea2-N(1-557)-GFP-myo52-C,SPBC1604.20c:allele-10,tea2-N(1-557)-GFP-myo52-C(926-1516) (chimera),{098d04fd85e6672d}
mis6-GFP,SPAC1687.20c:allele-3,GFP-C,{216f4dec12ef6153}
arc5-GFP,SPAC17G8.04c:allele-2,C-terminal GFP fusion,{6eeb7666f8d6b4bf}
pgk1DTATA-loz1-GFP,SPAC25B8.19c:allele-3,a Loz1-GFP fusion protein that is expressed from a derivative of the pgk1 promoter containing a deletion in the TATA box.,{e3188b7c6757274d}
cnp1-GFP,SPBC1105.17:allele-9,GFP-C,{216f4dec12ef6153}
rps2302-GFP,SPBP4H10.13:allele-11,GFP fusion,{54b4f3fa56c4718d}
nuf2-GFP,SPAC27F1.04c:allele-6,nuf2 tagged with GFP,{fe7a0f32d4e76d5d}
Pom1-Cdr2C-GFP,SPAC2F7.03c:allele-5,fusion,ectopically localized,{a475a61f06526c04}
mal3-GFP,SPAC18G6.15:allele-24,C-terminal tag GFP,{3248946eca150af0}
dad1-GFP,SPAC16A10.05c:allele-2,GFP-C,{216f4dec12ef6153}
cnp1(GFP-N),SPBC1105.17:allele-20,GFP-N,{440ff0786082ec49}
iec5-GFP,SPAPB1E7.14:allele-3,iec5-GFP fusion,{5bba706f5b371433}
tpz1-GFP,SPAC6F6.16c:allele-47,tpz1+ fused to GFP,{708b18da700d87e9}
stt4(N-GFP),SPBC577.06c:allele-3,N-terminal tag,{f4da3c52016e8dca}
rng10-GBP,SPAC688.07c:allele-10,GFP binding tag,{95c831769f7efdd6}
pkl1-3xGFP,SPAC3A11.14c:allele-7,C-ter tag 3xGFP,{5885cef5c51f3f2d}
spg1-GFP,SPAC1565.06c:allele-20,spg1-GFP fusion,{f4425b94136060a0}
nup184-GFP,SPAP27G11.10c:allele-3,GFP fusion gene,{6ad90d4a01aee5f2}
cdc15-gc1,SPAC20G8.05c:allele-18,Hypomorphic allele cdc15-GFP,{80b382d361649949}
cdc15-GFP,SPAC20G8.05c:allele-42,Hypomorphic Cdc15,{6788fbad2542709a}
mis12-GFP,SPBC409.04c:allele-3,GFP-C,{216f4dec12ef6153}
git7-GFP,SPBC36.12c:allele-4,git7-GFP,{a09d826a70b1a2d4}
dis2NGBP,SPBC776.02c:allele-15,cut12NGBP binds to GFP,{acd1a2d2ddcf29cc}
GFP-pps1,SPCC1442.12:allele-4,N-terminal GFP fusion,{61b0bcb9898f64f7}
ndc80-GFP,SPBC11C11.03:allele-4,GFP-C,{216f4dec12ef6153,fe7a0f32d4e76d5d}
tea2-N(1-557)-GFP-myo52C(926-1516),SPBC1604.20c:allele-9,tea2-N(1-557)-GFP-myo52C(926-1516)(chimera),{098d04fd85e6672d}
GFP-rae1,SPBC16A3.05c:allele-4,GFP fusion gene,{6ad90d4a01aee5f2}
arp2-GFP,SPAC11H11.06:allele-3,C-terminal GFP fusion,{6eeb7666f8d6b4bf}
41X-GFP-etd1,SPAC1006.08:allele-4,Overexpression of GFP-etd1,{6788fbad2542709a}
mEGFP-cdr1(delta460-482),SPAC644.06c:allele-6,mEGFP=cdr2 binding peptide,{020b7fc6a3fa0724}
nup45-GFP,SPAC22G7.09c:allele-4,GFP-fusion,{6ad90d4a01aee5f2}
rap1-GFP,SPBC1778.02:allele-59,rap1+ fused to GFP,{708b18da700d87e9}
GFP-act1,SPBC32H8.12c:allele-4,N-terminal GFP fusion,{6eeb7666f8d6b4bf}
cdc25-GFP-NLS,SPAC24H6.05:allele-3,cdc25 fused with GFP and NLS (nuclear localization signal),{915dd27f11d0b65d,8fe26054c4dd9003}
cut7-GFP,SPAC25G10.07c:allele-27,C-ter tag GFP,{5885cef5c51f3f2d}
Rrp6-GFP-Mmi1-chimera,SPAC1F3.01:allele-5,fusion Rrp6-GFP-Mmi1,{57d00be9a0ffdd97}
zip1-GFP,SPAC25G10.03:allele-3,GFP fusion,{1534156512e84afb}
GFP-wsp1,SPAC4F10.15c:allele-2,N-terminal GFP fusion,{6eeb7666f8d6b4bf}
pps1-GFP,SPCC1442.12:allele-3,C-terminal GFP fusion,{61b0bcb9898f64f7}
cnp3-GFP,SPBC1861.01c:allele-3,GFP-C,{216f4dec12ef6153}
rap1deltaPID-GFP,SPBC1778.02:allele-60,rap1deltaPID fused to GFP,{708b18da700d87e9}
rad21-GFP,SPCC338.17c:allele-11,GFP-C,{216f4dec12ef6153}
arp3-GFP,SPAC630.03:allele-2,C-terminal GFP fusion,{6eeb7666f8d6b4bf}
iec1-GBP,SPAC144.02:allele-2,iec1-GFP binding protein fusion,{5bba706f5b371433}
tor1-N-termGFP,SPBC30D10.10c:allele-11,N-term GFP tagged,{703aa934daf915d2}
ral3-cor-C-GFP fusion,SPAC22H10.07:allele-4,ral3-cor-C-GFP fusion,{88d2e1acdc9993bc}
rad11-GFP,SPBC660.13c:allele-9,GFP fusion,{4dfa9e1e417a7efe}
spc7-GFP,SPCC1020.02:allele-13,GFP-C,{216f4dec12ef6153}
dma1-GFP,SPAC17G8.10c:allele-18,GBP-binding,{f30149c5fcc7f553}
bot1-GFP,SPBC14C8.16c:allele-3,GFP tagged bot1,{6eb1454735373927}
EGFP-pcn1,SPBC16D10.09:allele-44,Pcn1 fused to GFP,{99beef0215ee9477}

Any useful info about the allele that isn't part of the description, or phenotype can go in

~ pombe-embl/supporting_files/allele_comments.txt
(we don't display these yet)

**Comment by manulera** [comment]
These I fixed most manually, if there are some left they should be picked up by the QC
