### ISSUE TITLE
Non-ascii characters

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3324]
From @ValWood email:

https://curation.pombase.org/dumps/latest_build/logs/log.2022-08-04-19-49-47.chado_checks.only_ascii_characters_in_feature_name

**Comment by kimrutherford** [comment]
This is the permanent URL for that file: https://curation.pombase.org/dumps/builds/pombase-build-2022-08-04/logs/log.2022-08-04-19-49-47.chado_checks.only_ascii_characters_in_feature_name

I've changed the web server configuration so that "Δ" in log files is displayed correctly in browsers.

**Comment by manulera** [comment]
We close then! Thanks @kimrutherford
