### ISSUE TITLE
checking standard description syntax for alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3327]
check:
1. for standard description types the descriptions all conform to allowed syntax
2. that the Canto prompts and documentation describe these correctly

e.g.
for amino acid substitutions QKTTSSSEGS-122-AAAAAAAAAA.

(pombemine is a good way to assess the outliers, but you probably have scripts for this?)

**Comment by manulera** [comment]
I can make some regex patterns for kim to inforce in those fields, so that the syntax conforms to our guidelines. However, would we allow the example you put there? I think it should be `Q122A,K123A, etc.`.

While I think this kind of concise nomenclature should be the one used for displaying/ entering the data, I was also thinking whether we can also export variants to a format similar to what they do in the alliance to name the variants in the genome. For example: 
```
NC_003279.8:g.4989984_4989985insTGTA - an insertion
NC_003280.10:g.8444774C>T - point mutation
NC_003281.10:g.5497429_5497429del - single nucleotide deletion
```

Then they have a tsv file with all the variants. Each allele is in multiple rows if the allele has more than one insertion.

We could do the same for our alleles, even those in which we only know the modifications at the protein level, by referencing NCBI protein id. For example if allele ase1-35 has Q122A,K123A

https://www.ncbi.nlm.nih.gov/protein/NP_593523.1

|AlleleId|VariantId|
|-----|-----|
|ase1-35|NP_593523.1:122Q>A|
|ase1-35|NP_593523.1:123K>A|

I think this could be a good output that might be useful if people are going to do analysis on our allele variants. Also might be useful as well for kim if we eventually do this kind of display where all the variants are shown along the sequence with their effect.

**Comment by ValWood** [comment]
> However, would we allow the example you put there? I think it should be Q122A,K123A, etc..

We could force only Q122A,K123A but I think the reason we also allowed QKTTSSSEGS-122-AAAAAAAAAA
is because the full version of this allele would be very long on the gene pages. I would be happy to change them since I doubt there are very many constructed like this.

**Comment by ValWood** [comment]
> We could do the same for our alleles, even those in which we only know the modifications at the protein level, by referencing NCBI protein id.

This is a good plan. We should do a resubmission of the genome first because many of these protein changes are not 
in EMBL/NCBI.
https://www.pombase.org/status/gene-coordinate-changes

We can proceed with the update once I have done:
https://github.com/pombase/curation/issues/3024
https://github.com/pombase/curation/issues/3241
https://github.com/pombase/curation/issues/3196
https://github.com/pombase/curation/issues/3023
(these are my next priority)

**Comment by ValWood** [comment]
This one would be much longer without the shorthand for the consecutive changes

[cdt1-PIP28A8-PIP301A10 
(Q28A, L31A, FSVRK33AAAAA, R39A, Q301A, LRQSS303AAAAA, R312A, RKK314AAA aa)]

will add 32 extra digits but we should probably change all to use only R39A type

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/1276
This was originally done to replace substitution descriptions like:
"58KRRKR62 substituted with NEHG"
but these could be done as 'deletion/insertion'

**Comment by manulera** [comment]
I made a first script to check for the syntax of `amino_acid_mutation` only. It handles some error correction already. First column is allele description, then type of error, and if it's a typo, a fix.

```tsv
F349A/F387A	pattern not matched: F349A/F387A
PG292AA	typo	fixto: PG-292-AA
204-254	pattern not matched: 204-254
(CTD)S7A	pattern not matched: (CTD)S7A
SS427-8AA,S437A,S439A,SSS441-443AAA T482A,T484A,T486A,S488A,T1006A	pattern not matched: SS427-8AA
S3AD,S24D,S31D,T55D,T64D,S67D,S97D,S136D,T214D	lengths don't match: S-AD
```

Here is the full file so far:

[allele_errors.tsv.zip](https://github.com/pombase/curation/files/9457078/allele_errors.tsv.zip)

**Comment by ValWood** [comment]
This is really useful.
For the ones that need to be manually repaired, can you include either the curation session ID, or the PMID and. the gene name?
I can do the manual fixes pretty quickly.

**Comment by manulera** [comment]
Ok, so I think I figured a way to do it in a 'generalised way' that I can extend for other types of alleles. For now still doing it only for the aminoacid subsitutions, but it only leaves unfixed 68 of 201, of which all seem actual errors, not inconsistencies.

**Comment by ValWood** [comment]
If you let me have those I can add them to my fix lists.

**Comment by manulera** [comment]
As you want, but I can also do this once I have the full list. You have been amending so many lately.

This is how the format looks now for the ones that can be fixed (it suggests a change of type for those that have been categorised as aminoacid substitutions but are not):

```tsv
D331A H315A	typo	fix to: D331A,H315A
IIPGY271AAAAA	typo	fix to: IIPGY-271-AAAAA
280-353	wrong type	change type to: partial_amino_acid_deletion
R707->STOP	typo	fix to: R707*
ntG30304A	invalid	lengths don't match: ntG-A
S217D-T218E-S220D-T221E-T283E	typo	fix to: S217D,T218E,S220D,T221E,T283E
NP328AA	typo	fix to: NP-328-AA
F349A/F387A	typo	fix to: F349A,F387A
1-21,151-254	wrong type	change type to: partial_amino_acid_deletion
R510A L512G	typo	fix to: R510A,L512G
```

The full list:

[allele_errors.tsv.zip](https://github.com/pombase/curation/files/9468381/allele_errors.tsv.zip)

**Comment by ValWood** [comment]
I can do these,  I would rather you concentrate on any tasks that I can't do as  easily, and the publication.
Let me know as soon as you have the associated sessions.
v

**Comment by manulera** [comment]
Hi @ValWood

Here is the list. There is the PMID and url of the curs.

To get the ones that fall out of pattern.

```
$cat allele_errors.tsv |grep 'pattern not matched'
```

The rest I think I will be able to auto-fix sooner or later.

[allele_errors.tsv.zip](https://github.com/pombase/curation/files/9495579/allele_errors.tsv.zip)

**Comment by manulera** [comment]
This is picked up already by the QC, so closing
