### ISSUE TITLE
non coding RNAs to add to remove

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3333]
Remove and add to removed genes removed genes page (some had been removed previously)

Already on removed genes page:
 - [x] SPNCRNA.76 (this is a NUMT https://en.wikipedia.org/wiki/NUMT)
 - [x] SPNCRNA.83 (this is a NUMT https://en.wikipedia.org/wiki/NUMT)

Add to removed RNA page
SPNCRNA.503  (replaced by protein mrp49)
SPNCRNA.958 (replaced by protein new11)
SPNCRNA.4538 ( replaced by LTR)
SPNCRNA.01 prl1 (3'UTR of eta2)
SPNCRNA.34 part of tps0 UTR

**Comment by ValWood** [comment]
SPNCRNA.503 (SPNG2499) mRNA for new gene mrp49

**Comment by ValWood** [comment]
SPNCRNA.958 is new11

**Comment by ValWood** [comment]
@manulera  these are already removed  from the contigs but could you add to 
https://www.pombase.org/status/new-and-removed-genes
so that they don't get re-imported as features.

**Comment by manulera** [comment]
These are now automatically added
