### ISSUE TITLE
Questions PMID:35783577

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3353]
Hi @ValWood 

A question for the new CC paper.

* They have annotated a thermosensitive mutant to `loss of viability at high temperature (FYPO:0001387)`. I guess this should be reserved for mutants that are partially viable. In this case the mutation is lethal so I should annotate to inviable cell population with high temperature as a condition, right?
    * Also, should a term like this exist, or should it be low viability with temperature as condition?

**Comment by ValWood** [comment]
> They have annotated a thermosensitive mutant to loss of viability at high temperature (FYPO:0001387). I guess this should be reserved for mutants that are partially viable. 

 I think "loss of viability" is  where a population lose  viability over  multiple generations (but I am a bit vague about this! maybe it isn't required?, it does not appear to have a viable/inviable parent) 

> In this case the mutation is lethal so I should annotate to inviable cell population with high temperature as a condition, right?

yes

> Also, should a term like this exist, or should it be low viability with temperature as condition?

Do you mean the "loss of viability at high temperature" term?
this ticket will lead you to where we got to on this question, and the historical tickets
https://github.com/pombase/fypo/issues/3104
We have definitely got rid of some terms that included the temperature condition, and  I'm in favour of removing the terms which include it for consistency.

 We still have:
decreased/abolished cell population growth at low temperature
decreased/abolished cell population growth at low temperature
We could merge these if we know that  the condition is  always applied first.
