### ISSUE TITLE
query  Complex_annotations.tsv

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3356]
where is the config config file for Complex_annotations.tsv

Need to add
GO:0000445 
possibly others

**Comment by ValWood** [comment]
I also need to annotate 
GO:0160051 | Cyc8(Ssn6)-Tup1 general repressor complex

**Comment by kimrutherford** [comment]
> OK, I think there used to be some complicated generation procedure

Ah sorry.  I've just checked and that's still the case.  The details are here: https://github.com/pombase/website/issues/273

**Comment by ValWood** [comment]
This seems to what we do
=======

It includes everything annotated to
GO:0032991 macromolecular complex and descendants

but the following terms are filtered

pombe-embl/supporting_files/Complex_annotation_filters
These are less specific complex grouping terms, for example we filter "ribosome" in favour of
"small/large ribosomal subunit"

Only represent each complex/gene association once

======

so, I probably just need to tweak the filters

**Comment by ValWood** [comment]
fixed
