### ISSUE TITLE
chloramphenicol

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3368]
We investigated whether inhibition of mitochondrial translation by chloramphenicol (CAP) activates the Sty1- and Pap1- stress pathways in S. pombe. CAP was chosen because it has been shown to specifically inhibit mitochondrial translation in S. pombe 
refers to PMID: 20876130

check and update this page
https://www.pombase.org/browse-curation/drugs-known-pombe-targets
translation->mitochondrial translation with this reference

**Comment by ValWood** [comment]
@kimrutherford  where is this page again?

**Comment by ValWood** [comment]
Actually you could do this.
On the 'drugs' page, change 
chloramphenicol from translation to mitochondrial translation with PMID: 20876130

**Comment by kimrutherford** [comment]
> @kimrutherford where is this page again?

All the documentation is here: https://github.com/pombase/website/tree/master/src/docs

PMID:20876130 isn't in PomBase so I linked to the PubMed page instead.

The page will be updated by the morning.
