### ISSUE TITLE
Question for PMID:18562692 (Do we curate wild type phenotypes)

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3372]
@ValWood 

Maybe I have asked this before, but we do not curate phenotypes of wild-type cells treated with drugs, right?

**Comment by ValWood** [comment]
No, it's a shame. We considered it early on. And we used to keep a list of WT phenotypes in the Dropbox. Maybe we should retrieve that and continue to list WT phenotypes on the Google drive. It could be a useful resource, especially for drug treatments.
