### ISSUE TITLE
N/C term alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3380]
@manulera 

This is really just a heads up.

If users report N or C terminal deletions without reporting the amino acids, I am inclined to  convert their name to a synonym, and qualify the name with the residues (so we don't need to disambiguate later when a different N or C mutant it made.

In this particular case,  they did qualify the residues but I'm not sure the intention was for this to be interpreted as part of the allele name. However for now, I have assumed that they did and made the synonym the entire string, including g the residues.
Obviously, this can't be the name anyway because
1. ":" have special meaning in allele names
2. spaces are not allowed
so i ended up with
<img width="211" alt="gpl1" src="https://user-images.githubusercontent.com/7359272/204305387-1c622cc1-c05f-4bd1-8928-3736431dbed0.png">
as the name/synonym

**Comment by manulera** [comment]
Makes sense to me.
