### ISSUE TITLE
load all of the Atkinson RNA

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3388]
Using the 3 gff files you created for me back in June.

There are  a number of issues with the ncRNAs
1. Clearly redundant  entities
2. Some old ncRNAs are no longer supported (this is mainly ncRNAs from Wilhelm et al that are not present in this dataset).
I was hoping to use this data to resolve these but I won't have time so we should just load them all. 

We can resolve  problems later. I  have a list of problems that I noticed whilst revising the TSS's on chromosome 1 so I will open a ticket to resolve these on a case-by-case basis). We can also do some checks later for largely overlapping entities.

This will make @bahler  very happy.

**Comment by bahler** [comment]
Oh yes, this does make him happy!

Best,
-Jürg

From: Val Wood ***@***.***>
Sent: 02 December 2022 22:25
To: pombase/curation ***@***.***>
Cc: Bahler, Jurg ***@***.***>; Mention ***@***.***>
Subject: [pombase/curation] load all of the Atkinson RNA (Issue #3388)


⚠ Caution: External sender


Using the 3 gff files you created for me back in June.

There are a number of issues with the ncRNAs

  1.  Clearly redundant entities
  2.  Some old ncRNAs are no longer supported (this is mainly ncRNAs from Wilhelm et al that are not present in this dataset).
I was hoping to use this data to resolve these but I won't have time so we should just load them all.

We can resolve problems later. I have a list of problems that I noticed whilst revising the TSS's on chromosome 1 so I will open a ticket to resolve these on a case-by-case basis). We can also do some checks later for largely overlapping entities.

This will make @bahler<https://github.com/bahler> very happy.
