### ISSUE TITLE
mating-type region transcripts SPNCRNA.391

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3391]
@bahler

I would like to annotate these ncRNAs as "mating-type repeat region ncRNA" (or similar)

<img width="325" alt="Screenshot 2022-12-07 at 12 35 53" src="https://user-images.githubusercontent.com/7359272/206181122-52c10c42-b59f-4432-a08b-02c985871e8f.png">

I came to these via the small non-coding RNA SPNCRNA.391. 

but should this really part of SPNCRNA.390?

This is how it looks in the viewer?

<img width="877" alt="Screenshot 2022-12-07 at 12 36 29" src="https://user-images.githubusercontent.com/7359272/206181536-da3bd576-5332-4640-906c-7cc60c698739.png">

I'm confused why it is adjacent to SPNCRNA.390 in the viewer, but not in the contig

**Comment by ValWood** [comment]
sorry, you can't quite see SPNCRNA.391 in the contig view, I cropped it but it is just on the rhs of the flagged repeat

**Comment by bahler** [comment]
Not sure about that one, not a ncRNA we annotated.

Best,
-Jürg

From: Val Wood ***@***.***>
Sent: 07 December 2022 12:41
To: pombase/curation ***@***.***>
Cc: Bahler, Jurg ***@***.***>; Mention ***@***.***>
Subject: [pombase/curation] mating-type region transcripts SPNCRNA.391 (Issue #3391)


⚠ Caution: External sender


@bahler<https://github.com/bahler>

I would like to annotate these ncRNAs as "mating-type repeat region ncRNA" (or similar)

[Screenshot 2022-12-07 at 12 35 53]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7359272%2F206181122-52c10c42-b59f-4432-a08b-02c985871e8f.png&data=05%7C01%7Cj.bahler%40ucl.ac.uk%7Cfba945e7c8e94ea6799a08dad8504f7c%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C638060136698118423%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=j7AsFnBoF5fsXhNIHiTPhZmsNVcX02J6alx4755WBf4%3D&reserved=0>

I came to these via the small non-coding RNA SPNCRNA.391.

but should this really part of SPNCRNA.390?

This is how it looks in the viewer?

[Screenshot 2022-12-07 at 12 36 29]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7359272%2F206181536-da3bd576-5332-4640-906c-7cc60c698739.png&data=05%7C01%7Cj.bahler%40ucl.ac.uk%7Cfba945e7c8e94ea6799a08dad8504f7c%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C638060136698118423%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FiEeY1y9Ln7euxbf%2F0ttIJTlRlXv%2BW93ysxustGKDNw%3D&reserved=0>

I'm confused why it is adjacent to SPNCRNA.390 in the viewer, but not in the contig

**Comment by ValWood** [comment]
Anyway it's OK, I will just annotate this bunch as mating type region...

**Comment by ValWood** [comment]
Annotated these as "mating-type region specific"
