### ISSUE TITLE
 SPNCRNA.118  and SPNCRNA.116  are paralogs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3396]
this is really just a heads up that  SPNCRNA.118  and SPNCRNA.116  are almost identical (were originally identified as a highly similar genome region)

<img width="770" alt="Screenshot 2022-12-07 at 14 53 26" src="https://user-images.githubusercontent.com/7359272/206211452-bc6946b0-3612-4392-8331-20be707d7bd3.png">

This has consequences for the ncRNAs on the opposite strands too:
SPNCRNA .5223  complementary to SPNCRNA.118
SPNCRNA.116 is in a "low complexity region"

I

**Comment by ValWood** [comment]
Also SPNCRNA.116 looks longer (maybe processed like the snoRNAs?)

<img width="412" alt="Screenshot 2022-12-07 at 15 08 44" src="https://user-images.githubusercontent.com/7359272/206215717-35e6ef01-dfbc-487e-b97f-b57f49cd50fb.png">

**Comment by ValWood** [comment]
related ticket
https://github.com/pombase/curation/issues/3392

**Comment by bahler** [comment]
Yes, again it would be god to know the original data for this annotation.

Best,
-Jürg

**Comment by ValWood** [comment]
I annotated them as likely RNAs  because they were highly  conserved genome region, and were not protein coding or LTRs. it is however was  possible that they are some random DNA segment inserted by dsb repair process.

**Comment by ValWood** [comment]
closing, no action required. I just think the very highly conserved region might indicate something interesting...
