### ISSUE TITLE
ncRNAs in introns

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3397]
https://www.pombase.org/gene/SPSNORNA.22 should be supported by

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2538488/

and any others from this publication

**Comment by ValWood** [comment]
Notably, the remaining 1% showed a signal intensity greater than eightfold that observed at the surrounding gene ([Fig. 2d](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2538488/figure/F2/)), including three potential ncRNAs residing within introns of annotated protein-coding genes, which we verified by strand-specific qPCR—rps3, SPBC1734.10c and SPAC6F6.03c ([Supplementary Fig. 6](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2538488/#SD1) and [Supplementary Table 3](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2538488/#SD1) online). Unique transcripts processed from introns are rare; only four are annotated in S. pombe, and all are snoRNAs ([Fig. 2d](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2538488/figure/F2/)).

**Comment by ValWood** [comment]
@bahler I'm surprised nobody has looked yet if these are snoRNAs.
https://www.pombase.org/term/PBO:0001137

SPNCRNA.498 in ipa1
SPNCRNA.497 in rps3
the SPAC6F6.03c(nog2) one is now annotated as snR191

**Comment by ValWood** [comment]
oh, 

<img width="974" alt="Screenshot 2022-12-07 at 16 30 46" src="https://user-images.githubusercontent.com/7359272/206235803-ddf9efbb-19a7-4516-bf1c-947623b910ba.png">

**Comment by bahler** [comment]
I myself only rarely look if anything in life is a snoRNA.

Best,
-Jürg

**Comment by ValWood** [comment]
Annotated as snos (or one as potential sno)
