### ISSUE TITLE
review GOA PAINT annotation for chado load

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#34]
not in a hurry to do this, but we can load immediately after an update, which will give us a chance to see when new annotations are created, and if there are too many problems to import.

 We will  wait until we are assured that all of the previously reported problems are fixed

Original comment by: ValWood

**Comment by ValWood** [comment]
now in progress, replaced by
https://github.com/pombase/pombase-chado/issues/493

**Comment by ValWood** [comment]
I'll close this as there is a replacement ticket on chado tracker
