### ISSUE TITLE
sncRNA centromeric/ centromere proximal

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3400]
Centromere proximal
SPNCRNA.481		non-coding RNA (predicted)	89

do all...

**Comment by ValWood** [comment]
It doesn't make sense to describe these as antisense or even intergenis, so we need a way to separate them out.

For now, I am labellling 
"centromeric non-coding RNA" if they are within the centromere proper
"centromere proximal non-coding RNA" if they are in the centromere boundary region

**Comment by ValWood** [comment]
- [ ] chromosome 1
- [ ] chromosome 2
- [ ] chromosome 3

**Comment by ValWood** [comment]
check tomorrow

**Comment by ValWood** [comment]
Also check warning , centromeric and no orf

**Comment by bahler** [comment]
Sounds sensible
