### ISSUE TITLE
scnRNA LOW confidence by ATkinson (i,e not detected), but submitted with, and supported, by Atkinson dataset

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3404]
These ncRNAs are reported as LOW CONFIDENCE by Atkinson, was in they are not detected.
They were identified by Wilhelm, and are annotated as "This transcript could be on either strand"

These were submitted back to us with he Atkinson data, so currently in PomBAse they are not supported by Wilhelm, and Altkinson (even though Atkinson did not detect them)

SPNCRNA.290		non-coding RNA (predicted)	Atkinson LOW probably opposite strand SPNCRNA.4561
SPNCRNA.310		non-coding RNA (predicted)	Atkinson LOW feature not detectable on either strand in TV1 or TV2 
SPNCRNA.386		non-coding RNA (predicted)	Atkinson LOW feature not detectable on either strand in TV1 or TV2 
SPNCRNA.208		non-coding RNA (predicted)	Atkinson LOW feature not detectable on either strand in TV1 or TV2 
SPNCRNA.138		non-coding RNA (predicted)	(this one does not say that the strand is unknown) Atkinson LOW feature not detectable on either strand in TV1 or TV2 

@bahler do you think these should be kept, or are due to technical limitations (I think the ones 
 from Wilhelm which had no strand specificity were from microarray!)

**Comment by ValWood** [comment]
SPNCRNA.265		non-coding RNA (predicted)	

This one is "transcript could be on either strand" from Wilhelm.
Which strand is it?
<img width="460" alt="SPNCRNA 265" src="https://user-images.githubusercontent.com/7359272/206451351-db026c1d-18d8-400c-af49-4512576313bc.png">

**Comment by bahler** [comment]
Seems to be lower strain, but overlap 4432

Best,
-Jürg

**Comment by ValWood** [comment]
These were all dealt with in other tickets
