### ISSUE TITLE
lnc  SPNCRNA.4525

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3407]
In the viewer

<img width="943" alt="Screenshot 2022-12-08 at 15 53 12" src="https://user-images.githubusercontent.com/7359272/206494753-df9f1e8a-a484-443d-9e51-f289b69146e9.png">

and the supp data says it is antisense to 

but in the annotation it looks completely different:
<img width="247" alt="Screenshot 2022-12-08 at 15 55 56" src="https://user-images.githubusercontent.com/7359272/206495653-d422ed5f-0e57-4d78-99c0-0102913d96c4.png">

@bahler any idea why?

**Comment by bahler** [comment]
No idea. In large-scale datasets there will always be some errors.

Best,
-Jürg

From: Val Wood ***@***.***>
Sent: 08 December 2022 15:57
To: pombase/curation ***@***.***>
Cc: Bahler, Jurg ***@***.***>; Mention ***@***.***>
Subject: [pombase/curation] lnc SPNCRNA.4525 (Issue #3407)


⚠ Caution: External sender


In the viewer

[Screenshot 2022-12-08 at 15 53 12]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7359272%2F206494753-df9f1e8a-a484-443d-9e51-f289b69146e9.png&data=05%7C01%7Cj.bahler%40ucl.ac.uk%7Cab27cc5787b945d0748e08dad934c93b%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C638061117978653298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3KUJy35ViAvw905Chawc3OW2StMX7Q4FDnOp6TIxCO0%3D&reserved=0>

and the supp data says it is antisense to

but in the annotation it looks completely different:

[Screenshot 2022-12-08 at 15 53 12]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7359272%2F206495441-00f31a4b-60fb-485f-8c61-99f4c2dd8756.png&data=05%7C01%7Cj.bahler%40ucl.ac.uk%7Cab27cc5787b945d0748e08dad934c93b%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C638061117978653298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QzFoTUqaVOw6U8IgK850pmDqvG6F4CgcZfDe14pne40%3D&reserved=0>

@bahler<https://github.com/bahler> any idea why?

**Comment by ValWood** [comment]
closing...
