### ISSUE TITLE
Missing gene, load failed: SPNCRNA.1707

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3425]
Hi Val.

This session references a gene (SPNCRNA.1707) that's gone from Chado:
   https://curation.pombase.org/pombe/curs/4f36d75cf334acbc/feature/gene/view/20/ro

The loader can't cope with that yet so the load is failing.

**Comment by ValWood** [comment]
changed to SPNCRNA.5748 which has


/primary_name="prl102"
/synonym="prl2"
/synonym="SPNCRNA.1707"
/systematic_id="SPNCRNA.5748"
/controlled_curation="term=name description, Pdc2-Repressed lncRNA; db_xref=PMID:28031482; date=20170419"
/product="Pdc2-Repressed lncRNA"
/db_xref="PMID:29914874"
/db_xref="PMID:28031482"

**Comment by kimrutherford** [comment]
Hi Val.  There's another gene in Canto that has gone from Chado: https://curation.pombase.org/pombe/curs/c757e60bdb79c5cb/feature/gene/view/139/ro

**Comment by ValWood** [comment]
SPNCRNA.574 is merged with SPNCRNA.1608
I removed SPNCRNA.574  from the gene list in the above session (it isn't necessary to list genes included in extensions). However, I could not find the annotation with the extension in the session itself, or in the PHAF files?

**Comment by kimrutherford** [comment]
> However, I could not find the annotation with the extension in the session itself, or in the PHAF files?

Is this what you're after?:

https://curation.pombase.org/pombe/curs/c757e60bdb79c5cb/feature/genotype/view/1/ro

![image](https://user-images.githubusercontent.com/90474/209786989-fa61cd1e-a2e7-4f0b-8717-0cb745824ab5.png)

**Comment by ValWood** [comment]
yes but that is in "existing annotation" not in the editable annotations for the session?

**Comment by kimrutherford** [comment]
> yes but that is in "existing annotation" not in the editable annotations for the session?

Good point!  :-)

I've checked and that gene is gone from Canto.  The existing extension in my screenshot will disable as soon as we get a successful Chado load done.

**Comment by kimrutherford** [comment]
> disable

Should be "disappear".

**Comment by kimrutherford** [comment]
Sorry, here's another one:
SPNCRNA.504 in this session: https://curation.pombase.org/pombe/curs/f44eccf92770b920/feature/gene/view/637/ro

**Comment by ValWood** [comment]
got is, this was cbp1-antisense, but is already remapped to assayed_using(SPNCRNA.1608)

**Comment by ValWood** [comment]
>SPNCRNA.504 in this session: 
fixed

**Comment by kimrutherford** [comment]
Thanks!  I think that's the last of the problems.  I'll check the load in the morning.

**Comment by ValWood** [comment]
i forgot to commit :(

**Comment by ValWood** [comment]
oh actually the changes this time were only in canto, so OK

**Comment by kimrutherford** [comment]
> I'll check the load in the morning.

All good now.
