### ISSUE TITLE
Allele synonyms with spaces

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3428]
Hi Val.

Here's the table of synonyms that have spaces: [allele_synonyms_with_spaces.txt](https://github.com/pombase/curation/files/10333920/allele_synonyms_with_spaces.txt)

Most of the spaces look like they should be there.

As I said on the call, some alleles come from multiple sessions and after they are merged into Chado it's not possible to know switch session a synonym came from.  Most of the suspect synonyms have only one or two sessions in the list.

I looked up in Canto to see which sessions these synonyms came from because the list of sessions in the table was long:

"cut11-3 cut11-4" is from 36f40baed62fc60c
"rec8-176::3HA-6His-kanMX6 rec8-176::3HA-6His-kanMX6" is from 35aab4b08bf43fb8
"nmt1 lem2+" and "lem2+ OE" are from 7bbe318b26434db4

Let me know if there are any others you'd like me to look up.

**Comment by ValWood** [comment]
All done. Did you say there would be a log file of these too?
