### ISSUE TITLE
GO slims pertenence

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3438]
Hello @ValWood @kimrutherford. I was looking into replying to the helpdesk question, but I am a bit lost on what criteria we use to decide whether a given GO term belongs to a certain slim (or to a GO page in pombase).

My understanding from the gene pages is that if a child is related to a parent through an `is_a` or `part_of` relationship, the term is included. However, following this criteria I don't get to the same subset for each GO slim (the difference is small). This is one example:

`GO:0004861`, cyclin-dependent protein serine/threonine kinase inhibitor activity. In the go json file (http://current.geneontology.org/ontology/go.json) it is linked to `GO:0030234` enzyme regulator activity through is_a relationships (see graph below, connecting term in bottom right to top left).

![Screenshot 2023-01-23 at 19 26 30](https://user-images.githubusercontent.com/22526102/214132170-6ea0de8f-4334-424e-aa7f-7fe03275b373.png)

However, in PomBase it is not listed under `GO:0030234` (https://www.pombase.org/term/GO:0030234), neither in the quickgo site (see how the parent `GO:0016538` directly links to molecular function https://www.ebi.ac.uk/QuickGO/term/GO:0016538 without passing through enzyme regulator activity).

**Comment by ValWood** [comment]
I can see the reason



GO:0016538   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0016538/complete)
cyclin-dependent protein serine/threonine kinase regulator activity

2022-12-12 | Added | RELATION | is a GO:0003674 (molecular_function)
-- | -- | -- | --
2022-12-12 | Deleted | RELATION | is a GO:0019887 (protein kinase regulator activity)


but I don't know why this change was made. It looks like a mistake,  @pgaudet  do you know why?

**Comment by pgaudet** [comment]
I think this happened when I worked on this ticket: 
https://github.com/geneontology/go-ontology/issues/24627

Looks like some terms fell through the cracks - hopefully this will now be fixed. 

Thanks, Pascale

**Comment by ValWood** [comment]
Thanks!
