### ISSUE TITLE
Extra column in modification file

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3441]
@ValWood @kimrutherford

There is an extra column in the svn modification file `trunk/external_data/modification_files/PMID_34296454_modifications.tsv`, called `Multiplicity`. I think this is probably a mistake, but just wanted to double check with you in case it is a flag for something.

If you tell me it can be removed, I can do so.

**Comment by kimrutherford** [comment]
Hi Manu.

Yes, you're right, it's a mistake.  We decided to store the multiplicity as an extension so we never used that column.

**Comment by manulera** [comment]
Ok, so I will remove it then.
