### ISSUE TITLE
PMID:30475921 insertion coordinates are wrong

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3444]
I will check this on my side, just putting here for the future

**Comment by ValWood** [comment]
Let me know if I need to do anything here.

**Comment by manulera** [comment]
This error is now captured by the pipeline:

https://github.com/pombase/allele_qc/blob/3e4f769adbb1f9c7d2f24c9f06fc5463e9f2f1c0/results/allele_cannot_fix_sequence_errors.tsv?plain=1#L24-L25

If I am not mistaken, they are using a different wtf18 sequence in the paper from the one that we have in PomBase

**Comment by manulera** [comment]
I guess we can close, it's just another one of those errors that are now logged.

**Comment by ValWood** [comment]
OK, FYI  I will work through this log file.
(I have started, the first 4 I have mailed the authors I hope to find time to do the rest this week)
