### ISSUE TITLE
structures in PDB but don't have an APPROVED session:

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3456]
I don't know if it's useful but here's the list of publications with structures in PDB but don't have an APPROVED session:

```
 PMID:10801440
 PMID:11273706
 PMID:11709168
 PMID:11832950
 PMID:12018481
 PMID:14614509
 PMID:15979093
 PMID:16138082
 PMID:16777962
 PMID:16790931
 PMID:17190600
 PMID:17937917
 PMID:18381891
 PMID:18676809
 PMID:19026779
 PMID:19028693
 PMID:19307292
 PMID:19362535
 PMID:19363481
 PMID:19394293
 PMID:19474788
 PMID:19516334
 PMID:19581297
 PMID:19680239
 PMID:19884503
 PMID:20008938
 PMID:20089861
 PMID:21217703
 PMID:21444718
 PMID:21481773
 PMID:21610214
 PMID:22001694
 PMID:22081013
 PMID:22085934
 PMID:22437499
 PMID:22658721
 PMID:22971103
 PMID:23019579
 PMID:23201273
 PMID:23273506
 PMID:23481256
 PMID:23583778
 PMID:23609449
 PMID:23857276
 PMID:24449894
 PMID:24862735
 PMID:24939935
 PMID:25414009
 PMID:25428765
 PMID:25619998
 PMID:25883047
 PMID:25959226
 PMID:26062005
 PMID:26088418
 PMID:26215567
 PMID:26292707
 PMID:26673708
 PMID:26960127
 PMID:27105116
 PMID:27165520
 PMID:28162934
 PMID:28223353
 PMID:28241144
 PMID:28467824
 PMID:28533364
 PMID:28572513
 PMID:28735863
 PMID:28988770
 PMID:29160296
 PMID:29681468
 PMID:29804820
 PMID:29892076
 PMID:30051891
 PMID:30295604
 PMID:30651569
 PMID:30808655
 PMID:30911189
 PMID:31048492
 PMID:31740076
 PMID:32374864
 PMID:32518066
 PMID:32610137
 PMID:32755595
 PMID:32839613
 PMID:32958768
 PMID:33106658
 PMID:33536434
 PMID:33536435
 PMID:34100774
 PMID:34194665
 PMID:34678589
 PMID:35058438
 PMID:35512546
 PMID:35849625
 PMID:36002457
 PMID:36250672
 PMID:36423630
 PMID:36468882
```

_Originally posted by @kimrutherford in https://github.com/pombase/pombase-chado/issues/1061#issuecomment-1426766722_

**Comment by ValWood** [comment]
Use this list,

PMID:11709168	Wrong organism
PMID:11832950	New
PMID:12018481	Curatable
PMID:14614509	Curatable
PMID:15979093	Wrong organism
PMID:16138082	Structure
PMID:16777962	Curatable
PMID:16790931	Wrong organism
PMID:17190600	Curatable
PMID:17937917	Curatable
PMID:18381891	Structure
PMID:18676809	Curatable
PMID:19026779	New
PMID:19028693	Curatable
PMID:19307292	Curatable
PMID:19362535	Curatable
PMID:19363481	Curatable
PMID:19394293	Curatable
PMID:19474788	Curatable
PMID:19516334	Curatable
PMID:19581297	New
PMID:19680239	Curatable
PMID:19884503	Curatable
PMID:20008938	Curatable
PMID:20089861	Curatable
PMID:21217703	Wrong organism
PMID:21444718	Curatable
PMID:21481773	Curatable
PMID:21610214	Curatable
PMID:22001694	New
PMID:22081013	Curatable
PMID:22085934	Wrong organism
PMID:22437499	Curatable
PMID:22658721	Curatable
PMID:22971103	Other
PMID:23019579	Curatable
PMID:23201273	Curatable
PMID:23273506	Curatable
PMID:23481256	New
PMID:23583778	Wrong organism
PMID:23609449	Curatable
PMID:23857276	Wrong organism
PMID:24449894	Curatable
PMID:24862735	Curatable
PMID:24939935	Curatable
PMID:25414009	Curatable
PMID:25428765	Method or reagent
PMID:25619998	New
PMID:25883047	Curatable
PMID:25959226	Curatable
PMID:26062005	New
PMID:26088418	Curatable
PMID:26215567	Curatable
PMID:26292707	Wrong organism
PMID:26673708	Curatable
PMID:26960127	Method or reagent
PMID:27105116	Curatable
PMID:27165520	Curatable
PMID:28162934	Curatable
PMID:28223353	Curatable
PMID:28241144	Curatable
PMID:28467824	Structure
PMID:28533364	Curatable
PMID:28572513	Structure
PMID:28735863	Curatable
PMID:28988770	New
PMID:29160296	Structure
PMID:29681468	Curatable
PMID:29804820	Curatable
PMID:29892076	Curatable
PMID:30051891	Curatable
PMID:30295604	Curatable
PMID:30651569	Curatable
PMID:30808655	Curatable
PMID:30911189	Curatable
PMID:31048492	New
PMID:31740076	New
PMID:32374864	Structure
PMID:32518066	New
PMID:32610137	Curatable
PMID:32755595	Curatable
PMID:32839613	Curatable
PMID:32958768	New
PMID:33106658	Curatable
PMID:33536434	Curatable
PMID:33536435	Structure
PMID:34100774	Structure
PMID:34194665	Structure
PMID:34678589	New
PMID:35058438	Curatable
PMID:35512546	Curatable
PMID:35849625	Curatable
PMID:36002457	Curatable
PMID:36250672	New
PMID:36423630	Curatable
PMID:36468882	Curatable

**Comment by ValWood** [comment]
- [ ] PMID:10801440 from first list
Hi @kimrutherford , can you remember the difference between the first list and the second list?

**Comment by kimrutherford** [comment]
>  can you remember the difference between the first list and the second list?

One list was publications with structures but the publication isn't in Chado (that's the small list).  The longer list was publications with structures that don't have an APPROVED session (there are publication that are in Chado but aren't APPROVED).

**Comment by ValWood** [comment]
Can you paste in the IDs that are in the first list but not in the second list (or remind me where the txt file for the 2nd list is)?
sorry, I initially thought the fist list was a subset of the second list.

**Comment by kimrutherford** [comment]
> Can you paste in the IDs that are in the first list but not in the second list

All of the publications from the first list will be in the second.

> (or remind me where the txt file for the 2nd list is)

Both lists are in this issue: https://github.com/pombase/pombase-chado/issues/1061

IDs not in Chado (as of Feb 12th): https://github.com/pombase/pombase-chado/issues/1061#issuecomment-1426703438

The 2nd list, of PubMed IDs from PDB that aren't APPROVED (which includes the IDs from the previous list) are in a comment that's been marked as outdated [in issue 1061](https://github.com/pombase/pombase-chado/issues/1061) but's also at the top of this issue.

**Comment by kimrutherford** [comment]
Would you like an updated version of either file?

**Comment by ValWood** [comment]
I was a bit confused because (at least) the first 2 items in the first list are not in the 2nd list (even though I didn't change them)

**Comment by ValWood** [comment]
Actually I did do
PMID:10801440

but 
 PMID:11273706
is not done yet, but isn't in the second list

**Comment by ValWood** [comment]
Anyway I don't need an updated list yet. I will continue to work through list 2, then I will request a new list of everything with a structure that has not been through approval.  I don't want to start on a new list yet as I have lots of status notes in this one. I think I will be another week or two processing these papers (have done over 30- they are usually quick, but the occasional one slows me down).

**Comment by kimrutherford** [comment]
> PMID:11273706
> is not done yet, but isn't in the second list

Now I'm confused.  That PMID is only in the second list, the one at the top of this issue.  It's in Chado but not approved.

**Comment by ValWood** [comment]
RIght I'm calling the list at the top the first list.
So the bottom list is a subset of the top list- that makes more sense.

**Comment by ValWood** [comment]
PMID:36358328
not in the list so this might not be all of the structure pubs?

**Comment by kimrutherford** [comment]
> PMID:36358328
> not in the list so this might not be all of the structure pubs?

That one we knew about:

https://github.com/pombase/pombase-chado/issues/1061#issuecomment-1427580211

> > We should check why this structure isn't in
https://www.pombase.org/reference/PMID:36358328
(maybe it takes pdb a while to get the structures curated...)
>
> I mailed pdb to see why this structure is missing

On Thursday they emailed me and said:

> Thank you for raising this. I have looked into it and resolved it. This should be fixed in next week's release.

The PMID wasn't associated with the structure in PDB.  Sorry I forgot to comment about it on the issue.

**Comment by kimrutherford** [comment]
> On Thursday they emailed me and said:
>
> > Thank you for raising this. I have looked into it and resolved it. This should be fixed in next week's release.

Sorry, ignore that.  I emailed about PMID:35314193.  I think it was you you emailed about PMID:36358328

But I've checked and I don't know why PMID:36358328 was missing from the list.  I've just re-run the query and it's there.  There were no other differences.

**Comment by ValWood** [comment]
OK, probably a synching issue. It's a recent pub.
