### ISSUE TITLE
Strain background in HTP datasets

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3462]
Hi @ValWood I am almost done with Maria's paper dataset. Just an extra question regarding preparation of the data for PomBase:

https://www.pombase.org/documentation/phenotype-data-bulk-upload-format

From the docs "The Parental strain column is for the parental strain designation, such as 972 h-, 975 h+, etc. This column must be filled in, but you can use “unknown” if you don’t know the original background."

For the paper of Maria they used:

* For the coding gene deletion library: the Bioneer collection, but they outcross it to make it prototroph: `we generated a prototroph version of Bioneer V.5 deletion library`.
* For the RNA deletion library: In total, 113 lincRNA genes were deleted in the 972 h- background, and 73 lincRNA genes were deleted in the 968 h90 background, the latter including 15 newly identified lincRNAs.

Do all these strains have a common ancestor that we can put as the parental strain?

**Comment by manulera** [comment]
Sorry my first comment was truncated so in an email you may not see the full question

**Comment by ValWood** [comment]
Hmm, I don't know what 968 is. Better to check with @bahler. For now you can put 'unknown or 972 h-', since we don't display this information in PomBase and add a suitable label  later (we can update the 73 that are a different strain if we can't identify a common lineage). 
We only added in case wanted it in the future, and since it is easy for large datasets.

**Comment by bahler** [comment]
What?! 968 is the original homothallic strain from Leupold from which ALL other S. pombe strains are derived, including the heterothallic 972 and 975. It is **THE** strain! Not knowing about 968 is not knowing about pombe. Is @ValWood taking the piss?!

**Comment by ValWood** [comment]
I glaze over when strain labels are mentioned. For me, everything starts with 972.

**Comment by yococonocomo** [comment]
Hi, the ncRNA deletion collection h- is derived from 972, the bioneer was crossed out with 972, so the background would be a mix between 972 and bioneer, the h90 strains are 968
