### ISSUE TITLE
Deleted genes still present in exon dataset

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3467]
Hello @kimrutherford I noticed that the exon files, like the one below

https://www.pombase.org/data/genome_sequence_and_features/Exon_Coordinates/chromosome1.exon.coords

Contain systematic ids of deleted systematic ids. I used [this script](https://github.com/manulera/phenomics_paper_HTP/blob/master/checks/check_deleted_genes_in_exons.py) and found that in chromosomes 1,2,3 the following deleted systematic_ids are listed:

<details>
  <summary>Click for full list</summary>

  ```
  SPAC110.05
SPAC823.02
SPAPB1A11.05
SPBC713.13
SPBC8E4.02c
SPNCRNA.01
SPNCRNA.06
SPNCRNA.08
SPNCRNA.09
SPNCRNA.108
SPNCRNA.1084
SPNCRNA.113
SPNCRNA.114
SPNCRNA.1163
SPNCRNA.119
SPNCRNA.1217
SPNCRNA.1256
SPNCRNA.126
SPNCRNA.127
SPNCRNA.129
SPNCRNA.138
SPNCRNA.143
SPNCRNA.144
SPNCRNA.145
SPNCRNA.1481
SPNCRNA.1531
SPNCRNA.1541
SPNCRNA.1631
SPNCRNA.197
SPNCRNA.20
SPNCRNA.205
SPNCRNA.208
SPNCRNA.210
SPNCRNA.227
SPNCRNA.236
SPNCRNA.246
SPNCRNA.248
SPNCRNA.254
SPNCRNA.263
SPNCRNA.265
SPNCRNA.272
SPNCRNA.277
SPNCRNA.289
SPNCRNA.290
SPNCRNA.299
SPNCRNA.310
SPNCRNA.321
SPNCRNA.325
SPNCRNA.329
SPNCRNA.334
SPNCRNA.341
SPNCRNA.342
SPNCRNA.379
SPNCRNA.38
SPNCRNA.386
SPNCRNA.410
SPNCRNA.411
SPNCRNA.419
SPNCRNA.424
SPNCRNA.426
SPNCRNA.436
SPNCRNA.444
SPNCRNA.458
SPNCRNA.46
SPNCRNA.490
SPNCRNA.495
SPNCRNA.503
SPNCRNA.504
SPNCRNA.507
SPNCRNA.508
SPNCRNA.510
SPNCRNA.514
SPNCRNA.515
SPNCRNA.523
SPNCRNA.528
SPNCRNA.532
SPNCRNA.538
SPNCRNA.539
SPNCRNA.541
SPNCRNA.543
SPNCRNA.551
SPNCRNA.552
SPNCRNA.553
SPNCRNA.557
SPNCRNA.559
SPNCRNA.564
SPNCRNA.574
SPNCRNA.578
SPNCRNA.59
SPNCRNA.681
SPNCRNA.72
SPNCRNA.729
SPNCRNA.73
SPNCRNA.74
SPNCRNA.81
SPNCRNA.860
SPNCRNA.87
SPNCRNA.88
SPNCRNA.882
SPNCRNA.89
SPNCRNA.91
SPNCRNA.911
SPNCRNA.962
SPNCRNA.99
  ```
</details>

**Comment by manulera** [comment]
Related to #3465

**Comment by kimrutherford** [comment]
Thanks for pointing those out.  They haven't been update since 2017.  We generated new version each night, like this: https://www.pombase.org/nightly_update/misc/chromosome_1.exon.coords.tsv

I'll update the load script to copy the generated files to the Exon_Coordinates directory.

**Comment by kimrutherford** [comment]
> I'll update the load script to copy the generated files to the Exon_Coordinates directory.

That's done now.   I've also manually updated the files so if you do `svn update` you'll get the latest versions.

I did the same for the `genome_sequence_and_features/CDS_Coordinates` directory which was also out of date.

**Comment by manulera** [comment]
Nice! We close then?

**Comment by kimrutherford** [comment]
Yep!
