### ISSUE TITLE
uvi15 UTRs and alternative transcript

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#347]
pombase has 791 bp primary transcript annotated, but that's probably not right

from PMID:7898433 - txn start mainly -50, some -53; polyA at 980, 1175

from PMID:10954610 - 54 bp 1186-1239 (inclusive) important for reg, so initial transcript must extend at least that far (but note this is beyond polyA, so not part of mature mRNA)
  also, primary transcript goes at least to 1287 (fig 7)

Original comment by: mah11

**Comment by mah11** [comment]
was closed as duplicate, but didn't say duplicate of what, and I don't see anything applicable

**Comment by mah11** [comment]
see #61
