### ISSUE TITLE
Curating Chip-Seq data

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3471]
Hi @ValWood 

Do we curate some results from Chip-Seq has phenotypes?

E.g. in this paper PMID:36793083 they show that in the deletion of gcn5 the occupancy of nse4 is reduced in gene regions and enhanced in repeats or intergenic regions.

<img width="338" alt="Screenshot 2023-03-06 at 11 54 51" src="https://user-images.githubusercontent.com/22526102/223104142-11cc2eb1-ac00-4640-8571-54527886968b.png">

**Comment by ValWood** [comment]
You can use
https://www.pombase.org/term/FYPO:0004161

With CHIP evidence
I  would probably do rDNA and centromeric region, but intergenic regions doesn't look very significant?

**Comment by manulera** [comment]
Ok thanks!
