### ISSUE TITLE
snoRNA without SNO type  systematic IDs lost

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3479]
I noticed yesterday while working on the genome resubmission pub that 

 SPNCRNA.723 snoRNA  had lost its systemtic ID SPSNORNA.07  |

A few other SNO's no longer have a systematic ID

SPNCRNA.445 snoR61 small nucleolar RNA snR61
SPNCRNA.1709 U2 snRNA-specific guide RNA
SPNCRNA.499 snR191 small nucleolar RNA snR191

This could have happened when the Atkinson data was imported?

@manulera   can you check the history and see if any ohter ncRNAs are affected by this?

**Comment by manulera** [comment]
Hi @ValWood. Not sure I follow, is `SPSNORNA.07` not a systematic id? For the first example, there seems to be separate entries for several and they all have retained `SPNCRNA.723` as a synonym:

https://www.pombase.org/gene/SPNCRNA.723
https://www.pombase.org/gene/SPSNORNA.07


```
FT   snoRNA          1200009..1200876
FT                   /db_xref="PMID:29914874"
FT                   /db_xref="PMID:21511999"
FT                   /systematic_id="SPNCRNA.723"
FT                   /product="snoRNA primary transcript"
FT   snoRNA          1200168..1200253
FT                   /controlled_curation="term=orthologous to S. cerevisiae
FT                   snR41; date=20061113"
FT                   /primary_name="snR41"
FT                   /product="small nucleolar RNA snR41 (predicted)"
FT                   /systematic_id="SPSNORNA.07"
FT                   /synonym="SPNCRNA.723"
FT   snoRNA          1200394..1200501
FT                   /controlled_curation="term=orthologous to S. cerevisiae
FT                   snR70; date=20061113"
FT                   /primary_name="snR70"
FT                   /product="small nucleolar RNA snR70 (predicted)"
FT                   /systematic_id="SPSNORNA.08"
FT                   /synonym="SPNCRNA.723"
FT   snoRNA          1200646..1200729
FT                   /controlled_curation="term=orthologous to S. cerevisiae
FT                   snR51; date=20061113"
FT                   /primary_name="snR51b"
FT                   /product="small nucleolar RNA snR51b (predicted)"
FT                   /systematic_id="SPSNORNA.09"
FT                   /synonym="SPNCRNA.723"
```

**Comment by ValWood** [comment]
Ah, OK, maybe to avoid confusion I should add all the sno-Ids as synonyms of SPNCRNA.723

so, it's just the disappeared ones that are a problem...

**Comment by manulera** [comment]
But where have they disappeared? I can find them all in PomBase and in the svn repo

https://www.pombase.org/gene/SPNCRNA.445
```
FT   snoRNA          complement(join(3874254..3874461,3874798..3874906))
FT                   /db_xref="PMID:18488015"
FT                   /db_xref="EMBL:AJ617330"
FT                   /systematic_id="SPNCRNA.445"
FT                   /synonym="SPNGAF57"
FT                   /product="small nucleolar RNA snR61"
FT                   /primary_name="snoR61"
FT                   /controlled_curation="term=warning, gene structure
FT                   updated; db_xref=PMID:18488015; cv=warning; date=20080808"
```

https://www.pombase.org/gene/SPNCRNA.1709

```
FT   snoRNA          1676220..1676335
FT                   /SO="SO:0000275"
FT                   /db_xref="EMBL:BK009173"
FT                   /product="U2 snRNA-specific guide RNA"
FT                   /systematic_id="SPNCRNA.1709"
```

https://www.pombase.org/gene/SPNCRNA.499

```
FT   snoRNA          complement(2735048..2735175)
FT                   /db_xref="PMID:29914874"
FT                   /db_xref="PMID:18641648"
FT                   /product="small nucleolar RNA snR191"
FT                   /systematic_id="SPNCRNA.499"
FT                   /controlled_curation="term=warning, ncRNA in intron;
FT                   db_xref=PMID:18641648; date=20100426"
FT                   /controlled_curation="term=warning, new gene;
FT                   db_xref=PMID:18641648; date=20100426"
FT                   /primary_name="snR191"
```

**Comment by ValWood** [comment]
I thought that all od the snos had an ID in the form 
SPSNORNA
but it seems that these probably never did.....

**Comment by ValWood** [comment]
We  never change sysatemtic IDs usually, they only change for deletions and merge, but I wonder if I  make SNORNA.55 the systematic ID for SPNCRNA.723 (SPNCRNA.723 will be a synonym), so that all SNOs have a SNORNA ID (the others are OK because they represent unprocessed transcripts, usually covering multiple snos). Or should I leave it as is and make SNORNA.55 a synonym?

CC @manulera

**Comment by manulera** [comment]
Sorry I had not seen this. Sounds like making SNORNA.55 a synonym would be less disruptive. But I don't know what best practice is.

**Comment by ValWood** [comment]
I will do that. People should rely on 'type' really.
