### ISSUE TITLE
Go protein binding vs. physical interaction

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3481]
Hi @ValWood,

I have a question regarding GO annotation for physical interactions.

In one of the last CC papers (PMID:33536434), they study binding of proteins Mmi1 and Mei2 to a new lncRNA, mamRNA. They do so using co-IP and they show that mutations of key residues from either protein on domains known to bind to RNA disrupt he co-IP of Mei2 and Mmi1 with mamRNA, but also with other meiotic RNAs. I have annoted those interactions as physical interactions, but I was wondering if they also can / should be annotated as GO:MF RNA binding. The mechanistic evidence for mei2-mamRNA-mmi1 associating together is quite strong, the other RNAs are not studied so much, so they could be co-IPed through a partner.

**Comment by manulera** [comment]
These were the annotations, for the record, to be added eventually if so:

![Screenshot 2023-03-27 at 16 16 01](https://user-images.githubusercontent.com/22526102/227984824-67448a80-c306-4ef7-a9c7-bff6856e3e27.png)

**Comment by ValWood** [comment]
I think we can keep the others,. They are likely mmi1 targets. Can refine later.

**Comment by manulera** [comment]
I see, what about this one?

![Screenshot 2023-03-28 at 10 19 50](https://user-images.githubusercontent.com/22526102/228190592-7ec79e0d-2d70-4294-91a6-7c8750a47d83.png)

THey also show that mamRNA is important for the mei2-mediated inhibition of mmi1, this occurs on the sme2+ locus, which recruits mei2-mamRNA-mmi1, and this inhibits mmi1. This could be the starting point, but what would be the biological process to use here? I thought positive regulation of meiotic entry?

**Comment by ValWood** [comment]
Yes, I think so since that is the main point of the paper!
These are the current annotations to switching:
https://www.pombase.org/results/from/id/37636cd0-dad9-45f8-9519-5ada40035642
I wonder if the transcription factor annotations  (mei4 and fkh2) are a bit suspect here? Presumably the switch has already been flipped  once the meiotic program TFs are active?
