### ISSUE TITLE
Annotation with reporter

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3487]
@ValWood should we delete this annotation? (PMC1635391)

![Screenshot 2023-03-31 at 17 02 22](https://user-images.githubusercontent.com/22526102/229171827-04622192-0e29-4753-b739-b39a271881a7.png)

The evidence here is that they took different fragments of DNA upstream of the prz1 gene (pressumably prz1 promoter) and put them in front of luciferase gene, and quantify signal in absence / presence of Calcium.

They see that when they go from putting the 1.2Kb 5' upstream fragment to the 1.5 Kb 5' upstream fragment, they get an increase in expression with Calcium, so the Calcium-response motif must be there. However, strictly a mutant of that region is never made. I see the intent in the annotation, but I am not sure how to go about it.

**Comment by ValWood** [comment]
I don't think we need it. There are GO annotations to capture the calcium responsiveness.
We can see that a) prz1 act n calcium responsive promoters
and b) prz1  transcriptionally regulates itself. So at least this info  is there. I think you can remove it.

**Comment by ValWood** [comment]
deleted
