### ISSUE TITLE
Negative complementation annotation

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3489]
cc @ValWood

from PMID:25866389

<img width="1035" alt="Screenshot 2023-04-03 at 17 22 56" src="https://user-images.githubusercontent.com/22526102/229569810-5f5f3bd0-682f-462b-afb3-d93032aed0c0.png">

I think we should probably delete the phenotype annotation. It seems to be captured by that special term, but I wonder if there is a way to use our existing annotations in Contig files to represent NOT complementation.

See [wiki](https://github.com/pombase/curation/wiki/Working-with-contig-files#annotating-complementation-with-foreign-gene)

**Comment by ValWood** [comment]
Agreed we should delete.

Lookign at 
https://www.pombase.org/gene/SPBC1604.14c

It seems that you can put

does not functionally complement [ORGANISM] [GENE]



[does not functionally complement S. cerevisiae CLA4](https://www.pombase.org/term/PBO:0091259)

**Comment by ValWood** [comment]
Eventually we will do it in Canto. It never got to the top of the list...
https://github.com/pombase/canto/issues/1980
