### ISSUE TITLE
unnamed_alleles (location?)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3490]
https://curation.pombase.org/dumps/latest_build/logs/log.2023-04-05-21-42-28.chado_checks.unnamed_alleles

errors

Check for alleles with no name - CHECK FAILURE:  expected 0 but got 8
uniquename	description	allele_type	canto_session
  SPAC31G5.10:allele-2	1759-2859	partial_nucleotide_deletion	
  SPNCRNA.1303:allele-2	93-419	partial_nucleotide_deletion	
  SPNCRNA.1533:allele-1	760-966	partial_nucleotide_deletion	
  SPNCRNA.1624:allele-1	15-1422	partial_nucleotide_deletion	
  SPNCRNA.627:allele-1	606-995	partial_nucleotide_deletion	
  SPNCRNA.628:allele-1	732-1573	partial_nucleotide_deletion	
  SPNCRNA.808:allele-1	(-7)-150	partial_nucleotide_deletion	
  SPNCRNA.941:allele-1	145-922	partial_nucleotide_deletion	

but no session ID.
@kimrutherford 
@manulera  do you know the  annotation source?

**Comment by manulera** [comment]
They must be from Jurg's paper. Will check it out.

**Comment by manulera** [comment]
Fixed now in the repo and svn
