### ISSUE TITLE
New gene name for SPBC17A3.03c (siw14)

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3493]
In this paper: PMID:36882296, they refer to SPBC17A3.03c as siw14, because of orthology with S. cerevisiae SIW14, studied in this paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5936820/

Should we rename the gene to siw14? I see that other orthologues are shown in PomBase.

**Comment by ValWood** [comment]
Agreed, and done. I also kept only siw14 as ortholog as the others are clearly more divergent, 

https://www.flyrnai.org/cgi-bin/DRSC_orthologs.pl?input_species=4896&output_species=0&additional_filter=None&search_fields=***&search_datasets=***&gene_list=SPBC17A3.03c

and not recorded as being true paralogs of siw14 (this is usually detected from synteny in Whole genome duplication)

**Comment by manulera** [comment]
Thanks!
