### ISSUE TITLE
rhb1 & gtr1

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3494]
PR:000059629 GTP-bound form 
PR:000059628  GDP-bound form
PMID:16262791

Spom-gtr1/GDP+ PR:000050542
Spom-gtr1/GTP+ PR:000050543
Spom-gtr2/GDP+ PR:000050545
Spom-gtr2/GTP+ PR:000050546

**Comment by ValWood** [comment]
hi @nataled  to use the PR terms in PomBase, I need to add them to a mini ontology so that  we don't need to import all of PRO, and also so I can add a user friendly display label.

It seems I never added this batch of GTP-GDP bound forms of the GTPases (I think you added them as a block at some point). How easy is it to provide me with the obo stanzas for this set of terms ?

**Comment by nataled** [comment]
It's actually something you can do yourself! On each PRO term page there's a link to the stanza (and GPI). See screen shot attached. Will this work for you?

![PR_000050541](https://user-images.githubusercontent.com/13770634/233114869-5c05af34-99f4-4d0d-a5cd-4d050df2c9a1.jpg)

**Comment by ValWood** [comment]
perfect, thanks!
