### ISSUE TITLE
Load errors for allele type: nucleotide_deletion_and_mutation

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3496]
We're getting some load errors about `nucleotide_deletion_and_mutation`: 
https://curation.pombase.org/dumps/builds/pombase-build-2023-04-25/logs/log.2023-04-24-22-14-12.phenotypes_from_PMID_1315954_phaf

Should we add this as a valid allele type for Chado?  What about in Canto?

@manulera I think this allele type appeared when we applied the allele fixes in pombase/canto#2689

**Comment by manulera** [comment]
I will go ahead and make an equivalent PR to these two to include them

https://github.com/pombase/canto/pull/2693
https://github.com/pombase/canto/pull/2692/

**Comment by manulera** [comment]
And yes, this should be added to chado. Is there any other that does not exist?

**Comment by kimrutherford** [comment]
> And yes, this should be added to chado.

I'll do that.

> Is there any other that does not exist?

There is `nucleotide_insertion_and_mutation` from https://curation.pombase.org/dumps/builds/pombase-build-2023-04-25/logs/log.2023-04-24-22-14-12.phenotypes_from_PMID_1315954_phaf

And two that look like typos: https://curation.pombase.org/dumps/builds/pombase-build-2023-04-25/logs/log.2023-04-24-22-14-12.phenotypes_from_PMID_23697806_phaf
Maybe they need to be `partial_nucleotide_deletion`?

**Comment by manulera** [comment]
Yep, those are errors, was feeling very Greek in this moment, apparently (nucleotídeos_deletion). 📜📜

This is the PR:
https://github.com/pombase/canto/pull/2724

Also, we recently decided to treat all nonsense_mutation alleles as partial_amino_acid_deletion. We could use this PR to enforce that (remove nonsense mutation as an option). I don't know if that would mess up other users of Canto so maybe there is a way to keep it in the config and not display it for users in PomBase?

**Comment by kimrutherford** [comment]
> I don't know if that would mess up other users of Canto so maybe there is a way to keep it in the config and not display it for users in PomBase?

I think it's OK.  The main user is PHI-base but they have their own configuration file and a different list of allele types.
