### ISSUE TITLE
Possible pombe publication PMID:37192628?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3506]
From https://github.com/pombase/website/issues/2045#issuecomment-1582167392

> There is a structure for PMID:37192628 which PDB says is from pombe, but it's not in PomBase. I had a look and it mentions pombe twice in the paper: https://www.sciencedirect.com/science/article/abs/pii/S1097276523003167?via%3Dihub

**Comment by ValWood** [comment]
Ooh I have been waiting for this one. It's an unknown gene characterization. na,e was registered a couple of weeks ago.

**Comment by ValWood** [comment]
So it should be in the triage list no? but i don't see it....

**Comment by ValWood** [comment]
I added it manually & triaged.

**Comment by kimrutherford** [comment]
> So it should be in the triage list no? but i don't see it....

It doesn't have "pombe" or "fission yeast" in the abstract so maybe our nightly PubMed query didn't find it?

**Comment by ValWood** [comment]
OK, I thought though since the pub now came in via the pdb, it would then appear in the triage, because it hadn't been through it previously?

**Comment by kimrutherford** [comment]
No, sorry, the publications in Canto are just from PubMed.  I think maybe at some point I sent you a list of PMIDs for pombe structures where the PMID wasn't in Canto, but it was a one off query.

**Comment by ValWood** [comment]
I guess we will catch these via the pdb pipeline, as long as you let me know any which are missing, because I will need to send out CC sessions for some of them.

**Comment by ValWood** [comment]
I mailed pdb about that.

**Comment by ValWood** [comment]
PMID:37192628 is curated so closing
