### ISSUE TITLE
Dubious gene name in PMID:26891792

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3518]
Hi @ValWood

They have a table of pombe genes, in which they have this line:

![Screenshot 2023-06-21 at 14 20 35](https://github.com/pombase/curation/assets/22526102/aba8b856-ffda-4c25-92a5-72833ed56cc7)

The problem is that there are three genes that could match:

- cmc1: https://www.pombase.org/gene/SPBC21D10.07
- raf1 (has cmc1 as a synonym): https://www.pombase.org/gene/SPCC613.12c
- cmc2 (is the orthologue of CMC1 and CMC2): https://www.pombase.org/gene/SPCC4B3.20

Do you have an intuition for what they could mean, or should I write to the authors?

**Comment by ValWood** [comment]
I think it will be cmc1 (both cmc1 and cmc2 map to S. cerevisiae CMC1 and CMC2 - looks like duplication after divergence in both species ), so it should be logically  the primary name for cmc1.

**Comment by ValWood** [comment]
@kimrutherford 

Actually it would be clearer  to understand in these situations if we showed the S. cerevisiae orthologs in all cases. Currently  it seems we don't show the S. cerevisiae orthologs if  there is an exact match to a pombe gene. But this is a bit misleading if you are actually looking for the orthologs, and we do say that you can search on those. I have been confused by this behavior myself.

<img width="293" alt="Screenshot 2023-06-21 at 14 36 22" src="https://github.com/pombase/curation/assets/7359272/3c5d1079-0d2e-4821-b770-335752a98648">

**Comment by manulera** [comment]
I see, that's what happenned to me. I thought only cmc2 the orthologue. Thanks!

**Comment by kimrutherford** [comment]
> Currently it seems we don't show the S. cerevisiae orthologs if there is an exact match to a pombe gene.

Is this better?  I've changed it to show the ortholog if it matches a cerevisiae gene name:

![image](https://github.com/pombase/curation/assets/90474/32f54562-e39e-4d30-8140-26e5c971451a)

We could also show the human ortholog name if that matches:

![image](https://github.com/pombase/curation/assets/90474/30447362-c887-4e9a-b42c-2520dc5026d2)

**Comment by kimrutherford** [comment]
Sorry, wrong issue.
