### ISSUE TITLE
CTD nomenclature - multiple mutations in CTD

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3523]
Hi @ValWood. I am doing some manual editing of alleles and I realised there is a particular case where the CTD nomenclature we proposed might be a bit problematic for allele **descriptions**, not so much in names.

When several modifications are in the CTD, we just proposed to put them one after the other without a comma: `rpb1-CTD-S5A(r1-r12)Δ(r13-r29)`. This is problematic for multiple aminoacid mutations if all repeats are modified. For example, if both S2A and S7A are mutated in the first ten repeats, then we can name the allele `rpb1-CTD-S2A(r1-r10)S7A(r1-r10)`, a bit repeating, but `rpb1-CTD-S2A,S7A(r1-r10)` would not clarify whether the first S2A also applies to repetitions 1 to 10 only. However, if all S2A and S7A are modified, then the allele name should be called in theory `rpb1-CTD-S2AS7A`, but it comes more naturally to call it `rpb1-CTD-S2A,S7A`. It might be then better to use comma for all cases, e.g. `rpb1-CTD-S5A(r1-r12),Δ(r13-r29)`. Remember that is also possible to have modifications both in the protein and in the CTD (e.g. `rpb1-S432A-CTD-S5A(r1-r12),Δ(r13-r29)`)

I think using the comma in that intance makes sense, and we should include it in the revision of the paper. However, it's a bit annoying for descriptions, because normally we have used the comma as separator between independent variants (e.g.) `1-40,S43A,EEF156AAA`. However, in a case `rpb1-S432A-CTD-S2A,S7A`, the options I see are:

1. Ask for the description to be `S432A,CTD-S2A,CTD-S7A` (write CTD on each of the comma-separated bits)
1. Ask not to use the comma in the CTD, but this is inconsistent with the allele naming rules and is a bit weird `S432A,CTD-S2AS7A`
1. Impose the condition that after `CTD` appears in the description all modifications are treated as belonging to the CTD: description would be `S432A,CTD-S2A,S7A`, and could not be written as `CTD-S2A,S7A,S432A`.
1. Use parenthesis `S432A,CTD-(S2A,S7A)`. This is consistent with the usage of parenthesis we have proposed for allele names.

I think option 3 is probably the best option, what do you think?

**Comment by ValWood** [comment]
I think I agree that option 3 seems best. Easier to read.
