### ISSUE TITLE
Several wrong annotations to hcs1

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3524]
Hello @ValWood I am working through the list of alleles with sequence errors. I have encountered a bunch that I deleted because they actually referred to a protein from another organism. For example, in some structural papers they had used a cerevisiae protein and we had made some annotations in PomBase to the gene in pombe.

The list of such cases is here:

https://github.com/pombase/allele_qc/blob/master/change_log/removed_alleles_05072023.tsv

However, I have found a case where in a structural paper they studied homocitrate synthase, to which they refer in the paper as HCS throughout. We had annotations to hcs1 (3-hydroxy-3-methylglutaryl-CoA synthase), but from the seuqence it is clear that they use HCS to refer to lys4 (homocitrate synthase). I have ammended the phenotype and GO annotations in the session, but making a note here for the future.

![Screenshot 2023-07-05 at 13 02 52](https://github.com/pombase/curation/assets/22526102/c99713ea-1c2e-4b3a-9eed-a9b718c9d143)

**Comment by ValWood** [comment]
Good catches!
