### ISSUE TITLE
Two nonsense mutations that might need to be partial_amino_acid_deletion

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3530]
From https://github.com/pombase/website/issues/2053#issuecomment-1627701387

> > The nomenclature paper says that the * is a stop codon, which makes sense. But in that case why doesn't W316* have the type "amino_acid_mutation"? Is it because the protein gets truncated?
>
> Yes, this is a truncated protein. In the past we used to record them as "nonsense_mutation" but we decided to merge with partial aminoacid deletion, since at the product level there is no difference in principle.

Do these two need to change to partial_amino_acid_deletion?:

https://www.pombase.org/genotype/lcf1-W376-%3Estop-W367*-nonsense_mutation-expression-not_assayed_or_wild_type
https://www.pombase.org/genotype/elf1-21-Q863*-nonsense_mutation-expression-not_assayed_or_wild_type

**Comment by ValWood** [comment]
@manulera I guess this will be i the pipeline?

**Comment by manulera** [comment]
They are in the pending changes, but we currently do not have a way to introduce these periodically. I am asking kim every now and then to add certain badges, but I am preparing a big one with a bunch of allele fixes.

https://github.com/pombase/allele_qc/blob/master/results/allele_auto_fix.tsv
