### ISSUE TITLE
amino_acid_mutation starting with "nt"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3533]
I noticed that this amino acid mutation has "nt" in the description.  That seems like a mistake?
https://www.pombase.org/genotype/sev4-L5-ntG1844A-amino_acid_mutation

There are some others:

|Gene systematic ID  |Gene name    |Allele name       |Allele description                  |Reference      |
|--------------------|-------------|------------------|------------------------------------|---------------|
|SPAC22G7\.06c       |ura1         |ura1\-61          |ntG16857A                           |PMID:11864600  |
|SPAC22F3\.09c       |res2         |res2\-J3          |ntG16597A                           |PMID:11864600  ||
|SPAC2G11\.12        |rqh1         |rqh1\-h2          |ntC28520T                           |PMID:10497270  |
|SPAC22F3\.09c       |res2         |res2\-G1          |ntG16590A                           |PMID:11864600  |
|SPAC821\.11         |pro1         |pro1\-1           |ntG30304A                           |PMID:11864600  |
|SPAC2G11\.12        |rqh1         |rqh1\-h2          |ntC28520T                           |PMID:11864600  |

They aren't displayed in the protein feature viewer at the moment because the description can't be parsed.

**Comment by ValWood** [comment]
I'm a bit confused about how to fix this
https://www.pombase.org/reference/PMID:11864600

because they look OK in here
legacy_phenotype_annotations_from_contigs.phaf.tsv
@manulera do you know where I need to fix them?

**Comment by kimrutherford** [comment]
Hi Val.  Manu fixed these in SVN in August last year so this can be closed
