### ISSUE TITLE
Support for GO annotations from PMID:35924983

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3534]
Hi @ValWood,

In PMID:35924983 they do SGA to study genetic interactions of transcription factors. In CC, they made the following GO annotations:

![Screenshot 2023-07-26 at 17 32 10](https://github.com/pombase/curation/assets/22526102/f192cbf4-213f-4077-9413-cb34a5d538b7)

* scr1 is a transcription factor
* ubr1 and mub1 are ubiquitin-ligases
* sds23 kinase that phosphorylates scr1 preventing nuclear translocation (PMID:25411338)
* amk2 is a kinase

The key experiments are in figures 6 and 7

* scr1 deletion promotes flocculation in a medium where flocculation does not normally happen.
* scr1 OE prevents flocculation in a medium where flocculation normally happens.
* deletion od sds23 prevents flocculation, but double mutant sds23D scr1D flocculates always (scr1D is downstream)
* deletion of ubr1, mub1, amk2 prevent flocculation.
* deletion of ubr1 or mub1 increase levels of scr1 both at high and low glucose (supports ubr1 and mub1 ubiquitinating scr1)
* deletion of sds23 and amk2 make scr1 accumulate at high levels in the nucleus (supports sds23 and amk2 inactivating scr1 via phosphorylation)

If we had more molecular detail, we could for sure move the kinases and ubiquitinases to molecular functions that happen during positive regulation of flocculation and that have scr1 as a target, but not sure if this is enough for an IMP annotation (only evidence of scr1 being their direct substrate is sds23 from PMID:25411338).

Also, in terms of GO cellular component, how do you record the fact that a TF is in the nucleus at high glucose, and in the cytoplasm at low glucose? This is how I did it for low glucose, but not sure how to do it the other way:

![Screenshot 2023-07-26 at 17 49 56](https://github.com/pombase/curation/assets/22526102/3ce4099f-1bfb-4b5b-b115-58f1d8571aac)

**Comment by ValWood** [comment]
I think it is OK to make these  GO annotations. These are clearly regulating, and the annotations don't  specify these act on  scr1 directly. When the regulation annotations are reviewed these may end up moving to "causally upstream" but for now this is fine.

For the  high glucose you can use:
GO:0071333   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0071333/complete)
cellular response to glucose stimulus
