### ISSUE TITLE
Homogenize PHAF files

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3539]
We should:

* [x] Have all headers be the same 
    ```
    cat trunk/external_data/phaf_files/chado_load/*/*.tsv|grep -v FYPO:|grep -v "#"|grep -v "SP"|sort|uniq
    ```
* [x] Control the values in allele type column

**Comment by kimrutherford** [comment]
> Have all headers be the same 

That's done now.

**Comment by kimrutherford** [comment]
> Control the values in allele type column

All the files now have standard allele name with underscores not spaces.

I have also fixed the values in the Date column to always look like "2023-11-17"

**Comment by ValWood** [comment]
was this many? and what type are they?
I wonder if I should be checking as I do these?

https://curation.pombase.org/dumps/latest_build/logs/log.2023-11-16-21-22-48.chado_checks.allele_with_space_in_name


I.e those with promoter in the name will need a slightly different solution

**Comment by kimrutherford** [comment]
> > All the files now have standard allele name with underscores not spaces.
> was this many? and what type are they?

Sorry!  That was a typo.  I meant to say: "standard allele _types_"

**Comment by ValWood** [comment]
ok!
