### ISSUE TITLE
check relation on target_of annotation for cdc2

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#354]
A couple of target_Ofs have the relation "binds"

these are
ribonucleotide reductase inhibitor
and
cyclin dependent protein kinase regulatory subunit

It seems that these would be better as
regulated_by
(or even inhibited_by)

What is it about the original annotations which makes them be classed as "binds" and could they get a more "directional" relationship?

Original comment by: ValWood

**Comment by ValWood** [comment]
transferred to cdc2 ticket
https://github.com/pombase/curation/issues/963
