### ISSUE TITLE
Missing description for rgf1-PTTRΔ

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3540]
The description is missing from this allele:
https://curation.pombase.org/pombe/curs/7b30a1cc7d87ace2/feature/genotype/view/18/ro

Canto showing "partial deletion, amino acid" instead of the description which doesn't seem like a good idea.

The allele is merging with an allele with the same name from this session which has a description so it's OK on the website:
https://curation.pombase.org/pombe/curs/0fd9142a80a1f4c8/feature/genotype/view/35/ro

**Comment by ValWood** [comment]
I think this is fixed?
