### ISSUE TITLE
Two alleles in Canto without names

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3541]
From https://github.com/pombase/canto/issues/2755#issuecomment-1680281740

-----------------------------------------------------

There are now only two alleles in Canto without names and both have no annotations:

```
396866ab84f69995 cnd2(SPCC306.03c)     description: T117I
865ebc50ec806a07 sgf11(SPAC57A10.14)   description: Q64->stop
```

**Comment by kimrutherford** [comment]
Sorry, found two more in:
https://desktop.kmr.nz/test/curs/bcb8d4f171dffc70/genotype_manage/ro

These two do have annotations: Q62A,L63A and F158S,S159G

**Comment by ValWood** [comment]
fixed
