### ISSUE TITLE
Alleles with the same description and gene, but a different name

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3542]
While looking into pombase/canto#2757 and pombase/canto#1284 I noticed some alleles that are the same except for the name.  I don't know if that's a big problem but there do seem to be some that look like mistakes, like "asp1(1-385)" vs "asp1-(1-385)".

Here's the list:

[duplicate_allele_descriptions.tsv.txt](https://github.com/pombase/curation/files/12460802/duplicate_allele_descriptions.tsv.txt)

|gene           |allele\_description |allele\_type        |allele\_name        |sessions                                                                                                                                                  |
|---------------|--------------------|--------------------|--------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
- [x] (deleted, unused) |SPBC3D6\.04c   |specify             |partial\_nucleotide\_deletion|mad1\-66bpdelta\-GFP|e26981c223efb4e4                                                                                                                                          |
- [x] (deleted, unused) |SPBC3D6\.04c   |specify             |partial\_nucleotide\_deletion|mad1\-108bpdelta\-GFP|e26981c223efb4e4                                                                                                                                          |
- [x]  |SPCC1672\.06c  |386\-920            |partial\_amino\_acid\_deletion|asp1\(1\-385\)      |4228fd893e7a1a88,a6782fab5fd233d0                                                                                                                         |
- [x]  |SPCC1672\.06c  |386\-920            |partial\_amino\_acid\_deletion|asp1\-\(1\-385\)    |06a0bcdb548ec92c                                                                                                                                          |
- [x] |SPBC14C8\.07c  |T10A,T46A,T60A,T104A,T134A,T374A|amino\_acid\_mutation|cdc18\-T6A          |7e83e3410ced8531,5ef3337d730491a3,5ef3337d730491a3,8ca59104c61e0b02,8ca59104c61e0b02                                                                      |
- [x] |SPBC14C8\.07c  |T10A,T46A,T60A,T104A,T134A,T374A|amino\_acid\_mutation|cdc18\-T6A\-TAP     |8ca59104c61e0b02                                                                                                                                          |
- [x] |SPAC3A12\.14   |E33V                |amino\_acid\_mutation|cam1\-EF1           |170b4d4db77791d1                                                                                                                                          |
- [x] |SPAC3A12\.14   |E33V                |amino\_acid\_mutation|cam1\-E234          |8e9ae50d97ec7769                                                                                                                                          |
- [x]  |SPCC16A11\.17  |828\-911            |partial\_amino\_acid\_deletion|mcm4\-c84           |de1e1946e680a0bb                                                                                                                                          |
- [x]  |SPCC16A11\.17  |828\-911            |partial\_amino\_acid\_deletion|mcm4delta828\-911   |41faea428ef0af7e                                                                                                                                          |
- [x]  |SPAC3A12\.14   |E69V                |amino\_acid\_mutation|cam1\-E134          |8e9ae50d97ec7769                                                                                                                                          |
- [x]  |SPAC3A12\.14   |E69V                |amino\_acid\_mutation|cam1\-EF2           |170b4d4db77791d1                                                                                                                                          |
- [ ] |SPAC343\.11c   |later               |other               |msc1\-PHD3\-C7\>A   |b9792083a95e2fee                                                                                                                                          |
- [ ] |SPAC343\.11c   |later               |other               |msc1\-PHD2\-C7\>A   |b9792083a95e2fee                                                                                                                                          |
- [ ] |SPAC343\.11c   |later               |other               |msc1\-PHD1\-C7\>A   |b9792083a95e2fee                                                                                                                                          |
- [x]  |SPBC8D2\.04    |S87A                |amino\_acid\_mutation|hht2\-S87A          |8acbb19b9968971d                                                                                                                                          |
- [x]  |SPBC8D2\.04    |S87A                |amino\_acid\_mutation|S86A                |8acbb19b9968971d                                                                                                                                          |
- [x] |SPAC1565\.08   |G332D               |amino\_acid\_mutation|cdc48\-G332D        |865ebc50ec806a07                                                                                                                                          |
- [x] |SPAC1565\.08   |G332D               |amino\_acid\_mutation|cdc48\-353          |28c85bd1757a57ff,28c85bd1757a57ff,16d769aa2fc305a4,1d9460b2fe58c1c2,6fa5a621a1388c10,205df3a82b504d79                                                     |
- [x] |SPBC342\.05    |crb2\(1\-358\)\-LZ  |fusion\_or\_chimera |crb2\(1\-358\)\-LZ  |fb81220ce61d5104                                                                                                                                          |
- [x] |SPBC342\.05    |crb2\(1\-358\)\-LZ  |fusion\_or\_chimera |crb2\-\(1\-520\)LZ  |288cc0705ff9b896                                                                                                                                          |
- [x]  |SPAP8A3\.06    |T45D,L47D           |amino\_acid\_mutation|uaf2\-T45D,L47D     |72862a5b1395f450                                                                                                                                          |
- [x]  |SPAP8A3\.06    |T45D,L47D           |amino\_acid\_mutation|uaf2\-T45DL47D      |                                                                                                                                                          |
- [x] |SPBC17F3\.02   |GFP\-nak1\-K39R\-orb6|fusion\_or\_chimera |nak1\-orb6          |f4425b94136060a0                                                                                                                                          |
- [x]  |SPBC17F3\.02   |GFP\-nak1\-K39R\-orb6|fusion\_or\_chimera |nak1\*\-orb6        |f4425b94136060a0                                                                                                                                          |
- [x] |SPBC660\.13c   |D223Y               |amino\_acid\_mutation|rad11\-D223Y        |29ac2c8c97f2cc6c,ff16cae20b63db89,be9521cb5c4791ae,e4b31ea722f9e274,4b35693cfa0373c0                                                                      |
- [x] |SPBC660\.13c   |D223Y               |amino\_acid\_mutation|ssb1\-D223Y         |7ad9eb5a73f1bab1                                                                                                                                          |
- [x] |SPBC30D10\.09c |21\-60              |partial\_amino\_acid\_deletion|hva22\-deltaN29     |2d8412a36a34689a                                                                                                                                          |
- [x] |SPBC30D10\.09c |21\-60              |partial\_amino\_acid\_deletion|hva22\-deltaC21–60  |2d8412a36a34689a                                                                                                                                          |
- [ ]  |SPBC28F2\.12   |CTD\-delta\(r17\-r29\)|partial\_amino\_acid\_deletion|rpb1\-CTD\-delta\(r19\-r29\)|ab5171b90f5cef1d                                                                                                                                          |
- [ ] |SPBC28F2\.12   |CTD\-delta\(r17\-r29\)|partial\_amino\_acid\_deletion|rpb1\-CTD\-delta\(r17\-r29\)|ab5171b90f5cef1d                                                                                                                                          |
- [x]  |SPAC3A12\.14   |E142V               |amino\_acid\_mutation|cam1\-E123          |8e9ae50d97ec7769                                                                                                                                          |
- [x]  |SPAC3A12\.14   |E142V               |amino\_acid\_mutation|cam1\-EF4           |170b4d4db77791d1                                                                                                                                          |
- [x] |SPBC14C8\.01c  |R262\*              |partial\_amino\_acid\_deletion|cut2\-364           |a285637adcbb8409,c641c32144a9fceb,ec89f0bd010d8a38,ec89f0bd010d8a38,e01b2f3ba979a8d0,468fa2c5da611313,25aefd25e9ecb150,809618c56c11583b,774b7f1a9f489629  |
- [x] |SPBC14C8\.01c  |R262\*              |partial\_amino\_acid\_deletion|cut2\-R262\*        |16ad711046a3f839                                                                                                                                          |
- [ ] |SPCC16A11\.17  |Ub\-DHFRts\-mcm4    |fusion\_or\_chimera |mcm4td              |7097a362b55929af,bcb5a5b99a75c27a                                                                                                                         |
- [ ] |SPCC16A11\.17  |Ub\-DHFRts\-mcm4    |fusion\_or\_chimera |mcm4\-tstd          |56ce08f89dc9d46c,7097a362b55929af,20a419e583ad61e6,37237b530ab38bc9                                                                                       |
- [x] |SPAC23C11\.16  |D625A,H626A,K628A   |amino\_acid\_mutation|plo1\-DHK625AAA     |                                                                                                                                                          |
- [x] |SPAC23C11\.16  |D625A,H626A,K628A   |amino\_acid\_mutation|plo1\-D625A,H626A,K628A|b74f9d9ca791af8a                                                                                                                                          |
- [x]  |SPAC890\.02c   |K341A,Y344A,R346A,K347A,Y348A|amino\_acid\_mutation|alp7\-5A            |17cceecf86230427                                                                                                                                          |
- [x]  |SPAC890\.02c   |K341A,Y344A,R346A,K347A,Y348A|amino\_acid\_mutation|alp7\-SPB           |17cceecf86230427,13f535eec84725d1                                                                                                                         |
- [x] |SPAC3A12\.14   |E106V               |amino\_acid\_mutation|cam1\-E124          |8e9ae50d97ec7769                                                                                                                                          |
- [x] |SPAC3A12\.14   |E106V               |amino\_acid\_mutation|cam1\-EF3           |170b4d4db77791d1                                                                                                                                          |
- [x]  |SPAC57A10\.02  |S755A,S758A         |amino\_acid\_mutation|cdr2\-S755A\-S758A  |bbe966c7c31d9042                                                                                                                                          |
- [x]  |SPAC57A10\.02  |S755A,S758A         |amino\_acid\_mutation|cdr2\-S755A\-758A   |bbe966c7c31d9042                                                                                                                                          |
- [ ] |SPNCRNA\.98    |A162C               |nucleotide\_mutation|srp7\-A162          |                                                                                                                                                          |
- [ ] |SPNCRNA\.98    |A162C               |nucleotide\_mutation|srp7\-A162C         |                                                                                                                                                          |
- [x]  |SPBC660\.13c   |G78E                |amino\_acid\_mutation|ssb1\-G78E          |7ad9eb5a73f1bab1                                                                                                                                          |
- [x]  |SPBC660\.13c   |G78E                |amino\_acid\_mutation|ssb1\-418           |aedeeafb353d00c4,94ca468a0f015cd5                                                                                                                         |
- [ ] |SPCC24B10\.14c |T180A,S192A         |amino\_acid\_mutation|nmt1\-xlf1\.AA      |c23b5043b024b0a5                                                                                                                                          |
- [ ] |SPCC24B10\.14c |T180A,S192A         |amino\_acid\_mutation|nmt41\-xlf1\.AA     |c23b5043b024b0a5                                                                                                                                          |
- [ ] |SPCC24B10\.14c |T180A,S192A         |amino\_acid\_mutation|xlf1\.AA            |c23b5043b024b0a5,c23b5043b024b0a5                                                                                                                         |
- [x] |SPAC1565\.08   |E319K               |amino\_acid\_mutation|cdc48\-8            |bea1c1e13005750d                                                                                                                                          |
- [x] |SPAC1565\.08   |E319K               |amino\_acid\_mutation|cdc48\-E319K        |dc907bc500c1a07a                                                                                                                                          |
- [x] |SPBC6B1\.09c   |G103D               |amino\_acid\_mutation|nbs1\-s10           |7622b54e59b561d0,e36b99ed5d28ee19,94b54d8b1a931fb9                                                                                                        |
- [x] |SPBC6B1\.09c   |G103D               |amino\_acid\_mutation|nbs1\-G103D         |e36b99ed5d28ee19                                                                                                                                          |

**Comment by ValWood** [comment]
They should all be in this log:
https://curation.pombase.org/dumps/latest_build/logs/log.2023-08-28-21-42-39.chado_checks.duplicate_allele_descriptions

I think the description fixes have increased this file, it has grown quite a lot, I was down to around 10 lines.
I will work through the obvious ones today...

**Comment by ValWood** [comment]
only a few in the logs now...
