### ISSUE TITLE
Alleles that look like gene names

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3546]
While working on pombase/canto#2776 I noticed some allele names that look like gene names.  I don't know if this is a problem, but here they are:

| gene | genotype |
| --- | --- |
| [ptp4](https://www.pombase.org/gene/SPBC3D6.05) | https://www.pombase.org/genotype/ptp4-unknown-unknown-expression-not_assayed_or_wild_type |
| [thi2](https://www.pombase.org/gene/SPBC26H8.01) | https://www.pombase.org/genotype/nmt2-unknown-unknown-expression-not_assayed_or_wild_type |
| [thi9](https://www.pombase.org/gene/SPAC9.10) | https://www.pombase.org/genotype/ptr1-E81K-amino_acid_mutation-expression-not_assayed_or_wild_type |
| [klp2](https://www.pombase.org/gene/SPAC664.10) | https://www.pombase.org/genotype/klp2-wild_type-wild_type-expression-overexpression |
| [tip1](https://www.pombase.org/gene/SPAC3C7.12) | https://www.pombase.org/genotype/tip1-wild_type-wild_type-expression-overexpression |
| [rad24](https://www.pombase.org/gene/SPAC8E11.02c) |  https://www.pombase.org/genotype/sam4-Q70*-partial_amino_acid_deletion |
| [nda3](https://www.pombase.org/gene/SPBC26H8.07c) | https://www.pombase.org/genotype/ben1-unknown-unknown-expression-not_assayed_or_wild_type |
| [pik3](https://www.pombase.org/gene/SPAC458.05) | https://www.pombase.org/genotype/pik3-disruption-disruption-expression-not_assayed_or_wild_type |
| [cdc4](https://www.pombase.org/gene/SPAP8A3.08) | https://www.pombase.org/genotype/cdc4-unknown-unknown-expression-not_assayed_or_wild_type |
| [rad52](https://www.pombase.org/gene/SPAC30D11.10) | https://www.pombase.org/genotype/rad22-unknown-unknown-expression-not_assayed_or_wild_type |
| [dld1](https://www.pombase.org/gene/SPAC1002.09c) | https://www.pombase.org/genotype/cyj150-T40C-nucleotide_mutation-expression-not_assayed_or_wild_type |

**Comment by ValWood** [comment]
The rule is to append these with a -

<img width="696" alt="Screenshot 2023-09-07 at 10 21 25" src="https://github.com/pombase/curation/assets/7359272/df7fdf6c-b54d-4c07-90b1-60d05200b10b">

isn't it great having rules!
;)

**Comment by ValWood** [comment]
I can edit these if I have the sessions, or is it better to fix but the pipeline?

**Comment by kimrutherford** [comment]
> I can edit these if I have the sessions, or is it better to fix but the pipeline?

I think editing the sessions makes sense since there aren't too many, if that's OK.  I'll do a query for the sessions IDs.

**Comment by kimrutherford** [comment]
|allele\_uniquename     |allele\_name |allele\_type                 |description  |sessions                           |
|-----------------------|-------------|-----------------------------|-------------|-----------------------------------|
|SPBC26H8\.01:allele\-3 |nmt2         |unknown                      |unknown      |c6573f77d7263495                   |
|SPBC26H8\.07c:allele\-6|ben1         |unknown                      |unknown      |652ccd500039fcac,5c1c72c4c8850e21  |
|SPAC8E11\.02c:allele\-9|sam4         |partial\_amino\_acid\_deletion|Q70\*        |0606c7fce02ac897                   |
|SPAC458\.05:allele\-2  |pik3         |disruption                   |             |67a45bb75e85f945                   |
|SPAC9\.10:allele\-2    |ptr1         |amino\_acid\_mutation        |E81K         |7af453947f7b7e9d                   |
|SPAP8A3\.08:allele\-21 |cdc4         |unknown                      |unknown      |482d360415391124                   |
|SPAC664\.10:allele\-6  |klp2         |wild\_type                   |             |8f6a751681cb343e                   |
|SPBC3D6\.05:allele\-3  |ptp4         |unknown                      |unknown      |6f2bb502b0b09c2b                   |
|SPAC3C7\.12:allele\-4  |tip1         |wild\_type                   |             |8fb498d6aad39666                   |
|SPAC30D11\.10:allele\-4|rad22        |unknown                      |unknown      |04fb586f59d968bf                   |
|SPAC1002\.09c:allele\-2|cyj150       |nucleotide\_mutation         |T40C         |12bdf99ec7ed84ce                   |

**Comment by ValWood** [comment]
These are all fixed.
v
