### ISSUE TITLE
Typo neh1 vs nhe1

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3547]
https://curation.pombase.org/pombe/curs/5fabf4733ea9413f/genotype_manage/ro

![image](https://github.com/pombase/curation/assets/90474/325b7af2-8881-4af4-98cf-12f892516393)

**Comment by ValWood** [comment]
Agreed, shouldn't it have appeared in
https://curation.pombase.org/dumps/latest_build/logs/log.2023-09-07-21-41-59.chado_checks.AlleleNotStartingWithGeneName
?

**Comment by ValWood** [comment]
fixed

**Comment by kimrutherford** [comment]
> shouldn't it have appeared in
> https://curation.pombase.org/dumps/latest_build/logs/log.2023-09-07-21-41-59.chado_checks.AlleleNotStartingWithGeneName

It doesn't appear in the log because it's OK in Chado.  When the deletions are exported from Canto, the allele name is fixed to <gene_name>delta because of this issue:
  - https://github.com/pombase/pombase-chado/issues/992#issuecomment-1179664520

**Comment by kimrutherford** [comment]
Sorry Val, I didn't notice before but there are others that need fixing:
  - https://curation.pombase.org/pombe/curs/eb4340d44f575950/feature/genotype/view/4/ro
  - https://curation.pombase.org/pombe/curs/ecbfda73cbbd469b/feature/genotype/view/5/ro
  - https://curation.pombase.org/pombe/curs/f1d8eeb553561925/feature/genotype/view/3/ro

I promise that all of them for nhe1!

**Comment by ValWood** [comment]
fixed!
