### ISSUE TITLE
Possible typo gls1 vs ghs1 

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3548]
I think this should be "ghs1Δ"?

https://curation.pombase.org/pombe/curs/661292025a8cdee8/genotype_manage/ro

![image](https://github.com/pombase/curation/assets/90474/8d28aa79-dd7c-4b22-aedb-621952975d83)

**Comment by ValWood** [comment]
The allele is correct, it seems the gene name is wrong:

Glucosidase I (GI) removes the outermost glucose from protein-linked Glc3Man9GlcNAc2 (G3M9) in the endoplasmic reticulum (ER). Individuals with congenital disorders of glycosylation MOGS-CDG bear mutations in the GI-encoding gene (gls1). Although GI absence has been reported to produce lethality in Schizosaccharomyces pombe yeasts, here we obtained two viable Δgls1 mutants, one with a very sick but not lethal phenotype (Δgls1-S) and the other with a healthier one (Δgls1-H).

There was something about this name recently but I can't fully remember, will dig around bet most likely I'll make
gls1 primary and ghs1 synonym

**Comment by ValWood** [comment]
I can't find the reason for this, it isn't in my mailbox or any tracker. There is a possibility there was something about it in the helpdesk, but I will 
make gls1 primary and ghs1 synonym

**Comment by ValWood** [comment]
A mystery.... fixed

**Comment by ValWood** [comment]
shouldn't that have appeared in this file too?
https://curation.pombase.org/dumps/latest_build/logs/log.2023-09-07-21-41-59.chado_checks.AlleleNotStartingWithGeneName

**Comment by kimrutherford** [comment]
It's OK in Chado so there's no warning: https://www.pombase.org/genotype/ghs1delta
