### ISSUE TITLE
Odd deletion name "spr1Δ" for SPBC19G7.04?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3549]
This looks weird to me because SPBC19G7.04 isn't named and I can't see a gene called "spr1".

https://curation.pombase.org/pombe/curs/006084139334e409/genotype_manage/ro

![image](https://github.com/pombase/curation/assets/90474/b846a04f-fd04-4461-bcb2-f3f99e355d17)

**Comment by ValWood** [comment]
Im a bit baffled by this one.
https://www.pombase.org/gene/SPBC19G7.04
I'll just change it to SPBC19G7.04 delta. There is no mention of spr1 in the paper or supp.
It is possible the name was added by mistake, and was presnet at the point this publication was annotated, but was removed. I wondered if it used to be named for an S. cerevisiae ortholog, and the orthology call was later removed, but  the SGD gene called SPR1 is not related.

**Comment by ValWood** [comment]
fixed
