### ISSUE TITLE
Three deletions with names to fix

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3557]
Hi Val.

I'm still working on:
  - pombase/canto#2776
 
My script reports cases where allele details in Chado don't match what's in Canto and there's no obvious fix.  There are lots of cases that are easy to fix, for example the description is missing in Canto.

There are 31 warnings from the script.  All the cases where there is a description mismatch are already reported in the [Canto JSON load log file](https://curation.pombase.org/dumps/builds/pombase-build-2023-09-11/logs/log.2023-09-10-21-41-16.curation-tool-data-load-output). 

There are 3 warnings about allele names (see below).  The first one seems like an easy fix but I wasn't sure about the other two.  Could you take a look?  Thanks.

```
0370b9834de2dfe6: allele name in Chado differs from Canto, "pap1delta" vs "pap1-delta" (for deletion SPAC1783.07c:0370b9834de2dfe6-4 / SPAC1783.07c:allele-1)
66b209326b30f74b: allele name in Chado differs from Canto, "mat1-Mcdelta" vs "mat1-mc-delta" (for deletion SPBC23G7.09:66b209326b30f74b-1 / SPBC23G7.09:allele-1)
68637de9f01b5872: allele name in Chado differs from Canto, "ssm4delta" vs "ssm4-prom::ura4" (for deletion SPAC27D7.13c:68637de9f01b5872-1 / SPAC27D7.13c:allele-1)
```

**Comment by ValWood** [comment]
This log file is on my todo list. How soon do you want it?  I probably won't get to it today, but I'd hoped to plod through by the end of the week. If it's holding you up I will put it to the top of my list and do it tomorrow.

**Comment by ValWood** [comment]
It's the same as this log right?

https://curation.pombase.org/dumps/builds/pombase-build-2023-09-11/logs/log.2023-09-10-21-41-16.curation-tool-data-load-output

or at least most of the errors are in this log?

I'm confused by the 31 vs the 3 you have selected here. I'm fixing the 3 now, they are all straightforward (but each has a slightly different fix)

**Comment by ValWood** [comment]
I see its allles vs descriptions.
The 3 are fixed.
I'll work through the others.

Will I get them all using ?

https://curation.pombase.org/dumps/builds/pombase-build-2023-09-11/logs/log.2023-09-10-21-41-16.curation-tool-data-load-output

**Comment by ValWood** [comment]
I'm confused by this one:

warning in 774b7f1a9f489629: description for new allele "cdc18-46(E521A,D524A)" does not match the existing allele with the same name "cdc18-46(E521A,Q334A)"

The error appears to be in
https://www.pombase.org/reference/PMID:11030343

but in the session it is correctly 
https://curation.pombase.org/pombe/curs/6e9c92a7382e9127/
cdc18-46(E521A,D524A)
?

**Comment by kimrutherford** [comment]
> This log file is on my todo list. How soon do you want it?

There's no rush.

> Will I get them all using ?
> https://curation.pombase.org/dumps/builds/pombase-build-2023-09-11/logs/log.2023-09-10-21-41-16.curation-tool-data-load-output

All of the mismatched descriptions will appear in that Canto load log file.   The three name mismatches aren't logged because deletions are handled differently.
