### ISSUE TITLE
Allele rec8-17A without description

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3560]
Following on from:
  -  pombase/curation#3561

There is now only one allele in the exported PHAF file that has no description, rec8-17A in:
https://curation.pombase.org/pombe/curs/536dc2e074eee139/genotype_manage/ro

It's also the only allele in Chado without a description.

![image](https://github.com/pombase/curation/assets/90474/11604a56-7030-4ab0-98fb-edc285e7dcd2)

The description in Canto is the text "unknown".  The Chado loading code treats "unknown" as a special case and doesn't store a description for the allele.  If the description in Chado and in the PHAF file really should be "unknown", I'll change the loading code and remove the special case.

We should also fix the Canto display code in that case because showing "aaunknown" isn't great.

**Comment by ValWood** [comment]
done
