### ISSUE TITLE
IPI annotations without a "with" review polymerase Alpha annotation

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3565]
Hi @ValWood

Does it make sense for an IPI annotation to not have a "with" field?  We have 45 IPI annotations from ComplexPortal and none have a "with".

Here's an example from pombase/website#2092:

![image](https://github.com/pombase/website/assets/90474/67b5623e-4f0a-497f-8869-f012a77251f1)

**Comment by ValWood** [comment]
No, see
https://github.com/pombase/website/issues/2092
Please filter if we have an IDA (or IPI).
If there are any left I will annotate them.

**Comment by kimrutherford** [comment]
I've changed the filtering code.  39 of the 45 ComplexPortal annotations without a "with" will be filtered after Wednesday night's load.

An example on one that isn't filtered is the "alpha DNA polymerase:primase complex" annotation here:
https://www.pombase.org/gene/SPCC553.09c

Here's the full list:

|DB object ID  |DB Object Symbol  |GO ID       |DB:Reference    |
|--------------|------------------|------------|----------------|
|SPAC6B12.10c |spp1              |GO:0005658  |PMID:14766746   |
|SPBC17D11.06 |spp2              |GO:0005658  |PMID:14766746   |
|SPBC660.07   |ntp1              |GO:0005946  |PMID:12153582   |
|SPBP4H10.04  |ppb1              |GO:0005955  |PMID:15657058   |
|SPCC553.09c  |spb70             |GO:0005658  |PMID:14766746   |
|SPCC830.06   |cnb1              |GO:0005955  |PMID:15657058   |

**Comment by ValWood** [comment]
Its odd that this annotation wasn't made from this paper
https://www.pombase.org/reference/PMID:14766746

I'll transfer to the curation tracker to review

**Comment by ValWood** [comment]
It is on the curation tracker!

**Comment by kimrutherford** [comment]
> We can filter all.

So remove all ComplexPortal annotations?

**Comment by ValWood** [comment]
filter those with no "with" field. If they make a none IPI annotation that can come through.
(I think we will already be covered and so they will be filtered, I think we have annotated most papers that define complexes)

**Comment by kimrutherford** [comment]
All IPI annotation without a "with" are already filtered so I think this is done?
