### ISSUE TITLE
Two alleles with conflicting types

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3566]
I noticed these while (still) working on pombase/canto#2776.

I think there are only two alleles in Canto like this.

These are also in the log: https://curation.pombase.org/dumps/builds/pombase-build-2023-09-18/logs/log.2023-09-17-21-41-34.curation-tool-data-load-output

--------------------------------------------------

name: spt5-CTD-T1A(7)
description: 801-990,S800SGSKAPAWNSGSGSKAPAWNSGSGSKAPAWNSGSGSKAPAWNSGSGSKAPAWNSGSGSKAPAWNSGSGSKAPAWNSGS

has type "amino acid insertion and substitution" in 6186ba197a53e798
but has type "amino acid insertion and deletion" in 8481a1a5bf90b23e and 8a66efe1aac64683

-------------------------------------------------

name: rpb1-CTD-P3A(r2-r29-2)
description: CTD-P3A(r2-r29-2)

"amino acid substitution(s)" in ff1e67fe7824549f
but has "type amino acid insertion and substitution" in 66d1d84a63cd8a3e and 67f8ea3e5c1c1bfc

**Comment by ValWood** [comment]
fixed
