### ISSUE TITLE
Missing synonym in new FYECO term

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3586]
Hi Val.  The synonym value is missing from your new term FYECO:0000436/"+ 5IAA":

```
synonym: "" EXACT [PMID:37783794]  
```

Unfortunately that caused the nighly load to fail.  The OBO parser isn't good at coping with errors.

**Comment by ValWood** [comment]
done, sorry about that!

**Comment by kimrutherford** [comment]
Thanks.  I checked the OBO file syntax and it's all good for tonight's load.

**Comment by kimrutherford** [comment]
The update worked last night.
