### ISSUE TITLE
Obsolete term in extension in qualitative gene expression file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3595]
When loading these files:

```
external_data/qualitative_gene_expression_data/PMID_33313903_RNAseq_qualitative_expression.txt
external_data/qualitative_gene_expression_data/PMID_33313903_Riboseq_qualitative_expression.txt
```

we're getting a lot of "can't find term with ID: GO:2001020" warnings because GO:2001020 is used in extensions but is obsolete.  There are 155 warnings in total.  The extension is: `during(GO:2001020)`

GO:2001020 is (/was) "regulation of response to DNA damage stimulus".

The OBO file says it has been replaced by GO:0006974 "DNA damage response".

Should I change GO:2001020 to GO:0006974 in those files?

**Comment by ValWood** [comment]
Please!

**Comment by kimrutherford** [comment]
OK, done for tomorrow.
