### ISSUE TITLE
"Putative glutathione S-transferase C460.02c" at InterPro

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3596]
From: https://www.ebi.ac.uk/interpro/protein/reviewed/B5BP46/

Most pombe IDs seem to have the "SP" at the start missing:
https://www.ebi.ac.uk/interpro/taxonomy/uniprot/284812/protein/UniProt/?page_size=50#table

Do you know if they've always done that?

**Comment by ValWood** [comment]
Yes, I have complained about it before

**Comment by ValWood** [comment]
..To Uniprot, which is where the descriptions come from...
