### ISSUE TITLE
SPBC25D12.05/trm1 3'UTR missing transcript ID

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3597]
Hi Val.

`chromosome2.contig`

I think this needs to be `/systematic_id="SPBC25D12.05.1"` or `/systematic_id="SPBC25D12.05.2"`:

```
  FT   3'UTR           3725030..3725138
  FT                   /systematic_id="SPBC25D12.05"
  FT                   /db_xref="PMID:21511999"
```

**Comment by ValWood** [comment]
added both
/systematic_id="SPBC25D12.05.1"
/systematic_id="SPBC25D12.05.2"

**Comment by kimrutherford** [comment]
Hi Val.

That will need to be split into two features because a feature can only have one `/systematic_id`

**Comment by ValWood** [comment]
ok fixed

**Comment by kimrutherford** [comment]
Thanks!
