### ISSUE TITLE
Fix alleles that do not match sequence

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3620]
OK I will take this over to the curation tracker and we will work through them
https://github.com/pombase/allele_qc/blob/master/manual_fixes_pombase/cannot_find.tsv

_Originally posted by @ValWood in https://github.com/pombase/website/issues/2085#issuecomment-1831781814_

**Comment by ValWood** [comment]
@manulera I think I probably fixed most of these, unless I am confusing it with another list. Is this list up to date?

**Comment by manulera** [comment]
This is not automatically updated, it was just to take notes. You can remove the file from the repo if they have been fixed

**Comment by ValWood** [comment]
I guess they would all be reported in the logs if they are still a problem....
@kimrutherford
