### ISSUE TITLE
Tidy syntax in new PHAF file fields

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3627]
From: https://github.com/pombase/website/issues/2029#issuecomment-1812160802

Should we remove all spaces?  Maybe "(2.5% v/v)" needs a space though?

--------------------------------

I wonder if we could tidy the syntax of these fields a little so that it will be consistent when I document that these values are allowed for HTP data

Percentage are usually (0.1%) but occasionally 2 % (with or without space)

Molarity is usually (20mM) but sometimes (20 mM) (with or without space)

Sometimes (2.5 % v/v) and sometimes  (2 % (w/v)) ( different use of brackets)

Just on https://pombase.org/genotype/alg6delta

Is it usual to mix molarity, ratio µg/ml, percentages in a single study?

Anyway, just standardizing use of spaces and brackets would be helpful.

**Comment by ValWood** [comment]
> Maybe "(2.5% v/v)" needs a space though?
yep I think a space is required anywhere that the % is followed by another value

**Comment by kimrutherford** [comment]
I've done that.  The changes will be visible tomorrow.
