### ISSUE TITLE
remove pseudo qualifier from apn1 

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#364]
Gene: apn1 Comment: I think we should remove the /pseudo qualifier form this. The major transcript does contain a stop codon, but I think we want to represent a valid translation, maybe need to think about this some motre...assign to me....

Original comment by: Antonialock

**Comment by ValWood** [comment]
I represented the coding version of this and removed the pseudo qualifier. Its also on the "alternative transcript list" for later
