### ISSUE TITLE
mmi1 adaptor

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3640]
Move targets  from binding to has_input
<img width="1049" alt="Screenshot 2024-01-22 at 16 25 55" src="https://github.com/pombase/curation/assets/7359272/13c9711e-836b-4a16-a5c1-cf00f1e78357">

**Comment by ValWood** [comment]
hi @kimrutherford 

PMID:26670050
has ~100m annotations to 

GO:0003729 | mRNA binding
would it be possible to change all of these to
GO:0140517 | protein-RNA adaptor activity
and add  has_input(SPAC1834.06c) where the input is the same as what is in the "with" field?

**Comment by ValWood** [comment]
ping

**Comment by kimrutherford** [comment]
> and add has_input(SPAC1834.06c) where the input is the same as what is in the "with" field?

Just to be clear: we want to then delete or keep the "with"?

The one existing `GO:0140517 | protein-RNA adaptor activity` annotation with `IPI` evidence has both "with" and "has_input()": https://www.pombase.org/term/GO:0140517

![image](https://github.com/pombase/curation/assets/90474/8704e0ab-6145-404f-a015-b5257d3e4d43)

https://curation.pombase.org/pombe/curs/c757e60bdb79c5cb/feature/gene/view/4/ro

![image](https://github.com/pombase/curation/assets/90474/12097e6d-65a4-494c-a009-748cce0ca8b6)

**Comment by kimrutherford** [comment]
I have a script ready to run to make this change.

**Comment by kimrutherford** [comment]
> GO:0003729 | mRNA binding
> would it be possible to change all of these to

Should the GO term be changed only for IPI annotations?  There are some GO:0003729 annotations with other evidence codes.

**Comment by kimrutherford** [comment]
That's done now.  The changes will be visible on pombase.org on Sunday morning.

**Comment by ValWood** [comment]
great!
