### ISSUE TITLE
H3-S10-P publications

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3657]
from PMID: [19362535]

S10 of histone H3 is phosphorylated during mitosis and displaces HP1 proteins (including Swi6) from chromatin (Fischle et al., 2005; Hirota et al., 2005; Yamada et al., 2005).

**Comment by ValWood** [comment]
Any of these which aren't done. They should be straightforward apart from the "modified forms" and the GO annotations so we can go through that together.

**Comment by PCarme** [comment]
Fischle et al., 2005 (PMID: 16222246) and Hirota et al., 2005 (PMID: 16222244) are not on S. pombe, so not curatable. 
Yamada et al., 2005 (PMID: 16246721) is currently under curation by you.

**Comment by ValWood** [comment]
Ok, can close then!
