### ISSUE TITLE
Allele with description in the name: alp7-5A(S50A,S51A,T100A,T116A,T131A)

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3659]
Hi Val.

It looks like this allele has the description included in the name.  

https://www.pombase.org/genotype/alp7-5A%28S50A,S51A,T100A,T116A,T131A%29-S50A,S51A,T100A,T116A,T131A-amino_acid_mutation-expression-not_assayed_or_wild_type

https://curation.pombase.org/pombe/curs/f134593392c70d97/genotype_manage/ro

I saw this when checking the allele comments load log file:
https://curation.pombase.org/dumps/builds/pombase-build-2024-02-26/logs/log.2024-02-25-22-16-33.allele-comments-from-supporting-data

**Comment by ValWood** [comment]
Yes it's a bit clunky but it's  to differentiate:

allele_comments.txt:alp7-5A(S50A,S51A,T100A,T116A,T131A)	warning: same name as alp7-5A(K341,Y344,R346,K347,Y348)	PMID:29021344
allele_comments.txt:alp7-5A(K341,Y344,R346,K347,Y348)	warning: same name as alp7-5A(S50A, S51A, T100A, T116A, T131A)	PMID:24790093

maybe I should change them to  alp7-5A(a) and alp7-5A(b) would be less confusing?

**Comment by kimrutherford** [comment]
> allele_comments.txt:alp7-5A(K341,Y344,R346,K347,Y348) warning: same name as alp7-5A(S50A, S51A, T100A, T116A, T131A) PMID:24790093

`alp7-5A(K341,Y344,R346,K347,Y348)` isn't in Chado so there's a warning at the moment:
https://curation.pombase.org/dumps/builds/pombase-build-2024-02-26/logs/log.2024-02-25-22-16-33.allele-comments-from-supporting-data

> maybe I should change them to alp7-5A(a) and alp7-5A(b) would be less confusing?

I'd prefer that.  :-)
But if you're happy we the current alleles names, it looks OK in the website.  I only flagged it in case it was an error.

**Comment by ValWood** [comment]
fixed as discussed
