### ISSUE TITLE
Multiple "present_during()" extensions on modification

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3660]
In this case I wonder if having multiple "present_during" extensions is correct?  Should this be split into three separate annotations?

https://pombase.org/gene/SPAC1B3.05

![image](https://github.com/pombase/curation/assets/90474/a717437e-a0e5-41cc-b620-69b239048197)

**Comment by ValWood** [comment]
Yes they should be separate. I think these are in a uploaded dataset so there are probably loads. I'll locate the dataset. Could you script it?

**Comment by ValWood** [comment]
external_data/modification_files/PMID_29996109_modifications.tsv 

there are around 137 rows with >1 present_during

**Comment by kimrutherford** [comment]
> Could you script it?

Yep, no problem.

There's some here too (but just one or two case each):
 - https://pombase.org/reference/PMID:31895039
 - https://pombase.org/reference/PMID:10559981
 - https://pombase.org/reference/PMID:29898918
 - https://pombase.org/reference/PMID:28103117

**Comment by ValWood** [comment]
I can fix the small once manually, they'll probably be in sessions. I'll do those this morning.

**Comment by kimrutherford** [comment]
> Could you script it?

I've fixed them and committed the change.

**Comment by ValWood** [comment]
I fixed all, except for the pairing of presen_during cellular response to DNA damage, present_during mitotic G2 phase  which can co-occur because one is a  'phase' and one is a 'process' (i.e orthogonal).

I don't think this applied to any of Matthew's dataset.

**Comment by kimrutherford** [comment]
Thanks!
