### ISSUE TITLE
rum1 modification extension:  modified residue T62 modified residue T58 added by cdc2 added by cig1 

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3662]
Hi Val.

Is this a correct annotation?  The code for writing the modification data file can only handle one "modified residue" relation per modification annotation.

https://www.pombase.org/reference/PMID:9430640

![image](https://github.com/pombase/curation/assets/90474/22c686d2-a09f-47ab-80df-7c9ed4751228)

**Comment by kimrutherford** [comment]
OK, thanks.  I think "added_by cdc2 , added_by cig1" makes sense because the comma is a bit like "and".

It's displayed as " added by cdc2 and cig1 " in the summary.

**Comment by ValWood** [comment]
yep, I think that was the plan, I had forgotten that we did that. I will add to curation docs.
