### ISSUE TITLE
par1 / SPCC188.02 modification: multiple "added_during()" relations

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3663]
- [x] Should this be split into two annotations, one for "**added during** mitotic anaphase" and one for "**added during** mitotic metaphase"?

FIXED
https://www.pombase.org/gene/SPCC188.02

![image](https://github.com/pombase/curation/assets/90474/f53651b5-b89f-48f0-ae7a-c1444d9f5c4a)

**Comment by kimrutherford** [comment]
Some other cases:
```
SPAC3G9.09c   tif211  MOD:00046   Inferred from Direct Assay    S52   added_during(GO:0000080),added_during(GO:0006974)       PMID:19033384   4896    2013-11-14
SPAC3G9.09c   tif211  MOD:00046   Inferred from Direct Assay    S52   added_during(GO:0000080),added_during(GO:0071494)       PMID:19033384   4896    2013-11-14
SPAC3G9.09c   tif211  MOD:00046   Inferred from Direct Assay    S52   added_during(GO:0000084),added_during(GO:0071494)       PMID:19033384   4896    2013-11-14
SPAC3G9.09c   tif211  MOD:00046   Inferred from Direct Assay    S52   added_during(GO:0000085),added_during(GO:0071494)       PMID:19033384   4896    2013-11-14
```

This is similar but maybe it makes sense to have a single annotation for present_during(X) AND present during(Y)?  It seems like a different case.
```
SPAC9E9.08    rad26   MOD:00696   Inferred from Direct Assay          present_during(GO:0000085),present_during(GO:0006974)   PMID:10559981   4896    2018-10-22
```

**Comment by ValWood** [comment]
these ones are OK, phase + process
<img width="1006" alt="Screenshot 2024-03-01 at 16 45 42" src="https://github.com/pombase/curation/assets/7359272/55a544c2-f738-4d3c-9868-04c2c633d6da">
