### ISSUE TITLE
pmt3 / SPBC365.06: two "added_by()" relations

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3664]
Should these annotation be split?

![image](https://github.com/pombase/curation/assets/90474/a367e101-9a6e-4cdd-a5f6-19fe5011deb3)

**Comment by kimrutherford** [comment]
Two other cases where there are two "added_by()" relations:

```
SPAC644.14c     rad51   MOD:01148   Inferred from Direct Assay  added_by(PomBase:SPBC336.01),added_by(PomBase:SPBC409.05)       PMID:25165823   4896    2014-09-03
SPBC582.03      cdc13   MOD:01148   Inferred from Direct Assay  added_by(PomBase:SPBC119.02),added_by(PomBase:SPCC1259.15c)     PMID:12724408   4896    2014-12-01
```

**Comment by ValWood** [comment]
fixed, I kept the pmt3 ones because these 'couples' work together like cdc2/cig1 example

**Comment by ValWood** [comment]
I added the rad51 one back, that was correct too
