### ISSUE TITLE
Genes with annotations and a NOT annotation to the same term

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3665]
I don't know if these are a problem, but here they are just in case.  These are genes with an annotation but also a NOT annotation to the same term.

```
      gene     |                  term_name                  
---------------+---------------------------------------------
 SPBC32F12.03c | thioredoxin peroxidase activity
 SPAC29B12.02c | histone H3K36 trimethyltransferase activity -> fixed, i misinterpreted
 SPBC2F12.08c  | mRNA capping enzyme complex  -> fixed, legacy ISS
 SPAC644.04    | mRNA capping enzyme complex -> fixed, legacy ISS
 SPAC17H9.04c  | nucleus
 SPAC23C11.14  | fungal-type vacuole membrane
```

 SPAC17H9.04c The Dri1-GFP signal is present in the cytoplasm in a dispersed manner throughout the cell cycle and appears to be excluded from the nucleus ([Figure 3](https://www.mdpi.com/1422-0067/22/9/4795#fig_body_display_ijms-22-04795-f003)A)

**Comment by ValWood** [comment]
SPBC32F12.03c | thioredoxin peroxidase activity
and
SPAC23C11.14  | fungal-type vacuole membrane
are conflicts in different papers, I resolved the others
