### ISSUE TITLE
check HDAC complexes/ revise GO names?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3670]
Rpd3S complex-> Rpd3S/Clr6S complex

Rpd3L complex-> Rpd3L/Clr6L/Complex II

**Comment by ValWood** [comment]
The ticket wasn't very explict!
Basically if you can confirm what the complexes are called in pombe, and their members I will revise the GO labels to include the Clr6 name (and make sure that all of the correct synonyms are associated).

If it isn't clear I would contact the authors if they are still working on pombe, check with me if you can't resolve.

**Comment by PCarme** [comment]
I have found mentions of 3 Clr6 complexes in S. pombe : 
- Clr6S/Rpd3S/SIN3S : composed of Clr6, Cph1, Cph2, Pst2, Alp13 (2 copies) and Prw1
- Clr6L/Rpd3L/SIN3L : composed of Clr6 (2 copies ?), Rxt2, Rxt3, Sds3, Pst1, Pst3, Prw1 (2 copies ?), Dep1, Png2, Laf1, Laf2 and Cti6
- Clr6L Extended : All of Clr6L subunits + Srt1, Hif2, Set3 and Hda1 from Set3 Complex. 
Informations found in these papers : PMID:37076472 / PMID:19040720 / PMID:37459529

There is also this paper PMID:17450151 in which they did size fractionation and identified 3 forms of Clr6 complexes : 
- Complex II, which corresponds to Clr6S, 
- Complex I and I', which both contain few detectable subunits from Clr6L (and probably correspond to Clr6L & the extended complexe), and only differ by the detection of Png2 (a subunit of both Clr6L and extended) in complex I'.

**Comment by ValWood** [comment]
We have annotated

[Rpd3S complex](https://www.pombase.org/term/GO:0032221)
[alp13](https://www.pombase.org/gene/SPAC23H4.12), [clr6](https://www.pombase.org/gene/SPBC36.05c), [cph1](https://www.pombase.org/gene/SPAC16C9.05), [cph2](https://www.pombase.org/gene/SPAC2F7.07c), [prw1](https://www.pombase.org/gene/SPAC29A4.18), [pst2](https://www.pombase.org/gene/SPAC23C11.15)

[Clr6 histone deacetylase complex I''](https://www.pombase.org/term/GO:1990483)
[clr6](https://www.pombase.org/gene/SPBC36.05c), [laf1](https://www.pombase.org/gene/SPAC14C4.12c), [laf2](https://www.pombase.org/gene/SPCC1682.13), [mug165](https://www.pombase.org/gene/SPAC5D6.02c), [nts1](https://www.pombase.org/gene/SPCC24B10.19c), [png3](https://www.pombase.org/gene/SPAC16E8.12c), [prw1](https://www.pombase.org/gene/SPAC29A4.18), [pst1](https://www.pombase.org/gene/SPBC12C2.10c), [pst3](https://www.pombase.org/gene/SPBC1734.16c), [rxt2](https://www.pombase.org/gene/SPBC428.06c), [rxt3](https://www.pombase.org/gene/SPCC1259.07), [sds3](https://www.pombase.org/gene/SPAC25B8.02)

although the definition of this complex says

Definition	Parents
A histone deacetylase complex involved in chromatin organization. In Schizosaccharomyces pombe this complex consists of Clr6, Nts1, Mug165, and Png3

[Rpd3L complex](https://www.pombase.org/term/GO:0033698)
[clr6](https://www.pombase.org/gene/SPBC36.05c), [cti6](https://www.pombase.org/gene/SPBC1685.08), [dep1](https://www.pombase.org/gene/SPBC21C3.02c), [laf1](https://www.pombase.org/gene/SPAC14C4.12c), [laf2](https://www.pombase.org/gene/SPCC1682.13), [pcf3](https://www.pombase.org/gene/SPAC25H1.06), [png2](https://www.pombase.org/gene/SPBC1709.11c), [prw1](https://www.pombase.org/gene/SPAC29A4.18), [pst1](https://www.pombase.org/gene/SPBC12C2.10c), [pst3](https://www.pombase.org/gene/SPBC1734.16c), [rxt2](https://www.pombase.org/gene/SPBC428.06c), [rxt3](https://www.pombase.org/gene/SPCC1259.07), [sds3](https://www.pombase.org/gene/SPAC25B8.02)

[Rpd3L-Expanded complex](https://www.pombase.org/term/GO:0070210)
[clr6](https://www.pombase.org/gene/SPBC36.05c), [cti6](https://www.pombase.org/gene/SPBC1685.08), [dep1](https://www.pombase.org/gene/SPBC21C3.02c), [hif2](https://www.pombase.org/gene/SPCC1235.09), [hos2](https://www.pombase.org/gene/SPAC3G9.07c), [laf1](https://www.pombase.org/gene/SPAC14C4.12c), [laf2](https://www.pombase.org/gene/SPCC1682.13), [pcf3](https://www.pombase.org/gene/SPAC25H1.06), [png2](https://www.pombase.org/gene/SPBC1709.11c), [prw1](https://www.pombase.org/gene/SPAC29A4.18), [pst1](https://www.pombase.org/gene/SPBC12C2.10c), [pst3](https://www.pombase.org/gene/SPBC1734.16c), [rxt2](https://www.pombase.org/gene/SPBC428.06c), [rxt3](https://www.pombase.org/gene/SPCC1259.07), [sds3](https://www.pombase.org/gene/SPAC25B8.02), [set3](https://www.pombase.org/gene/SPAC22E12.11c), [snt1](https://www.pombase.org/gene/SPAC22E12.19)

**Comment by ValWood** [comment]
I filtered the mapping to remove  pcf3 from RPD3 and RPD3L expanded

**Comment by ValWood** [comment]
I don't think we need a term for
[Clr6 histone deacetylase complex I''](https://www.pombase.org/term/GO:1990483)
this seems likey to be an artefact @PCarme  do you agree?

**Comment by ValWood** [comment]
PMID:19040720 seems to show that snt1 hif2(sif2) set3, hos2 and (tos4 missing) 
are also part_of Rpd3L-Expanded complex 
so maybe everything else is OK.

I will remove the complex annotations from  PMID:25002536, the physical interactions will still be there
and remove the GO term
[GO:1990483](https://www.pombase.org/term/GO:1990483)	
[Clr6 histone deacetylase complex I''](https://www.pombase.org/term/GO:1990483)

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/27509
term will go, I think we can close this, thanks!
