### ISSUE TITLE
PMID:15550243 review

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3678]
CC @PCarme 

 **MF**
I explicitly added the histone substrates.

Histones are a special case in GO. They are one of the only MF terms which refers to a gene product. This is "allowed" so that we can  capture the histone code (usually  it would just be protein methyltransferase has_imput geneA
However, to build the modes automatically we  needed to add the substrate histones.
For histones (unless there is any compelling reason to do otherwise) I always add all 3 since the sequence is identical (using EXP, as you have done)
- moved down to "trimethyltransferase"
(Then it covets the existing IEA, specific term was not added until 2022)

Added MF with IMP for set1

**Existing annotations**

set6 GO:0042054histone methyltransferase activity ISM InterPro:IPR001214
(I kept this as it shows the IEA is reviewed and agreed)

set9GO:0042799histone H4K20 methyltransferase activityIMP
(Deleted, redundant with new more detailed annotation)

set9	GO:0006355	regulation of DNA-templated transcription	IMP	NOT
Deleted and added 
GO:0010468	regulation of gene expression NOT instead

Deleted and instantiated in the session	
set9	GO:0007095	mitotic G2 DNA damage checkpoint signaling	IMP	

**Localization** 
Deleted	legacy annotation	

I'm trying to remove process localization terms unless they are transport

Basically we should try to make a 
MF x adaptor for Y during process 
If we can't  do that (as here because we don't know if it is direct), the localization dependency is captured by the phenotype.
Rationale The process/pathway isn't really 'localization' it's  some aspect of  mitotic G2 DNA damage checkpoint signaling.
In GO if we captured localization of everything there would be combinatorial explosion.

A nice example is cdc15
https://www.pombase.org/gene/SPAC20G8.05c
where we use an adaptor  term (in this case displayed as anchored) 

**Geneoype background**

Added background hhf1delta hhf3delta to the histone mutants (usually we would do other deleted genes as a multi phenotype, but in this case I think background is probably better)

It also explains
This most likely reflects the slower growth rate of the h4.2 background strain, as we have found that fission yeast cells are generally more resistant to CPT when growing at a reduced rate (data not shown).

**Modifications**

Added these

**Question**

would this term label be better if it were
decreased ~response to~ mitotic G2 DNA damage checkpoint signaling (FYPO:0004372)

like the parent. "response to" signalling seems a bit ambiguous as it could refer to the downstream events? What do you think?

**Comment by ValWood** [comment]
and  the parent 
abnormal mitotic G2 DNA damage checkpoint (FYPO:0004373)
-> abnormal mitotic G2 DNA damage checkpoint  signalling (FYPO:0004373)

**Comment by PCarme** [comment]
I feel like "decreased response to mitotic G2 DNA damage checkpoint signaling" is more descriptive of the observed phenotype (what we can see is the response to the signalling). "decreased mitotic G2 DNA damage checkpoint signaling" is probably more consistent with the actual effect of the mutation.

**Comment by ValWood** [comment]
OK!
