### ISSUE TITLE
Early cytokinetic node formation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3679]
I think we have most of the cytokinetic network, but are missing some of these early steps:

Plo1-induced export from the nucleus of the anillin-like protein Mid1, reinforces division plane positioning in the cell middle (Almonacid et al., 2009), 

Plo1 also activates Mid1, which becomes competent for the sequential recruitment of essential ring components (Almonacid et al., 2011):  Mid1 first engages the IQGAP protein Rng2 and myosin II light chain Cdc4, heavy chain Myo2 and regulatory light chain Rlc1. 

We are also  missing myo2 and rlc2 (if these are directly recruited by mid1….)

**Comment by PCarme** [comment]
Note to self - see references :
Motegi, F., M. Mishra, M. K. Balasubramanian, and I. Mabuchi. 2004. Myosin
II reorganization during mitosis is controlled temporally by its dephosphoryla-
tion and spatially by Mid1 in fission yeast. J. Cell Biol. 165:685–695
Wu, J. Q., J. R. Kuhn, D. R. Kovar, and T. D. Pollard. 2003. Spatial and
temporal pathway for assembly and constriction of the contractile ring in
fission yeast cytokinesis. Dev. Cell 5:723–734

**Comment by PCarme** [comment]
Uncurated publication : 
PMID:22427686

**Comment by ValWood** [comment]
>  Should I curate this myself ?
I sent a reminder, they usually curate

**Comment by PCarme** [comment]
> Uncurated publication : PMID:22427686 It was actually sent to the author in 2014, with 6 reminders (last sent in 2020). Should I curate this myself ?

In the end I went on and curated this one. 
I think we should have the steps of recruitments of the different factors covered in GO MF at this point. Still need to annotate the activation of mid1 by plo1.

**Comment by PCarme** [comment]
> > Uncurated publication : PMID:22427686 It was actually sent to the author in 2014, with 6 reminders (last sent in 2020). Should I curate this myself ?
> 
> In the end I went on and curated this one. I think we should have the steps of recruitments of the different factors covered in GO MF at this point.
