### ISSUE TITLE
CTD_T1 allele description

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3685]
Hi @ValWood

I'm investigating a failure of the allele_qc pipeline:
https://github.com/pombase/allele_qc/actions/runs/8531853828/job/23372127361

I think it's failing on the allele in this genotype on the description `CTD-T1F...`:
 https://pombase.org/genotype/rpb1-Y1F-S2A%28CTD-18repeats%29-CTD-T1F,S2A%28r5-r18%29,%E2%88%86%28r19-r29%29-amino_acid_deletion_and_mutation-expression-not_assayed_or_wild_type

Could you check that the description is OK?  The allele_qc code doesn't like the "T1"

**Comment by ValWood** [comment]
Yes, it should be 'Y" ! will fix

**Comment by kimrutherford** [comment]
Thanks.  Once it's fixed and in Chado, I'll manually re-run the allele_qc pipeline.

**Comment by kimrutherford** [comment]
Thanks.  The allele_qc pipeline works again now.
