### ISSUE TITLE
orthologs cannot be distinguished, to check

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#369]
SPAC13G6.08, Cdc20/Fizzy subfamily WD repeat protein 
SPAC1D4.13, byr1, I, MAP kinase kinase Byr1 
SPAC6F12.03c, fsv1, I, SNARE Fsv1 
SPAC6G9.04, spo7, I, sporulation protein Spo7
SPAPB1A11.02, SPAPB1A11.02, I, esterase/lipase (predicted) 
SPBC16E9.17c, rem1, II, meiosis-specific cyclin Rem1 
SPBC19F5.01c, puc1, II, cyclin Puc1 
SPCC1620.04c, mug55, III, Cdc20/Fizzy subfamily WD repeat protein 

Original comment by: ValWood

**Comment by ValWood** [comment]
transfered remaining task to:
https://github.com/pombase/curation/issues/810
