### ISSUE TITLE
Tor1 listed in the subunits of TORC1

### ISSUE THREAD

**Issue by PCarme** [pombase/curation#3693]
The page for ontology term "TORC1 complex" (GO:0031931) lists Tor1 as a subunit of the complex, with an IBA evidence code
![image](https://github.com/pombase/curation/assets/163283897/d8323954-ec21-47c5-b683-28881a24d84f)
although in pombe, Tor1 is specific to TORC2, and Tor2 to TORC1.

**Comment by ValWood** [comment]
thansk
reported 
https://github.com/geneontology/go-annotation/issues/3466

I will filter this mapping
