### ISSUE TITLE
Annotation of lsd2 to GO:007115 

### ISSUE THREAD

**Issue by PCarme** [pombase/curation#3707]
Reviewing the mating type switching pathway for the GO-CAM, it seems like lsd2 is involved in this BP with lsd1, although it is not annotated to it. 
The lsd1 annotation comes from this paper PMID: 23260662, in which the effect of lsd2 deletion on mating type switching could not be tested because it is inviable. The paper still shows that combining catalytically dead lsd1 and lsd2 is required to affect the imprinting (Fig. 3A), so I was thinking of annotating lsd2 to this GO BP with an IGI evidence. @ValWood , what do you think about it ?

**Comment by ValWood** [comment]
Sounds good, and makes sense since they are a complex.

**Comment by ValWood** [comment]
I guess it is also involved in heterochromatin formation at MT region?

**Comment by PCarme** [comment]
They are both annotated to heterochromatin boundary formation so probably, I will have to look into this.
