### ISSUE TITLE
act1-LatA resistance

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3712]
https://www.pombase.org/genotype/act1-R183A,D184A-R183A,D184A-amino_acid_mutation-expression-not_assayed_or_wild_type

[act1-LatA resistant](https://www.pombase.org/reference/PMID:18562692)
but does not have LatA resistant phenotype annotation?

**Comment by ValWood** [comment]
Thanks for that, I just deleted the synonym

**Comment by PCarme** [comment]
Okay, so we can close this issue I guess
