### ISSUE TITLE
GO:1902406 has a GO-CAM but no annotations

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3714]
I was confused by this so I wanted to check: is it OK for GO:1902406 to have GO-CAM but no annotations?:
http://dev.pombase.kmr.nz/term/GO:1902406

**Comment by PCarme** [comment]
I have changed that annotation last week. This BP shouldn't appear in the model anymore, but I'm guessing that the change is not available in the GO release yet.

**Comment by kimrutherford** [comment]
Thanks Pascal.  I'll look out for the next release.  You've answered my question so I'll close this issue.
