### ISSUE TITLE
SBF/MBF complex annotations in S. pombe

### ISSUE THREAD

**Issue by PCarme** [pombase/curation#3717]
@ValWood 
As you asked me to do here https://github.com/geneontology/go-ontology/issues/28372 I had a look at the annotations we have for SBF and MBF complexes in PomBase. We have full experimental evidence for the subunits of MBF, but only inferred annotations to SBF. 
I couldn't find any paper related to SBF complex in S. pombe, or any evidence that these two are separate complexes in S. pombe. So I discussed it with Jurg, and he told me that S. cerevisiae has 2 complexes, SBF (formed by interaction between Swi6 and Swi4) and MBF (formed by interaction between Swi6 and Mbp1), but S. pombe only has a common ortholog for Swi4 and Mbp1 called Res1, and so only the MBF complex. 
So we should probably remove the annotations to SBF complex, which are mostly redundant with MBF anyway.

**Comment by ValWood** [comment]
Thanks
