### ISSUE TITLE
specific replication termination terms

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3719]
I was chatting with Pascale today and we were looking at how to  add some terms when we spotted:

<img width="861" alt="Screenshot 2024-07-18 at 14 33 24" src="https://github.com/user-attachments/assets/fe7a9248-eda9-4b2d-b689-d7dd46098769">

These terms seem a bit out of scope for GO. and these are the only 2 EXP annotations (which means they aren't really very useful process terms)
Do you think we could just use "replication termination" occurs at "some region described by GO CC"

Let me know what you think.

**Comment by PCarme** [comment]
For the "site-specific" one, I think you're right, we could just make it so the site can be annotated through an extension. I wonder if it might be a term that has been created just as a grouping term for termination at those specific sites ? Although looking at the child terms for it, that would only fit  for "site-specific DNA replication termination at RTS1 barrier", are there any other specific termination sites described ? 
For the "cis-acting" one, looking at the term's definition I wonder if the term name shouldn't reflect the idea of long-distance termination to be more descriptive ? Actually the paper from which this annotation comes on reb1 describes cis-acting as well as trans-acting effects, so it seems like the main characteristic of the mechanism is the "remote, through topological rearrangements" side of it. 
<img width="919" alt="image" src="https://github.com/user-attachments/assets/57937eb9-a766-49ea-84e6-00d12fa44acc">
Anyway, you're right that these terms don't have a lot of EXP annotations to them, so they might not be very useful in describing actual biological processes...

**Comment by ValWood** [comment]
great, thanks, I made an obsoletion ticket.
