### ISSUE TITLE
Genes which used to have signal peptides but no longer have

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3739]
These genes have had revised structures which means that they
These genes  do not have signal peptides because the sequence does not match the UniProt sequence at the N-term. 

https://www.pombase.org/results/from/id/5fcb9395-8d2f-407e-8ef9-fa6050cf01a2

Systematic ID	Gene name	Product description
SPBC30D10.09c	hva22	ER membrane organization protein, HVA22/TB2/DP1 family protein
SPAC13C5.03	tht1	nuclear membrane protein involved in karyogamy Tht1
SPBC337.16	cho1	phosphatidyl-N-dimethylethanolamine N-methyltransferase
SPBC13E7.05	gpi14	pig-M, glycosylphosphatidylinositol-mannosyltransferase I complex subunit pig-M
SPAC1F12.09	gpi17	pig-S
SPCC622.11	lmb1	plasma membrane LMBR1-like multi-pass membrane protein, human LMBRD2 ortholog, implicated in signalling

However, we would expect them to have signal peptides, this indicates a possible issue with the sequence revision

SignalP
DeepSig
Phobius 
also did not provide signal peptides.

We need to check if the N-term trimming was over enthusiastic. This was likely done to match the N-term of Schizo paralogs (which might not be good), or to make the translation start inside the transcription start.
Consider reinstating the old sequences 
(fasta is probably the best tool to check the N-term alignments (need a global alignment tool)

**Comment by ValWood** [comment]
similar situation for transit peptides with these
 SPAC23C11.17 transit_peptide
 SPAC5H10.06c transit_peptide
 SPAC167.04 transit_peptide
 SPAC1B3.18c transit_peptide

**Comment by PCarme** [comment]
> We need to check if the N-term trimming was over enthusiastic. This was likely done to match the N-term of Schizo paralogs (which might not be good), or to make the translation start inside the transcription start. Consider reinstating the old sequences (fasta is probably the best tool to check the N-term alignments (need a global alignment tool)

I am not sure of what you mean by checking the alignments exactly.

> Systematic ID Gene name Product description 
>SPBC30D10.09c hva22 ER membrane organization protein, HVA22/TB2/DP1 family protein 
>SPAC13C5.03 tht1 nuclear membrane protein involved in karyogamy Tht1 SPBC337.16 cho1 phosphatidyl-N-dimethylethanolamine N-methyltransferase 
>SPBC13E7.05 gpi14 pig-M, glycosylphosphatidylinositol-mannosyltransferase I complex subunit pig-M
>SPAC1F12.09 gpi17 pig-S 
>SPCC622.11 lmb1 plasma membrane LMBR1-like multi-pass membrane protein, human LMBRD2 ortholog, implicated in signalling

I tested using SignalP and Phobius on the UniProt sequences for these proteins. SignalP predicted a signal peptide on Tht1 residues 1-29 (which are absent in the PomBase sequence). I got no predictions for the other genes.

**Comment by ValWood** [comment]
No worries we can [ark this until after the hols!

**Comment by ValWood** [comment]
I'm going to close this. 
We can add additional prediction methods if  we come across them. Some should be fixed when the uniprot sequence become updated
