### ISSUE TITLE
Residue fix for PMID:33711009 - remove en-dash

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3746]
Could you change the residues extension ("residue 506–639") in this session to use a dash rather than an en-dash?:
https://curation.pombase.org/pombe/curs/fcfd9a50a6a6cb53/ro

https://www.pombase.org/reference/PMID:33711009

Unfortunately it's messing things up in the website and changing the extension is the quickest fix.

**Comment by ValWood** [comment]
@pcar

**Comment by PCarme** [comment]
Done !

**Comment by kimrutherford** [comment]
Thanks Pascal.  I'll check the website in the morning to make sure that the problem is gone.

**Comment by kimrutherford** [comment]
> I'll check the website in the morning to make sure that the problem is gone.

All fixed.  Thanks!
