### ISSUE TITLE
Possible UniProt mis-annotation of modifications in hta1 and hta2

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3747]
There is one PubMed ID in the UniProt data that we don't have already in Chado:
https://pubmed.ncbi.nlm.nih.gov/24352239/

I can't see a mention of pombe or fission yeast in the text so I wonder if the annotations are incorrect?

It's the reference for only two annotations.  Modification of residue 106 in these two proteins:
  - https://www.uniprot.org/uniprotkb/P04909/feature-viewer
  - https://www.uniprot.org/uniprotkb/P04910/feature-viewer

PomBase: [hta1](https://www.pombase.org/gene/SPCC622.08c) and [hta2](https://www.pombase.org/gene/SPAC19G12.06c) : [ N5-methyl-L-glutamine](https://www.pombase.org/term/MOD:00080)

**Comment by ValWood** [comment]
What's the evidence code ?

**Comment by ValWood** [comment]
I think this should probably be ISS, it isn't clear which yeast it is but I think it is S. cerevisiae.
@Antonialock  what do you think?

**Comment by kimrutherford** [comment]
> What's the evidence code ?

"experimental evidence used in manual assertion"

They're both here: https://www.pombase.org/term/MOD:00080

**Comment by Antonialock** [comment]
yes if anything it should be ISS. Do you think we could keep them (with ISS) or remove?

**Comment by Antonialock** [comment]
Thanks! I changed the evidence code and will submit the change for integration today.
