### ISSUE TITLE
add residues vacuolar sorting signal

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3751]
See if residues can be added here

<img width="837" alt="Screenshot 2024-10-01 at 10 34 59" src="https://github.com/user-attachments/assets/ac1fa95f-19e3-4854-ba50-8b9bdf4d03fa">

**Comment by ValWood** [comment]
in pombe_embl/external_data (I think?)

**Comment by PCarme** [comment]
Not really. This paper only narrows it down to the 478 N-terminal amino acids of Cpy1. And I didn't find any more precise mapping in other papers.

**Comment by ValWood** [comment]
OK!
