### ISSUE TITLE
Session with problem synonyms for rpb1 alleles

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3775]
Moved from this issue which is a bit long:
 - pombase/pombase-chado#1192

> > rpb1-S5.S5A (this is incorrect, which session was it added?)
> > rpb1-CTD-S5.S5A (this is incorrect, which session was it added?)
>
> I think this is the session that has the problem synonyms:
> https://curation.pombase.org/pombe/curs/67f8ea3e5c1c1bfc/genotype_manage/ro

**Comment by ValWood** [comment]
I think the synonyms in that session are OK. Its the correct residues. This is how this alleles would be captured i papers before we had the ability to describe the specific repeat numbers affected

**Comment by ValWood** [comment]
The ones I sew  were for all sorts of different residues (I think)?

**Comment by kimrutherford** [comment]
> The ones I saw were for all sorts of different residues (I think)?

I removed the synonyms that were from the the wrong alleles.

**Comment by ValWood** [comment]
so  we can close this?

**Comment by kimrutherford** [comment]
> so we can close this?

Yep!
