### ISSUE TITLE
SPCC1442.04c sequence update

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#381]
This came from the email exchange surrounding PMID:24210919 community curation:

I asked Nathan Lee (nathan dot lee at nih.gov) about a SPCC1442.04c allele that deleted a cryptic intron. The worms seized their opportunity, and left the can.

This is what I've received so far:

"Regarding your questions on SPCC1442.04c, it's a bit complicated. First, the gene structure in pombase is not entirely correct. It currently shows 2 bp intron. However, when I sequenced it, the wildtype genomic DNA sequence is different from what's in the database. About 4 bp changes need to be made around the annotated 2bp intron.  And the current pombase annotation doesn't have the cryptic intron annotated, but I don't think we should annotate the cryptic one as an intron since it creates a frameshift of the gene causing nonsense transcript.  The deleted intron is the "cryptic intron #2" annotated in the paper, not present in pombase. I will dig out the correct genomic DNA sequence and provide you the information if you are interested."

[snip rest of email about annotations in the session]

Original comment by: mah11

**Comment by mah11** [comment]
file that was attached to the SourceForge ticket is also attached to the relevant RT ticket
https://rt.sanger.ac.uk/Ticket/Display.html?id=391582

**Comment by ValWood** [comment]
was already in the list, so closing
http://www.pombase.org/status/sequence-updates
