### ISSUE TITLE
Canto Admin interface documentation

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#384]
Currently there is not much documentation for the admin side of Canto.  Scott Cain has asked that we work on some.

Some things that need docs, some is configuration stuff and some is day-to-day curator stuff:
- triage
  - adding / changing triage types (configuration)
- user management (adding a user?)
- session management (assigning, sending out)
- session approval
- publication list updating (from PubMed with `canto_add.pl` script)
- publication management
- exporting annotation and loading into Chado (partially documented)

Original comment by: kimrutherford

**Comment by ValWood** [comment]
From the wiki

* Canto documentation required
  * From Scott: provide even one paper and walk the user through entering the paper, the genes and a sample entry.  Then you could also walk through an administrative approval and saving the data to Chado (Kim suggested we start with just a list of bullet points)

The podcast Antonia is looking into will be useful for GMOD

**Comment by ValWood** [comment]
moved to Canto tracker
https://github.com/pombase/canto/issues/1758
