### ISSUE TITLE
new ribosomal nomenclature

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#386]
Implement if others do....

http://www.sciencedirect.com/science/article/pii/S0959440X14000037

Original comment by: ValWood

**Comment by ValWood** [comment]
It's doubtful we will ever do this.
We would follow the lead of other MODs with more  details ribosomal work and even in the paper it say there was a reluctance for yeast to adopt the new scheme. The current names are working just fine for us right now...

  we will adopt Systematic nomenclature only when we know its the universally accepted naming system.
