### ISSUE TITLE
mating type region

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#39]
Need to follow this up at some point. MAy need to check further with Juan...

Yes, what Xavi did is perfect.  He's put together mat2 and mat3 with adjacent regions (which should be present in all h90 strains).  In h90 cells, mat1 would switch between having a p cassette or a m cassette.  In 972 h- there is a deletion of mat2-p.  However, in some h+ strains there is a deletion of mat3-M, but more frequently there are mutations that prevent the switching from P to M, although mat2-P is still there.  Therefore, one would have to assemble a different region for each strain.  I think the configuration of the different h+ and h- strains is described in the very old pombe book.  Anyway, most of the time people don't even know which h+ or h- allele they have.

I think it would help to annotate mat1-m and mat3-m as such in the main contig (rather than calling them matmi_1 and _2 - or at least add a note), so that people know which one they are looking at.   Also, it would help to annotate the features of the mating type region that Xavi put in his contig and that are present in 972 (like the IR-L and IR-R regions, or the homology boxes).  Finally, would it be possible to add a note somewhere directing people to the mating type contig?

I hope this is useful - let me know if I can help with anything else

Juan

Original comment by: ValWood

**Comment by ValWood** [comment]
documentation, where to find mating type info

are all features in mating type contig annotated with SO terms?
(features for mat1 locus, mat3 locus, K repeat, H1, H2, H3, silenced genes etc)

gene_cassette_array SO:0005854 ("An array of non-functional genes whose members, when captured by recombination form functional genes."), and also
cassette_array_member SO:0005847

silenced_gene SO:0000127 and descendants

or a common child will probably be appropriate

**Comment by ValWood** [comment]
closing unless anyone asks us to do anything
