### ISSUE TITLE
creating GO terms for phenotypes when a  process doesn't exist

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#399]
I guess the question is, should we do this?

I think we have sometimes used GO to create logical defs for terms, and created terms like this, when there isn't really a 'biological process'
Is there another way to model these?
perhaps just starvation, and chebi for compound.

Original comment by: ValWood

**Comment by Antonialock** [comment]
Closing this based on Midoris last comment: "Any problematic terms in GO will have to be handled on a case-by-case basis, as will any repercussions for FYPO term definitions"
