### ISSUE TITLE
various updates to mitochondrial respiratory chain, waiting for GO

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#405]
I would avid any old papers related  to respiratory complex until these are fixed:

https://github.com/geneontology/go-ontology/issues/11051

https://github.com/geneontology/go-ontology/issues/11050 (done)

https://github.com/geneontology/go-ontology/issues/11049 (closed out of date)

https://github.com/geneontology/go-ontology/issues/11050 (done)

Most of our existing ISS's look OK

GO:0045281 - succinate dehydrogenase complex (5 subunits)

GO:0005750 (10 subunits)
Name    mitochondrial respiratory chain complex III

GO:0008121 ubiquinol-cytochrome-c reductase activity (all complex III)
(OK when  missing annotations added to cyt1 and qcr1)

Update
mitochondrial electron transport, NADH to ubiquinone (IDA) 
add
- [x] SPBC947.15c
- [x] SPAC3A11.07
update annotation and products

- [x] GO:0045153 electron transporter, transferring electrons within CoQH2-cytochrome c reductase complex activity
(changed single existing annotation  (cyt1) to GO:0008121 ubiquinol-cytochrome-c reductase activity (contributes_to))

- [x] qcr1
add 
GO:0008121 ubiquinol-cytochrome-c reductase activity (contributes_to)
remove proteolysis
add
GO:0006122  mitochondrial electron transport, ubiquinol to cytochrome c

Original comment by: ValWood

**Comment by ValWood** [comment]
I think you said you were doing some mitochondrial paper annotation? if so you should monitor these GO tickets and not address any of these until the GO things are fixed

**Comment by Antonialock** [comment]
nope, I haven't been doing much on mitochondria :)

**Comment by ValWood** [comment]
tickets on jira are
https://github.com/geneontology/go-ontology/issues/11051
https://github.com/geneontology/go-ontology/issues/11050
https://github.com/geneontology/go-ontology/issues/11048

**Comment by ValWood** [comment]
I'll close this, we can frefer back to it but there is no specific action right now
