### ISSUE TITLE
revise some old polarity annotations tea1/tea4

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#408]
tea1
GO:0071963  establishment or maintenance of cell polarity regulating cell shape             37
during cellular response to stress  IMP     Tatebe H et al. (2005)

GO:2000771  positive regulation of establishment or maintenance of cell polarity regulating cell shape

tea4 has
GO:0071963  establishment or maintenance of cell polarity regulating cell shape IMP     Martin SG et al. (2005) 37
during cellular response to stress  IMP     Tatebe H et al. (2005)

I think these annotations could be slighhtly incorect as tea1/tea4 are not required for  polarized growth per se, but for the location of this process

so the annotation should probably be more along the lines of 
"positioning of the growth zone/ site selection during establishment of cell polarity"

low priority but I think these papers haven't gone through Canto yet

Original comment by: ValWood

**Comment by ValWood** [comment]
Cell polarity annotation is moving along, so this one is largely out of date. new tickets for missing links
