### ISSUE TITLE
question about relationship display labels for discussion (GAP/GEF)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#409]
i) Exchange of GDP for GTP is 'promoted' by GEFs (positive regulation)
Guanine nucleotide exchange factors (GEFs) activate monomeric GTPases by stimulating the release of guanosine diphosphate (GDP) to allow binding of  (GTP).
Note that guanyl-nucleotide exchange factor (GEF) activity alters binding affinity, but not GTPase catalytic activity directly. Therefore GO:0005085 is under 'regulation of GTPase activity' but is not a 'GTPase regulator', which is reserved for cases where the action of one gene product directly alters the rate of catalysis by another gene product.
ii) GAPs promote GTP hydrolysis (direct enzyme activation)
NOT and enzyme activator, priming, not activating

question  about labels
scd1 http://www.pombase.org/spombe/result/SPAC16E8.09
has 
Rho guanyl-nucleotide exchange factor activity  has direct input cdc42
what should this relation display as? (positively regulates?)

on the cdc42 page in the target_of section the relation is "input for"
input for
scd1
RhoGEF Scd1
what should be displayed
(ideally we would have specific relations for GAFs and GEFs 'activated by' and 'positively regulates'

Original comment by: ValWood

**Comment by ValWood** [comment]
Midori is fixing the config file
