### ISSUE TITLE
AE meeting at EBI, use of localization_dependent_on  

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#411]
We have some cases of the use of 

"localization_dependent_on" with component which is disallowed (domain restriction). 

Essentially an annotation extension should extend the GO term, and here we are capturing something which is related to the gen product (does this make sense?)

Anyway, some of them we don't need because we already capture the reciprocal (and display the reciprocal in the target section) so making this annotation is redundant

For example,
mid2 CC "medial cortical node" localization_dependent_on(cdr2)
They are the reciprocal of:
cdr2 BP "protein localization to medial cortex"  has_input(localizes(mid2)

so we can just get rid of the extensions here. As this is done we should check that the 'forward' process localization annotation is in place.

PomBase	SPCC18B5.03	wee1		GO:0071341	PMID:19474792	IDA		C	M phase inhibitor protein kinase Wee1		protein	taxon:4896	20090826	PomBase	localization_dependent_on(PomBase:SPAC57A10.02)	

PomBase	SPCC4B3.15	mid1		GO:0071341	PMID:19474789	IDA		C	medial ring protein Mid1	dmf1	protein	taxon:4896	20050729	PomBase	exists_during(GO:0051319),localization_dependent_on(PomBase:SPAC57A10.02)	

PomBase	SPBC3H7.13	far10		GO:0044732	PMID:22119525	EXP		C	SIP/FAR complex FHA domain subunit Far10/Csc1	csc1	protein	taxon:4896	20121126	PomBase	dependent_on(PomBase:SPAC4H3.11c),exists_during(GO:0000091)

PomBase	SPAC21E11.03c	pcr1		GO:0005667	PMID:9135083	IDA		C	transcription factor Pcr1	mts2	protein	taxon:4896	20130313	PomBase	localization_dependent_on(PomBase:SPBC29B5.01)	

PomBase	SPBC29B5.01	atf1		GO:0005667	PMID:9135083	IDA		C	transcription factor, Atf-CREB family Atf1	gad7|sss1|mts1	protein	taxon:4896	20130313	PomBase	localization_dependent_on(PomBase:SPAC21E11.03c)	

PomBase	SPAC664.10	klp2		GO:0035371	PMID:24039245	IDA		C	minus end-directed kinesin-14, Klp2		protein	taxon:4896	20131111	PomBase	localization_dependent_on(PomBase:SPAC18G6.15)	

PomBase	SPAC664.10	klp2		GO:0036449	PMID:24039245	IDA		C	minus end-directed kinesin-14, Klp2		protein	taxon:4896	20131111	PomBase	localization_dependent_on(PomBase:SPAC18G6.15)	

PomBase	SPAC1D4.11c	lkh1		GO:0005634	PMID:21745468	IMP		C	dual specificity protein kinase Lkh1	kic1	protein	taxon:4896	20110805	PomBase	dependent_on(PomBase:SPAC1D4.11c)	

PomBase	SPBC106.10	pka1		GO:0005737	PMID:18621924	IMP		C	cAMP-dependent protein kinase catalytic subunit Pka1	sam7|sam6|sam5|sam1|git6|tpk	protein	taxon:4896	20111005	PomBase	dependent_on(PomBase:SPAC8C9.03),exists_during(GO:0009651)	

PomBase	SPBC106.10	pka1		GO:0005737	PMID:18621924	IMP		C	cAMP-dependent protein kinase catalytic subunit Pka1	sam7|sam6|sam5|sam1|git6|tpk	protein	taxon:4896	20111005	PomBase	dependent_on(PomBase:SPAC8C9.03),exists_during(GO:0042149)	

Original comment by: ValWood

**Comment by ValWood** [comment]
fixed
we no longer have any 'localization_dependent_on'  extensions
