### ISSUE TITLE
sort pombe/cerevisia ortholog table (gene fusions)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#419]
chromosome1.contig:FT                   YDR267C; qualifier=SPAC806.02c,C-term; date=19700101"
chromosome1.contig:FT                   YIL003W; qualifier=SPAC806.02c,N-term; date=19700101"
chromosome1.contig:FT                   /GO="aspect=C; term=mitochondrion; qualifier=C-term;
chromosome1.contig:FT                   /GO="aspect=C; term=mitochondrion; qualifier=N-term;
chromosome1.contig:FT                   /GO="aspect=F; term=hydrolase activity; qualifier=N-term;
chromosome1.contig:FT                   qualifier=C-term; GOid=GO:0008808; evidence=ISS;
chromosome1.contig:FT                   and biogenesis; qualifier=C-term; GOid=GO:0007006;
chromosome1.contig:FT                   YKR070W; qualifier=SPAC22A12.08c,N_term; date=19700101"
chromosome1.contig:FT                   YDL142C; qualifier=SPAC22A12.08c,C_term; date=19700101"
chromosome1.contig:FT                   YPL132W; qualifier=SPAC1420.04c,C-term; date=19700101"
chromosome1.contig:FT                   YKL155C; qualifier=SPAC1420.04c,N-term; date=19700101"
chromosome1.contig:FT                   YJR142W; qualifier=SPAC6F12.05c,N-term; date=19700101"
chromosome1.contig:FT                   YOR143C; qualifier=SPAC6F12.05c,C-term; date=19700101"
chromosome1.contig:FT                   next round of sequencing updates; qualifier=pending;
chromosome1.contig:FT                   YOR074C qualifier=SPAC15E1.04,C-term; date=19700101"
chromosome1.contig:FT                   YPL132W; qualifier=SPAC19B12.13,C-term; date=19700101"
chromosome1.contig:FT                   YKL155C; qualifier=SPAC19B12.13,N-term; date=19700101"
chromosome1.contig:FT                   YER141W; qualifier=SPAC22E12.10c,N-term; date=19700101"
chromosome1.contig:FT                   YPL252C; qualifier=SPAC22E12.10c,C-term; date=19700101"
chromosome2.contig:FT                   YGR036C; qualifier=SPBC530.12c,C-term; date=19700101"
chromosome2.contig:FT                   qualifier=SPBC530.12c,N-term; date=20101012"
chromosome2.contig:FT                   YCL030C; qualifier=YCL030C(N-term); date=19700101"
chromosome2.contig:FT                   YCL030C; qualifier=YCL030C(C-term); date=19700101"
chromosome2.contig:FT                   YJL200C; qualifier=SPBP4H10.15,N-term; date=19700101"
chromosome2.contig:FT                   YJL096W; qualifier=SPBP4H10.15,C-term; date=19700101"
chromosome2.contig:FT                   qualifier=HGMP:GART,N-term; date=20130815"
chromosome2.contig:FT                   YDR419W; qualifier=SPBC16A3.11,N-term; date=19700101"
chromosome2.contig:FT                   YFR027W; qualifier=SPBC16A3.11,C-term; date=19700101"
chromosome3.contig:FT                   YDR302W; qualifier=SPCC1450.15,C-term; date=19700101"
chromosome3.contig:FT                   YBR265W; qualifier=SPCC1450.15,N-term; date=19700101"
chromosome3.contig:FT                   qualifier=SPCC1223.08c,N-term; date=20130801"
chromosome3.contig:FT                   YOR236W; qualifier=SPCC1223.08c,C-term; date=20130801"
chromosome3.contig:FT                   qualifier=HGMP:GART,C-term; date=20130815"

Original comment by: ValWood

**Comment by ValWood** [comment]
transferred to 
https://github.com/pombase/curation/issues/810
