### ISSUE TITLE
check consistent function terms used for transcription associated complexes:

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#436]
check consistent function terms used for transcription associated complexes
mediator
- [x] TFIID
- [x] TFIIIC
- [x] CCAAT-binding factor complex
- [x] TFIIF
- [x] TFIIIA
- [x] TFIIH

Original comment by: ValWood

**Comment by ValWood** [comment]
We are largely internally consistent,
except that these

SPBP16F5.02	mcs2	TFIIH complex cyclin Mcs2
SPBC19F8.07	mcs6	TFIIH associated cyclin-dependent protein kinase Mcs6	
SPBC776.18c	pmh1	transcription factor TFIIK complex complex ubiquitin.....Pmh1	
SPCC5E4.03c	taf5	SAGA .../TATA-binding protein associated factor/TFIID subunit Taf5	
SPCC16C4.18c	taf6	histone H4-like TAF Taf6, SAGA complex subunit	
SPBC32F12.15	tfb5	transcription factor TFIIH complex subunit Tfb5 (predicted)	
SPCC1494.09c	tfb6	holo TFIIH complex subunit Tfb6	

don't have the  function term
GO:0000991 - transcription factor activity, core RNA polymerase II binding
which other complex members have. Check if ISO is appropriate...
