### ISSUE TITLE
specific cyclin cdk complexes

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#447]
request specific cyclin /cdk complexes
https://sourceforge.net/p/pombase/chado/366/

Original comment by: ValWood

**Comment by ValWood** [comment]
when specific cdck/cyclin complexes are defined

"binds"
annotations for
• SPAC29B12.03 protein complex binding
• SPBC1734.14c
should be done with 
protein complex binding GO term

**Comment by ValWood** [comment]
also in GO there are 2 terms for GO:0031387 MPF complex

....has been discussed that  it would be better to arrange these complexes differently (by function rather than cyclin family). I don't want to bring this up right now or it will be assigned to me.

**Comment by ValWood** [comment]
Duplicate:
https://github.com/pombase/curation/issues/2022
