### ISSUE TITLE
check GO_REFs

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#449]
if you're adding GO annotations with ISS or ISO, the reference to use is GO_REF:0000024 (see http://www.geneontology.org/cgi-bin/references.cgi). IC annotations should cite the same reference as you use for the annotation to the "from" GOID

(Maybe we can get a chado check for this though?)

Original comment by: ValWood

**Comment by mah11** [comment]
use GO_REF:0000111 for IC from ISS

**Comment by ValWood** [comment]
Can we close as this is an ongoing task?

**Comment by mah11** [comment]
Not yet. I have a large overhaul nearly done, and will close this when it's finished.

**Comment by mah11** [comment]
finally done!

**Comment by ValWood** [comment]
Woo Hoo
