### ISSUE TITLE
dis1 and other noname(WT) annotations

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#46]
Are these annotations correct?
http://curation.pombase.org/pombe/curs/3932fba28567af8a/ro/
I thought it was another example of not displaying the correct allele description

See the dis1 page, this shows as unnamed(wildtype). Should there be an expression level or something too?
Do you see what I mean? Is this in an external file?

val

Original comment by: ValWood

**Comment by Antonialock** [comment]
well dis1 looks ok now so I guess this has been resolved by Kim or Mark
