### ISSUE TITLE
cdc3-6 unknown/ waiting for multigene phenotypes

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#472]
cdc3-6 unknown 

Two temperature- sensitive alleles of cdc3, cdc3-6 and cdc3-124, were identified during the initial isolation of cdc mutants in S. pombe and they exhibited strikingly different pheno- types (Nurse et al. 1976) (Fig. 1). When placed at the restrictive temperature of 360 C for 6 h, cdc3-124 mutant cells became elongated and accumulated up to eight nuclei. In contrast, cdc3-6 mutant cells remained shorter and more ‘‘dumbbell’’ shaped, and the vast majority of cells accumulated only two nuclei. Nucleotide sequence analysis of the profilin gene from the cdc3-6 strain re- vealed the same single nucleotide change (data not shown) that had been detected previously in the cdc3- 124 strain (Balasubramanian et al. 1994), raising the possibility that a second mutation in another gene was present in one of the strains. To test this possibility, both strains were back-crossed to wild-type cells and tetrads were dissected. The cdc3-124 backcross segregated two phenotypes, wild-type and cdc), in a 2:2 ratio. However, the cdc3-6 backcross yielded four different phenotypes: wild-type, short dumbbell shaped cdc), long dumbbell shaped cdc) and a watermelon-shaped, temperature- sensitive lethal. The 31 tetrads dissected in this latter backcross yielded 7 parental ditypes, 22 tetratypes, and 2 nonparental ditypes. All four spores in the nonparental ditypes failed to form colonies at 360 C. These data in- dicated that two recessive temperature-sensitive muta- tions existed in cdc3-6: cdc3-124 and wat1-1.

soo....when we can curate genetic interactions we need to convert any phenotypes which use cdc3-6 to genetic interactions  cdc3-124/wat1-1 (and delete the single gene allele unknown designation)

Original comment by: ValWood

**Comment by mah11** [comment]
done
