### ISSUE TITLE
GO:0000979 - RNA polymerase II core promoter sequence-specific DNA binding 

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#474]
GO:0000979 - RNA polymerase II core promoter sequence-specific DNA binding) edit

is for things which bind to the core promoter like tbp binding protein (& polII although this is not annotated....probably should be with ISO)

but it has annotations for 2 sequence-specific DNA binding TFs (loz1 and pap1)

these should be annotated to

GO:0000978	RNA polymerase II core promoter proximal region sequence-specific DNA binding
(which is a region close to the core promoter)

so these 2 need updating

php2 has both GO:0000979 & GO:0000978 so one of these is wrong, not sure which, it depends whether CCAAT is part of core promoter or not?

v

Original comment by: ValWood

**Comment by ValWood** [comment]
I think this is OK...
