### ISSUE TITLE
requires sequence feature

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#476]
SPAC13D6.04c	IPI	requires_sequence_feature(Pfam:PF00651)
SPCC962.02c	IPI	requires_sequence_feature(Pfam:PF00653)
SPCC5E4.03c	IPI	requires_sequence_feature(Pfam:PF04494)
SPAC16E8.09	IPI	requires_sequence_feature(Pfam:PF00564)
SPBC25B2.06c	IPI	requires_sequence_feature(Pfam:PF00651)
SPCC962.02c	IPI	requires_sequence_feature(Pfam:PF00653)
SPBC336.04	IPI	requires_sequence_feature(Pfam:PF14260)
SPAC637.13c	ISO	requires_sequence_feature(Pfam:PF00169)
SPBC32H8.10	IPI	requires_sequence_feature(Pfam:PF00069)
SPAC1952.13	IPI	requires_sequence_feature(Pfam:PF04571)
SPAC22H10.07	IPI	requires_sequence_feature(Pfam:PF00787)
SPBC21D10.12	IPI	requires_sequence_feature(Pfam:PF03114)
SPCC962.02c	IPI	requires_sequence_feature(Pfam:PF00653)
SPAC1952.13	IPI	requires_sequence_feature(Pfam:PF04571)
SPBC21D10.12	IPI	requires_sequence_feature(Pfam:PF03114)
SPAC22H10.07	IPI	requires_sequence_feature(Pfam:PF00018)
SPBC28E12.03	IMP	requires_sequence_feature(Pfam:PF00620)
SPCC330.11	IPI	requires_sequence_feature(Pfam:PF00651)
SPCC18B5.11c	IPI	requires_sequence_feature(Pfam:PF00069)
SPCC550.13	IMP	requires_sequence_feature(Pfam:PF07535)
SPAC1952.13	IPI	requires_sequence_feature(Pfam:PF04571)
SPAC1565.04c	IPI	requires_sequence_feature(Pfam:PF07647)
SPCC5E4.03c	IPI	requires_sequence_feature(Pfam:PF00400)
SPAC23C11.16	IPI	requires_sequence_feature(Pfam:PF00659)
SPBC1778.02	IPI	requires_sequence_feature(Pfam:PF11626)
SPBC6B1.08c	IMP	requires_sequence_feature(Pfam:PF10637)
SPBC6B1.08c	IPI	happens_during(GO:0071456),requires_sequence_feature(Pfam:PF10637)
SPBC6B1.08c	IMP	happens_during(GO:0071456),requires_sequence_feature(Pfam:PF13640)
SPBC32C12.02	IMP	has_regulation_target(PomBase:SPAC27D7.03c),requires_sequence_feature(SO:0001858)
SPAC20G4.08	IPI	requires_sequence_feature(SO:0001080)
SPBP8B7.19	IPI	requires_sequence_feature(Pfam:PF00557)
SPBP8B7.19	IPI	requires_sequence_feature(Pfam:PF00557)
SPBP8B7.19	IPI	requires_sequence_feature(Pfam:PF00557)
SPBP8B7.19	IPI	requires_sequence_feature(Pfam:PF00557)
SPBP8B7.19	IPI	requires_sequence_feature(Pfam:PF00557)

I am going to deal with  (delete)

SPBC32C12.02	IMP	has_regulation_target(PomBase:SPAC27D7.03c),requires_sequence_feature(SO:0001858)

now because this is implicit from the DNA binding/transcription factor activity combination (and we don't usually do this).

The others we can check that the relevant FYPO annotation is in place and delete.

Original comment by: ValWood

**Comment by ValWood** [comment]
single annotation remaining
 1 | requires_sequence_feature | gene_ex

QUESTION, is requites_sequence _feature allowed for 'gene expression' (I don't know what it would mean in this context?

Is not documented here:
http://curation.pombase.org/pombase-trac/wiki/CapturingGeneExpression

**Comment by ValWood** [comment]
mes1

FT                   /controlled_curation="term=misc, meiosis-specific
FT                   splicing;
FT                   annotation_extension=requires_sequence_feature(SO:0000204);
FT                   db_xref=PMID:11459187; date=20060106"

so it isn't a gene expression annotation, its actually a "misc" annotation

probably needs a canto ticket....
and decision, do we allow extensions with misc?

**Comment by ValWood** [comment]
This realtion is all gone......
