### ISSUE TITLE
misfolded protein/ vs unfolded protein response

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#478]
GO:0071218 cellular response to misfolded protein IMP Fernandez F et al. (1996) 6
GO:0030968 endoplasmic reticulum unfolded protein response IMP Frost A et al. (2012) 9

These annotations should probably be reviewed.
Mainly I see gpt1 is annotated to signal transduction, that seems wrong?
Not sure but good to check these I suspect they are mixed up...

Original comment by: ValWood

**Comment by ValWood** [comment]
I looked at this as this ticket is only really to check the ISS's as I haven't done this for this process for years, and they always get a bit mixed up.

I *think* that we probably need to ISS 
yos9,slt2,mnl1 dcr1(our gid8) to "er unfolded protein response.

However, need to check  these....as SGD have rot1 to this term and I don't think that one is correct (have mailed them).

Also, can't detect orthologs for hac1/uli1/opi1 but I think these are known to be missing

**Comment by ValWood** [comment]
Will wait to hear back from SGD before I update

**Comment by ValWood** [comment]
SGD have updated the ones I queried, and I fixed those as tey came back. Only need to do 
yos9,slt2,mnl1 dcr1(our gid8), hrd1 to "er unfolded protein response.

**Comment by ValWood** [comment]
endoplasmic reticulum unfolded protein response  GO:0030968

**Comment by ValWood** [comment]
DONE
