### ISSUE TITLE
mrpl* gene names

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#483]
I had a query this week about naming a gene with a 4 letter name quoting these as an e.g, but GNC have over ruled this previously.

In this case, to prevent speculation we should instate mrp* primary name for all mrpl* gene names (provided they are not already taken)

Original comment by: ValWood

**Comment by mah11** [comment]
note added to naming guidelines ages ago

is there anything else to do for this? kinda looks like not ...
