### ISSUE TITLE
browse / disease ontology

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#49]
map these annotations to one of the disease ontologies so that we can do more sensible querying for disease "classes" like cancer associates, neurological disorders, metabolic diseases etc.)

Original comment by: ValWood

**Comment by ValWood** [comment]
resurrect when we can handle ontology subsets and include in chado

**Comment by ValWood** [comment]
> Then Mark needs to include the terms we have used in the search. I haven't thought about how this all needs to happen, because we probably don't want to include every term in DO, only the subset of the ontology we have annotated.....

This doesn't need to happen. The query builder ignores unannotated terms anyway. I wonder if we do need  ontology_subsets at all.

We do need to decide how/where we will collect these annotations longer term when we move from Artemis. We could have an Admin only option in Canto. However, I  would like to move to more automation for this. 

A while ago I looked into  the possibility of getting all disease associated genes from OMIM and comparing to our ortholog table to see if we had many missing. Unfortunately I could  not establish the difference between a file which gave me definitively mapped   genes and those which were  only 'implicated', despite a number of enquiries to the helpdesk. I put on hold at this point.

I'm now wondering if we really only need a simple flat file to  load for this and treat it as 'external data'.  At least, this needs to be an option for the autogenerated route. Will discuss with Kim.

If we do decide to do this, preparing the import file would be a nice perl training exercise for you @Antonialock

**Comment by mah11** [comment]
>> Then Mark needs to include the terms we have used in the search. ...
> 
> This doesn't need to happen. The query builder ignores unannotated terms anyway.

I think my comment dates back to before the search ignored unused terms ;)

**Comment by ValWood** [comment]
I thought it was my comment pre-migration. I was just  chatting to myself on github...

**Comment by ValWood** [comment]
Yeah I just found my notes...

OMIM 24369 diseases 15373 genes
which implies that over half human genes are associated with diseases. I think this number must include 
'genes in candidate regions' etc, not genes known to be disease causative...maybe not but it seems high?

I could not work out how to get a list of  human genes definitively associated with diseases. It should be easier....if anyone has any ideas..... Once we have this list it is trivial to see if we have a lot of disease associations missing by comparing to the human ortholog table (need HGNC IDs)

**Comment by Antonialock** [comment]
check what we still need to map

**Comment by Antonialock** [comment]
map to DO and HGNC IDs

**Comment by ValWood** [comment]
continue in 
https://github.com/pombase/curation/issues/2130
