### ISSUE TITLE
conjugation without glucose starvation

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#492]
from email
In the meantime, could you prioritise  a few papers to make all of the git genes annotated
 to FYPO conjugation without glucose starvation
http://www.pombase.org/spombe/related/FYPO:0001864

Original comment by: Antonialock

**Comment by Antonialock** [comment]
Charlies main assay is to look at gluconeogenesis genes so the git genes are annotated to the "abnormal negative regulation of transcription by glucose" term
