### ISSUE TITLE
cell separation tidy up  dependent on GO ontology-requests/11414/

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#506]
When GO put the new terms in place
https://sourceforge.net/p/geneontology/ontology-requests/11414/
some annotations should automatically migrate under the new term (because the primary and secondary septum dissolution will be placed under here).

Then need to assess the remainder (only 28 annotation in total), but most look as though they will migrate. The annotation looks really nice actually, it is 
i) cell wall degrading enzymes, 
ii) exocyst complex (how they get there)
iii) GTPase pathway and some other signalling (regulating exocyst)
iv) transcription factors, regulating transcription of the degrading enzymes.

There are also a couple of uniquitin pathway components, but these look like general cytokinetic defects rather than cell separation defects. They call it 'cell separation' so our annotation is unsurprising, but  cytokinesis seems to have failed here.
Also ditto the septins.

Original comment by: ValWood

**Comment by ValWood** [comment]
All looks OK!
