### ISSUE TITLE
residues on MF terms

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#524]
protein binding	PMID:11805113	molecular_function	444|region
protein binding	PMID:19720063	molecular_function	107-200
protein binding	PMID:23133674	molecular_function	A311-A370
protein binding	PMID:24774534	molecular_function	463
protein binding	PMID:24774534	molecular_function	53112
protein binding	PMID:23133674	molecular_function	A457-A512
protein binding	PMID:23966468	molecular_function	329-419
protein binding	PMID:23966468	molecular_function	9571101

extrinsic component of mitochondrial outer membrane	PMID:21856157	cellular_component	I136-P400

F-box protein	PMID:17016471	PomBase family or domain	C172-C214

(we can wait for these to show in the logs as we don't know which gene product)

Original comment by: ValWood

**Comment by ValWood** [comment]
I think I can close this as these will be reported in the logs via 
https://github.com/pombase/canto/issues/985
and fixed
