### ISSUE TITLE
requires_sequence_feature to update from Artemis embl files

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#537]
These should be replaceable with phenotype annotations.

: failed to add annotation extension to SPCC550.13.1 <-> cellular response to DNA damage stimulus: requires_sequence_feature() not allowed for biological_process
: failed to add annotation extension to SPAC13D6.04c.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPBC28E12.03.1 <-> regulation of cell diameter: requires_sequence_feature() not allowed for biological_process
: failed to add annotation extension to SPAC637.13c.1 <-> phosphatidylinositol binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPBC32H8.10.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPAC1952.13.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPCC18B5.11c.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPBC336.04.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPCC962.02c.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPCC330.11.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPAC1952.13.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPCC5E4.03c.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPCC962.02c.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPAC22H10.07.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPBC21D10.12.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPBC25B2.06c.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPCC5E4.03c.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPAC1952.13.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPBC21D10.12.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPAC1565.04c.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function
: failed to add annotation extension to SPCC962.02c.1 <-> protein binding: requires_sequence_feature() not allowed for molecular_function

Original comment by: mah11

**Comment by mah11** [comment]
out of date - there are none in the current .contig files, nor in the GAF from the latest build.
3
