### ISSUE TITLE
A heads up GO:0031134 sister chromatid biorientation

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#545]
will be appearing in the GO terms not to annotate file
GO:0031134 sister chromatid biorientation
based on
https://sourceforge.net/p/geneontology/ontology-requests/11412/
Feel free to take this ticket and fix when the restriction (an the new terms) appear
(need to check  these as some might be meiotic)

Original comment by: ValWood

**Comment by ValWood** [comment]
closing as these are in my log file and I have been fixing them, the new GO terms are now in place
