### ISSUE TITLE
check/fix use of | in residue= (Artemis flat files)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#549]
chromosome1.contig:FT                   mapping; residue=R34|E74; db_xref=PMID:14528010;
chromosome1.contig:FT                   site; residue=M438-K455|region; db_xref=PMID:19606215;
chromosome1.contig:FT                   /GO="aspect=F; term=protein binding; residue=444|region;
chromosome1.contig:FT                   residue=L55|L32; db_xref=PMID:20444689; evidence=IDA;
chromosome2.contig:FT                   residue=99|108; evidence=IDA; db_xref=PMID:12943532;
chromosome2.contig:FT                   residue=K4|K9; cv=pt_mod; date=20100311"
chromosome2.contig:FT                   residue=CTD,S2|CTD,S5; cv=pt_mod; evidence=IDA;
chromosome2.contig:FT                   residue=S13|S19; cv=pt_mod; db_xref=PMID:12135491;
chromosome2.contig:FT                   residue=K4|K9; cv=pt_mod; date=20100311"
chromosome3.contig:FT                   residue=S17-L18|R45-D46; db_xref=PMID:11115118;
chromosome3.contig:FT                   site; residue=R179-N180|R231-D232; db_xref=PMID:15329725;
chromosome3.contig:FT                   db_xref=PMID:19041767; residue=S1024|T1028;
chromosome3.contig:FT                   residue=C48|C169; db_xref=PMID:17409354; cv=pt_mod;

Original comment by: ValWood

**Comment by mah11** [comment]
fixed for a chado ticket recently
