### ISSUE TITLE
follow on from new gene specific db_xrefs (Documentation and announcement)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#551]
We can now make gene specific db_xrefs from specific gene pages 

implemented in Chado https://sourceforge.net/p/pombase/chado/436/
display will follow https://www.ebi.ac.uk/panda/jira/browse/PB-2215
migration of existing annotation will follow  https://sourceforge.net/p/pombase/curation-tasks/563/

Syntax
/controlled_curation="term=external_link, description; db_xref=GEO:GSE57040"
where
description= description of the link which will appear on the gene page
Current allowed list is:
deletion mutant expression profiling
WT overexpression expression profiling
genome-wide localization

the accession will usually be of the form GEO:GSE57040 or ArrayExpress:E-MTAB-2543

To do, 
1. Add syntax to curator documentation and list of allowed 'types'
Q where should the  list of allowed descriptions be maintained?
1. check that these are the correct prefixes in the DBxrefs file (GEO and ArrayExpress is that correct?)
2. Let uses know that they can submit gene specific link outs (maybe a submission form for this?, initially just document the  requirements in the FAQ  (gene, description (from selection or suggest new, DB:ACC) and ask to submit to help desk)

Original comment by: ValWood

**Comment by ValWood** [comment]
Discuss at next curator meeting, or next call, unless anyone knows what to do?????

**Comment by mah11** [comment]
From the comment history, it looks like when we left it the next step was:

- Ask Kim if we can put more than one dbxref on an external_link annotation in Artemis, e.g. using "db_xref=GEO:GSE57040|PMID:1111111".

If that's been asked, someone should put the answer here. Then we move on to figuring out what we want on the gene pages, but I think that may depend on the answer to the multi-dbxref question.

**Comment by kimrutherford** [comment]
> Ask Kim if we can put more than one dbxref on an external_link annotation

That could be done.  It's possible to have secondary dbxrefs in Chado.
