### ISSUE TITLE
curators discuss: (ccanto relations shown) septation following abnormal chromosome segregation

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#554]
from septation following abnormal chromosome segregation
you get the term suggestions
inviable mononucleate monoseptate vegetative cell
septation following abnormal chromosome segregation, with anucleate cell formation

from septation following abnormal chromosome segregation, with anucleate cell formation
you get
    septation following abnormal chromosome segregation, with binucleate cell formation during cellular response to hydroxyurea
    septation following abnormal chromosome segregation, with binucleate cell formation during cellular response to salt stress

but shouldn't you also get
inviable mononucleate monoseptate vegetative cell?

Also shouldn't 
elongated mononucleate monoseptate vegetative cell 
be here too?

Original comment by: Antonialock

**Comment by ValWood** [comment]
might be fixed, can you close if it is. If not tag for discussion at next curator meeting
v

**Comment by mah11** [comment]
Let's close - this has a long and confusing comment history, and we can open new tickets if we spot any problems with what's in FYPO or how Canto displays it.
