### ISSUE TITLE
review session  ams2 annotation

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#557]
Hi,

should this session have more phenotypes (the ones the GO terms were derived from?)

http://curation.pombase.org/pombe/curs/440ff0786082ec49/ro/

v

Original comment by: ValWood

**Comment by ValWood** [comment]
This is also about the paper you are reading, can you close this one at the same time?

**Comment by ValWood** [comment]
Oh but probably a different paper?

**Comment by Antonialock** [comment]
different paper..

**Comment by Antonialock** [comment]
not sure what happened to those phenotypes. done now.
