### ISSUE TITLE
possible pruning of BioGRID datasets

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#558]
These are the genes which most likely have a lot of false positives:

tea1 Snaith/Sawin PMID: 21652630 (247)

These seem to be functionally related and are probably largely OK
~pir2 Egan/Moazed      |   (282) might be ok~
~red1  Egan/Moazed |  266~
~mtl1 Egan/Moazed   |   312~
~red5    Egan/Moazed  |   178~

appears to be fixed/deleted
- [x] sog2 Sipak/Gregan     |   154

cbf11    Pancanaldi  |   299
cid14   |   147 filter ribosomals & tifs from Zhang paper 

epe1 Wang/Jai     |   157
nak1     |   135  lots of ribosomals
clp1 Chen/Gould    |   159 looks ok, quite functionally cohesive
paa1    Bernal/Daga Singh/Gould/Balasbramanian |   164

I'll report the above to BIOGRID after checking with the authors. Some look OK, but some include a lit of proteins which are presnet in over >1000,000 copies per cell and not functionally related to the process/complex under study.

REPORTED TO BIOGRID
- [x] hhp2 Johnson/Gould  hhp2     |   844 reported
- [x] hhp1  Johnson/Gould |  1023  reported
  waiting to hear back on these

Original comment by: ValWood

**Comment by ValWood** [comment]
Will raise priority if folks moan...

**Comment by ValWood** [comment]
hhp1 and hhp2 look OK now.

check
 - [ ] pir2 Egan/Moazed | (282) might be ok
 - [ ] cbf11 Pancanaldi | 299
- [ ] red1 Egan/Moazed | 266
- [ ]  mtl1 Egan/Moazed | 312
- [ ] cid14 | 147 filter ribosomals & tifs from Zhang paper 
- [ ] sog2 Sipak/Gregan | 154
- [ ] epe1 Wang/Jai | 157
- [ ] nak1 | 135 lots of ribosomals
- [ ] clp1 Chen/Gould | 159 looks ok, quite functionally cohesive
- [ ] paa1 Bernal/Daga Singh/Gould/Balasbramanian | 164
- [ ] red5 Egan/Moazed | 178

**Comment by ValWood** [comment]
Closing this. We can deal with any other datasets as uses or authors complain. The most offending ones are now sorted.
