### ISSUE TITLE
FYPO:0000266 search results query/ sensitive to DNA damaging agents

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#560]
FYPO_ID(FYPO:0000266 - sensitive to DNA damaging agents) is only giving 7 results.
Is that a  Query issue or a paerntage issue?

val

Original comment by: ValWood

**Comment by ValWood** [comment]
It would be nice to get this to infer if it could be done by asking CHEBI to do something. Is that possible?

**Comment by mah11** [comment]
ChEBI has added more role links as we requested a while back (see https://sourceforge.net/p/chebi/annotation-issues/86/). What remains beyond the scope of our current practices is to use the role links somehow. That's probably more of a question for Chris et al., and may turn out to take quite a bit of time to implement (especially counting any time required for me to get my head round it, and learn how to use tools to actually do it).

**Comment by ValWood** [comment]
@mah11 is this "help wanted" or "waiting for feedback" ?

**Comment by mah11** [comment]
bit of both, really

tho if you want to bring this back up the priority list, I can try to hack it for now

**Comment by ValWood** [comment]
nope, no hurry, plenty of other stuff...

**Comment by mah11** [comment]
I have investigated and found that the hack I had in mind would work, so I can deploy it if you want. If I do, I'll do a release with no other FYPO changes, and have you test it before I do any more ontology edits, in case you want to roll it back.

**Comment by ValWood** [comment]
whatever makes sense to you. Might be nice to be able to query on/ enrich over...

**Comment by mah11** [comment]
OK, I've done a hacked-up FYPO release. Check what appears under FYPO:0000266 ! sensitive to DNA damaging agents in Canto from tomorrow, and close this if you like it.

**Comment by ValWood** [comment]
sensitive to DNA damaging agents

Result: 928 genes (up from 9), so something happened.

As an aside we probably shouldn't use CHEBI roles more generally..... they are causing bit issues in GO, you have likely seen....
