### ISSUE TITLE
annotation check, elongated/swollen bgs1 PMID:9401022

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#565]
bgs1 has
	elongated cell			714
Extensions	Evidence	Allele	Expression	Condition	Reference		Microscopy	cps1-12		liquid culture, standard temperature, glucose MM	Ishiguro J et al. (1997)		Microscopy	cps1-12		liquid culture, + cyclosporin A, standard temperature, glucose MM	Ishiguro J et al. (1997) 	

and
	swollen vegetative cell			49
Extensions	Evidence	Allele	Expression	Condition	Reference		Microscopy	cps1-12		+ Ca ions, high temperature, YES	Ishiguro J et al. (1997)		Microscopy	cps1-12		high temperature, agar plates, YES	Ishiguro J et al. (1997)		Microscopy	cps1-12		liquid culture, + cyclosporin A, standard temperature, glucose MM	Ishiguro J et al. (1997) 	

for the same allele/conditions.

I'm pretty sure these cells are simultaneously swollen and elongated, so probably a compound term should be used here.

Original comment by: ValWood

**Comment by ValWood** [comment]
Is OK
