### ISSUE TITLE
annotation check, dis genes

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#571]
The paper I am reading implies that this paper the process is "separation' (more specific than segregation). 

Title of paper seems to support this
PMID:3409871
Title	Cold-sensitive and caffeine-supersensitive mutants of the Schizosaccharomyces pombe dis genes implicated in sister chromatid separation during mitosis.
Authors	Ohkura H, Adachi Y, Kinoshita N, Niwa O, Toda T, Yanagida M

could you check and move down if appropriate,

tks

val

Original comment by: ValWood

**Comment by Antonialock** [comment]
hmm, they don't really show that it is separation, but on the other hand I can't think of anything else that could cause this? I changed it to separation.
