### ISSUE TITLE
bioGRID corrections V?-> V 49?

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#582]
I fixed the ones allocated to me. Here are the resolutions:

fixed deleted PMID:15647375	Val
fixed phenotypic supression -> dosage rescue PMID:16874521	Val
fixed switched directionality PMID:21289066	Jia/Val
fixed deleted PMID:22065639	Gould/Val visually there seems to be no difference
fixed deleted PMID:23091701	Pluskal/Val
fixed ac-luminesence -> western PMID:23389634	Shiosaki/Val
fixed PMID:24006488	Ayte/Val
fixed deleted PMID:24006493	Tanaka/Val
already fixed PMID:24081329	Bachand/Val (possibly fixed?)
fixed  copurification-> affinity capture western PMID:24554432	Martin/ Val
fixed dosage rescue- phenotypic supression PMID:24710126	Matsumoto/Val
fixed phenotypic supression -> synthetic growth defect PMID:24798735	Wu/Val
fixed 3 (different reasoons) PMID:24876389	Akio Nakashima/ Val
fixed (deleted as incorrect directionality and experimental system) PMID:24943839	King/Val
fixed co-purification->reconstituted complex AND phenotypic suppression->synthetic rescue phenotypic supression-> synthetic growth defect PMID:24963130 	Megan King/ Val
fixed co-purification-> reconstituted complex PMID:25165823	Yasuhiro Tsutsui/Val
fixed PMID:3428262phenotypic enhancement->synthetic rescue Val

NOT FIXED
kept, plo1 is in fig s3&s4  PMID:22809626	Jin/Val  plo1 single mutant not shown, Fig 4

PMID:24920823	Rachfall/Val
I did not understand this one. I changed the direction as suggested, but I don’t see the problem with Antonia’s origin annotation (synthetic growth defect has no directionality)

I could not think of any suggestions  to improve annotation. Basically the problem seems to be that some evidence codes could be considered a 'refinement' of another code, so if you see one that fits you use it.
We almost need to be able to prompt to say "but if its this, you need to use this more specific code"
OR "do not use evidence code x for y" 

Original comment by: ValWood

**Comment by ValWood** [comment]
Not sure where we are up to here, but I think everyone fixed their last batch and sent queries to BioGRID.
Did we all hear back and resolve any inconsistencies?

**Comment by Antonialock** [comment]
Yeah I think this can be resolved until next share

**Comment by mah11** [comment]
Yeah, I've dealt with my share by email with the BioGRID curators rather than tickets.

**Comment by ValWood** [comment]
fixed
