### ISSUE TITLE
PomBase ftp site review

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#583]
Go through the PomBase ftp site launch pages and check that the links identify the expected datasets.

M's suggested options:

* Reorganize the static web pages to mirror the current ftp directory organization; or
* Reorganize the ftp directories; or
* Leave everything basically as is, perhaps with a little bit more explanatory text on the web pages (including a note to the effect that some web pages point to the same ftp directories because of what's where).

Also check that: 
The launch page test is explanatory enough 
All README's are in place
All archives are correct.

Original comment by: ValWood

**Comment by mah11** [comment]
Did you want to reorganize either the static pages or the FTP directory structure (options 1 and 2 from the original summary)? If so, which?

I have no preference; just need to know how to proceed.

**Comment by ValWood** [comment]
I don't mind. If you don't want to decide we can  punt this and take a look during curator meeting. If so just flag it as a discussion thingy...it isn't urgent. I don't think people are particularly struggling to locate things.

**Comment by mah11** [comment]
OK, I've given both the web pages and ftp site a once-over, and added some notes to the main Datasets web page to explain what's there. It basically makes sense, so if people aren't having problems there's no great need to change things.

I suggest we leave it at that, and open new tickets on Jira if and when we identify anything that can be improved.

**Comment by ValWood** [comment]
Good plan, I think some things had probably been sorted since this ticket was spawned
