### ISSUE TITLE
Additions to the "GO terms not to annotate" file

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#592]
Add broad complex terms
Terms from GOA load filters

Original comment by: ValWood

**Comment by ValWood** [comment]
added 111 Terms from GOA load filters to  "GO_terms_excluded..."
removed duplicates
tidied file
deleted a few which we are allowed to use but  the mappings were dodgy

There will be some more which will need to be deleted. I know that a few of these are too restrictive. After the next Chado update I'll check the  log file and see which other ones I need to delete.
