### ISSUE TITLE
ortholog table update

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#594]
In the S. cerevisiae/pombe ortholog table SPAC3C7.15c  (synonym) should be replaced by
SPAC25A8.03c (systematic ID)

Original comment by: ValWood

**Comment by ValWood** [comment]
Add supporing evidence for divergent orthologs
Go through my old cerevisiae ortholog table release notes and add evidences for some of the distant ortholog predictions.

**Comment by ValWood** [comment]
This is now listed with the pending updates so it won't get forgotten
http://curation.pombase.org/pombase-trac/wiki/OrthologTableUpdates

**Comment by ValWood** [comment]
other task is now in new "ortholog table" ticket
https://github.com/pombase/curation/issues/810
