### ISSUE TITLE
telomeric heterochromatin related annotation

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#596]
Should these be "nuclear subtelomeric heterochromatin"
(I think the 'telomeric heterochromatin is a GO issue as as far as I know the telomeric sequence itself (is the repetative part), isn't heterochromatic... when people say 'telomeric heterochromatin' they are really referring to the sub-telomeres)

Antonia
SPAC1783.04c.1		GO:0031933	telomeric heterochromatin	e94ce18ecdb1e796	PomBase
SPBC16D10.07c.1		GO:0031933	telomeric heterochromatin	e94ce18ecdb1e796	PomBase

Midori
SPAC664.01c.1		GO:0031933	telomeric heterochromatin	d4e73d1a93ec5860	PomBase
SPAC17H9.20.1		GO:0031933	telomeric heterochromatin	d4e73d1a93ec5860	PomBase
SPBC8D2.04.1		GO:0031933	telomeric heterochromatin	d4e73d1a93ec5860	PomBase
SPAC1834.04.1		GO:0031933	telomeric heterochromatin	d4e73d1a93ec5860	PomBase
SPBC1105.11c.1		GO:0031933	telomeric heterochromatin	d4e73d1a93ec5860	PomBase

Original comment by: ValWood

**Comment by mah11** [comment]
did the outstanding bit, just so this can be closed (you know I love closing tickets)
