### ISSUE TITLE
annotation update CRAL/TRIO family

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#597]
The "CRAL TRIO" family proteins would be better labelled as 
glycerophospholipid-transfer protein (at least I think the entire family fits this description)  which is more informative.

http://www.pombase.org/spombe/related/protein_domains/SSF52087/superfamily?interpro=IPR001251

csr102	SPAC3H8.02.1:pep	sec14 cytosolic factor family phosphatidylinositol transmembrane transporter (predicted)
looks especially wrong as the product mentions "transmembrane transport". I am not sure that this is true (I thought that these transfer proteins were just transferases).

we should check if
a) this is the case
and if not
b) if  any have a transmembrane transport annotation from any source it will need fixing

Original comment by: ValWood

**Comment by ValWood** [comment]
check after update and close

**Comment by ValWood** [comment]
fixed
