### ISSUE TITLE
query mitotic DNA repliction checkpoint pim1

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#607]
pim1 overexpression suppreses DNA replication checkpoint defects. Does that necessarily mean it is involved in replication checkpoint?
http://www.ncbi.nlm.nih.gov/pubmed?term=12135745
I think it could be just be that it is slowing the cell cycle instead of the replication checkpoint?

Thoughts?

Original comment by: ValWood

**Comment by Antonialock** [comment]
the mitotic dna replication checkpoint comes from the paper 8387358

I did this paper, and removed the annotation, there is no evidence for it.

---

but yeah, I agree that if you slow the cell cycle then the cell has more time to deal with problems. I don't really know what these genes do specifically though
