### ISSUE TITLE
ofd2 priority paper PMID: 22235339

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#610]
histone H2A dioxygenase
negative regulation of transcription

GO:0061428	negative regulation of transcription from RNA polymerase II promoter in response to hypoxia
(presumably via chromatin remodelling?)

I am adding an NAS to 
GO:0061428	negative regulation of transcription from RNA polymerase II promoter in response to hypoxia to  get this grouped for my figure....

Original comment by: ValWood

**Comment by Antonialock** [comment]
guessing this can be closed?

**Comment by ValWood** [comment]
PMID: 22235339 isn't curated though?

**Comment by mah11** [comment]
In progress. Two questions:

1. I'm a bit confused now about whether to use GO:0061428 for ofd2. In the deletion mutant, genes that are up-regulated in hypoxia behave the same as in wt, but a subset repressed genes seem to be more repressed. So would you still infer a role in "negative regulation of transcription ..." from that effect?
2. Would you annotate anything for the experiment in Figure 2C, where they made some peptides corresponding to a bit of H2A that seems to be important for whatever Ofd2 is doing to modify the histone? It could be captured as phenotypes of mutations in hta1/hta2, if we believe that the effect would be roughly the same with the whole pombe proteins. Can't think of any other sensible way to do it.

**Comment by mah11** [comment]
decision for 1: use plain old regulation

**Comment by mah11** [comment]
For now I haven't added any annotations for the mutated-histone-peptide experiment (fig 2C), but it'd be easy enough to go back and add phenotypes if we decide we want to capture the information that way. 

The rest is done. I'll leave the session for a day or two in case either of you want to have a look (or just go ahead and approve it).

**Comment by mah11** [comment]
it's been a week, so I hit the "approve" button
