### ISSUE TITLE
pho1 PMID: 3447747

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#612]
move annotations down to "transmembrane term" import across plasma membrane

Original comment by: ValWood

**Comment by Antonialock** [comment]
phenotype only

I removed it and added
phosphate-containing compound metabolic process
cellular response to phosphate starvation

but it won't be in the slim from this, what to do?

**Comment by ValWood** [comment]
I think there is enough detail here to keep "regulation of x transport"  GO terms? It definitely seems that this is the *only* interpretation for these phenotypes. Even though sometimes there is only phenotypic data, we can still make GO annotations if that is the only likely/possible interpretation of the phenotype, and it could not be an 'upstream effect'. I can't think of anything which could be upstream of transport...

**Comment by Antonialock** [comment]
you don't think it is an indirect effect from phosphate starvation?

**Comment by ValWood** [comment]
Yeah, it could be upstream of the sensor. leave it as phenotype. its OK that it doesn't slim...
The things which don't slim are basically a bunch of things we don't know much about.
