### ISSUE TITLE
after update check V54 methylgloxoxal

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#619]
methylglyoxal catabolic process to D-lactate  
-> (cellular) detoxification

Original comment by: ValWood

**Comment by Antonialock** [comment]
I presume you wanted all genes annotated to methylglyoxal catabolic process to D-lactate via S-lactoyl-glutathione to also be annotated to detoxification? I added detoxification to SPCC13B11.03c so it will get that as a slim term.

Let me know if this was not what you had in mind

**Comment by ValWood** [comment]
Yep. Can you use "cellular detoxification" instead (its new).

I think we aren't sure if all  methylglyoxal catabolic process to D-lactate is "cellular detoxification" for all organisms, though I suspect that it is....so it is possible this can eventually be linked in the ontology. For now it can be IC.

I did some "cellular detoxification" this week when I checked the slim 'fall out' after the update, so it is possibel that some of these are done already...

**Comment by Antonialock** [comment]
ok I changed the one I added to cellular detoxification
