### ISSUE TITLE
mxr1 and mxr2 annotation query

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#625]
Do you know why mrx1 & 2 are annotated to protein repair by IEA only. I'm sure ther ewas a Hidalgo paper for these genes devoted to this process (I thought we raised the term for that paper)

Original comment by: ValWood

**Comment by Antonialock** [comment]
in that paper they don't loook at protein repair (they look at the reduction of free methionine). The BP L-methionine biosynthetic process from methionine sulphoxide 
was added for this function

Also no evience for mrx2 from this paper

I also requested the term Positive regulation of removal of reactive oxygen species, seems like this is supported.

**Comment by Antonialock** [comment]
according to wikipedia 
Mxr1 can reduce both free and protein-based methionine-S-sulfoxide, whereas Mxr2 is specific for protein-based methionine-R-sulfoxide

so I can IC the protein repair

**Comment by ValWood** [comment]
Thats odd, I was sure that we had a long discussion about protein repair based on one of one of Elena's papers? But IC is fine....
can delete IC to GO:0044267	cellular protein metabolic process

**Comment by Antonialock** [comment]
where does this annotation come from? I cant see it in artemis
	cellular protein metabolic process	1447
Annotation Extension	Evidence	With/From	Reference
	IC	GO:0008113	GO_REF:0000001

**Comment by ValWood** [comment]
Ah maybe I already removed it? I thought it might be from an F-P link but I can't see it...
val

**Comment by Antonialock** [comment]
ok, I IC'd protein repair in any case

**Comment by ValWood** [comment]
They are still IEA?

**Comment by mah11** [comment]
Seems to be a filtering issue. The ICs are in the contig files and recent GAFs (checked one from earlier this week), but not in the GAF for the v30 release.

(but also see https://github.com/pombase/pombase-chado/issues/557 on filtering ...)
