### ISSUE TITLE
Solicit gene names

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#628]
After Japan.

As of V52  3686/5054 proteins have assigned primary names.

Especially ask for suggestions for the 12 (attached) which are published but un named (otherwise we will name them sensibly)

With a GNC reminder, and preregister your gene names blah blah...

We will do this soon after Japan as people will be more 'engaged' and community  minded, hopefully.

Original comment by: ValWood

**Comment by Antonialock** [comment]
You need to re-post the list of 12 genes

**Comment by ValWood** [comment]
As of V52  3719/5054 proteins have assigned primary names.

**Comment by ValWood** [comment]
SPAC1486.01	manganese superoxide dismutase
SPAC1751.03	translation initiation factor eIF3m	
SPAC17A2.14		CorA family magnesium ion transmembrane transporter
SPAC25G10.08	translation initiation factor eIF3b (p84)	protein_coding	I	1	
SPAC29A4.02c	translation elongation factor EF-1 gamma subunit	protein_coding	I	
SPAC589.05c tRNA queuosine modification protein	
SPAPB2B4.04c	vacuolar calcium transporting P-type ATPase P2 type, Pmc1
SPBC1709.14       peptide N-glycanase	
SPBC1778.05c	human LAMTOR2 ortholog	
SPBC660.16	phosphogluconate dehydrogenase, decarboxylating

**Comment by ValWood** [comment]
another one bites the dust
