### ISSUE TITLE
Pfam update check

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#631]
re

==
Hi Val

Just in case you haven’t seen the news, we have finally released Pfam 28.0 on the old website.

I expect you may find that many of your proteins are no longer in their families, so please let me know.

==
will check after V 54

have downloaded current PFam coverage

Original comment by: ValWood

**Comment by ValWood** [comment]
Pfam V27 file is in Dropbox/pombase/Data

**Comment by ValWood** [comment]
84 protiens which used to have Pfam membership no longer do. I sent the list to Pfam to re-include
