### ISSUE TITLE
identify missing sno's

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#635]
1. Get a list of snos in S. cerevise http://www.yeastgenome.org/snoRNAtable.shtml
2. check which are missing in fission yeast
3. How many of these are in introns?
4. do we have all of these?
http://snoopy.med.miyazaki-u.ac.jp/snorna_db.cgi?mode=sno_search&organism=Schizosaccharomyces_pombe
5. Are they in introns in the corresponding fisison yeast genes Some sno's are in introns, and I think this location might be conserved for some sno's see SPNCRNA.497 above
6.  Are they in Rfam? if not submit
7. Can they be identifed by blast?  (if any of Sam's transcripts are in the hit list that's probably a true positive.....
8. Go back to Todds method, can this be improved? http://lowelab.ucsc.edu/databases.html
9.  sno/snu's in PomBase are all noted as "known"
Maybe we need to use the same "status" qualifiers for these so we can keep track of which are predicted/published (or maybe this could be inferred from evidence codes?).
10. Do GO annotation

~snR18 YAL003W  check  tef5~
ssnR44 missing YLR367E  pomb gene does not have intron.
snR59 missing YPL198w check rpl701,2,3
snR52  not in an intron, pol III transcribed, missing
SPNCRNA.497 is in rps3 intron, could it be a sono? 

Original comment by: ValWood

**Comment by ValWood** [comment]
do we have all of these?
http://snoopy.med.miyazaki-u.ac.jp/snorna_db.cgi?mode=sno_search&organism=Schizosaccharomyces_pombe
