### ISSUE TITLE
overlapping protein sequence

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#638]
VERY LOW PRIORITY
AUTOGENERATE LIST OF OVERLAPPING PROTEIN SEQ
see thread below

No worries, I now reilase I can find these from artemis.

So that we don't need to maintain this manually it would be useful if they were autogenerated. However, becasue we will have them all annotated, and this is very unlikely to change, it proably isn't worth you speding any time on ...ignore...there's lots more important stuff to do.... if it comes up again I'll request \(I will think about other "warnings" which can be autogenerated adn you can do them all together when the  more important stuff is done\)

Val

On 26/06/2011 20:21, mcdowall@ebi.ac.uk wrote:
&gt; Hi Val,
&gt;
&gt; \(ps Kim, we are not sat next to each other\)
&gt;
&gt;&gt; I wondered if it is possible to extract a list of protein coding regions
&gt;&gt; which overlap with each other from Chado or Ensembl?
&gt; This should be easy to include in the PomBase website as an extra page.
&gt;
&gt; We could get out the locations with some SQL if you wanted them now though
&gt; before getting this into the website.
&gt;
&gt; I'll raise this as a feature request for JIRA.
&gt;
&gt; Mark
&gt;

Original comment by: ValWood

**Comment by ValWood** [comment]
nobody has *ever* asked for this. I think I needed it once for something, if anybody needs it again it should be possible with a query, we can ask Mark
