### ISSUE TITLE
Check protein binding annotation for pop1 & pop2

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#64]
pop1 has
binds cig2	IPI	cig2	Yamano H et al. (2004)

so it has the bound thing in 2 places, the with field and an extension.
I think it only needs to be there once?
v

Original comment by: ValWood

**Comment by ValWood** [comment]
The paper PMID:14970237, with pop1 and pop2 are on my chromosome segregation priorities list so closing.
