### ISSUE TITLE
documentation for interactions

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#640]
somehow need to make it clear that you can curate  
RNA's using affinity cature RNA, and the mRNA will be displayed

http://www.ebi.ac.uk/panda/jira/browse/PB-873

here is an example
http://curation.pombase.org/pombe/curs/9ffe6c54d2c9f419

Original comment by: ValWood

**Comment by ValWood** [comment]
I'm not aware of this as an issue? Is it

**Comment by mah11** [comment]
I doubt it ..

**Comment by ValWood** [comment]
ok, easy
