### ISSUE TITLE
closing the slim holes.... (after V54 update)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#641]
Much easier to work on now Mark has made this list

http://www.pombase.org/browse-curation/fission-yeast-go-slim-terms-not-covered

Working through slowly.

1. response to free radical should get sucked into "cellular detoxification"

2. mRNA cleavage should be fixed by
 https://sourceforge.net/p/geneontology/ontology-requests/11732/

3. Jacky just mailed to ask why suc1 wasn't slimming (which is why I was looking)
this needs annotation prioritising but in the short term I'll find out which transition its regulating and make an NAS

4. Can ignore anything which is meu/mug/Schizosaccharomyces specific (meiotic cell cycle only)
5. Ignore anything which is "peptidase" (has proteolysis only)

A lot should clear up in 54 so I'll check again then

Original comment by: ValWood

**Comment by ValWood** [comment]
Slim 'fallout ' is now down to  118 (lowest ever, used to hover around 240).
I can see potential to slim some others but
closing as this is on my periodic tasks list.
