### ISSUE TITLE
Queuosine salvage

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#644]
pending
https://sourceforge.net/p/geneontology/ontology-requests/11744/

I annotated qtr1 and SPAC589.05c
curs/59866e3fe9bebea8
to tRNA modification to prevent dodgy intersections.

Need to re annotated when GO fixed

Original comment by: ValWood

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/11905
