### ISSUE TITLE
iron assimilation genes

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#646]
frp1- reduces ferric ion to ferrous
fip1/fio1 - complex (?) transports ferrous ion into cell
fep1 - represses the above genes when iron is available

to do:
fep1 represses "during cell response to iron" NOT "during cell response to iron starvation"
fip1 should have ferrous ion import? (fio1 does)
complex annotation fip and fio?

Original comment by: Antonialock

**Comment by ValWood** [comment]
@Antonialock this might be done?

**Comment by ValWood** [comment]
This looks as though it might be out of date?

**Comment by Antonialock** [comment]
yeah done
