### ISSUE TITLE
reminder to update Slm3 function term

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#647]
OK, the QC  rules worked, I just couldn't figure what it was telling me....
I had both mitochondrial tRNA thio-modification and tRNA methylation which are confliciting. Will delete
tRNA (5-methylaminomethyl-2-thiouridylate)-methyltransferase activity
and
tRNA methylation
Let me know when there is a correct MF term

cheers

Val

On 12/06/2015 21:32, Rama Balakrishnan wrote:
> Val,
>
> The data reported in PMID: 15509579 (http://www.jbc.org/content/280/2/1613.full#sec-4) doesn’t support the MF annotation we have. This paper reports thiol modification in position 2. If you look at the reaction in the URL you mention below for 2.1.1.61, the modification is at the 5 position not the thiol in the 2nd position. 
>
> tRNA-specific 2-thiouridylase is the activity we should be annotating to. There is no matching GO term for this activity. I will request one.
> If MF was 2.1.1.61 then yes, tRNA methylation would be right, but not in this case. So our BP annotation is right, not the MF annotation.
>
> Let me know if you have any questions.
> Rama
>
>
> On Jun 10, 2015, at 12:55 AM, Valerie Wood <vw253@CAM.AC.UK> wrote:
>
>>
>> Here it is:
>>
>> http://www.ebi.ac.uk/intenz/query?cmd=SearchEC&ec=2.1.1.61
>>
>> It looks like methylation. I don't see the  "thio-modification" ?
>>
>> Val

Original comment by: ValWood

**Comment by ValWood** [comment]
not yet fully fixed on stage, but should now be fine next update so closing
