### ISSUE TITLE
regulation of G1/S via transcription

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#648]
We need to find out if in pombe

transcription actually *regulates* G1/S, or is required for it.
http://www.pombase.org/spombe/related/GO:0000083

IIRC In budding yeast, it is regulatory because there is a feedback loop to increase cyclin transcription. in pombe the cyclins are present and regulation is post trasncriptional.

This would mean that although these gene products are *required for G1/S* to occur they might not be regulatory.

I need to run this by Jacky first.

Val

Original comment by: ValWood

**Comment by ValWood** [comment]
I guess this will all become apparent when somebody gets around to the G1/S papers
