### ISSUE TITLE
allele fixes

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#650]
1.
   10 cdc42L160S to  6 cdc42-L160S

2.  2 alleles are just called "F"  and 5 called "G" is that correct?

3. Should these be comma separated?
  2 G159A/C164U
   1 G159C/C164A
   1 G159C/C164G 
   1 G159U/A162C
   1 G159U/A162U
   2 G159U/C164A
 2 K/A
   2 K/R
  2 U157G/A165G
   1 U157G/U158C
   1 U158C/A166C

4. remove spaces
 1 Y1348A, N1344A, S1349A

5. change dot to standard 'hyphen'
 2 ade8.106

6. add hyphen
   2 alp111163
  2 alp41238

7. standardize
  +Removed cdc27 ones, done+

8. Does one of these have a space, maybe needs a canto ticket?
  16 pat1-114
   1 pat1-114 

9.   remove spurious hyphen after plo?

 1 plo-1-1-312
   2 plo-1-484-683
   2 plo-1-534-683
   1 plo-1-584-683
   2 plo-1-634-683
   2 plo-1-D181N
   2 plo-1-D181R
   5 plo-1-DHK625AAA
   2 plo-1-E193V
   2 plo-1-FN519AA
   2 plo-1-G505A
   2 plo-1-K69Q
   4 plo-1-K69R
   2 plo-1-L577A
   3 plo-1-T197V
   5 plo-1-YQL508AAA

10. Use standard nomenclature (hyphen) to match others

    12 rad15.P

13. Use standard nomenclature (hyphen) to match others

  12 rad9-192
   1 rad9.192

14.  
standardize
    1 ssm4-KE
   1 ssm4KE

15.
  1 vps17RR  add hyphen (standard nomenlature)

Original comment by: ValWood

**Comment by Antonialock** [comment]
remind me where I can see these again?

**Comment by ValWood** [comment]
I spotted them in:
http://www.pombase.org/downloads/phenotype-annotations

**Comment by ValWood** [comment]
Hmm, I though I had a file of these somewhere but I can't find it...

Note that, in publications sometimes 'mis-splell' alleles. So it is likely that the author wrote
 plo-1-1-312
plo-1-484-683
plo-1-534-683
plo-1-584-683
plo-1-634-683
etc

However, I think we should always just use the standard convention  of 
lowercase gene name-hyphen

**Comment by Antonialock** [comment]
ah ok I see now

**Comment by mah11** [comment]
I did the cdc27 ones because I curated the papers.
