### ISSUE TITLE
standardize notation for diploids etc in allele descriptions

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#651]
We need a system, discuss on call

**Comment by Antonialock** [comment]
What I've been doing:

type of mutation: "other"

name: geneX-/geneX-
description: homozygous diploid
expression: null

name: geneX+/geneX-
description: heterozygous diploid
expression: not specified

I figured that if we come up with a different way of doing them, then they are easily located on their "description"


(I may have done something else in earlier sessions but I think I've done this for the majority)

**Comment by mah11** [comment]
considerable overlap with #669
suggestion in Canto ticket https://github.com/pombase/canto/issues/976

**Comment by ValWood** [comment]
Actually it seems there is a solution for this proposed. I don't think we still need this ticket?

**Comment by mah11** [comment]
Presumably there will be genotypes to update when the Canto work is done (ticket 976 linked above). I don't mind whether we reopen this, open a new ticket, or rely on logs when the time comes.
