### ISSUE TITLE
process or physical structure phenotype document

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#654]
I thought this was really useful can we include in phenotype curation docs? I'd certainly include this advice  in a detailed curation workshop

If you see a process going wrong (e.g. movie or kymograph), you can annotate to a "process phenotype" term, i.e. one that uses a GO BP term for its logical definition. If you only have a still picture of a wonky structure, annotate to a "physical structure" term (GO CC term in logical def) such as abnormal morphology.

**Comment by mah11** [comment]
done yesterday
