### ISSUE TITLE
nonsense note fps1, spo9

### ISSUE THREAD

**Issue by mah11** [pombase/curation#658]
I looked at fps1 and spo9 for #590, and saw that they both have this note, which doesn't make grammatical sense:

    FT                   /note="Fps1 appears to have YJL167W has retained the
    FT                   functions YPL069C, Spo9 (Fps1 paralog) appears to have
    FT                   farnesyltransferase like S. cerevisiae BTS1 YPL069C which
    FT                   does not have a direct ortholog in fission yeast"

I didn't fix it because I don't know what it's supposed to say. Both genes have S.c. ERG20 listed as a manually curated ortholog.

Might be worth reviewing the ISO annotations from ERG20 - I've put the some on both genes but am not sure that's 100% correct.

**Comment by ValWood** [comment]
oh delete, it should all be apparent if there is now published data....slowly getting rid of most notes...

**Comment by mah11** [comment]
ooh, I love it when it's easy! deleting now ...
