### ISSUE TITLE
annotate sub telomeric repeat regions

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#66]
In the meantime, I have deleted the following legacy repeat  features:
They aren't particularly useful, and they would be difficult to map to any repeat type.

/systematic_id="SPRPTA.2"
/note="duplicated region in c794"

/systematic_id="SPRPTA.3"
/note="duplicated region in c750"

/systematic_id="SPRPTA.22"
/note="duplicated region in c977 "

/systematic_id="SPRPTA.23"
/note="duplicated region in c1348"

/systematic_id="SPRPTA.24"
/note="duplicated region in c977"

/systematic_id="SPRPTA.25"
/note="region duplicated in SPAC1952 S. pombe chromosome 1"

/systematic_id="SPRPTA.26"
/note="duplicated region in c212"

/systematic_id="SPRPTA.19"
/note="duplicated region in c977 S. pombe chromosome 1: sub telomeric region"

/systematic_id="SPRPTA.21"
/note="duplicated region in 977"

/systematic_id="SPRPTA.1"
/note="duplicated region in pB8E5"

/systematic_id="SPRPTA.4"
/note="region duplicated in SPAC1348 S. pombe chromosome 1"

/systematic_id="SPRPTB.1"
/note="duplicated region in c212"

/systematic_id="SPRPTB.2"
/note="duplicated region in c977"

/systematic_id="SPRPTB.3"
/note="duplicated region in c977"

/systematic_id="SPRPTB.16"
/note="dupliated region in c212"

/systematic_id="SPRPTB.17"
/note="duplicated region in c212"

/systematic_id="SPRPTB.18"
/note="telomeric repeats"

Original comment by: ValWood

**Comment by ValWood** [comment]
see "future" doc
