### ISSUE TITLE
query PMID:25533956 genotypes

### ISSUE THREAD

**Issue by mah11** [pombase/curation#661]
Looking at this session for the Canto load log (also see https://github.com/pombase/pombase-chado/issues/469), I spotted a couple of oddities with the genotypes:

- The session lists rec7 and uses it in a couple of genotypes, but the paper mentions rec12, and not rec7. Which is correct?

- Is the plo1 FYPO:0003604 annotation from figure 5f? That one also has the rec12delta allele present, so should it be done as multi-allele?

**Comment by ValWood** [comment]
yep both wrong and now fixed
