### ISSUE TITLE
checkpoint annotation specificity

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#662]
can these move down to the 'mitotic' term?

SPCC18B5.03.1		GO:0072401	signal transduction involved in DNA integrity checkpoint	e0f7d8e22ba14953	PomBase
SPCC1259.13.1		GO:0072401	signal transduction involved in DNA integrity checkpoint	e0f7d8e22ba14953	PomBase
SPBC11B10.09.1		GO:0072402	response to DNA integrity checkpoint signaling	e0f7d8e22ba14953	PomBase

(let me know if not, I'll remove the restriction)

**Comment by mah11** [comment]
first two moved; more specific term does not exist for third

**Comment by mah11** [comment]
TGFF'd this:
ID: GO:1990820 Label: response to mitotic DNA integrity checkpoint signaling

**Comment by mah11** [comment]
term in Canto, and deployed
