### ISSUE TITLE
phosphorylation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#663]
should these be 'protein dephosphorylation'?

SPBP4G3.02.1		GO:0016311	dephosphorylation	878b71dfebf4ce34	PomBase
SPBC428.03c.1		GO:0016311	dephosphorylation	dad0d98fa4da533e	PomBase

**Comment by mah11** [comment]
Antonia did both papers, but to me it looks like the answer is "no". They're about acid phosphatase, which removes phosphate from all sorts of things, not just proteins.

**Comment by ValWood** [comment]
Ah OK, I'll remove that term from the 'do not annotates'
