### ISSUE TITLE
make sure all detoxification terms are "cellular"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#666]
when this is addressed
https://github.com/geneontology/go-ontology/issues/12027

This will involve
i) migrating detoxification direct annotations to "cellular detoxification"
ii) detoxification of cadmium ion to cellular....
iii) detoxification of copper ion to cellular
iv) detoxification of arsenic-containing substance -> cellular

**Comment by Antonialock** [comment]
requested
GO:1990880 Label: cellular detoxification of copper ion
http://curation.pombase.org/pombe/curs/168bceb80cef3319

**Comment by Antonialock** [comment]
I think this is fine now:
 
Query: ( GO_ID(GO:0098754 - detoxification) ) NOT ( GO_ID(GO:1990748 - cellular detoxification) )
This query matches 0 genes.
