### ISSUE TITLE
annotation check hta1 and hta2

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#667]
I noticed that hta1 and hta2 are annotated to
DNA damage induced protein phosphorylation

is that correct? it sounds odd? regulation perhaps but it can't be direct unless  it is a kinase?

**Comment by Antonialock** [comment]
curate PMID:
    15226425

**Comment by ValWood** [comment]
ah right so the histone is phosphorylated, by something else?

**Comment by Antonialock** [comment]
yeah rad3 and tel1 probably

**Comment by ValWood** [comment]
yep makes sense
