### ISSUE TITLE
fix non standardhomo/het diploid name/descriptions

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#669]
Most are done Antonias's way, these are the exceptions 

heterozygous diploid,SPBC1289.03c,spi1,spi1::ura4/-,e113c7320f53efc5
homozygous diploid,SPBC21.05c,ral2,ral2mutant/ral2mutant,423a987e520829e2
heterozygous diploid,SPAC17H9.09c,ras1,D59T/+,a64b97197e845b5b
homozygous diploid,SPAC1D4.13,byr1,byr1::LEU2/byr1::LEU2,a64b97197e845b5b
heterozygous diploid,SPAC4A8.12c,sds22,sds22::ura4/+,c93df2f114eaee6e
homozygous diploid,SPAC22H10.07,scd2,ral3mutant/ral3mutant,423a987e520829e2
homozygous diploid,SPAC16E8.09,scd1,ral1mutant/ral1mutant,423a987e520829e2

Once these are fixed we need a ticket on the canto tracker to  add 
homozygous diploid/ heterozygous diploid to the drop down 
with prompts for the syntax for the name format.

**Comment by ValWood** [comment]
Correction ALL will need fixing to use multi-allele
 WT and deletion of the same gene
record the homozygous diploid in the background field

**Comment by ValWood** [comment]
its3+/its3-,SPAC19G12.14,its3,heterozygous diploid,ed12ab2f3f0456f6
srk1-/srk1-,SPCC1322.08,srk1,homozygous diploid,ec6c2870725e0368
tif35+/tif35-,SPBC18H10.03,tif35,heterozygous diploid,ed12ab2f3f0456f6
ste13-/ste13-,SPBC776.09,ste13,diploid construct,e8aedfc4412e4268
pac2+/pac2+ diploid,SPAC31G5.11,pac2,pac2 OEP in diploid,e25a10ee7a1d5416
mcs2+/mcs2-,SPBP16F5.02,mcs2,heterozygous diploid,9a1022fd353bacb9
heterozygous diploid,SPBC1289.03c,spi1,spi1::ura4/-,e113c7320f53efc5
fkh1-/fkh1-,SPBC839.17c,fkh1,homozygous diploid,ae029b5da42522e3
gpa1-/gpa1-,SPBC24C6.06,gpa1,homozygous diploid,986cd0e5341a9fe8
atf1-/atf1-,SPBC29B5.01,atf1,homozygous diploid,87780c68f55805a1
map1-/map1-,SPAC11E3.06,map1,homozygous diploid,bf6ebbd7a7fa9fb9
ste7-1/ste7-1 diploid,SPAC23E2.03c,ste7,homozygous diploid,34e3d6fc4ce28886
gea1+/gea1-,SPBC211.03c,gea1,heterozygous diploid,fa30fa9e2e0880e6
spi1+/spi1-,SPBC1289.03c,spi1,heterozygous diploid,894e3c36003ab516
dic1+/dic1-,SPBC646.17c,dic1,heterozygous diploid,9a1022fd353bacb9
rad24+/rad24-,SPAC8E11.02c,rad24,heterozygous diploid,894e3c36003ab516
fus1-B20/fus1-B20,SPAC20G4.02c,fus1,homozygous diploid,ef2da839886aa260
ras1-/ras1-,SPAC17H9.09c,ras1,homozygous diploid,803cfb382ebb41c6
skp1-/skp1-,SPAC1687.15,gsk3,homozygous diploid,d37836a2104d53bc
top2+/top2-,SPBC1A4.03c,top2,heterozygous diploid,894e3c36003ab516
tor2+/tor2-,SPBC216.07c,tor2,heterozygous diploid,ed12ab2f3f0456f6
homozygous diploid,SPBC21.05c,ral2,ral2mutant/ral2mutant,423a987e520829e2
moe1-/moe1-,SPAC637.07,moe1,homozygous diploid,2de3ef290c749683
sty1-/sty1-,SPAC24B11.06c,sty1,homozygous diploid,87780c68f55805a1
spk1-/spk1-,SPAC31G5.09c,spk1,homozygous diploid,986cd0e5341a9fe8
taf4+/taf4-,SPAC23G3.09,taf4,heterozygous diploid,9a1022fd353bacb9
heterozygous diploid,SPAC17H9.09c,ras1,D59T/+,a64b97197e845b5b
delta/delta,SPAC18B11.07c,rhp6,deletion in diploid,47797c5ac471b4da
SPBC19C2.10+/SPBC19C2.10-,SPBC19C2.10,,heterozygous diploid,9a1022fd353bacb9
byr2-/byr2-,SPBC1D7.05,byr2,homozygous diploid,803cfb382ebb41c6
cam1+/cam1-,SPAC3A12.14,cam1,heterozygous diploid,894e3c36003ab516
spn3+/spn3-,SPBC16A3.01,spn3,heterozygous diploid,9a1022fd353bacb9
sum1+/sum1-,SPAC4D7.05,sum1,heterozygous diploid,ed12ab2f3f0456f6
ste7-delta/ste7-delta diploid,SPAC23E2.03c,ste7,homozygous diploid,34e3d6fc4ce28886
ste7+/ste7+,SPAC23E2.03c,ste7,homozygous diploid,34e3d6fc4ce28886
erg10+/erg10-,SPBC215.09c,erg10,heterozygous diploid,9a1022fd353bacb9
tif45+/tif45-,SPAC16E8.15,tif45,heterozygous diploid,ed12ab2f3f0456f6
cdc2+/cdc2-,SPBC11B10.09,cdc2,heterozygous diploid,ed12ab2f3f0456f6
asa1+/asa1-,SPAC1006.02,asa1,heterozygous diploid,9a1022fd353bacb9
cgs1delta/cgs1-1,SPAC8C9.03,cgs1,heterozygous diploid,0c872033a21c238e
homozygous diploid,SPAC1D4.13,byr1,byr1::LEU2/byr1::LEU2,a64b97197e845b5b
cut12+/cut12-,SPBC649.05,cut12,heterozygous diploid,ed12ab2f3f0456f6
cut7+/cut7-,SPAC25G10.07c,cut7,heterozygous diploid,894e3c36003ab516
ste4-/ste4-,SPAC1565.04c,ste4,homozygous diploid,0dd384fe368bd279
tuf1+/tuf1-,SPBC9B6.04c,tuf1,heterozygous diploid,ed12ab2f3f0456f6
act1+/act1-,SPBC32H8.12c,act1,heterozygous diploid,ed12ab2f3f0456f6
heterozygous diploid,SPAC4A8.12c,sds22,sds22::ura4/+,c93df2f114eaee6e
zfs1-/zfs1- diploid,SPBC1718.07c,zfs1,homozygous diploid,67506e3e78c72666
map1 mutant / map1 mutant,SPAC11E3.06,map1,homozygous diploid,cd202708cc47017a
mip1+/mip1-,SPAC57A7.11,mip1,heterozygous diploid,c22385c0fd392e28
alg9+/alg9-,SPAC1834.05,alg9,heterozygous diploid,9a1022fd353bacb9
byr1-/byr1-,SPAC1D4.13,byr1,homozygous diploid,803cfb382ebb41c6
suc1+/suc1-,SPBC1734.14c,suc1,heterozygous diploid,ed12ab2f3f0456f6
homozygous diploid,SPAC22H10.07,scd2,ral3mutant/ral3mutant,423a987e520829e2
homozygous diploid,SPAC16E8.09,scd1,ral1mutant/ral1mutant,423a987e520829e2
pcr1-/pcr1-,SPAC21E11.03c,pcr1,homozygous diploid,aefacb75b8af3f8a
pik3+/pik3-,SPAC458.05,pik3,heterozygous diploid,ed12ab2f3f0456f6
int6-/int6-,SPBC646.09c,int6,homozygous diploid,2de3ef290c749683
cpc2-/cpc2-,SPAC6B12.15,cpc2,homozygous diploid,5e0bcd0a5a6d9347
tor1-/tor1- diploid,SPBC30D10.10c,tor1,homozygous diploid,3c604e8199f9bf8b
ste7-111/ste7-111,SPAC23E2.03c,ste7,homozygous diploid,34e3d6fc4ce28886

**Comment by mah11** [comment]
I have opened a Canto ticket: https://github.com/pombase/canto/issues/976

**Comment by ValWood** [comment]
I guess this will all be dealt with via a log file?
