### ISSUE TITLE
GO terms not to annotate logs, a heads up

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#671]
OK, I *  think* I finished clearing out the last  couple of 100 of these!
so from now on, this file can become part of the normal log file checking procedure.

For the next couple of runs, ignore any from UniPROT/InterPro/GOC. These are awaiting fixes at GO
I will let you know once these are all fixed, and any new ones after this will need to be checked by the person doing the logs.

BUT, please check any which come from Canto session.
The new ones from this update are:

1. Are these definitely "meiotic nuclear division"? and not "meiotic cell cycle" (one seems to be m-type gene?)

SPBC23G7.17c.1		GO:0045836	positive regulation of meiotic nuclear division	24e9f1d9ea02f952	PomBase
SPMTR.02.1		GO:0045836	positive regulation of meiotic nuclear division	24e9f1d9ea02f952	PomBase

2. can we say + or -?
SPBC887.10.1		GO:0010389	regulation of G2/M transition of mitotic cell cycle	ea7f33ab6887fe6d	PomBase

3. Can we say which polymerase? has always been possible up to now?
SPBC11B10.10c.1		GO:0045892	negative regulation of transcription, DNA-templated	cfba7cb5d851df37	PomBase
SPCC1020.12c.1		GO:0045892	negative regulation of transcription, DNA-templated	cfba7cb5d851df37	PomBase

Will assign to Antonia first. If any left assign to M.
If you can't make more specific let me know and I'll relax the constraints.

v

**Comment by mah11** [comment]
none of the annotations queried are mine

**Comment by ValWood** [comment]
These will get processed as part of the logs

**Comment by ValWood** [comment]
Hi Antonia,

could you look at this one when you get chance, they are still in the log file.

Val

**Comment by ValWood** [comment]
also, should these be protein phosphorylation?

SPBP4G3.02.1		GO:0016311	dephosphorylation	878b71dfebf4ce34	PomBase
SPAC24H6.05.1		GO:0016311	dephosphorylation	4c3ae230fa3c6f4d	PomBase
SPBC428.03c.1		GO:0016311	dephosphorylation	dad0d98fa4da533e	PomBase

I might have asked about these before, but I thought the older one were already  made more specific so I suspect these are new.

**Comment by mah11** [comment]
> also, should these be protein phosphorylation?

SPBP4G3.02.1 and SPBC428.03c.1 were covered in both #595 and #663.

Re SPAC24H6.05.1 - Although we know from loads of other papers that Cdc25 is a protein phosphatase, in PMID:22561704 they only assayed its activity using a chemical substrate (3-O-methylfluorescein phosphate cyclohexyl ammonium salt (OMPF)), so it wouldn't be strictly correct to say _that paper_ has data saying it does protein dephosphorylation.

**Comment by ValWood** [comment]
Yeah I think maybe we already checked these...
I'll take that term out of the logs....

**Comment by Antonialock** [comment]
1. I recurated the paper (old)
1. (the second 1..) I changed this annotation to SAPK cascade BP, because I guess it is ihe SAPK cascade that has knock on effects on the cell cycle
2. This was a community curator annotation. I changed the BP to "chromatin organization"
