### ISSUE TITLE
question about extension for tRNA

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#672]
GO:0001875 tRNA methyltransferase activity (SO:glycyl_tRNA)

Antonia, can you check this? Isn't it just methylating a *glycine* residue, not a "glycyl tRNA?

Val

**Comment by Antonialock** [comment]
I would be very surprised if a tRNA had a glycine residue as a substrate ;)

**Comment by ValWood** [comment]
Oh yeah.
So does this methylate glycine tRNA only?

**Comment by ValWood** [comment]
and to be clear, did they only assay glycyl tRNA  (i.;e is this info really physiologically relevent?)

I can check later, but bogged down trying to get through the AE extension stuff. Don't want to stop half way through
v

**Comment by Antonialock** [comment]
Umm, yeah? Maybe they tried one other one? Different tRNAs will have different modifications so I don't see why this would make it physiologically irrelevant

**Comment by ValWood** [comment]
I  looked yesterday and I couldn't see where they mentioned glycyl tRNA... I must have missed it...

If it is relevant I might change the extension to the pombe sys IDs for cytosolic glycyl tRNA (presumable it would be all of them as they are pretty much identical, or do they mention which specific one they assayed?). Then I can keep modifications to have PomBase IDs rather than SO terms.....
v

**Comment by ValWood** [comment]
Ah got it, its superscripted. I'll plug the IDs in...

**Comment by Antonialock** [comment]
The primer is identical to
TRNAGLY.0
TRNAGLY.0
TRNAGLY.0
TRNAGLY.0
TRNAGLY.0

**Comment by Antonialock** [comment]
TRNAGLY.0

**Comment by ValWood** [comment]
That's wierd, I only found 4 when I used the codon...will double check

**Comment by ValWood** [comment]
look
http://www.pombase.org/spombe/related/GO:0033462

**Comment by ValWood** [comment]
ah you were looking at these....I bet you didn't do chromosome 2 yet?

**Comment by Antonialock** [comment]
I cut a piece of the primer they amplified and pasted it into artemis

**Comment by Antonialock** [comment]
this
GCTTTGGCCGGGAATCGAACCCGGGTCGAATCGATGGCAACGATTCATTATACCACTAAAC

**Comment by Antonialock** [comment]
That way doesn't work? now im confused :p

**Comment by ValWood** [comment]
Is Ok.
I just wanted all of the TRNAGlys to add as extensions instead of the SO term.
but they don't all have the same adaptor activity annotated. I now have them all.
