### ISSUE TITLE
annotation check/ meiosis or meiotic cell cycle

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#675]
working through allowed extensions.

Should this be "meiotic cell cycle" rather than "meiosis" ?
GO:1900475	positive regulation of meiosis by negative regulation of transcription from RNA polymerase II promoter
curs/45dd89cc4951b51a

**Comment by mah11** [comment]
I don't know why this is assigned to me - I've done nothing with this paper/session. But at a quick glance it looks like "regulation of meiotic cell cycle" would work.

**Comment by ValWood** [comment]
not sure

**Comment by ValWood** [comment]
closing, redundant with
https://github.com/pombase/curation/issues/671
