### ISSUE TITLE
AE for regulations of mitochondrial translation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#676]
These are probably legacy annotations. I bet if this paper was reannotated these might only be 'phenotype' annotations?

So at the moment, I haven't put anything in the config file for this one

when
PMID:21727087 is reannotated we can put something in. It would also be good to be able to restrict to mitochondrial gene products

**Comment by mah11** [comment]
It's not at all clear what the question or task is -- what are the "legacy annotations" mentioned in the summary? Is PMID:21727087 the only paper affected here?

**Comment by mah11** [comment]
p.s. PMID:21727087 has a completed Canto session, done by ... Val
http://curation.pombase.org/pombe/curs/da671cd7

**Comment by ValWood** [comment]
I deleted the GO for now, phenotype only for now. pprs do something with mitochondrial mRNAs
