### ISSUE TITLE
annotation check PMID:25918164 (for BP AE config file completion)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#677]
These aren't glycosylases,  so should they be "regulation of glycosylation"
or, should they be phenotypes?
v

PomBase	SPBC119.02	ubc4		GO:0006487	PMID:25918164	IMP		P	ubiquitin conjugating enzyme E2 Ubc4/UbcPubcP1	protein	taxon:4896	20150720	PomBase	has_input(PomBase:SPBC947.10)	
PomBase	SPAC1486.02c	dsc2		GO:0006487	PMID:25918164	IMP		P	Golgi Dsc E3 ligase complex subunit Dsc2	ucp14	protein	taxon:4896	20150720	PomBase	has_input(PomBase:SPBC947.10)	
PomBase	SPAC20H4.02	dsc3		GO:0006487	PMID:25918164	IMP		P	Golgi Dsc E3 ligase complex subunit Dsc3	protein	taxon:4896	20150720	PomBase	has_input(PomBase:SPBC947.10)	
PomBase	SPAC4D7.11	dsc4		GO:0006487	PMID:25918164	IMP		P	Golgi Dsc E3 ligase complex subunit Dsc4	protein	taxon:4896	20150720	PomBase	has_input(PomBase:SPBC947.10)

**Comment by ValWood** [comment]
When this is done, the appropriate doamin /range needs adding to BP config file

**Comment by mah11** [comment]
> These aren't ~~glycosylases~~ glycosyltransferases, so should they be "regulation of glycosylation" ...?

I don't know; I'll email Peter.

**Comment by mah11** [comment]
Peter has opted for GO:0060049 (regulation of protein glycosylation).
