### ISSUE TITLE
a tidy of peptide pheromone export

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#678]
Term ID	Term Name	Evidence	With/From	Reference	Count
GO:0000770	peptide pheromone export	IMP		Christensen PU et al. 
seems that it should move down to
GO:0090539	peptide pheromone export by transmembrane transport	
(I am blocking peptide pheromone export for direct annotation)

also
peptide pheromone export involved in conjugation with cellular fusion
should be a transmembrane term?
I will block this to, but a new term will need to be requested

**Comment by Antonialock** [comment]
new term requested

**Comment by Antonialock** [comment]
fixed, also had a bit of a tidy of the rest of the curation, session very old
