### ISSUE TITLE
dfp1 annotation query

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#679]
For these, (pic)
are dfp1 and mcm2 correct as "regulates" targets?

for the term
"positive regulation of s/t protein kinase activity" I expected the regulates targets to be kinases?

**Comment by ValWood** [comment]
![dfp1](https://cloud.githubusercontent.com/assets/7359272/9722917/d85b406a-55ad-11e5-9a90-04e0ffe3b49e.jpg)

**Comment by mah11** [comment]
Rats. In  the session mcm2 and dfp1 extensions use has_input, not has_regulation_target, but both are being transformed to ‘regulates' for display. I was trying to capture "regulates the activity of Hsk1 phosphorylating itself, Dfp1 or Mcm2" but I suspect the system just isn't quite sophisticated enough to handle that (might need nested extensions or lego/noctua/whatever).

I'll delete the has_input extensions. Sigh. It's got the kinase substrates on the MF annotation anyway.

**Comment by ValWood** [comment]
Yeah I think thats the important part....not a big loss

These are probably the kinds of annotations where the noctua/lego can help
I'll put a "lego" flag on here . We can find it in closed tickets if we ever want to.
