### ISSUE TITLE
status of AE config file, and still to do 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#684]
I have created config files for BP, MF, and CC

There is still stuff to do, but I have covered most relations.

Some relations will need better  domain and range specification later. For example, I got in knots trying to do happens_during. I wanted to restrict it to the subsets which excluded "mitotic cell cycle" or other terms where you wouldn't add it because it is implicit. We will need to refine these later hence this ticket. It might be easier to be able to exclude subsets for some terms

I will add other to do's in here also.

**Comment by ValWood** [comment]
![go_bp_a_e_config](https://cloud.githubusercontent.com/assets/7359272/9754930/7773ebe4-56c5-11e5-80af-fd502793c56d.jpg)

**Comment by ValWood** [comment]
![go_mf_a_e_config](https://cloud.githubusercontent.com/assets/7359272/9754937/89c83d72-56c5-11e5-9eb2-7f1993198247.jpg)

**Comment by ValWood** [comment]
![go_cc_a_e_config](https://cloud.githubusercontent.com/assets/7359272/9754945/9693d9f8-56c5-11e5-937c-4356414c5f9b.jpg)

**Comment by ValWood** [comment]
These will need some refining I suspect.
The text to appear on the pages probably needs tweaking for many

**Comment by ValWood** [comment]
not done (some of the less used ones and the ones slated for possible obsoletion)
So if you come across any missing when we start using, please add.

 13 | occurs_in                 | biological_process
 62 | inhibited_by              | molecular_function
  9 | occurs_in                 | molecular_function
  8 | dependent_on            | biological_process
    12 | independent_of          | biological_process
     1 | not_happens_during      | biological_process
    24 | dependent_on            | cellular_component
    20 | independent_of          | cellular_component
    16 | not_exists_during       | cellular_component
     8 | dependent_on            | molecular_function
     23 | independent_of          | molecular_function
      3 | not_happens_during      | molecular_function

**Comment by ValWood** [comment]
To do
restrict domain and range for "happens_during"

**Comment by pombase-admin** [comment]
Thanks that's great.

**Comment by ValWood** [comment]
occurs_at also not done

**Comment by ValWood** [comment]
range restrictions required later
(to specific GO process term branches)
GO:0005575 is_a happens_during GO:0008150 location happens during cell cycle phase or process

**Comment by mah11** [comment]
emailed:

Actually, the most natural-language-friendly thing would be "phosphorylates", "methylates", "modifies", etc. You wouldn't say "Cdc2 has Cdc13 as a phosphorylated protein" or anything like that; you'd say "Cdc2 phosphorylates Cdc13".

and

I think it would be fine to use "modifies" not only for these small Ub-like things, but also for some of the other modifications. I don't think it's essential to repeat all of the GO term specificity in the display text, because they'll have the term there anyway.

**Comment by mah11** [comment]
It would probably be more useful to have separate tickets for specific to-do items rather than try to find specific things in a growing pile of comments here.

**Comment by ValWood** [comment]
OK lets keep this ticket only for future  restrictions to domains and ranges.  We don't need to do it until the ability to handle subsets in ranges is implemented, and then they can hopefully be addressed as a single task. Everything else, new ticket.

**Comment by mah11** [comment]
notes on FYPO extensions in #689 and the Canto ticket (https://github.com/pombase/canto/issues/181)

**Comment by ValWood** [comment]
Closing. We can open new tickets for  us or Kim specifics which arise during testing and checking.
