### ISSUE TITLE
FYPO - CL extensions to convert to genotypes

### ISSUE THREAD

**Issue by mah11** [pombase/curation#689]
There are some phenotype annotations that have occurs_in(CL:nnn) extensions to capture h+, h- or diploid. Now that Canto & Chado do genotypes, the extensions should be removed and replaced with genotypes including the mating type.

I have not included these in the FYPO extension configuration files.

occurs_in(CL:0002674)   H minus
occurs_in(CL:0002675)   H plus
occurs_in(CL:0000415)   diploid cell

The new config files should cover all other extensions as of v54.

pombe-embl/supporting_files/annotation_ex_config/FYPO_A_E_admin-only_config
pombe-embl/supporting_files/annotation_ex_config/FYPO_A_E_config

**Comment by mah11** [comment]
tracker won't let me upload a .txt file, but it's trivial to grep from the phaf

**Comment by mah11** [comment]
These four need the diploid-handling upgrade in https://github.com/pombase/canto/issues/976
PMID:12376568
PMID:12882583
PMID:2107403
PMID:8380233

The rest are done.

**Comment by ValWood** [comment]
@mah11 Can these be done now?

**Comment by mah11** [comment]
yep, done
