### ISSUE TITLE
update PHAF and website for multi-gene data

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#693]
Placeholder...Not sure if we have a ticket for this...

**Comment by mah11** [comment]
dependency: discuss with Kim and decide which files will actually be produced (and accepted as submissions, if anyone ever sends any)

**Comment by ValWood** [comment]
wiki says
* multgene phenotype format  input/output (there is one dataset for this....which one?)

I don't  know what this means....

**Comment by mah11** [comment]
Well, the history says you added it ;)

There are quite a few multi-allele phenotypes annotated now, so in a sense there's "a set" of data that could be used to test output.

As far as I know, there is no fully "real" dataset for loading, or testing thereof. The wiki note may be referring to a set of three files I mocked up for Kim to use to test Chado loading. The alleles, allele combinations (i.e. genotypes) and phenotypes are real, but I assigned them totally made-up IDs that won't be used in real life.

**Comment by ValWood** [comment]
Oh I have no doubt about that!

**Comment by ValWood** [comment]
read-only copy is at
http://oliver0.sysbiol.cam.ac.uk/pombase-trac/wiki/PhenotypeImportExportFormats

**Comment by ValWood** [comment]
@kimrutherford  needs to monitor this ticket.

**Comment by mah11** [comment]
three sample files, with totally fake IDs for everything except genes, in svn:
/pombe-embl/external_data/phaf_files/in-progress/PMID_24362309_multigene_*

**Comment by mah11** [comment]
one for alleles, one for genotypes, and one for phenotype annotations

**Comment by ValWood** [comment]
documentation only when
https://github.com/pombase/pombase-chado/issues/496
completed

**Comment by ValWood** [comment]
I don't think we need this ticket
