### ISSUE TITLE
need to create a DB xref  for non-GO ISS inferences

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#695]
From the wiki:

 * creating a DB x-ref for ISS inferences for annotations other than GO
    * will get rid of http://curation.pombase.org/dumps/latest_build/logs/db_xref_problems.txt
    * https://www.ebi.ac.uk/panda/jira/browse/PB-1916 
    * suggestion PB_REF:0000001 "def"

Was this all done? The jira ticket is closed, but I don't *remember* doing the part assigned to me?
Anyone know  if this is still outstanding?

**Comment by mah11** [comment]
This all got done a wihle ago. PB_REFs (well, ref singular at the moment) live in pombe-embl/supporting_files/PB_references.txt
