### ISSUE TITLE
creating and handling protein complexes for annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#696]
- annotate to protein complex ID (can get from PRO)?
  - example: PMID:18723846 has direct assays showing ORC binding to origin DNA, but doesn't distinguish subunits; from other work, it's known that some but not all ORC subunits actually make contact with DNA. Annotate all to DNA binding anyway, with or without contributes_to, or annotate to a complex ID? (I'd (m) prefer the latter but will it break anything?)
  - same paper: similar issue for annotation extension - cdt1 or cdc18 increase ORC origin binding - put complex ID in has_regulation_target ext?

**Comment by mah11** [comment]
see PRO ticket https://sourceforge.net/p/pro-obo/term-requests/95/

**Comment by ValWood** [comment]
OK, I plan to make a list of all of the things which will need to be addressed by removing complexes from GO and run it by you.
