### ISSUE TITLE
dealing with deprecated annotation extension relations

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#697]
The ontology group have been working through the list of AE relations as
discussed at the GOC meeting. We'll now have follow-up meetings with some
of the annotators and work together to produce some definitive
documentation. In the meantime though, there are a set of relations we are recommending be deprecated, we suggest you avoid using these:

X in_absence_of (Use instead inhibited_by or negatively_regulates or
don't capture)
X in_presence_of (Use instead activated_by or positively_regulates or
don't capture)
X independent_of
X localization_dependent_on
X requires_sequence_feature
X requires_substance

**Comment by ValWood** [comment]
I'm not sure if we still use all of these?

1. Get counts of use
2.  reannotate any remaining. If we have data we still want to capture but we don't know whet to do with it consider my old suggestion (might be better not to do this if we can avoid it!)

1. GO will soon be obsoleting some annotation extension relationships which we currently have in use (because they don't extend the annotation, they are provide slightly different type of information). For some of these, the information captured is useful, and we would like to keep them internally. This means that there are a small number of qualifiers which will continue to be hosted by PomBase, but will need to be filtered from the GO GAF (although the core annotation, and other concurrent extensions will remain). We will evaluate which of these we would like to keep and cannot be captured in another way at the next curator meeting, and them provide a list to Kim.

**Comment by mah11** [comment]
in_absence_of, localization_dependent_on, requires_sequence_feature, requires_substance all absent from pombase-build-2015-10-21-v1-l1.gaf

**Comment by mah11** [comment]
in_presence_of now gone (updated/deleted as appropriate)

**Comment by ValWood** [comment]
How did you deal with
cyclin-dependent protein serine/threonine kinase activity
has substrate cdc18, in presence of cdc13
has substrate cdc18, in presence of cig2

I was thinking yesterday that this is the only way we have of knowing which CDK complex links to which phase....did you think of another way to do this ? (I think we need to  preserve this information so I'm prepared to go back to GOC if  we lose this capability).

(I kind of didn't realise that in_presence_of was one of the ones for the chop)

**Comment by ValWood** [comment]
Ah look above...

**Comment by ValWood** [comment]
I'm not sure that activated_by or positively_regulates would fit in this context...

**Comment by mah11** [comment]
For the cyclin-dependent kinase one, I just put in a comment for now. Eventually we'll upgrade the annotations to use IDs for the cyclin-CDK complexes (and I can defer worrying about them in the meantime).

**Comment by mah11** [comment]
I'm also saving notes on the changes I'm making, so nothing will be lost to us.

**Comment by mah11** [comment]
Done - just polished off dependent_on and independent_of.

Notes for posterity in Dropbox/pombase/ontologies/GO/GO_annotation_misc/
