### ISSUE TITLE
make screencasts for canto curation examples

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#700]
We need some  short/simple screencasts for each curation type.

**Comment by ValWood** [comment]
This is high medium. It will become high as soon as I have done  my 'high' tickets

**Comment by Antonialock** [comment]
"Camtasia software (www.techsmith.com/camtasia.html) has been used by the SGD to add simple effects and annotations to video tutorials in order to enhance clarity of the presented material."

**Comment by ValWood** [comment]
Useful. I  was looking for something which allowed annotating the movies for pombe 2017 and I couldn't find anything free. I found a lot which pretended to be free.

**Comment by ValWood** [comment]
this can't happen  now until after genotype interface revision

**Comment by ValWood** [comment]
CLosing!

**Comment by ValWood** [comment]
Thanks @manulera
