### ISSUE TITLE
change from "other" to "disruption"?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#701]
spo15::ura4+,SPAC1F3.06c:allele-5,f51c10788015bf25
gar2::ura4+,SPAC140.02:allele-4,ab7d71d62a2030e3
mcs6::ura4+,SPBC19F8.07:allele-2,e96bae1f0363904c
crp79delta::ura4+,SPAC1610.03c:allele-3,3b211355644f4b72
ppa1::ura4+,SPAC823.15:allele-3,760d48a1560efbfc
snu4::LEU2,SPSNRNA.04:allele-2,9ef19b84bfc2287a
cnx1::ura4+,SPAC3C7.11c:allele-2,aa80b6544eead412
srp7::ura4+,SPNCRNA.98:allele-131,d877da09e6003baa
msn5::ura4+,SPAC328.01c:allele-5,c1d9cf8c5062801d
ran1::LEU2,SPBC19C2.05:allele-12,cfa1ac27dc7acf6c
cut6::ura4+,SPAC56E4.04c:allele-3,b8f1a7f747cfebd1
kinl::LEU2,SPBC4F6.06:allele-3,246fd447dd1ab258
cdc8::ura4+,SPAC27F1.02c:allele-6,82154f75e067e7cd
cdc6::ura4+,SPBC336.04:allele-13,4852bbb0f1d3de60
rrk1::ura4+,SPNCRNA.128:allele-1,94cf820b62c19f47
upa2::ura4+,SPBC1289.02c:allele-3,9bde74c8ee3e19f5
cdc22::ura4+,SPAC1F7.05:allele-3,d3ef79e3f89a4ef2
suc22::ura4+,SPBC25D12.04:allele-3,d3ef79e3f89a4ef2
dis3::LEU2,SPBC26H8.10:allele-4,35c498b7a5ea246c
ppb1::ura4+,SPBP4H10.04:allele-3,ece9176a66feeefa
exol-1::ura4,SPBC29A10.05:allele-4,d059c2df7b2d6e91
snR88::kanR,SPSNORNA.53:allele-1,e9b6581da99a35cf
dcc1::ura4+,SPAC31A2.15c:allele-4,a5072a23ae384ac4
cki1::ura4+,SPBC1347.06c:allele-3,1b9692f34c4ac74a
dis2::ura4+,SPBC776.02c:allele-5,760d48a1560efbfc
ctf18::ura4+,SPBC902.02c:allele-3,a5072a23ae384ac4
ppa2::ura4+,SPBC16H5.07c:allele-5,760d48a1560efbfc
cki2::ura4+,SPBP35G2.05c:allele-4,1b9692f34c4ac74a
set1::Kan,SPCC306.04c:allele-3,9340627d98142a43
pcn1::ura4+,SPBC16D10.09:allele-12,68f20cc081d78bc5
Sucl::leu,SPBC1734.14c:allele-6,8a3e6d23ff2153d2
cut3::ura4+,SPBC146.03c:allele-3,384f03fb73e35a13
prp4::ura4+,SPCC777.14:allele-20,fcc0142cbab8adf6
prp10::ura4+,SPAC27F1.09c:allele-3,1088ee3f2681b5d2
sds21::LEU2,SPCC31H12.05c:allele-4,760d48a1560efbfc
pol1::ura4+,SPAC3H5.06c:allele-20,4852bbb0f1d3de60
orc5::ura4+,SPBC646.14c:allele-2,f203140be1f71f81
cdc12::ura4,SPAC1F5.04c:allele-3,7ced7ee21306a509
hsk1::ura4+,SPBC776.12c:allele-12,d0f47dc66e0ff761
nmt1::ura4,SPCC1223.02:allele-2,1bd720a71d7eff96
dna2::ura4+,SPBC16D10.04c:allele-4,32e5984a7be84674
pab1::ura4+,SPAC227.07c:allele-3,91d681458c26c2f0

**Comment by ValWood** [comment]
paa1::ura4+,SPAP8A3.09c:allele-2,91d681458c26c2f0
dsk1+::ura4,SPBC530.14c:allele-5,5a0095c9d74677e3  (REMOVE PLUS)
snu1::LEU2,SPSNRNA.01:allele-20,60969c954007a561

**Comment by mah11** [comment]
everything listed here now fixed
