### ISSUE TITLE
check should be single allele or multi

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#703]
fix
	inviable cell population	nup189c Δ (nup189n is expressed in nup189delta)	1
nup189n Δ (nup189c is expressed in nup189delta)

**Comment by ValWood** [comment]
nup189n-GFP,SPAC1486.05:allele-4,6ad90d4a01aee5f2
nup189c delta,SPAC1486.05:allele-3,6ad90d4a01aee5f2

**Comment by ValWood** [comment]
nup184-GFP,SPAP27G11.10c:allele-3,6ad90d4a01aee5f2
nup189n delta,SPAC1486.05:allele-2,6ad90d4a01aee5f2

**Comment by Antonialock** [comment]
changed the allele type and description to clarify, but cant specify exact residues as it is not specified in manuscript
