### ISSUE TITLE
move some of this allele description  detail to "background" ?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#711]
may be others...

![erh1_background](https://cloud.githubusercontent.com/assets/7359272/9982116/0e683aee-5fc9-11e5-8807-d1a8171cdf28.jpg)

**Comment by Antonialock** [comment]
changed to multi allele phenotypes, these are different from the single mutant

**Comment by ValWood** [comment]
Ah clearly, thats why they were done this way ;)
