### ISSUE TITLE
GAF 2.1

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#714]
It seems that the only change for GAF 2.1 is  the  , | so we can go ahead and do this?

I will need to change any pipes  I used in the with field with IPI to commas (pipe separated would be independent annotations in gaf?)...only a couple...

**Comment by mah11** [comment]
found and fixed two pipes for IPI

There are some for IGI as well, but "or" may be intended for those. I'll check over the next few days and change any that need it.

**Comment by ValWood** [comment]
I wouldn't bother, if I used they are always "or". Also is mainly for processes so it doesn't  affect the interpretation of the annotation as much as  the IPI
