### ISSUE TITLE
cdc2 extensions check

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#715]
check if more reg of BPs can be added to cdc2 kinase_activity direct targets using the part_of relation

**Comment by ValWood** [comment]
yep, your ahead of me

**Comment by ValWood** [comment]
I've been doing cdc2 so I'll steal this one. You have some other protein kinase tagget tickets...

**Comment by ValWood** [comment]
moved to new cdc2 ticket
https://github.com/pombase/curation/issues/963
