### ISSUE TITLE
specificity, cellular detoxification

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#719]
SPAC22F3.10c	gcs1	glutamate-cysteine ligase Gcs1	
SPAC3F10.04	gsa1	glutathione synthetase large and small subunit Gsa1	
SPCC737.09c	hmt1	vacuolar transmembrane transporter Hmt1	
SPBC2G5.06c	hmt2	sulfide-quinone oxidoreductase	
SPAC3H1.10	pcs2	phytochelatin synthetase	protein_coding	
SPAC23C11.14	zhf1	zinc ion transmembrane transporter Zhf1

move all from 
detxification of cadmium ion to cellular detoxification of cadmium ion

**Comment by ValWood** [comment]
so do these all have cellular detoxification now?

anyone know why gsa1 has the product line:
glutathione synthetase large and small subunit Gsa1??????

**Comment by mah11** [comment]
according to PMID:12734194, it encodes both (I only read the abstract)

**Comment by ValWood** [comment]
Ah got it, its cleaved. Could not compute

**Comment by Antonialock** [comment]
yeah I updated them in the other ticket. This is a duplicate?

**Comment by ValWood** [comment]
which other ticket? doesn't it only cover this part?
move all from 
detxification of cadmium ion to cellular detoxification of cadmium ion

**Comment by Antonialock** [comment]
I checked half of them and I had done all as part of this ticket
https://github.com/pombase/curation/issues/729

**Comment by Antonialock** [comment]
It looks the same as what you say in this ticket
"move all from
detxification of cadmium ion to cellular detoxification of cadmium ion"

**Comment by ValWood** [comment]
Ok, I was just starting to look at this one when you closed it. 
So you added "cellular detoxification" to all of the others? I was going to check the ontology to see if some could come from F-P links (as this might pull in more), but if you have done it the other way we are good for now.

**Comment by Antonialock** [comment]
I think all of them should have it...you can keep this open and we can check after next update

**Comment by ValWood** [comment]
nah its OK, they will fall through the slim if they aren't annotated.
