### ISSUE TITLE
structure papers to curate

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#721]
Is it worth sending out structure papers do you think?
Should we just do them?

I'll add the ones I didn't send out here for folks to grab if they want a quick paper to process:

http://curation.pombase.org/pombe/view/object/pub/10905?model=track
http://curation.pombase.org/pombe/view/object/pub/10776?model=track
http://curation.pombase.org/pombe/view/object/pub/10764?model=track
http://curation.pombase.org/pombe/view/object/pub/10968?model=track
http://curation.pombase.org/pombe/view/object/pub/10428?model=track

**Comment by Antonialock** [comment]
nah, they are generaly quick and easy and people that do nmr/crystallography don't tend to be hardcore molecular biologists (who it is more helpful to get input from I guess volume-wise)

**Comment by ValWood** [comment]
yeah, they are a bit detached from the biology often. Sometimes if there is clearly a lot of other data from the abstract I wall send them out to an obvoius "pombe collaborator/author".

Maybe we need a triage class to stash these structure PMIDs for us to pick up  when we feel like it rather than a ticket.... I'll request at some point soon

**Comment by Antonialock** [comment]
it's ok either way....I'm happy to have a special class to target "quick papers" but also happy to smash them as and when I come across them :-) In any case no one should spend extra time re-/classifying them.

**Comment by ValWood** [comment]
another
  http://curation.pombase.org/pombe/curs/4adda085ff88928f

**Comment by ValWood** [comment]
PMID: 21307936

**Comment by ValWood** [comment]
done 
http://curation.pombase.org/pombe/view/object/pub/10428?model=track

**Comment by ValWood** [comment]
http://curation.pombase.org/pombe/view/object/pub/11025?model=track

**Comment by ValWood** [comment]
we can  do this one too, as it looks from the abstract as though it only has a bit of pombe work:
http://curation.pombase.org/pombe/view/object/pub/11024?model=track

**Comment by ValWood** [comment]
PMID: 26901872
Crystal structure of eukaryotic translation initiation factor 2B.
(I think we could call tif212 "published' and make process annotations from IPI)

**Comment by ValWood** [comment]
PMID:26787556 (slx1-slx4)

**Comment by ValWood** [comment]
I'm assigning this one to you, can use these to bump the numbers more quickly as we get close to half way ;)

**Comment by Antonialock** [comment]
all done except http://curation.pombase.org/pombe/view/object/pub/10764?model=track
(no way to do tRNA mods yet)

new ticket for new structure papers :)

**Comment by Antonialock** [comment]
oh and the LSM one but that one is pending a canto fix...it's on the radar.

**Comment by ValWood** [comment]
excellent!
