### ISSUE TITLE
dcp2 check annotation

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#722]
annotated to "activator" MF but it is the phosphatase, dcp1 is the activator

**Comment by ValWood** [comment]
I think there was something weird about this. I remember a discussion. I think the enzyme itself is also regulatory. I seem to remember some connection to David Hill from this discussion? I will  dig around...

**Comment by ValWood** [comment]
I can't find anything searching my inbox. Did we discuss in a curator meeting at some point?

**Comment by Antonialock** [comment]
dont know...thought I'd just have a quick look at the reference as I just
did a paper saying that dcp1 reglates dcp2 so wanted to check if that
particular annotation had been attached to the wrong gene (or if it is
ok..).

Not a big deal, I'll just have a quick check.

On Mon, Oct 12, 2015 at 12:58 PM, Val Wood <notifications@github.com> wrote:

> I can't find anything searching my inbox. Did we discuss in a curator
> meeting at some point?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pombase/curation/issues/722#issuecomment-147460639>.
>



-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by Antonialock** [comment]
I've removed it. I think they say that the enzyme flips between different conformations (but not in a self-regulatory way, it's just pretty dynamic)  and that the regulators stabilize the active conformation.
