### ISSUE TITLE
refining and adding features based on Gagneur data

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#723]
This will involve
~i) refining UTRs~
ii) adding polycistronic transcripts (possibly later)
iii) refining nc RNA coordinates
iv) adding new non coding RNAs

First question, can anyone confirm that the next available ID space for non coding RNAs is SPNCRNA.1698?

**Comment by ValWood** [comment]
Second question (for Kim)

Do you remember creating the UTR annotation based on  different datasets.
We will discuss a the next planning meeting but  we might want to rerun with more and differently weighted datasets (deprioritisign the Rhind data).

Q do you still have the original datasets
Q Do you still have the scripts
Val

**Comment by ValWood** [comment]
The data is in  the dropbox

Data/Broad/UTRs/final
(the original, the lantermann and the Broad)

**Comment by Antonialock** [comment]
from RT 
the paper is just in press at MSB and should be out soon. Meanwhile you
can have a look at it at bioRxiv (http://dx.doi.org/10.1101/025585).

Best

Leonhard

**Comment by ValWood** [comment]
OK,  I've come round to the fact that we should not try to curate UTRs manually. It would be imposssible.
Let's discuss  at this weeks curator meeting.

**Comment by ValWood** [comment]
We decided we are going to

1. delete all UTR features relating to tracks (by Pubmed ID)
2. Host all datasets as tracks (announce)
3.  Create a track for the 'legacy features' from Artemis (this can happen later, these can hang about in Artemis)
4. Tell people

**Comment by ValWood** [comment]
@Antonialock This paper came through today. I just triaged it into "sequence feature or region"

We should  go ahead and delete the existing consensus UTRs. I will open a new ticket for that.

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/2289

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/2289

I will do this at the same time as this data goes live

**Comment by ValWood** [comment]
covered by https://github.com/pombase/curation/issues/2806
