### ISSUE TITLE
Duplicate 5'UTR on SPAC4A8.05c

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#726]
SPAC4A8.05c has two 5'UTRs which the loader doesn't like:

    FT   5'UTR           complement(2553666..2553696)
    FT                   /systematic_id="SPAC4A8.05c"
    FT                   /db_xref="PMID:21511999"
    FT                   /gene="myp2"
    FT                   /gene="myo3"
    FT                   /gene="SPAC4A8.05c"
    FT   5'UTR           complement(2553666..2553707)
    FT                   /systematic_id="SPAC4A8.05c"
    FT                   /db_xref="PMID:9398685"
    FT                   /gene="myp2"
    FT                   /gene="myo3"
    FT                   /gene="SPAC4A8.05c"

**Comment by ValWood** [comment]
I deleted the Rhind one in favour of the pollard one.
v

**Comment by kimrutherford** [comment]
Thanks!
