### ISSUE TITLE
A little detective work required for gamma-glutamyltransferase 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#728]
Hi Antonia

Do you still have this paper?
http://curation.pombase.org/pombe/curs/d461486b9fbbaa6e/ro/
(I can't access CJM)

Firs can you double check the activity they assayed? (I was changed the annotation to 
glutathione hydrolase activity and added a comment, based on
https://github.com/geneontology/go-annotation/issues/1324

but then I noticed the in vivo over expression phenotype also refers to gamma-glutamyltransferase activity, and that over-expression increases glutathione level, so it seems to do the opposite reaction in a physiological context

So we need to double check that Maria's comments also apply in pombe. The Metacyc diagram supports this. Also, although SGD have used the transpepetidase term, they have also annotated to the "glutathione catabolic process" which would also support the hydrolase annotation (I have mailed SGD too).

Thanks,

Val

**Comment by ValWood** [comment]
Also Ggt2 (a paper from same group)

**Comment by Antonialock** [comment]
Hmm, ok so I think it is best to remove the GO term since the assay is not physiologically relevant. Kept the phenotype terms though.

**Comment by ValWood** [comment]
I'm still confused by this. the pombe exp were in vivi weren't they? So  it sounds as though it might be.....
I have the name of another expert to contact. Will let you know. Could you monitor the GO ticket too.

Val
