### ISSUE TITLE
histone related

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#738]
Tel1    PMID:21098122   Tel1 phosphorylation of histone H2A at DSBs depends on its interaction with the Nbs1 subunit of MRN complex (52).

**Comment by ValWood** [comment]
I realise this ticket may need some disambiguation! None urgent ....

**Comment by mah11** [comment]
Yeah, it's not clear what the question or task is ...

**Comment by ValWood** [comment]
I guess this is just  priority paper for network building if it identifies histones as actual substrates of tel1

**Comment by ValWood** [comment]
Will add to general priorities
