### ISSUE TITLE
small-protein conjugating updates (quick)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#74]
check all F-box have

Original comment by: ValWood

**Comment by ValWood** [comment]
F-box proteins pof4,pof6,pop1,pop2 do not have
protein modification by small protein conjugation or removal

**Comment by ValWood** [comment]
pof14
pof4
need protein binding bridging

**Comment by ValWood** [comment]
pof4
pof6
pop1
pop2
need protein modification by small protein conjugation or removal

**Comment by ValWood** [comment]
done
