### ISSUE TITLE
move GO annotations down to cytoplasmic or mitochondrial translation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#744]
terms appearing in
http://curation.pombase.org/dumps/latest_build/logs/log.2015-10-26-22-24-44.excluded_go_terms
need moving to cytoplasmic or mitochondrial terms.
v

SPMITTRNAILE.02.1		GO:0006412	translation		PomBase
SPMITTRNAMET.02.1		GO:0006412	translation		PomBase
SPCTRNAASP.08.1		GO:0006414	translational elongation		PomBase
SPCTRNAGLN.06.1		GO:0006414	translational elongation		PomBase
SPCTRNASER.13.1		GO:0006414	translational elongation		PomBase
SPCTRNAGLY.12.1		GO:0006414	translational elongation		PomBase
SPCTRNAGLN.05.1		GO:0006414	translational elongation		PomBase
SPCTRNAHIS.04.1		GO:0006414	translational elongation		PomBase
SPCTRNAPRO.09.1		GO:0006414	translational elongation		PomBase
SPCTRNASER.12.1		GO:0006414	translational elongation		PomBase
SPCTRNAASN.06.1		GO:0006414	translational elongation		PomBase
SPCTRNASER.11.1		GO:0006414	translational elongation		PomBase
SPCTRNALYS.12.1		GO:0006414	translational elongation		PomBase
SPCTRNATHR.10.1		GO:0006414	translational elongation		PomBase
SPCTRNASER.10.1		GO:0006414	translational elongation		PomBase
SPCTRNAVAL.11.1		GO:0006414	translational elongation		PomBase
SPCTRNAPHE.05.1		GO:0006414	translational elongation		PomBase
SPCTRNALYS.11.1		GO:0006414	translational elongation		PomBase
SPCTRNAASP.07.1		GO:0006414	translational elongation		PomBase
SPCTRNAARG.13.1		GO:0006414	translational elongation		PomBase
SPCTRNAVAL.10.1		GO:0006414	translational elongation		PomBase
SPCTRNATHR.09.1		GO:0006414	translational elongation		PomBase
SPCTRNALEU.13.1		GO:0006414	translational elongation		PomBase
SPCTRNAGLU.10.1		GO:0006414	translational elongation		PomBase
SPCTRNALEU.12.1		GO:0006414	translational elongation		PomBase
SPCTRNATHR.08.1		GO:0006414	translational elongation		PomBase
SPCTRNAVAL.09.1		GO:0006414	translational elongation		PomBase
SPCTRNAARG.12.1		GO:0006414	translational elongation		PomBase
SPCTRNAASP.06.1		GO:0006414	translational elongation		PomBase
SPCTRNALYS.10.1		GO:0006414	translational elongation		PomBase
SPCTRNALEU.11.1		GO:0006414	translational elongation		PomBase
SPCTRNAARG.11.1		GO:0006414	translational elongation		PomBase
SPCTRNAASP.05.1		GO:0006414	translational elongation		PomBase
SPCTRNAARG.10.1		GO:0006414	translational elongation		PomBase
SPCTRNASER.09.1		GO:0006414	translational elongation		PomBase
SPCTRNAALA.12.1		GO:0006414	translational elongation		PomBase
SPCTRNAASN.05.1		GO:0006414	translational elongation		PomBase
SPCTRNAARG.09.1		GO:0006414	translational elongation		PomBase
SPCTRNASER.08.1		GO:0006414	translational elongation		PomBase
SPCTRNAGLY.11.1		GO:0006414	translational elongation		PomBase
SPCTRNAILE.09.1		GO:0006414	translational elongation		PomBase
SPCTRNAARG.08.1		GO:0006414	translational elongation		PomBase
SPCTRNASER.07.1		GO:0006414	translational elongation		PomBase
SPCTRNAPHE.04.1		GO:0006414	translational elongation		PomBase
SPCTRNAGLU.09.1		GO:0006414	translational elongation		PomBase
SPCTRNAGLY.10.1		GO:0006414	translational elongation		PomBase
SPCTRNAHIS.03.1		GO:0006414	translational elongation		PomBase
SPBTRNAASN.04.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLU.08.1		GO:0006414	translational elongation		PomBase
SPBTRNAASN.03.1		GO:0006414	translational elongation		PomBase
SPBTRNAASP.04.1		GO:0006414	translational elongation		PomBase
SPBTRNALEU.10.1		GO:0006414	translational elongation		PomBase
SPBTRNATYR.04.1		GO:0006414	translational elongation		PomBase
SPBTRNALYS.09.1		GO:0006414	translational elongation		PomBase
SPBTRNAPRO.08.1		GO:0006414	translational elongation		PomBase
SPBTRNASER.06.1		GO:0006414	translational elongation		PomBase
SPBTRNALEU.09.1		GO:0006414	translational elongation		PomBase
SPBTRNAPRO.07.1		GO:0006414	translational elongation		PomBase
SPBTRNATHR.07.1		GO:0006414	translational elongation		PomBase
SPBTRNALEU.08.1		GO:0006414	translational elongation		PomBase
SPBTRNAPHE.03.1		GO:0006414	translational elongation		PomBase
SPBTRNAPRO.06.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLY.09.1		GO:0006414	translational elongation		PomBase
SPBTRNAASN.02.1		GO:0006414	translational elongation		PomBase
SPBTRNAPRO.05.1		GO:0006414	translational elongation		PomBase
SPBTRNAPRO.04.1		GO:0006414	translational elongation		PomBase
SPBTRNATRP.03.1		GO:0006414	translational elongation		PomBase
SPBTRNAARG.07.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLU.07.1		GO:0006414	translational elongation		PomBase
SPBTRNAVAL.08.1		GO:0006414	translational elongation		PomBase
SPBTRNAALA.11.1		GO:0006414	translational elongation		PomBase
SPBTRNAILE.08.1		GO:0006414	translational elongation		PomBase
SPBTRNALYS.08.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLY.08.1		GO:0006414	translational elongation		PomBase
SPBTRNALEU.07.1		GO:0006414	translational elongation		PomBase
SPBTRNATYR.03.1		GO:0006414	translational elongation		PomBase
SPBTRNAILE.07.1		GO:0006414	translational elongation		PomBase
SPBTRNAALA.10.1		GO:0006414	translational elongation		PomBase
SPBTRNAVAL.07.1		GO:0006414	translational elongation		PomBase
SPBTRNAVAL.06.1		GO:0006414	translational elongation		PomBase
SPBTRNAALA.09.1		GO:0006414	translational elongation		PomBase
SPBTRNAILE.06.1		GO:0006414	translational elongation		PomBase
SPBTRNAARG.06.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLU.06.1		GO:0006414	translational elongation		PomBase
SPBTRNAVAL.05.1		GO:0006414	translational elongation		PomBase
SPBTRNAALA.08.1		GO:0006414	translational elongation		PomBase
SPBTRNAILE.05.1		GO:0006414	translational elongation		PomBase
SPBTRNALYS.07.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLY.07.1		GO:0006414	translational elongation		PomBase
SPBTRNALEU.06.1		GO:0006414	translational elongation		PomBase
SPBTRNATYR.02.1		GO:0006414	translational elongation		PomBase
SPBTRNAASN.01.1		GO:0006414	translational elongation		PomBase
SPBTRNATHR.06.1		GO:0006414	translational elongation		PomBase
SPBTRNALEU.05.1		GO:0006414	translational elongation		PomBase
SPBTRNAARG.05.1		GO:0006414	translational elongation		PomBase
SPBTRNAHIS.02.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLU.05.1		GO:0006414	translational elongation		PomBase
SPBTRNASER.05.1		GO:0006414	translational elongation		PomBase
SPBTRNATRP.02.1		GO:0006414	translational elongation		PomBase
SPBTRNALYS.06.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLY.06.1		GO:0006414	translational elongation		PomBase
SPBTRNAHIS.01.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLN.04.1		GO:0006414	translational elongation		PomBase
SPBTRNAARG.04.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLY.05.1		GO:0006414	translational elongation		PomBase
SPBTRNAALA.07.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLY.04.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLN.03.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLN.02.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLN.01.1		GO:0006414	translational elongation		PomBase
SPBTRNAGLY.03.1		GO:0006414	translational elongation		PomBase
SPATRNASER.04.1		GO:0006414	translational elongation		PomBase
SPATRNAASP.02.1		GO:0006414	translational elongation		PomBase
SPATRNAARG.03.1		GO:0006414	translational elongation		PomBase
SPATRNAALA.06.1		GO:0006414	translational elongation		PomBase
SPATRNATHR.05.1		GO:0006414	translational elongation		PomBase
SPATRNAASP.01.1		GO:0006414	translational elongation		PomBase
SPATRNASER.03.1		GO:0006414	translational elongation		PomBase
SPATRNALEU.04.1		GO:0006414	translational elongation		PomBase
SPATRNAALA.05.1		GO:0006414	translational elongation		PomBase
SPATRNAGLU.04.1		GO:0006414	translational elongation		PomBase
SPATRNAILE.04.1		GO:0006414	translational elongation		PomBase
SPATRNAILE.03.1		GO:0006414	translational elongation		PomBase
SPATRNAGLU.03.1		GO:0006414	translational elongation		PomBase
SPATRNAALA.04.1		GO:0006414	translational elongation		PomBase
SPATRNAPHE.02.1		GO:0006414	translational elongation		PomBase
SPATRNAARG.02.1		GO:0006414	translational elongation		PomBase
SPATRNAVAL.04.1		GO:0006414	translational elongation		PomBase
SPATRNAPHE.01.1		GO:0006414	translational elongation		PomBase
SPATRNACYS.03.1		GO:0006414	translational elongation		PomBase
SPATRNALEU.03.1		GO:0006414	translational elongation		PomBase
SPATRNATRP.01.1		GO:0006414	translational elongation		PomBase
SPATRNAARG.01.1		GO:0006414	translational elongation		PomBase
SPATRNATHR.04.1		GO:0006414	translational elongation		PomBase
SPATRNAALA.03.1		GO:0006414	translational elongation		PomBase
SPATRNALYS.05.1		GO:0006414	translational elongation		PomBase
SPATRNASER.02.1		GO:0006414	translational elongation		PomBase
SPATRNATHR.03.1		GO:0006414	translational elongation		PomBase
SPATRNALEU.02.1		GO:0006414	translational elongation		PomBase
SPATRNALYS.04.1		GO:0006414	translational elongation		PomBase
SPATRNAILE.02.1		GO:0006414	translational elongation		PomBase
SPATRNACYS.02.1		GO:0006414	translational elongation		PomBase
SPATRNALYS.03.1		GO:0006414	translational elongation		PomBase
SPATRNATHR.02.1		GO:0006414	translational elongation		PomBase
SPATRNAGLY.02.1		GO:0006414	translational elongation		PomBase
SPATRNAVAL.03.1		GO:0006414	translational elongation		PomBase
SPATRNAILE.01.1		GO:0006414	translational elongation		PomBase
SPATRNATYR.01.1		GO:0006414	translational elongation		PomBase
SPATRNALYS.02.1		GO:0006414	translational elongation		PomBase
SPATRNALYS.01.1		GO:0006414	translational elongation		PomBase
SPATRNAGLY.01.1		GO:0006414	translational elongation		PomBase
SPATRNATHR.01.1		GO:0006414	translational elongation		PomBase
SPATRNALEU.01.1		GO:0006414	translational elongation		PomBase
SPATRNAPRO.03.1		GO:0006414	translational elongation		PomBase
SPATRNACYS.01.1		GO:0006414	translational elongation		PomBase
SPATRNAPRO.02.1		GO:0006414	translational elongation		PomBase
SPATRNAALA.02.1		GO:0006414	translational elongation		PomBase
SPATRNASER.01.1		GO:0006414	translational elongation		PomBase
SPATRNAGLU.02.1		GO:0006414	translational elongation		PomBase
SPATRNAALA.01.1		GO:0006414	translational elongation		PomBase
SPATRNAGLU.01.1		GO:0006414	translational elongation		PomBase
SPATRNAVAL.02.1		GO:0006414	translational elongation		PomBase
SPATRNAVAL.01.1		GO:0006414	translational elongation		PomBase
SPATRNAPRO.01.1		GO:0006414	translational elongation		PomBase

**Comment by mah11** [comment]
per curator meeting chat, assumed all nuclear-encoded tRNAs can be annotated to "cytoplasmic (i.e. cytosolic) tranlation elongation

done
