### ISSUE TITLE
log fixes which may not be in logs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#747]
migrrate to "overexpression" allele:
 failed to store extension in 3b98520c5f6ca92f: upgrade script can't handle: expression=overexpression
failed to store extension in 3b98520c5f6ca92f: upgrade script can't handle: expression=overexpression
failed to store extension in efa1583765ddce89: upgrade script can't handle: expression=overexpression

heterologous system need to be capture in Artemis as the ID of the heterologous gene should be in the 'with filed' (and IGI should be used)
failed to store extension in 0b3d460aeaeeeb91: upgrade script can't handle: qualifier=heterologous_system
failed to store extension in 0b3d460aeaeeeb91: upgrade script can't handle: qualifier=heterologous_system

**Comment by Antonialock** [comment]
I 'fixed' these:
migrrate to "overexpression" allele:
failed to store extension in 3b98520c5f6ca92f: upgrade script can't handle: expression=overexpression
failed to store extension in 3b98520c5f6ca92f: upgrade script can't handle: expression=overexpression
failed to store extension in efa1583765ddce89: upgrade script can't handle: expression=overexpression

**Comment by ValWood** [comment]
I  migrated the heterologous_system ones to Artemis

NOTE: we can only do heterologous_system in Artemis (i) needs to be IGI with ID of complementing gene products ii) can no longer use this qualifier in Canto)
