### ISSUE TITLE
possible background tweaks

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#748]
1 Cnp3C-TEV (kinetochore localized protease) (other allele, this affects exp outcome, not really background?)
      1 ergerg (?)
      2 diploid (how are  we doing these, most are in allele description 'other')
      1 hem1-delta (that doesn't look like background (hem1 is inviable double mutant?)
      1 nda3-KM311 (this mutant has affects at permissive t, double mutant?)
      2 pat1as2 standardize-> others use pat1-as2
      2 WT background (remove 'background, just put WT?)

**Comment by Antonialock** [comment]
1 nda3-KM311 (this mutant has affects at permissive t, double mutant?) 
this is often used to synchronize cells at meta/ana?
 
I dont think we should just "tweak" these...would we have put them in the background unless we thought that they were most appropriate there?

**Comment by ValWood** [comment]
OK I was wavering about the nda3 one, that is OK as background.

I can't see how hem1 can be though, its inviable?
The others are syntax issues
What is ergerg?

**Comment by ValWood** [comment]
4 186e8e06649ff2d7        cdc25-22
      1 31390a94c8f8643a        leu1-32, ura4-294
      1 330f117d21a8480a        nda3-KM311
      1 35bfa0019d25c550        ergerg
      1 6dda6bff1b0363f6        h90
      2 9f25f26d17f2ec78        pat1as2
      6 9f25f26d17f2ec78        pat1-as2
      2 bbe966c7c31d9042        diploid
      1 cfa1ac27dc7acf6c        h90
      1 d17a6f8397b4b058        hem1-delta
      2 d800c02f9eed68d9        WT background
      1 e13e49a2df6b7722        Cnp3C-TEV (kinetochore localized protease)

**Comment by Antonialock** [comment]
The hem1􏰁 deletion is lethal for S. pombe (9), unless exogenous ALA is provided, allowing heme biosynthesis from step 2 to proceed. An additional way to maintain hem1􏰁 cells alive is to add exogenous hemin (heme chloride), thereby fostering cells to use their heme uptake sys- tem. The hem1􏰁 mutant strain can thus be used to selectively block heme biosynthesis by controlling growth medium com- position (absence of ALA), thereby allowing the possibility of investigating the mechanism of exogenous heme acquisition.

**Comment by ValWood** [comment]
OK yes doh. Clearly will be lots like this.
