### ISSUE TITLE
Duplicate term names in mini-ontologies/pombe_mini_PR.obo

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#750]
There are some duplicates in mini_PR.  I made this change:

 [Term]
 id: PR:000034361
-name: glutaredoxin-3
+name: glutaredoxin GrxC
 def: "A protein that is a translation product of the Escherichia coli K-12 grxC gene or a 1:1 ortholog thereof." [PRO:DNx]
 comment: Category=gene.
 synonym: "grx3" EXACT []

then notice these duplicates:

      2 name: 54S ribosomal protein L23, mitochondrial (Schizosaccharomyces pombe 972h-)
      2 name: 54S ribosomal protein L27, mitochondrial (Schizosaccharomyces pombe 972h-)
      2 name: 54S ribosomal protein L9, mitochondrial (Schizosaccharomyces pombe 972h-)
      2 name: alpha-glucosidase (Schizosaccharomyces pombe 972h-)
      2 name: arginase (Schizosaccharomyces pombe 972h-)
      2 name: argininosuccinate lyase (Schizosaccharomyces pombe 972h-)
      2 name: brefeldin A resistance protein (Schizosaccharomyces pombe 972h-)
      2 name: glutathione S-transferase C1183.02 (Schizosaccharomyces pombe 972h-)
      2 name: invertase (Schizosaccharomyces pombe 972h-)
      2 name: malic acid transport protein (Schizosaccharomyces pombe 972h-)
      2 name: mannose-1-phosphate guanyltransferase (Schizosaccharomyces pombe 972h-)
      2 name: MHF histone-fold complex subunit 1 (Schizosaccharomyces pombe 972h-)
      2 name: peptidyl-prolyl cis-trans isomerase (Schizosaccharomyces pombe 972h-)
      2 name: trehalose-phosphatase (Schizosaccharomyces pombe 972h-)
      2 name: ubiquitin-60S ribosomal protein L40 (Schizosaccharomyces pombe 972h-)
      2 name: ubiquitin carboxyl-terminal hydrolase 1 (Schizosaccharomyces pombe 972h-)
      2 name: ubiquitin carboxyl-terminal hydrolase 2 (Schizosaccharomyces pombe 972h-)
      2 name: uncharacterized membrane protein C6F6.13c (Schizosaccharomyces pombe 972h-)
      2 name: UTP--glucose-1-phosphate uridylyltransferase (Schizosaccharomyces pombe 972h-)

From the command:
   grep name: mini-ontologies/pombe_mini_PR.obo | sort | uniq -c | sort -n

**Comment by ValWood** [comment]
I don't understand what these are...

**Comment by mah11** [comment]
Oops. Darren at PR said the duplicate names got fixed a month or two ago ... but then I forgot a key step in my update procedure last Friday. Try it again now, and if it's OK we can close this.

**Comment by mah11** [comment]
Should be fixed - no duplicate names in the file now.
