### ISSUE TITLE
abnormal sporulation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#756]
How many direct annotations do we have to "abnormal sporulation"?
(i.e. if you add it to the filter...I would do it to see, but I don't know where it is!)

**Comment by mah11** [comment]
grep on phaf from latest chado build says 23

**Comment by ValWood** [comment]
OK I'll take this ticket and review at some point. I think many/some could be me being a numpty...or old...

**Comment by ValWood** [comment]
It wasn't what I thought.Looks OK,
