### ISSUE TITLE
orc4 topological change

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#757]
Is orc4 definitlly a 'topological change' althought he abstract also refers to a topological change, caused by top1, but then seems to describe a geometric change affected by orc4  "alteration of the DNA structure due to its wrapping around spOrc4p"

We also show that treatment of the spORC (spOrc4p)-ars1 complex with topoisomerase I induced a negative shift in the topoisomer distribution. These findings suggest that the binding of spORC to origin DNA alters the structure of the DNA. Thus, in the case of spORC, due to its unusual spOrc4p, at least two factors are likely to influence ars1 activation. These include the selective binding of the complex to A- and T-rich regions and the alteration of the DNA structure due to its wrapping around spOrc4p.

**Comment by mah11** [comment]
The gel in figure 4 definitely shows a topological difference between Orc4 present and Orc4 absent. So while I wouldn't annotate orc4 to a topoisomerase MF term, it does look like it makes some contribution to a topological change process.

**Comment by ValWood** [comment]
So you can  see a change in linking number from a gel? I don't get that (well you would see a topological change even if the DNA broke?)
.... but then for me DNA metabolism .....pffft

**Comment by ValWood** [comment]
OK that's what it says......

**Comment by mah11** [comment]
With gels run under centain conditions, yes. I've even done a few, waaay back in the day (undergrad!).

**Comment by mah11** [comment]
closing because it's basically OK
