### ISSUE TITLE
lys7 GO:0008897 evidence

### ISSUE THREAD

**Issue by mah11** [pombase/curation#760]
This annotation gets flagged by the owltools/Jenkins checks because we aren't supposed to use IPI for catalytic activity MF terms (see http://geneontology.org/page/annotation-quality-control-checks#0000007).

I'll change it to IDA in the v56 GAF, because that's what the lys7 gene page has now, and if GO doesn't want IPI here we'll have to make do. If nobody objects here in a day or two, I'll make the same change in the Canto session. Meanwhile, assigning to Antonia because she did the Canto curation.

Also, I didn't spot the data for the physical interaction, but that may be becuse I just skimmed over it looking for the enzyme assays.

    #------------
    # GO_AR:0000007 IPI should not be used with catalytic activity molecular
    function terms Warning count:  1
    33711   GO_AR:0000007   Warning IPI should not be used with catalytic
    activity molecular function terms PomBase SPAC17C9.02c    lys7            GO:0008897     PMID:15546125   IPIPomBase:SPAP7G5.04c     F       alpha-aminoadipate reductase phosphopantetheinyl transferase Lys7               protein taxon:4896
    20151001        PomBase
    #------------

**Comment by Antonialock** [comment]
ah, yeah, changed it to IDA + has substrate lys1, this seems to be a better way to represent it anyway.

**Comment by mah11** [comment]
sounds good; thanks
