### ISSUE TITLE
fkh2 and sep1

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#762]
fkh2 and sep1 are annotated to GO:0097221 - M/G1 phase-specific MADS box-forkhead transcription factor complex
it doesn't seem like they are part of this ocmplex from PMID:15509866 (but mbx1 is)

**Comment by mah11** [comment]
by PMID:18057023 it was sounding like they are in the complex ... that's what's cited for the annotations (done in Artemis; paper's untouched in Canto)

**Comment by Antonialock** [comment]
yeah I put it on here to have a look later

**Comment by ValWood** [comment]
Its defined

"A protein complex that contains a MADS-box protein and two forkhead domain proteins, and binds to and regulates transcription from promoters of genes transcribed during the M/G1 transition of the cell cycle. In Schizosaccharomyces pombe, the complex contains the MADS-box protein Mbx1 and two forkhead proteins, Sep1 and Fkh2." [GOC:mah, PMID:18057023]

so I think its OK (or the GO term need obsoleting, so will close for now, but feel free to take the paper ;)
