### ISSUE TITLE
GO slim unexplained annotation drops between stage and dev

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#765]
membrane organization  17
DNA replication 9

**Comment by ValWood** [comment]
DNA replication non issue, its transposons (although that does imply a change in pareenage at GO?)

**Comment by ValWood** [comment]
OK the membrane drop is largely due to a drop we see because 
SNAP receptor activy, which has F-P link to membrane organization (via membrane fusion).

We wouldn't have picked this up, but it was  included inadvertently last month when Mark included  the MF in the GO slim. The point here was that Mark didn't need to do this, and we only wanted to show process slim headings on the process terms, and we *should*already  of had all the process annotations. 

So, SNAP receptor activity  *should* have an F-P annotation to 
GO:0061025 membrane fusion

This is weird, because we do pick up quite a lot of F-P annotations
Possible causes

i) GO aren't updating
ii) GOA aren't updating
(I don't  *think* it can be us, as I think we get the F-P links from GOA?...double check that)

relation added
2015-01-12	Added	RELATION	part of GO:0061025 (membrane fusion)

Kim, first could you check the GOA files. I'll upload a gene list in a sec...

**Comment by ValWood** [comment]
SPBC31E1.04	
SPAC4G8.10
SPBC8D2.14c
SPAC823.05c
SPBC2A9.08c
SPCC895.04c
SPBC3B9.10
SPBC36B7.07	
SPAP14E8.03
SPAC23A1.15c
SPBC13G1.11
SPAC6F12.03c
SPAC6G9.11
SPAC31A2.13c
SPAC23C4.13
SPAC17G6.07c

**Comment by ValWood** [comment]
should have GO:0061025 membrane fusion from GOC in  GOA file

**Comment by ValWood** [comment]
same story
phospholipid-translocating ATPase activity FP part_of phospholipid translocation

**Comment by mah11** [comment]
I'm 99% certain that the GO:0061025 annotation problem is just a synchronization issue.

GOA has nothing to do with our MF-BP annotations. We get F-P inferences from the gene_association.pombase.inf.gaf file, which is generated by the owltools processes run for the Jenkins checks. At present Kim must be using the .inf.gaf from the v55 release, which doesn't have the inferred GO:0061025 annotations (see 
http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/95)/. But when I ran the owltools checks locally for v56, the annotations get inferred, so we should pick them up in due course.

If the GAF we commit for v56 doesn't yield all the annotations we expect in its .inf.gaf we can squawk to GO about it.

**Comment by ValWood** [comment]
Hmm, then something smells funny to me because these links have been in GO for ages.... anyway we'll watch this space...

**Comment by mah11** [comment]
Yup, whatever's going awry is happening at the GO inference step. If the problem doesn't magically sort itself when I commit the v56 GAF I'll holler at GO and post a linky here.

**Comment by kimrutherford** [comment]
Is there anything I need to do on this at the moment?

**Comment by ValWood** [comment]
Nope. Odd I thought there was another comment on this ticket.
Anyway its a wait and see....
val

**Comment by mah11** [comment]
https://github.com/geneontology/go-annotation/issues/1336

(I also just realized that the inferred-GAF anomaly has plagued the last few Jenkins runs, at least as far back as v54. So that problem wouldn't explain slim count changes from v55 to v56.)

**Comment by ValWood** [comment]
something isn't updating here because SPBC31E1.04 still has no annotation to membrane fusion
even though it is encoded in the F-P links...

**Comment by mah11** [comment]
It's the same problem as before -- GO hasn't acted on the ticket I opened two months ago (linked above).

**Comment by ValWood** [comment]
We can close this. Problem is at GO
