### ISSUE TITLE
annotation prioirty, Fleigal papers

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#773]
As Larry generously approved the name change, I said we would curate his papers as a priority. Some are probably done already.

PMID: 8431459
PMID: 8232284
PMID: 9094438
PMID: 9622480
PMID: 9655186
PMID: 14674689
PMID: 15724441
PMID: 16091782
PMID: 18629612
PMID: 19171118
PMID: 23836910
PMID: 24104454

Can somebody take this ticket. My annotation proiority is still chromosome segregation, especially up to the Noctua meeting...

**Comment by ValWood** [comment]
also, from this sod22 annotations shouldn't be from orthology:

Summary of substrate specificity from Paul Young:
We all agree that sod2 and sod22 belong to the broad family of  antiporters capable of transporting Na.  Pombe and a number of other yeast have a sod2 and a sod22 equivalent.   Sod2 is Na specific (+Li); Sod22 carries K and Na.  Nha1, a bacterial antiporter name,  in budding yeast is more like Sod22 in pombe with respect to substrate specificity and physiological function. Nha1 is not the best comparator for Sod2  given its  substrate specificity for K and Na and its role in ion homeostasis like Sod22 vs Sod2 which is Na specific and also detoxifies its analogue Li in pombe and some other yeasts. Many yeasts have these two antiporters in their plasma membranes with budding yeast the exception (with only one) rather than the rule.  This has been directly demonstrated: Papouskovak K and Sychrova H 2007 Schizosaccharomyces pombe possesses two plasma membrane alkali metal cation /H1 antiporters differing in their substrate specificity. FEMS Yeast Res 7 (2007) 188–195.  With respect to ion specificity Sod2 is more similar to Nhe1, the mammalian Na/H antiporter, although they normally function in opposite directions – pombe Na out; mammals Na in – but antiporters act in response to ion gradients and work in both directions, or even Sos1 in Arabidopsis which works in the Sod2 direction and provides Na tolerance.  Sod2 and its functional orthologues in yeasts are characterized by their shorter length (468 aa) than the budding yeast Nha1 (841) and the Sod22’s of several yeasts.

**Comment by Antonialock** [comment]
8431459
8232284
9622480
9655186
15724441
16091782
18629612
23836910

**Comment by Antonialock** [comment]
all done

**Comment by ValWood** [comment]
FANTASTIC!  THAT WAS FAST!

**Comment by ValWood** [comment]
which are the ones you just processed, I'd like to send to Larry.
