### ISSUE TITLE
extension corrections for GO:790/GO:61638 in PMID:15369671 & PMID:24710126

### ISSUE THREAD

**Issue by mah11** [pombase/curation#774]
Two sessions have annotations to GO:0000790 'nuclear chromatin' with the extension occurs_at(GO:0061638) (GO:0061638 is 'CENP-A containing chromatin').

This isn't allowed, for two reasons:

- A cellular component isn't an event that can occur, so no CC annotation can use the relation occurs_at (or occurs_in).

- The correct extension to use with CC 'chromatin' terms is coincident_with, but its range only includes SO IDs and MOD gene/feature IDs.

This is therefore a case that's best handled by pre-composing a GO term that covers both parts. Accordingly, I have TG'd GO:1904834 "nuclear CENP-A containing chromatin".

I'm happy to update the sessions when the new term reaches Canto as part of the v57 log work; I've just included the reasoning for everyone's future reference.

**Comment by ValWood** [comment]
I changed this *from*  CENP-A containing chromatin

It isn't part of "CENP-A containing chromatin", it  is "coincident with" CENP-A containing chromatin
so I'll change it to the appropriate SO term 
SO:0001796

**Comment by ValWood** [comment]
Ah which 2 sessions were they?

**Comment by mah11** [comment]
That doesn't make sense -- does the chromatin where these proteins are found contain CENP-A or not? How can chromatin be coincident with chromatin?

Coincident_with is NOT for use with CC terms in the extension -- as I said above, you can use coincident_with(SO:nnn) or coincident_with(MOD ID). It's chromatin at the location of some sequence (a specific feature or a feature type).

That said, chromatin coincident_with part or all of the centromere would be semantically sensible, so GO:0000790 coincident_with(SO:0001796) woud be fine (especially if these proteins aren't at CENP-A-containing chromatin, in which case it's misleading to use GO:0061638 at all).

**Comment by mah11** [comment]
the session IDs are in the latest Canto log
