### ISSUE TITLE
after V 46 upate , check intersect for small cells

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#78]
check intersect between
viable small vegetative cell.
and premature mitosis

Also check when "viable small vegetative cells" can occur in any other circumstances

Original comment by: ValWood

**Comment by ValWood** [comment]
Closing as redundant as covered by
https://sourceforge.net/p/pombase/fission-yeast-phenotype/1770/
and no point having a ticket in 2 places.

**Comment by Antonialock** [comment]
you are linking to sourceforge there
