### ISSUE TITLE
Deleted dubious gene in 7de65253495d383a

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#781]
SPAC1D4.07c has been deleted from the contig files due to being dubious but it is referred to in this session:
  http://curation.pombase.org/pombe/curs/7de65253495d383a/feature/gene/view/32/ro

The curation data loader currently fails if a gene is missing (that's a bug).

Could someone fix that session?  (No rush of course)

**Comment by kimrutherford** [comment]
> The curation data loader currently fails if a gene is missing (that's a bug).

I've made an issue for that: pombase/pombase-chado#510

**Comment by mah11** [comment]
I deleted the gene from that session.

**Comment by kimrutherford** [comment]
> I deleted the gene from that session.

Thanks!

I think SPCC622.05 needs deleting too.

**Comment by mah11** [comment]
dead easy, therefore done
