### ISSUE TITLE
Why do lots of annotations in the contig files have the date "19700101"?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#782]
It seems a bit suspicious that the only "date=" qualifier before 2000 is "19700101".  Is that expected?

**Comment by mah11** [comment]
I asked Val about this shortly after I started, and she said that's the date she plugged in for just about anything that didn't have a PMID xref in the GeneDB era.

(She didn't explain why she picked the UNIX epoch start date instead of, say, the date she put the annotation into Artemis; I decided not to fuss about that.)

**Comment by kimrutherford** [comment]
Thanks for that.  I'm surprised I hadn't noticed before.

Those dates are stored in Chado but I don't think we should do that since 19700101 is meaningless.

**Comment by ValWood** [comment]
I didn't pick this date. For some reason GeneDB required a date and this was chosen across the board so it was not confused with a  real date AFAIR. If we don't need it, don't store it....

Is this date in the GO GAF for some annotations (I have no idea?)

**Comment by kimrutherford** [comment]
> If we don't need it, don't store it....

OK, thanks.


> Is this date in the GO GAF for some annotations (I have no idea?)

There are no GO annotations in Chado with that date so so the GAF is fine.  Here are the counts of which annotations have that date:

 warning                  |    26
 genome_org               |    78
 gene_ex                  |    37
 PSI-MOD                  |    30
 name_description         |    63
 species_dist             |   635
 pathway                  |    20
 m_f_g                    |    16
 complementation          |    22
 disease_associated       |    56
 subunit_composition      |     4
 fission_yeast_phenotype  |   274
 PomBase family or domain |  1399
 cat_act                  |     2
 sequence                 |   788
 misc                     |    20

**Comment by Antonialock** [comment]
I don't know if this has anything to do with it but I can't store today's date in a controlled curation
20160106 = I get an error message saying there is a wualifier problem but oddly 20160105 works fine

**Comment by Antonialock** [comment]
i.e. I don't know if you made any fix that had an impact on this.

this is the error I get:
Cannot apply changes because of a qualifier error: failed to read a qualifier name from this string: term=disease associated, fatty acid metabolism disorder; date=20160106”

**Comment by mah11** [comment]
The problem there isn't the date, it's that the closing double quote is a fancy one (pasted, I guess).
" will work; ” won't

**Comment by Antonialock** [comment]
Weird! I'm pasting them all from a text file where I'm just changing the 5 for a 6 (not touching the quotation mark)....nevermind then and I'll just pretend the date is the 5th for this data :-)

**Comment by mah11** [comment]
Hmm, check whether your text editor is automagically substituting the fancy quotes when you type plain ones - e.g. in Apple TextEdit, see if Edit menu -> Substitutions -> Smart Quotes is ticked. It may even be doing something too-damn-clever where it only changes quotes if you also edit something else.

**Comment by Antonialock** [comment]
aha, thanks!
