### ISSUE TITLE
should  probably be FYPO:0005070

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#787]
septation following abolished mitotic sister chromatid separation, with mononucleate and anucleate cell formation FYPO:0005070
not
FYPO:0002000 'inviable septated mononucleate vegetative cell'.

SPAPB1A10.09	ase1	antiparallel microtubule cross-linking factor Ase1	
SPCC5E4.04	cut1	separase/separin	protein_coding
SPBC14C8.01c	cut2	securin, sister chromatid separation inhibitor	
SPAC17C9.13c	cut8	tethering factor for nuclear proteasome Cut8	
SPAC3H5.06c	pol1	DNA polymerase alpha catalytic subunit	
SPBC216.05	rad3	ATR checkpoint kinase Rad3	
SPAC1565.06c	spg1	GTPase Spg1

**Comment by ValWood** [comment]
as part of 
https://github.com/pombase/fypo/issues/2429#issuecomment-172575907
I'm also checking

FYPO:0003166

ensembl_id	name	description
SPBC146.07	prp2	U2AF large subunit (U2AF-59) 
SPAC1782.09c	clp1	Cdc14-related protein phosphatase Clp1/Flp1 
SPAC6F12.15c	cut9	anaphase-promoting complex, TPR lobe subcomplex subunit Cut9/Apc6 
SPAC13D6.05	alp11	tubulin specific chaperone cofactor B 
SPBC11B10.09	cdc2	cyclin-dependent protein kinase Cdk1/Cdc2 
SPAC19G12.01c	cut20	anaphase-promoting complex, platform subcomplex scaffold subunit Apc4/Cut20 
SPAC1A6.04c	plb1	phospholipase B homolog Plb1 [Source:PomBase;Acc:SPAC1A6.04c]
SPBC6B1.04	mde4	microtubule-site clamp monopolin complex subunit Mde4 
SPBC26H8.07c	nda3	tubulin beta Nda3 
SPBC800.05c	atb2	tubulin alpha 2 
SPBC428.18	cdt1	replication licensing factor Cdt1 
SPBC17D11.06	spp2	DNA primase large subunit Spp2 
SPAC6F12.14	cut23	anaphase-promoting complex, TPR lobe subcomplex subunit Apc8 
SPATRNAALA.02	scn2	tRNA Alanine 
SPAPB1E7.02c	mcl1	DNA polymerase alpha accessory factor Mcl1 
SPAC23D3.02	rfc2	DNA replication factor C complex subunit Rfc2 
SPATRNAALA.03	scn1	tRNA Alanine 
SPAC24H6.05	cdc25	M phase inducer tyrosine phosphatase Cdc25 
SPAC3H5.06c	pol1	DNA polymerase alpha catalytic subunit 
SPAC9E9.08	rad26	ATRIP, ATR checkpoint kinase regulatory subunit Rad26 

SPAPB24D3.01	toe3	transcription factor (predicted) 
SPAC11D3.06	SPAC11D3.06	MatE family transmembrane transporter (predicted)
SPBC3H7.05c	SPBC3H7.05c	mitochondrial Membrane Bound O-Acyl Transferase (MBOAT) family 
SPCC417.02	dad5	DASH complex subunit Dad5

**Comment by ValWood** [comment]
This is what I think FYPO:0003166 should look like
(arrow head, clear binucleate compartment with anucleate compartment. Its septated but still a single cell)

This is from the prp2 paper:

![fypo-0003166](https://cloud.githubusercontent.com/assets/7359272/12397374/bb11a106-be04-11e5-83c0-5e561803877e.jpg)

**Comment by ValWood** [comment]
I checked this paper
http://curation.pombase.org/pombe/curs/94e20d207ffa7a12/ro/
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3730917/
SPAPB24D3.01	toe3	transcription factor (predicted) 
SPAC11D3.06	SPAC11D3.06	MatE family transmembrane transporter (predicted)
SPBC3H7.05c	SPBC3H7.05c	mitochondrial Membrane Bound O-Acyl Transferase (MBOAT) family 
SPCC417.02	dad5	DASH complex subunit Dad5 
but I couldn't see this phenotype. @Antonialock  could you check and confirm?

**Comment by ValWood** [comment]
Assigning to you to  @Antonialock could you confirm phenotype, then assign back to me for completion

**Comment by ValWood** [comment]
all of these already have this annotation on stage?
Not sure if this is a consequence of current parentage though?
FYPO:0003166 - septation following abnormal chromosome segregation, with binucleate and anucleate cell formation 

SPBC146.07 prp2 U2AF large subunit (U2AF-59) 
SPAC1782.09c clp1 Cdc14-related protein phosphatase Clp1/Flp1 
SPAC6F12.15c cut9 anaphase-promoting complex, TPR lobe subcomplex subunit Cut9/Apc6 
SPAC13D6.05 alp11 tubulin specific chaperone cofactor B 
SPBC11B10.09 cdc2 cyclin-dependent protein kinase Cdk1/Cdc2 
SPAC19G12.01c cut20 anaphase-promoting complex, platform subcomplex scaffold subunit Apc4/Cut20
SPAC1A6.04c plb1 phospholipase B homolog Plb1 [Source:PomBase;Acc:SPAC1A6.04c]
SPBC6B1.04 mde4 microtubule-site clamp monopolin complex subunit Mde4 
SPBC26H8.07c nda3 tubulin beta Nda3 
SPBC800.05c atb2 tubulin alpha 2 
SPBC428.18 cdt1 replication licensing factor Cdt1 
SPBC17D11.06 spp2 DNA primase large subunit Spp2 
SPAC6F12.14 cut23 anaphase-promoting complex, TPR lobe subcomplex subunit Apc8 
SPAPB1E7.02c mcl1 DNA polymerase alpha accessory factor Mcl1 
SPAC23D3.02 rfc2 DNA replication factor C complex subunit Rfc2 
SPATRNAALA.02 scn2 tRNA Alanine 
SPATRNAALA.02 scn2 tRNA Alanine 
SPAC24H6.05 cdc25 M phase inducer tyrosine phosphatase Cdc25 
SPAC3H5.06c pol1 DNA polymerase alpha catalytic subunit 
SPAC9E9.08 rad26 ATRIP, ATR checkpoint kinase regulatory subunit Rad26
SPAPB24D3.01 toe3 transcription factor (predicted) 
SPAC11D3.06 SPAC11D3.06 MatE family transmembrane transporter (predicted)
SPBC3H7.05c SPBC3H7.05c mitochondrial Membrane Bound O-Acyl Transferase (MBOAT) family 
SPCC417.02 dad5 DASH complex subunit Dad5

**Comment by Antonialock** [comment]
Maybe?

I checked the curation sessions and I think only rad3 is annotated directly to inviable septated mononucleate vegetative cell (this didnt look right so I changed this to a different term). Some had been changed after the last update.

Some are annotated to "inviable after spore germination, single or double cell division, arrest with septated mononucleate cell" though. 

Reopen if you want anything done with those..

**Comment by ValWood** [comment]
No its OK, I saw the other term 
"inviable after spore germination, single or double cell division, arrest with septated mononucleate cell"
yesterday.

I fixed al the others from another ticket, there seems to be a bit of duplication. I think its all OK now.
