### ISSUE TITLE
sessions with term requests

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#799]
A  number of the sessions with term requests are from users and they have been there a long time

http://curation.pombase.org/pombe/view/list/sessions_with_term_requests?model=track

If the users got as far as making annotations it is likely 
a) they maybe thought they had  submitted
b) they forgot to finish.

These are clearly people who have tried, so I suggest:
1. Have a scan of the session and  if it seems near completion mail the users asking if they forgot to submit or if they  got stuck and would need some help.....
2. If the term  request makes sense, open a ticket on the FYPO tracker, it would look good if they come back to finish and the terms they requested are in, if sensible.

**Comment by mah11** [comment]
Of the sessions on the list today ...

This is Val's, so I'll leave it to her to open a FYPO ticket:
f78a781e3e01fdf4

These are Antonia's, and have FYPO tickets (some done, some open):
33497d588756c658 #2416
38560610372534b4 #2547
71662226413c7ee0 #2535
789cb7143f17138e #2527
ea7f33ab6887fe6d #2538
ed1e6e11b1c4abfa #2548

39e9205957ce5637
For this one, the term request was not part of original curation. Antonia has restarted approval and added the term suggestion. It's under discussion in https://github.com/pombase/fypo/issues/2546

I've opened tickets for these and will follow up:
341a050d011a7bfa
40c52ec90ce2de0e
80b382d361649949
83d3bee37f8b40fd (this prompted the GO ticket #12274 kerfuffle)
bf037075feb20f28

**Comment by mah11** [comment]
closing because community sessions are in hand one way or another
