### ISSUE TITLE
annotation check protein localization related

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#801]
From
PMID: 25963819  I spotted

imp1	GO:1904687	positive regulation of mitotic spindle disassembly	IGI	nup132			
imp1	GO:1902967	protein localization to mitotic spindle midzone	IPI	rpn8	has_input(PomBase:rpn8)	
imp1	GO:1902967	protein localization to mitotic spindle midzone	
imp1	GO:1902967	protein localization to mitotic spindle midzone

I'd question the GO terms f 'localizing a protein to the spindle midzone' for imp1
This sounds like a phenotype. The imp1 is an importin. There (as far as I'm aware) are involved in nucleocytoplasmic transport. I don't think they localize things to a specific nuclear localization (which is presumably diffusion or some other mechanism?)

so, 
imp1 can be annotated to localization of rpn8 and cdc48 to the nucleus, but not to the spindle midzone (although this can be a phenotype)

Can also have a protein binding annotation?
or even 
O:0061608 nuclear import signal receptor activity IMP
with targets?

I'm also not sure about
imp1	GO:1904687	positive regulation of mitotic spindle disassembly	IGI	nup132		
because although imp1 is *required*  for disassembly, its upstream (unless transport was explicitly defined as part of this process of spindle disassembly)

The thing which is doing the regulating (if it isn't constitutive) is the thing which is regulating imp1 to do the transporting? (A GTPase usually)

"We show that, during anaphase B, Imp1-mediated transport of the AAA-ATPase Cdc48 protein at the MMD allows this disassembly factor to localize at the spindle midzone, thereby promoting spindle midzone dissolution."

**Comment by ValWood** [comment]
It seems to be nucleocytoplasmic transport at a specific sub domain of the nuclear membrane

"domain surrounding the mitotic spindle midzone, here named the midzone membrane domain (MMD)"

**Comment by Antonialock** [comment]
Ok so:

1. I added MF O:0061608 nuclear import signal receptor activity 
with targets

2. I removed imp1 GO:1904687 positive regulation of mitotic spindle disassembly
I agree disassembly is downstream

3. I kept 
imp1 	GO:1902967 	protein localization to mitotic spindle midzone 
after rereading the paper it still feels like this is correct.

**Comment by Antonialock** [comment]
(reopen if you want to discuss it further)

**Comment by ValWood** [comment]
OK,  when I had a Iook I wasn't sure what I thought, but this is a summary....

The importin  probably doesn't really localize  proteins actually to the mitotic spindle midzone. What appears to happen is that somehow a restricted membrane domain is targeted which is close proximity to the spindle ......which I guess increases its chances of localizing there.

If you think about it, something which localizes something to the spindle would have to do one of 2 things:
i) physically anchor it to the spindle (i.e through some PT modification) or
ii) actively transport it to the spindle. 
I think we can rule out i) and I'm not sure if importins have the capacity to transport to a specific location *within* the nucleus. As far as I'm aware they only transport things into or out of the nucleus through the pore. 

So, I would have gone with a localization phenotype and but not a GO process. For GO I would have said that it transports the cargo into the nucleus.

I could be wrong....

**Comment by ValWood** [comment]
So the importin does this
https://en.wikipedia.org/wiki/Nuclear_transport
and probably releases its cargo close to the spindle midzone, but isn't responsible for localizing to the spindle midzone....its only localizing to the nucleus, does that make sense?

Something else is doing the localizing, either downstream on the spindle midzone, or whatever pathway is responsible for clustering the nuclear pore complexes at the spindle midzone domain. UNLESS this importin is selective for particular nuclear pores at the spindle midzone, in which case it IS responsible for the specific spindle mid zone domain localization, but they don't show that....

The language is subtle:
"We show that, during anaphase B, Imp1-mediated transport of the AAA-ATPase Cdc48 protein at the MMD allows this disassembly factor to localize at the spindle midzone, thereby promoting spindle midzone dissolution."

They say "allows" which is true....but it might not be an intrinsic function of imp1

**Comment by Antonialock** [comment]
Ok yeah, actually
"therefore, Imp1 transport of NLS proteins through nuclear pores at the MMD region might be dependent on a specific importin- subunit, likely Kap95 or Kap104"

I removed it.

**Comment by ValWood** [comment]
Yeah thats it. They haven't determined that this is responsible for the specificity at this domain. This is could be just  'shuttling' . The phenotype is fine though.
