### ISSUE TITLE
improved 'target of' notation for phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#805]
I am "reviewing' some of my annotations for chromosome segregation for consistency, trying to work out which gene products are involved  directly in Cenp-A loading and which  phenotypes from upstream/downstream chromatin processes.

It would be easier to interpret the annotations if we could be more specific about mutational effects.
For example here:

![cnp1](https://cloud.githubusercontent.com/assets/7359272/12871770/ec036128-cd81-11e5-8fa2-1d654cc4ec55.jpg)

I *think* all of these are
"localization affected by mutation in" but I can't be sure unless I click on each individually and find the contributing annotation/extension among the many phenotypes.

It would be useful if we could identify a few high level nodes  types of these, (localization/ expression/binding/modification) and ask Mark to implement in the same way as he did for GO (referring to the old jira ticket to describe what we need, as presumable the code for this already exists)

It would be incredibly useful here, for example:
http://www.pombase.org/spombe/result/SPBC11B10.09#recipext

**Comment by mah11** [comment]
moved to Jira https://www.ebi.ac.uk/panda/jira/browse/PB-2547
