### ISSUE TITLE
annotation check sty1 modifications

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#808]
I spotted this when I was doing the update check:

1. is T171 actually 'removed' during cellular response to heat? That seems odd? Is it just absent during?

2. phosphorylated residue
added_by wis1 Y173
should be 	O4'-phospho-L-tyrosine
than it would 'merge' into redundant annotations

**Comment by ValWood** [comment]
3.  	This seems odd as a 'compound' annotation
removed by pyp1, added during cellular response to osmotic stress

Shouldn't added_by only be compound with added during and removed by with removed_during

**Comment by mah11** [comment]
1 and 3 come from PMID:10398679, which I didn't curate, but I had a look anyway. I agree that 3 looks odd as a compound extension. 1 looks correct, though - fig 3 shows phosphorylation at Y171 starting high and then decreasing during heat shock.

2 is an NAS, so it can just be deleted outright.

**Comment by ValWood** [comment]
I fixed 2.

Did you fix 3? assuming you did so closing....
