### ISSUE TITLE
odd annotation to nucleobase-small molecule metabolic process (dcp1 & 2), Slim check

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#814]
I checked the slims and this was one of the outliers:

dcp1 and 2 are annotated to 
nucleobase-containing small molecule metabolic process.
I think this is from a F-P mapping, but I'm not really sure what 
7-methylguanosine catabolic process	
refers to.

I'll move to the GO tracker but I wanted to know if it looks odd to you first?

![odd](https://cloud.githubusercontent.com/assets/7359272/13036177/458669b2-d358-11e5-95d7-9c19da80e03c.jpg)

**Comment by mah11** [comment]
There is no F-P link involving GO:0046119 7-methylguanosine catabolic process. There are direct annotations in the PMID:18280239 session (9787081c65c1aca3).

**Comment by Antonialock** [comment]
is that ok?

**Comment by ValWood** [comment]
I was just looking. I don't think it is necessarily 
7-methylguanosine catabolism.....
this is just cleaving the cap...no idea what happens to it after that....

**Comment by ValWood** [comment]
could be recycled

**Comment by Antonialock** [comment]
oh yea...I moved the term to deadenylation-dependent decapping of nuclear-transcribed mRNA 
(they say in the intro that both existing pathways in eukaryotes are deadenylation dependent)
