### ISSUE TITLE
what did we decide for transcription factor targets?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#815]
I noticed an inconsistency for Fep1. Sometimes 'direct_input' sometimes 'regulates' for the regulated transcript (I think we said regulates because it isn't really 'direct'). 

![fep1_target inconsistency](https://cloud.githubusercontent.com/assets/7359272/13036266/9752a2cc-d35a-11e5-9d26-fdd8e8a3a1cc.jpg)

**Comment by mah11** [comment]
We have "a transcription factor activity term (sequence-specific DNA binding transcription factor activity (GO:0003700) or a descendant) with any target genes as has_regulation_target extensions ..." on the wiki.

http://curation.pombase.org/pombase-trac/wiki/GOAnnotationGuidelines

**Comment by ValWood** [comment]
OK I thought it was regulates. I'll fix this one.

**Comment by ValWood** [comment]
fixed
