### ISSUE TITLE
clr4 DNA binding odd?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#816]
DNA binding looks odd for clr4 (it binds histones, but it doesn't appear to have a DNA binding domain).
It could do, but first could you check that this isn't CHIP data?
http://www.pombase.org/spombe/result/SPBC428.08c#go-molecular_function
v

**Comment by mah11** [comment]
actually shown by gel shift in PMID:22727667 figure S7

**Comment by ValWood** [comment]
OK!  weird especially the RNA binding....
