### ISSUE TITLE
negative regulation of chromatin silencing at silent mating-type cassette

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#817]
This term doesn't sound right (2 genes annotated). chromatin silencing at silent mating-type cassette = ok, but silencing isn't negatively regulated here.

**Comment by ValWood** [comment]
That does sound weird.
http://www.ncbi.nlm.nih.gov/pubmed?term=12417737
Phenotype only?

**Comment by Antonialock** [comment]
Yeah sounds like it...I'll take a look when I'm done with the paper that made me look :)

**Comment by ValWood** [comment]
This looks really quick.

**Comment by ValWood** [comment]
DOne
