### ISSUE TITLE
more curation from  one of the phosphoproteome papers PMID: 21712547

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#820]
I think part of this data is covered by a   modification spreadsheet.
I am putting some HTP papers through, but I think there is more data in this one (Aurora substrates), possibly other stuff

http://libsta28.lib.cam.ac.uk:2135/content/4/179/rs6.full

**Comment by ValWood** [comment]
and not sure if this one needs approving ?
curs/f248129e68667867

**Comment by ValWood** [comment]
These should all be checked to see if they are 'cleared' through canto. I have been doing the others as I go through but I'm too brain dead now....

PMID_18257517_modifications.tsv
 PMID_26412298_modifications.tsv
 PMID_24763107_modifications.tsv
 PMID_21712547_modifications.tsv
PMID_26644575_modifications.tsv

**Comment by mah11** [comment]
All except PMID:21712547 are done (PMID:24763107 / f248129e68667867 was approved at one point, so shouldn't have come out of approval).

**Comment by mah11** [comment]
done, esp. now that I've fixed my typo in an extensions ...
