### ISSUE TITLE
Do we need to approve this session?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#822]
curs/4d77205831109bda

PMID:25452419
Title	Parallel Profiling of Fission Yeast Deletion Mutants for Proliferation and for Lifespan During Long-Term Quiescence.
Authors	Sideri T, Rallis C, Bitton DA, Lages BM, Suo F, Rodríguez-López M, Du LL, Bähler J

or is there more to do?

**Comment by Antonialock** [comment]
I did not take it out of approval & I don't know why it was taken out of approval...

I reapproved it

**Comment by ValWood** [comment]
It didn't seem to have been approved? I thought the data was all in a spreadsheet?  Maybe not? but its fully annotated anyway...

**Comment by Antonialock** [comment]
ah ok, yeah I see. Approved it anyway, it was 'done' :)
