### ISSUE TITLE
standardise phosphorylation 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#833]
we sshould decide what to do here for consistent annotation
1) use phosphorylated
or
2) use specific.

Here, phosphorylated could be more specific because we know they are serines (this would group more data together consistently).

I tried to check which gene this was, because I forgot to now it. I though I would be able to find this by going to the ark1 page and finding the substrate, but this one isn't listed. We could generate the protein kinase/target annotations from the modification/added by annotations.

Also, the same but the other way around. Byr1 has target byr1 but byr1 isn't listed as a phosphoprotein...we should check first that annotations aren't going missing. For ark1 has no modification data. Possibly that's correct, but intuitively, I thought it would have loads.

**Comment by ValWood** [comment]
![standardise](https://cloud.githubusercontent.com/assets/7359272/13466484/0c8ca49a-e092-11e5-9007-c055a67cd8d0.jpg)

**Comment by mah11** [comment]
I don't think I've done much, if anything, on ark1 specifically, but I always annotate what the paper shows -- and sometimes it really does only show generic "phosphorylated", especially in older papers.

**Comment by ValWood** [comment]
For this one, if we know the specific residue, we know its O-phosphoL serine though. But it could predate the specific ontology terms (i.e it might be in Artemis). I'll check this too.

Longer term it would be good to have the reciprocal annotation so 
ark1 has substrate whatever this gene product is (when I can track it down).

**Comment by ValWood** [comment]
cnd2
tada PMID: 21633354

**Comment by ValWood** [comment]
I need to move the phosphorylation down to O-phosphoL serine
AND
change the substrate of ark1 from cnd1 to cnd2

**Comment by ValWood** [comment]
I don't think there is anything to discuss. I think generally we make the most specific if we know the residue....
will fox when Canto back

**Comment by ValWood** [comment]
Done the fixes above.
