### ISSUE TITLE
 consistency mRNA/RNA level

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#837]
I wonder if there is an easy way to make this type of annotation consistent

![standardize](https://cloud.githubusercontent.com/assets/7359272/13508346/861d1dd4-e17e-11e5-9c84-ee7c1c10dbb6.jpg)

Is there any  negative effects of merging RNA/mRNA if we pretty much always specify the gene?
(It would save us needing to check extensions and migrating to mRNA)

If its bulk RNA would we be able to distinguish type?

**Comment by ValWood** [comment]
transferring to FYPo tracker

**Comment by mah11** [comment]
agreed to merge 'mRNA' terms into 'RNA' for generic cases: https://github.com/pombase/fypo/issues/2969

anything more specific has a reason to retain 'mRNA'
