### ISSUE TITLE
add target protein? (cdc10)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#839]
I think this must be an APC substrate ?  need to add target protein (soft warning?)

![cdc10 which protein](https://cloud.githubusercontent.com/assets/7359272/13508978/337fcd08-e181-11e5-98bc-cf23c1ba9424.jpg)

(Also is the protein level here increased because is arrested in G1 ? and if so is the arrest transient?...I was annotating something similar today...I haven't really figured that one out yet)

**Comment by Antonialock** [comment]
I don't know about this specific case, but I guess protein levels could also be up globally

**Comment by ValWood** [comment]
In this case its doubtful as its cdc10, and an APC target so I presume they were looking at specific proteins. Didn't look at the paper yet though.....

**Comment by ValWood** [comment]
Cut8 is required for efficient destruction of Cdc13 and Cut2 in G1-arrested cells.
update when canto back

**Comment by ValWood** [comment]
fixed
