### ISSUE TITLE
qualifier to get rid of:  "constitutive"   on cellular_component

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#841]
7 | constitutive             | cellular_component

can be done with
nucleus happens_during(mitotic interphase)
and
nucleus happens_during(mitotic M-phase)

to cover mitotic cell cycle

**Comment by mah11** [comment]
Cellular component annotations do not allow happens_during. Use exists_during.

I think I've done a few as exists_during(GO:0000278) 'mitotic cell cycle'. Does that work?

**Comment by ValWood** [comment]
It does but some time last week  (for extension prompts) we discussed changing all of these to phase terms (mitotic cell cycle is a bona fida process term).

In these cases I have usually done
nucleus happens_during(mitotic interphase)
and
nucleus happens_during(mitotic M-phase)
to cover the entire cell cycle with phase extensions

Ii guess it could be
during GO:0098763 mitotic cell cycle phase
 instead

I think it could be useful to only allow phases for during (with the exception  of the during response to stress terms)

**Comment by mah11** [comment]
1. Ouch, it'll be tedious to go back and update my extensions. Back burner. (Ages ago I asked GO if they could come up with a way to represent "throughout the cell cycle" but guess what? Radio silence.)

2. NEVER USE HAPPENS_DURING, or occurs_*, in an extension for a CC annotation.

**Comment by ValWood** [comment]
I  suggest for this we
a) get a log report to see how many do not match the allowed extension ranges we plug in
b) probably ask Kim to do a bulk change when we know how many are affected

**Comment by Antonialock** [comment]
chromosomes 1 & 3 done

**Comment by ValWood** [comment]
and 1.

gone forever...
