### ISSUE TITLE
lsd2 GO:0032454 problem

### ISSUE THREAD

**Issue by mah11** [pombase/curation#843]
The lsd2 annotation to GO:0032454 from PMID:17440621 throws an error in the Oort/Jenkins checks, because GO frowns upon using IPI for terms in the catalytic activity branch of MF.

Would IDA and qualifier=contributes_to be close enough? If so I'm happy to amend in the session.

    #------------
    # GO_AR:0000007 IPI should not be used with catalytic activity molecular function terms Warning count:  1
    31389   GO_AR:0000007   Warning IPI should not be used with catalytic activity molecular function terms PomBase SPAC23E2.02     lsd2            GO:0032454      PMID:17440621   IPI     PomBase:SPBC146.09c     F       histone demethylase SWIRM2 (predicted)  saf140|swm2     protein taxon:4896      20160125        PomBase
    #------------

https://curation.pombase.org/pombe/curs/628c4060d26880cf/

**Comment by Antonialock** [comment]
ok thanks, I've changed it
