### ISSUE TITLE
small annotation fixes to track down

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#852]
residues which are not in the format  single letter amino acid,integer

These 2 are in the modification file currently
165
469
473

**Comment by ValWood** [comment]
pombase-build-2016-01-25-v3-l1.modifications:SPCC162.09c	hmg1	MOD:00696		S1024|residue=T1028	present_during(GO:0042594)	PMID:19041767	4896	2009-02-06
pombase-build-2016-01-25-v3-l1.modifications:SPAC15E1.03	rpl42	MOD:00427	Inferred from Direct Assay	L32|residue=L55		PMID:20444689	4896	2010-06-28
pombase-build-2016-01-25-v3-l1.modifications:SPBC8D2.04	hht2	MOD:00427	Inferred from Sequence or Structural Similarity	K4|residue=K9		PB_REF:0000001	4896	2010-03-11
pombase-build-2016-01-25-v3-l1.modifications:SPBC1105.11c	hht3	MOD:00427	Inferred from Sequence or Structural Similarity	K4|residue=K9		PB_REF:00000014896	2010-03-11
pombase-build-2016-01-25-v3-l1.modifications:SPBC32F12.09	rum1	MOD:00696		S13|residue=S19		PMID:12135491	4896	2009-02-13
pombase-build-2016-01-25-v3-l1.modifications:SPCC576.03c	tpx1	MOD:00689		C48|residue=C169		PMID:17409354

**Comment by mah11** [comment]
fixed the ones in the contig files (rest will have to wait until canto is back online)

**Comment by mah11** [comment]
done
