### ISSUE TITLE
annotation exercise, QC for kinetochore / "short mitotic spindle"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#867]
As I get closer to finishing the kinetochore papers I tried enriching kinetochore components in Angeli to see what the enriched phenotypes were. I am going to do the large sub complexes next, its really informative and identifies annotation oddities.

One thing I notices were some unexpected phenotypes to abnormal spindle. I think a lot of these are because often an experiment will report  "metaphase arrest with short spindle". I think here I would make an annotation to "metaphase arrest" and to "short spindle", but now I think I should not make the short spindle annotations here, because a short spindle is normal for a cell arrested in metaphase. Do you agree?

I guess this is something to consider generally that I hadn't thought about before.

**Comment by ValWood** [comment]
I also need to check these. 
short spindle

![short spindle nuf2](https://cloud.githubusercontent.com/assets/7359272/13874494/3414cbcc-ecf0-11e5-81ea-f1088d089713.jpg)
 seems to contradict normal spindle elongation, same alleles, same paper:

**Comment by Antonialock** [comment]
yeah I agree, it sounds like an abnormal metaphase arrest with a normal spindle :)

good to have checks....these sorts of errors are bound to creep in...partly because our knowledge is limited, partly of how authors phrase things, and partly because, well, the biology researched is unknown and sometimes it is unknown at the time if an observation is abnormal or a transient state

**Comment by Antonialock** [comment]
(just to clarify, I wouldn't annotate to 'normal spindle' based on this....just see it as an indication that cells are in metaphase....so I would annotate to abnormal arrest in mitotic metaphase, or whatever the flavor of those terms is du jour :) )

**Comment by ValWood** [comment]
Yeah. Now I have annotated a lot of papers in this area and have a better feeling for the phenotypes and processes my early  errors are jumping out.    If you finish annotating a complex run the gene list through Angeli, its really useful....

**Comment by ValWood** [comment]
gahhh...
I thought there might be an easy way to check these but I think I will need to look at them all.

Systematic ID | Gene name | Product description
-- | -- | --
SPBC17D1.04 | acr1 | RNA polymerase I upstream activation factor complex subunit Acr1
SPBC800.05c | atb2 | tubulin alpha 2
SPCC962.02c | bir1 | survivin, Bir1
SPBC582.03 | cdc13 | G2/M B-type cyclin Cdc13
SPAC1786.03 | cut11 | spindle pole body docking protein Cut11
SPAC25G10.07c | cut7 | kinesin-5 family plus-end directed microtubule motor, bimC subfamily Cut7
SPAC17C9.13c | cut8 | tethering factor for nuclear proteasome Cut8
SPAC6F12.15c | cut9 | anaphase-promoting complex, TPR lobe subcomplex subunit Cut9/Apc6
SPAC26A3.16 | dsk2 | UBA domain protein Dph1/Dsk2
SPBC15D4.01c | klp9 | kinesin-6 family microtubule motor protein Klp9
SPBC947.12 | kms2 | mitotic and meiotic spindle pole body KASH domain protein Kms2
SPBC20F10.06 | mad2 | mitotic spindle checkpoint protein Mad2
SPAC1687.20c | mis6 | CENP-I ortholog Mis6
SPAC17C9.01c | nuc2 | anaphase-promoting complex TPR lobe subcomplex subunit Apc3
SPAC27F1.04c | nuf2 | NMS complex subunit Nuf2
SPBC557.03c | pim1 | RCC1 family Ran GEF
SPAC3A11.14c | pkl1 | kinesin-14 family minus-end directed microtubule motor Pkl1
SPBC12D12.01 | sad1 | spindle pole body SUN domain protein Sad1
SPATRNAALA.03 | scn1 | tRNA Alanine
SPATRNAALA.02 | scn2 | tRNA Alanine
SPAC4A8.12c | sds22 | protein phosphatase regulatory subunit Sds22
SPBC577.15c | sim3 | NASP family CENP-A chaperone
SPBC18E5.03c | sim4 | CENP-K ortholog Sim4
SPAC664.01c | swi6 | heterochromatin (HP1) family chromodomain protein Swi6
SPCC1259.15c | ubc11 | ubiquitin conjugating enzyme E2, Ubc11/UbcP4
SPCC1682.12c | ubp16 | ubiquitin C-terminal hydrolase Ubp16
