### ISSUE TITLE
intron data/ branch sites/ confirmed introns

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#87]
resurrect intron data at some point

and annotate branch sites as features

see
https://rt.sanger.ac.uk/SelfService/Display.html?id=223991

Original comment by: ValWood

**Comment by Antonialock** [comment]
can this close @ValWood ?

**Comment by Antonialock** [comment]
or do we still want to have an intron track?

**Comment by Antonialock** [comment]
/ features

**Comment by ValWood** [comment]
I think Danny's branch point data covers this...
