### ISSUE TITLE
och1 modifications?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#870]
/note="C12N15/09,C07K14/00,C07K14/39,C12N1/00,C12N1/15,C12N 1/19,C12N1/21,C12N5/10,C12N9/10,C12P21/02//(C12N15/09,C12R1 :645),(C12N1/00,C12R1:645),(C12N9/10,C12R1:645),(C12P21/02,C12R1:645),C12N15/00,C12N5/00, (C12N15/00, C12R1:645)"

**Comment by Antonialock** [comment]
it looks like these have to do with patents.

It looks like you deleted the note already (?) so I'll close this.

**Comment by ValWood** [comment]
OK if there is no publication paper trail...we can ignore
