### ISSUE TITLE
confusing uses of ID SPAPB1A11.05

### ISSUE THREAD

**Issue by mah11** [pombase/curation#873]
In chromosome1.contig, it looks like SPAPB1A11.05 has become a synonym for SPAPB1A11.06 for the CDS feature, but the UTRs use SPAPB1A11.05:

    FT   5'UTR           2975608..2975642
    FT                   /systematic_id="SPAPB1A11.05"

    FT   CDS             2975643..2975771
    [snip some lines]
    FT                   /systematic_id="SPAPB1A11.06"
    FT                   /synonym="prl31"
    FT                   /synonym="SPNCRNA.31"
    FT                   /synonym="SPAPB1A11.05"

    FT   3'UTR           2975772..2976007
    FT                   /systematic_id="SPAPB1A11.05"

and elsewhere in the same file there's this:

    FT                   /primary_name="sap49"
    FT                   /synonym="SF3b49"
    FT                   /synonym="SPAPB1A11.05"
    FT                   /product="U2 snRNP-associated RNA-binding protein Sap49"
    FT                   /systematic_id="SPAC31G5.01"

Jira https://www.ebi.ac.uk/panda/jira/browse/PB-2481 lists SPAPB1A11.05 as a new gene from PMID:26494834 (so I guess also see #866).

(spotted whilst going through GOA syntax checks)

**Comment by ValWood** [comment]
changed the UTrs to match the feature systematic ID.

**Comment by mah11** [comment]
OK, updated "New and removed genes" page to match
