### ISSUE TITLE
Discuss  annotation, filtering and display of modification terms.

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#880]
figure out why this no longer has histone aceylation:
http://www.pombase.org/spombe/result/SPAC17G8.13c

**Comment by ValWood** [comment]
looks quick...

**Comment by mah11** [comment]
yep, same problem as reported to GO some months back
https://github.com/geneontology/go-annotation/issues/1336

**Comment by ValWood** [comment]
I don't think that it matters  if we don't 'display' these on our gene pages (this is like the phosphorylation discussion this week with @AntoniaLock). I  can even filter those from external sources  so that they don't appear explicitly on the gene pages (to a gene page user its obvious that a histone acetylase is involved in histone acetylation so this is redundant information).  For this reason I exclude 'protein modification' terms from the slim, as they aren't really providing useful information about the biological role. However, they should still exist  behind the scenes for enrichment purposes so we need to make sure the F-P link comes back.

We only need to make explicit annotations to modifications when we have information for extensions which we can't put on the MF.
We should also make explicit annotation for other processes (like transmembrane transport).
i'll put a "discuss label" on this ticket to go through this. It might not be clear....

**Comment by ValWood** [comment]
I'm already filtering direct annotations to these  terms for gene page display from external sources, but because of FP links they will still be retrieved by queries.

GO:0006468 protein phosphorylation
GO:0006470 protein dephosphorylation    
GO:0006479 protein methylation
GO:0016310 phosphorylation
GO:0016311 dephosphorylation

as yet, I don't do anything with  acetylation etc, but can/will in the future when F-P links back

**Comment by mah11** [comment]
> we need to make sure the F-P link comes back

This doesn't quite make sense as worded, because the F-P link is in the ontology, and has been all along. It's the annotations inferred using the existing F-P links that need to come back, and GO has to sort that.

**Comment by mah11** [comment]
It seems to me that what we choose to display on gene pages is a separate question from whether annotation inference over F-P links are working correctly, so perhaps they shouldn't be in the same ticket.

**Comment by ValWood** [comment]
Fixed comment. 
I think for discussion purposes its useful to have them in the same ticket for now.  There isn't really any action except the discussion. I'll change the subject.

**Comment by ValWood** [comment]
I don't think we need to discuss anything here. 
The annotations are back.
The F-P pipeline still creates redundant annotation. There are tickets at GO about this. 
If they annoy me too much I can filter.
