### ISSUE TITLE
add FAQ item: mapping GO MF to EC

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#881]
From RT ticket:
https://rt.sanger.ac.uk/Ticket/Display.html?id=522905

**Comment by mah11** [comment]
Until we move all non-private stuff to GitHub, web page edits should still go on Jira (and after we move, we should create a separate repo & tracker for the web site, not lump it into this one).

Val already opened https://www.ebi.ac.uk/panda/jira/browse/PB-2603

**Comment by Antonialock** [comment]
ah sorry, I was in an RT blitz, thanks
