### ISSUE TITLE
penetrance

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#887]
I wonder if it makes sense to offer penetrance for normal terms?
If they are 'normal' you wouldn't be annotating penetrance (one would assume that its 100 %?)

**Comment by Antonialock** [comment]
I think I've done 
abnormal morphology X = 20%
abbnormal morphology Y = 50%
normal morphology = 30% 

in the past, but only where they have specified "X% were normal"

**Comment by ValWood** [comment]
that makes sense, ok...
