### ISSUE TITLE
	abnormal centromere clustering at nuclear periphery

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#890]
oh poo, I have used the wrong term for moa1 here
81e91219a1043368/ro/

I think I have *almost * figured it out now....

**Comment by ValWood** [comment]
and Jonathan made this  from PMID:21965289
centromere clustering at the nuclear envelope
but with [happens_during] mitotic anaphase B
for nsk1 but this process happens during interphase?

**Comment by ValWood** [comment]
This could be because of the older definition.....
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0072766#term=history

**Comment by ValWood** [comment]
OK there are 2 things

I think Joantans Nsk1 annotation is OK, but this clustering at the nuclear envelope appears to occur during anaphase B and persist through Interphase.
So:
PMID: 21965289

Type 1 phosphatase (PP1) antagonizes Aurora B kinase to stabilize kinetochore-microtubule attachments and to silence the spindle checkpoint. We screened for factors that exacerbate the growth defect of Δdis2 cells, which lack one of two catalytic subunits of PP1 in fission yeast, and identified Nsk1, a novel protein required for accurate chromosome segregation. During interphase, Nsk1 resides in the nucleolus but spreads throughout the nucleoplasm as cells enter mitosis. Following dephosphorylation by Clp1 (Cdc14-like) phosphatase and at least one other phosphatase, Nsk1 localizes to the interface between kinetochores and the inner face of the spindle pole body during anaphase. In the absence of Nsk1, some kinetochores become detached from spindle poles during anaphase B. If this occurs late in anaphase B, then the sister chromatids of unclustered kinetochores segregate to the correct daughter cell. These unclustered kinetochores are efficiently captured, retrieved, bioriented, and segregated during the following mitosis, as long as Dis2 is present. However, if kinetochores are detached from a spindle pole early in anaphase B, then these sister chromatids become missegregated. These data suggest Nsk1 ensures accurate chromosome segregation by promoting the tethering of kinetochores to spindle poles during anaphase B.


Looks like this:
![anaphaseb](https://cloud.githubusercontent.com/assets/7359272/14329867/6f7e44c8-fc35-11e5-8438-6ac780c05ebd.jpg)

So when this phenotype results in chromosome mis-segregation, this mis segregation is in the NEXT mitosis.

**Comment by ValWood** [comment]
I found one pombe paper that refers to this as 'kinetochore clustering'

![cluster2-metaphase spindle](https://cloud.githubusercontent.com/assets/7359272/14330020/5fe2c704-fc36-11e5-8ea8-312eb543a7e5.jpg)

**Comment by Antonialock** [comment]
ok I don't really get this but I haven't done anywhere near as much on chromosome segregation as you. 

I'll use GO:0099607 for PMID:22375062 then
It is also the Millar group and they reference PMID: 17881496

**Comment by ValWood** [comment]
Yep...

**Comment by ValWood** [comment]
This is fine.
This helped. 
![makes_sense](https://cloud.githubusercontent.com/assets/7359272/18355193/41bac42e-75e0-11e6-8420-13ac8bfa39d1.jpg)
