### ISSUE TITLE
biosharing

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#898]
update with publications etc

**Comment by Antonialock** [comment]
https://biosharing.org/

**Comment by ValWood** [comment]
Thanks!
Val

On 19/04/2016 11:20, Antonialock wrote:
>
> https://biosharing.org/
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/pombase/curation/issues/898#issuecomment-211845535>
>


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by ValWood** [comment]
Done?
