### ISSUE TITLE
query about "during" term

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#902]
curs/f07cd572b2d0adcf/ro/
response to ammonium ion sounds more like a 'condition' to induce a specific signalling pathway...
but this is an in vitro assay, so I didn't get the "cellular response to ammonium ion"

**Comment by Antonialock** [comment]
I think the annotation is fine

In vivo: 
Rps6   (fission    yeast    S6)   is   phosphorylated    under ammonium stimulation  in these  strains. In contrast, Rps6 phosphorylation  in psk1D was  not  detected  even  in  nitrogen-rich  conditions  (Fig. 2A).
These results suggest that the deletion of psk1 results in failure to  phosphorylate  Rps6.  

in vitro
To  further  investigate  whether  Psk1 phosphorylates  Rps6  protein in vitro,  we  examined  the  kinase activity of Psk1 using recombinant Rps602 as a substrate. As shown in Fig. 2C, the  Psk1  protein  phosphorylated  Rsp6 in vitro

**Comment by Antonialock** [comment]
look at the paper not just my comment :-) my comment is only there because they only assayed one of the substrates and I inferred the other.

**Comment by ValWood** [comment]
Hmm, but what are they using the Ammonium to demonstrate? Is it as a nitrogen source?
Its OK though...
