### ISSUE TITLE
Question about mitotic cell cycle arrest in G1

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#913]
When this happens in a normal cell, is it always the fist step of conjugation?
@Antonialock niaLock

**Comment by Antonialock** [comment]
err I guess not?
GO:0044819 mitotic G1/S transition checkpoint

**Comment by ValWood** [comment]
This is the restriction point, its before the transition isn't it? If you arrest in G1, you don't go through the transition. I'm confused...

(but the above statement would not work for other non-yeast organisms which exit the cell cycle at this point)

**Comment by ValWood** [comment]
OK I wasn't thinking about the checkpoints. I was thinking about the arrests  in order to conjugate  (i.e in response to nitrogen starvation, or pheromone)

 I'll close this ticket shortly, and update the other one. I think I know what we need to do...
