### ISSUE TITLE
elongation phenotypes, review (revisit V 47)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#92]
look into how many
inviable after spore germination, multiple cell divisions, elongated cell
should be
inviable after spore germination, multiple cell divisions, elongated cell arrested at interphase

(especially deletion project phenotypes)

Original comment by: ValWood

**Comment by ValWood** [comment]
to check
SPAC30D11.13	hus5	SUMO conjugating enzyme E2 Hus5 
SPCC645.04	nse3	Smc5-6 complex non-SMC subunit Nse3 
SPBC30B4.07c	tfb4	transcription factor TFIIH complex subunit Tfb4 
SPCC1682.07	ssl1	transcription factor TFIIH complex subunit Ssl1 
SPCC16C4.08c	skb15	p21 activated protein kinase inhibitor Skb15 
SPAC9G1.15c	mzt1	mitotic spindle organizing protein Mzt1 
SPBC11G11.07	mtr10	karyopherin, nuclear import receptor Mtr10 (predicted) 
SPBP16F5.02	mcs2	TFIIH complex cyclin Mcs2 
SPCC550.05	nse1	Smc5-6 complex ubiquitin-protein ligase E3 subunit 1 
SPCC645.05c	myo2	myosin II heavy chain 
SPAC26H5.12	rpo41	mitochondrial RNA polymerase Rpo41 
SPCC162.08c	nup211	nucleoporin nup211 
SPCC1620.11	nup97	nucleoporin Nic96 homolog 
SPBC776.18c	pmh1	transcription factor TFIIK complex complex ubiquitin-protein ligase E3 subunit, Pmh1 
SPAC1002.08c	mtf1	mitochondrial RNA polymerase specificity factor Mtf1 
SPBC83.07	jmj3	Lid2 complex subunit, histone demethylase H3-K36 specific Jmj3 
SPAC22F3.05c	alp41	ADP-ribosylation factor Alp41 
SPBC17D1.04	acr1	upstream activation factor complex subunit Acr1 
SPAC6B12.10c	spp1	DNA primase catalytic subunit Spp1 
SPAC31G5.13	rpn11	19S proteasome regulatory subunit Rpn11 
SPBC1215.02c	naa25	NatB N-acetyltransferase complex regulatory subunit Naa25 
SPAPB1A10.11c	mse1	mitochondrial glutamyl-tRNA ligase Mse1 (predicted) 
SPAC1F5.11c	tra2	NuA4 complex phosphatidylinositol pseudokinase complex subunit Tra2 
SPAC1687.04	mcb1	MCM binding protein homolog Mcb1 
SPAC22H10.10	alp21	tubulin specific chaperone cofactor E 
SPAC328.08c	tbc1	tubulin specific chaperone cofactor C, GTPase activating protein Tbc1 (predicted)

**Comment by ValWood** [comment]
Can't be any more specific
