### ISSUE TITLE
check role of rad1 in repair

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#920]
See
https://github.com/geneontology/go-annotation/issues/1393#issuecomment-216851741

Will dig out paper

**Comment by ValWood** [comment]
This is the paper cited.
Seems pretty comprehensive. It seems that it doesn't have good evidence for a repair role. Do you agree?

https://curation.pombase.org/pombe/curs/25c44b9071bd33a2/ro/

**Comment by mah11** [comment]
Yes. The only data in that paper for rad1 is one interaction (with kpa1, and I didn't even annotate it; BioGRID did). Of the other two 9-1-1 subunits, hus1 also has interaction with kpa1 and nothing else, and for rad9 there are phenotypes that could be explained by the checkpoint signaling role.

 I'd call that consistent with a tantalizing possibility but not enough to support a GO annotation to repair. I would gladly reconsider if more evidence crops up - and there are several not-yet-curated 9-1-1 pombe papers - but I don't think we have it yet.

Oh, and with this

> We would also argue that Rad1 proteins would still contribute to the overall process of DNA repair, even if they were just involved in slowing the cell cycle

they're just talking bollocks. I believe that's the technical term, anyway.

**Comment by ValWood** [comment]
OK!
In the cited papers I see lots of use of "suggests". And most of the   another review also mentions this paper....http://www.ncbi.nlm.nih.gov/pubmed/15876866
I might ask Paul Russell if there are any papers we should look at.

**Comment by ValWood** [comment]
I think we are done here...
