### ISSUE TITLE
checking some G2/M annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#921]
Checking to this

![g2_m_regulation](https://cloud.githubusercontent.com/assets/7359272/15068175/5449a9c8-136d-11e6-94fd-bb7e24393119.jpg)

and removing some outliers:

**Comment by ValWood** [comment]
ubc11
VW 5/6/16 I removed GO:0010971	positive regulation of G2/M transition of mitotic cell cycle because its chk1 dependent. This implies that its only causing a defect which is activating the checkpoint and it isn't part of the normal regulation of the transition.

**Comment by ValWood** [comment]
missing for positive regulation
1, The sty1 pathway MAPKKK
2. plo1

False positive  map2 ? @Antonialock 

srb10  likely indirect/upstream (val to check)

**Comment by ValWood** [comment]
Of the negative regulators, most are above or are "mitotic G2  checkpoint"

Should  Rad24 be "mitotic G2 DNA damage checkpoint"?

...looking good....

**Comment by ValWood** [comment]
current esyN (43 /54 in network)

![43_out_of_54](https://cloud.githubusercontent.com/assets/7359272/15070124/403746b8-137a-11e6-8f3e-6b4ce212ad02.jpg)


possibly missing, win1/wis4/mcs4/skb1

**Comment by ValWood** [comment]
- [ ] blt1 (Ub ligase)
- [ ] crb2 (checkpoint)
- [ ] ctp1 IEA
- [ ] dfp1 checkpoint
- [ ]  hsp9 (this could be indirect)
- [ ] mus81 (I already questioned this, but I think it mught be a sensor)
- [ ] orc1

- [ ] rfc2 (required for a 'checkpoint competent state?)
- [ ] swi1

**Comment by mah11** [comment]
orc1 is annotated to GO:0033314 based on an orc1 cdc18 double mutant phenotype in PMID:11988741 (updated from and IMP in Artemis, I think). I stashed a bit of email about it - basically, the checkpoint isn't working properly in the double mutant. I have no strong feelings about whether to keep the GO annotation or just the phenotypes.

session f655c12afd36086c

**Comment by ValWood** [comment]
Yeah I remember we looked back  at this one before. I think the best thing is to ask Paul Russell again once I have the pathway  G2/M pathway modelled, he was really helpful weeding out the spurious ones before. I remember some are  very tricky because Jacky said if you get a problem early in replication the checkpoint is not competent at all. So the phenotype manifests the same as something that is really  involved in the checkpoint, and its impossible to know.  It should become clearer hopefully in a model....and there might be more recent insights.....

**Comment by ValWood** [comment]
This is now a duplicate of 
https://github.com/pombase/curation/issues/1047

**Comment by ValWood** [comment]
All the same questions, which is good...
