### ISSUE TITLE
cam1 GO:1990945 query

### ISSUE THREAD

**Issue by mah11** [pombase/curation#922]
There's a log warning about the cam1 annotation to GO:1990945 in artemis. It has "term=maintenance of protein localization at meiotic spindle pole body" and "GOid=GO:1990945", but the name for GO:1990945 is "protein location to meiotic spindle pole body" (queried in https://github.com/geneontology/go-ontology/issues/12445, because its def is essentially the same as GO:1902441).

There is no GO term for maintenance of meiotic SPB localization. If you need one, request it (based on the generic term, maintenance of protein location in spindle pole body (GO:0071990). In the meantime, I've put GO:1902441 and its name in the contig file.

**Comment by mah11** [comment]
Saw your comment on the GO ticket - if "protein localization to meiotic spindle pole body" is what you want for this annotation, it's all fine because I've done that fix.

The paper also has a session assigned to Chikashi Shimoda.

**Comment by ValWood** [comment]
Ah I see, this will be one which I was fixing because it had an Artemis annotation which wasn't specific for the meiotic or the mitotic term.

I saw it is assigned...I'll keep this one  open for now and figure out why the annotation was in Artemis, seems odd for a session which is out for CC so I'm a bit confused...

**Comment by ValWood** [comment]
Paper annotated through Canto.

requested
ID: GO:1990954 Label: establishment of protein localization to meiotic spindle pole body

That was so nice and easy compared to the ones I have been doing......
