### ISSUE TITLE
requested spreadsheet, SUMO targets

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#924]
Genvieve's paper went out normal CC route, but it would be better to contact her and request spreadsheet of  SUMO modification data:

https://curation.pombase.org/pombe/view/object/pub/11046?model=track

No hurry

**Comment by mah11** [comment]
- The session says it's been assigned but hasn't been sent. Do you want me to send it?

- Small thing, but the annotation_priority label and the "no hurry" comment seem contradictory ...

**Comment by ValWood** [comment]
Ignore the annotation priority label -I don't use it, that's the default and I never change it.

Probably would benefit from a tailored e-mail explaining what is required for protein modification spreadsheet.

No hurry, after beer festival ?.

**Comment by mah11** [comment]
This tracker doesn't apply any labels by default.

**Comment by ValWood** [comment]
Durr, I thought you meant the 'curation status' for the publication in Canto. Yeah not a burning priority.....

**Comment by mah11** [comment]
sent session and emailed
https://rt.sanger.ac.uk/Ticket/Display.html?id=532663

**Comment by ValWood** [comment]
No word I guess....
Might be worth following up after Matthew's data goes live and pointing to the format etc.

**Comment by mah11** [comment]
I just went ahead and committed a file myself (didn't realize back when this was opened that it was all there in a supp table).
