### ISSUE TITLE
cohesin annotation question

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#925]
Hi antonia, 

It seems odd that cohesin itself is regulating cohesin here.
d445419299dddade/ro/

Should this just be "maintenance"? rather than +ve regulation of?
(which EXP? I can take a look)

val

**Comment by ValWood** [comment]
;)
for
https://github.com/geneontology/go-annotation/issues/1396

**Comment by Antonialock** [comment]
moved it to non-reg :-)

**Comment by ValWood** [comment]
that looks right.
