### ISSUE TITLE
irc3 updates

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#926]
update ISS annotations to irc3 based on 27194389

**Comment by ValWood** [comment]
This is what I want to capture:
Irc3 is a mitochondrial DNA branch migration enzyme.

I'm thinking I need to change the MF to a helicase and for BP 
I can't find anything for branch-migration in GO   is there a recombination child to represent this by another name? @mah11 

(whatever I do I'll ask SGD to update so the ISS  is correct...
at present has mitochondrial DNA metabolic process at SGD

**Comment by mah11** [comment]
>  Is there a recombination child to represent [branch migratoin] by another name?

Unfortunately, I know far too little about recombination to have any idea. Nothing leaps out at me.

**Comment by ValWood** [comment]
gone with

/GO="aspect=P; term=mitochondrial DNA metabolic process; GOid=GO:0032042; evidence=ISO; db_xref=GO_REF:0000001; with=SGD:S000002740; date=20161005"
/GO="aspect=C; term=mitochondrial matrix; GOid=GO:0005759; evidence=ISS; db_xref=GO_REF:0000024; with=SGD:S000002740; date=20161005"
/colour=7
/product="mitochondrial DNA branch migration helicase Irc3 (predicted)"

to get it out of "conserved unknown"

**Comment by mah11** [comment]
corrected db_xref (never use GO_REF:0000001 any more)
