### ISSUE TITLE
check this list has DNA binding 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#927]
(if applicable)
after next update (I filtered the KW  because of issues with  some mappings)

SPAC10F6.08c
SPAC11D3.11c
SPAC11E3.01c
SPAC1250.07
SPAC13D1.01c
SPAC13D6.02c
SPAC13F5.07c
SPAC13G6.01c
SPAC144.02
SPAC144.09c
SPAC15A10.03c
SPAC167.08
SPAC1783.05
SPAC17A5.06
SPAC17H9.10c
SPAC1834.03c
SPAC1834.04
SPAC19D5.09c
SPAC19G12.06c
SPAC19G12.13c
SPAC1D4.12
SPAC20G8.08c
SPAC20H4.03c
SPAC22F3.03c
SPAC22F3.06c
SPAC23E2.02
SPAC23G3.04
SPAC23H3.10
SPAC25A8.01c
SPAC26A3.03c
SPAC26A3.13c
SPAC27E2.08
SPAC29B12.01
SPAC2E1P3.03c
SPAC2G11.12
SPAC31G5.10
SPAC3G6.01
SPAC3G6.11
SPAC4H3.05
SPAC57A10.09c
SPAC688.10
SPAC6B12.05c
SPAC6F6.16c
SPAC9.04
SPAPB15E9.03c
SPBC1105.11c
SPBC1198.13c
SPBC11B10.10c
SPBC1289.17
SPBC13E7.02
SPBC146.09c
SPBC14C8.12
SPBC16C6.10
SPBC16D10.09
SPBC16G5.12c
SPBC1703.02
SPBC1778.01c
SPBC17D11.06
SPBC1826.01c
SPBC19C7.10
SPBC19G7.04
SPBC1A4.03c
SPBC25H2.13c
SPBC28F2.11
SPBC29A3.14c
SPBC2A9.07c
SPBC30B4.04c
SPBC30D10.17c
SPBC336.04
SPBC336.09c
SPBC4.04c
SPBC409.12c
SPBC582.10c
SPBC685.02
SPBC887.14c
SPBC9B6.02c
SPBP19A11.06
SPBP8B7.14c
SPCC1020.14
SPCC1235.05c
SPCC1259.04
SPCC1620.09c
SPCC1672.08c
SPCC1682.02c
SPCC330.01c
SPCC338.08
SPCC622.08c
SPCC622.09
SPCC895.03c
SPMTR.01
SPMTR.04

**Comment by ValWood** [comment]
https://github.com/geneontology/go-annotation/issues/1397

**Comment by ValWood** [comment]
These are false positives

SPAC22F3.06c	lon1 false positive
SPBC30D10.17c	smi1 false positive
SPBC16C6.10	chp2  false positive?
SPBC13E7.02	cwf24 false positive
SPBC19C7.10	bqt4  false positive?
SPCC895.03c	sua5  false positive
SPCC1672.08c	tfa2  false positive
SPCC1620.09c	tfg1  false positive
SPCC1259.04	iec3 false positive (no evidence)
SPAC6B12.05c	ies2 false positive (no evidence)
SPAC13D6.02c	byr3 NO EVIDENCE FOR DNA BINDING, ADD TO TICKET
SPAC23G3.04	ies4 false positive?
SPAC19G12.13c	poz1  false positive (bridges 2 DNA binding sub complexes?)
SPBC1778.01c	zuo1  false positive
SPAC17H9.10c	ddb1 (no evidence?)

**Comment by ValWood** [comment]
Midori can you do these some time (no hurry)
SPBC16D10.09	pcn1
SPBP8B7.14c	dpb2
SPAC688.10	rev3
SPBC25H2.13c	cdc20
SPBC14C8.12	rpb8
SPCC1682.02c	mcm3
SPBC685.02	exo5
SPBC4.04c	mcm2
SPBC336.04	cdc6
SPCC338.08	ctp1
SPCC622.08c	hta1
SPCC622.09	htb1
SPAC1834.03c	hhf1
SPAC1834.04	hht1
SPAC19G12.06c	hta2
SPBC1105.11c	hht3
SPBC11B10.10c	pht1
SPBC16G5.12c	top3
SPBC1A4.03c	top2

I will do the rest tomorrow if I can face it....

**Comment by ValWood** [comment]
Antonia a couple for you too
SPMTR.01	mat2-Pc
SPMTR.04	mat3-Mc

**Comment by ValWood** [comment]
DOne
SPAC10F6.08c	nht1
SPAC11D3.11c

**Comment by ValWood** [comment]
DONE:

SPAC13F5.07c	hpz2 	IPR001510
SPBC2A9.07c	hpz1   IPR001510
SPAC144.02	iec1  IPR013087
SPAC23E2.02	lsd2  	IPR011991
SPBC146.09c	lsd1 	IPR011991

SPBP19A11.06	lid2  	IPR001606 (has ISS/ISO annotation not recognised)
SPBC19G7.04	SPBC19G7.04  	IPR009071 (has ISS/ISO annotation not recognised)
SPBC30B4.04c	sol1 	IPR001606 (has ISS/ISO annotation not recognised)
SPAC57A10.09c	nhp6  	IPR009071 (has ISS/ISO annotation not recognised)
SPBC28F2.11	hmo1   IPR009071 (has ISS/ISO annotation not recognised)
see https://github.com/pombase/pombase-chado/issues/549

**Comment by mah11** [comment]
> Midori can you do these

Could you please clarify what it means to "do these"? I.e. do what?

**Comment by ValWood** [comment]
In the ticket  title.
Find a DNA binding annotation? (if applicable). Will  most likely be ISS/ISM/IC/TAS if it doesn't have experimental already.
(the  keyword mapping which previously provided the annotation had to be filtered because it contians too many false positives).

**Comment by mah11** [comment]
The ticket title doesn't say whether the list is of things that
- should have DNA binding annotations but don't, or
- do have DNA binding annotations but shouldn't.

That's what needed clarifying. 

I don't add TAS annotations any more.

**Comment by ValWood** [comment]
> I don't add TAS annotations any more.

Good, me neither.

I didn't check yours but I think they probably *should*. I'm guessing you will know better. Quite a few of the ones I eliminated  so far were parts of complexes which bound DNA but were not the DNA binding subunit and were distal to the DNA... others were never even in the nucleus AFAIK, sometimes RNA binding

**Comment by ValWood** [comment]
done helicases....
SPAC2G11.12	rqh1 OK
SPAC17A5.06	ptr8 added
SPAC4H3.05	srs2 OK
SPAC3G6.11	chl1 OK
SPAC29B12.01	ino80 OK
SPAC22F3.03c	rdh54 added
SPAC25A8.01c	fft3 OK
SPAC20G8.08c	fft1 added
SPAC1D4.12	rad15 OK
SPAC11E3.01c	swr1 added 
SPAC1783.05	hrp1 added
SPCC1235.05c	fft2 added
SPBC1198.13c	tfg2 added
SPCC330.01c	rhp16 added
SPBC887.14c	pfh1 added

**Comment by ValWood** [comment]
done
SPAC15A10.03c	rad54  translocase   added
SPBC1826.01c	mot1  ISS http://www.yeastgenome.org/locus/YPL082C/overview#go added ISO
SPAC26A3.03c	rmi1 four-way junction DNA binding  ISS S000005945 added
SPAC31G5.10	eta2  sequence-specific DNA binding  ISS S000000253 added
SPAC23H3.10	ssr2   OK
SPAC144.09c	sfc2  ISS http://www.yeastgenome.org/locus/YPR186C/overview#go
SPBC409.12c	stn1  ISS  single-stranded telomeric DNA binding S000002489 added
SPAC6F6.16c	tpz1  PMID: 23299958  TAS added
SPAC13G6.01c	rad8  update ISS to http://www.yeastgenome.org/locus/YLR032W/overview#go added
SPAC20H4.03c	tfs1  RNA polymerase II regulatory region DNA binding  (ISS SGD) added
SPAC1250.07	sfc7   ISS to S000005636  http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0001016 added
SPBC29A3.14c	trt1 telomeric DNA binding ISS SGD (added)
SPBC582.10c	SPBC582.10c ISS to SGD,  (added)
SPBC17D11.06	spp2  contributes to single-stranded DNA binding  ISS S000001528 (added)

waiting to hear back from SGD about
SPBC1703.02	rsc9 SGD mentions DNA binding, but no annotation
(description had DNA binding, but no DNA binding annotation)

**Comment by mah11** [comment]
SPAC1834.03c hhf1	added ISS with InterPro:IPR001951
SPAC1834.04 hht1	added ISS with InterPro:IPR000164
SPAC19G12.06c hta2	added ISS with InterPro:IPR002119
SPAC688.10 rev3	added ISS with InterPro:IPR006134
SPBC1105.11c hht3	added ISS with InterPro:IPR000164
SPBC11B10.10c pht1	added ISS with InterPro:IPR002119
SPBC16D10.09 pcn1	added ISO S.c.
SPBC16G5.12c top3	added ISS with InterPro:IPR013497
SPBC1A4.03c top2	added ISS with InterPro:IPR002205
SPBC25H2.13c cdc20	added ISO S.c.
SPBC336.04 cdc6	added ISS with InterPro:IPR006134
SPBC4.04c mcm2	added ISO S.c.
SPBC685.02 exo5	added IC from GO:0045145
SPBP8B7.14c dpb2	added ISO S.c.
SPCC1682.02c mcm3	added ISO S.c.
SPCC338.08 ctp1	added ISO S.c.
SPCC622.08c hta1	added ISS with InterPro:IPR002119
SPCC622.09 htb1	added ISS with InterPro:IPR000558

SPBC14C8.12 rpb8	not annotated - it's a subunit of all three nuclear RNA polymerases, but I haven't found anything experimental that addresses whether it's one of the subunits that makes contact with DNA. It's got a match to IPR012340, which has the name "Nucleic acid-binding, OB-fold", but the InterPro entry doesn't have any GO annotations, and the "nucleic acid" could be DNA or RNA.

**Comment by ValWood** [comment]
@Antonialock 
should these ahve DNA binding annotation? I didn't add it as  is there something odd here that we house all the annotation on the genome copy  rather than the mating type contig?

SPMTR.01 mat2-Pc
SPMTR.04 mat3-Mc

**Comment by Antonialock** [comment]
So the sequenced reference strain only contains M specific mating information - The P information (mat2 locus) has been deleted. The M information exists at mat1 (transcriptionally active) and mat3 (transcriptionally silent).

the gene at mat3 SPBC1711.02 has this annotation as a NAS (I guess this can be removed since the gene is never expressed from the silenced locus? When it exists at mat1 it is called SPBC23G7.09).

The MTR is just the whole mating type region (including mat1, mat2, and mat3) so it duplicates the silenced gene eg SPMTR.04=SPBC1711.02 
BUT it adds the P specific information at mat2 eg SPMTR.01

since we don't have  gene pages for the P specific genes when they are at the transcriptionally active mat1 locus, I guess we need to bung the P-specific annotations at least onto the MTR contig.

does that make sense?

**Comment by ValWood** [comment]
yep

I removed the NAS annotation for  SPBC1711.02 in external data...still need to remove any in Artemis....

**Comment by ValWood** [comment]
removed from SPBC1711.02  in artemis.

Not done anything with the mating-type contig. @Antonialock  could you do that?
