### ISSUE TITLE
migrate jira  issues to  Pombase website github

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#931]
Put all new tickets on here (unless sensitive)

Migrate old tickets to give the new person nice clear tickets.
Starting with  most urgent.

We have a couple of months for this  I envisage....

**Comment by ValWood** [comment]
This is a nice Friday afternoon task. We need to begin to migrate the existing tickets and make nice clear new tickets on the GitHub website tracker.
Beginning with the  highest priority tickets. We  won't bother with  the ones referred to Ensembl, or Blue sky at least early one. The important thing is to make sure that the most urgent tickets are there when the new person is in post.

We should all chip in with this one, but guess who  I'm going to assign it to....

**Comment by Antonialock** [comment]
is this a simple-but-tedious copy+paste exercise? 

I don't know if we can be more clever, or if you want any special "formatting" where there is more than one post.

**Comment by ValWood** [comment]
Nope unfortunately. Some of the tickets are so commented and convoluted that it isn't fair to inflict them on  a new hire. I think we should re-iterate each ticket clearly, and link to the old ticket.
Some might be  simple cut and paste.

**Comment by Antonialock** [comment]
That's fair enough :p

**Comment by mah11** [comment]
done

**Comment by kimrutherford** [comment]
> done

Thanks!
