### ISSUE TITLE
- telosome  missing members

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#942]
I wonder if there is more then one term for this...

http://www.pombase.org/spombe/related/GO:0070187

**Comment by mah11** [comment]
I don't see anything else similar in GO ...

**Comment by ValWood** [comment]
OK Definition: ..... The complex contains ......

and Pot1, Tpz1, Ccq1, Poz1, Rap1, Rif1, Rif2and Rap1 in Schizosaccharomyces......." [GOC:expert_mf, GOC:mah, GOC:vw, PMID:18828880]

**Comment by ValWood** [comment]
missing 4 subunits

**Comment by ValWood** [comment]
refer to 
https://github.com/geneontology/go-ontology/issues/12483

**Comment by ValWood** [comment]
You'll probably be able to close this one anyway when telomere genes are done?

**Comment by mah11** [comment]
probably, yeah ... but telomere genes won't really be on my radar for a while yet ...

**Comment by ValWood** [comment]
well "low priority" means in the next couple of years- possibly,  
I reckon.....

**Comment by ValWood** [comment]
Update
https://www.pombase.org/term/GO:0000783

rif1 and rif2 are not annotated to "shelterin" but they are annotated to
nuclear telomere cap complex (GO:0000783)
do these need to be more specific, or does the def of shelterin need to change?

A nuclear telomere cap complex that is formed by the association of telomeric ssDNA- and dsDNA-binding proteins with telomeric DNA, and is involved in telomere protection and recruitment of telomerase. The complex is known to contain TERF1, TERF2, POT1, RAP1, TINF2 and ACD in mammalian cells, and Pot1, Tpz1, Rap1, Rif1, Rif2 and Taz1 in Schizosaccharomyces. Taz1 and Rap1 (or their mammalian equivalents) form a dsDNA-binding subcomplex, Pot1 and Tpz1 form an ssDNA-binding subcomplex, and the two subcomplexes are bridged by Poz1, which acts as an effector molecule along with Ccq1.

**Comment by ValWood** [comment]
@mah11

**Comment by mah11** [comment]
Well, I'm a little confused myself, because most - but annoyingly not quite all - of the papers I've just been skimming through don't count Rif1 as a shelterin subunit. But I'm leaning towards having the GO:0070187 def changed; we don't even have a pombe gene called rif2.

PMID:26063574 and PMID:27264871 are among those that list Taz1, Rap1,  Poz1, Pot1 and Tpz1 as shelterin parts; PMID:28096402 leads off with "The Shelterin component Rif1 has ..." >:-P

**Comment by mah11** [comment]
aha - Rif1p and Rif2p are annotated as shelterin in *S. cerevisiae*, not pombe. And the "Schizosaccharomyces" looks like a plain old typing/pasting mistake when the def was last updated:

https://github.com/geneontology/go-ontology/issues/10748

That should be trivial for them to fix. I'll open a ticket.

**Comment by mah11** [comment]
https://github.com/geneontology/go-ontology/issues/16881
