### ISSUE TITLE
geranylation pathway  update

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#945]
I notice that geranylation pathway have

/GO="aspect=P; term=protein targeting to plasma membrane; GOid=GO:0072661; evidence=IC; db_xref=GO_REF:0000001; from=GO:0018342; date=20110208"

but this should be 
maintenance of protein location in plasma membrane

(possibly this could be a parent of the gerenylation term in GO but I'll look into that later. 

For now I changed

cwg2 to

/GO="aspect=P; term=maintenance of protein location in plasma membrane; GOid=GO:0072660; evidence=IC; db_xref=GO_REF:0000001; from=GO:0018342; date=20160609"

**Comment by mah11** [comment]
remember that IC annotations should use the same db_xref as the "from" annotation, not GO_REF:0000001

**Comment by ValWood** [comment]
Actually this abstract says that it is involved in targeting.
http://www.ncbi.nlm.nih.gov/pubmed?term=9781874

Need to establish if involved in targeting, or anchoring once it gets there, or both and add appropriate  ancestors to GO terms.

**Comment by ValWood** [comment]
I don't think we'll ever be able to sort out any targetting stuff until GO do

**Comment by ValWood** [comment]
All geranylation have protein targeting to plasma membrane, which is correct.
