### ISSUE TITLE
SPBC713.13 has no product

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#946]
Also check others. `Needs a log report.

**Comment by ValWood** [comment]
There are 3, fixing now....
SPBC713.13
SPAC823.02
SPAPB1A11.05

**Comment by ValWood** [comment]
OK these are fine in Artemis, with products. Opening a jira ticket....

@kimrutherford   does chado report missing products in logs if they were missing?

Val

**Comment by kimrutherford** [comment]
>  does chado report missing products in logs if they were missing?

It should do.  The loader should say "no product for ..." in the logs.

But: there is no annotation for those three genes in Chado v60 and the product is missing.  So it looks like a loader bug.  There is no annotation in v59 either.  v58 seems OK.
