### ISSUE TITLE
possible deletion allele fix list

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#951]
Some may be OK, some may need fixing

From
https://github.com/pombase/canto/issues/1162#issuecomment-227117944

mug80delta | clg1
mrpl6delta | mrpl1602
ptr6delta | taf7
mrpl11delta | mrp11
mrps5delta | mrp5
mug82delta | pth4
sod2delta | nhe1
mrpl16delta | mrpl1601
fub2delta | uba2
pmc1delta | med14
eic1delta | mis19
eic2delta | mis20
mug55delta | fzr3
gcg1delta | ggc1
matPidelta | mat2-Pi
gld1-delta | gld1
tup11-delta | tup11
dak1-delta | dak1
dak2-delta | dak2
scr1-delta | scr1
sts1delta | erg4
pub1-WWdelta | pub1
CDTdelta | hrq1

pho1-ncRNAdelta | pho1

- [x] mrx1delta | mxr1 (fixed below)

ppg1delta | ppa3
abc1delta | ybt1
php2 delta | php2
sks1-delta | rpn11
delta/delta | rhp6
dil1delta | dhc1
atg18delta | atg1801
mug179delta | atg1802
atg14delta | vps38
lrp1delta | sog2
cdc27partial_delta | cdc27
cdt1-PIP28delta | cdt1
rad30delta | eso1
clr4delta | sir2
rad22delta | rad52
mat1-Mmdelta | mat1-Mi
matPcdelta | mat2-Pc
P3nmt1-egt1 egt2delta | egt2
scn1delta | scn3
972-tsc1delta | tsc1
972-tsc2delta | tsc2
nup189n-delta | nup189
nup189c-delta | nup189
xba1-xba1delta | ste4

**Comment by ValWood** [comment]
Note, I am leaving the ones  where the mutant was explicity named like this in the publication. Just adressing those which are automatically generated form screens,b ut name has changed, or typos...


Actions

mug80delta | clg1       change to clg1 ? (PMID:23874875)
 mug82delta change to  pth4 ? (23892058)


These are from Hayles et al, and  need to work out how to fix these...(oddly the  earlier Kim dataset is corrected?)
mrpl11delta | mrp11
mrpl6delta | mrpl1602 change to  mrpl1602 
mrps5delta | mrp5
mug82delta | pth4
mrpl16delta | mrpl1601
fub2delta | uba2
mug55delta | fzr3

Possible typos!
gcg1delta | ggc1

These need the hyphens precedeing the 'delta' deleting
gld1-delta | gld1
tup11-delta | tup11
dak1-delta | dak1
dak2-delta | dak2
scr1-delta | scr1


@Antonialock  need feedback on this one? matPidelta | mat2-Pi

@Antonialock 
Is this how there were named in the paper?
rrm1delta | mug28
rrm2delta | mug28
rrm3delta | mug28
rrm1delta rrm2delta | mug28
rrm1delta rrm3delta | mug28
rrm2delta rrm3delta | mug28
if not, i'm not keen on the naming, they look like single and double mutant genotypes but they are domain mutants

**Comment by ValWood** [comment]
this one sounds like a ncRNA associated with pho1  was deleted.
If this isn't how it was named in the paper pho1-ncRNAdelta | pho1
consider pho1-5'UTRdelta
(also should it be a partial deletion, not a deletion?)

**Comment by ValWood** [comment]
php2 delta | php2  remove space

**Comment by ValWood** [comment]
delta/delta | rhp6 is this a diploid?

**Comment by ValWood** [comment]
dil1delta | dhc1
this might be attached to the wrong gene
dil1 is http://www.pombase.org/spombe/result/SPAC458.04c

**Comment by ValWood** [comment]
These appear to be fixed already
atg14delta | vps38
lrp1delta | sog2

**Comment by ValWood** [comment]
clr4delta | sir2
This is wrong clr4 and sir2 are different genes. Need to check what it should really be

**Comment by ValWood** [comment]
Not sure if this gene is/should be called scn1 or scn3. it uses both a  bit randomly.....scn1delta | scn3

**Comment by ValWood** [comment]
remove 972? unless reason to keep?
972-tsc1delta | tsc1
972-tsc2delta | tsc2

**Comment by ValWood** [comment]
xba1-xba1delta | ste4
looks like a deleted region (between restriction sites) rather than a 'deletion'
change type?

**Comment by Antonialock** [comment]
mug28:

![screen shot 2016-09-06 at 11 53 55](https://cloud.githubusercontent.com/assets/12727506/18271178/bbe4e7de-7428-11e6-853b-b7cc1c30a779.png)

**Comment by Antonialock** [comment]
for tsc1 it is quite important to record the background as far as I remember - TOR mutants behave really differenly in strains that are not prototrophs

**Comment by mah11** [comment]
yeah, but the deletion allele is still the deletion allele; the fact that the background is important doesn't mean it's not still, well, the background

**Comment by mah11** [comment]
or maybe it's even worth "promoting" alleles that we'd normally put in the background to parts of multi-allele genotypes for TOR

**Comment by Antonialock** [comment]
yep

**Comment by ValWood** [comment]
closing, will start with a clean slate here:
https://github.com/pombase/pombase-chado/issues/576

and figure out what  what needs to be fixed

**Comment by ValWood** [comment]
> for tsc1 it is quite important to record the background as far as I remember - TOR mutants behave really differenly in strains that are not prototrophs

also did the 972-tor... predate the availability of the "background" field?
