### ISSUE TITLE
find EXP  PMID for these

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#952]
There are 4 annotations in the  pombase-go-substrates for esyN  with GO refs, we should try to replace these....

SPAC27E2.09	SPAC24B11.06c	GO_REF:0000001
SPAC13A11.01c	SPAC1F7.04	GO_REF:0000024
SPCC737.06c	SPAC22F3.10c	GO_REF:0000024
SPBC14C8.04	SPBP35G2.07	GO_REF:0000024

**Comment by Antonialock** [comment]
SPAC27E2.09 - removed (sty1 is not a substrate, it just transmits a signal trhough to sty1)

**Comment by Antonialock** [comment]
SPAC13A11.01c fixed

**Comment by ValWood** [comment]
Re 
> SPAC27E2.09 - removed (sty1 is not a substrate, it just transmits a signal trhough to sty1)

How do we capture this directional link...so we need another relation?

**Comment by Antonialock** [comment]
it's just a pathway, they are linked in the sense of target of MFs and shared BPs

**Comment by ValWood** [comment]
so SPAC27E2.09-> has_target "some other gene product" -> has target sty1

**Comment by Antonialock** [comment]
yeah

**Comment by Antonialock** [comment]
SPCC737.06c SPAC22F3.10c GO_REF:0000024
SPBC14C8.04 SPBP35G2.07 GO_REF:0000024

these have not been published
