### ISSUE TITLE
esyN updating

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#960]
I need to figure out why cdc2 targets drc1 and cdc18  aren't appearing in DNA replication

**Comment by mah11** [comment]
That link is for the DNA repair graph, and neither gene is annotated to repair. I see both drc1 and cdc18 on the DNA replication graph.

**Comment by ValWood** [comment]
doh

**Comment by ValWood** [comment]
There is still a problem
cdc2 has substrate cdc18 (both are annotated to replication)
cdc2 has_substrate drc1 (both are annotated to replication)

So in this graph we should see cdc2 (I  still cant see cdc2)
with directional arrows to both cdc18 (present) and drc1 (I see drc1 but it is only connected to rad24).

I'll track through the  files and see if there is a problem....

**Comment by ValWood** [comment]
no appeared yet, not sure why....

**Comment by ValWood** [comment]
Another example
SPAC1782.09c
SPAC24H6.05
have an effector /target  clp1 has substrate cdc25 but not recognised.

**Comment by ValWood** [comment]
So there a[[ear to be problems at esyN end and at pur end. I'll  wait to submit esyN ticket until our end files are fixed (I think its likely esyN is not updating)

**Comment by ValWood** [comment]
check why rfc2 rad17 do not appear in interaction map (esyN ) as a complex 
from
https://github.com/pombase/curation/issues/1057

**Comment by ValWood** [comment]
pretty sure everything is fixed now.....
