### ISSUE TITLE
cdc2 annotation and QC

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#963]
From

https://github.com/pombase/curation/issues/845

continue tidying modification section

In fact, cdc2p is phosphorylated primarily on two residues in fission yeast, Y15 and T167 (Gould and Nurse 1989; Gould et al. 1991), although T14 phosphorylation can also be detected under certain circumstances
so if Y15 is the only tyrosine phoshorylated, this must always be what was assayed here?
Tryptic cleavage of 32P-labeled Schizosaccharomyces pombep34cdc2generatedonlytwophosphopeptides,termed
1 and 2 (Gould and Nurse, 1989). Phosphopeptide 1 contained phosphorylated Tyrl5 and phosphopeptide 2 contained phosphothreonine (Gould and Nurse, 1989).

This is prior knowledge so we can assume that in subsequent papers they knew which residue they were assaying.
- [x] Can we fill this in for others?
  No, we can't really do this

**Comment by ValWood** [comment]
CDK (cyclin dependent protein kinase) is inactivated upon cyclin degradation through polyubiquitination by 20S APC/ cyclosome and proteolysis by 26S proteasome (Glotzer et al. 1991; Irniger et al. 1995; King et al. 1995; Zachariae et al. 1996).

**Comment by ValWood** [comment]
transferred from
https://github.com/pombase/curation/issues/715
check if more reg of BPs can be added to cdc2 kinase_activity direct targets using the part_of relation

**Comment by ValWood** [comment]
relation on the cdck/kinase complex binds substrate

A couple of target_Ofs have the relation "binds"

these are
ribonucleotide reductase inhibitor
and
cyclin dependent protein kinase regulatory subunit

It seems that these would be better as
regulated_by
(or even inhibited_by)

What is it about the original annotations which makes them be classed as "binds" and could they get a more "directional" relationship?
vw
=====
These come from the extensions on the 'protein complex binding' term in
http://curation.pombase.org/pombe/curs/f1afdd21aae916be

There was an email exchange about it, about a year ago. It wasn't on any list, but I saved them and can paste here and/or forward if you want.

Original comment by: mah11

**Comment by ValWood** [comment]
cdc2 PMID:6526270 uniprot has this paper for allele cdc2-4w C67F (we have 'unspecified')||

**Comment by ValWood** [comment]
cdc2 PMID:8557037 mcs6 substrate cdc2

**Comment by ValWood** [comment]
Follow on from
https://github.com/pombase/curation/issues/923

I added 
changed extension to: has_substrate PomBase:clp1 , directly_inhibits GO:0004865 , part_of GO:0001100"
to 3472d1b25692f40c
but this is not allowed

Is now
It is now: 
has_substrate PomBase:clp1 
part_of GO:1905183 
happens_during GO:0001100


I'm trying to establish with go what relationship to use when 
we want to capture on for example a protein kinase activity is inhibiting or activating (so that we don't have concurrent annotation fro the same experiment to phosphatase inhibitor, and the like.

I talked about it with them already but I forgot what the outcome was. I know it can't be "directly inhibits"
because you inhibit an activity not a gene product?


al: so is GO:1905183
"negative regulation of protein serine/threonine phosphatase activity"?

vw: I want to avoid this....if possible, we want to represent onMF not as BP, its direct so this has a broader meaning

**Comment by Antonialock** [comment]
> This is prior knowledge so we can assume that in subsequent papers they knew which residue they > were assaying

I'm not sure I'm comfortable with this....

**Comment by ValWood** [comment]
This has both +ve and -ve regulation of attachment...it could be different contexts (one might be during chromosome loss), anyway it looks odd and  the terms might require further disambiguation?

**Comment by ValWood** [comment]
do these add anything, if we have has_input on MF?
![phosphorylation](https://cloud.githubusercontent.com/assets/7359272/17300751/96aeface-580b-11e6-9730-85901056b83e.jpg)

**Comment by Antonialock** [comment]
do you mean the BP or the extension?

**Comment by ValWood** [comment]
both....

**Comment by ValWood** [comment]
so we already have above

	cyclin-dependent protein serine/threonine kinase activity
has substrate dis2, involved in negative regulation of phosphoprotein phosphatase activity

So, we know that cdc2 directly negatively regulates dis2 (inhibitory phosphorylation).
What we really want to do is capture this on the MF with  the appropriate relation
directly_inhibits (remember the GO annotation consistency exercise discussion this week?)

So it would b, more simply
cyclin-dependent protein serine/threonine kinase activity directly_inhibits dis2

What we really want is to know which *process* this is regulating and link this by involved_in instead 
 chromosome segregation? DNA damage checkpoint?  cell polarity?

if we know it inhibits dis2 *activity* the fact that its  negative regulation of protein phosphatase is implicit, and its only really information about the function, not the biological role.


Then this annotation 
	negative regulation of phosphoprotein phosphatase activity	
regulates dis2	IDA		Yamano H et al. (1994)
is redundant (its saying exactly the same thing as the MF annotation, but less precisely)

This is only  for the modification terms.
We would need to  explicitly add for *real processes* like 'negative regulation of chromosome segregation"

**Comment by ValWood** [comment]
The protein kinase that phos- phorylates the T loop threonine has been termed CAK for CDK-activating kinase (reviewed in Solomon 1994). In ®ssion yeast, this kinase is most probably composed of two subunits, a catalytic subunit encoded by crk1/ mop1 and a cyclin subunit encoded by mcs7 (Buck et al. 1995; Damagnez et al. 1995)."

Find evidence to support
crk1 -> cdc2  T167 phosphorylation.

**Comment by ValWood** [comment]
some cdc2 stuff to follow up

 Complex formation is promoted by cdc2 phosphorylation at Thrl67 (Gould et al., 1991)
The cdc2/cdc13 heterodimer exists as an inactive complex during G2 as a result of cdc2 phosphorylation at Tyrl5 (Gould and Nurse, 1989)
The contribution of the cyclin B subunit to cdc2 kinase activity during mitosis is not fully understood but it may determine the subcellular localization of cdc2 or cdc2  substrate specificity (Booher et al., 1989; Galaktionov and Beach, 1991).
A second protein, directly interacts with cdc2  in S.pombe (Hayles et al., 1986a; Brizuela et al., 1987). The function of  suc1  is enigmatic. Deletion of the suc1 gene is lethal, arresting cells with chromosomal abnormalities in late M phase. Overexpression of suc1  delays M phase entry by inhibiting cdc2 kinase activation (Hayles et al., 1986b; Hindley et al., 1987" Dunphy and Newport, 1989). suc1 does not contain a p34 protein kinase recognition sequence motif (Pearson and Kemp, 1991). Therefore, it probably does not inhibit cdc2 kinase activity through a pseudosubstrate mechanism as seen in a number of other protein kinases, most notably the inhibition of cAMP-dependent protein kinase (cAPK) by its naturally occurring inhibitor protein, PKI (Taylor et al., 1990).

**Comment by ValWood** [comment]
-  [ ] check protein import into nucleus. Looks dodgy and I can't immediately see the phenotype that the GO term is derived from fa51a7649e995191/ro
...it'll be "regulation of" anyways....

**Comment by ValWood** [comment]
- [ ]  substrate cig2/Cdc2 has been reported to phosphorylate MBF on its DNA-binding subunit Res1 at residue S130  (not sure of source)

**Comment by ValWood** [comment]
- [ ] when does csk1 phosphorylate and activate cdc2?????

**Comment by ValWood** [comment]
- [ ]  the cdc2  BP annotation 
"negative regulation of ubiquitin ligase activity" looks like it should be an MF  annotation with substrate "ste9/srw1 is negatively regulated by cdc2-dependent protein phosphorylation" part_of  negative regulation of whatever process the APC is activating here....
