### ISSUE TITLE
New PSI-MOD relation "inhibits activity"

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#966]
can we add the relation "inhibits activity"? (opposite to "required for activity") for protein modifications? 

in my example the protein is a dual kinase/phosphatase and the modification inhibits its phosphatase activity

I can add it I just wanted to check that you don't see any problems with this relation

**Comment by Antonialock** [comment]
actually we can hold off for this...I'm not sure I'm comfortable making this extension in this case. Will reopen if I change my mind.

**Comment by ValWood** [comment]
I think this is analogous to what I wanted to do
I wanted to  be able to capture on the kinase or phosphatase whether the modification is activatory or inhibitory.....This will be important information for network building....

Its one of the things in this ticket
https://github.com/pombase/curation/issues/963

**Comment by Antonialock** [comment]
ok..re-open this one?

**Comment by ValWood** [comment]
opened as a reminder...

**Comment by ValWood** [comment]
I opened a ticket for this  on the GO tracker so we don't need this one:
https://github.com/geneontology/annotation_extensions/issues/70
