### ISSUE TITLE
assayed using config "protein secretion"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#972]
Cant add assayed_using

**Comment by mah11** [comment]
"Protein secretion" itself is a GO BP term, and therefore wouldn't allow any assayed_using extensions.

If there's a protein secretion FYPO term that doesn't offer "assayed protein" I'll need to know which specific one(s). I fixed the config for "normal protein secretion" in https://github.com/pombase/fypo/issues/2724, and "abnormal protein secretion" already had an is_a path that makes the extension options appear, so they all should have them now. If any don't, I'll have to see if I can figure out why.

**Comment by ValWood** [comment]
oh sorry it was
FYPO:0001945	normal protein secretion
although it might be odd to use "assayed using" on normal terms? 

This was using the standard secretion assay  with pho1, everyone uses this assay, but it could turn out that   different  targets are not normal. I also think we probably recorded this before judging by:
http://www.pombase.org/spombe/result/SPBP4G3.02#recipext

**Comment by mah11** [comment]
> oh sorry it was
> FYPO:0001945 normal protein secretion

That should be OK following https://github.com/pombase/fypo/issues/2724; pester Kim if it isn't.

> although it might be odd to use "assayed using" on normal terms? 

Why? Assay what happens to something, see that it's normal, say so, including which gene/transcript/protein it was. Looks fine to me.

**Comment by ValWood** [comment]
all good
