### ISSUE TITLE
misc annotations

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#974]
At the moment I add misc annotations to datasets with genome-wide info
i.e.
/controlled_curation="term=misc, chromatin binding profiling; db_xref=PMID:xxx; date=yyy"

just a heads up for pulling datasets into the genome browser

(there are some others i.e. deletion mutant expression profiling and WT overexpression expression profiling, I couldn't find where these are documented...are they?)

**Comment by ValWood** [comment]
I don't think that they are documented....

@kimrutherford , is there a way we can see all of the curation of type misc? I think there is a way to get to lists like this in Chado, but I can't remember how to.....

**Comment by kimrutherford** [comment]
> is there a way we can see all of the curation of type misc?

Is this what you need?:
  https://curation.pombase.org/pombe/view/object/cv/misc?model=chado
(click a term name to get a list of features)

The main Chado entry point is here:
  https://curation.pombase.org/pombe/chado/

**Comment by ValWood** [comment]
Exactly! Thanks!

**Comment by ValWood** [comment]
Step 1.
delete any misc annotations which are now captured by multigene phenotypes etc. I see a lot of stuff in this list which could be captured  by an existing protocol, now that we know how.

Step2.   Do the papers   where the annotations relate to genetic interactions, and delete the misc.

Step3. See if we need to 
standardize  and or document what is remaining

**Comment by ValWood** [comment]
This is related, its about adding some meta data about the expression profiles
https://github.com/pombase/curation/issues/550

**Comment by ValWood** [comment]
Good "curation jamboree" fodder

**Comment by ValWood** [comment]
superseded by
https://github.com/pombase/curation/issues/550
which will "get rid" of the expression profiling ones.

and

curators  will address:
https://github.com/pombase/curation/issues/1328
probably on a curator call (but feel free to scan the list and add obvious resorting)

**Comment by ValWood** [comment]
@Antonialock Antonia from this ticket you need to make sure that the ones which are not "browser fodder" have
https://github.com/pombase/curation/issues/550

and the others have
https://github.com/pombase/curation/issues/1327

**Comment by ValWood** [comment]
Re
>is there a way we can see all of the curation of type misc?
Is this what you need?:
https://curation.pombase.org/pombe/view/object/cv/misc?model=chado
(click a term name to get a list of features)

How can I see all curation types? I tried removing the URL specificity but I got an error. I wanted to see a list of all non obo Cv's

**Comment by ValWood** [comment]
superseded by

https://github.com/pombase/curation/issues/1326
https://github.com/pombase/curation/issues/550
https://github.com/pombase/curation/issues/1328

**Comment by mah11** [comment]
> How can I see all curation types? 

https://curation.pombase.org/pombe/view/list/cv?model=chado

(starting from main admin page at https://curation.pombase.org/pombe/chado/, click "controlled vocabularies")
