### ISSUE TITLE
why has the number of NAS increased in the current gaf?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#982]
In the current gaf the number of NAS has increased from  1069 (and has been falling steadily) back up to 1264.
This usually indicates that a parentage has disappeared from somewhere which has made some normally suppressed higher level NAS reappear....try to establish what caused the increase....

**Comment by mah11** [comment]
this looks a bit suspicious (from chado_checks):

check for annotations from Canto - FAILURE:  expected >= 13000 but got 0
check that we have enough annotations - FAILURE:  expected >= 168000 but got 150348

look again after the Canto load is working, and only worry if the NAS increase still happens then

**Comment by mah11** [comment]
Well, now Canto annotations are getting in, but I've opened https://github.com/pombase/pombase-chado/issues/557 because GAF filtering looks completely broken.

**Comment by ValWood** [comment]
fixed by filtering fix
