### ISSUE TITLE
After update check situation with %  on penetrance

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#986]
nuc1 has on gene page
![nuc1](https://cloud.githubusercontent.com/assets/7359272/17177483/8721236c-5409-11e6-9dcb-e9a2bd98caae.jpg)

**Comment by mah11** [comment]
relevant jira ticket: https://www.ebi.ac.uk/panda/jira/browse/PB-2619

**Comment by ValWood** [comment]
yeah % is still missing, but not a lot we can do for now....its on jira
