### ISSUE TITLE
check kap109 /no spores germinate

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#988]
kap109 has
viable spore population (I don't know what this means, although I appear to have requested the  the term

I also has inviable vegetative cell population for the same phenotype.

I guess it just means that the cells germinate,  and then die? but isn't this an odd term?

**Comment by Antonialock** [comment]
> kap109 has viable spore population (I don't know what this means

We wanted to be able to distinguish populations of spores that cannot germinate, from population of spores that can germinate but not go on and form colonies.

This is because of the cases where genes are annotated to "inviable vegetative cell population" but actually it is because the spores were inviable, the vegetative cells are fine.

Conversely, for kap109 you can see that the spores are completely fine, the problem is in the vegetative phase.

**Comment by ValWood** [comment]
but some spores don't germinate. According to Jacky its a mixture of inviable spores, spores which germinate and die.
Inviable spore population seems wrong in this case?

**Comment by ValWood** [comment]
Some *must* germinate as Jacky saw abnormal septum morphology?

**Comment by ValWood** [comment]
deleted previous comment. I mean not all spores germinate. Some are inviable.

"viable spore population" as a population phenotype looks incompatible with a cellular phenotye of  "inviable spore"
That's why I asked what it meant...

**Comment by Antonialock** [comment]
Well, the 90 in h90 comes from that only 90% of the spores from that strain would germinate

**Comment by ValWood** [comment]
To me, "inviable spore population" would mean "no spores germinate"

**Comment by Antonialock** [comment]
yes "inviable spore population" = "no spores germinate"

**Comment by ValWood** [comment]
OK got it (I think).
we need  to add this for those where this for eg:

inviable after spore germination with normal, unseptated germ tube morphology
and all the others which are inviable after spore germination...

and everything viable?
etc

**Comment by ValWood** [comment]
I can see we would want to capture "inviable spore population" for those which can't sporulate , but how useful is the term  "viable spore population" (its very annotation incomplete based on current knowledge).

**Comment by ValWood** [comment]
Lets leave for now, we'll discuss...needs linking to the ticket  about finding the list of mutants which cant sporulate but can grow vegetatively (Henry Levin's paper?)

**Comment by ValWood** [comment]
transferring to https://github.com/pombase/curation/issues/448
