### ISSUE TITLE
SPCC1620.08 succinate ligase

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#989]
5 minute task.

Find out if this is DGP forming. If so, (i) change the ISS ii) ask SGD to make a more specific annotation-(this will suppress the IEA). Otherwise  get the mapping  fixed (and add to filtered mappings)

**Comment by Antonialock** [comment]
PMID:9874242 
"The yeast succinyl-CoA ligase was shown to utilize ATP but not GTP for succinyl-CoA synthesis."

**Comment by Antonialock** [comment]
I put up 2 issues on the go tracker for this
https://github.com/geneontology/go-annotation/issues/1423
and 
https://github.com/geneontology/go-annotation/issues/1422

i also emailed uniprot helpdesk about ticket 1422

also added 
GO:0004776 succinate-CoA ligase (GDP-forming) activity 
to filtered GO mappings

it took almost 15 minutes to do all this so your time estimate is out by a factor of 3 :-)

**Comment by ValWood** [comment]
I can do it in 5 :)

**Comment by Antonialock** [comment]
I could definitely not
1. look up a gene page to get a feel for a gene I've never really looked at before
2. find a reference supporting/disclaiming a GO term 
3. put up 2 tracker tickets
4. write an email
5.add the term to the filtered mappings
6. update this issue

in 5 mins!

So either I'm slow or you are a time optimist :p
