### ISSUE TITLE
quick structure papers, grab them while you can...

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#992]
PMID:22405003
Title:	Mechanistic insights into the activation of Rad51-mediated strand exchange from the structure of a recombination activator, the Swi5-Sfr1 complex.

more  to be added shortly....would be good to get them out of my 'needs assigning' list so I don't keep  going back to them, even if not curated soon....

**Comment by ValWood** [comment]
PMID:22437499
Title:	Structure of the mitotic checkpoint complex.
Authors:	Chao WC, Kulkarni K, Zhang Z, Kong EH, Barford D

**Comment by ValWood** [comment]
this one is cryo EM
	PMID:26804377
Title:	The architecture of the Schizosaccharomyces pombe CCR4-NOT complex.
Authors:	Ukleja M, Cuellar J, Siwaszek A, Kasprzak JM, Czarnocki-Cieciura M, Bujnicki JM, Dziembowski A, Valpuesta JM

**Comment by ValWood** [comment]
PMID:27183195
Title:	Structure of the Dcp2-Dcp1 mRNA-decapping complex in the activated conformation.
Authors:	Valkov E, Muthukumar S, Chang CT, Jonas S, Weichenrieder O, Izaurralde E

(we actually have a 'stucture' triage class, so I will  put them there for easy location. I forgot about this as it doesn't appear in the reports list...)

**Comment by ValWood** [comment]
PMID:25815904
Title:	Contribution of dihydrouridine in folding of the D-arm in tRNA.
Authors:	Dyubankova N, Sochacka E, Kraszewska K, Nawrot B, Herdewijn P, Lescrinier E

**Comment by Antonialock** [comment]
I all except 
 Structure of the mitotic checkpoint complex. (you said you took it)
and 
Contribution of dihydrouridine in folding of the D-arm in tRNA. (I relabeled this as structure, probably better to deal with the RNA ones later anyway).
