### ISSUE TITLE
IEA mappings to primosome

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#998]
I try to  Keep IEAs out of the complex file as a check.

Two IEA annotations  to
GO:1990077	primosome complex	IEA	UniProtKB-KW:KW-0639	GO_REF:0000037	2
 have crept in

Spp1&2
Is this correct, and if it is should  alpha DNA polymerase:primase complex be part of it?

**Comment by mah11** [comment]
see https://github.com/geneontology/go-ontology/issues/12575

**Comment by mah11** [comment]
sorted (once it all bubbles through the various pipelines) by taxon restriction on GO:1990077
